### ISSUE TITLE
writeup/DOI

### ISSUE THREAD

**Issue by ttriche** [PoisonAlien/maftools#1]
This is a great toolkit you have assembled.  Are you planning to write it up, deposit a preprint, submit to BioC, or get a DOI for your repository?  It is not a trivial amount of work and I would like to cite you for it.

**Comment by PoisonAlien** [comment]
Hi, 
Thank you for your kind words. Yes, I am planning to submit it to bioconductor as I am still adding some more functions, and I think in another couple of days I should finish it. I wasn't aware of DOIs for github repositories, thanks for the suggestion, I will add it soon.

**Comment by PoisonAlien** [comment]
Hi, 
Maftools preprint is up on [bioRxive](http://biorxiv.org/content/early/2016/05/11/052662).
