### ISSUE TITLE
Maftools is not available for R version 3.4.0

### ISSUE THREAD

**Issue by danablanc** [PoisonAlien/maftools#100]
Hi!

I'm trying to install maftools. I have R version 3.4.0, according to https://bioconductor.org/packages/release/bioc/html/maftools.html it should be sufficent. 
Nevertheless, I get the error message mentioned above - "Maftools is not available for R version 3.4.0"

How can this issue be solved? 
Thank you

**Comment by PoisonAlien** [comment]
Hi,
Could you try the following and see if it works.

```r
source("https://www.bioconductor.org/biocLite.R")
biocLite()
```

Also see this issue: https://support.bioconductor.org/p/91198/
Let me know if this works for you.

**Comment by danablanc** [comment]
Thank you, but it didn't solve the issue. I still get the same message

`> source("https://www.bioconductor.org/biocLite.R")
Bioconductor version 3.2 (BiocInstaller 1.20.3), ?biocLite for help
> biocLite()
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.4.0 (2017-04-21).
Old packages: 'rpart'
Update all/some/none? [a/s/n]: a
trying URL 'https://cran.rstudio.com/src/contrib/rpart_4.1-12.tar.gz'
Content type 'application/x-gzip' length 817720 bytes (798 KB)
==================================================
downloaded 798 KB

* installing *source* package ‘rpart’ ...
** package ‘rpart’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c anova.c -o anova.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c anovapred.c -o anovapred.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c branch.c -o branch.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c bsplit.c -o bsplit.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c choose_surg.c -o choose_surg.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c fix_cp.c -o fix_cp.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c free_tree.c -o free_tree.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c gini.c -o gini.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c graycode.c -o graycode.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c init.c -o init.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c insert_split.c -o insert_split.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c make_cp_list.c -o make_cp_list.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c make_cp_table.c -o make_cp_table.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c mysort.c -o mysort.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c nodesplit.c -o nodesplit.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c partition.c -o partition.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c poisson.c -o poisson.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c pred_rpart.c -o pred_rpart.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c print_tree.c -o print_tree.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c rpart.c -o rpart.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c rpart_callback.c -o rpart_callback.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c rpartexp.c -o rpartexp.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c rpartexp2.c -o rpartexp2.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c rpcountup.c -o rpcountup.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c rpmatrix.c -o rpmatrix.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c rundown.c -o rundown.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c rundown2.c -o rundown2.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c surrogate.c -o surrogate.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c usersplit.c -o usersplit.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c xpred.c -o xpred.o
gcc -std=gnu99 -I/home/danab/R/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c xval.c -o xval.o
gcc -std=gnu99 -shared -L/usr/local/lib -o rpart.so anova.o anovapred.o branch.o bsplit.o choose_surg.o fix_cp.o free_tree.o gini.o graycode.o init.o insert_split.o make_cp_list.o make_cp_table.o mysort.o nodesplit.o partition.o poisson.o pred_rpart.o print_tree.o rpart.o rpart_callback.o rpartexp.o rpartexp2.o rpcountup.o rpmatrix.o rundown.o rundown2.o surrogate.o usersplit.o xpred.o xval.o
installing to /home/danab/R/lib/R/library/rpart/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (rpart)

The downloaded source packages are in
        ‘/tmp/RtmpAwr777/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
> require(maftools)
Loading required package: maftools
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘maftools’
> biocLite("maftools")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.4.0 (2017-04-21).
Installing package(s) ‘maftools’
Warning message:
package ‘maftools’ is not available (for R version 3.4.0)
`

**Comment by PoisonAlien** [comment]
Hi, 
It appears your bioconductor is not up to date. Current biocoductor is 3.6 but your log shows its attempting to install 3.2
Could you update your R and try ?

**Comment by PoisonAlien** [comment]
Hi,
Just realised, do this..

```r
source("https://bioconductor.org/biocLite.R")
biocLite("BiocUpgrade")
```

and it should het you proper version of maftools.
