### ISSUE TITLE
Plot is being masked by a white layer

### ISSUE THREAD

**Issue by manwarA** [PoisonAlien/maftools#1005]
I am trying with TCGA-LUSC data, and when tried to plot oncoplot, it appears like this:

[oncoplot_luad.pdf](https://github.com/PoisonAlien/maftools/files/14305269/oncoplot_luad.pdf)

It appears that there is a white layer has been appended on top of the plot that mask the actual plot. I opened this PDF in InkSpace and remove that white layer and later it appeared like this (desired one):

[oncoplot_luad_noWhiteLayer.pdf](https://github.com/PoisonAlien/maftools/files/14305300/oncoplot_luad_noWhiteLayer.pdf)

Even if the data is large, it should not mask the actual plot.

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue. I still can not figure out where this layer is coming from. 
The only reason I could think of is the grid lines that are drawn between the columns and rows.  You could set the color to NA with the argument `borderCol = NA` and see if it helps.

**Comment by manwarA** [comment]
Thank you for the input, however, it is something to do with the number of samples being analyzed. Previously, I had more samples and the plot is being masked, however, with one cancer type, it is fine (no masking). I will try your suggestion with large dataset and see if it corrects the plot.
