### ISSUE TITLE
extra space somaticInteractions

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#1006]
**Describe the issue**
A clear and concise description of what the issue is.
There is extra space 
<img width="507" alt="Screenshot 2024-02-28 at 5 03 28 PM" src="https://github.com/PoisonAlien/maftools/assets/31411260/291b9b46-1678-4817-a7d2-8da1e5b2f4da">

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
somaticInteractions(maf = maf, top = 30, pvalue = c(0.05, 0.1))
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
What does the output look like for these pairs?

For. ex: 
```r
laml.maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #MAF file
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') #clinical data
laml = read.maf(maf = laml.maf, clinicalData = laml.clin)

si = somaticInteractions(maf = laml)
si[pair %in% "KMT2C, ADAM6"] #or se[pair %in% "ADAM6, KMT2C"]
```
