### ISSUE TITLE
Extracting VAF information apart from plot.

### ISSUE THREAD

**Issue by HiraDatascience** [PoisonAlien/maftools#1014]
Hello

I am wondering how can i extract the information of VAF . My Maf file doesnot contain t_vaf column but i understand that i still get plotvaf graph. But I need to vaf values corresponding to each sample. How can i extract this column as plot function already creating it somewhere. 
I have tried 

```r
sar2[,t_vaf := as.numeric(t_alt_count)/(sum(as.numeric(t_alt_count) + as.numeric(t_ref_count))] 
```

but getting an error 

```r
Error: unexpected ']' in "sar2[,t_vaf := as.numeric(t_alt_count)/(sum(as.numeric(t_alt_count) + as.numeric(t_ref_count))]"
```

**Comment by PoisonAlien** [comment]
Hi,

I guess `sar2` is your MAF object? If so, please feel free to try the below. The plot function will do the [same](https://github.com/PoisonAlien/maftools/blob/master/R/plot_vaf.R#L40) if it finds the `t_ref_count` and `t_alt_counts` columns.

```r
sar2@data[,t_vaf := as.numeric(t_alt_count)/(sum(as.numeric(t_alt_count) + as.numeric(t_ref_count))]
```

I hope this helps. I will update the function to return the plot data.

**Comment by HiraDatascience** [comment]
Thanks much it worked by adding as.character as mentioned in source code.
Without it it was giving only NAs.

  dat[,t_vaf :=
as.numeric(as.character(t_alt_count))/(as.numeric(as.character(t_ref_count))
+ as.numeric(as.character(t_alt_count)))]
