### ISSUE TITLE
Getting error in lollipop plot

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#1016]
Hi

As I am working with genomic England data, I am not able to copy paste my commond and the error

Please, look at this screenshot which shows the error I get and if possible help me to know the reason.

FYI, the data is whole genome sequencing data comes from germline mutations in regulatory regions of a gene.
<img width="1512" alt="Screenshot 2024-04-22 at 16 31 40" src="https://github.com/PoisonAlien/maftools/assets/60115705/503fc1e7-bcf3-4e29-b9ff-2ac4c946e9b9">

Thanks for any help

**Comment by PoisonAlien** [comment]
Hi,

The error message is pretty clear. The position you are trying to label does not exist in the maf file.

**Comment by MaryGoAround** [comment]
> Hi,
> 
> The error message is pretty clear. The position you are trying to label does not exist in the maf file.

But you are seeing the amino acid in the screen shot in `HGVps_Short `column

**Comment by PoisonAlien** [comment]
Hi,
The error is not about the column `HGVSp_Short` but the position you are trying to label. There are no mutations at the position 882. Remove the argument `labelPos = 882` or change it to 31 as suggested.
