### ISSUE TITLE
Signature plot

### ISSUE THREAD

**Issue by Ind2022** [PoisonAlien/maftools#1017]
**Describe the issue**

**Command**
Dear Maftools support,

I am using maftools, NMF and sigminer R packages for construction of signature plots from a whole exome data from 2 sets of data, whole exome. I did use "nrun = 100" and pConstant = 0.01.

While I am able to create the signatures but the diagnostic plots doesn't look all right i.e there is  drop at 3 then again it goes up in cophenetic plot from first plot .  And it second plot there is no drop, its a straight line.

Please advice if these plots looks fine. 

There are 2 sets of data run, so I am sharing 2 plot sets below.

Thank you.

![factorizationrank_scid](https://github.com/PoisonAlien/maftools/assets/110693618/1beaa4fd-2497-44b0-8b0b-1060974f7301)
![factorizationrank_nude](https://github.com/PoisonAlien/maftools/assets/110693618/79c52a61-5fc5-4c45-a8c3-08688efbefa7)

**Comment by PoisonAlien** [comment]
Hi,
How many samples do you have? Also it appears your mutation load is quite low. 

CC: @ShixiangWang

**Comment by Ind2022** [comment]
Thank you for your reply. I have 4 samples in first set and on 2nd set there are 3 samples.
Kindly let me know if it will be fine to use this results or derived signatures.

**Comment by PoisonAlien** [comment]
Hi,

I would not use maftools for signature analysis with this low no. of samples. You should consider other tools such as [deconstructSigs](https://github.com/raerose01/deconstructSigs) that can work at the sample level.

**Comment by PoisonAlien** [comment]
It won't extract any new signatures and compare them to COSMIC. 
It's meant to get the composition of known COSMIC signatures within each sample.

**Comment by Ind2022** [comment]
Also does deconstructSigs work with mouse genome rather than human. I am not finding any ref for mouse genome with deconstructSigs

**Comment by ShixiangWang** [comment]
@Ind2022 Signature fitting is suitable for your data as @PoisonAlien suggested. Use the SigProfiler Assignment https://cancer.sanger.ac.uk/signatures/assignment/ or my sigminer sig_fit (https://shixiangwang.github.io/sigminer-book/basic-workflow.html#reference-signature-fitting) function as alternative is recommended.

**Comment by Ind2022** [comment]
Thank you for your response. Like I have mentioned above does these methods work with mouse genome and where can I find mouse genome reference file like maftools provide.

Thanks again.

**Comment by PoisonAlien** [comment]
Hi,
maftools does not provide any reference genomes. It uses BSGenome object to get the sequences. Please have a look at Bioconductor `BSgenome` packages for your mouse builds. 

I don't know how well these signatures translate to the mouse genome, you will have to research these independently.

**Comment by ShixiangWang** [comment]
They both support the mouse genome. You should check corresponding usage/tutorial. @PoisonAlien I think this could be close now.

> @Ind2022 Signature fitting is suitable for your data as @PoisonAlien suggested. Use the SigProfiler Assignment https://cancer.sanger.ac.uk/signatures/assignment/ or my sigminer sig_fit (https://shixiangwang.github.io/sigminer-book/basic-workflow.html#reference-signature-fitting) function as alternative is recommended.

**Comment by Ind2022** [comment]
Thank you for your replies.
