### ISSUE TITLE
TMB plot (tcgaCompare): Burden changes depending on input order

### ISSUE THREAD

**Issue by FriederikeHanssen** [PoisonAlien/maftools#1018]
**Describe the issue**
I am using the funciton `tcgaCompare`. Depending on the whether I plot each of my cohorts individually or add them all to one tcgaCompare plot, the results change.

**Command**
Please post your commands and the output (errors or any unexpected output)

Plot A  (both):
```r
tumor_mutational_burden <- tcgaCompare(
                               maf = c( mafs_wes,mafs_overlap),
                               capture_size = c(capture_size_wes,capture_size_overlap),
                               cohortName = c( "WES","Overlap )
                                )
tumor_mutational_burden
```

Plot B  (one only):
```r
tumor_mutational_burden <- tcgaCompare(mafs_wes, capture_size = capture_size_wes )
tumor_mutational_burden
```

**Session info**
Run `sessionInfo()` and post the output below

```r
karyoploteR       regioneR  GenomicRanges   GenomeInfoDb        IRanges      S4Vectors   BiocGenerics 
      "1.28.0"       "1.34.0"       "1.54.1"       "1.38.1"       "2.36.0"       "0.40.2"       "0.48.1" 
        ggpubr        ggplot2      gridExtra          tidyr          dplyr ComplexHeatmap     kableExtra 
       "0.6.0"        "3.5.1"          "2.3"        "1.3.1"        "1.1.4"       "2.18.0"        "1.3.4" 
         knitr        cowplot        forcats      patchwork       maftools 
        "1.45"        "1.1.3"        "1.0.0"        "1.1.3"       "2.18.0" 
```
![B](https://github.com/PoisonAlien/maftools/assets/12273093/c97da431-eaf7-499d-bd65-735f31c519df)
![A](https://github.com/PoisonAlien/maftools/assets/12273093/12b7c2d1-36d9-4596-bb6f-fd4f62fba5e0)

**Comment by PoisonAlien** [comment]
Hi,
Thank you for the issue. It was indeed a bug - all the input MAFs were being normalized with the first `capture_size`.
I have fixed it. Please let me know if it works for you.
