### ISSUE TITLE
lollipopPlot（）Report an error：Error in .getdomains(geneID = gene, refSeqID = refSeqID, proteinID = proteinID) :    Structure for protein PPDPFL not found.

### ISSUE THREAD

**Issue by yaohuiovo** [PoisonAlien/maftools#1025]
If this protein has no domain, can't we use lollipopPlot to draw it?

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue. I have updated the protein database with PPDPFL. Please reinstall maftools from GitHub for the changes.
