### ISSUE TITLE
Error in if (dist <= mergeDist) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by Iononering** [PoisonAlien/maftools#1027]
Thank you for your excellent work!

but when I use lollipopplot to draw PGM5, it told me "Error in if (dist <= mergeDist) { : missing value where TRUE/FALSE needed", but I have checked that all of our data and I am sure that there were not any NAs.

Codes and Error are as follow:
```r
lollipopPlot(maf = Responder,gene = "PGM5", AACol = "aaChange", showMutationRate = TRUE,repel = TRUE)
Error in if (dist <= mergeDist) { : missing value where TRUE/FALSE needed
```

**Comment by PoisonAlien** [comment]
Hi,
Unfortunately, `repel` is deprecated. Please do not use it. It will be removed soon.
