### ISSUE TITLE
sampleSwaps.R: add an error message in case of missing index files

### ISSUE THREAD

**Issue by eolaniru** [PoisonAlien/maftools#1028]
**issue**
With the sampleSwaps() function, if no index bai file is provided, it crashes r session without any useful error message.
It will be useful to raise an error that bai index files should be provided. 
Thank you

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue. I have updated the function. It should now throw an error if it can't find BAI files in the same directory.

**Comment by eolaniru** [comment]
Brilliant! Thank you

**Comment by eolaniru** [comment]
`    if(!file.exists(paste0(x , ".bai"))){
      stop("Index file for ", x, " not found!")
    }` 
This looks for file.bam.bai as index, since x is file.bam. It will not find file.bai. Would it be possible for check for either file extension? Thank you

**Comment by eolaniru** [comment]
This should work

```
    if(!file.exists(paste0(sub("\\.bam$", "", x), ".bai")) && !file.exists(paste0(x, ".bai"))){
      stop("Index file for ", x, " not found!")
    }
```

**Comment by PoisonAlien** [comment]
Hi,

Thanks again. I have updated the function, it should check for both now.

**Comment by eolaniru** [comment]
Brilliant! Thank you
