### ISSUE TITLE
Lollipopplot does not show complete protein length.

### ISSUE THREAD

**Issue by Arnob5105** [PoisonAlien/maftools#1029]
**Describe the issue**
We tried to plot "MUC3A" in lollipop plot. The length of the actual protein is 3323 according to uniprot database. But it is only showing 876.

**Command**

```r
lollipopPlot(
  maf = maffiles,
  gene = 'MUC3A',
  AACol = 'Protein_Change',
  showMutationRate = TRUE,
  showDomainLabel = FALSE,
  labPosSize = 1.2,
  printCount = TRUE,
  labPosAngle = 90,
  repel = FALSE,
  legendTxtSize = 1.4,
  axisTextSize = c(1.3,1.3),
  labelOnlyUniqueDoamins = FALSE,
  titleSize = c(1.4,1.2),
  pointSize = 1.8,
  domainLabelSize = 1.4
  )
```

**Comment by PoisonAlien** [comment]
Hi,

I don't know which transcript the length of 3323 corresponds to. 
As per cBioPortal - the length and transcript seems to match 

![](https://github.com/PoisonAlien/maftools/assets/8164062/9d465713-6ab4-4736-a3e3-db6d2107d40e)

**Comment by Arnob5105** [comment]
Hi, thanks for your quick reply. But according to [Uniprot,](https://www.uniprot.org/uniprotkb/Q02505/entry#sequences) the length of the protein is 3323. Moreover, in our analysis we also got the same length and mutational site, which extends beyond 876 amino acids.

**Comment by PoisonAlien** [comment]
Could you please post the transcript ID?

**Comment by Arnob5105** [comment]
It,s ENST00000379458.9
