### ISSUE TITLE
Intron region mutations

### ISSUE THREAD

**Issue by pwwang** [PoisonAlien/maftools#103]
Does `read.maf` automatically ignore the genes with only intronic mutations?
I can't find some genes with `getGeneSummary`.

Thanks.

**Comment by PoisonAlien** [comment]
Hi,
Yes, `read.maf` only keeps non-synoymous variants unless you ask it to include everything. Use argument `vc_nonSyn` in `read.maf` to include different kind of variant classifications. Also see #102.

**Comment by pwwang** [comment]
Hi, thanks for your reply. I will try the option.

**Comment by Shicheng-Guo** [comment]
Same with above question. 
1) annovarToMaf will ignore mutations in intron regions? 
2) I found oncoplot ignored all the mutations in intron regions. 

Thanks. 
Shicheng

**Comment by PoisonAlien** [comment]
No, it doesnt ignore anything. Your `maf` object contains a `maf.silent` slot which contains all the silent variants such as `intronic`. They wont be plotted in oncoplot. You will have to specify with `vc_nonSyn` argument while reading your maf with `read.maf`.
