### ISSUE TITLE
Error in get_lp_data(maf = m1, geneID = gene, AACol = AACol1, refSeqID = refSeqID,  :    Structure for protein BAGE3 not found.

### ISSUE THREAD

**Issue by libiqing77** [PoisonAlien/maftools#1033]
Hi guys,

when I used lollipopPlot2 to plot figure for BAGE3 gene, I got the following error.
Gene: BAGE3
Error in get_lp_data(maf = m1, geneID = gene, AACol = AACol1, refSeqID = refSeqID,  : 
  Structure for protein BAGE3 not found.

Could you help update the database.
Thanks.

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue. Unfortunately, this gene seems to have no transcripts or protein structures available. [Unirot](https://www.uniprot.org/uniprotkb/Q86Y29/entry) says its a 109 aa length protein with no domains. 
Please confirm or point me to the structure example (from any publication), I am happy to include it.
