### ISSUE TITLE
Discrepancy in MATH Scores

### ISSUE THREAD

**Issue by fatemedorri77** [PoisonAlien/maftools#1040]
**Describe the issue**
I am encountering a discrepancy in the MATH scores calculated for the sample TCGA.IB.7651.01A using the maftools R package. The score calculated using the 'math.score' function differs from the score obtained when visualizing the data with 'inferHeterogeneity' function.Could you please help me understand why there is a discrepancy between the two scores? I have attached the plots for both the laml2.math object and TCGA.IB.7651.01A plot for your reference.

**Command**
Calculating the MATH score:
laml2.math <- math.score(maf = laml2, vafCol = 'i_TumorVAF_WU',
                         sampleName = maf.m.vaf$Tumor_Sample_Barcode)

Output for TCGA.IB.7651.01A at laml2.math table : 18.304

Visualizing the data:
TCGA.IB.7651.01A = inferHeterogeneity(maf = laml2, tsb = 'TCGA.IB.7651.01A', vafCol = 'i_TumorVAF_WU')
print(TCGA.IB.7651.01A$clusterMeans)
plotClusters(clusters = TCGA.IB.7651.01A) 

Output for TCGA.IB.7651.01A: 19.098

![laml2.math](https://github.com/user-attachments/assets/c2df0c61-cf70-48df-8f73-0c54c74196fa)

![TCGA IB 7651 01A](https://github.com/user-attachments/assets/5b23189c-d369-417c-b505-0b4c1a0034a9)

**Comment by PoisonAlien** [comment]
Hi,
I'm sorry for not getting back to you sooner. This is due to the vaf cutoff used while estimating the math score.
`math.score` uses variants with a min vaf of 0.075 (`vafCutOff` argument) while `inferHeterogeneity` does not use any cutoff.  You can set this with `minVaf`. I hope this helps if you are still using it.
