### ISSUE TITLE
selectedPathways argument in oncoplot not functioning properly with user-defined pathways

### ISSUE THREAD

**Issue by kbrar4013** [PoisonAlien/maftools#1041]
Hi,

I'm having an issue with the "selectedPathways" argument in the oncoplot function, when using my own user-defined pathways. I either get the error below (with code):
```
 oncoplot(maf = wgs.maf.cnTable.G3only, altered=TRUE, pathways = kegg_pathways_oncoplot, selectedPathways = "KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_FGF8_TO_RAS_ERK_SIGNALING_PATHWAY", gene_mar = 8, fontSize = 0.8)
Error in matrix(data = 0, nrow = nrow(numMat), ncol = length(tsbs[!tsbs %in%  : 
  non-numeric matrix extent 
```

OR, it works, but the number of samples affected is incorrect. For example, for the pathway "REACTOME_FGFR2_ALTERNATIVE_SPLICING", the results of the "pathways" function indicates that 24 out of 37 samples should be altered. If I take the list of genes in that pathway and provide it as an argument to the oncoplot through the "genes" argument, then I correctly get 24/37. If I provide the pathway name through the "selectedPathways" argument, I instead get 8/37 altered, which seems to be incorrect. Below is all the code and the results I'm getting - would appreciate your help.

I've also attached the pathway data-frame I'm providing as input. I had to switch the order of the Gene and Pathways column, as it seems that the pathways function expects the pathway column first, whereas the oncoplot function expects the gene names first. 

[reactome_pathways.txt](https://github.com/user-attachments/files/16381432/reactome_pathways.txt)

```
G3_reactome_pathways <- pathways(wgs.maf.cnTable.G3only, pathways = reactome_pathways, plotType = NA)

fgfr2_splicing_pathway_genes <- c("ESRP1", "ESRP2", "FGFR2", "GTF2F1", "GTF2F2", "HNRNPA1", "HNRNPF", "HNRNPH1", "HNRNPM", "NCBP1", "NCBP2", "POLR2A", "POLR2B", "POLR2C", "POLR2D", "POLR2E", "POLR2F", "POLR2G", "POLR2H", "POLR2I", "POLR2J", "POLR2K", "POLR2L", "PTBP1", "RBFOX2", "TIA1", "TIAL1")

oncoplot(maf=wgs.maf.cnTable.G3only, genes=fgfr2_splicing_pathway_genes, altered=TRUE, showTumorSampleBarcodes = TRUE, gene_mar = 8, fontSize = 0.8)

oncoplot(maf = wgs.maf.cnTable.G3only, altered=TRUE, pathways = reactome_pathways_oncoplot, selectedPathways = "REACTOME_FGFR2_ALTERNATIVE_SPLICING", gene_mar = 8, fontSize = 0.8)
```

<img width="783" alt="Screenshot 2024-07-25 at 1 08 56 PM" src="https://github.com/user-attachments/assets/3a4e6157-a8ab-4e00-8028-53c499c7078b">

**output with specifying the pathway genes manually**

<img width="794" alt="Screenshot 2024-07-25 at 1 07 31 PM" src="https://github.com/user-attachments/assets/15c788e5-ce37-4d79-8476-326ad6246a2d">
**output with oncoplot pathways function**

Thanks for the great package, it's been really helpful for my analysis.

**Comment by PoisonAlien** [comment]
Hi,

I'm sorry for the late response. I somehow overlooked the issue.

Thank you for reporting and, I have fixed it. If you are still working on it, I would appreciate it if you could try it and let me know if this helps.
