### ISSUE TITLE
Border of gisticOncoPlot

### ISSUE THREAD

**Issue by maximus3219** [PoisonAlien/maftools#1043]
I try to plot gisticOncoPlot but the legend is out of the border that I cannot adjust with any options within gisticOncoPlot()

![Rplot01](https://github.com/user-attachments/assets/0f7709ad-ed4c-41ce-8f92-0178e424f476)

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the delay. I have added `right_mar` argument to the function. You should be able to define your own margin size. I hope this helps.
