### ISSUE TITLE
Error :could not find function "OncogenicPathways"

### ISSUE THREAD

**Issue by HiraDatascience** [PoisonAlien/maftools#1046]
Hello i am getting this weird error. 

*Error in OncogenicPathways(maf, pathways = NULL, fontSize = 1,  : 
  could not find function "OncogenicPathways"

 [sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Europe/Stockholm
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggpubr_0.6.0      ggplot2_3.5.1     tidyr_1.3.1       data.table_1.14.8 dplyr_1.1.3      
[6] maftools_2.18.0  

loaded via a namespace (and not attached):
 [1] gtable_0.3.5        htmlwidgets_1.6.4   devtools_2.4.5      remotes_2.5.0      
 [5] rstatix_0.7.2       lattice_0.21-8      vctrs_0.6.4         tools_4.3.1        
 [9] generics_0.1.3      curl_5.2.1          tibble_3.2.1        fansi_1.0.5        
[13] pkgconfig_2.0.3     pheatmap_1.0.12     Matrix_1.6-4        RColorBrewer_1.1-3 
[17] lifecycle_1.0.4     compiler_4.3.1      farver_2.1.1        stringr_1.5.1      
[21] munsell_0.5.1       carData_3.0-5       httpuv_1.6.13       htmltools_0.5.7    
[25] usethis_3.0.0       later_1.3.2         pillar_1.9.0        car_3.1-2          
[29] urlchecker_1.0.1    ellipsis_0.3.2      cachem_1.0.8        sessioninfo_1.2.2  
[33] abind_1.4-5         nlme_3.1-162        mime_0.12           tidyselect_1.2.1   
[37] digest_0.6.33       stringi_1.7.12      purrr_1.0.2         labeling_0.4.3     
[41] splines_4.3.1       fastmap_1.1.1       grid_4.3.1          colorspace_2.1-0   
[45] cli_3.6.1           magrittr_2.0.3      survival_3.5-5      pkgbuild_1.4.4     
[49] utf8_1.2.4          broom_1.0.6         withr_3.0.1         scales_1.3.0       
[53] promises_1.2.1      backports_1.5.0     ggsignif_0.6.4      memoise_2.0.1      
[57] DNAcopy_1.76.0      shiny_1.9.1         miniUI_0.1.1.1      mgcv_1.8-42        
[61] profvis_0.3.8       rlang_1.1.2         Rcpp_1.0.11         xtable_1.8-4       
[65] glue_1.6.2          BiocManager_1.30.24 pkgload_1.4.0       rstudioapi_0.16.0  
[69] R6_2.5.1            fs_1.6.3   ](url)

**Comment by HiraDatascience** [comment]
I installed it from 
BiocManager::install("maftools")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories",
package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.18 (BiocManager 1.30.23), R 4.3.1 (2023-06-16 ucrt)
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.3.1/library
  packages:
    boot, cluster, codetools, foreign, KernSmooth, lattice, mgcv, nlme, rpart, spatial,
    survival
Old packages: 'BiocManager', 'cachem', 'cli', 'colorspace', 'corrplot', 'cpp11', 'curl',
  'data.table', 'digest', 'dplyr', 'fansi', 'farver', 'fastmap', 'fs', 'gert', 'glue', 'gmp',
  'htmltools', 'httpuv', 'httr2', 'insight', 'minqa', 'mvtnorm', 'NMF', 'openssl', 'promises',
  'Rcpp', 'RcppEigen', 'rlang', 'rmarkdown', 'stringi', 'vctrs', 'waldo', 'xfun'
Update all/some/none? [a/s/n]: 
a
Warning: packages ‘data.table’, ‘dplyr’ are in use and will not be installed

  There are binary versions available but the source versions are later:
      binary source needs_compilation
cpp11  0.4.7  0.5.0             FALSE
curl   5.2.1  5.2.2              TRUE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/BiocManager_1.30.24.zip'
Content type 'application/zip' length 504281 bytes (492 KB)
downloaded 492 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/cachem_1.1.0.zip'
Content type 'application/zip' length 72511 bytes (70 KB)
downloaded 70 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/cli_3.6.3.zip'
Content type 'application/zip' length 1339445 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/colorspace_2.1-1.zip'
Content type 'application/zip' length 2660280 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/corrplot_0.94.zip'
Content type 'application/zip' length 3812343 bytes (3.6 MB)
downloaded 3.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/digest_0.6.37.zip'
Content type 'application/zip' length 221803 bytes (216 KB)
downloaded 216 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/fansi_1.0.6.zip'
Content type 'application/zip' length 314225 bytes (306 KB)
downloaded 306 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/farver_2.1.2.zip'
Content type 'application/zip' length 1509450 bytes (1.4 MB)
downloaded 1.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/fastmap_1.2.0.zip'
Content type 'application/zip' length 133299 bytes (130 KB)
downloaded 130 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/fs_1.6.4.zip'
Content type 'application/zip' length 409107 bytes (399 KB)
downloaded 399 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/gert_2.1.1.zip'
Content type 'application/zip' length 3496044 bytes (3.3 MB)
downloaded 3.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/glue_1.7.0.zip'
Content type 'application/zip' length 161414 bytes (157 KB)
downloaded 157 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/gmp_0.7-5.zip'
Content type 'application/zip' length 760461 bytes (742 KB)
downloaded 742 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/htmltools_0.5.8.1.zip'
Content type 'application/zip' length 358321 bytes (349 KB)
downloaded 349 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/httpuv_1.6.15.zip'
Content type 'application/zip' length 1042070 bytes (1017 KB)
downloaded 1017 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/httr2_1.0.3.zip'
Content type 'application/zip' length 586490 bytes (572 KB)
downloaded 572 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/insight_0.20.3.zip'
Content type 'application/zip' length 2159709 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/minqa_1.2.8.zip'
Content type 'application/zip' length 459712 bytes (448 KB)
downloaded 448 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/mvtnorm_1.2-6.zip'
Content type 'application/zip' length 785571 bytes (767 KB)
downloaded 767 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/NMF_0.28.zip'
Content type 'application/zip' length 3104944 bytes (3.0 MB)
downloaded 3.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/openssl_2.2.1.zip'
Content type 'application/zip' length 3399224 bytes (3.2 MB)
downloaded 3.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/promises_1.3.0.zip'
Content type 'application/zip' length 2023388 bytes (1.9 MB)
downloaded 1.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/Rcpp_1.0.13.zip'
Content type 'application/zip' length 2886369 bytes (2.8 MB)
downloaded 2.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/RcppEigen_0.3.4.0.2.zip'
Content type 'application/zip' length 2612428 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/rlang_1.1.4.zip'
Content type 'application/zip' length 1579343 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/rmarkdown_2.28.zip'
Content type 'application/zip' length 2683630 bytes (2.6 MB)
downloaded 2.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/stringi_1.8.4.zip'
Content type 'application/zip' length 14997376 bytes (14.3 MB)
downloaded 14.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/vctrs_0.6.5.zip'
Content type 'application/zip' length 1336828 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/waldo_0.5.3.zip'
Content type 'application/zip' length 105347 bytes (102 KB)
downloaded 102 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/xfun_0.47.zip'
Content type 'application/zip' length 535044 bytes (522 KB)
downloaded 522 KB

package ‘BiocManager’ successfully unpacked and MD5 sums checked
package ‘cachem’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘cachem’
Warning: restored ‘cachem’
package ‘cli’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘cli’
Warning: restored ‘cli’
package ‘colorspace’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘colorspace’
Warning: restored ‘colorspace’
package ‘corrplot’ successfully unpacked and MD5 sums checked
package ‘digest’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘digest’
Warning: restored ‘digest’
package ‘fansi’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘fansi’
Warning: restored ‘fansi’
package ‘farver’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘farver’
Warning: restored ‘farver’
package ‘fastmap’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘fastmap’
Warning: restored ‘fastmap’
package ‘fs’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘fs’
Warning: restored ‘fs’
package ‘gert’ successfully unpacked and MD5 sums checked
package ‘glue’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘glue’
Warning: restored ‘glue’
package ‘gmp’ successfully unpacked and MD5 sums checked
package ‘htmltools’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘htmltools’
Warning: restored ‘htmltools’
package ‘httpuv’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘httpuv’
Warning: restored ‘httpuv’
package ‘httr2’ successfully unpacked and MD5 sums checked
package ‘insight’ successfully unpacked and MD5 sums checked
package ‘minqa’ successfully unpacked and MD5 sums checked
package ‘mvtnorm’ successfully unpacked and MD5 sums checked
package ‘NMF’ successfully unpacked and MD5 sums checked
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘promises’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘promises’
Warning: restored ‘promises’
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘Rcpp’
Warning: restored ‘Rcpp’
package ‘RcppEigen’ successfully unpacked and MD5 sums checked
package ‘rlang’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘rlang’
Warning: restored ‘rlang’
package ‘rmarkdown’ successfully unpacked and MD5 sums checked
package ‘stringi’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘stringi’
Warning: restored ‘stringi’
package ‘vctrs’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘vctrs’
Warning: restored ‘vctrs’
package ‘waldo’ successfully unpacked and MD5 sums checked
package ‘xfun’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\chaud\AppData\Local\Temp\RtmpkrYFpx\downloaded_packages
installing the source packages ‘cpp11’, ‘curl’

trying URL 'https://cran.rstudio.com/src/contrib/cpp11_0.5.0.tar.gz'
Content type 'application/x-gzip' length 275693 bytes (269 KB)
downloaded 269 KB

trying URL 'https://cran.rstudio.com/src/contrib/curl_5.2.2.tar.gz'
Content type 'application/x-gzip' length 717715 bytes (700 KB)
downloaded 700 KB

* installing *source* package 'cpp11' ...
** package 'cpp11' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (cpp11)
* installing *source* package 'curl' ...
** package 'curl' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/chaud/AppData/Local/R/win-library/4.3/curl'
* restoring previous 'C:/Users/chaud/AppData/Local/R/win-library/4.3/curl'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\chaud\AppData\Local\R\win-library\4.3\00LOCK-curl\curl\libs\x64\curl.dll to C:\Users\chaud\AppData\Local\R\win-library\4.3\curl\libs\x64\curl.dll: Permission denied

The downloaded source packages are in
	‘C:\Users\chaud\AppData\Local\Temp\RtmpkrYFpx\downloaded_packages’
There were 18 warnings (use warnings() to see them)

**Comment by HiraDatascience** [comment]
while trying from git hub it gives this error
BiocManager::install("PoisonAlien/maftools")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories",
package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.18 (BiocManager 1.30.24), R 4.3.1 (2023-06-16 ucrt)
Installing github package(s) 'PoisonAlien/maftools'
Downloading GitHub repo PoisonAlien/maftools@HEAD
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/rtools43/files/rtools43-5958-5975.exe'
Content type 'application/x-msdownload' length 442828520 bytes (422.3 MB)
downloaded 422.3 MB

Error: Failed to install 'maftools' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

**Comment by snosna** [comment]
I encountered a similar issue. It seems that `OncogenicPathways()` is deprecated and no longer a part of `maftools`. Try `pathways` instead. To obtain the Pathways plot, use `pathways(maf = YourMafObject, plotType = "bar")` (the other possible argument for `plotType` is `treemap`. Check `?pathways` for full details).
