### ISSUE TITLE
The subsetMaf function is ineffective for screening samples and genes.

### ISSUE THREAD

**Issue by MECHANIC-LIJIAN** [PoisonAlien/maftools#1048]
The subsetMaf function passes the parameters 'tsb' and 'genes' to filter samples and genes. The dataframe filter statement uses the column name directly, causing the filter result to be empty:

> Error in subsetMaf(maf = pancan, tsb = selected_samples) : 
  Subsetting has resulted in zero non-synonymous variants!
 
`maf.dat = maf.dat[Tumor_Sample_Barcode %in% tsb, ]`
`maf.dat = maf.dat[Hugo_Symbol %in% genes, ]`

Whether it should be written this way：
`maf.dat = maf.dat[maf.dat$Tumor_Sample_Barcode %in% tsb, ]`
`maf.dat = maf.dat[maf.dat$Hugo_Symbol %in% genes, ]`

**Comment by PoisonAlien** [comment]
Hi,

I have trouble reproducing the issue. 
`data.table` syntax allows columns to be referred to as if they are variables. We do not need to add the prefix $ each time (although its perfectly acceceptable)

**Comment by MECHANIC-LIJIAN** [comment]
I'm sorry.I found that some samples in my data lacked clinical information.
