### ISSUE TITLE
Error:long vectors not supported yet: memory.c:3940

### ISSUE THREAD

**Issue by Olsennnnn** [PoisonAlien/maftools#1049]
Hi,
While running this
`laml.tnm = trinucleotideMatrix(maf = combined_maf, prefix = 'chr', add = TRUE, ref_genome = "BSgenome.Hsapiens.UCSC.hg18")`
, I got a mistake, like
```
Warning in trinucleotideMatrix(maf = combined_maf, prefix = "chr", add = TRUE,  :
  Chromosome names in MAF must match chromosome names in reference genome.
Ignorinig 4253421 single nucleotide variants from missing chromosomes chr23, chr25, chr26
-Extracting 5' and 3' adjacent bases
-Extracting +/- 20bp around mutated bases for background C>T estimation
Error in .Call2("XStringSet_letter_frequency", x, collapse, codes, baseOnly,  : 
  long vectors not supported yet: memory.c:3940
```
Do you have any suggestion how to solve it?
Thanks

**Comment by PoisonAlien** [comment]
Hi,

I'm sorry for not getting back to you sooner. Chromosome names in your MAF appear to have the `chr` prefix already.  You do not need to use the `prefix` argument.
