### ISSUE TITLE
icgcSimpleMutationToMAF transform icgc data to maf but some sample lost

### ISSUE THREAD

**Issue by yezheng1003** [PoisonAlien/maftools#105]
Hi, I used the icgcSimpleMutationToMAF function to transform the data download from ICGC and I found that some sample were dropped. I want to know the reason they are dropped and how to save all the sample to the final maf file.

my code:
require(maftools)
icgcSimpleMutationToMAF("simple_somatic_mutation.open.LICA-FR.tsv","lica-fr")

this icgc file has 251 samples, however the maf file only has 247 samples.

maftools version: 1.4.10
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)

Thank you very much~~

**Comment by PoisonAlien** [comment]
Hi,

This is weird. Can you post a link to your iccc file ? Just post the url and I will take a look.

**Comment by yezheng1003** [comment]
sorry to answer you so late, the link is https://dcc.icgc.org/api/v1/download?fn=/current/Projects/LICA-FR/simple_somatic_mutation.open.LICA-FR.tsv.gz

**Comment by yezheng1003** [comment]
i find something strange in the 147 line in the r code named icgc_to_maf.R: 
icgc.maf$Tumor_Sample_Barcode = as.factor(x = as.character(icgc.maf$Hugo_Symbol))
whether the Hugo_Symbol should be Tumor_Sample_Barcode ?

**Comment by PoisonAlien** [comment]
Hi,
Could you post your command ? and nice catch btw ! I will fix it asap. 
Also I realised I did not update this function after recent modifications to MAF object, so it might be the issue.

**Comment by PoisonAlien** [comment]
Hi,

I don't think that was the issue. See here results are the same and none of the samples were removed from original icgc data.

Raw data. 251 samples.
```r
>icgc_raw = data.table::fread(input = "zcat < simple_somatic_mutation.open.LICA-FR.tsv.gz")
> icgc_raw[,.N,icgc_sample_id]
     icgc_sample_id     N
  1:       SA529909   920
  2:       SA529911   602
  3:       SA529913   895
  4:       SA529896   494
  5:       SA529900    86
 ---                     
247:       SA267236 44344
248:       SA561310 20443
249:       SA561312 56680
250:       SA561308  7039
251:       SA561306 65603
```

After converting to MAF. 251 samples
```r
>icgc_maf = icgcSimpleMutationToMAF(icgc = "simple_somatic_mutation.open.LICA-FR.tsv.gz")
>icgc_maf[,.N,Tumor_Sample_Barcode]
 Tumor_Sample_Barcode   N
  1:             SA529909 126
  2:             SA529911  97
  3:             SA529900  17
  4:             SA529880  98
  5:             SA529891  88
 ---                         
247:             SA499700  16
248:             SA530175  18
249:             SA530058   1
250:             SA499658   1
251:             SA499696   2
```

Maybe post your commands and how you calculated number of samples after maf conversion, so that I can help?

**Comment by PoisonAlien** [comment]
Ah! I see.. when you read converted maf file with `read.maf` it shows 247 samples. Because 4 of the samples ("SA499658", "SA499696", "SA530101", "SA530139") have no non-synonymous mutations. They are still there but they are in silent variants slot of MAF object.

```r
>icgc_maf = icgcSimpleMutationToMAF(icgc = "simple_somatic_mutation.open.LICA-FR.tsv.gz")
>icgc_maf = read.maf(maf = icgc_maf)
> icgc_maf
An object of class  MAF 
                        ID summary   Mean Median
 1:             NCBI_Build  GRCh37     NA     NA
 2:                 Center      NA     NA     NA
 3:                Samples     247     NA     NA
 4:                 nGenes    7044     NA     NA
 5:        Frame_Shift_Del     194  0.785      0
 6:        Frame_Shift_Ins      91  0.368      0
 7:           In_Frame_Del     130  0.526      0
 8:           In_Frame_Ins      24  0.097      0
 9:      Missense_Mutation   11576 46.866     31
10:      Nonsense_Mutation     719  2.911      2
11:       Nonstop_Mutation      17  0.069      0
12:            Splice_Site     606  2.453      1
13: Translation_Start_Site      21  0.085      0
14:                  total   13378 54.162     36

#See, these are the missing ones with no non-syn mutations.
subsetMaf(maf = icgc_maf, tsb = c("SA499658", "SA499696", "SA530101", "SA530139"))[,.N, Variant_Classification]
```
