### ISSUE TITLE
Questions of GISTIC and copy number alteration analysis 

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#1054]
**Describe the issue**
Hi I am planning to analyze copy number alterations in a small cohort (n=15), and I have the segmentation data in TCGA format. I tried to generate GISTIC files for maftools, however it failed due to limited sample size. I wonder if you have any suggestions to get this around. Thanks

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,

Could you please post the commands used and the error?
