### ISSUE TITLE
Cannot find function Oncogenic Pathways

### ISSUE THREAD

**Issue by londonlondon20** [PoisonAlien/maftools#1055]
**Describe the issue**
Hello! I am using maftools version 2.21.1 and am not able to use the function OncogenicPathways. I saw some documentation online that this function may only exist under v2.6.05, but I don't know how to install that version. Really appreciate your help!

**Command**
Please post your commands and the output (errors or any unexpected output)

> packageVersion("maftools") [1] ‘2.21.1’ > library(maftools) > C.pathway=OncogenicPathways(maf=C.maf) Error in OncogenicPathways(maf = CTE.maf) :    could not find function "OncogenicPathways"

**Session info**
Run `sessionInfo()` and post the output below
<html>
<body>

R version 4.4.1 (2024-06-14 ucrt) Running under: Windows 11 x64 Matrix products: default  attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] maftools_2.21.1  loaded via a namespace (and not attached):  [1] desc_1.4.3          RColorBrewer_1.1-3  R6_2.5.1            Matrix_1.7-0        lattice_0.22-6      splines_4.4.1        [7] remotes_2.5.0       ps_1.8.0            cli_3.6.3           processx_3.8.4      callr_3.7.6         grid_4.4.1          [13] data.table_1.16.0   compiler_4.4.1      rstudioapi_0.16.0   tools_4.4.1         pkgbuild_1.4.4      curl_5.2.3          [19] survival_3.7-0      DNAcopy_1.78.0      BiocManager_1.30.25

**Comment by PoisonAlien** [comment]
Hi,

This function has been replaced by the more generic `pathways()`. Please switch to it. 
`?pathways()` for more info.
