### ISSUE TITLE
The variants are almost Silent

### ISSUE THREAD

**Issue by DayTimeMouse** [PoisonAlien/maftools#1056]
Hi,

When I use read.maf to read maf file, but almost variants are silent(silent variants/all variants: **16874**/17013).

I am unsure about that is annotation problem or something.
`df = read.maf('filter.vep.maf')`
```
plotmafSummary(maf = df,
               rmOutlier = T,
               showBarcodes = F,
               textSize = 0.4,
               addStat = 'median',
               dashboard = TRUE,
               titvRaw = FALSE)
```
```
-Reading
-Validating
-Silent variants: 16874 
-Summarizing
-Processing clinical data
--Missing clinical data
-Finished in 0.360s elapsed (3.499s cpu)
```
![Rplot01](https://github.com/user-attachments/assets/b6169128-b72d-4426-bea6-9f4281636725)

Best regards.

**Comment by PoisonAlien** [comment]
Hi,

It's hard to know without seeing the data. If it is WGS, I guess it is possible.
