### ISSUE TITLE
No non-synonymous mutations found

### ISSUE THREAD

**Issue by aeozdemr** [PoisonAlien/maftools#1058]
Hi first of all thanks for this great tool!

I am trying to read my .maf file but I want classify all the mutations as non-silent because I need all for oncoplot and I want to see the mutations if they are even silent.

For this I tried to use  "nonSyn = c("Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site",
               "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del","In_Frame_Ins", "Missense_Mutation","intergenic")" for nonSyn option, however even though there are mutations in my .maf file it still says no non-synonymous mutations found. How can I skip the part where read.maf checks for non-synonymous mutations or how can I classify all mutations as nonSyn.

Thanks.

**Comment by PoisonAlien** [comment]
Hi,

Are you sure the values in `Variant_Classification` column match those provided in `nonSyn`? 

If you'd like to consider all types as nonSyn, please try as below

```r
> laml.maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #MAF file
> m = data.table::fread(input = laml.maf)
> all_vcs = m[,.N,Variant_Classification][,Variant_Classification]
> print(all_vcs)
 [1] "Splice_Site"       "Missense_Mutation" "Silent"            "Frame_Shift_Del"   "Nonsense_Mutation" "Intron"            "Frame_Shift_Ins"   "RNA"               "In_Frame_Del"     
[10] "IGR"               "In_Frame_Ins"      "5'Flank"   
> m = maftools::read.maf(maf = m, vc_nonSyn = all_vcs)
```

I hope this helps.

**Comment by aeozdemr** [comment]
Hi yes!, this helped I also realized my Variant_Classifcation values were not matching with the values in the columns.

Thanks.
