### ISSUE TITLE
Error when using mafSurvival with TCGA samples

### ISSUE THREAD

**Issue by Mars-fi** [PoisonAlien/maftools#1073]
There is an error when using mafSurvival in TCGA-PAAD cohort, the K-M plot didn't exist.

**Command**
mafSurvival(maf=maf, genes=c("KRAS"), time="days_to_last_follow_up", Status="days_to_death", isTCGA=TRUE)

**Session info**
Looking for clinical data in annoatation slot of MAF..
Number of mutated samples for given genes: 
KRAS 
 106 
Removed 142 samples with NA's
Median survival..
    Group medianTime     N
   <char>      <num> <int>
1: Mutant      131.5    16
2:     WT      141.0    14
Error: survfit.formula(formula = survival::Surv(time = Time, event = Status) ~ : 
  data set has no non-missing observations
Warning:
In survival::Surv(time = Time, event = Status) :
  Invalid status value, converted to NA

Thank you!

**Comment by PoisonAlien** [comment]
Hi,

How did you generate the `maf`? Is it via `tcgaLoad()` function?

**Comment by Mars-fi** [comment]
no, I just use read.maf()

Besides, I have already solved this problem by replacing the vital_status with Dead=1, Alive=0.

Thank you very much!
