### ISSUE TITLE
CDC MAF and TCGA MAF

### ISSUE THREAD

**Issue by dschslava** [PoisonAlien/maftools#108]
Dears PoisonAlien,

It seems to me that tcga_laml.maf used in your example is based on GDC MAF, not TCGA MAF. Could you clarify?

The GDC MAF file format is based on the   TCGA Mutation Annotation Format specifications, with additional columns included.

The reason is that in tcga_laml.maf, Column 56 Amino_acids is specified. The TCGA MAF only has 34 columns. 

Thanks in advance for your clarification!

Canyon Crest Academy High School,
San Diego, CA

**Comment by dschslava** [comment]
It seems to be that you still use the TGCA MAF format based on the following:

- Recommended optional fields: non MAF specific fields containing vaf and amino acid change information

Which file contains the amino acid change information? tcga_laml_annot.tsv?

Thanks in advance!

**Comment by dschslava** [comment]
I think the amino acids change information is stored in the optional field of the MAF. Could you clarify?

**Comment by PoisonAlien** [comment]
Hi,

TCGA MAF files contain a lot of information but maftools doesn't require all of them. Amino acid change information is usually stored in MAF under column names such as 'HGVSp_Short', 'AAChange' or 'Protein_Change'. maftools tries to guess it automatically and if it fails to do so, you'll have to figure out the column name by going through maf file manually.

**Comment by dschslava** [comment]
Got it. Thanks.
