### ISSUE TITLE
Gene Mutation

### ISSUE THREAD

**Issue by dschslava** [PoisonAlien/maftools#109]
For Gene Summary..
       Hugo_Symbol Frame_Shift_Del Frame_Shift_Ins In_Frame_Del In_Frame_Ins Missense_Mutation Nonsense_Mutation Nonstop_Mutation Splice_Site total MutatedSamples AlteredSamples
    1:      PIK3CA               0               2           13            1               273                 0                0           0   289            263            263
    2:        TP53              33              13            5            0               158                35                0          18   262            258            258
    3:         TTN               4               0            1            0               138                10                1           2   156            122            122
    4:       GATA3              14              45            0            0                 6                 0                0          20    85             81             81
    5:        MLL3              11               7            2            1                27                14                0           3    65             61             61

Can we see the concrete mutations in these genes?

Thanks in advance?

**Comment by PoisonAlien** [comment]
What does concrete mutations mean ? You can use `lollipopPlot` to visualise distribution of mutations in the desired gene.

**Comment by dschslava** [comment]
What I mean is if it is possible to list the SNP for the mutated genes in maftools? 

Thanks for your prompt reply!
