### ISSUE TITLE
Samples with zero coding mutations

### ISSUE THREAD

**Issue by tb08** [PoisonAlien/maftools#110]
Hello and thanks for this very nice package.
I was wondering if there is an easy way to force the inclusion of samples that have zero mutations in the maf object so that they are taken into account in the plots and summaries.

**Comment by PoisonAlien** [comment]
Hi,
Sorry, for now there is no way to include them in the analysis. You will have introduce them with a simulated mutation.

**Comment by tb08** [comment]
Thanks for the quick reply. I thought about adding dummy mutations but it's a bit unsatisfying because it affects some of the plots and summary statistics. A better solution would be to have a "samples" argument to maf constructors and that all the matrices built inside include those samples unless otherwise specified but I guess this would require a bit of code in multiple functions.

**Comment by PoisonAlien** [comment]
Yes, I was thinking about this and my guess would be it will break many functions and fixing would require some time. I don't think I can do this immediately. Sorry :|
