### ISSUE TITLE
Oncostrip: sort columns by mutations

### ISSUE THREAD

**Issue by maoge2333** [PoisonAlien/maftools#111]
Hi,

I am trying to sort columns by types of mutations(i.e., color), instead randomly distributed. I can't find that functionality. Could you please let me know if you have the functionality? If not, perhaps you could give me guidance to create one?

**Comment by maoge2333** [comment]
and also in oncoplot, I tried to use sortbymutaion = T, but the result doesn't have any difference with sortbymutation = F. I would appreciate it if you can help me. 
Thanks and best regards.

**Comment by PoisonAlien** [comment]
Hello,
Could you post your command and sessionInfo ?
If you want to sort by columns you will have to make an annotation table for every sample and then sort it by `sortByAnnottaion = TRUE`. See [here](http://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#523_changing_colors,_including_mutsig_q-values,_adding_annotations_and_sorting)

**Comment by maoge2333** [comment]
Hi,
Thank for your response.

this is my command:
require(maftools)
ucs <- read.maf('/Users/maoge/Desktop/PR_TCGA_UCS_PAIR_Capture_All_Pairs.aggregated.capture.tcga.uuid.curated.somatic.maf')
oncoplot(ucs,sortByMutation = T)

and sessionInfo:
sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_1.4.15     Biobase_2.38.0      BiocGenerics_0.24.0

could you please let me know what information should be concluded in the annotation table. Thanks!

**Comment by PoisonAlien** [comment]
Hi,
annotation table should be two columns data frame or a text file with sample names and associated annotations. 
Something like this.
```r
>getClinicalData(x = laml)[,1:2]
     Tumor_Sample_Barcode FAB_classification
  1:         TCGA-AB-2802                 M4
  2:         TCGA-AB-2803                 M3
  3:         TCGA-AB-2804                 M3
  4:         TCGA-AB-2805                 M0
  5:         TCGA-AB-2806                 M1
 ---                                        
188:         TCGA-AB-3007                 M3
189:         TCGA-AB-3008                 M1
190:         TCGA-AB-3009                 M4
191:         TCGA-AB-3011                 M1
192:         TCGA-AB-3012                 M3
```
