### ISSUE TITLE
Question about Mutation Type

### ISSUE THREAD

**Issue by Tina9** [PoisonAlien/maftools#112]
Hi,

I have a question about the plots including SNV class. I ran the command according to the introduction of maftools' website [https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html](url). But I'm really curiour why do you choose T>G, T>C, T>A, C>T, C>G and C>A in the summary plot and TiTv plot.  Could you please tell me the answer?

Thanks for your help.
Tina

**Comment by PoisonAlien** [comment]
Hello,
Every mutations can be [classified](https://www.mun.ca/biology/scarr/Transitions_vs_Transversions.html) into 6 of transitions to transversions. That plot helps to visualise what kind of events are more frequent. Hope this helps.

**Comment by Tina9** [comment]
So is G>A the same as C>T?

**Comment by Tina9** [comment]
Cool. That's what I need. 

Thank you so much.

**Comment by Tina9** [comment]
Cool. That's what I need. 

Thank you so much.
