### ISSUE TITLE
read.maf Removing Variants 

### ISSUE THREAD

**Issue by patidarr** [PoisonAlien/maftools#113]
Hi,

Thanks for writing such an awesome tool!!

When I loaded a maf file I got this message:
```
reading maf..
Read 538537 rows and 20 (of 20) columns from 0.069 GB file in 00:00:03
NOTE: Removed 7651 duplicated variants
Summarizing..

```
But when I did count uniq of the Chromosome     Start_Position  End_Position Reference_Allele        Tumor_Seq_Allele1       Tumor_Seq_Allele2 Tumor_Sample_Barcode, I did not find any duplicate rows in my maf file.

just wondering why they got removed?

Thanks,
Rajesh

**Comment by PoisonAlien** [comment]
Hi,
Could you post your commands on how you counted duplicated IDs ? You should make an unique ID for every variant/sample then look for duplicated IDs.

See [here](https://github.com/PoisonAlien/maftools/blob/master/R/validateMaf.R#L26) for the source.

**Comment by patidarr** [comment]
Hi,

Isn't is possible to have many variants starting at the same start position? Especially if there are indels or >1 variant in a sample(Uncommon but not that uncommon as well)

`    maf = maf[, variantId := paste(Chromosome, Start_Position, Tumor_Sample_Barcode, sep = ':')]
`

Should this be something similar to:
`$ cut -f5,6,7,11,12,13,14 My.maf |sort |uniq -c |sort -n |tail`

**Comment by PoisonAlien** [comment]
Hi,
Its possible to have many variants starting at same position (hotspots), but they do not occur in same sample twice (or >2). Rationale behind doing this was to remove such variants possibly mapping to multiple transcripts of the same gene. You can double check it, if you have transcript information in annotations. If you would like to keep all of them, then there is an argument in `read.maf` not to remove them. May be try reading maf with `removeDuplicatedVariants = FALSE` ? 
Hope it was clear.

**Comment by patidarr** [comment]
Ahh, should have looked at read.maf more carefully. 
Thanks!!
