### ISSUE TITLE
require(maftools) Error

### ISSUE THREAD

**Issue by WatsonCrick2018** [PoisonAlien/maftools#114]
Dear PoisonAlien,

I tried to use Maftools but when I type 
> require (maftools)

I have the following error:
 Loading required package: maftools
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘maftools’

What should I do so I can read maftools package?

**Comment by WatsonCrick2018** [comment]
I figured it out.

**Comment by banerjeeshayantan** [comment]
@WatsonCrick2018 I am facing the same problem. Can you share what you did to fix the problem?

**Comment by PoisonAlien** [comment]
Hi,
How did you install the package ? Can you post your sessionInfo ?

**Comment by banerjeeshayantan** [comment]
Thanks for your help. I fixed the issue. I was using an older Bioconductor version.
