### ISSUE TITLE
Error in Reading TriNucleotide Matrix

### ISSUE THREAD

**Issue by WatsonCrick2018** [PoisonAlien/maftools#115]
Dear PoisonAlien,

Thanks for creating such a wonderful tool!

When I typed the following command from the maftools website:

> laml.tnm = trinucleotideMatrix(maf = laml, ref_genome = '/path/to/hg19.fa', 
                               prefix = 'chr', add = TRUE, ignoreChr = 'chr23', useSyn = TRUE)

I got the following error:
reading /path/to/hg19.fa (this might take few minutes)..
Error in .Call2("new_input_filexp", filepath, PACKAGE = "XVector") : 
  cannot open file '/path/to/hg19.fa'

How can I fix the error?

Thanks!

Watson-Crick2018

**Comment by PoisonAlien** [comment]
Hello!

`ref_genome` should point to a reference genome file located on your machine. '/path/to/hg19.fa' is just an example.

**Comment by dschslava** [comment]
Thank you so much!
