### ISSUE TITLE
miss data

### ISSUE THREAD

**Issue by Tina9** [PoisonAlien/maftools#116]
Hi PoisonAlien,

I got a strange result when I draw the oncoplot. All my samples have EGFR mutations, but the oncoplot didn't show 3 samples. And the In_Frame_Del didn't appear. So does maftools filter any data before it plot?

Thanks for your help.

Tina

**Comment by PoisonAlien** [comment]
Hi,
maftools only uses non-synonymous variants with functional impact for plotting and other downstream analysis. 

By default these are the ones considered as non-syn variants.

```
"Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site", "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del","In_Frame_Ins", "Missense_Mutation"
```

Those missing EGFR mutations, are they non-synonymous variants ? Also run this command and see how many patients have this EGFR mutations.

```r
lapply(genesToBarcodes(maf = maf, genes = 'EGFR', justNames = TRUE), length)
```

**Comment by Tina9** [comment]
I ran the command and the result was the same as the result of oncoplots. I will follow the way you provide to check the data.

Thank you so much.

Tina
