### ISSUE TITLE
add genelist to oncoplot/oncostrip

### ISSUE THREAD

**Issue by jharenza** [PoisonAlien/maftools#117]
Please add the ability for genes to take a list, rather than naming each gene of interest, when graphing oncoprints. Thanks!

**Comment by PoisonAlien** [comment]
Go it! I will follow up on this soon.

**Comment by patidarr** [comment]
Could tstv also be added to oncoprint? Thanks!!

**Comment by jharenza** [comment]
The list works with oncoplot!
