### ISSUE TITLE
Error when plotting "plotmafSummary"

### ISSUE THREAD

**Issue by shirleydaidai** [PoisonAlien/maftools#12]
Hi,
I can successfully plot maf summary plots using your demo data. But when I created my own plot, an error jumped out:
`> plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE)

Error in `[.data.table`(vt.plot.dat, , c(2:4), with = FALSE) : 
  j out of bounds
`
Can you figure out what's the problem?
Thanks!

**Comment by PoisonAlien** [comment]
Hi, what version of maftools are you using ? This has been fixed #9 after 0.99.40
Can you try updating and let me know ?

**Comment by shirleydaidai** [comment]
I'm using Version: 0.99.31. I will update it and let you know if it fixed.

**Comment by shirleydaidai** [comment]
It works. Thanks!
