### ISSUE TITLE
add new variant classifications

### ISSUE THREAD

**Issue by jharenza** [PoisonAlien/maftools#121]
In Jan. 2018, SNPEff released a new version using a new variant annotation (per their website, below):

_This new format specification has been created by the developers of the most widely used variant annotation programs (SnpEff, ANNOVAR and ENSEMBL's VEP) and attempts to: provide a common framework for variant annotation, make pipeline development easier, facilitate benchmarking, and improve some known problems in variant annotations._

Please add additional variant classifications as an enhancement. http://snpeff.sourceforge.net/VCFannotationformat_v1.0.pdf

**Comment by PoisonAlien** [comment]
Thank you for this. This is a good resource, I will add the missing ones.

**Comment by chjp** [comment]
Hi, is there a way to use custom variant classifications? e.g. I want to use "pathogenic" and "non-pathogenic" only.

**Comment by PoisonAlien** [comment]
Yes, you can. You will have to use the argument `vc_nonSyn` argument in `read.maf` to define your own set of variant classes. 
That being said, you will also have to define color codes for these VC's while plotting.
