### ISSUE TITLE
mafSurvival samples functionality

### ISSUE THREAD

**Issue by mcewenrk** [PoisonAlien/maftools#122]
Hello,

I've been trying to use the "samples" option in mafSurvival to subset on a clinical attribute instead of a gene status but without success. Could you provide some example code of how to use this please. I've looked at the code and the docs but have been unable to make any progress.
Thanks.

**Comment by PoisonAlien** [comment]
Hi,
could you post your command? `sample` argument takes a vector of samples names of interest and compares against rest of the samples. 

For laml example from package vignette,

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml.clin <- system.file("extdata", "tcga_laml_annot.tsv", package = "maftools")
laml <- read.maf(maf = laml.maf,  clinicalData = laml.clin)

#These are samples from M2 subtype of AML
m2.samples = as.character(getClinicalData(laml)[FAB_classification %in% 'M2', Tumor_Sample_Barcode])

mafSurvival(maf = laml, samples = m2.samples, time = 'days_to_last_followup', Status = 'Overall_Survival_Status', isTCGA = TRUE, groupNames = c("M2", "Rest"))
```

**Comment by mcewenrk** [comment]
Thank you - that's clear now - I was trying to pass two lists of sample IDs as well as other ways of using this option.
Thanks for clarifying!
