### ISSUE TITLE
Enhancement Request - Frequency of Mutations Co-Occuring in Pairs of Genes 

### ISSUE THREAD

**Issue by dschslava** [PoisonAlien/maftools#124]
Dear PoisonAlien,

Is there a way to show the frequency of mutations that are co-occuring in two genes at the same time such as TTN and TP53?

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Where would you like to show this ? on oncostrip plot?

**Comment by PoisonAlien** [comment]
Hi,

Lollipop plots are meant to show distribution of variants on a protein structure. So it will be per gene. Oncostrip can be done. I will do it soon.

**Comment by dschslava** [comment]
Sounds good!
