### ISSUE TITLE
Potential Wrong Legend in Somatic Interaction Function somaticInteractions ()

### ISSUE THREAD

**Issue by dschslava** [PoisonAlien/maftools#125]
Dear PoisonAlien,

Thank you so much for creating the powerful cancer gene analysis tool. Today is the President's Day in the US and I don't have school. 

It seems to me that in section 7.1 Somatic Interactions (https://www.bioconductor.org/packages/3.7/bioc/vignettes/maftools/inst/doc/maftools.html#7_analysis), the legend is not compatible with the data below it. It seems to me that the for the legend, the green should be at the bottom and the red should be at the top.

The reason is that 
## 11:   TP53   FLT3 0.0124927250  0.0000000 125 NA 52 15      Mutually_Exclusive

Could you also explain how the oddsRatio is defined and what  the four numbers 00, 11, 01, 10 mean?

My two cents.

Thanks again!

Student at Canyon Crest Academy H.S.

**Comment by PoisonAlien** [comment]
Hello,

I think you're mis-interpreting the plot. Green shows tendency towards co-occurance. Means these two genes (RUNX1 and ASXL1) tend to be mutated together in same samples. Their position in the plot has nothing to do with them being red or green. 

```
00 - none of the genes are mutated 
01 - first gene wt (non-mutated) second gene is mutated
10 - second gene wt (non-mutated) first gene is mutated 
11 - both genes are mutated
```

For RUNX1 and ASXL1, of the 5 ASXL1 mutations - 4 of them co-occur with the RUNX1, hence high odds ratio (by Fishers exact test). 

Vice versa for TP53 and FLT3. 

Hope this helps.

**Comment by dschslava** [comment]
Dear PoisonAlien,

Thank you so much for your explanation! I'll think about it to make sure I understand. Will write you back if I have more questions.

Thanks again!
