### ISSUE TITLE
APOBEC plots

### ISSUE THREAD

**Issue by CynStr** [PoisonAlien/maftools#127]
First, thanks for this great package.

I'm having a few issue with my plots using plotApobecDiff.

1. plots are getting cutoff at the y axis of the boxplot 
2. values around the pie graph do not include the "tCw" or "non-tCw" text seen in the vignette 
3. my bar chart does not have a title 

#2 and #3 are no big deal since I can edit the function myself to address but just thought I would mention it but I'm not sure how to increase the space on the left of the plot so that the y axis doesn't get cutoff.

Thanks in advance,
Cynthia

**Comment by PoisonAlien** [comment]
Hello,

How did you install the package ? from GitHub ?
Can you save the plot to an output pdf and see if it still the case ?

**Comment by CynStr** [comment]
Yes it stays cut off no matter how I save it. I got the latest package from GitHub last night just to make sure.   It cuts it for my larger dataset but not the smaller one

**Comment by PoisonAlien** [comment]
Could you try installing again and let me know if it works? I have also added two more arguments to control axis width and font size.

**Comment by CynStr** [comment]
Thanks, no longer cut off.

 Only other issue I notice now is that some values on the boxplots (grey dots) are under the boxplot title and trail off the page. So, boxplot title is too low. After checking prior runs, I see that this was the case before as well, I just hadn't noticed.

**Comment by PoisonAlien** [comment]
Hi,
Yes, I tried to limit y axis till box plot edges, but I guess outliers are still outside the plot. I will probably remove them.
