### ISSUE TITLE
Will maftools work for R 3.3.3 ?

### ISSUE THREAD

**Issue by kb472** [PoisonAlien/maftools#129]
I have a Mavericks OS , so can only run R 3.3.3, and cannot upgrade to the latest R or Bioconductor . Is there anyway to get maftools working for R 3.3.3 ?

When I tried to install it, I got this error:
`> library(maftools)`
`Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called ‘slam’`
`Error: package or namespace load failed for ‘maftools’`

`> install.packages("slam")`
`Warning in install.packages : package ‘slam’ is not available (for R version 3.3.3)`

`biocLite()`
`BioC_mirror: https://bioconductor.org`
`Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.3 (2017-03-06).`

I've also tried installing this package directly from github, but still can't get the package to work.
`install_github("PoisonAlien/maftools")`

Can you please help ?

**Comment by PoisonAlien** [comment]
Hello,

Can you try installing from Github again ? However I can't guarantee that it will work (other dependencies might fail).

**Comment by kb472** [comment]
Hello, Thank you for your message.

Tried again , still same error

> install_github("PoisonAlien/maftools")
Downloading GitHub repo PoisonAlien/maftools@master
from URL https://api.github.com/repos/PoisonAlien/maftools/zipball/master
Installing maftools
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/ww/86qycsxx2_jgplc2vzzsl80m0000gn/T/RtmpFJHyKB/devtools110ab3bdc1051/PoisonAlien-maftools-3cf0578'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library'  \
  --install-tests 

* installing *source* package ‘maftools’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘slam’
ERROR: lazy loading failed for package ‘maftools’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/maftools’
Installation failed: Command failed (1)

**Comment by kb472** [comment]
I did the following, and I think I got it working. Thank you !

install.packages('devtools')
library(devtools)

slam_url <- "https://cran.r-project.org/src/contrib/Archive/slam/slam_0.1-37.tar.gz"
install_url(slam_url)

install_github("PoisonAlien/maftools")

**Comment by PoisonAlien** [comment]
Nice. 
I am closing this for now.
