### ISSUE TITLE
remove white from oncoprint

### ISSUE THREAD

**Issue by apastore** [PoisonAlien/maftools#130]
Hi I love this package. What I missing is a way to remove the white from the oncoprint?
Do you have any idea how I could get it there?
Thanks a lot!

**Comment by PoisonAlien** [comment]
Hi,
Glad you find the package useful. But I do not understand the question ? Which part would you like to remove ?

**Comment by apastore** [comment]
Sorry !
I mean the white/gray spaces between each patients. Basically the grey/white background grid. 

One more thing. Is possible to extract the patients order from an oncoprint and use the same order in the Transition/Transversion plot?

Thanks a lot!

**Comment by PoisonAlien** [comment]
Hi,
1. Sorry there is no option to remove the background grids. Also they help to separate samples and removing them would only make the plot indistinguishable. 

2. This is again not doable for now, but I will implement it soon. You can get the patient order by setting `writeMatrix = TRUE` in  `oncoplot` function. oncostrip is just oncoplot with `drawRowBar` and `drawColBar` set to `FALSE`.

Hope this helps.
