### ISSUE TITLE
Tumor_sample_barcode does not have sample id

### ISSUE THREAD

**Issue by kb472** [PoisonAlien/maftools#131]
Hello,
I'm trying out maftools for the first time to convert my vcf file  to maf file. Almost everything looks good, except the `Tumor_sample_barcode` column says "TUMOR" and not the sample id. I do not have a matching normal sample id. 

Not sure if I am doing something wrong  ? This is the command I used: 
`perl vcf2maf.pl --input-vcf T_077.vcf --output-maf T_077.maf --vcf-tumor-id T_077`

Any advise is helpful. Thank you.

**Comment by PoisonAlien** [comment]
Hi,

This is not really related to maftools. You can try posting this on [vcf2maf](https://github.com/mskcc/vcf2maf)
@ckandoth

**Comment by ckandoth** [comment]
@kb472 your missing argument is `--tumor-id`, which is `TUMOR` by default.

**Comment by kb472** [comment]
Thank you , yes figured out how to get it working. Closing the issue now.
