### ISSUE TITLE
oncoplot drawRowbar

### ISSUE THREAD

**Issue by Indigofera** [PoisonAlien/maftools#133]
Hi, 

I have tried to change the order of categories in row barplot. I have not found yet. I have five groups like E1, ..., E5 from blue color to red color. But I want to draw from E5 to E1 from red color to blue color. I could change to column bar plot, but it does not work for row bar plot. How can I do that?  
<img width="171" alt="screen shot 2018-03-15 at 11 44 20 am" src="https://user-images.githubusercontent.com/8021354/37474262-4d41073a-2846-11e8-8654-c186255b90af.png">

**Comment by PoisonAlien** [comment]
Hi,
Apologies for late reply. Sorry for now its not possible, as it draws from least to most frequent events. I will make an option for it soon.

**Comment by Indigofera** [comment]
Thanks
