### ISSUE TITLE
Legend typo for somatic interaction plot

### ISSUE THREAD

**Issue by pwwang** [PoisonAlien/maftools#135]
In section "7.1 Somatic Interactions" from your document:

![somainteraction](https://raw.githubusercontent.com/pwwang/maftools/master/vignettes/maftools-somainteractions.png)

The legend of the figure should be `log10(odds-ratio)` instead of `log10(p-value)`.
Obviously, `log10(p-value)` cannot be a positive number.

**Comment by PoisonAlien** [comment]
Hello,

Thanks for pointing it. 
They're indeed p-values on log10 scales and you're correct regrading them being non-negative. Odds ratios are used to decide exclusiveness or co-occurances but log10 transformed p-values are used to plot heat map. I represent p-values in negative scales for exclusiveness just to differentiate it from co-occurance; guess I forgot to change the symbol. I will update it soon.

**Comment by pwwang** [comment]
This makes sense now.
![image](https://user-images.githubusercontent.com/1188067/42057120-2762d4a2-7ad1-11e8-865b-8246a32e6e10.png)
Thanks.
