### ISSUE TITLE
maftools installation problem

### ISSUE THREAD

**Issue by rong923** [PoisonAlien/maftools#136]
#########The message from installing maftools
The downloaded source packages are in
	‘/private/var/folders/kw/jpc0q95967vg05dcht3z9yym0000gn/T/RtmpQvsiHm/downloaded_packages’
Warning messages:
1: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘mvtnorm’ had non-zero exit status
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘fpc’ had non-zero exit status
3: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘dendextend’ had non-zero exit status
4: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘nlme’ had non-zero exit status
5: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘RcppArmadillo’ had non-zero exit status
6: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘rgl’ had non-zero exit status
7: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘mgcv’ had non-zero exit status
###############
> library("maftools")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘dendextend’
Error: package or namespace load failed for ‘maftools’

Does anyone know the issue? Truly appreciated!

**Comment by PoisonAlien** [comment]
Hello,

Can you post your sessionInfo ? How did you install ?

**Comment by rong923** [comment]
Hi thanks for the reply.

I downloaded this way:
source("https://bioconductor.org/biocLite.R")
biocLite("maftools")

I see a lot of this for packages

ERROR: compilation failed for package ‘mgcv’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/mgcv’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/mgcv’

The downloaded source packages are in
	‘/private/var/folders/kw/jpc0q95967vg05dcht3z9yym0000gn/T/RtmpgybAQa/downloaded_packages’

**Comment by rong923** [comment]
Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.3 (2017-03-06).
Installing package(s) ‘maftools’

**Comment by PoisonAlien** [comment]
Hi,
Try updating your R and bioconductor versions. They seem to be old. Current R versions 3.4.4 and Bioconductor version is 3.6
Let me know if this helps.

**Comment by rong923** [comment]
Thanks the new versions worked.
