### ISSUE TITLE
plotCBSsegments function plots without genes 

### ISSUE THREAD

**Issue by ymavura3** [PoisonAlien/maftools#137]
Hi, I used the function plotCBSsegments in order to visualize genes affected by copy number alteration. Unfortunately, the plot gets plotted without the gene names showing, even after specifying a couple of genes eg genes = "MUC16". please advice.

**Comment by ymavura3** [comment]
p7_met2.seg <- ("/PATH/p7_met_noDip_gistic_input.tsv")
plotCBSsegments(cbsFile = p7_met2.seg, maf = laml, labelAll = TRUE)

The plot is drawn, without gene names.
Additionally, the following warnings are produced:

1: Removed 2 rows containing missing values (geom_segment). 
2: Removed 8247 rows containing missing values (geom_point). 
3: Removed 8247 rows containing missing values (geom_text_repel).

**Comment by PoisonAlien** [comment]
Hi,
what is laml here ? Is it an MAF object ?

**Comment by PoisonAlien** [comment]
I can only think of one possibility, is the sample name in your segmentation file same as the one in MAF file ? Make sure they match or else it will only plot the segmentation.
