### ISSUE TITLE
error in extractSignatures:  (list) object cannot be coerced to type 'double' [in call to 'which.min']

### ISSUE THREAD

**Issue by solovictor** [PoisonAlien/maftools#138]
Hi,
most of tested procedures worked perfectly (such as 
plotApobecDiff(tnm = laml.tnm, maf = laml) , for example, just I have problem with extractSignatures.
Please look at the output and resolve.
Best Regards, Victor
> laml.sign = extractSignatures(mat = laml.tnm, nTry = 3, plotBestFitRes = FALSE)
Estimating best rank..
Timing stopped at: 16.39 6.268 3.847
Timing stopped at: 19.64 7.504 5.454
Error in (function (...)  : All the runs produced an error:
	-#1 [r=2] -> (list) object cannot be coerced to type 'double' [in call to 'which.min']
	-#2 [r=3] -> (list) object cannot be coerced to type 'double' [in call to 'which.min']

**Comment by PoisonAlien** [comment]
Hi,
Can you load `NMF` library and try again ?

**Comment by solovictor** [comment]
Hi,

I did and it is not helping:

> require("NMF")
> laml.sign = extractSignatures(mat = laml.tnm, nTry = 6, plotBestFitRes =
FALSE)
Estimating best rank..
Timing stopped at: 15.55 6.024 3.676
Timing stopped at: 18.22 13.99 9.147
Timing stopped at: 25.8 9.721 6.922
Timing stopped at: 39.45 12.5 8.235
Timing stopped at: 41.16 12.22 8.611
Error in (function (...)  : All the runs produced an error:
        -#1 [r=2] -> (list) object cannot be coerced to type 'double' [in
call to 'which.min']
        -#2 [r=3] -> (list) object cannot be coerced to type 'double' [in
call to 'which.min']
        -#3 [r=4] -> (list) object cannot be coerced to type 'double' [in
call to 'which.min']
        -#4 [r=5] -> (list) object cannot be coerced to type 'double' [in
call to 'which.min']
        -#5 [r=6] -> (list) object cannot be coerced to type 'double' [in
call to 'which.min']


Unless some warning important when I first request NMF:

> require("NMF")
Loading required package: NMF
Loading required package: pkgmaker
Loading required package: registry

Attaching package: ‘pkgmaker’

The following object is masked from ‘package:base’:

    isNamespaceLoaded

Loading required package: rngtools
Loading required package: cluster
NMF - BioConductor layer [OK] | Shared memory capabilities [NO: bigmemory]
| Cores 7/8
  To enable shared memory capabilities, try: install.extras('
NMF
')

**Comment by PoisonAlien** [comment]
This is weird. Could you try install NMF from GitHub and see if it helps. 

```r
devtools::install_github("renozao/NMF")
```

**Comment by solovictor** [comment]
unfortunately not helping.  In R console even produce *segfault*
*(while pdlotapobecdiff and others are working OK)*


> require("NMF")
*Loading required package: NMF*
*Loading required package: pkgmaker*
*Loading required package: registry*
*Loading required package: rngtools*
*Loading required package: cluster*
*NMF - BioConductor layer [OK] | Shared memory capabilities [NO: bigmemory]
| Cores 7/8*
*  To enable shared memory capabilities, try: install.extras('*
*NMF*
*')*
>  laml.sign = extractSignatures(mat = laml.tnm, nTry = 6, plotBestFitRes =
FALSE)
*Estimating best rank..*

* *** caught segfault ****
*address 0x110, cause 'memory not mapped'*

*Traceback:*
* 1: .local(object, ...)*
* 2: fitted(x)*
* 3: fitted(x)*
* 4: .KL(y, fitted(x))*
* 5: obj.fun(x, y, ...)*
* 6: .local(object, ...)*
* 7: deviance(strategy, nmfFit, v, ...)*
* 8: deviance(strategy, nmfFit, v, ...)*
* 9: trackError(nmfData, deviance(strategy, nmfFit, v, ...), niter = i,
force = TRUE)*
*10: .local(object, y, x, ...)*
*11: run(strategyX, y, x, maxIter = maxIter, ...)*
*12: run(strategyX, y, x, maxIter = maxIter, ...)*
*13: .local(object, y, x, ...)*
*14: run(object = <S4 object of class "NMFStrategyIterative">, y = c(0, 1,
1, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0,
0, 0, 1, 0, 1, 1, 0, 1, 2, 1, 0, 2, 3, 2, 2, 3, 0, 2, 0, 1, 1, 1, 1, 0, 1,
0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0*

**Comment by PoisonAlien** [comment]
Hi,
Its hard for me to suggest anything without a reproducible data. Is it possible for you to share the matrix ? Also can you post your sessioninfo after loading maftools and maf ?
