### ISSUE TITLE
Package not loaded error in function extractSignatures()

### ISSUE THREAD

**Issue by lajoiem** [PoisonAlien/maftools#14]
Hi. 
I have installed the package from github, and I get the following error:

> maf_sig = extractSignatures(mat = maf.tnm, nTry = 6, plotBestFitRes = FALSE)
Estimating best rank..
Timing stopped at: 0.001 0 0.001 
Timing stopped at: 0.001 0.001 0.002 
Timing stopped at: 0.001 0 0.002 
Timing stopped at: 0.001 0.001 0.001 
Timing stopped at: 0.003 0.001 0.005 
Error in (function (...)  : All the runs produced an error:
	-#1 [r=2] -> none of the packages are loaded [in call to 'path.package']
	-#2 [r=3] -> none of the packages are loaded [in call to 'path.package']
	-#3 [r=4] -> none of the packages are loaded [in call to 'path.package']
	-#4 [r=5] -> none of the packages are loaded [in call to 'path.package']
	-#5 [r=6] -> none of the packages are loaded [in call to 'path.package']

**Comment by PoisonAlien** [comment]
Hi,

Try loading NMF package before running extractSignatures.

```
library('NMF')
maf_sig = extractSignatures(mat = maf.tnm, nTry = 6, plotBestFitRes = FALSE)
```

**Comment by lajoiem** [comment]
That worked, but
````
install.extras('NMF')
````
was also required.

Thx for the quick reply.

**Comment by PoisonAlien** [comment]
oh! That was not supposed to happen. Let me see why it didn't install it as a dependency.
