### ISSUE TITLE
median option lost target when use plotmafSummary function

### ISSUE THREAD

**Issue by ShixiangWang** [PoisonAlien/maftools#141]
Hello @PoisonAlien ,

When I learn the usage of this package, I find something very strange. The `median` option do not function in `plotmafSummary`  and lost its target.

When use command

```R
plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
```
get

![image](https://user-images.githubusercontent.com/25057508/39392861-4e8817ba-4af0-11e8-8813-1d56f540760c.png)

When use command 

```R
plotmafSummary(maf = laml.plus.gistic, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
```

get

![image](https://user-images.githubusercontent.com/25057508/39392867-7a134b5c-4af0-11e8-83c3-efc93e4a024a.png)

the `laml` and `laml.plus.gistic` are objects from your extend data, I think you know what they mean. 

Do you have any idea to work around?

**Comment by PoisonAlien** [comment]
Hi,
Could you post your sessionInfo ?

**Comment by PoisonAlien** [comment]
Hi, 
Thanks for the report, it was indeed a bug. I have fixed it. Can you install the package from GitHub and see if you have the same issue ? 
Note that on May 1st new bioconductor releases (3_7), and I have made few changes to the package including to the mafsummary plot. You won't be able to add the label, and plot might look bit different.

**Comment by ShixiangWang** [comment]
OK, I am looking forward you latest version. Would you update the usage of these functions at <https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html>? I think I need more time to be familiar with this powerful package.
