### ISSUE TITLE
data.table v1.11.0 will break maftools

### ISSUE THREAD

**Issue by mattdowle** [PoisonAlien/maftools#143]
Dear Anand,
v1.11.0 of data.table is about to go to CRAN. I include all Bioconductor packages in reverse dependency testing.  Thanks for using data.table ... looks like some heavy duty usage!

The NEWS item affecting maftools is this one : 
> Fixed cases where the result of merge.data.table() would contain duplicate column names if by.x was also in names(y). merge.data.table() gains the no.dups argument (default TRUE) to match the correpsonding patched behaviour in base:::merge.data.frame(). Now, when by.x is also in names(y) the column name from y has the corresponding suffixes added to it. by.x remains unchanged for backwards compatibility reasons. In addition, where duplicate column names arise anyway (i.e. suffixes = c("", "")) merge.data.table() will now throw a warning to match the behaviour of base:::merge.data.frame(). Thanks to @sritchie73 for reporting and fixing PR#2631 and PR#2653

```
> ### Name: gisticBubblePlot
> ### Title: Plot gistic results as a bubble plot
> ### Aliases: gisticBubblePlot
> 
> ### ** Examples
> 
> all.lesions <- system.file("extdata", "all_lesions.conf_99.txt", package = "maftools")
> amp.genes <- system.file("extdata", "amp_genes.conf_99.txt", package = "maftools")
> del.genes <- system.file("extdata", "del_genes.conf_99.txt", package = "maftools")
> scores.gistic <- system.file("extdata", "scores.gistic", package = "maftools")
> laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gistic)
Processing Gistic files..
Processing amp_genes.conf_99.txt..
Processing del_genes.conf_99.txt..
Processing scores.gistic..
Summarizing samples..
> gisticBubblePlot(gistic = laml.gistic)
Error in eval(jsub, SDenv, parent.frame()) : object 'Cytoband' not found
Calls: gisticBubblePlot ... transformSegments -> [ -> [.data.table -> eval -> eval
Execution halted
```

`Cytoband` isn't found because that column is now called `Cytoband.y` due to the suffix.

I think it's probably this line in `readGistic()` :
```
cnDt.summary$cytoband.summary = merge(cnDt.summary$cytoband.summary, 
        qval, by.x = "Cytoband", by.y = "Unique_Name", all.x = TRUE)
```
related to the `by.x = "Cytoband"` in that call.

Hope this is ok to update.  Please let us know if you have any trouble.
Best, Matt

**Comment by davidmasica** [comment]
Any known workaround to this?

**Comment by davidmasica** [comment]
Got it... solution below. 

colnames(laml.gistic@cytoband.summary)[5] <- "Cytoband"
