### ISSUE TITLE
Oncoplot MutSig result as matsig input but gene order different q value order!

### ISSUE THREAD

**Issue by lijanan** [PoisonAlien/maftools#145]
Hi ,

I met a question about q value order and gene maf order inconsistent. 
Scripts: re-run example:
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
laml = read.maf(maf = laml.maf)
col = RColorBrewer::brewer.pal(n = 8, name = 'Paired')
names(col) = c('Frame_Shift_Del','Missense_Mutation', 'Nonsense_Mutation', 'Multi_Hit', 'Frame_Shift_Ins',
+                'In_Frame_Ins', 'Splice_Site', 'In_Frame_Del')

laml.mutsig <- system.file("extdata", "LAML_sig_genes.txt.gz", package = "maftools")
oncoplot(maf = laml, colors = col, mutsig = laml.mutsig, mutsigQval = 0.01)

Result:
Figure: PHP6, -log10(q) ~ 5
R/library/maftools/extdata/LAML_sig_genes.txt.gz:
            PHP6, -log10(q) ~ 8
Can you help me about this questions?

**Comment by PoisonAlien** [comment]
Hi,
I dont follow the question. If I understand correctly, gene names in the plot and mutsig results dont match ?

They do seem to match..

```r
#MutSig results
ms[q < 0.01, .(gene, q, logq)]
      gene            q      logq
 1:   FLT3 2.281625e-13 12.641756
 2: DNMT3A 2.281625e-13 12.641756
 3:   NPM1 2.281625e-13 12.641756
 4:   IDH2 2.281625e-13 12.641756
 5:   IDH1 2.281625e-13 12.641756
 6:   TET2 2.281625e-13 12.641756
 7:   NRAS 2.281625e-13 12.641756
 8:    WT1 2.281625e-13 12.641756
 9:  U2AF1 4.503311e-13 12.346468
10:  RUNX1 8.105960e-13 12.091196
11:  CEBPA 3.500301e-12 11.455895
12:   TP53 6.923841e-12 11.159653
13:   KRAS 3.614167e-09  8.441992
14:   PHF6 6.457555e-09  8.189932
15:  STAG2 1.966814e-06  5.706237
16:    KIT 1.137517e-05  4.944042
17:  RAD21 1.137517e-05  4.944042
18:   EZH2 7.463546e-05  4.127055
19:   SMC3 3.732372e-04  3.428015
20:  ASXL1 2.098493e-03  2.678092
21:  SMC1A 2.961696e-03  2.528460
22: GIGYF2 6.378338e-03  2.195292
23: PTPN11 7.664584e-03  2.115511
```


Plot

![rplot](https://user-images.githubusercontent.com/8164062/39698070-8e8e6daa-51f3-11e8-9bc7-3ec19fc0eced.png)

**Comment by lijanan** [comment]
HI，

Sorry , English isn't my native. 
You are crrect about my questions.

But I 'm confused as below: In your result:
14:   PHF6 6.457555e-09  8.189932

You can see in the above figure, PHF6 ,-log10(q-value) ~ 5.

**Comment by lijanan** [comment]
Continued:

As the result:
13:   KRAS 3.614167e-09  8.441992
14:   PHF6 6.457555e-09  8.189932

You can see in the figure,
KIT ,KRAS ~ 8
not KRAS and PHF6.

**Comment by PoisonAlien** [comment]
Ah !! I see it now.. Yes, you are correct. There seems to be some mismatch. I will fix it soon.

**Comment by lijanan** [comment]
Very thanks.

Best wishes for you!

**Comment by lijanan** [comment]
HI，
  very thanks. I'll test it quickly.
