### ISSUE TITLE
plotApobecDiff error with maftools_1.4.28 and  maftools_1.6.05

### ISSUE THREAD

**Issue by jeffchen2000** [PoisonAlien/maftools#146]
> laml.tnm=trinucleotideMatrix(maf = laml, ref_genome = 'hg19.fa',add = TRUE, ignoreChr = c('X','Y','MT'), useSyn = TRUE)
reading hg19.fa (this might take few minutes)..
Extracting 5' and 3' adjacent bases..
Extracting +/- 20bp around mutated bases for background C>T estimation..
Estimating APOBEC enrichment scores.. 
Performing one-way Fisher's test for APOBEC enrichment..
APOBEC related mutations are enriched in 81.818% of samples (APOBEC enrichment score > 2 ; 9 of 11 samples)
Creating mutation matrix..
matrix of dimension 11x96
> plotApobecDiff(tnm = laml.tnm, maf = laml)
Error in file.exists(anno) : invalid 'file' argument

**Comment by PoisonAlien** [comment]
Hi,
I have hard time tracking the issue. Was your maf read along with clinical data ? Is it possible to share your maf file?
