### ISSUE TITLE
Copy number whiskers not resizing when displaying more than 10 genes

### ISSUE THREAD

**Issue by Anjan-Purkayastha** [PoisonAlien/maftools#147]
So I am trying to display the top 15 genes in my cohort of interest:
oncoplot(maf = laml, top = 15, fontSize = 8, colors = col, 
         clinicalFeatures = 'Disease', sortByAnnotation = TRUE, 
         annotationColor = annotcolors,
        legendFontSize = 8,
        annotationFontSize = 8,
        annotationTitleFontSize =8,
        titleFontSize = 8)

It all displays well except for the amplified genes. The orange whiskers representing the "amps" do not seem to resize. 
Any suggestions? Please see attached image.
Thanks,
Anjan
![top7diseaseoncoplotsnvsindelsamps](https://user-images.githubusercontent.com/13382684/40211453-e3297ada-5a18-11e8-8ec9-ba499128b34d.png)

**Comment by PoisonAlien** [comment]
Hi,
Its a known issue, I will fix it soon. 
Meanwhile can you try to save the plot to a pdf and see if it works ? Try playing around with width and height.

**Comment by Anjan-Purkayastha** [comment]
Hello,
Yes, changing the width and height did eventually fix the problem.
Thanks,
Anjan
