### ISSUE TITLE
How does the non-synonymous variants define?

### ISSUE THREAD

**Issue by ShixiangWang** [PoisonAlien/maftools#148]
Dear @PoisonAlien ,

I am curious about how you calculate the `nonsync` mutation, I read your code and find you seem firstly calculate `nonSilent` mutation in `read.maf` function  
```
vc.nonSilent = c("Frame_Shift_Del", "Frame_Shift_Ins", 
            "Splice_Site", "Translation_Start_Site", "Nonsense_Mutation", 
            "Nonstop_Mutation", "In_Frame_Del", "In_Frame_Ins", 
            "Missense_Mutation")
```
and you filter this with 

```
fields = "Variant_Classification", 
                        query = "Variant_Type == 'SNP'"
```

From <https://en.wikipedia.org/wiki/Mutation> I find 

> point mutations that occur within the protein coding region of a gene may be classified as synonymous or **nonsynonymous substitutions**, the latter of which in turn can be divided into **missense or nonsense mutations**

Therefore I directly calculate `nonsynonymous substitutions` by plus `missense` and `nonsense` mutation in `MAF` file.  Is your calculation consistent with this method?

Thanks.

**Comment by PoisonAlien** [comment]
Hi,
You are definition is correct. However this is more to it. Nonsyn mutations are those which result in a faulty protein with modified or no functional properties. These are further classified based on the position it occurs and functional impact it results in. Maftools uses those variants with [high/moderate](https://www.ensembl.org/info/genome/variation/predicted_data.html#consequences) consequences as non synonymous. 
You can change this to your manual list with the argument `vc_nonSyn` while reading maf with `read.maf `. Hope this helps.

**Comment by ShixiangWang** [comment]
@PoisonAlien  Your description about `nonSync` is more reasonable, I dont know if I correctly understand your code. Can you provide the detail how you calculate nonsyn mutation based on `MAF@data`? Some description is okay.  

Thanks.

**Comment by ShixiangWang** [comment]
So all the mutations of `maf@data` slot  are `non-slient` mutation, you store `slient mutation` in `maf@maf.silent` ???

**Comment by PoisonAlien** [comment]
Yes, that is correct. Try `?MAF` for details on MAF object.

**Comment by ShixiangWang** [comment]
3Q.
