### ISSUE TITLE
Can't open MAF file

### ISSUE THREAD

**Issue by kvn95ss** [PoisonAlien/maftools#149]
I've converted wAnnovar output into MAF using annovarToMaf, then I then wrote it into a file (output.maf).
When I tried to open the file again using read.maf(), I get the following error -

> maf=read.maf("output.maf")
reading maf..
NOTE: Removed 34 duplicated variants
silent variants: 245
        ID   N
1: Samples   6
2: 3'Flank   3
3:   3'UTR   3
4:     IGR  12
5:  Intron 204
6:     RNA  23
Summarizing..
Error in dcast.data.table(data = vc, formula = Tumor_Sample_Barcode ~  : 
  Can not cast an empty data.table

Any idea what's going on? Why am I not able to import the file?

**Comment by PoisonAlien** [comment]
Hi,
Can you post your sessionInfo ? How many samples do you have ? 
If I have to guess, error is due to lack of non synonymous mutations in your file.

**Comment by ShixiangWang** [comment]
@kvn95ss  you cannot use functions from `maftools`  on `maf` file which you load via `fread` function. Funtions from `maftools` can only put on `MAF` object or else built in this package.

the `maf` now is a `data.table` or `data.frame`, you can manipulate it by many basic functions of R. 

You can not install R3.5.0 by conda (I tried, I think the newest version is 3.4.3 on R channel). 

Just install newest version of `maftools` via github 

···
#Install maftools from github repository.
library("devtools")
install_github(repo = "PoisonAlien/maftools")
···

**Comment by kvn95ss** [comment]
@PoisonAlien 

The data is from Targeted amplicon sequencing.

I'm going to upgrade maftools and see how it goes.

**Comment by kvn95ss** [comment]
I updated maftools. The last two lines of my error has been replaced by 

>Error in read.maf("SNP_in_cn.maf") : No non-synonymous mutations found
Check `vc_nonSyn`` argumet in `read.maf` for details

Any way I can still process the file? Do I have to change the parameters of vc_nonSyn? 

Any help appreciated!

**Comment by ShixiangWang** [comment]
@kvn95ss  You can run 
```
?read.maf
```

to see the `vc_nonSyn` argument.

It says

> NULL. Provide manual list of variant classifications to be considered as non-synonymous. Rest will be considered as silent variants. Default uses Variant Classifications with High/Moderate variant consequences. http://asia.ensembl.org/Help/Glossary?id=535: "Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site", "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del","In_Frame_Ins", "Missense_Mutation"

Could you try 

```
read.maf("SNP_in_cn.maf", vc_nonSyn=c("3'Flank", "3'UTR",  "IGR", " Intron",  "RNA"))
```

I have not test the code.  

```
vc_nonSyn=c("3'Flank", "3'UTR",  "IGR", " Intron",  "RNA")
``` 

maybe is

```
vc_nonSyn=list("3'Flank", "3'UTR",  "IGR", " Intron",  "RNA")
```

**Comment by kvn95ss** [comment]
@PoisonAlien 

>read.maf("SNP_in_cn.maf", vc_nonSyn=c("3'Flank", "3'UTR",  "IGR", " Intron",  "RNA"))

This worked! I can now import the file as a MAF. Functions like plotmafSummary are also working. 

How can I get the information on per-sample basis?

**Comment by PoisonAlien** [comment]
Hi,

Please refer to [vignette](http://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html). You can use `getSampleSummary`, `getGeneSummary` to access information.

**Comment by ShixiangWang** [comment]
``r`
getSampleSummary(your_maf)
```

can get what you want

For more info, please run following code in you console

```r
browseVignettes("maftools")
```

**Comment by kvn95ss** [comment]
Thanks for the help, much appreciated!

If you don't mind, I'm closing the thread!
