### ISSUE TITLE
order annotation covariate

### ISSUE THREAD

**Issue by shirleydaidai** [PoisonAlien/maftools#15]
Hello,
Is there a way to order the covariate in the annotation file?
e.g. in FAB_classification, when drawing oncoplot, ordered by M1, M2, M3...
Thanks

**Comment by PoisonAlien** [comment]
Hi,
For now there is no option to sort by annotation. Is there any reason to do that ? I think it would destroy original sorting by mutations.

**Comment by shirleydaidai** [comment]
I just want to see different mutation signitures with different annotation subtype.

**Comment by PoisonAlien** [comment]
Hmm.. For now its not possible. Maybe you can subset you MAF according to annotations with `subsetMaf` function and draw individual plots.

For e.g, If I wanted to draw only for M2 samples,
```
llaml.fab.anno = system.file('extdata', 'tcga_laml_fab_annotation.txt', package = 'maftools')
laml.fab.anno = read.delim(laml.fab.anno, sep = '\t')
m2.samples = dplyr::filter(.data = laml.fab.anno, FAB_classification %in% 'M2')
m2.samples$Tumor_Sample_Barcode = gsub(pattern = '-', replacement = '.', x = m2.samples$Tumor_Sample_Barcode) #Just temp step

m2.maf = subsetMaf(maf = laml, tsb = m2.samples$Tumor_Sample_Barcode, mafObj = T)
oncoplot(maf = m2.maf)

```

and do the same for other subtypes. And also once you subset for different covariates, try `coOncoplot` to draw side by side plots. 

Just a suggestion for now if you really want something.
