### ISSUE TITLE
plotmafSummary error

### ISSUE THREAD

**Issue by kvn95ss** [PoisonAlien/maftools#150]
I've loaded a small maf file, and when I use plotmafSummary, I get this error

>Error in seq.default(0, max(colSums(gs.dat)), length.out = 4) : 
  'to' must be a finite number
In addition: Warning message:
In max(colSums(gs.dat)) : no non-missing arguments to max; returning -Inf

There are two such files which are giving this same error. Although they have data from 3-4 samples, the getSampleSummary lists only the sample with missense mutation for both of them.

Am I getting this error because there is only one sample which has a missense mutation?

Any help appreciated!

**Comment by PoisonAlien** [comment]
Hi,
Please accept my apologies for late reply. Yes, your cohort is way too small for plotting stuffs. Use `vs_nonSyn` argument while reading maf to define variant classifications. 

Plus if you can share your maf file thats causing the error, I might be able to track the issue.
