### ISSUE TITLE
R breakdown when try add MutSigCV (v1.2) results to oncoplot function

### ISSUE THREAD

**Issue by ShixiangWang** [PoisonAlien/maftools#156]
Dear @PoisonAlien,

My R breakdown when I try to add results from `MutSigCV` (using [GenePattern](https://genepattern.broadinstitute.org/gp/pages/index.jsf?lsid=urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00320:1.2) MutSigCV version 1.2 module ) to `oncoplot` function in maftools.

![image](https://user-images.githubusercontent.com/25057508/41275687-472ae3b2-6e54-11e8-90de-e2265130a605.png)

To find the problem, I check the `LAML_sig_genes.txt.gz` and compare the content to my result file, and find they are a bit different.

I thought maybe the number of rows is very big so that the program cannot run, I used top signicant genes but got same problem.

Part of my result file show as follows, and file has been upload. 

![image](https://user-images.githubusercontent.com/25057508/41275841-cba21ebc-6e54-11e8-87a2-dca8577ba5ae.png)
[new_LUAD_sig_genes_top.txt](https://github.com/PoisonAlien/maftools/files/2092972/new_LUAD_sig_genes_top.txt)

Could you help me make this work?

Best,

Shixiang

**Comment by PoisonAlien** [comment]
Hi,
Indeed there are way to many sig genes (205!!!) 
Can you try to plot it to pdf instead of printing to console?

```r
pdf(file = "onc.pdf", width = 15, height = 15, paper = "special", bg = "white", pointsize = 9)
oncoplot(...)
dev.off()
```

**Comment by ShixiangWang** [comment]
@PoisonAlien  Thanks, I'll take a try.

**Comment by ShixiangWang** [comment]
@PoisonAlien 

the `pdf()` indeed work, but the figure is not good.

![image](https://user-images.githubusercontent.com/25057508/41326188-75fb3cd6-6ef0-11e8-96d4-44b02b73b5bf.png)


How can I plot the top 10 significant genes? the `top=10` seems not work.

![image](https://user-images.githubusercontent.com/25057508/41325611-d6568f52-6eed-11e8-9c08-b19e310cf6bd.png)

and 

```
pdf(file = "onc2.pdf", width = 15, height = 15, paper = "special", bg = "white", pointsize = 9)
oncoplot(maf = luad_maf, top = 20,  mutsig = luad_mutsig, mutsigQval = 0.1 )
dev.off()
```

give same result with not setting `top` argument. I find the `top` default is 20, but why the plot give more than 20 genes?

Best,
Shixiang

**Comment by PoisonAlien** [comment]
Hi,
top argument is mutually exclusive with mutsig results. If you want to restrict to top, use fdr cut off. It will plot all the genes below fdr threshold (e.g; mutsigQval < 0.001).

**Comment by ShixiangWang** [comment]
Got it. Thanks.
