### ISSUE TITLE
why dose read.maf  function filtered samples  during reading process

### ISSUE THREAD

**Issue by likelet** [PoisonAlien/maftools#159]
I have 500samples in my maf file, after read into R by `read.maf` function, it result into only 200 samples in the returned object.  
it resulted in overestimated mutation rate genes in oncoplot. 

How to get accurate mutation rate displayed in plot ? 
Thanks.

**Comment by likelet** [comment]
Hi ShixiangWang
thanks for your reply. 
I noticed this parameter before, it indeed keep my samples in the maf objec. BTW, I modified your code . 

```R
    maf <- datatable::fread(maf_file)
    table(maf$Variant_Classification)
    vcNames <- names(table(maf$Variant_Classification))

# use read.maf
   maf <- read.maf(maf_file, vc_nonSyn=vcNames
```
But this did not solved my problem yet. When I plot the maf into an oncoplot, it plot all intron mutations as well, which seems bad now. 
To clear my issue, what I concern is:  Is there a way to keep my sample size unchanged in the oncoplot to get a descriptive mutation rate of each gene. For example, leave a totalSize parameter in the  `oncoplot` function. 

I have modified `oncoprint` function from complexHeatmap package, but I think maftools could be better when take this. 

Thanks!

**Comment by ShixiangWang** [comment]
@likelet Yeah, your question is good, maybe this should take into account when use `read.maf` function.

**Comment by likelet** [comment]
@PoisonAlien @ShixiangWang  both are nice guys . 
here is my sessionInfo
![image](https://user-images.githubusercontent.com/3021506/41414954-f5e9832e-7019-11e8-950a-7b7361a3c088.png)

**Comment by PoisonAlien** [comment]
I remember fixing this issue. 
Can you update your maftools package and try again ? You are using an older version.

**Comment by likelet** [comment]
@PoisonAlien 
I updated the package, but it seems the problem still exist.  
![image](https://user-images.githubusercontent.com/3021506/41418660-c0fb2dc6-7022-11e8-9ba2-e9f4cc6f7cd0.png)
is there a way to remove the syn mutations in the oncoplot and keep total sample size unchanged. (it seems  the filter step can only be set in `read.maf`  step)
![image](https://user-images.githubusercontent.com/3021506/41418781-0dd3a614-7023-11e8-8546-69e01ed704b3.png)

**Comment by PoisonAlien** [comment]
How many sample do you have in total ? Whats the title in oncoplot when you just use `read.maf` and `read.maf` with `vc_nonSyn` argument ?

**Comment by likelet** [comment]
I have 550 samples in total (about 300 samples with nonsyn mutations ).  The plot i  posted above was generated by`read.maf` with `vc_nonSyn` arguments (and it includes `intron` type). It dose retain all samples i have. but i want to plot  real nonSyn samples (without intron and silence mutations) with total simple size(550) as denominator to get mutation rate.   
my code 
```R
maf.bloodr<-read.maf("blood/filter.merge.maf",removeDuplicatedVariants =T,useAll = T,vc_nonSyn = vcNames)
pdf(file = "blood/normal.oncoplot0.001.pdf", height = 10,width = 20)
oncoplot(maf = maf.bloodr, top = 50, fontSize = 12)
dev.off()
```
while the vcNames is 
```
[1] "3'Flank"           "3'UTR"             "5'Flank"           "5'UTR"             "Frame_Shift_Del"   "Frame_Shift_Ins"  
 [7] "In_Frame_Del"      "In_Frame_Ins"      "Intron"            "Missense_Mutation" "Nonsense_Mutation" "Nonstop_Mutation" 
[13] "RNA"               "Silent"            "Splice_Site" 
```

**Comment by PoisonAlien** [comment]
You dont have to use `vc_nonSyn` if you dont want to include synonymous variants. Just read your maf without it. But I agree that the total sample size in the title is an issue. I will fix it soon.

**Comment by PoisonAlien** [comment]
Hi, Sorry for the delay. I have pushed a commit to fix this issue. Could you give it a try and let me know if this fixes your problem ?

**Comment by likelet** [comment]
wow, i will try the commit ASAP

**Comment by likelet** [comment]
![image](https://user-images.githubusercontent.com/3021506/41820212-707d7ed6-7800-11e8-87af-151646df48ca.png)
It's fixed ~, good job. :)

**Comment by ZeroFung** [comment]
I have 151 patients in my clinical data, but only 143 patients in maf file, which means there are 8 patients who do not have any kind of mutation. When I read.maf(), the result only contains 143 patients, and oncoplot show 143 patients too, which make the mutation rate a little bit higher than I expected. Is it possible to make it show a results with 151 patients?

**Comment by PoisonAlien** [comment]
Hello @ZeroFung ,
Do these 8 missing samples have any kind of mutation? As in synonymous mutations?

**Comment by ZeroFung** [comment]
No, they don't have any kind of mutation, not even synonymous mutations.

**Comment by PoisonAlien** [comment]
Can you add some dummy synonymous mutations to your maf for your missing samples. One intergenic variant per sample would be enough.

**Comment by ZeroFung** [comment]
Good idea. Thanks for the suggestion!

**Comment by beginner984** [comment]
Sorry, I have a list of genes for which I only want oncoplot but by plotting these genes I see some genes only altered in `< 0.05` of samples. How I can ignore these genes? I tried top argument but again I have them

**Comment by PoisonAlien** [comment]
You should use `genes` argument. See `?maftools` for details.

**Comment by beginner984** [comment]
Thank you, I have used `genes = t(Frankel)`

![Rplot12](https://user-images.githubusercontent.com/43682980/79645042-b0db4080-81a4-11ea-8240-b8c9f9c663f7.png)

**Comment by PoisonAlien** [comment]
What is `t(Frankel)`? 
Example usage is as below.

```r
> my_genes = c("TP53", "TTN", "MUC16", "FLG2", "CSMD3", "HMCN1", "USH2A", 
"AHNAK2", "FLG", "NF1")
> oncoplot(m, genes = my_genes)
```

**Comment by beginner984** [comment]
Thank you for replying 
Frankel is a vector in which I have put my genes of interest

Frankel et al nat genetics 2019 from which I have a list of driver genes 
But most of these genes altered in less than 5 percent of samples     On Saturday, April 18, 2020, 06:48:54 PM GMT+1, Anand Mayakonda <notifications@github.com> wrote:  
 
 


What is t(Frankel)?
Example usage is as below.

**Comment by binbinZhao2017** [comment]
> Hi, I think the other 300 samples have no non-synonymous mutations. But I can push a fix for total variants, can you post your sessionInfo ?

Hi，Are there any parameters for all mutations now? Even if I use

```
vcNames <- names(maf$Variant_Classification) 
maf <- read.maf(maf_file, vc_nonSyn=vcNames) 
```

there will still be mutations counted as silent mutations such as Silent, Intro , RNA, etc in Variant_Classification column.
