### ISSUE TITLE
APOBEC enrichment estimation

### ISSUE THREAD

**Issue by qxxxd** [PoisonAlien/maftools#160]
Hello,

I was trying to calculate the APOBEC enrichment manually, but the result I got is different from the output of the `TrinucleotideMatrix()`

On the line 240 (https://github.com/PoisonAlien/maftools/blob/master/R/TrinucleotideMatrix.R) I found
> `sub.tbl[,APOBEC_Enrichment := (`tCw_to_G+tCw_to_T`/`n_C>G_and_C>T`)/(tcw/C)]`

It seems that the ratio term in the denominator didn't consider the reverse complement cases. Should it be something like `((tcw+wga)/(C+G))`, or did I miss something?

Thanks

**Comment by ShixiangWang** [comment]
@qxxxd 

The method used in maftools is right. The APOBEC should fill `TcW` motif, and in 96 mutation matrix, the "G" base will be transformed to "C". like G>C will be C>G, so the result of signature will not have G>C. You can use the `plotSignatures` in maftools to see this. 

I can give you some description about this.

> APOBECs deaminate cytidines predominantly in a TCW motif (W = A or T). The APOBEC mutagenesis signature is composed of approximately equal numbers of two kinds of changes in this motif: TCW → TTW and TCW → TGW mutations. The analysis calculates the enrichment of the APOBEC mutational signature among all mutated cytosines in comparison with the fraction of cytosines that occur in the TCW motif among ±20 nucleotides surrounding each mutated cytosine on a per sample basis, and is described in detail in Roberts et al. (*__Roberts SA, Lawrence MS, Klimczak LJ, Grimm SA, Fargo D, Stojanov P, et al. An APOBEC cytidine deaminase mutagenesis pattern is widespread in human cancers. Nat Genet. 2013;45:970–6.__*)


> APOBEC_enrich mean the enrichment over random of APOBEC pattern mutations. This is calculated as: 

>*__{[(TCW to TGW) + (TCW to TTW)]/[(C to G) + (C to T)]}/[TCW/C]__*. 

>The enrichment value > 2, which implies that in such samples at least 50% of APOBEC signature mutations have been in fact made by APOBEC enzyme(s). 

> from <https://www.nature.com/articles/s41388-018-0245-9#Sec10)>

**Comment by ShixiangWang** [comment]
https://github.com/PoisonAlien/maftools/blob/9180830198bc4ea1e686ad5ff2030ae3f8ff4146/R/TrinucleotideMatrix.R#L115
https://github.com/PoisonAlien/maftools/blob/9180830198bc4ea1e686ad5ff2030ae3f8ff4146/R/TrinucleotideMatrix.R#L116

The TCW and reverse WGA are used,  they are summarized as `TcW`.

**Comment by qxxxd** [comment]
@ShixiangWang 
Thank you for the prompt reply! And I agree with you that `C->A` is a case that needs to be excluded from the enrichment calculation, based on my understanding. 

And I would like to clarify my question. In the code, the enrichment score was computed as:
https://github.com/PoisonAlien/maftools/blob/9180830198bc4ea1e686ad5ff2030ae3f8ff4146/R/TrinucleotideMatrix.R#L239-L240

where  `tCw_to_G+tCw_to_T` counts the number of both the TCW and the reverse motif WGA:
https://github.com/PoisonAlien/maftools/blob/9180830198bc4ea1e686ad5ff2030ae3f8ff4146/R/TrinucleotideMatrix.R#L232-L233

and `n_C>G_and_C>T` , too, takes the reverse complements into account, as shown in the code below:
https://github.com/PoisonAlien/maftools/blob/9180830198bc4ea1e686ad5ff2030ae3f8ff4146/R/TrinucleotideMatrix.R#L213

but the `tcw` and `C` in the denominator part seem to ignore the complements, because variables `wga` and `G` were separately defined. 
https://github.com/PoisonAlien/maftools/blob/9180830198bc4ea1e686ad5ff2030ae3f8ff4146/R/TrinucleotideMatrix.R#L205-L206

I think this might cause some problems, since the motif counting criteria for the two ratios are not consistent.

And by the way, is there a standard for counting overlapping motifs, such as `TCTCTCT`, when calculating this type of score? I would appreciate it if you could also comment on this.

Thanks!

**Comment by PoisonAlien** [comment]
Hi @qxxxd ,
Thanks for going through the code. Please give me some time, I will get back to you soon by weekend as I am not in the lab at the moment. 

Thanks @ShixiangWang for answering and posting references.

**Comment by ShixiangWang** [comment]
@qxxxd Maybe you are right. 

the second part should calculated as 

tCw+wGa / n_G + n_C

@PoisonAlien  I am looking forward to your answer. You opinion is valuable.

**Comment by ShixiangWang** [comment]
@qxxxd  

I just got a problem about APOBEC, could you help me?

The thing is when a random mutation happen, like C[C>T]C, how could I calculate the probability this mutation is related to APOBEC? in more detail, how can this probability described by Mutation Signature (2 and 13) data (like COSMIC signature <https://github.com/PoisonAlien/maftools/blob/master/inst/extdata/signatures.txt>)

**Comment by PoisonAlien** [comment]
Hello @qxxxd 
You are correct regarding denominator being incorrect. Nice catch and sorry for the sloppy mistake - I will update it soon. 

Regarding overlapping motif, for now motifs are calculated with `trinucleotideFrequency` from Biostrings package which will count all possible combinations. 

For your example:
```r
x = Biostrings::DNAString(x = "TCTCTCT")
trinucleotideFrequency(x = x)
AAA AAC AAG AAT ACA ACC ACG ACT AGA AGC AGG AGT ATA ATC ATG ATT CAA CAC CAG CAT CCA CCC CCG CCT CGA CGC CGG CGT CTA CTC CTG CTT GAA GAC GAG GAT GCA GCC GCG 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   2   0   0   0   0   0   0   0   0   0 
GCT GGA GGC GGG GGT GTA GTC GTG GTT TAA TAC TAG TAT TCA TCC TCG TCT TGA TGC TGG TGT TTA TTC TTG TTT 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   3   0   0   0   0   0   0   0   0 
```

As you can see `TCT` is counted thrice. I am not sure how much these kind of repeats influece the results but if I have to guess - it should not affect much. Maybe one could try @ShixiangWang suggestion and see how it goes, but that would be out of context for now. 

Thanks again to both of you.

**Comment by PoisonAlien** [comment]
feel feel to open the issue if needed.

**Comment by qxxxd** [comment]
Hello @PoisonAlien 

Sorry for reopening this issue. I just got the chance to look at this problem again, and I found another potential issue related to this one.

According to [Roberts et al.](https://www.nature.com/articles/ng.2702),

>  mutationsTCW is the number of mutated cytosines (and guanines) falling in a TCW (or WGA) motif, mutationsC (or G) is the total number of mutated cytosines (or guanines), contextTCW is the total number of TCW (or WGA) motifs within the 41-nucleotides region centered on the mutated cytosines (and guanines) and contextC (or G) is the total number of cytosines (or guanines) within the area 41-nucleotides region centered on the mutated cytosines (or guanines).

As I understand it, the TCW/WGA motifs or C/G in the context are counted only if the mutated C->T/G or G->A/C at the center is present.

For example, below is a summary of my toy data,
![screenshot at 2018-06-26 16 39 32](https://user-images.githubusercontent.com/26338519/41937881-8d5957d6-795f-11e8-91d0-90b6baaf4efb.png)

I believe that to get the TCW frequency in the context, one needs to sum the `tcw` conditioning on the variable `SubstitutionType`, so the code would be like
`n_bg_tcw = sum(tcw[SubstitutionType %in% c("C>T", "C>G")])`
rather than sum over all the rows.

I'm not very certain if my understanding agrees with the idea in the paper, so please forgive me if I'm wrong.

Also, thank you for telling me about the `trinucleotideFrequency` function, that's really helpful!

@ShixiangWang 
Sorry I'm not familiar with the COSMIC signature, but for APOBEC I think the Fisher's exact test described in Roberts et al. might be useful for testing if random mutations within a certain region have the APOBEC pattern.

**Comment by PoisonAlien** [comment]
Hi,

Thanks again for being meticulous and once again apologies for the delay. 
I went through the code and the reference. You are right again - context should be with tcw/wga motif. I have corrected it. 

On my test samples with known APOBEC enrichment, this correction increases the number of samples classified as APOBEC enriched by about 3%. I will push this update to Bioconductor soon.

I really appreciate your corrections - please do let me know if you encounter any other issues.

**Comment by ShixiangWang** [comment]
good to know, it's time to update maftools. :smile:
