### ISSUE TITLE
Several functions not working and not clear how to extract sample specific mutation data

### ISSUE THREAD

**Issue by asmagen** [PoisonAlien/maftools#161]
Hello,

I tried running the manuals here but some functions could not be found:
`could not find function "somaticInteractions"`
I made sure I updated to the latest version of the package through GitHub.

Also, how do I perform the simple task of getting a list of mutated genes for each sample?

Thanks

**Comment by PoisonAlien** [comment]
Hi,
please post your sessionInfo.

**Comment by PoisonAlien** [comment]
Hi,

You are using way older version (maftools_1.2.30) 
Current version is 1.6.07 - please update and let me know if you still have the issue.

**Comment by asmagen** [comment]
Alright, I repeated the install from GitHub again and not it works. Thanks.

So regarding the second question - how can I get sample info from the file as a table or list? I want to get or create a table annotating whether there was any mutation in gene for each sample.

**Comment by PoisonAlien** [comment]
Hi,
I am sorry, somehow your I missed your reply. For the matrix you take a look at the function `mutCountMatrix` 

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
##Generate matrix
mutCountMatrix(maf = laml)
##Generate count matrix of Splice_Site mutations
mutCountMatrix(maf = laml, countOnly = 'Splice_Site')
```

Please let me know if this is something you wanted. 
Again please accept my apologies for the delay.
