### ISSUE TITLE
Changing the row background colour for an Oncoplot

### ISSUE THREAD

**Issue by Anjan-Purkayastha** [PoisonAlien/maftools#164]
Is there an argument in Oncoplot that allows one to change the background colour of each row? Please see attached plot. The background colour is grey- it needs to be changed to white. 
Thanks.
<img width="1123" alt="oncoplot_with_grey_row_background" src="https://user-images.githubusercontent.com/13382684/42098417-dec87af4-7b88-11e8-9304-6591a807c655.png">

**Comment by PoisonAlien** [comment]
Hello!
Sorry for the delay. I have added two arguments to `oncoplot` and `oncostrip` function namely - `bgCol` and `borderCol` to change default grey background and border colours. Could you install from GitHub and let me know if this is something you wanted ?

Usage:
```
oncoplot(maf = laml, top = 5, bgCol = "white") #for what you want
oncoplot(maf = laml, top = 5, bgCol = "white", borderCol = "black") #for white boxes with black border
```

**Comment by Anjan-Purkayastha** [comment]
Dear PoisonAlien,
Sorry for the late reply. Thank you so much! That is exactly what I wanted.

Sincerely,
Anjan

--
Anjan Purkayastha, PhD [C]
Lead for Bioinformatics/Data Science Group,
Biomedical Applications Development Center, BIDS
Frederick National Laboratory for Cancer Research
9605 Medical Center Dr.
Suite 370 Office #5
Rockville, MD 20850
Mobile: 703.740.6939 | Desk: 240-276-6570
anjan.purkayastha@nih.gov

NOTICE: This communication may contain privileged or other confidential information. If you are not the intended recipient, or believe that you have received this communication in error, please do not print, copy, retransmit, disseminate or otherwise use the information. Please indicate to the sender that you have received this email in error and delete the copy you received.

**Comment by PoisonAlien** [comment]
Thanks for confirming. I am closing it for now. Please feel free to re-open if you find any bugs.
