### ISSUE TITLE
showBarcodes not working (data.table has NULL row.names?)

### ISSUE THREAD

**Issue by ahwanpandey** [PoisonAlien/maftools#165]
https://github.com/PoisonAlien/maftools/blob/55867358510447ac852ca19830c0c5f11f7f69ac/R/plotMafSummary.R#L74

Tried the following code with the example data and I can't seem to be able to show the barcodes in the "Variants per sample" plot

```
require(maftools)

laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools') #path to TCGA LAML MAF file
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') # clinical information containing survival information and histology. This is optional

laml = read.maf(maf = laml.maf)

plotmafSummary(
  maf = laml, 
  rmOutlier = TRUE, 
  addStat = 'median', 
  dashboard = TRUE, 
  titvRaw = FALSE, 
  showBarcodes = TRUE,
  textSize = 10,
  fs = 1,
  top = 20
)
```

![image](https://user-images.githubusercontent.com/8450532/42296091-c1337236-8034-11e8-9e2f-7befa6096783.png)

**Comment by PoisonAlien** [comment]
Hi,

Including barcodes there would make the plot pretty crowded and unreadable. But it will work with `dashboard = FALSE` . I will update the docs to make it clear. Hope this helps.

**Comment by ahwanpandey** [comment]
Hey!

Thanks for such positive feedback to my comments!

What I would suggest is at least giving the option to show the names there. I have a cohort of 48 samples and I think I would love to be able to show them there. The dashboard view is awesome!

Dashboard = FALSE does not show all the panels though.

**Comment by PoisonAlien** [comment]
Yes, thats the point. If dashboard style is too crowded setting it to false will just draw variant per sample and variant classification summary.

**Comment by PoisonAlien** [comment]
I have fixed it. Also I have added annotations to the bar plots - you will see when you use it. 
Please let me know if this helps you.

**Comment by ahwanpandey** [comment]
Hello,

Just tested it and it is showing the sample ID's only when "dashboard = FALSE". I understand that it might be illegible for large datasets (as in the attached image of the laml dataset) in the "dashboard = TRUE" view but for smaller datasets I think it would still be nice to have. In any case, I can still make both the TRUE/FALSE plots and use them accordingly. 

Thanks!

![image](https://user-images.githubusercontent.com/8450532/42481316-1c5f75e4-8425-11e8-99d1-43b08f804d8e.png)

**Comment by ahwanpandey** [comment]
Actually, I re-installed the master repo and not "RELEASE_3_7" which is where you made the changes. 

The Sample IDs are now in the dashboard view, thanks! 

But there is an error and the Hugo_Symbol plot. 

```
require(maftools)

laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools') #path to TCGA LAML MAF file
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') # clinical information containing survival information and histology. This is optional

my_maf = read.maf(maf = laml.maf)

plotmafSummary(
  maf = my_maf, 
  rmOutlier = TRUE, 
  addStat = 'median', 
  dashboard = TRUE, 
  titvRaw = FALSE, 
  showBarcodes = TRUE,
  textSize = 0.1,
  fs = 1,
  top = 20
)

Error in dashboard(maf = maf, color = color, rmOutlier = TRUE, titv.color = titvColor,  : 
  object 'laml' not found
```

![image](https://user-images.githubusercontent.com/8450532/42482976-3430ab26-842e-11e8-9a99-44104a6560e3.png)

I have made a comment in the Dashboard.R code for you where "laml" has been hardcoded instead of "maf"

   #--------------------------- hugo-symbol plot -----------------
   gs = getGeneSummary(maf)
   nsamps = as.numeric(**laml**@summary[ID %in% "Samples", summary])

**Comment by PoisonAlien** [comment]
Fixed it. Thanks for going through the code.
