### ISSUE TITLE
pairs empty

### ISSUE THREAD

**Issue by ahwanpandey** [PoisonAlien/maftools#166]
https://github.com/PoisonAlien/maftools/blob/da0d0d28e50c86dfc9686dad92b2cb8d06a70ac2/R/somaticInteractions.R#L191

I believe this should be

`sigPairsTblSig[,pair := NULL]`

and not

`sigPairsTblSig = sigPairsTblSig[,pair := NULL]`

data.table will remove the "pair" column in place when doing `sigPairsTblSig[,pair := NULL]`. Assigning it back to "sigPairsTblSig" causes some problems and the resulting `pairs` in `return(list(pairs = sigPairsTblSig, gene_sets = sig.genes.pvals))` is empty and needs to be invoked twice to actually print.

**Comment by PoisonAlien** [comment]
Ah! I wasn't aware of this. Thanks for the suggestion, will modify it soon.
