### ISSUE TITLE
oncoplot column barplot showing total mutations in all genes rather than just what is displayed in the oncoprint

### ISSUE THREAD

**Issue by ahwanpandey** [PoisonAlien/maftools#167]
First off thanks for this amazing tool! I really appreciate you sharing it with us.

I have a minor suggestion. What I expect from an oncoprint is:

1) row barplot: to show the total number of mutations in a gene per row for all displayed samples in the current oncorpint
2) column barplot: to display the number of genes mutated per sample from the geneset that is currently diplayed in the oncoprint

This is apparent from the ComplexHeatmap's examples:

![image](https://user-images.githubusercontent.com/8450532/42303588-7841c858-8065-11e8-9bd6-123ff1bc9d8a.png)

But what I am seeing from the oncoplot function in maftools is that is displays the total number of mutations in all genes per sample regardless of the geneset on display in the current oncoprint

![image](https://user-images.githubusercontent.com/8450532/42303695-d15c3fcc-8065-11e8-9c30-16fca0edbec1.png)

The row barplot seems to be doing what is it supposed to but the column barplot is not. Is it possible to add a parameter such that the oncoprint's column barplot only show the total number of mutations in the currently displayed genes?

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Thanks for using it and I am glad you find the tool useful. 

Regarding the column bars, In earlier versions of maftools it was the case. Later I changed it since it makes sense to display mutation burden per tumor rather than the displayed pathway. You can see this in most of the TCGA landmark papers, which includes total tumor burden. 

But I agree with your suggestion - I will make it as an argument.

**Comment by ahwanpandey** [comment]
Thanks so much! This tool is really awesome!

I had been doing a lot of what this tool does ad hoc using bits and pieces of code but to have something that is this robust and best of all has amazing documentation is quite rare. Congrats on your achievement!

**Comment by ahwanpandey** [comment]
Also, we are investigating frequently mutated pathways in say Ovarian Cancer and Homologous Recombination Deficiency  (HRD) genes and it would make perfect sense to just view the mutation burden in the pathways.

**Comment by PoisonAlien** [comment]
Yes, this is something I intend to do. Also splitting oncoplot according to pathways. But it might take some time :|

**Comment by PoisonAlien** [comment]
Hi,
I have pushed a commit to address the issues. Could you install it from GitHub and try. Please let me know if these fixes your requirements. 

To limit the column bar graph to the genes included in the plot, run `oncoplot` with `colbar_pathway = TRUE` 

```r
#eg;
oncoplot(laml, colbar_pathway = TRUE, top = 10) 
```

**Comment by ahwanpandey** [comment]
Hey thanks for this!

I am away until early next week but I will test as soon as I am back.

**Comment by ahwanpandey** [comment]
Looks like it's working. Thanks!

![image](https://user-images.githubusercontent.com/8450532/42483082-cabbbe00-842e-11e8-965a-064d342f6d88.png)

**Comment by ahwanpandey** [comment]
Hi,

looks like the latest version of maftools has revertedd back to showing the "total mutations" in the column barplot rather than the mutations in the current pathway?

Can the "colbar_pathway" option be re-implemented? I have a lot of plots I made using the old version and updating to the new version (maftools_2.0.10) would make it difficult to compare directly :(

Thanks!
