### ISSUE TITLE
coOncoplot sort

### ISSUE THREAD

**Issue by mcewenrk** [PoisonAlien/maftools#168]
Hello,
is it possible to specify the sort order of samples in the coOncoplot? A similar functionality to the sortByAnnotation option in the oncoplot would be very useful.

Thanks

**Comment by PoisonAlien** [comment]
Hi,
There is no option to do it for now. But its a nice suggestion, will implement soon and update you. 

Thanks.

**Comment by PoisonAlien** [comment]
Hi,
I have implemented `sortByAnnotation` argument to `coOncoplot`. Could you install from GitHub and let me know if it works for you ?
Thanks.

**Comment by mcewenrk** [comment]
Thanks very much - this implementation works really nicely for me.
Thank you for doing this so quickly!
