### ISSUE TITLE
sampleOrder in oncoplot

### ISSUE THREAD

**Issue by ahwanpandey** [PoisonAlien/maftools#169]
Hello,

I am trying to see if I can change the order of samples in the oncoplot by giving it a list of sample IDs generated by sorting based on some score. I am able to order the oncoplot itself but not the column barplot. I have attached some examples here:

1) This is using default order of the oncoplot function on the laml dataset which looks good

```
test_maf = read.maf(maf = laml.maf)

oncoplot(
          maf = test_maf, 
          top = 10, 
          fontSize = 12,
          removeNonMutated = FALSE, 
          showTumorSampleBarcodes = FALSE, 
          SampleNamefontSize = 8, 
          colbar_pathway = TRUE,
          genes = c("FLT3","DNMT3A","NPM1")
        )
```

![image](https://user-images.githubusercontent.com/8450532/42486815-516bd4a0-8441-11e8-98dc-fb18f3ef08e2.png)

2) now I tried in the oncoplot function using "sampleOrder" by giving it a randomized list of the samples. The main oncoplot seems to be doing what it is supposed to but not the column barplot. The column barplot looks the same as the one above

```
test_maf = read.maf(maf = laml.maf)

sample_order = sample(test_maf@variants.per.sample$Tumor_Sample_Barcode)

oncoplot(
          maf = test_maf, 
          top = 10, 
          fontSize = 12,
          removeNonMutated = FALSE, 
          showTumorSampleBarcodes = FALSE, 
          SampleNamefontSize = 8, 
          colbar_pathway = TRUE,
          genes = c("FLT3","DNMT3A","NPM1")
        )
```

![image](https://user-images.githubusercontent.com/8450532/42486885-98e72c08-8441-11e8-8c26-2acc8e2b3455.png)

**Comment by PoisonAlien** [comment]
Hi,
I have fixed it. Could try again and let me know if this works ? (you can install from master branch)

**Comment by ahwanpandey** [comment]
Hello!

I checked it and now the column bars look like how they should. Thanks!

![image](https://user-images.githubusercontent.com/8450532/42543868-4a2f7c0e-84f1-11e8-8108-64cb33f0a041.png)


But one problem. Now if I plot the top 10 the Y-axis of the column bar is way too high and squashes the detail!

![image](https://user-images.githubusercontent.com/8450532/42543889-5c6cd8bc-84f1-11e8-9005-74291ac61ee4.png)

Same problem with the default ordering of samples:

![image](https://user-images.githubusercontent.com/8450532/42543941-a469d9c6-84f1-11e8-897b-d267c63c856a.png)

It's strange that if I plot the 3 genes in the example above ("FLT3", "DNMT3A", "NPM1") then the column y-axis is has nice limits but not when I plot the top 10.

**Comment by PoisonAlien** [comment]
Hi, 
Sorry for the delay. I somehow missed to follow-up on this. 
I have fixed it. Could you try it out and let me know ?

**Comment by ahwanpandey** [comment]
I think it's fixed now. Thanks!
