### ISSUE TITLE
error in strsplit when plot "coOncoplot"

### ISSUE THREAD

**Issue by shirleydaidai** [PoisonAlien/maftools#17]
Hello,
I used subsetMaf function to subset my dataset by gender. When I plotted coOncoplot with these 2 dataset, an error occured:

> genes=c("USH2A","ASXL3","ARID1A","DCHS1","FMN2","GNAS")
>  coOncoplot(m1 = male.maf, m2 = female.maf, m1Name = 'male', m2Name = 'female', genes=genes)
Error in strsplit(x = variant.classes, split = ";", fixed = TRUE) : 
  non character parameter

Is there a problem with my gene list?
Thanks

**Comment by PoisonAlien** [comment]
Hi,

Can you send me a sample file so that I can see whats going on. You can change barcodes and other details.

**Comment by shirleydaidai** [comment]
I found the error might be due to no mutations in one of the compared MAF.

> print(pt.vs.rt)
$results
     Hugo_Symbol male female        pval       or     ci.up   ci.low
  1:       USH2A   11      0 0.000771904      Inf 2.4659925      Inf
  2:       ASXL3    9      0 0.003384388      Inf 1.8599523      Inf
  3:      ARID1A    8      0 0.007011792      Inf 1.5771181      Inf
  4:       DCHS1    8      0 0.007011792      Inf 1.5771181      Inf
  5:        FMN2    8      0 0.007011792      Inf 1.5771181      Inf
 ---

**Comment by shirleydaidai** [comment]
I tried to add a commonly mutated genes, e.g. TP53, but failed. Can you have a try?
[https://drive.google.com/open?id=0B1-mG_svgrTcS05ocVhWdzZuQXM](url)
[https://drive.google.com/open?id=0B1-mG_svgrTcbGxwMnlxaUkyNVU](url) 
[https://drive.google.com/open?id=0B1-mG_svgrTcbXphRHVhZUx6UFE](url)

**Comment by shirleydaidai** [comment]
Well. I finally got the answer. There must be at least 2 mutations in one of the compared MAF to plot coOncoplot

**Comment by PoisonAlien** [comment]
Hi,
Its not supposed to be the case. It should still draw the plot even when mutations are missing in one of the sample (take a look at the example in vignette, RARA has no mutation). i think this an issue with factor to character conversion. 

Sorry I have a test tomorrow and won't be able to fix it soon. I will work on this over the weekend. Meanwhile can you write those two maf (male and female) to output files (write.mafSummary function) and then read them separately and try to plot and see if it works?

**Comment by shirleydaidai** [comment]
I have output 2 files and re-read in. But this error exists:
```
Error in strsplit(x = variant.classes, split = ";", fixed = TRUE) : 
  non-character argument
```

**Comment by PoisonAlien** [comment]
Hi,
Can you share your samples files ?

**Comment by shirleydaidai** [comment]
https://drive.google.com/open?id=0B1-mG_svgrTcS05ocVhWdzZuQXM
https://drive.google.com/open?id=0B1-mG_svgrTcbGxwMnlxaUkyNVU
https://drive.google.com/open?id=0B1-mG_svgrTcbXphRHVhZUx6UFE

**Comment by PoisonAlien** [comment]
Hi,

I see the issue here, female have no mutations for these genes at all ! So no way to plot them, maybe you include a gene which is mutated in at least one sample among female ? Anyways I have made a temporary fix. You can pull it from github. Target devel brach. 

```
devtools::install_github(repo = "PoisonAlien/maftools", ref = 'devel')
```

P.S: Delete your files, very interesting data.

**Comment by shirleydaidai** [comment]
Thank you!
