### ISSUE TITLE
Somatic Signatures for WGS data

### ISSUE THREAD

**Issue by ahwanpandey** [PoisonAlien/maftools#170]
Hello,

Please correct me if I am wrong, but I believe my understanding of a MAF file is that in only contains annotated variants and everything that is not in annotated regions (eg.. intergenic) are not represented.

http://software.broadinstitute.org/software/igv/book/export/html/166

> In somatic MAFs, to minimize germline contamination, unvalidated mutations are included only if within coding regions and splice sites. Thus, mutations from UTRs, intergenic regions, introns, and other noncoding regions are excluded. Additionally, mutation types are filtered as detailed here. Finally, SNPs present and annotated as other than somatic in dbSNP, COSMIC, or OMIM are removed.

For WGS data I have previously run (MutationalPatterns) that uses VCF files to identify signatures using all the variants called regardless of annotation.

Is there, or can there be a similar functionality in maftools? I wonder how I would represent unannotated variants in a MAF file without breaking any assumptions used by the tool.

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
TCGA usually does not include germline SNPs in their MAF for privacy reasons (See [here](https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/#somatic-maf-file-generation) for the steps). MAF is a file format defined by TCGA for distributing true somatic variants, there is no hard rule saying if you should not include intergenic variants. If your MAF contains such variants its fine - they are usually annotated as `Intergenic` or `Intron`. Maftools will consider them as synonymous according to MAF guidelines. For signature analysis all variants (including synonymous) are used just like any other tool using vcf files.

Hope this helps.

**Comment by ahwanpandey** [comment]
Yup, sounds good. Thanks!
