### ISSUE TITLE
filter maf file

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [PoisonAlien/maftools#171]
I try to filter the maf file for plot only the variants that have more thann 15 % on variant allele fraction (VAF)

```

> on_15<- subsetMaf(maf=f_vars,query="t_vaf > 15")

 oncostrip(maf=on_15,top=20,fontSize=12)
Error in oncostrip(maf = sarc_15, top = 20, fontSize = 12) : 
  trying to get slot "summary" from an object (class "data.table") that is not an S4 object 
```

**Comment by PoisonAlien** [comment]
Hi,
`subsetMaf` returns data.table as an output. Run with `mafObj = FALSE` and it will return as an MAF object, which should work fine.

**Comment by bioinfo-dirty-jobs** [comment]
@PoisonAlien  tanks so much... I have this erro in case I use this:
Error in dcast.data.table(data = vc, formula = Tumor_Sample_Barcode ~  : 
  Can not cast an empty data.table

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay. Error suggests that resulting data.table from subsetMaf function is empty. Could you double check if thats the case ? 

```r
#See if this is zero
nrow(subsetMaf(maf=f_vars,query="t_vaf > 15"))

#Also post output of this command
subsetMaf(maf=f_vars,query="t_vaf > 15")[,.N,Variant_Classification]
```

**Comment by bioinfo-dirty-jobs** [comment]
@PoisonAlien  it is 0 for both....
If I use  .15... works...


subsetMaf(maf=f_vars,query="t_vaf > .15")[,.N,Variant_Classification]
    Variant_Classification      N
 1:      Missense_Mutation 151535
 2:           In_Frame_Ins   1260
 3:            Splice_Site   1025
 4:      Nonsense_Mutation   1662
 5:        Frame_Shift_Ins   1338
 6:        Frame_Shift_Del   1741
 7:           In_Frame_Del   2579
 8: Translation_Start_Site    185
 9:       Nonstop_Mutation    201
10:                    RNA  29454
11:                 Intron 263038
12:                 Silent 151079
13:                  5'UTR   9654
14:          Splice_Region  19657
15:                  3'UTR  15317
16:                5'Flank  28388
17:                3'Flank  23962
18:                    IGR  58731

**Comment by PoisonAlien** [comment]
Great. I am closing this.
