### ISSUE TITLE
Plotting summary of synonymous variants?

### ISSUE THREAD

**Issue by kvn95ss** [PoisonAlien/maftools#172]
The function plotmafsummary does provide a nice insight to the number and types of variants in the samples. However, I was interested to know if synonymous variant types could be plotted in a similar manner as well.

Is it possible? If so how do I go about doing it?

Regards!

**Comment by PoisonAlien** [comment]
Hi,
`plotmafsummary` only plots non-synonymous variants and it is not directly possible to plot synonymous ones. However you could define all your synonymous variant classifications as `non-syn` while reading maf which should do the trick.

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #example maf
#Synonymous  variant classification
silent = c("3'UTR", "5'UTR", "3'Flank", "Targeted_Region", "Silent", "Intron",
                       "RNA", "IGR", "Splice_Region", "5'Flank", "lincRNA", "De_novo_Start_InFrame", "De_novo_Start_OutOfFrame", "Start_Codon_Ins", "Start_Codon_SNP", "Stop_Codon_Del")
#Read maf with vc_nonSyn argument.
laml <- read.maf(maf = laml.maf, vc_nonSyn = silent)
#Plot
plotmafSummary(maf = laml)
```

Hope this helps.

**Comment by kvn95ss** [comment]
Hello!

Thanks, I was able to plot summary by using vc_nonSyn argument. 

Marking as closed!

**Comment by sagarutturkar** [comment]
Thanks! The argument `vc_nonSyn` is very useful.  

I wanted to plot `oncostrip` for synonymous variants for few genes and its need making additional changes to provide named list of colors for all variant types in `vc_nonSyn`.  

I am pasting the code below, might be useful for others:

```r
silent = c("3'UTR", "5'UTR", "3'Flank", "Targeted_Region", "Silent", "Intron")

mycol = RColorBrewer::brewer.pal(n = 6, name = 'Paired')

names(mycol) = c("3'UTR", "5'UTR", "3'Flank", "Targeted_Region", "Silent", "Intron")

oncostrip(maf = laml , genes = c('MYC', 'TP53), 
          showTumorSampleBarcodes = TRUE, colors = mycol)
```
