### ISSUE TITLE
An MAF obj subset by subsetMaf is not an object of MAF

### ISSUE THREAD

**Issue by DadongZ** [PoisonAlien/maftools#173]
I used `subsetMaf` to a MAF object but the subset seems not a MAF object any more but a data.frame. How to reclass it to MAF object?

**Comment by ShixiangWang** [comment]
```
mafObj	
returns output as MAF class MAF-class. Default FALSE
```

You can set this to `TRUE` when you use this function.

**Comment by PoisonAlien** [comment]
Hi,
As mentioned above, run `subsetMaf` with `mafObj = TRUE` and it should return as an MAF object.
