### ISSUE TITLE
somaticInteractions function error

### ISSUE THREAD

**Issue by QANGFQ** [PoisonAlien/maftools#178]
Hello, 

Although somaticInteractions() function works well for tutorial MAF data(tcga_laml.maf.gz), this function doesn't work for my MAF data.
But, Most functions in maftools work well for my MAF data. 

When I used somaticInteractions() function, I got these error messages below.

Error in sigPairs[i, ] : subscript out of bounds
Calls: somaticInteractions -> <Anonymous> -> lapply -> FUN
Execution halted

Why did this happen?
Could you please give me a solution? 

A portion of my MAF data is as follows.

> head(myMAF, n=3)
  Tumor_Sample_Barcode Hugo_Symbol Chromosome Start_Position End_Position
1             Sample-1      SAMD11          1         861369       861369
2             Sample-1      SAMD11          1         865694       865694
3             Sample-1      SAMD11          1         871334       871334
  Reference_Allele Tumor_Seq_Allele2 Variant_Classification Variant_Type
1                G                 -        Frame_Shift_Del          DEL
2                C                 T      Missense_Mutation          SNP
3                G                 T                 Intron          SNP

I downloaded maftools from github.  
There are maftools version and R sessionInfo below.

Thank you!
-----------------------------------------------------
> packageVersion("maftools")
[1] ‘1.7.5’

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS: ~/anaconda2/lib/R/lib/libRblas.so
LAPACK: ~/anaconda2/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=ko_KR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=ko_KR.UTF-8        LC_COLLATE=ko_KR.UTF-8    
 [5] LC_MONETARY=ko_KR.UTF-8    LC_MESSAGES=ko_KR.UTF-8   
 [7] LC_PAPER=ko_KR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=ko_KR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_10.0.8     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
[1] compiler_3.4.3

**Comment by PoisonAlien** [comment]
Hi,
How many samples do you have ?

**Comment by QANGFQ** [comment]
Hi, thank you for your reply!


I tried using small samples less than three samples or large samples like about 100 or 300 samples. But, regardless of sample size, It didn't work... :(


Each sample has about 50000 variants.

However, when I used just 2000 variants in two samples, It didn't work.


I hope to solve this problem!
thank you.

- 권호식 올림
________________________________
보낸 사람: Anand Mayakonda <notifications@github.com>
보낸 날짜: 2018년 8월 20일 월요일 오후 3:58:22
받는 사람: PoisonAlien/maftools
참조: 권호식; Author
제목: Re: [PoisonAlien/maftools] somaticInteractions function error (#178)


Hi,
How many samples do you have ?

**Comment by ShixiangWang** [comment]
@QANGFQ  Maybe you could provide small samples to PoisonAlien so he can debug this error.  You can  drag zip file into comment box.

**Comment by PoisonAlien** [comment]
It would be helpful if you could share your file. 
If its not possible, please give me some time I will get back yo you soon.

**Comment by QANGFQ** [comment]
Because this data is private, I think that sharing data through e-mail would be better.   
Could you let me know your e-mail address?

**Comment by PoisonAlien** [comment]
Hi,
I understand. You can send me to anandmt3@gmail.com - also if its of concern, you could remove any personal data or change sample names.
