### ISSUE TITLE
maftools input file with no chromosomal locations

### ISSUE THREAD

**Issue by Sumithrasank** [PoisonAlien/maftools#179]
I have a file of genes and alterations but there are no chromosomal cooridinates associated with those alterations. Can I use maftools on this file. Here is the first line of the file that I have

Tumor_sample_Barcode gene alteration type mut_type

200_B NF1 D724N SNV missense

Thanks in advance

**Comment by PoisonAlien** [comment]
Hello,
Yes you can use it - but it would be limited to certain functions. For example you won't be able to run signature analysis or change point detection. 

You will have to modify your input data a bit. maftools expects following columns - 

```
Hugo_Symbol, Chromosome, Start_Position, End_Position, Reference_Allele, Tumor_Seq_Allele2, Variant_Classification, Variant_Type and Tumor_Sample_Barcode.
```

I see you have Hugo_Symbol, Tumor_Sample_Barcode, Variant_Classification, and Variant_Type. You can make other columns and fill them up with NA or some dummy values. I think it should work. You might have have to change values in `mut_type` to the standard MAF values such as - `missence` to `Missence_Mutation`, etc.

**Comment by Sumithrasank** [comment]
Thanks this worked.

**Comment by bioinfo-dirty-jobs** [comment]
I ue this code:

Ihave imported from  enrichment pannel a copy number data 
sample99.txt
   ```
chromosome     start       end       segVal
1           1  40356095  40372764   -4.0000000
2           1 115245084 115261621   19.1428571
3           1 204485504 204526342 1731.4285714
4           2  16075982  16090656   -4.0000000
5           2  29416088  30143527   32.5714286
6           3  12626011  12704516   -5.7142857
7           3 138374229 138478187   -0.2857143
8           3 178866308 178952154    7.7142857
```
I use this code 
```
CN_features<-extractCopynumberFeatures(segment_table)
all_components<-fitMixtureModels(CN_features) #(this step is optional)
sample_by_component<-generateSampleByComponentMatrix(CN_features)
chooseNumberSignatures(sample_by_component)
component_by_signature<-generateSignatures(sample_by_component,4)
results<-quantifySignatures(sample_by_component,component_by_signature
```

I have this error:
`Error in rowSums(t_df) : 'x' must be an array of at least two dimensions
`
Could you please help me?

**Comment by ShixiangWang** [comment]
This is not a feature of maftools, you need to refer to other packages or documentation.

**Comment by ShixiangWang** [comment]
If I were right, you should find help from https://github.com/markowetzlab/Drews2022_CIN_Compendium
