### ISSUE TITLE
cnTable option in read.maf

### ISSUE THREAD

**Issue by Sumithrasank** [PoisonAlien/maftools#181]
I would like to include copy number data in my analysis but don't have it in gistic format. I made a custom table (amp.genes) with sample_name,gene,copy_number_status (Amp, in my case). I then include it like
amp.genes = read.delim("full_data_copy_number_status.txt",sep = "\t",header = T)
full_data = read.maf(maf = full_data.maf,cnTable = amp.genes,vc_nonSyn = c("Missense_Mutation","Nonsense_Mutation","Splice_Site","indel"))
But when I do getGeneSummary(full_data), I get sample_names in the Hugo_Symbol column
example shown in attached screenshot. What am i doing wrong?

![screen shot 2018-08-22 at 9 33 10 pm](https://user-images.githubusercontent.com/23560745/44501505-120ae380-a653-11e8-8f15-323d7ce8e5c4.png)

**Comment by PoisonAlien** [comment]
Hi,
Could you post  `head(amp.genes)` ? Columns should be in this order - 'gene_name', 'sample_name', 'cnv_status'. 
I see that your columns are bit out of order. Try fixing it and let me know if it works.

**Comment by Sumithrasank** [comment]
I changed the order of columns in amp.genes and it works fine. A kind suggestions : could you mention the order of the columns in this place in the maftools vignette, it will avoid confusion

5 Reading and summarizing maf files
5.1 Required input files
an MAF file - can be gz compressed. Required.
an optional but recommended clinical data associated with each sample/Tumor_Sample_Barcode in MAF.
an optional copy number data if available. Can be GISTIC output or a custom table containing sample names, gene names and copy-number status (Amp or Del).

**Comment by PoisonAlien** [comment]
Thank you for the suggestion. I will update it soon.
