### ISSUE TITLE
removeNonMutated = FALSE in coOncoplot() function doesn't work for me

### ISSUE THREAD

**Issue by Baiwen224** [PoisonAlien/maftools#182]
hi, i'm trying to keep non mutated events in coOncoplot, but it doesn't work. 
i'm not sure why did this happen.
Could you please give me a solution?

thanks.

**Comment by PoisonAlien** [comment]
Hi,
Could you post your command and sessionInfo ?

**Comment by onkomed** [comment]
I'm having the same problem. Has this been resolved? I'm wondering if it's because the code I see on R for the coOncoplot function is different from the one I see in your documentation:

`function (m1, m2, genes = NULL, m1Name = NULL, m2Name = NULL, 
	clinicalFeatures1 = NULL, clinicalFeatures2 = NULL, annotationColor1 = NULL, 
	annotationColor2 = NULL, sortByAnnotation1 = FALSE, sortByAnnotation2 = FALSE, 
	colors = NULL, removeNonMutated = TRUE, geneNamefont = 10, 
	showSampleNames = FALSE, SampleNamefont = 10, legendFontSize = 10, 
	titleFontSize = 12, keepGeneOrder = FALSE, includeSyn = FALSE, 
	bgCol = "#CCCCCC", borderCol = NA) 
{
	if (is.null(genes)) {
		m1.genes = getGeneSummary(m1)[1:5]
		m2.genes = getGeneSummary(m2)[1:5]
		mdt = merge(m1.genes[, .(Hugo_Symbol, MutatedSamples)], 
			m2.genes[, .(Hugo_Symbol, MutatedSamples)], by = "Hugo_Symbol", 
			all = TRUE)
		mdt$MutatedSamples.x[is.na(mdt$MutatedSamples.x)] = 0
		mdt$MutatedSamples.y[is.na(mdt$MutatedSamples.y)] = 0
		mdt$max = apply(mdt[, .(MutatedSamples.x, MutatedSamples.y)], 
			1, max)
		mdt = mdt[order(max, decreasing = TRUE)]
		genes = mdt[, Hugo_Symbol]
	}
	m1.sampleSize = m1@summary[3, summary]
	m2.sampleSize = m2@summary[3, summary]
	if (is.null(m1Name)) {
		m1Name = "M1"
	}
	m1Name = paste(m1Name, " (n = ", m1.sampleSize, ")", sep = "")
	if (is.null(m2Name)) {
		m2Name = "M2"
	}
	m2Name = paste(m2Name, " (n = ", m2.sampleSize, ")", sep = "")
	m1.oc = getOncoPlot(maf = m1, genes = genes, removeNonMutated = removeNonMutated, 
		colors = colors, showGenes = TRUE, left = TRUE, hmName = m1Name, 
		showTumorSampleBarcodes = showSampleNames, fs = SampleNamefont, 
		gfs = geneNamefont, tfs = titleFontSize, clinicalFeatures = clinicalFeatures1, 
		anno_sort = sortByAnnotation1, annotationColor = annotationColor1, 
		keepGeneOrder = keepGeneOrder, includeSyn = includeSyn, 
		bCol = bgCol, borCol = borderCol)
	m2.oc = getOncoPlot(maf = m2, genes = genes, removeNonMutated = removeNonMutated, 
		colors = colors, showGenes = FALSE, left = FALSE, hmName = m2Name, 
		showTumorSampleBarcodes = showSampleNames, fs = SampleNamefont, 
		gfs = geneNamefont, tfs = titleFontSize, clinicalFeatures = clinicalFeatures2, 
		anno_sort = sortByAnnotation2, annotationColor = annotationColor2, 
		keepGeneOrder = keepGeneOrder, includeSyn = includeSyn, 
		bCol = bgCol, borCol = borderCol)
	oc.list = m1.oc[[1]] + m2.oc[[1]]
	tn = unlist(unique(c(m1.oc[[2]], m2.oc[[2]])))
	tn = unique(unlist(strsplit(x = tn, split = ";", fixed = TRUE)))
	tc = c(m1.oc[[3]], m2.oc[[3]])
	legend = grid::legendGrob(labels = tn, pch = 15, gp = grid::gpar(col = tc[tn], 
		fontsize = legendFontSize), nrow = 2)
	suppressWarnings(ComplexHeatmap::draw(oc.list, newpage = FALSE, 
		annotation_legend_side = "bottom", annotation_legend_list = list(legend)))
}
`

**Comment by PoisonAlien** [comment]
Hi, Could you post your `sessionInfo` please ? You could also try to install from GitHub and see if it helps.

**Comment by onkomed** [comment]
reinstalled from github that solved the issue
