### ISSUE TITLE
subsetMaf only cnv

### ISSUE THREAD

**Issue by Sumithrasank** [PoisonAlien/maftools#183]
Can I subset a maf for only cnvs and show them on a oncoplot?

**Comment by PoisonAlien** [comment]
Hi,
I think you should be able to do it. 
You can use `query %in% 'Amp|Del'` in subsetMaf to restrict your MAF to CNV alterations.

**Comment by Sumithrasank** [comment]
I did this and I get an error

r_updated_amps.maf = subsetMaf(maf = r_updated, query = "Variant_Classification %in% 'Amp'")
r_updated_amps = read.maf(maf = r_updated_amps.maf,isTCGA = F,vc_nonSyn = c("Amp"))
NOTE: Non MAF specific values in Variant_Classification column:
[1] "Amp"
NOTE: Non MAF specific values in Variant_Type column:
[1] "CNV"
Summarizing..
Error in `[.data.table`(vc.cast, , 2:ncol(vc.cast), with = FALSE) : 
  Item 1 of j is 2 which is outside the column number range [1,ncol=1]

**Comment by Sumithrasank** [comment]
I also tried the following 
r_updated_amps.maf = r_updated.maf[r_updated.maf$Variant_Classification == "Amp",]
r_updated_amps = read.maf(r_updated_amps.maf,vc_nonSyn = NULL)
NOTE: Removed 151 duplicated variants
NOTE: Non MAF specific values in Variant_Classification column:
[1] "Amp"
NOTE: Non MAF specific values in Variant_Type column:
[1] "CNV"
silent variants: 86
        ID  N
1: Samples 86
2:     Amp 86
Error in read.maf(r_updated_amps.maf, vc_nonSyn = NULL) : 
  No non-synonymous mutations found
Check `vc_nonSyn`` argumet in `read.maf` for details
I could not resolve this problem

**Comment by PoisonAlien** [comment]
Hello,
Please give me some time, I will get back to you soon.
