### ISSUE TITLE
Interpreting the ClinicalEnrichment output

### ISSUE THREAD

**Issue by abracarambar** [PoisonAlien/maftools#184]
Hi there,
Could you clarify what the column OR_low and and OR_high stand for in the group-wise comparison. And what is the FDR you would recommend to use?

Cheers

**Comment by PoisonAlien** [comment]
Hi,
`OR_low` and `OR_high` are 95% CI of Odds Ratios from Fishers Exact Test. You could use FDR 0.1 or 0.05 - but it depends on you. 
If your sample size is small, I would suggest using p-values instead.

**Comment by abracarambar** [comment]
Thanks for the speedy reply

**Comment by PoisonAlien** [comment]
No problem. Hope it was useful. 
I am closing this for now, feel free to re-open if you have any follow up questions.
