### ISSUE TITLE
Two questions about extdata/tcga_laml.maf.gz. and some functions

### ISSUE THREAD

**Issue by QANGFQ** [PoisonAlien/maftools#185]
Hi,
I have two questions.

Q1.
"extdata/tcga_laml.maf.gz." is example data in maftools. 
I think that "i_TumorVAF_WU" column in extdata/tcga_laml.maf.gz means "Variant Allele Frequency" or "Minor Allele Frequency". 
Therefore, I think that values of "i_TumorVAF_WU" column must be less than 1.
But, there are values of "i_TumorVAF_WU" column which are more than 1 !
Does not "i_TumorVAF_WU" mean variant allele frequency? 
What is "i_TumorVAF_WU"?

Q2.
plotVaf and inferHeterogeneity functions require VAF(Variant Allele Frequency) info.
Is the VAF variant allele frequency within the dataset ?
or in population database(ex. 1000genome, ExAC) ? 

Thank you

**Comment by PoisonAlien** [comment]
Hello!

Q1. Yes, it is variant allele frequency. VAF can be represented as in fractions (0-1) or as in percentage (0-100). Maftools will automatically convert it into fractions.

Q2. VAF is within the MAF file, they are not from population database but instead allele frequency in tumor samples.

Hope this helps.

**Comment by QANGFQ** [comment]
Hello~
Oh, I got it!
Your description is so clear and it is helpful to me.  
Thank you for your reply.
