### ISSUE TITLE
GISTIC plot

### ISSUE THREAD

**Issue by yunsuhk** [PoisonAlien/maftools#187]
hello

I am really enjoying your tool.

Recently, I used gisticChromPlot for 2 significantly different GISTIC outputs.

I want to present those 2 plots back to back as a publication quality, but y axis scale is very different from each other.

It is optimized to present the original data.

For example, ylim of one plot seems c(-2,2) but the other c(-2,6).

Also the size of cytoband is different, even though I set that offset with the same value.

Can I give an option for the absolute size of  y axis scale and cytoband ?

wish your kind reply.

**Comment by PoisonAlien** [comment]
Hi,
Glad it was useful for you. 
`gisticChromPlot` returns ggplot object which you can add on to it. 

```r
g = gisticChromPlot(gistic = laml.gistic, markBands = "all")
g+ylim(-2, 6)
```
But for cytoband size, sorry - you will have to play around offset size.

**Comment by yunsuhk** [comment]
thanks. Now I can change it.

One more question, please.

Can I select only one chromosome to draw plots ?

I wanted to zoom in one certain chromosome with only significant difference.

**Comment by PoisonAlien** [comment]
Hi, sorry for the delay. Could you post your commands ? I think I can make it as an argument. to plot per chromosome.
