### ISSUE TITLE
Could I add the Amp and Del data per hand to MAF matrix and then visualise them in oncoplot?

### ISSUE THREAD

**Issue by batis2ta** [PoisonAlien/maftools#188]
I actually did manually insert Amp and del (CNV) in. I get two notes
NOTE: Non MAF specific values in Variant_Classification column:
[1] "Amp" "Del"
NOTE: Non MAF specific values in Variant_Type column:
[1] "CNV"
and also I will not be able to make an oncoplot containing them. 
I am not using GISTIC because I have WGS copy number data and could not prepare my CNV files for it. As I have only tumor samples I use a control free software (control-FREEC) and it does not have of course markers ._

**Comment by PoisonAlien** [comment]
Hello,
If you know what genes are amplified/deleted, you can make a data.frame or a tsv file out of it and read it along with MAF file. 
Something like this..
```r
genes sample_name cnv
DNMT3A          S1 Amp
 NPM1          S2 Del
DNMT3A          S3 Amp
```

See `cnTable` argument in `read.maf` for details.

**Comment by batis2ta** [comment]
Hi, Thanks a lot for the prompt response. I will do so and let you know on Monday. Best Mo

**Comment by batis2ta** [comment]
Thanks it helped a lot. I was wondering if when making oncoplots, is there an option not to show CNVs? or choose what to show? Another question is if I could do statistics with CNVs like mafCompare? 
if it is the worng place to ask question, just let me know I will ask them there.
Best

**Comment by PoisonAlien** [comment]
1. Nope, for now there is no option to restrict visualization to cnv or mutation data.
2. Yes, you can run mafCompare on maf generated with including cnv.

You can ask your questions here, no problem.

**Comment by batis2ta** [comment]
great thanks. One remaining question is if I could adjust the sizes of CNVs in Boxplot. While try to make the plot with more  than 15 genes they tend to mix with other other rows and cover other vars.
Best

**Comment by PoisonAlien** [comment]
Yesh, its a known issue. 
For now you will have to play around height and width of the plot while saving it to pdf, it seems to work.

**Comment by simonlee184** [comment]
Is it also possible to add the cnTable argument for the coOncoplot as well?

**Comment by PoisonAlien** [comment]
You have to read copy number data along with MAF, it can't be integrated while plotting.
