### ISSUE TITLE
oncoplot - incorporation of GISTIC region with no SNV

### ISSUE THREAD

**Issue by sophiespo** [PoisonAlien/maftools#19]
Hi,
I just recently found this package and it's great.
I was wondering, though - the incorporation of GISTIC data in the oncoplot is really useful, as these sorts of sequencing studies will increasingly use tools list GISTIC. However, as it works right now, the oncoplot won't show CNV in a gene unless a sample has an SNV in it.
For instance, 95% of my samples have a homozygous loss of a particular gene, which then obviously has no SNVs, but I cannot show it on the oncoplot along with the other genes. The genes that have het/hom losses and SNVs will show up.
Is this possible to implement somehow?
Thanks for your great work.
Sophie

**Comment by PoisonAlien** [comment]
Hi,

Glad that you found this tool useful. There is a reason why variants are given preference. Since, most of the copy number altered segments (especially broad segments) harbor huge number of genes, they always tend to populate upper part of oncoplots. But it can be changed easily, just use genes argument to pass a vector of gene names that you want to plot. 

````
myGenes = c('TP53', 'BRCA1', 'BRCA2', 'DNMT3A', 'KIT', 'myCopyNumberAlteredGene')
oncoplot(maf = myMaf, genes = myGenes)
```

Hope this helps.

**Comment by sophiespo** [comment]
Thanks for your quick reply!
This is what I have tried to do. WIthout being too candid (this will be for near future publication), I specify a list of 10 genes. 9 of those genes have SNVs, as well as CNVs from GISTIC2.0. Then the 10th gene has no SNV, but is listed in the most significantly lost region in the del_plot file and is lost in 26 of my 30 samples. I would then expect this gene to show on the oncoplot with only "Del" but it is not shown at all. 
My warning message also does not exclude the gene. It just doesn't show up.

**Comment by PoisonAlien** [comment]
Ohh! That should not be happening. Let me check and get back to you soon. 

Can you check if your gene shows up here ?

```
gis = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, isTCGA = T)
gis.gs = getGeneSummary(x = gis)
gis.gs[Hugo_Symbol %in% 'myCopyNumberAlteredGene']
```

**Comment by sophiespo** [comment]
I've tried that, and sure enough it shows up there.

`> gis.gs[Hugo_Symbol %in% 'myCopyNumberAlteredGene']
   Hugo_Symbol Amp Del total AlteredSamples
1:      myCopyNumberAlteredGene   0  25    25             25`

**Comment by PoisonAlien** [comment]
Oh okay, let me see why this is happening. I will fix it soon.

**Comment by sophiespo** [comment]
Thanks very much for your help with this.

**Comment by sophiespo** [comment]
Hi, I was wondering if you were able to replicate the problem I am having? 
I am happy to speak via email to try help - obviously I don't want to post any data publicly.

**Comment by PoisonAlien** [comment]
Hi,
Yes I was able to replicate the issue with same data that was used in vignette. I have figured out the issue, but didn't get chance to fix it. I will try to finish soon. Sorry for the delay :|

**Comment by sophiespo** [comment]
No need to apologise! I am very grateful of your attention to it - it's a great tool and extremely relevant in this, the age of TCGA data :-)

**Comment by PoisonAlien** [comment]
Hi,
I have pushed a fix. Can you install again from github and try ?

```{r}
devtools::install_github(repo = "PoisonAlien/maftools")
```

Please let me know if you get any errors or needs to be improved.

Thanks.

**Comment by sophiespo** [comment]
Brilliant :) it now includes the gene of interest!
The only thing it isn't doing is sorting the rows. I would have expected them to be sorted from most mutated to least mutated (top to bottom row) but they are just coming up in a different order. I have set the sortByMutation = TRUE but it hasn't changed anything whether I set it to TRUE or FALSE. It's not a deal breaker though. Thankyou!
