### ISSUE TITLE
Oncoplot "top" and CNAs

### ISSUE THREAD

**Issue by mcewenrk** [PoisonAlien/maftools#191]
Hello,

I wanted to clarify the behaviour of the "top" flag in the oncoplot function; I noticed that when I use it with an object which contains CNAs, it doesn't include any genes in the oncoplot which contain only CNAs. That is, it appears to me that the "top" functionality is based only on the frequency of point mutations and doesn't take into account CNAs. It appears to be using the "MutatedSamples" slot in getGeneSummary rather than "AlteredSamples" to select the "top" genes.  Is that correct?

Cheers,
Rob

**Comment by PoisonAlien** [comment]
Hello,
Yes, that is the case. 
If you're processing GISTIC results it is often the case that hundreds of passenger gene are deleted/amplified across all the samples. These genes tend to occupy top list. Thats why top argument uses `MutatedSamples`. If you want to plot top copy number altered genes, you will have to plot it by providing gene names. 
Hope this helps.

**Comment by mcewenrk** [comment]
Thanks for clarifying - that's useful to know.
Cheers
