### ISSUE TITLE
PlotOncogenicPathways

### ISSUE THREAD

**Issue by patidarr** [PoisonAlien/maftools#195]
I like this new feature and its very informative.

Is it possible to plot all the pathways as a single plot? That way I can see if there are samples with aberrations in multiple pathways and what combo therapy could work on them.

Thanks,
Rajesh

**Comment by PoisonAlien** [comment]
Hi,
I am glad that you find it informative. 
No, you cannot plot them all in a single plot for now. But, I will push a  a commit soon to do so. It will be a nice addition.

**Comment by patidarr** [comment]
Thank you, would wait for the commit.
