### ISSUE TITLE
RNASEQ Expression Data

### ISSUE THREAD

**Issue by patidarr** [PoisonAlien/maftools#196]
Hi,

Is it possible to include RNASeq TPM/FPKM values or even a format similar to custom cnv file Gene, Sample, Expression (High, Low), into not only oncoprint but also the new features you developed, pathway analysis and others? 

Again, Already a amazing tool.

Thanks,
Rajesh

**Comment by PoisonAlien** [comment]
This is something I am planning to include it sometime (expression and methylation), but for now its only restricted to mutations.
