### ISSUE TITLE
How to change the colour for clinical feature legends in concoplot?

### ISSUE THREAD

**Issue by SaranyaGLS** [PoisonAlien/maftools#198]
When I generated the cooncoplot with clinical feature like gender, the color for the gender differs between two cohorts and no legend is shown for the other cohort. 
For eg., Male - red and Female - blue. This legend is shown for cohort 1 but the colors are different for cohort 2 with no legend for it. 
why is that? is there any option to show the legend for cohort2 or any option to make the color (for clinical feature) uniform for both the cohorts?

**Comment by PoisonAlien** [comment]
Hi, Could you post your command ? 
You should use `annotationColor1` and `annotationColor2` separately for each cohort.

**Comment by SaranyaGLS** [comment]
Hi,
coOncoplot(m1 = young, m2 = old, m1Name = 'young', m2Name = 'old', clinicalFeatures1 = c("TMB_Class"), clinicalFeatures2 = c("TMB_Class"), sortByAnnotation1 = TRUE, sortByAnnotation2 = TRUE)

**Comment by SaranyaGLS** [comment]
Hi,
Command used:
coOncoplot(m1 = young, m2 = old, m1Name = 'young', m2Name = 'old',
clinicalFeatures1 = c("TMB_Class"), clinicalFeatures2 = c("TMB_Class"),
sortByAnnotation1 = TRUE, sortByAnnotation2 = TRUE)

Thanks,
Saranya Anandan

**Comment by PoisonAlien** [comment]
Thank you. Could you try again with the above mentioned color (`annotationColor1` and `annotationColor2`) arguments ? That should fix it. Let me know if you still have any issues.

**Comment by SaranyaGLS** [comment]
Hi,
Thank you. I tried like you said, but I am getting an error saying:

Error in HeatmapAnnotation(df = annotation, col = annotationColor,
annotation_legend_param = list(title_gp = gpar(fontface = "bold"),  :
  `col` should be a named list.

Command used:
coOncoplot(m1 = young, m2 = old, m1Name = 'young', m2Name = 'old',
clinicalFeatures1 = c("TMB_Class"), clinicalFeatures2 = c("TMB_Class"),
sortByAnnotation1 = TRUE, sortByAnnotation2 = TRUE, annotationColor1 =
c("RED", "BLUE", "GREEN"), annotationColor2 = c("RED", "BLUE", "GREEN"))

Note: This clinical feature TMB_Class has three values "High",
"Intermediate", "Low". I want to fix the uniform colors for these three
values for both cohorts.

**Comment by PoisonAlien** [comment]
You should pass colors as a named list. In your case it would be. 

```r
coOncoplot(m1 = young, m2 = old, m1Name = 'young', m2Name = 'old',
           clinicalFeatures1 = c("TMB_Class"), clinicalFeatures2 = c("TMB_Class"),
           sortByAnnotation1 = TRUE, sortByAnnotation2 = TRUE, 
           annotationColor1 = list(TMB_Class = c("High" = "RED", "Intermediate" = "BLUE",  "Low" =  "GREEN")), 
           annotationColor2 = list(TMB_Class = c("High" = "RED", "Intermediate" = "BLUE",  "Low" =  "GREEN")))
```

You can refer to [this](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#723_changing_colors,_including_mutsig_q-values,_adding_annotations_and_sorting) section of the vignette on how to color code annotations.

Hope this helps.

**Comment by SaranyaGLS** [comment]
Hi,
That's Awesome.  Thank you so much. It worked
