### ISSUE TITLE
Error in OncogenicPathways(maf = laml) :    could not find function "OncogenicPathways"

### ISSUE THREAD

**Issue by tjmuhans** [PoisonAlien/maftools#199]
Hello,
Error in OncogenicPathways(maf = laml) : 
  could not find function "OncogenicPathways"
How can I fix this error?
Thanks 
Ganxun Li

**Comment by PoisonAlien** [comment]
Hi,
Could you post your sessioninfo ? That function is available only in versions >1.8.0.

**Comment by tjmuhans** [comment]
Hi, Alien
When I upload my "maftools" package, it could work well. 
Thank you very much.
Ganxun Li
