### ISSUE TITLE
VCF to MAF conversion?

### ISSUE THREAD

**Issue by crazyhottommy** [PoisonAlien/maftools#2]
Hi,

This is a great tool and I found it very useful. 
most of my variant calls are in VCF format, to use this tool, I have to convert it to MAF first.
Is it possible to do this conversion inside the tool?
Now, I am thinking to use [vcf2maf](https://github.com/mskcc/vcf2maf) from Cyriac.

Thanks,
Ming

**Comment by PoisonAlien** [comment]
Hi,

I am glad that this tool was helpful to you. I am constantly working on new features and vcf to maf is one of them. Meanwhile you can use vcf2maf for conversion. Please let me know if you find any bugs or if you have any suggestions.

**Comment by crazyhottommy** [comment]
Thanks for the great user support!
