### ISSUE TITLE
How to use subsetMaf to subset to Variant_Classification 5'UTR? (i.e. escape single quote)

### ISSUE THREAD

**Issue by Tabea-K** [PoisonAlien/maftools#20]
I am not sure how to escape the single quote after the number 5 in the term `5'UTR` correctly, so that it works in the function subsetMaf. This same problem will also apply to 3'UTR, 3'Flank and 5'Flank.

Here is what I tried so far:

```
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
laml = read.maf(maf = laml.maf, removeSilent = TRUE, useAll = FALSE)
subsetMaf(maf = laml, includeSyn = T, query='''Variant_Classification == "5'UTR"''')
subsetMaf(maf = laml, includeSyn = T, query='Variant_Classification == "5''UTR"')
subsetMaf(maf = laml, includeSyn = T, query='Variant_Classification == "5'''UTR"')

```

However, these lines all result in:
`Error: unexpected string constant in "subsetMaf(maf = laml, includeSyn = T, query='''Variant_Classification == "5'"
`

When I instead remove the single quote from 5'UTR,
`subsetMaf(maf = laml, includeSyn = T, query='Variant_Classification == "5UTR"')
`
I do not get an error message, but an empty output (as no Variant classification 5UTR is known).

I created a small test file, where I replaced all `5'UTR` by `5UTR`, and now the previous line of code works fine, resulting in the expected number of observations.

However, I am sure that there is some smart way to escape the quote character?

**Comment by PoisonAlien** [comment]
Hi,

try this:
```{r}
subsetMaf(maf = m, includeSyn = TRUE, query = "Variant_Classification %in% '5\\'UTR'")
```

above example has no 5'UTR variants, so it should return empty data table.

**Comment by Tabea-K** [comment]
Thanks for your quick reply.
The above command works like a charm!
