### ISSUE TITLE
Adding Fusions to Oncoprints

### ISSUE THREAD

**Issue by Anjan-Purkayastha** [PoisonAlien/maftools#200]
It looks like maftools has been upgraded to display fusions in the waterfall plots. How does one enter the fusion data into maftools?  Is it in the maf file? If so, what are the rules for entering fusion data? Thanks. Anjan

**Comment by PoisonAlien** [comment]
Hi Anjan,

You can put your fusions in MAF files but annotate them as `Fusion` in the `Variant_Classification` column. While reading maf with `read.maf` use `vc_nonSyn` argument to consider `Fusion` as one of the non-synonymous data. Finally, you will have to describe a color code for Fusion events while drawing oncoplots (See [here](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#723_changing_colors,_including_mutsig_q-values,_adding_annotations_and_sorting) for describing colors) . 

Out of curiosity, where did you see this fusion events in the plot ?

Hope this helps. Let me know if you have follow-up questions.
