### ISSUE TITLE
Error in calling "rainfallPlot"

### ISSUE THREAD

**Issue by Tinter7** [PoisonAlien/maftools#201]
Hello,
I used `rainfallPlot()` with the parameter `detectChangePoints = TRUE`, but I got an error:
> Error in paste0(Chromosome, ":", Start_Position) :
> object 'Chromosome' not found  

And then I found that I got an empty `maf.cpt` with`Null data.table (0 rows and 0 cols)` by the function `detect_kataegis`, but when checking it with `is.null(maf.cpt)`, it returned `FALSE`, which made it go to the `else` branch.
It seems the null `data.table` is `NULL` with some attributes attatched, making it not `NULL` anymore, maybe you can refer to this [is.null does not work on null data.table in R](https://stackoverflow.com/questions/15317536/is-null-does-not-work-on-null-data-table-in-r-possible-bug)

**Comment by PoisonAlien** [comment]
Hi Tinter7,

Please accept my apologies for the late reply as I was on vacation. Thank you for pointing and solution to the issue. I will fix it asap.

**Comment by jingquanlim** [comment]
Hi @PoisonAlien , have you managed to find time to push an updated maftools with the patch onto git ? Thanks!

**Comment by PoisonAlien** [comment]
Hi,
This is has been fixed already. Please install from GitHub for the updated version.

**Comment by jingquanlim** [comment]
thanks!

**Comment by Tinter7** [comment]
thanks!
