### ISSUE TITLE
plotmafSummary Customisations

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#204]
The documentation states that if `addStat` can be `NULL`. However, the median is drawn if it is `NULL`. There's no way to turn off the addition of the horizontal line to Variants Per Sample. I also wonder if there could be a customisation of the percentages shown in the Top Mutated Genes panel. Currently, they are grey, but I would like to make them black for better contrast to the white background. Lastly, the Variant Classification Summary boxplots lack labels for each of the categories. I can look at the Variant Classification bar chart to see them, but it unnecessarily forces the viewer's attention to another plot. The return value of the function is NULL, so it doesn't seem to be possible to customise the plot like a ggplot2 plot.

**Comment by PoisonAlien** [comment]
Hi, 
I have fixed `addStat` issue and changed annotations to black font. Thanks for reporting. You may have to reinstall from GitHub. Please let me know if you have any suggestions. Happy to help.

Regarding labels for variant classification, it would make plot crowded with repetitive labels when they are all uniformly color coded. Previous versions had ggplot2 backend for this plot, but I changed to base R for some customisation which weren't possible in ggplot.

**Comment by DarioS** [comment]
I find that `addStat` works as described by the documentation in the latest version; the median line can be omitted. Gene mutation percentages are black and legible on the white background.
