### ISSUE TITLE
Allow Use of SNV Class for oncoplot

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#209]
It would be convenient to be able to pick a particular value of SNV Class and plot an oncoplot, instead of using Variant Classification. For example, being able to plot presence of C to A mutations in genes, a [somatic signature of tobacco smoking](http://science.sciencemag.org/content/354/6312/618), and provide details about the patients' smoking via `annotationDat` could suggest a relationship between smoking and associated gene mutations.

**Comment by PoisonAlien** [comment]
This is a great suggestion. I will implement it soon.
