### ISSUE TITLE
Convert Dataframe to MAF object

### ISSUE THREAD

**Issue by gaiusjaugustus** [PoisonAlien/maftools#21]
Hello,
I have a txt file with all the MAF required columns (plus others) that I would like to use maftools with.  Is there a way to convert this dataframe to a MAF object?

**Comment by PoisonAlien** [comment]
Hi,

Sorry for late reply. For now there is no way to do that. You may have to write it to an external tab delimited file and read it with function `read.maf`. I will implement a function soon to do in future version.

**Comment by PoisonAlien** [comment]
added in version > 1.0

**Comment by crazyhottommy** [comment]
what's the function for it?

**Comment by PoisonAlien** [comment]
Sorry, should have mentioned it. in `read.maf` input can be a data.frame.

**Comment by rasteh** [comment]
I am having the same problem as Gaius. Does any one find a solution for it? How did you solve it Gaius?

**Comment by rasteh** [comment]
Hello
I need to save a data frame to a .maf file in R. Do you know how I can do that?
