### ISSUE TITLE
oncoplot - unused argument (top_annotation_height = grid::unit(2, "cm"))

### ISSUE THREAD

**Issue by tiagochst** [PoisonAlien/maftools#210]
The development version of ComplexHeatmap had some changes, which broke maftools in Bioconductor.

https://www.bioconductor.org/packages/devel/bioc/vignettes/ComplexHeatmap/inst/doc/difference_to_old_versions.html

http://bioconductor.org/checkResults/devel/bioc-LATEST/maftools/

**Comment by tiagochst** [comment]
Actually there is a pull request fixing the problem #205

**Comment by PoisonAlien** [comment]
Hi Tiago,
Please accept my apologies for late response as I was on vacation. I have merged the pull request. I will push it to bioconductor devel branch soon. Thank you.

-Anand.
