### ISSUE TITLE
Can we plot tumor ID in PlotOncogenicPathways

### ISSUE THREAD

**Issue by wangdatou2009** [PoisonAlien/maftools#214]
The plot will be better visualized with tumor barcode in the bottom

**Comment by PoisonAlien** [comment]
Hi,
Thank you for using maftools. I have pushed a commit to fix it. You can use arguments `showTumorSampleBarcodes` and `SampleNamefontSize` to annotate plots with sample names. You will have to install it from GitHub. 
Please let me know if this works for you.

**Comment by wangdatou2009** [comment]
> Hi,
> Thank you for using maftools. I have pushed a commit to fix it. You can use arguments `showTumorSampleBarcodes` and `SampleNamefontSize` to annotate plots with sample names. You will have to install it from GitHub.
> Please let me know if this works for you.

Thanks a lot！It works！

**Comment by DarioS** [comment]
Would naming the parameter `sampleNameFontSize` make the casing consistent with `showTumorSampleBarcodes` and therefore easier for users to remember without having to refer to documentation? It would also be nice if `titv` could be `TiTv`, to make it similar to `plotTiTv` (science journals also capitalise the Ts).
