### ISSUE TITLE
Permit annotationDat Specification for TiTv Plot

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#219]
I like that I can specify a clinical annotation for an Oncoplot and have the columns sorted in order by the values of the clinical variable. This option is also desirable to have for the Ti-Tv plot function. Apart from a clinical variable, it might also be nice to be able to sort the plot's columns in increasing percentage of a particular mutation (for example, C to T).

**Comment by PoisonAlien** [comment]
Hi,
Thank you, this is indeed a good suggestion! I will work on it soon.
