### ISSUE TITLE
Error in readGistic

### ISSUE THREAD

**Issue by lixiangchun** [PoisonAlien/maftools#22]
> library(maftools)
> r2=readGistic(gisticAllLesionsFile='all_lesions.conf_99.txt', gisticAmpGenesFile='amp_genes.conf_99.txt', gisticDelGenesFile='del_genes.conf_99.txt')
> Processing Gistic files..

 **\* caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: rbindlist(l, use.names, fill, idcol)
 2: data.table::.rbind.data.table(...)
 3: rbind(deparse.level, ...)
 4: rbind(ampGenes, delGenes)
 5: readGistic(gisticAllLesionsFile = "all_lesions.conf_99.txt",     gisticAmpGenesFile = "amp_genes.conf_99.txt", gisticDelGenesFile = "del_genes.conf_99.txt")

**Comment by PoisonAlien** [comment]
Hi,

Sorry for late reply. This seems to me an issue with low memory. Can you just try with only one of the file (either amp or del file) and see if it works ?

For e.g,

```{r}
library(maftools)
r2=readGistic(gisticAllLesionsFile='all_lesions.conf_99.txt', gisticAmpGenesFile='amp_genes.conf_99.txt')
```

**Comment by lixiangchun** [comment]
It works when either amp or del file provided.  I found this issue is related to

```R
delGenes = suppressWarnings(data.table::melt(delGenes, id.vars = 'cytoband')) ## in readGistic.R
```

Replaced the above with the following, this issue was fixed.

```R
data.table::setDF(delGenes)
delGenes = reshape2::melt(delGenes, id.vars = 'cytoband')
data.table::setDT(delGenes)
```

**Comment by PoisonAlien** [comment]
Hi,
Does it work if you use both files (amp and del) with the above fix ?

**Comment by lixiangchun** [comment]
Yes, the above fix works for both amp and del files.

**Comment by PoisonAlien** [comment]
Hmm, that is weird. Thanks for reporting, I will look into it.
