### ISSUE TITLE
reading maf..  Error

### ISSUE THREAD

**Issue by Vergegung** [PoisonAlien/maftools#220]
I am trying to read the maf file download from TCGA (TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf.gz)
I run the following code. but it reported error.
```
laml.maf = system.file('extdata', 'TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf.gz', package = 'maftools')

laml = read.maf(maf = laml.maf)
```

> reading maf..
> Error in data.table::fread(input = maf, sep = "\t", stringsAsFactors = FALSE,  : 
>   Input is empty or only contains BOM or terminal control characters

Thanks so much for your help. Does this file is now suitable for reading?

**Comment by PoisonAlien** [comment]
Hi,
You don't need to use `system.file` command. Its only meant for an example file bundled with maftools. You can directly use your file as an input to `read.maf`. E.g as in below..

```
tcga_luad = read.maf(maf = "TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf.gz")
```

**Comment by Vergegung** [comment]
> Hi,
> You don't need to use `system.file` command. Its only meant for an example file bundled with maftools. You can directly use your file as an input to `read.maf`. E.g as in below..
> 
> ```
> tcga_luad = read.maf(maf = "TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf.gz")
> ```
Thanks so much for your help. It helps a lot.
Sorry to ask another stupid question. How can I transfer xls document to maf for reading?
Thanks soooooo much!

**Comment by PoisonAlien** [comment]
If your excel sheet contains all the necessary columns that are mentioned in [vignette](http://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#3_maf_field_requirements), then you can save it as a tsv file and read it using `read.maf`

**Comment by Vergegung** [comment]
> If your excel sheet contains all the necessary columns that are mentioned in [vignette](http://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#3_maf_field_requirements), then you can save it as a tsv file and read it using `read.maf`

I will try it according to your suggestion. Thanks again for your kind help. 'maftools' is the most fantastic package I have ever met.

**Comment by PoisonAlien** [comment]
I am glad you find it useful. I am closing this issue for now.
