### ISSUE TITLE
clinical data import

### ISSUE THREAD

**Issue by Vergegung** [PoisonAlien/maftools#221]
sorry, but I do not find the instruction for the essential titles of the clinical date file, as I need to import an original file of my data. Could you please tell me the Mandatory fields of this file (like sex? os? histology?)

`msktotal = read.maf(maf = "mskmaf.tsv", clinicalData = "mskclnical.tsv")`
```
Checking clinical data..
Error in colnames(sample.anno) : 找不到对象'sample.anno'
```
Thanks so much for your kind help.

**Comment by PoisonAlien** [comment]
You can include as mach information as you can. There are no hard rules. But make sure it has a column called `Tumor_Sample_Barcode` with same samples as in MAF.

**Comment by Vergegung** [comment]
> You can include as mach information as you can. There are no hard rules. But make sure it has a column called `Tumor_Sample_Barcode` with same samples as in MAF.
> Also I am not sure what the error message is. It would help me if you can translate it to English.

Thanks so much for your reply.
 
sorry, the '找不到对象' means "can't find the 'sample.anno' "

My clinical file included the column called `Tumor_Sample_Barcode` and other columns like OS, cancer type. But it failed to read it again.

I was going to make a Clinical enrichment analysis, but failed at the just beginning. 

`msktotal = read.maf(maf = "mskmaf.tsv", clinicalData = "mskclnical.tsv")
`
Thanks so much for your kind help.

**Comment by Vergegung** [comment]
> You can include as mach information as you can. There are no hard rules. But make sure it has a column called `Tumor_Sample_Barcode` with same samples as in MAF.
> Also I am not sure what the error message is. It would help me if you can translate it to English.

Sorry, but I still do not get your response. 

Another question, Can I insert exon number into the lollipop map? Thanks so much for your kind help?

**Comment by PoisonAlien** [comment]
Hi,
Sorry for late reply. I overlooked the issue. Could you post your `sessonInfo` here ? 
For exon number, sorry its not possible since protein domains do not contain exon information - which further depend on isoform of the transcript.
