### ISSUE TITLE
How to add clinical data

### ISSUE THREAD

**Issue by clersdom** [PoisonAlien/maftools#223]
I am making plots with my own sequencing data with Maftools. I have different phenotype data for which I would like to do clinical enrichment analysis and mafSurvival plot, but it is not working. Is it possible to import the clinical data?  

For example, I have tumour stage data and I would like to do enrichment analysis based on tumour stage.

> myLUADmaf_pheno_pyh <-read.maf("LUAD_52_WES_Targeted_PYH.txt")
> clinicalEnrichment(myLUADmaf_pheno, clinicalFeature = 'Stage')

Then, I get this error:
Error in `[.data.table`(getClinicalData(x = maf), , c("Tumor_Sample_Barcode",  : 
  column(s) not found: Stage

**Comment by clersdom** [comment]
Many thanks, it has worked now! Just warning about the fact that the clinical data file does not need the header #version 2.4 as the maf file does.

**Comment by PoisonAlien** [comment]
Yes. That's fine. You just need column names. Those commented lines will be ignored.
