### ISSUE TITLE
TiTv Stacked Bar Plot Fails Unless Cairo is Bitmap Type

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#226]
I take the example code from the documentation of `titv`. If I don't change any setting, it fails with 

```
## Warning in xypolygon(xx, yy, lty = "blank", col = boxfill[i]): semi-
## transparency is not supported on this device: reported only once per page
```

and the plot is incomplete and also missing colours.

![image](https://user-images.githubusercontent.com/631218/51015766-8d007680-15c1-11e9-9d49-400a7286f25c.png)

It's because

```r
> getOption("bitmapType")
[1] "Xlib"
```

If I add `options(bitmapType = "cairo")` to the top of the R Markdown document and knit it again, I see the complete and correct plot. Perhaps this required setting should be documented. Or, this warning could be caught and solid colours automatically used instead of transparency.

```r
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so
```

**Comment by PoisonAlien** [comment]
Oh I see! Never encountered this till now. Thanks you for pointing, I will fix it.
