### ISSUE TITLE
Outlier Labelling of TiTv Boxplot

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#227]
In the software's vignette, the example plot shows a couple of samples have very low Ti and very high Tv, which is not biologically expected (but probably caused by very few detected mutations in such a sample). Could such dots be automatically annotated by their sample ID? The samples would be interesting to analyse in more detail if they were immediately identifiable.

**Comment by PoisonAlien** [comment]
Yes, you are right. Those samples have low mutation rate (AML in general has extremely low mutation rate). But annotating them would be tricky because the plot would become way to crowded with texts. Do you have a suggestion on how you would approach ?

**Comment by DarioS** [comment]
I can't think of a general solution. It could be done by making the plot interactive by using Shiny and Plotly and the user could see the sample identifier if they hovered the mouse pointer above the dot, but that would add extra dependencies for the package which is a disadvantage.

**Comment by PoisonAlien** [comment]
Yes, exactly. Right now package has too many dependecies - especially with tdyverse package. I am slowly moving towards base graphics. Making them interactive would make it only harder. Sorry this cant be done at least for now :|
