### ISSUE TITLE
Number of samples to ExtractSignatures 

### ISSUE THREAD

**Issue by clersdom** [PoisonAlien/maftools#228]
Hi again, 
I am trying to extract signatures but I am not sure why is not working. I am conscious I need enough number of samples (in my case the mutation rate is high), so after trying to do it with two different sets I have combined them both and then, I have obtained a matrix of dimensions 34x96. Is still not enough or there may be something else?

This is the output I get after running extractSignatures:
> combinedSets_sign_52 <-extractSignatures(APOBEC_enrichment_combinedSets, plotBestFitRes = FALSE)
Error in extractSignatures(APOBEC_enrichment_combinedSets, plotBestFitRes = FALSE) : 
  Warning : Found zero mutations for conversions G[C>A]AWarning : Found zero mutations for conversions G[C>A]GWarning : Found zero mutations for conversions G[C>A]TWarning : Found zero mutations for conversions A[C>G]CWarning : Found zero mutations for conversions A[C>G]GWarning : Found zero mutations for conversions C[C>G]AWarning : Found zero mutations for conversions C[C>G]CWarning : Found zero mutations for conversions C[C>G]TWarning : Found zero mutations for conversions G[C>G]TWarning : Found zero mutations for conversions A[C>T]GWarning : Found zero mutations for conversions C[C>T]CWarning : Found zero mutations for conversions G[C>T]AWarning : Found zero mutations for conversions G[C>T]TWarning : Found zero mutations for conversions T[C>T]CWarning : Found zero mutations for conversions A[T>A]AWarning : Found zero mutations for conversions A[T>A]CWarning : Found zero mutations for conversions A[T>A]GWarning : Found zero mutations for conversions A[T>A]TWarning : Found ze

Thank you.

**Comment by ShixiangWang** [comment]
could you give the info you getting trinucletide matrix?

**Comment by PoisonAlien** [comment]
Hi @clersdom ,
As suggested could you post your complete command logg including `trinucleotideMatrix` ?
Also please post the  error message that you're getting. I can only see the warnings.

**Comment by ShixiangWang** [comment]
@clersdom It's strange. May you provide your MAF or `APOBEC_enrichment_combinedSets` to help the developer reproduce this issue and debug it?

**Comment by PoisonAlien** [comment]
It means there are really no mutations for those mutation channels. Also, `combinedSets_sign_52` is a list. Could you check `rowSums(combinedSets_sign_52$nmf_matrix)`  ? This output should be equal to the total mutations in each sample.

**Comment by clersdom** [comment]
Most samples match the total number of mutations, but a few samples do not match. I have realised that these samples have, among others, one mutation in the chr X. However, in some cases for samples with mutation in chr x do match. It is a bit confusing.

**Comment by PoisonAlien** [comment]
It appears to be the case. It is what it is. No need to worry. When you plot signatures, does it work ?

**Comment by clersdom** [comment]
No, as attached. I have made a change so now my matrix is of dimension 115x96.

> APOBEC_enrichment_combinedSets <-trinucleotideMatrix(LUAD_nd_LUSCmaf_pheno,ref_genome = "BSgenome.Hsapiens.UCSC.hg19", prefix = 'chr', add = TRUE)
Extracting 5' and 3' adjacent bases..
Extracting +/- 20bp around mutated bases for background C>T estimation..
Estimating APOBEC enrichment scores.. 
Performing one-way Fisher's test for APOBEC enrichment..
APOBEC related mutations are enriched in 27.027% of samples (APOBEC enrichment score > 2 ; 20 of 74 samples)
Creating mutation matrix..
matrix of dimension 115x96
> combinedSets_sign_52 <-extractSignatures(APOBEC_enrichment_combinedSets, plotBestFitRes = FALSE)
Error in extractSignatures(APOBEC_enrichment_combinedSets, plotBestFitRes = FALSE) : 
  Warning : Found zero mutations for conversions G[C>T]TWarning : Found zero mutations for conversions A[T>A]CWarning : Found zero mutations for conversions C[T>C]TWarning : Found zero mutations for conversions A[T>G]GWarning : Found zero mutations for conversions A[T>G]TWarning : Found zero mutations for conversions C[T>G]AWarning : Found zero mutations for conversions G[T>G]AWarning : Found zero mutations for conversions G[T>G]CWarning : Found zero mutations for conversions G[T>G]GWarning : Found zero mutations for conversions T[T>G]CWarning : Found zero mutations for conversions T[T>G]T
> plotSignatures(combinedSets_sign_52)
Error in plotSignatures(combinedSets_sign_52) : 
  object 'combinedSets_sign_52' not found

**Comment by PoisonAlien** [comment]
Hi, It's hard for me to guess what's going on. Can you attach your maf file here ? Or save maf object with save.image and attach it here.

**Comment by PoisonAlien** [comment]
@clersdom I have fixed. Thank you for reporting it. Please install from GitHub and let me know if it works. As @ShixiangWang suggested you will have to run it with `pConstant` argument.
