### ISSUE TITLE
TGCA compare only with one type of tumor

### ISSUE THREAD

**Issue by IrisSWE** [PoisonAlien/maftools#229]
Hi! 
Thank you so much for this wonderful tool!

I was wondering if there is a way to run the TGCA comparison but only with one type of tumor aka only Lung or only brain.  Would that be possible somehow? 

thank you

**Comment by PoisonAlien** [comment]
Hi,
I am glad that you find the tool useful. 
Could you explain a bit what you meant by comparing within a tumor type ? Do you mean within subtypes of a cancer type ?

**Comment by IrisSWE** [comment]
Hi and thanks for your quick reply!
What I meant was if I could compare my maf that is from e.g Brain tumor only to the Glioblastoma from TGCA. So in plot I would see just the type of cancer that I am interested in (TGCA and my maf) side by side without all the rest cancer types. It is quite a nice plot to have especially the one with the normalization to capture size.

Thank you

**Comment by PoisonAlien** [comment]
I believe you want to check kind of differentially mutated genes between your maf and tcga gbm maf ?

**Comment by IrisSWE** [comment]
No, no I have done that. I wanted to compare the mutation rates as per TGCAcompare

**Comment by PoisonAlien** [comment]
Oh I see! You don't want to display other cohorts, just the GBM. Then I dont think its possible as of now. But I can push a commit for this.

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the super delay. I have pushed a commit to address this. I have also updated tcga cohorts to recent MC3 project for stable comparison. You can find the argument `tcga_cohorts` within `tcgaCompare` function which accepts list of cohorts to restrict the comparison against.

e.g,
```r
tcgaCompare(maf = laml, tcga_cohorts = "GBM")
```

Again, apologies for the delay.
