### ISSUE TITLE
error in extractSignatures: none of the packages are loaded

### ISSUE THREAD

**Issue by crazyhottommy** [PoisonAlien/maftools#23]
Hi, 

I am using the latest version of maftools on github.

```r
SCLC.sig = extractSignatures(mat = SCLC.tnm, nTry = 6, plotBestFitRes = FALSE)
Estimating best rank..
Timing stopped at: 0.002 0 0.003 
Timing stopped at: 0.001 0 0.002 
Timing stopped at: 0.001 0.001 0.001 
Timing stopped at: 0.002 0 0.001 
Timing stopped at: 0.001 0 0.002 
Error in (function (...)  : All the runs produced an error:
	-#1 [r=2] -> none of the packages are loaded [in call to 'path.package']
	-#2 [r=3] -> none of the packages are loaded [in call to 'path.package']
	-#3 [r=4] -> none of the packages are loaded [in call to 'path.package']
	-#4 [r=5] -> none of the packages are loaded [in call to 'path.package']
	-#5 [r=6] -> none of the packages are loaded [in call to 'path.package']
```

what packages am I missing?

Thanks.
Tommy

**Comment by PoisonAlien** [comment]
Hi,
You're not missing any package. Its a known issue with NMF package #14 .

Try loading NMF package before running  `extractSignatures` and it should work fine.

**Comment by crazyhottommy** [comment]
after loading NMF first, I got another error:
any clues?
```
Estimating best rank..
Error in (function (...)  : All the runs produced an error:
	-#1 [r=2] -> attempt to set 'rownames' on an object with no dimensions [in call to 'rownames<-']
	-#2 [r=3] -> attempt to set 'rownames' on an object with no dimensions [in call to 'rownames<-']
	-#3 [r=4] -> attempt to set 'rownames' on an object with no dimensions [in call to 'rownames<-']
	-#4 [r=5] -> attempt to set 'rownames' on an object with no dimensions [in call to 'rownames<-']
	-#5 [r=6] -> attempt to set 'rownames' on an object with no dimensions [in call to 'rownames<-']
> 
```

**Comment by PoisonAlien** [comment]
Do you have enuf mutations ? You can manually set `n` values (2 or 3) and see if you can still get this error ?

**Comment by crazyhottommy** [comment]
indeed, after set n =2, it worked. Does that mean I do not have enough mutations?

**Comment by PoisonAlien** [comment]
My immediate guess is of low mutation. It depends on sample size and mutation rate. But I will check this  thoroughly again.

**Comment by crazyhottommy** [comment]
I do only have 2 samples in this case, but even with 1 sample, one should be able to extract mutation signatures in this single sample? I have not gotten into the signature extracting method yet.

**Comment by PoisonAlien** [comment]
2 samples are too low for signature analysis ! You could see 96 matrix in each sample but signature analysis is something to be done on big cohorts to capture underlying mutational processes. I would suggest you to include more samples.
