### ISSUE TITLE
Converting multi-vcf to maf 

### ISSUE THREAD

**Issue by craigdj91** [PoisonAlien/maftools#230]
Hello,

I have a multi-vcf file with 19 samples (each sample variant frequency representing an additional column in the VCF file) that I'm trying to convert to an MAF file using vcf2maf.pl

Is that the correct way to read in multiple samples into maftools? When I run the program, it still says that there is only 1 sample, and the first sample variant frequencies are the only ones reported.

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Make sure your maf file has a column called `Tumor_Sample_Barcode` with sample names (19 samples). It seems your maf file has a single value in this column. See if `vcf2maf` can generate an maf file for every sample in vcf. If it can, you can merge all the individual mafs into s single file and process it in maftools.

**Comment by ShixiangWang** [comment]
Another issue not related to maftools, close is suggested. @PoisonAlien Hope you can spend some time and go through all open issues and close inactive and unrelated issues. :)
