### ISSUE TITLE
plotApobecDiff out of bound error

### ISSUE THREAD

**Issue by IyadSultan** [PoisonAlien/maftools#232]
I generated the .tnm object using:
laml.tnm = trinucleotideMatrix(maf = laml, prefix = 'chr', add = TRUE, ref_genome = "BSgenome.Hsapiens.UCSC.hg19")
received the following:
Extracting 5' and 3' adjacent bases..
Extracting +/- 20bp around mutated bases for background C>T estimation..
Estimating APOBEC enrichment scores.. 
Performing one-way Fisher's test for APOBEC enrichment..
APOBEC related mutations are enriched in 3.571% of samples (APOBEC enrichment score > 2 ; 1 of 28 samples)
Creating mutation matrix..
matrix of dimension 29x96

Here are snapshots of the generated object
![screen shot 2019-01-27 at 12 08 33 am](https://user-images.githubusercontent.com/42122545/51793347-cfcc6c00-21c7-11e9-8252-ea19a903aadc.png)
![screen shot 2019-01-27 at 12 08 46 am](https://user-images.githubusercontent.com/42122545/51793348-d0fd9900-21c7-11e9-83a6-3928f33d3012.png)

then when I try:
plotApobecDiff(tnm = laml.tnm, maf = laml)

#Error in mcg.gs[mcg, , drop = FALSE] : subscript out of bounds

**Comment by PoisonAlien** [comment]
Hi,
It appears that since there is only one sample to be enriched for Apobec related mutagenesis, plotting function is failing to subset the data. Thanks for letting me know, I will look into it soon.

**Comment by jlac** [comment]
I don't think this is due to there only being a single sample. I am having the same issue with results that have several significant samples (>5 out ~15 tumors). Has there been any progress on this bug? Thanks in advance!

**Comment by ShixiangWang** [comment]
@jlac  could you provide sample data for reproducing this error?

**Comment by jlac** [comment]
Absolutely. I am attaching the MAF file that was causing the error (HBV_final_filtered.maf). A different cohort with a MAF file produced using the exact same pipeline analyzed without issue. Thanks for your help!
[HBV_final_filtered.maf.txt](https://github.com/PoisonAlien/maftools/files/3099634/HBV_final_filtered.maf.txt)

**Comment by PoisonAlien** [comment]
Hello,
Thank you for the file. It helped to track the issue. It was due to no significantly altered genes between samples with APOBEC enrichment and non-APOBEC enrichment. I have updated the code for better error handling. I have also added an argument to change the default P-value threshold for identifying differentially mutated genes. You can still plot the results with increasing P-value threshold.

Hope this helps.

**Comment by jlac** [comment]
Thanks so much!

Justin Lack [Contractor]
Bioinformatics Manager/Lead,
NIAID Collaborative Bioinformatics Resource (NCBR)
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov<mailto:ustin.lack@nih.gov>
