### ISSUE TITLE
annovarToMaf Warning

### ISSUE THREAD

**Issue by yanglq-bio** [PoisonAlien/maftools#234]
when I translate my file to maf format by 
var.annovar.maf = annovarToMaf(annovar = "all_sample.txt", 
                               Center = 'NA', 
                               refBuild = 'hg38', 
                               tsbCol = 'Tumor_Sample_Barcode', 
                               table = 'refGene',
                               sep = "\t",
                               sampleAnno = NULL)
I get this Warning message:
In data.table::data.table(Hugo_Symbol = ann$Gene.refGene, Entrez_Gene_Id = NA,  :
  Item 18 is of size 4890 but maximum size is 4893 (recycled leaving remainder of 3 items)

What does that mean？My file has 4948 lines, but this function can only read 4893 lines？

**Comment by PoisonAlien** [comment]
Okay, recycling values is never a good warning. I think something must have went wrong while parsing. Is it possible to share a sample of your maf file? Maybe top 100 rows. You can remove any sensitive information and change barcodes if you would like.

**Comment by elainebblythe** [comment]
Thank you for your reply.
Attached is my original data and the converted maf file.



elaineylq@163.com
 
From: Anand Mayakonda
Date: 2019-01-30 16:13
To: PoisonAlien/maftools
CC: elainebblythe; Author
Subject: Re: [PoisonAlien/maftools] annovarToMaf Warning (#234)
Okay, recycling values is never a good warning. I think something must have went wrong while parsing. Is it possible to share a sample of your maf file? Maybe top 100 rows. You can remove any sensitive information and change barcodes if you would like.

**Comment by davidcoffey** [comment]
I had this same issue and solved it by making the following change to the function annovarToMaf().

Change this:
` tx = unlist(sapply(xaa, function(l) {
        l[length(l) - 3]
    }))`

To this:
`tx = unlist(sapply(xaa, function(l) {
    if (length(l) > 1) {
      l[length(l) - 3]
    }
      else {
        NA
      }
  }))`

**Comment by elainebblythe** [comment]
ok.
thanks.



elaineylq@163.com
 
From: David Coffey
Date: 2019-03-13 06:51
To: PoisonAlien/maftools
CC: elainebblythe; Author
Subject: Re: [PoisonAlien/maftools] annovarToMaf Warning (#234)
I had this same issue and solved it by making the following change to the function annovarToMaf().
Change this:
tx = unlist(sapply(xaa, function(l) { l[length(l) - 3] }))
To this:
tx = unlist(sapply(xaa, function(l) { if (length(l) > 1) { l[length(l) - 3] } else { NA } }))
