### ISSUE TITLE
Subsetting Changes Object's Class

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#235]
The documented return value suggests that it should remain a MAF object if the input is a MAF.

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
> class(laml)
[1] "MAF"
miniExample <- subsetMaf(laml, levels(laml@data[["Tumor_Sample_Barcode"]])[1:20])
> class(miniExample)
[1] "data.table" "data.frame"
```

**Comment by PoisonAlien** [comment]
Hi,
By default `subsetMaf` returns data.table, but you can set `mafObj = TRUE` to get MAF object. 
In the beginning I thought it made sense to return data-table, but after I received several issues, I think it would make sense to return maf object by default. I will change it in next push.

**Comment by DarioS** [comment]
I overlooked the parameter `mafObj`. I assumed that subsetting is endomorphic (function's return type is the same as the input data type).

**Comment by PoisonAlien** [comment]
Hi, 
I have changed default value for `mafObj` to TRUE. Thanks for the reporting.
