### ISSUE TITLE
Could not find BSgenome Mmusculus.UCSC.mm10

### ISSUE THREAD

**Issue by DadongZ** [PoisonAlien/maftools#237]
I encountered error when I run `trinucleotideMatrix`

```
library("BSgenome.Mmusculus.UCSC.mm10") 
ref="BSgenome.Mmusculus.UCSC.mm10" 
trinucleotideMatrix(master_s, ref_genome=ref, prefix="", add=TRUE, ignoreChr="MT")
Could not find BSgenome Mmusculus.UCSC.mm10
Found following BSgenome installtions. Correct ref_genome argument if necessary.
1: BSgenome.Hsapiens.UCSC.hg19 Hsapiens     UCSC             hg19  FALSE
Error in trinucleotideMatrix(master_s, ref_genome = ref, prefix = "",  :
```
Any suggestions? Thanks

**Comment by ShixiangWang** [comment]
The mm10 package may not install correctly.

BSgenome::installed.genomes(splitNameParts only return hg19 in your case.

**Comment by PoisonAlien** [comment]
Yes, you don't seem to have mm10 genome installed.

**Comment by DadongZ** [comment]
I can see both of them:
> BSgenome::installed.genomes()
[1] "BSgenome.Hsapiens.UCSC.hg19"  "BSgenome.Mmusculus.UCSC.mm10"

**Comment by PoisonAlien** [comment]
Hmm.. maftools version on Bioconductor doesn't support mouse genome. This has been fixed in recent updates.. Could you try installing from GitHub and see if it works for you ?
