### ISSUE TITLE
snpEff and TCGA maf

### ISSUE THREAD

**Issue by vaksmaz** [PoisonAlien/maftools#238]
I have two issues to ask about which are not completely independent.
I am currently using the new version of snpEff (4.xx) which has new annotations. I have been putting them in manually but I am having issues with the lollipop plots (the little bobbles are not coming up) and a few others. 

I am also trying to compare my data to TCGA but I don't know what are the TCGA filter parameters (meaning what Minor Allele Frequencies and what ethnicities, Variant Effects (HIGH,MODERATE,etc..), which reference (HG19/38), etc... ) you used for filtering snps. This is so I can make the same changes (or does it do this automatically?). 

FYI, I am using using this with both?

**Comment by PoisonAlien** [comment]
Hi,
Could you post your sessioninfo and commands used for first issue ?

For second issue, I calculated mutation load from MAF files available from GDC (https://portal.gdc.cancer.gov/) with Mutect2 pipeline. However, I am not sure what filtering parameters they have used. I am trying to move this function to compare mutation load against more robust MC3 MAF files (https://gdc.cancer.gov/about-data/publications/mc3-2017). 
I will let you know when the function is updated.
