### ISSUE TITLE
Segfault when loading Gistic results

### ISSUE THREAD

**Issue by rdmorin** [PoisonAlien/maftools#24]
I am unable to successfully load a set of Gistic results along with a MAF file for a cohort of ~100 patients. Are there any known bugs or things I may not be doing correctly that could cause this?

reading maf..
NOTE: Removed 1 duplicated variants
Using all variants.
Excluding 18821 silent variants.
                 ID    N
 1:         Samples   95
 2:         3'Flank  720
 3:           3'UTR  615
 4:         5'Flank 1256
 5:           5'UTR  494
 6:             IGR  182
 7:          Intron 9459
 8:             RNA 1212
 9:          Silent 4882
10: Targeted_Region    1
Processing Gistic files..

 *** caught segfault ***
address 0x7c1, cause 'memory not mapped'

Traceback:
 1: rbindlist(l, use.names, fill, idcol)
 2: data.table::.rbind.data.table(...)
 3: rbind(deparse.level, ...)
 4: rbind(ampGenes, delGenes)
 5: readGistic(gisticAllLesionsFile = gisticAllLesionsFile, gisticAmpGenesFile = gisticAmpGenesFile,     gisticDelGenesFile = gisticDelGenesFile, isTCGA = isTCGA)
 6: read.maf(maf = "tcga_lohr_namefix_cut.maf", useAll = TRUE, gisticAmpGenesFile ="amp_genes.conf_75.txt",     gisticDelGenesFile = "del_genes.conf_75.txt",     gisticAllLesionsFile = "all_lesions.conf_75.txt")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by PoisonAlien** [comment]
Hi,

It's a known bug report #22 
I will fix it by weekend. Can you just check if you're getting same error using only one of the gistic file (either amp or del) ?

```{r}
m = read.maf(maf = "tcga_lohr_namefix_cut.maf", useAll = TRUE, gisticAmpGenesFile ="amp_genes.conf_75.txt", gisticAllLesionsFile = "all_lesions.conf_75.txt")
```

**Comment by PoisonAlien** [comment]
Hi,
I can't seem to reproduce this error on my machine. Do you think you can share your file ?

**Comment by rdmorin** [comment]
Sure. I can privately share them with you. Is email OK?

**Comment by PoisonAlien** [comment]
Yes, email is ok. anandmt3@gmail.com

**Comment by PoisonAlien** [comment]
Hi Ryan,

I have made necessary changes and fixed gistic bugs. Can you install again from github and let me know ?

```{r}
devtools::install_github(repo = 'poisonAlien/maftools')
```
