### ISSUE TITLE
Strange display in oncoplot with the latest git version (CN + variants)

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#240]
I'm using a MAF plus additional copy number data supplied (not from GISTIC). The top bar in the oncoplot display looks a little odd with the default X11 device:

![screenshot_20190212_094430](https://user-images.githubusercontent.com/25192/52622794-f6b6bd80-2eaa-11e9-9323-dbf47efb2b93.png)

**Comment by lbeltrame** [comment]
Cheched also with the PDF device, same result.

**Comment by PoisonAlien** [comment]
I have not come across this issue. I will check this on my system and let you know if I can reproduce it.

**Comment by lbeltrame** [comment]
I can share (privately) a MAF + CN data file that causes this.

**Comment by PoisonAlien** [comment]
Yeah, that's much better. (you can email me at anandmt3@gmail.com)

**Comment by lbeltrame** [comment]
I've emailed the relevant files.

**Comment by PoisonAlien** [comment]
I haven't received them yet. Could you double check your sent mail ?

**Comment by PoisonAlien** [comment]
Okay I was able to reproduce the issue with a demo data. I will fix it soon.

**Comment by PoisonAlien** [comment]
I've fixed it. You can try from GitHub installation.

**Comment by lbeltrame** [comment]
Thanks, I'll try (but I did send the mail: I'm sure GMail flagged it as spam).

**Comment by lbeltrame** [comment]
Works, thanks!

**Comment by PoisonAlien** [comment]
Yes, it was in the spam.
