### ISSUE TITLE
Regression: oncoplot sampleOrder no longer working in current git

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#241]
I checked the code and it's not implemented, probably removed at some point.

**Comment by lbeltrame** [comment]
Indeed, it was removed (an oversight?) in 54e1156dde10dc18de6b3f1a9617a75ea1613ca5#diff-0553f413d680d86c2478d04b01397b3a.

**Comment by PoisonAlien** [comment]
I received several suggestion that the current implementation of maftools has too many dependencies which often leads to package breaks. So I am moving all the plotting code to base graphics by removing ggplot/complexheatmap dependencies. During the course several changes have been made    and I think this might have been one of it. I will add it again. 

Thanks and apologies for the complications :|
