### ISSUE TITLE
In lollipopPlot, an existing AAChange column overrides user choice

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#242]
If I have a MAF with two columns for amino acid changes like "AAChange" and "HGVSp", for example, selecting `AACol` to be `HGVSp` will not work, because the existing `AAChange` will shadow the other when selecting the columns.

**Comment by PoisonAlien** [comment]
Try forcing it with `AACol` argument, it should work.

**Comment by lbeltrame** [comment]
It doesn't, I poorly worded the report. 

```
 prot.dat = mut[Hugo_Symbol %in% geneID, .(Variant_Type, Variant_Classification, AAChange)]
```

Will get the existing AAChange column and not the new one, no matter if it's set a few lines above.

**Comment by PoisonAlien** [comment]
Please try now, and let me know if you still have any issues.

**Comment by lbeltrame** [comment]
Doesn't seem to work:

```r

> colnames(maf@data)
 [1] "Hugo_Symbol"            "Entrez_Gene_Id"         "NCBI_Build"            
 [4] "Chromosome"             "Start_Position"         "End_Position"          
 [7] "Strand"                 "Variant_Classification" "Variant_Type"          
[10] "Reference_Allele"       "Tumor_Seq_Allele1"      "Tumor_Seq_Allele2"     
[13] "dbSNP_RS"               "Tumor_Sample_Barcode"   "Mutation_Status"       
[16] "Consequence"            "Validation_Status"      "AAChange"              
[19] "t_vaf"                  "HGVSc"                  "HGVSp"                 
[22] "Tumor_Sample_barcode" 

> lollipopPlot(maf = maf, gene = 'TP53', showMutationRate = TRUE, AACol="HGVSp", repel=T)
8 transcripts available. Use arguments refSeqID or proteinID to manually specify tx name.
   HGNC    refseq.ID   protein.ID aa.length
1: TP53    NM_000546    NP_000537       393
2: TP53 NM_001126112 NP_001119584       393
3: TP53 NM_001126118 NP_001119590       354
4: TP53 NM_001126115 NP_001119587       261
5: TP53 NM_001126113 NP_001119585       346
6: TP53 NM_001126117 NP_001119589       214
7: TP53 NM_001126114 NP_001119586       341
8: TP53 NM_001126116 NP_001119588       209
Using longer transcript NM_000546 for now.
Removed 77 mutations for which AA position was not available
```

Note the last line, the position is there, but the existing `AAChange` column shadows whatever I set.

**Comment by PoisonAlien** [comment]
Thanks for pointing it out. It was a silly mistake. Could you try again and let me know ?

**Comment by lbeltrame** [comment]
I hate to be "that guy" but it still don't work, it only works if I forcibly remove the `AAChange` column from the MAF, then `HGSVp` is picked up. I'm pretty sure there's some shadowing (in the variable sense) going on.

**Comment by PoisonAlien** [comment]
Haha.. No problem, this is how its done. Its a variable name conflict issue. Only workaround is to change the 'AAChange' in the code itself (which I dint want to do). Give it a final try, if it won't work I will purge this function.

**Comment by lbeltrame** [comment]
That seems to work now.

**Comment by PoisonAlien** [comment]
Thanks for testing. I am closing it now, please feel free to open any issues if you come across. I appreciate it.
