### ISSUE TITLE
Overlapping Protein Domains in lollipopPlot

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#245]
Is there a more robust way to plot the Lollipop Plot? The example in Section 7.5 of the vignette for DNMT3A has two domains which are partially overlapping and their labels also overlap, causing them to be illegible. Could colour transparency be used in such cases or drawing each of the two overlapping domains half-height and putting one up and the other down to prevent the overlap?

**Comment by PoisonAlien** [comment]
Hi,
this is a tricky part. For the first part (overlapping domain names) you can set the argument `showDomainLabel = FALSE` and it will annotate them in the legend instead on the domains itself.

For second issue, Colors are already 0.6 alpha dont know how much it will help. I can try to implement your second suggestion but it might take some time.
