### ISSUE TITLE
Multihit samples in oncoprint 

### ISSUE THREAD

**Issue by Tato14** [PoisonAlien/maftools#246]
I was wondering how difficult would be that oncoprint function show genes with more than one variant type (multihit) as half (or proportion) of each variant in the cell.
For example, take a gene which has Missense mutation (green) and Frameshift (red). Would be easy to plot the specific cell as half green and half red?
Thanks!

**Comment by PoisonAlien** [comment]
Hi,
That's an interesting idea. I have never thought of it. I can give it a shot and see if its doable. 
Thanks.

**Comment by DarioS** [comment]
This would be powerful to have but I imagine hard to code. The ultimate solution would also inform you of how many of each type of mutation there is and perhaps look like 

![image](https://user-images.githubusercontent.com/631218/59003263-86b4b480-8858-11e9-9e1d-a55f0fdc5b32.png)

**Comment by PoisonAlien** [comment]
Yeah, I tried to do it but it was quite hard implement it. Image command would not let me split the boxes.

**Comment by jgarces02** [comment]
Wow, @PoisonAlien, that'd be wonderful idea! (very interesting suggestion, @DarioS).
