### ISSUE TITLE
Typo in gisticOncoPlot

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#247]
```
> gisticOncoPlot(gistic, showTumorSampleBarcodes=T)
Error in text(x = 1:nrow(nm), y = par("usr")[3] - 0.2, labels = rownames(nm),  : 
  object "SampleNamefontSize" not found
```

I assume that meant `fontSize` alone, according to the function signature.

**Comment by PoisonAlien** [comment]
Ah, sorry.. code migration from ggplot to base graphics has led to some discrepancies. I have fixed it. Could you please try again from GitHub ?

**Comment by lbeltrame** [comment]
Thanks, this is fixed, however a new problem surfaced (will open a separate issue for it).
