### ISSUE TITLE
gisticOncoPlot: unable to display annotation

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#248]
```r
> gisticOncoPlot(gistic, showTumorSampleBarcodes=T, clinicalData=clinical, clinicalFeatures="Histo", annotationColor=fabcolors)
Error in legend(x = x_axp, y = 1, legend = names(x), col = x, border = NA,  : 
  'legend' is of length 0
```

Looks like `names(x)` is `NULL`. I tried looking through the code but I couldn't find how color assignment is done. But basically the code does not plot anything as far as I can see.

**Comment by lbeltrame** [comment]
It looks that this is where it's broken:

```r
for (i in 1:length(names(clini_lvls))) {
    anno_code = clini_lvls[i]
    col = anno_cols[anno_code]
    temp_anno = as.matrix(annotation)
    temp_anno[temp_anno != names(anno_code)] = NA
    image(x = 1:nrow(temp_anno), y = 1:ncol(temp_anno), z = temp_anno, 
        axes = FALSE, xaxt = "n", yaxt = "n", xlab = "", ylab = "", 
        col = col, add = TRUE)
}
```

In particular `col` is `NA` because `anno_cols` has no names. In addition, I've seen that the legend exits early, before all annotations can be plotted.

**Comment by PoisonAlien** [comment]
Can you print `fabcolors` ? It should be a list of named vectors.

**Comment by lbeltrame** [comment]
```r
x = annotationColor[[i]]
```
In my case, where I only have one column, it will get the *first* value of the colors, and ignore the rest.

**Comment by lbeltrame** [comment]
In case it doesn't error (legend doesn't exit) but colors are nevertheless not plotted due to `col = anno_cols[anno_code]` returning `NA` AFAICS.

**Comment by lbeltrame** [comment]
I made a patch adding 

```r
names(anno_cols) = clini_lvls
```

after `clini_lvls` is properly made. I can submit that as PR if you want to.

**Comment by PoisonAlien** [comment]
I see.. Its hard for me to figure out the issue without a reproducible example. Can you print `fabcolors` so that I can make sure its not due to color formats. Or can you try once plotting without `annotationColor` and see if it works as it should ?

**Comment by lbeltrame** [comment]
```
> fabcolors
$Histo
      A B        C        D
 "#D7191C"  "#FDAE61"  "#ABDDA4"  "#2B83BA" 
```
(formatting may be off)

**Comment by PoisonAlien** [comment]
This looks okay to me. Just one last question, did the function work properly without `annotationColor` argument ? 
If your patch fixes the issue, pleas do send a PR, happy to accept :)

Thanks.

**Comment by lbeltrame** [comment]
And now I removed the code.... and works. Must have been some glitch in the matrix. I'll close for now and reopen if need be.

**Comment by lbeltrame** [comment]
I might rework the patch to error out if `annotationColors` is not a list, though.

**Comment by PoisonAlien** [comment]
Sure. I will update the documentation and add an example to make this clear.
