### ISSUE TITLE
readGistic: allow keeping samples with no alterations

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#249]
As the subject says, otherwise the percentages are off in case one wants to evaluate a sample population (for example, it cut off 17 samples off my analysis because they were all CN neutral).

**Comment by lbeltrame** [comment]
A possible solution (kind of testing it) would be to alter the `cnLevel` parameter as such:

- `all`: all samples even if not altered
- `altered` (default): Any samples with alterations
- `deep`: like before
- `shallow`: like before

I still need to see whether the code makes assumptions that there are samples with more than 0 alterations, though.

**Comment by lbeltrame** [comment]
I've seen that `gisticOncoPlot` breaks already with this...

**Comment by PoisonAlien** [comment]
Okay, I will go through it and get back to you soon.

**Comment by lbeltrame** [comment]
I'm also working on this ("yay" for deadlines!) I'll report back if I find anything useful.

**Comment by lbeltrame** [comment]
I had to give up on implementing it, at least temporarily. Lots of the code makes assumptions that you *always* have at least one alteration.

**Comment by PoisonAlien** [comment]
Hi,
Sorry it took a while but I have fixed it. Could you please try and let me know.
You can use `removeNonAltered` to control samples with no alterations.

```r
gisticOncoPlot(gistic = laml.gistic,  top = 10, removeNonAltered = FALSE, showTumorSampleBarcodes = TRUE)
```

**Comment by lbeltrame** [comment]
Looks like it's working now, thanks!
