### ISSUE TITLE
Gistic amplifications are consistently dropped

### ISSUE THREAD

**Issue by rdmorin** [PoisonAlien/maftools#25]
I was having a hard time pulling in Gistic results. Once I found a file that would successfully be parsed, I noticed that none of the expected amplifications were being shown. I came across this line in the readGistic function:

all.lesions.melt = all.lesions.melt[value %in% 1]

I believe that this removes all of the gains. I changed it to:

all.lesions.melt = all.lesions.melt[value %in% c(1,2)]

Now it seems to work.

**Comment by PoisonAlien** [comment]
Ohh! Thanks for noticing this and apologies for the mistake. Somehow I missed deep CN alterations. This is extremely helpful. I will fix it soon.
