### ISSUE TITLE
gisticOncoPlot: numbers as annotation names confuse the color mapping

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#252]
Example:

```r
> unique(clinical$Grade)
[1] 3 1 2

> gisticOncoPlot(gistic, removeNonAltered=F, sortByAnnotation=T, clinicalFeatures="Grade", clinicalData=clinical, showTumorSampleBarcodes=T)

```

The annotation output in this case is puzzling.

Grade ordered by annotation: already wrong, since there is a "2" somewhere in the data (see above):
![screenshot_20190225_112055](https://user-images.githubusercontent.com/25192/53330692-6e470c80-38ef-11e9-9491-5be69ca123a8.png)

Grade not ordered by annotation: also wrong, and different from before
![screenshot_20190225_112130](https://user-images.githubusercontent.com/25192/53330734-8880ea80-38ef-11e9-93f8-f3e95c5d3cbe.png)

The issues disappear if, for example, I set strings like `One` instead.

**Comment by PoisonAlien** [comment]
Okay, I can fix this. 
But, in general this is also expected because annotations are usually categorical variable. As you suggested best way is to encode levels in the variables to characters/factors that way indexing wont mess-up the order.

**Comment by lbeltrame** [comment]
It's kind of a problem when the clinics insist in using numbers or they won't understand. ;) But I also understand that it makes far more sense to use categorical names.
