### ISSUE TITLE
RFE oncoplot:  in case of missing genes in the list, draw them empty

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#254]
As usual this comes from a request from clinicians and wet lab people: they know some genes are not mutated in a small panel, but they want to get them drawn nevertheless. This won't work for gene order, because it will try to sort the MAF and fail due to missing genes.

Tagged RFE because it may be just trouble with little benefit.

**Comment by lbeltrame** [comment]
An idea would be to show genes that are marked with "excluded" variants as non mutated. I generated "fake" records with genes that only included silent mutations for all genes that were missing, so it would be a matter of showing samples like that.

**Comment by PoisonAlien** [comment]
I will fix this soon. I will make an argument `fill = TRUE` to force missing sample and genes to be drawn at the end of the matrix. I believe this is what you want is it ?

**Comment by lbeltrame** [comment]
Exactly, that would fit the bill (and make the wet lab people happy ;).

**Comment by PoisonAlien** [comment]
Hello,
Could you please try again and let me know if it works for you. I have tested on the vignette data and seems to be working fine. Let me know..

**Comment by lbeltrame** [comment]
I'm currently testing, I'll let you know.

**Comment by lbeltrame** [comment]
Looks like it's working. If I'll notice something odd, I'll reopen. Thanks!
