### ISSUE TITLE
lollipop "Structure for protein ... not found"

### ISSUE THREAD

**Issue by rong923** [PoisonAlien/maftools#255]
is there a way to manually add the data or any other ways to solve this issue? appreciated

**Comment by PoisonAlien** [comment]
Can you paste your command ? What protein is it, and is it human data ?

**Comment by rong923** [comment]
> lollipopPlot(laml,gene='MTRNR2L8')
Assuming protein change information are stored under column AAChange. Use argument AACol to override if necessary.
Error in lollipopPlot(laml, gene = "MTRNR2L8") : 
  Structure for protein MTRNR2L8 not found.

Thank you!

**Comment by PoisonAlien** [comment]
Hmm.. I checked cbioportal and they seem to have domain information. 
For now there is no alternate way to manually provide domains, but I can push a commit to solve this. It might take some time though..

**Comment by rong923** [comment]
thank you very much. would be great if you can make it work!

**Comment by rong923** [comment]
Hi we are preparing a manuscript, would be really much appreciated if you can let me know a timeline that this would be fixed. thanks so much

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay as things are bit busy here as well. I will get back to you by tomorrow. However, I assume you have a protein structure for this data? For now, internal data used by maftools for lollipop plot looks as below:

```r
HGNC refseq.ID protein.ID Start End aa.length        Label
1: TP53 NM_000546  NP_000537     5  29       393      P53_TAD
2: TP53 NM_000546  NP_000537   109 288       393          P53
3: TP53 NM_000546  NP_000537   319 359       393 P53_tetramer
```  

Do you have something similar ? I would at-least need column 1,3,4,5,6.

**Comment by rong923** [comment]
can you try this

HGNC refseq.ID protein.ID Start End aa.length        Label

1: HM NM_001190702 NP_001177631 6  13       24      HM_Helix


thanks!

**Comment by PoisonAlien** [comment]
Is the gene name `HM` ? Note it should be same as your query gene from MAF. So shouldn't it be `MTRNR2L8` ? If you're sure, then I will add this entry to maftools database. Let me know.

**Comment by rong923** [comment]
yes the name should be MTRNR2L8. Thanks so much

**Comment by PoisonAlien** [comment]
Hello,
Thanks for clarifying. I have added MTRNR2L8 to the database. Please install from GitHub and let me know if this works for you.

**Comment by rong923** [comment]
https://drive.google.com/file/d/1qlffrLN3wBj-gVlSKyd6rQ9fCWgMNBRg/view?usp=sharing

Hi can I have questions about the figure. 1) is y axis number of mutations or patients? 2) why would it yield 2 dots on the same bar? 3) why is there mutations outside of amino acids region? thanks!!

**Comment by PoisonAlien** [comment]
Hi,
It quite weird how the plot looks. Could you try installing from package from GitHub again and try ?
Regarding your questions,
1. Y-axis are mutations. 
2. Thats because that particular amino acid is mutated into two different allele. For example in AML, DNMT3A R882 amino-acid gets changed to `R882C` and `R882H`. You can check this by labelling all that position. Use `labelPos` argument and it should highlight them.
3. That means some of the mutations are outside the protein length. It also means that the structure we have here might the right one since the lengths seems to mismatch. Can you run lollipopPlot with  `printCount = TRUE` to see where they are located ?

**Comment by hwijunkwon** [comment]
Hello! 
I also faced the same problem
I put maf file with snp (Hugo_symbol : MUC3A, LCE4A, LORICRIN, CCDC168 )
but it shows error like "can't find gene"
Do you know how can i solve this problem?
