### ISSUE TITLE
oncoplot: sampleOrder ignored

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#256]
As the subject says, No matter how I specify the sample ordering, the ordering of the samples in the plot is not what I expect it to be.

E.g.: if I use `sampleOrder=c(133, 49)` where 49 has more variants than 133, the latter will always get drawn first, no matter if the order should say otherwise.

**Comment by PoisonAlien** [comment]
Could you try now ?

**Comment by lbeltrame** [comment]
Works, thanks.
