### ISSUE TITLE
trinucleotideMatrix error with hg38

### ISSUE THREAD

**Issue by lxilxi** [PoisonAlien/maftools#257]
Hi, I got the following error when using hg38 reference_genome for the trinucleotideMatrix function, could you please help?  Thanks!
`
maf.tnm = trinucleotideMatrix(maf = maf, ref_genome = "BSgenome.Hsapiens.UCSC.hg38") 
Extracting 5' and 3' adjacent bases.. 
Error: C stack usage  7969428 is too close to the limit
`

**Comment by ShixiangWang** [comment]
have not enough memory?

**Comment by lxilxi** [comment]
It should not be as the maf only contains 125 variants.

**Comment by PoisonAlien** [comment]
If I have to guess loci `7969428` is too close to the edge of the chromosome. 
Could you check to which chromosome this loci belongs to?

**Comment by ShixiangWang** [comment]
@PoisonAlien This is not a problem related to genome loci. https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit This link may help.

**Comment by PoisonAlien** [comment]
Ah I see.. Thanks @ShixiangWang 
This is interesting.. 
@lxilxi Please let me know if the above works after setting C stack.

**Comment by lxilxi** [comment]
Thank you both, after setting the new stack size, the problem was solved.
