### ISSUE TITLE
Sorting breaks annotation order in oncostrip

### ISSUE THREAD

**Issue by rdmorin** [PoisonAlien/maftools#26]
I believe I have found a bug in the oncostrip function. The effect of this bug is that the annotation of samples is not reordered when the sample mutation matrix is sorted (i.e. the default behavior). I think adding the following code to the function to replace the single line setting "bot.anno" (now in the else block) fixes this.

if(sort){
        sorted.order = colnames(mat)
        anno.df.sorted = as.data.frame(anno.df[sorted.order,])
        rownames(anno.df.sorted) = sorted.order
        colnames(anno.df.sorted) = colnames(anno.df)
        bot.anno = ComplexHeatmap::HeatmapAnnotation(anno.df.sorted)
      }else{
        bot.anno = ComplexHeatmap::HeatmapAnnotation(anno.df)
      }

**Comment by PoisonAlien** [comment]
Hi,
You were correct about sorting order. Nice catch ! 
Thank you for reporting. It will be fixed in next update.
