### ISSUE TITLE
gisticOncoPlot: labels cut off in the plot

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#260]
As shown:

![screenshot_20190304_141528](https://user-images.githubusercontent.com/25192/53735695-f7c68380-3e87-11e9-992b-374263114b78.png)

![screenshot_20190304_141548](https://user-images.githubusercontent.com/25192/53735726-044adc00-3e88-11e9-9daf-3508341e80ea.png)

**Comment by PoisonAlien** [comment]
Hi,
You could try `fontSize` argument to decrease it. If it doesn't help I could push a fix to increase the left margin.

**Comment by sagarutturkar** [comment]
I am facing the similar issue. In the image below, I am using `fontSize = 0.5`
I tried to control margins with:
`par(mar = c(2, 10, 2, 2))`
but it did not help. 

I think in the newest version, gene names plotted on the leftmost panel is the problem. It would be a great help if you could fix this at source.

![maftools_1](https://user-images.githubusercontent.com/7976228/59610792-1f182800-90e8-11e9-9fa0-2a77f7617a71.png)

**Comment by sagarutturkar** [comment]
Just a reminder - It may be helpful to increase the margins on all 4 sides. I get title clipped off with increased font size. The sample names are clipped if I am plotting titv.

```
oncoplot(maf = mymaf, top = 20, fontSize = 0.8, legendFontSize = 2, 
             SampleNamefontSize = 2,titleFontSize = 2,
             showTumorSampleBarcodes = TRUE, draw_titv = TRUE)
```

![image](https://user-images.githubusercontent.com/7976228/60280264-9dd34900-98d0-11e9-810f-af64a846886a.png)

**Comment by PoisonAlien** [comment]
Hello both, 
I have added `barcode_mar` and `gene_mar` argument to `gisticOncoPlot`. Increase these values to improve the margin width to accommodate longer texts. I would appreciate if any one can test it and let me know if it works.

**Comment by sagarutturkar** [comment]
I reinstalled the package with `BiocManager::install("PoisonAlien/maftools")` and sessioninfo shows `maftools_2.0.10`. But I get the error `unused arguments (barcode_mar = 2, gene_mar = 5)` with oncoplot command:

```
oncoplot(maf = mymaf, top = 20, fontSize = 0.8, legendFontSize = 2, 
             SampleNamefontSize = 2,titleFontSize = 2,
             showTumorSampleBarcodes = TRUE, draw_titv = TRUE, barcode_mar  = 2, gene_mar = 5)
```
Maybe I am not updating correctly?

**Comment by PoisonAlien** [comment]
Yes, I think update didn't work properly. Your version should be `2.0.15`

**Comment by sagarutturkar** [comment]
Thank you! This worked like a charm with `oncoplot` function. Appreciate your quick responses and a great tool indeed.

**Comment by rajkump** [comment]
Hi,
  Can you add the same arguments barcode_mar and gene_mar  to co-oncoplot?
Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Hi @rajkump 
`coOncoplot` already has a `barcode_mar` option. I have just added `gene_mar` to the function. You will have to install from GitHub for the update. Please let me know if this helps.

**Comment by rajkump** [comment]
Thanks Anand. Will let you know soon.
Thanks,
Praveen

**Comment by rajkump** [comment]
Hi Anand,
     I got maftools_2.4.15 installed. With 'gene_mar' I could increase left margin. Thanks a lot for that.  I would like to control space between two oncoplot and change the position towards center of the gap between two oncoplots. Please let me know if you can introduce argument for that. 'barcode_mar' just pushes the center gene name down.
Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Ah! Took me a while to figure out the issue but I think I have fixed it. I have changed the argument names to be more intuitive. 
`gene_mar` = Width between two plots. Now the gene names will always be at the center.
`outer_mar` = Width of outer margins (extreme left and right).

Could you try again and let me know if this is what you intended?

**Comment by rajkump** [comment]
Thanks a lot Anand. I will check and let you know.

**Comment by rajkump** [comment]
I really like how `gene_mar` controls the space between plots but now the `oncoplot` and bottom `annotation
![example](https://user-images.githubusercontent.com/38671329/92197842-e1183880-ee40-11ea-9462-887d881749b7.png)
 bar` doesn't align well.

**Comment by PoisonAlien** [comment]
Rightt! I overlooked the annotation bar. I'll fix it over the weekend. Thanks for testing.

**Comment by rajkump** [comment]
Yes please. That will be a great help.  I am planning to use co-oncoplot for our upcoming paper.
Thanks,
Praveen

**Comment by PoisonAlien** [comment]
@rajkump 
Done! Thank you for the feature request and checking. Let me know if it looks good or if you have any other issues.

**Comment by rajkump** [comment]
Thanks much Anand. I just reinstalled Maftools from github.  Alignment in the coOncoplot seems great. Thanks a lot for your great tool and you working on my request. 
Thanks,
Praveen

**Comment by FiveThirteen** [comment]
Thank you so much for this great package! Any chance you could also add margin arguments to the coBarplot function? Thank you for considering.

**Comment by PoisonAlien** [comment]
Hello @FiveThirteen 

Sure. I have added `geneMar` argument to `coBarplot`. Hope it helps. You will have to install the package from GitHub for changes.

**Comment by FiveThirteen** [comment]
Thank you so much Anand! The geneMar argument works great. Two other small issues: the x-axis labels are now rotated 90 degrees and "Percentage of cases" overlaps with the 0% label. In addition, the m1Name and m2Name labels are cut-off at the top. 

Here is an example (data obscured). 

![plot_zoom_png](https://user-images.githubusercontent.com/47004140/110811829-e7e29680-823b-11eb-84d3-2b6fe46c8eb7.png)

Thank you Anand!

**Comment by PoisonAlien** [comment]
That is weird. Could you please run `dev.off()` and try again? Also, saving to a pdf would work better than the plot window.
