### ISSUE TITLE
Mutect Hotspot mutations and variant classification ranking

### ISSUE THREAD

**Issue by simonlee184** [PoisonAlien/maftools#262]
Hi Mayakonda,
    I was using the output MAF file from Mutect which essentially has all the information to use maftools and only required some column renaming. 
     Everything works well, but I was wondering how I could add hotspot mutations as another variant classification.

**Comment by PoisonAlien** [comment]
Hi @simonlee184 ,
Could you explain a bit ? Are you trying to highlight hotspot variants in oncoplot ?

**Comment by simonlee184** [comment]
Yes, and cooncoplot as well. There's a column in Mutect which tells whether
a mutation is a hotspot or not, so in my lab, if the value in the hotspot
column is true, the variant classification column is then changed to
Hotspot mutation

**Comment by PoisonAlien** [comment]
Ah, This is quite tricky and there is no straight-forward way to do this. One thing you could do is, change values in `Variant_Classification` column for these hotspot variants to your desired value. example `hotspot`. Then read your maf with `vc_nonSyn` argument to consider all entries with `hotspot` variant classification as a non-synonymous variant. Below is the commands,

```r
#create non-syn variant classification 
custom_vcs = c("Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site", "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del","In_Frame_Ins", "Missense_Mutation", "hotspot")

#read maf
maf = read.maf(maf = "foo.maf", vc_nonSyn = custom_vcs)

#color code for VCs
vc_cols = maftools:::get_vcColors()
#Add color code for hotspot
vc_cols = c(vc_cols, hotspot = "maroon") 

#Plot 
oncoplot(maf = maf, colors = vc_cols)
```

Above workround should highlight all the hotspots in maroon.

**Comment by simonlee184** [comment]
It works perfectly! Thank you so much.

Simon
