### ISSUE TITLE
FeatureRequest: plot clinical information in oncoplot

### ISSUE THREAD

**Issue by bkinnersley** [PoisonAlien/maftools#263]
Hello,

Firstly thank you for such a useful tool!

I would like to be able to plot tumour telomere length as estimated from WGS data e.g. as an extra graph on the oncoplot. If I included the tumour telomere length as a category in the clinical information input file is there an easy way to include this in an oncoplot?

Thanks very much

**Comment by PoisonAlien** [comment]
Hi,
If I understand correctly you would like to include a side bar plot of telomere lengths ? 

But regarding adding it as an annotation, you can definitely plot telomere length as a one of the clinical feature. Check out `clinicalFeatures` argument in `oncoplot`.

**Comment by bkinnersley** [comment]
Hello,

Thank you for your very rapid reply!

I have tried using clinicalFeatures in oncoplot but my understanding is this assumes the clinicalFeature is categorical rather than continuous (as is the case e.g. for telomere length or another feature) - unless there is a way to specify this? As at the moment I have tried the command:

"oncoplot(maf = glioma, clinicalFeatures = 'tumour_tel_content', top = 10, fontSize = 12)"

But this produces a legend colour annotation for every possible length value, whereas ideally I would like a bar plot similar to mutation number but with telomere length.

This is using the 1.8.0 release as the environment I am working in cannot download via github, I do not know if this changes things

Thanks very much

**Comment by PoisonAlien** [comment]
Hi,
Yes, Ideally `clinicalFeature`  Should be categorical.  For numeric variable it is bit of a trouble as it will plot all levels. However, I can push a commit to address this - as this seems to be recurring request, but you will have to install it from GitHub :|

**Comment by bkinnersley** [comment]
Great, thanks very much!
