### ISSUE TITLE
oncoplot: unclear meaning of percentages

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#264]
![screenshot_20190308_160249](https://user-images.githubusercontent.com/25192/54036314-a423a500-41bb-11e9-956f-013f3eafd646.png)

It's unclear what 42% means, given that > 50% of the samples have variants in that gene.

**Comment by PoisonAlien** [comment]
Hi,
These percentages are estimated by dividing number mutated samples the row by total number of samples in the maf. Check here for the [code](https://github.com/PoisonAlien/maftools/blob/master/R/oncoplot.R#L184).
However, there was a [bug](https://github.com/PoisonAlien/maftools/issues/261#issuecomment-469963693) in it a while back which is now fixed. You can try again to see if you still get this number.

**Comment by lbeltrame** [comment]
Indeed, it was that bug, now I get a much more reasonable 86% (which also fits the biology of these samples ;). Closing.
