### ISSUE TITLE
Oncostrip not showing all nonsense mutated samples

### ISSUE THREAD

**Issue by tjbencomo** [PoisonAlien/maftools#265]
Hi,

I had a question about the behavior of `oncostrip()`. I'm trying to plot which samples are nonsense mutated for a list of genes. When I use `oncostrip()` with my overall MAF file containing all types of mutations (missense, nonsense, frameshift etc), it does not show the correct number of nonsense samples mutations. It shows fewer nonsense mutated samples than expected, classifying the rest of the samples with mutations as missense. To remedy the issue, I first filter my MAF file to only include nonsense variants and then plot these mutations with `oncostrip()` and the correct number of nonsense mutated samples are now shown. 

I know my overall MAF file contains cases where a sample has both nonsense and missense mutations. My question is how does `oncostrip()` handle these samples? How does it classify samples that have both missense and nonsense mutations? To better visualize my question, I've attached 2 plots:
A
![example1](https://user-images.githubusercontent.com/26121995/54234768-02f36200-44cd-11e9-9770-5502f7897c35.png)
B
![example2](https://user-images.githubusercontent.com/26121995/54234776-07b81600-44cd-11e9-857d-131e38d950c1.png)

Figure A was made using the entire MAF file whereas figure B was made using an MAF file filtered to only have nonsense mutations. Why does figure B show nonsense mutations that are not visible in figure A? 

 I thought it would have labeled these samples as `Multi_Hit` because there are multiple types of mutations per sample, but the number of `multi_hit` samples does not account for all the missing nonsense mutated samples. Any insight into this behavior is much appreciated. Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Only thing I can think of is that these samples are `Multi_Hit` type in figure-A. However since you're certain that they aren't, I am not so sure what might have gone wrong. Is it possible to share the data from figure-A ? You can change gene names, sample names and remove all sensitive info from the maf if you prefer.

**Comment by tjbencomo** [comment]
Thanks for the quick response! While examining my data to reproduce the issue, I realized I miscounted the number of nonsense mutations. The correct number of nonsense mutations are in fact being displayed properly. Thanks for the help and the really useful package!
