### ISSUE TITLE
Export MAF File to Disk

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#266]
It would be convenient to have a `write.maf` function as a partner for `read.maf` that could export a MAF file modified by `subsetMaf` so that the contents could be uploaded to a Shiny application, for example.

**Comment by PoisonAlien** [comment]
Hi,
There is already a function `write.mafSummary` which will do this along with other summary files.

**Comment by DarioS** [comment]
It works. I read the documentation but didn't get the impression one of the output files would be a MAF file. Perhaps a description of each of the four output files could be listed in the Details section of the function's documentation so users could immediately know what it produces.

**Comment by PoisonAlien** [comment]
Thank you. I will update the docs.
