### ISSUE TITLE
Limit Cores for plotApobecDiff

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#267]
I am doing an analysis on a shared server. `plotApobecDiff` appears to be using 12 CPUs and there's no parameter to change this. It would be useful to have a parameter which the user can change.

**Comment by PoisonAlien** [comment]
Hi,
`plotApobecDiff` is just a plotting function and never uses any threads. Are you sure its this function which is using cores ? How did you measure it ?

Only function in maftools to use multi-threads is `extractSignatures` which in turn has an argument `parallel` to control number of cores.

**Comment by DarioS** [comment]
I saw a value like 1208 in the %CPU column of `top`. It became high when I used `plotApobecDiff` and never exceeded 100% for the other functions.  I stepped through the code and the line which causes high CPU usage is `mc = mafCompare(m1 = apobec.maf, m2 = nonapobec.maf, m1Name = "Enriched", 
    m2Name = "nonEnriched", minMut = 2, useCNV = TRUE)`. Then, I stepped through `mafCompare`. The high CPU usage is caused by the for loop which carries out the Fisher test.

The same problem can be seen by simply doing `fisher=c();for(i in 1:10000) fisher=rbind(fisher, data.table(A=1, B=2, C=3))` The inefficient row binding seems to be the problem. Perhaps you should put the value of each iteration of the for loop into a list and use `do.call(rbind, resultList)` at the end. For example,

```r
resultList <- lapply(1:10000, function(x) data.table(A=1, B=2, C=3))
allTable=do.call(rbind, resultList)
```

is much faster and does not suffer from the same problem as the for loop.

**Comment by PoisonAlien** [comment]
I see.. This makes sense. I will replace for loop with a vectorised code and see if it helps.
Thanks for tracking the issue. I will update it as soon as I can.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the suggestion. I've replaced for-loop with vectored lapply.
I am closing this for now, please feel free to reopen if needed.
