### ISSUE TITLE
subsetMaf Creates Empty Data Tables for TCGA Data

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#268]
The code assumes that the MAF file contains barcodes of 12 characters `if(isTCGA) {tsb = substr(x = tsb, start = 1, stop = 12)}` but the MAF files which can be downloaded from Genomic Data Commons don't. I created my MAF object:

```r
library(TCGAbiolinks)
library(maftools)
MAF <- read.maf(GDCquery_Maf("HNSC", pipelines = "muse"))
> MAF
An object of class  MAF 
                        ID summary    Mean Median
 1:             NCBI_Build  GRCh38      NA     NA
 2:                 Center      BI      NA     NA
 3:                Samples     506      NA     NA
 4:                 nGenes   14538      NA     NA
 5:      Missense_Mutation   50169  99.345     67
 6:      Nonsense_Mutation    4133   8.184      5
 7:       Nonstop_Mutation      56   0.111      0
 8:            Splice_Site    1246   2.467      1
 9: Translation_Start_Site      80   0.158      0
10:                  total   55684 110.265     74
```

The TSBs are much longer:

```r
> getSampleSummary(MAF)[, 1]
             Tumor_Sample_Barcode
  1: TCGA-F7-A624-01A-22D-A30E-08
  2: TCGA-CV-7568-01A-11D-2229-08
  3: TCGA-D6-6516-01A-11D-1870-08
  4: TCGA-CR-7402-01A-11D-2012-08
  5: TCGA-CN-4723-01A-01D-1434-08
 ---                             
501: TCGA-CR-7392-01A-11D-2012-08
502: TCGA-CQ-A4CH-01A-11D-A25Y-08
503: TCGA-CV-A6K0-01B-21D-A31L-08
504: TCGA-CV-5971-01A-11D-1683-08
505: TCGA-CV-A45T-01A-11D-A24D-08
```

This causes the function to stop with an error because it looks for an exact match `maf.dat = maf.dat[Tumor_Sample_Barcode %in% tsb, ]`. It should be looking for partial matches or perhaps also extracting the sub-string of the barcode from the MAF object, too. Perhaps Genomic Data Commons changed the format of MAF files slightly and this causes maftools to fail on the new format.

**Comment by PoisonAlien** [comment]
You first command read.maf should be run with `isTCGA = TRUE` for this to work.

```r
MAF <- read.maf(GDCquery_Maf("HNSC", pipelines = "muse"), isTCGA = TRUE)
```

**Comment by DarioS** [comment]
The `isTCGA` parameter is useful to know. I was following TCGAbiolinks' vignette and it does not use that parameter. I'll let the maintainer know about it.
