### ISSUE TITLE
Enrichment Confidence Intervals Incorrectly Stored

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#269]
Using the example from the vignette, I see the upper bound and lower bound are switched.

```r
$results
     Hugo_Symbol Enriched nonEnriched       pval        or      ci.up     ci.low adjPval
  1:        TP53        2          13 0.08175632 5.9976455 0.49875432  46.608861       1
  2:        TET2        1          16 0.45739351 1.9407002 0.03882963  18.983979       1
  3:        FLT3        2          45 0.65523131 1.4081851 0.12341748  10.211621       1
``` 

The upper bound should be - by definition - larger than the lower bound.

Also, the APOBEC enriched samples look suspicious. All of the samples determined to be enriched have high p-values (e.g. 0.97) and FDR of 1. I don't think a journal reviewer would like that.

```r
> laml.tnm[[2]][, c(1, 39, 44, 36, 43)][1:10]
    Tumor_Sample_Barcode fisher_pvalue fdr APOBEC_Enrichment APOBEC_Enriched
 1:         TCGA-AB-2946     0.7876588   1          3.428571             yes
 2:         TCGA-AB-2812     0.8382664   1          2.388889             yes
 3:         TCGA-AB-2941     0.8562368   1          3.916667             yes
 4:         TCGA-AB-3012     0.9500478   1          1.769231              no
 5:         TCGA-AB-2897     0.9580635   1          1.117647              no
 6:         TCGA-AB-2910     0.9693494   1          2.555556             yes
 7:         TCGA-AB-2843     0.9699295   1          1.896104              no
 8:         TCGA-AB-3008     0.9753432   1          1.464286              no
 9:         TCGA-AB-2901     0.9804400   1          1.328571              no
10:         TCGA-AB-3007     0.9830072   1          1.270588              no
```

**Comment by PoisonAlien** [comment]
1. Okay, I will double check this and get back to you.
2. For this, APOBEC_Enriched is `yes` [based](https://github.com/PoisonAlien/maftools/blob/master/R/TrinucleotideMatrix.R#L272) on enrichment score (>2). You can manually filter based on p-values from results. Function uses 2 as a cut-off because by definition enrichment score, a value of 2 means there are twice APOBEC related mutations in C>T context than in surrounding 20 bp region of mutated base.

**Comment by PoisonAlien** [comment]
Hi,
Thank you again. Yes, indeed the CI values were interchanged. I have fixed it. You will have to install from GitHub for updated version. 

I am closing the issue for now. Please feel free to reopen if necessary.
