### ISSUE TITLE
rainfallPlot ignore mutations in X and Y chromosomes?

### ISSUE THREAD

**Issue by crazyhottommy** [PoisonAlien/maftools#27]
Hi,

I used `rainfallPlot()`, the resulting figure does not show any mutations points on X and Y chromosomes. do you filter out those first?

![screenshot 2016-11-16 16 58 07](https://cloud.githubusercontent.com/assets/4106146/20369300/ce1a03b2-ac1d-11e6-94d4-a05b8672ee9d.png)

Although 4 change points were detected, I do not see any clustered mutations on the four arrows.

Thanks,
Tommy

**Comment by PoisonAlien** [comment]
Hi,
No it doesn't remove X and Y chromosomes. All 24 (22 + XY) chromosomes are plotted. How are chromosome X and Y are labelled in MAF ? 

For change-point, I must admit that its not a robust method ! It will detect any genomic loci where inter-event distance changes. For e.g, in case of chromosome 4, the detected changepoint at the center, that is where mutation burden is higher compared to beginning of chromosome. See #13 for more. I am also thinking of removing this option in future update.

**Comment by crazyhottommy** [comment]
It is labeled as X and Y. I check the maf files under unix:

```bash
less my.maf | cut -f5 | sort | uniq -c
   1 #version 2.4
4693 1
2553 10
3541 11
3679 12
3177 13
2508 14
1583 15
1299 16
1258 17
2248 18
1165 19
5733 2
1414 20
1024 21
 467 22
4340 3
4630 4
3010 5
4031 6
4271 7
4032 8
3093 9
   1 Chromosome
1504 X
 130 Y

```
I also checked the maf object after reading into maftools;

```{r}
my.maf@data %>% group_by(Chromosome) %>% summarise(cnt = n()) %>% print(n=23)
# A tibble: 23 × 2
   Chromosome   cnt
        <int> <int>
1           1 10457
2           2 12185
3           3  9601
4           4  9222
5           5  7765
6           6  8722
7           7  8333
8           8  8013
9           9  5885
10         10  5337
11         11  6939
12         12  7069
13         13  5875
14         14  4881
15         15  3578
16         16  2957
17         17  2840
18         18  4430
19         19  2221
20         20  2725
21         21  2007
22         22  1121
23         NA  4091
```
There are NAs produced and I do not see X and Y.

**Comment by crazyhottommy** [comment]
I fixed the merged maf, but still no points showing in the X and Y for the rainfall plot.

```bash
 cat merged.maf | cut -f5 | sort | uniq -c
10457 1
5337 10
6939 11
7069 12
5875 13
4881 14
3578 15
2957 16
2840 17
4430 18
2221 19
12185 2
2725 20
2007 21
1121 22
9601 3
9222 4
7765 5
8722 6
8333 7
8013 8
5885 9
   1 Chromosome
   2 MT
3709 X
 380 Y

```

```{r}
my.maf@data %>% group_by(Chromosome) %>% summarise(cnt = n()) %>% print(n=25)
# A tibble: 25 × 2
   Chromosome   cnt
        <chr> <int>
1           1 10457
2          10  5337
3          11  6939
4          12  7069
5          13  5875
6          14  4881
7          15  3578
8          16  2957
9          17  2840
10         18  4430
11         19  2221
12          2 12185
13         20  2725
14         21  2007
15         22  1121
16          3  9601
17          4  9222
18          5  7765
19          6  8722
20          7  8333
21          8  8013
22          9  5885
23         MT     2
24          X  3709
25          Y   380
```

**Comment by PoisonAlien** [comment]
Ahh ! I found the culprit. While tranforming segments into linearized scale, I forgot to convert chrX and chrY to 23 and 24. I will fix it soon ! 
Meanwhile, sorry to ask, but can you change X, Y to 23, 24  in your MAF and try ? It should work.

**Comment by crazyhottommy** [comment]
I downloaded the dev branch of maftools, the problem is still there.

**Comment by PoisonAlien** [comment]
ohh ! that is odd. Wait let me see..

**Comment by PoisonAlien** [comment]
Hi Tommy,
I am not able to reproduce this on a similar maf with same chromosome name as yours. Can you share the data for above sample ?
