### ISSUE TITLE
Adding LOH to heat map

### ISSUE THREAD

**Issue by simonlee184** [PoisonAlien/maftools#270]
Hi Anand,
     In my maf file, I have a column stating whether or not a mutation also has loss of heterozygosity, and was wondering how I could add that information in the Oncoplot as a diagonal white line. 
I was originally thinking that maybe I could instead add LOH as a copy number alteration in cnTable when reading in the maf file, though I'm not sure if that would work. And even if this were to work, I'm not sure how I could tilt the line. 

Simon

**Comment by PoisonAlien** [comment]
Hi Simon,
I think this is bit complicated and for now it is not possible to include additional features such as this into the plot.
But I can push a fix for it. I will update you soon.

**Comment by simonlee184** [comment]
I've tried adding an LOH bar by using cnTable but that didn't work. However, I saw that you were able to add a dot or star in the middle of the plot when looking at the somatic alterations. Is that also possible to do in the oncoplot? I understand how making a diagonal white line can make coding and visualization of a plot difficult particularly in instances where there are dozens or hundreds of samples.

**Comment by PoisonAlien** [comment]
Hi Simon,
Yes, that is the original plan. Sorry for the delay, things have been busy so I couldn't spare time to implement it. I will do it by the weekend and update you.

**Comment by PoisonAlien** [comment]
Hi Simon,

Apologies for the delay. I have pushed a fix to address it. There is an argument `additionalFeature` in the oncoplot which accepts a vector two argument consisting of the column name, and the value in that column name to be highlighted. For ex,

```r
#load tcga acc cohort
>TCGAmutations::tcga_load(study = "ACC") 
#It consists of column called IMPACT
>tcga_acc_mc3@data[,.(Tumor_Sample_Barcode, Hugo_Symbol, IMPACT)]
 Tumor_Sample_Barcode Hugo_Symbol   IMPACT
   1:         TCGA-OR-A5J1        OPN4 MODERATE
   2:         TCGA-OR-A5J1       KLRB1 MODERATE
   3:         TCGA-OR-A5J1       SALL2 MODERATE
   4:         TCGA-OR-A5J1    C15orf27     HIGH
   5:         TCGA-OR-A5J1      KLHDC4 MODERATE
  ---                                          
7743:         TCGA-PK-A5HC        PGM5 MODERATE
7744:         TCGA-PK-A5HC     C9orf41 MODERATE
7745:         TCGA-PK-A5HC      PRUNE2 MODERATE
7746:         TCGA-PK-A5HC      PNPLA4     HIGH
7747:         TCGA-PK-A5HC       SYTL4 MODERATE

#Highlighting all HIGH impact variants
oncoplot(maf = tcga_acc_mc3, additionalFeature = c("IMPACT", "HIGH"))
![image](https://user-images.githubusercontent.com/8164062/55291397-87574780-53de-11e9-84f7-b68540bf00c3.png)
```

Could you try with your data and let me know ?

Thanks again,
Anand

**Comment by simonlee184** [comment]
Unfortunately, oncoplot doesn't accept the additionalFeature argument. My data contains a column labelled 'loh' where the only two entries are 'yes' and 'no', so if I try this command:
**oncoplot(maf = laml, top = 10, fontSize=12,colors=vc_cols,showTumorSampleBarcodes = TRUE,additionalFeature = c("loh","yes"))**
, I end up with this output:
**unused argument (additionalFeature = c("loh", "yes"))**

I've tried only selecting the tumor sample barcode, Hugo symbol, and loh status, and I've tried renaming the column to IMPACT, but still nothing.

**Comment by PoisonAlien** [comment]
Did you update the package from GitHub ?

**Comment by simonlee184** [comment]
It works now, thank you so much! I really appreciate all your time and effort.

**Comment by PoisonAlien** [comment]
Glad to be of help. I am closing this issue now, please feel free to re-open if necessary.

**Comment by simonlee184** [comment]
Hi Anand,
 This features works great, but is only available in Oncoplot. Is it possible to also have the additionalFeature argument in the coOncoplot as well?
