### ISSUE TITLE
is this possible to keep non-mutated sample in MAF file to accurately calculate the mutation rate

### ISSUE THREAD

**Issue by wangdatou2009** [PoisonAlien/maftools#271]
Just think this patients' group contain someone that really is non-somatic-mutated for all genes

**Comment by wangdatou2009** [comment]
and what the format of those in MAF

**Comment by PoisonAlien** [comment]
Hi, 
They are always used for mutation rate estimation. Which function are you referring to ? Is it regarding header in `oncoplot` ?

**Comment by wangdatou2009** [comment]
Yes, exactly. Can I just write like that?  using NA for other fields,  and just keep ID info

Hugo_Symbol     Entrez_Gene_Id  Center  NCBI_Build      Chromosome      Start_Position  End_Position    Strand  Variant_Classification        Variant_Type    Reference_Allele        Tumor_Seq_Allele1       Tumor_Seq_Allele2       dbSNP_RS        Tumor_Sample_Barcode  Mutation_Status AAChange        Transcript_Id   TxChange        sample_id       GeneDetail.refGene

NA      NA      center      hg19    NA      NA      NA      NA      NA      NA      NA      NA      NA      NA      ID     NA       NA      NA      NA      ID        NA

**Comment by PoisonAlien** [comment]
Hi,
I am sorry - I am bit confused regarding the issue. Could you be bit more specific ?

**Comment by wangdatou2009** [comment]
Basically, MAF are made manually and individually in my case. Reported variants are selected, so some patients in my cohort are mutated, some are non-mutated in the context. To calculate the mutation frequency fairly, I need to put those non-mutated sample into the aggregated MAF. That's why I make this kind of fake MAF for non-mutated sample

**Comment by PoisonAlien** [comment]
If you have already added these fake samples then its already taken care of. I think its fine. Do you see any discrepancies in the number of samples in the maf and the reported number in the header ?
