### ISSUE TITLE
remove outlier from plotmafSummary

### ISSUE THREAD

**Issue by ShixiangWang** [PoisonAlien/maftools#273]
Dear @PoisonAlien,

Any ideas to remove outliner from variants per sample?

![image](https://user-images.githubusercontent.com/25057508/55067853-709db180-50bb-11e9-891e-4831e02bb1f9.png)
 
or provide a truncated y axis?

Best,
Shixiang

**Comment by PoisonAlien** [comment]
I see the problem.
Best way would be to use `log10` scale which should fix the issue. I will push a commit soon.

**Comment by ShixiangWang** [comment]
@PoisonAlien Thanks :)

**Comment by ShixiangWang** [comment]
@PoisonAlien The cocoplot has the same issue, could you also modify it?

![image](https://user-images.githubusercontent.com/25057508/55070423-31725f00-50c1-11e9-8e8f-7f3634835fc6.png)

**Comment by PoisonAlien** [comment]
Hi @ShixiangWang ,
Thanks for the issue. I have added arguments to `oncoplot` and `plotmafSummary` to draw the bars on log10 scale. 

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)

oncoplot(maf = laml, logColBar = TRUE)
plotmafSummary(maf = laml, log_scale = TRUE)
```

Let me know if this works fine for you.

**Comment by ShixiangWang** [comment]
@PoisonAlien It works, thanks.
