### ISSUE TITLE
Incompatible rds object, protein_domains.RDs in lollipopPlot

### ISSUE THREAD

**Issue by sbamin** [PoisonAlien/maftools#276]
I am using R 3.4.2 and dev version of maftools (96a70f71147ace00748caaf612c3d06c0fc47a7a). While using `lollipopPlot` function, I get following error as rds file, *maftools/extdata/protein_domains.RDs* has been written in newer R. I made it work by saving protein_domains data frame  but better if it is either kept as table format or saved as rds with R 3.4.

```r
Error in readRDS(file = gff) : 
  cannot read workspace version 3 written by R 3.6.0; need R 3.5.0 or newer
```

Thanks a lot for keeping maftools up-to-date and well-documented.

Related #244

**Comment by PoisonAlien** [comment]
Oh! That's weird. I never tested this package on 3.6. 
I am still on recent build 3.5.3. I will check this again and make necessary changes. Thanks for reporting.

**Comment by PoisonAlien** [comment]
Yes, you were right. I did run it with 3.6. Sorry about that. I have made it backward compatible now. Could you please check it and let me know if it works for you ?
Thank you.

**Comment by sbamin** [comment]
Thanks Anand and that worked.
