### ISSUE TITLE
mafSurvival plot does not correspond with real time 

### ISSUE THREAD

**Issue by clersdom** [PoisonAlien/maftools#277]
I am working with maftools survival analysis function (mafSurvival), and the output results I am getting do not correspond with the data I have. I am concerned about how the comparison is made, as for example, if I have under "Hugo_Symbol" altered KRAS variants in my maf file, does it compare survival against the rest of the samples that do not appear with this Hugo_Symbol (KRAS) in the same column, thus corresponding to the wild-type KRAS?

I am running:
maSurvival(maf, genes = 'KRAS', time= 'months', Status = 'event_death', addInfo = TRUE)

The resultant plot is accurate regarding the time for the mutant KRAS, but the time for the wt KRAS on the x axis does not represent the time for the rest of samples with no KRAS alteration.

Many thanks,

**Comment by PoisonAlien** [comment]
Hi,
Yes, it compares those samples where KRAS appears as mutated against those where it doesn't (WT).

Is it possible to provide a reproducible example ?
