### ISSUE TITLE
Minimum Required Columns For Read 'MAF'

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#278]
Could `read.maf`'s documentation specify what are the minimal columns to create a valid MAF class object? This information would be useful to know if you don't really have a MAF, but want to create an object you could easily and quickly draw an oncoplot with. I was looking at IGV's Issue Tracker and noticed there are [multiple varieties of MAF](https://github.com/igvteam/igv/issues/642#issue-427188510) and it made me wonder if MAFtools supports an input table that only has a few important columns and what the column names of those columns would be.

**Comment by PoisonAlien** [comment]
Hi,

This has been [mentioned](https://bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/maftools.html#3_maf_field_requirements) in the vignette. 

You need following mandatory columns to read and generate an MAF object.
```
Hugo_Symbol, Chromosome, Start_Position, End_Position, Reference_Allele, Tumor_Seq_Allele2, Variant_Classification, Variant_Type and Tumor_Sample_Barcode.
```

Even if you dont really have above basic columns (such as ref-allele, tum-seq allele, chr) - for onocplot purpose you can create a dummy columns with the above names and fill them with NAs. It should just work fine. For onocplot you will only need `Tumor_Sample_Barcode, Hugo_Symbol, and Variant_Classification`

**Comment by DarioS** [comment]
The vignette answers my question.
