### ISSUE TITLE
readGistic error

### ISSUE THREAD

**Issue by clersdom** [PoisonAlien/maftools#279]
Hello, 

I am trying to read Gistic outputs but I am having this error:

Processing Gistic files..
Error in data.table::fread(input = gisticAllLesionsFile, stringsAsFactors = FALSE,  : 
  input= must be a single character string containing a file name, a system command containing at least one space, a URL starting 'http[s]://', 'ftp[s]://' or 'file://', or, the input data itself containing at least one \n or \r

This is how I am reading the files, and they are correctly imported:
all.lesions <- read.csv("all_lesions.conf_90.txt", sep= "\t", stringsAsFactors = FALSE)
amp.genes <- read.csv("amp_genes.conf_90.txt", sep= "\t", stringsAsFactors = FALSE)
del.genes <- read.csv("del_genes.conf_90.txt", sep= "\t", stringsAsFactors = FALSE)
scores.gis <- read.csv( "scores.gistic", sep= "\t", stringsAsFactors = FALSE)

gistic_maftools <- readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, cnLevel = "all", gisticScoresFile = scores.gis, )

And my session info
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.14.3

Any idea why is not working? Do I have to do any manipulation to the output files from gistic?

**Comment by ShixiangWang** [comment]
@clersdom Please read this part of vignette <https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#8_processing_copy-number_data>. You shoud not read file into R, just pass the file paths to `readGistic()` function.

**Comment by PoisonAlien** [comment]
Yes, as @ShixiangWang suggested, you don't have to read the files first. Directly pass the file names to the functions. 

```r
gistic_maftools <- readGistic(gisticAllLesionsFile = "all_lesions.conf_90.txt", 
                                                  gisticAmpGenesFile = "amp_genes.conf_90.txt", 
                                                  gisticDelGenesFile = "del_genes.conf_90.txt", 
                                                  cnLevel = "all", gisticScoresFile = "scores.gistic")
```

**Comment by clersdom** [comment]
Many thanks for your comments. I was reading the files into R as I did for read.maf, so I thought it was the same for readGistic function.
