### ISSUE TITLE
Double-counting in gene summary calculation

### ISSUE THREAD

**Issue by rdmorin** [PoisonAlien/maftools#28]
I have been running oncodriveClust in maftools and found that genes with total mutation counts below minMut were sometimes found in the result. I traced this to an issue in the function that calculates the gene-level summary of mutations. 

Unless I'm mistaken, the fix is an easy one:

===================================
if(any(colnames(hs.cast) %in% c('Amp', 'Del'))){
    hs.cast.cnv = hs.cast[,colnames(hs.cast)[colnames(hs.cast) %in% c('Amp', 'Del')], with =FALSE]
    hs.cast.cnv$CNV_total = rowSums(x = hs.cast.cnv)
    
    hs.cast = hs.cast[,!colnames(hs.cast)[colnames(hs.cast) %in% c('Amp', 'Del')], with =FALSE]
    hs.cast[,total:=rowSums(hs.cast[,2:ncol(hs.cast), with = FALSE])]
    
    hs.cast = cbind(hs.cast, hs.cast.cnv)
    hs.cast = hs.cast[order(total, CNV_total, decreasing = TRUE)]
    
  }else{
    hs.cast[,total:=rowSums(hs.cast[,2:ncol(hs.cast), with = FALSE])]
    hs.cast = hs.cast[order(total, decreasing = TRUE)]
#the line below needs to be deleted
    hs.cast[,total:=rowSums(hs.cast[,2:ncol(hs.cast), with = FALSE])]
    hs.cast[order(total, decreasing = TRUE)]
  }

==================================

#normal functionality
> which(s.old[,Hugo_Symbol]=="ADCYAP1R1")
[1] 2259
> s.old[2259,]
   Hugo_Symbol Frame_Shift_Del Frame_Shift_Ins In_Frame_Del In_Frame_Ins Missense_Mutation Nonsense_Mutation
1:   ADCYAP1R1               0               0            0            0                 2                 0
   Nonstop_Mutation Splice_Site Translation_Start_Site total MutatedSamples
1:                0           0                      0     4              1

#after change to code
> s.f=getGeneSummary(laml.f)
> which(s.f[,Hugo_Symbol]=="ADCYAP1R1")
[1] 2259
> s.f[2259,]
   Hugo_Symbol Frame_Shift_Del Frame_Shift_Ins In_Frame_Del In_Frame_Ins Missense_Mutation Nonsense_Mutation
1:   ADCYAP1R1               0               0            0            0                 2                 0
   Nonstop_Mutation Splice_Site Translation_Start_Site total MutatedSamples
1:                0           0                      0     2              1

#actual MAF input (I pruned out the latter columns):

grep ADCYAP1R1 in.maf 
ADCYAP1R1	0	.	GRCh37	chr7	31132339	31132339	+	Missense_Mutation	SNP	A	A	G	novel		
ADCYAP1R1	0	.	GRCh37	chr7	31132340	31132340	+	Missense_Mutation	SNP	G	G	C	novel

**Comment by PoisonAlien** [comment]
Hi Ryan,

Sorry to get back to you on this so late. This is so helpful and a major bug, don't know how I missed it. Those two duplicated lines has to go. 

Thanks for being so vigilant ! I will fix it soon.

**Comment by PoisonAlien** [comment]
Hi,
I have fixed the issue. Thanks again.
