### ISSUE TITLE
Error in running oncoplot and empty first columns

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#281]
Hello,

Sorry, I am being stopped when running oncoplot

```
> oncoplot(maf = laml, top = 1, fontSize = 12)
Error in oncoplot(maf = laml, top = 1, fontSize = 12) : 
  Cannot create oncoplot for single gene. Minimum two genes required ! 
```
Also I noticed I don't have any gene name

```
> head(var.annovar.maf[1:2,1:7])
   Hugo_Symbol Entrez_Gene_Id  Center NCBI_Build Chromosome
1:        <NA>             NA CSI-NUS       hg19         15
2:        <NA>             NA CSI-NUS       hg19          7
   Start_Position End_Position
1:       67547301     67547301
2:       48443570     48443570
> 
```

Any help please to know what I am doing wrong?

Thank you so much

**Comment by PoisonAlien** [comment]
Hello!
How did you generate your maf files ?

**Comment by beginner984** [comment]
Hi

I firstly used annovar to convert vcf so I used annovar output for your software

Thank you for replying me

**Comment by PoisonAlien** [comment]
Is it possible to share your maf file ? 
Also it should be noted that maftools won't work with single sample.

**Comment by beginner984** [comment]
Sorry what I have tried here was sample .vcf in vcf2maf software to get used to this tool but on my own .vcf I have stopped in producing maf files

I know this is unrelated to you but could you please help me to get maf file for your software?


 I have called somatic SNV by Strelka; Long time I am trying vcf2maf to convert my .vcf files to maf required for any visualization tool like maftools but I am failing. I heard I can use annovar to get something compatible with maftools but annovar rejects .vcf from Strelka.

I am typing

  -bash-4.1$ module load samtools/1.3.2
    -bash-4.1$ module load ensembl-vep/95
    -bash-4.1$ perl vcf2maf.pl --input-vcf /temp/hgig/fi1d18/strelka-2.9.2.centos6_x86_64/bin/demo_somatic_036_2post/results/variants/double_filtered_somatic_036_2post.snvs.vcf --output-maf tests/test.vep.maf --filter-vcf /home/fi1d18/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz --ref-fasta /temp/hgig/fi1d18/hs37d5.fa --vep-path /local/software/ensembl-vep/95/vep --vep-data /home/local/software/ensembl-vep/95/cache/

But program returns empty maf

I have attached one of my .vcf files here

https://www.dropbox.com/s/4lc23an3rdcrios/filtered_1pre_021_somatic.snvs.vcf?dl=0

Could you please help me to convert my .vcf files to maf?

Thank you for any help
