### ISSUE TITLE
abnormal wide black spots when use oncoplot if fontSize is offered

### ISSUE THREAD

**Issue by leoatchina** [PoisonAlien/maftools#283]
Both 1.8.0 install from biocondutor or 1.9.0 via devtools::install_github. If I set fontSize when oncoplot
> oncoplot(maf = mutect_maf, top = 20 , fontSize = 10)

the numbers , letters near axies apperd to be black spot which like stacked one by one together，but if not set fontSize

> oncoplot(maf = mutect_maf, top = 20 )

it works well.

I run docker-rtudio which is writen myself, the system is ubunut 16.04, r 3.5.3, Biomanager 3.8

**Comment by leoatchina** [comment]
![Snipaste_2019-04-16_14-14-57](https://user-images.githubusercontent.com/4470821/56187055-0fcb1e80-6054-11e9-98b8-a2a9d1293b11.jpg)

**Comment by PoisonAlien** [comment]
Hi,
If you're using devel version of the package, keep `fontSize = 1` (or in that range) as you would use in any base plots. Let me know if you still have the issue.

**Comment by leoatchina** [comment]
oh, it's the fontSize  problem,`=1` works good.
Actually I have do `?oncoplot`, it appeard the default `fontSize = 10`.
So, have you changed the font base ?

**Comment by PoisonAlien** [comment]
Yes. Earlier version of oncoplots depended on ComplexHeatmap library. Now everything has been re-implemented in base graphics. 

Please let me know if you find any bugs. I am closing this issue for now.
