### ISSUE TITLE
Custom Variant Classification Breaks Oncoplot

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#284]
An example of oncoplot breakage is

```r
library(maftools)
plotData <- data.frame(Hugo_Symbol = c("TP53", "MYC", "TP53"),
                       Chromosome = '.',
                       Start_Position = '.',
                       End_Position = '.',
                       Reference_Allele = '.',
                       Tumor_Seq_Allele2 = '.',
                       Variant_Classification = rep("Splice Site", 3),
                       Variant_Type = '.',
                       Tumor_Sample_Barcode = c("John", "John", "Sam"))
copyTable <- data.frame(Gene = "KRAS", Sample = "John", Status = "Del")
MAF <- read.maf(plotData, cnTable = copyTable, vc_nonSyn = "Splice Site")
  NOTE: Removed 1 duplicated variants
oncoplot(MAF)
```

Colours are missing from the plot and MYC is lost entirely. There's no duplicated variant, but it's considered to be one and removed by `read.maf`. I don't like using labels which look like computer code (containing _ or ,) in publication graphics so I want to rename the classes to look more like those used in professional graphics.

**Comment by PoisonAlien** [comment]
Hello,
oncolplot has a pre built color coding schemes for standard MAF variant classification entries. Since, you're using own terms, you will also have to provide manual color list. For the first step, you can use read.maf with `removeDuplicatedVariants = FALSE`

Below code works for your toy data.
```r
> read.maf(plotData, cnTable = copyTable, vc_nonSyn = "Splice Site", removeDuplicatedVariants = FALSE)
> cols = RColorBrewer::brewer.pal(n = 3, name = "Dark2")
> names(cols) = c('Splice Site', 'Amp', 'Del')
> oncoplot(maf = x, colors = cols)
```

**Comment by DarioS** [comment]
Indeed. The documentation didn't specify that an explicit colour scheme is mandatory, though.
