### ISSUE TITLE
Application of the software

### ISSUE THREAD

**Issue by cshen226** [PoisonAlien/maftools#285]
Is this software suitable for other genomes? Such as plant genome.Thank you!

**Comment by ShixiangWang** [comment]
I think the basic functions are suitable for any MAF-like data. But note some features are designed for tumor studies.

**Comment by cshen226** [comment]
![图片](https://user-images.githubusercontent.com/16556829/56274825-116b1400-6132-11e9-8443-cc1e9ca5a9fc.png)
Thank you ! This is my data. Could you help me how to read my data? 
![图片](https://user-images.githubusercontent.com/16556829/56274852-247de400-6132-11e9-904a-0658adab594d.png)

**Comment by ShixiangWang** [comment]
Your code stop here @cshen226 

https://github.com/PoisonAlien/maftools/blob/ea2693ab354a7d988f1a2a93f8d15a048237725b/R/annovarToMaf.R#L192

I think it is an issue caused by usage change of `fread` function, @PoisonAlien

**Comment by ShixiangWang** [comment]
It is indeed another problem. 

The first problem is your code stop at `fread()` function, could you run following code?

```
> ens = system.file('extdata', 'ensGenes.txt.gz', package = 'maftools')
> ens = data.table::fread(cmd = paste('zcat <', ens), sep = '\t', stringsAsFactors = FALSE)
```

I can run it successfully in my MacOS.

The second problem is no plant annotation provided. 

![image](https://user-images.githubusercontent.com/25057508/56276834-d66adf80-6135-11e9-9b78-896eb59a0485.png)

Could you provide plant data with the same format so @PoisonAlien  can add a new feature for supporting genome besides human?

**Comment by cshen226** [comment]
Do you need which format data ? reference genome ?

**Comment by ShixiangWang** [comment]
@cshen226 Don't you see the snapshot above, you need to prepare gene symbol/id mapping.

And did you get an error when you run 

```
> ens = system.file('extdata', 'ensGenes.txt.gz', package = 'maftools')
> ens = data.table::fread(cmd = paste('zcat <', ens), sep = '\t', stringsAsFactors = FALSE)
```

`annovarToMaf()` function does not use `refBuild` option for calculation, it just stores whatever you input, thus it does not matter.

**Comment by PoisonAlien** [comment]
Hi @cshen226 ,
Sorry for the delay. As @ShixiangWang suggested you can use maftools but with a limited functionality. Regarding annovartomaf, how did you run annovar tool ? Did you use ensemble as the annotation source ? Also can you share a sample output file from annovar (maybe top 100 or so) ?
