### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by Chitanda-Satou** [PoisonAlien/maftools#288]
Hello,
Is it possible to share an example file ?

_Originally posted by @PoisonAlien in https://github.com/PoisonAlien/maftools/issues/287#issuecomment-485068147_

Of cource yes! 

Could you provide your e-mail? I'd like to send several ANNOVAR files, which may be helpful in addressing issues 
https://github.com/PoisonAlien/maftools/issues/234
and
https://github.com/PoisonAlien/maftools/issues/287

**Comment by PoisonAlien** [comment]
Thank you. You can send them to: anandmt3@gmail.com

**Comment by Chitanda-Satou** [comment]
Sorry for my mistake of opening an new issue. Files have been sent.

**Comment by PoisonAlien** [comment]
Hi, 
I haven't received them yet. Just wondering if something went wrong.
