### ISSUE TITLE
additional edits with TMB visualization and additionalFeatures

### ISSUE THREAD

**Issue by simonlee184** [PoisonAlien/maftools#289]
Hello Anand,
     Maftools is working wonderfully and I've presented it to the lab and they love it since the updates you've made. There were just two small edits we were wondering how we could change.

1) When adding CNAs to the oncoplot, the section on the top shows both the ratio of mutations and also CNAs per sample. However, when representing TMB, we want only to look at the mutations per sample. Is it possible to remove the CNAs altered and only include the mutations?

2) When implementing the additionalFeature option to show whether a sample shows loh, it shows a white dot. Though this function works well, is it possible to increase the size of the dot to make it more visible when printed?

**Comment by PoisonAlien** [comment]
Hi Simon,

I am glad that the updates have been helpful. Thanks for the suggestions, I have added arguments to `oncoplot` function.

`additionalFeatureCol` and `additionalFeatureCex` to control color and size.
`includeColBarCN` for TMB in top barplot.

Also, now you can also [include expression](http://bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/oncoplots.html#05_including_expression_(or_any)_values) (or any sort of numeric) data as a left side bar plot.
