### ISSUE TITLE
plotSignatures issue

### ISSUE THREAD

**Issue by shirleydaidai** [PoisonAlien/maftools#29]
Hi,
I tried to use extractSignatures function and found the result was not consistent with the plotted figure. 
The result shown Signature 3 & 4 were similar to validated Signature_4, however, from the picture you could see they are different. The same thing as Signature_1 & 2.
Can you help to check if I am wrong. 

```
> laml.tnm = trinucleotideMatrix(maf = laml, ref_genome = 'E:/ucsc.hg19.fasta', 
+                                prefix = 'chr', add = TRUE, ignoreChr = 'chr23', useSyn = TRUE)
reading fasta (this might take few minutes)..
Extracting adjacent bases..
matrix of dimension 87x96
> laml.sign = extractSignatures(mat = laml.tnm, nTry = 6, plotBestFitRes = FALSE)
Estimating best rank..
  method   seed rng metric rank sparseness.basis sparseness.coef      rss      evar silhouette.coef silhouette.basis residuals niter cpu
2 brunet random   2     KL    2        0.4802616       0.5718631 18204.83 0.9573528       1.0000000        1.0000000  4308.167   440  NA
3 brunet random   4     KL    3        0.4520756       0.4341126 14054.08 0.9670764       0.7536191        0.8272047  4035.479   790  NA
4 brunet random   3     KL    4        0.4284171       0.4341540 13504.15 0.9683647       0.5846974        0.7104043  3846.275  1310  NA
5 brunet random   3     KL    5        0.4386150       0.4470788 12955.52 0.9696500       0.4601231        0.6525860  3687.892  1760  NA
6 brunet random   1     KL    6        0.4405360       0.4818809 12114.70 0.9716197       0.3969700        0.5699692  3546.226  2000  NA
  cpu.all nrun cophenetic dispersion silhouette.consensus
2      NA   10  0.9731426  0.9330321            0.9612811
3      NA   10  0.9806881  0.8537614            0.9163375
4      NA   10  0.9710437  0.8224865            0.8598038
5      NA   10  0.9127233  0.6518430            0.5939005
6      NA   10  0.8393772  0.6170696            0.4315838
Using 4 as a best-fit rank based on decreasing cophenetic correlation coefficient.
Comparing against experimentally validated 21 signatures.. (See Alexandrov et.al Nature 2013 for details.)
Found Signature_1 most similar to validated Signature_1B. Correlation coeff: 0.775910702869783 
Found Signature_2 most similar to validated Signature_1B. Correlation coeff: 0.353931858288915 
Found Signature_3 most similar to validated Signature_4. Correlation coeff: 0.488376357569433 
Found Signature_4 most similar to validated Signature_4. Correlation coeff: 0.149722296925071 
> plotSignatures(laml.sign)
```

![image](https://cloud.githubusercontent.com/assets/20200043/20584145/fa72e326-b22a-11e6-9979-e3e67482c296.png)

**Comment by PoisonAlien** [comment]
Hi,
Is the maf used here is from package (LAML)? I see matrix of dim 87x96, i.e 87 samples. Example maf has 196 samples. Did you subset it ? 

Regardless, I should admit that the way comparison made to known signature is very naive here and can go off-set sometimes. Results printed are based on maximum simple correlation coefficient. Better way to make a comparison is using cosine similarity. (Sorry I will try to implement it into next version). 

For now you can draw correlation matrix of output and see which signature makes more sense than the printed one. (comparison are made to these [signatures](http://www.nature.com/nature/journal/v500/n7463/fig_tab/nature12477_F2.html) 

```{r}
pheatmap::pheatmap(laml.sign$corTable, cluster_cols = F, cluster_rows = F)
```

**Comment by shirleydaidai** [comment]
Thanks for you quick response. 
Another question I just noticed, why you use only  21 validated signatures not 30 on cosmic website?
The last few signatures might be useful to my research.

**Comment by PoisonAlien** [comment]
Yes you are correct. I wanted to use those updated 30 signatures mentioned on cosmic, but the raw data is not available for them (I couldn't find online, maybe its out there somewhere). For the original 21 signatures, results are downloaded from [here](https://www.mathworks.com/matlabcentral/fileexchange/38724-wtsi-mutational-signature-framework) for comparison. You can also find the same in `extdata` of maftools installation directory.

**Comment by shirleydaidai** [comment]
I look forward to the new version.
This tool is very helpful to me as coding naive person.
Many thanks.
