### ISSUE TITLE
Oncoplot

### ISSUE THREAD

**Issue by dlivgni** [PoisonAlien/maftools#290]
Hi, 

Thank you so much for an amazing tool. I am trying to make an oncoplot using the following code: 

_oncoplot(maf = laml, top = 10, clinicalFeatures = "Diagnose", removeNonMutated = TRUE, sortByAnnotation = TRUE, annotationDat = "clinical.data")_

However, I get this error 

_Error in split.default(anno, as.factor(as.character(anno[, 1]))) : 
  first argument must be a vector_

What does this mean? I have no problems in making a simple oncoplot without clinical data, such as this: _oncoplot(maf = laml, top = 10)_ .. 

Thank you in advance!

**Comment by PoisonAlien** [comment]
Hello,
First, Thank you for using the tool, I am glad that you find it useful.

Did you include clinical data (sample annotations) while reading and generating  `laml` object ?
Why is clinical.data is in quotes ? Is it a file name ?

Also could you post your sessionInfo ?
