### ISSUE TITLE
Oncoplot misreads clinical features

### ISSUE THREAD

**Issue by jeff-meng** [PoisonAlien/maftools#293]
After updating to Maftools v1.8.10, I encountered a new error in the Oncoplot function. Somehow the clinical response categories "CR", "PR"... in my clinical annotation file is turned into "4" "2" ... and no longer matches with the order I'm specifying.

`oncoplot(maf = comb_maf, colors = col, mutsig = mutsig, mutsigQval = 0.1, 
         genes=cm_genes, keepGeneOrder = T, GeneOrderSort = F, #don't sort samples by gene mut
         removeNonMutated=F,
         clinicalFeatures = c("Response","Sample_source"), sortByAnnotation = TRUE, annotationOrder=c("CR","PR","SD","PD","SPP"),
         annotationColor = Response_colors)`

> Values in provided annotation order CR, PR, SD, PD, SPP does not match values in clinical features. Here are the available features..
[1] "4" "2" "3" "1" "5"
Error in sortByAnnotation(numMat = numMat, maf = maf, anno = annotation,  : 
  
In my clinical data, I definitely have a Response column with values "CR" "PR"...
> > clin_data$Response
 [1] "SD"  "PR"  "SD"  "SPP" ...

>

**Comment by PoisonAlien** [comment]
Hi,
Could you install maftools from GitHub and try again ? Lots of issues regarding oncoplot have been fixed recently on GitHub version (which will be on bioconductor by next week) - maybe your issue has been fixed already. 

Let me know.

**Comment by jeff-meng** [comment]
@PoisonAlien , Thanks for the reply! I reinstalled maftools from GitHub a few days ago and again just now with
`install_github(repo = "PoisonAlien/maftools", force=T)`
I got the exact same error!
I would appreciate any further help!

**Comment by PoisonAlien** [comment]
Hello @jeff-meng ,

Thanks for the issue. I can reproduce the error. I have fixed it. Could you try again ? You will have to install it from GitHub. 
Please let me know if this helps.

**Comment by jeff-meng** [comment]
Thank you so much @PoisonAlien for solving the problem so quickly!!

On a related note, I don't think you have documentation in "?oncoplot" for how to add colors for more than one clinical annotation, but I figured out how to do it. It could be useful for others.
```
annot_colors = list(Response = Response_colors, Sample_source = Source_colors)
oncoplot(maf = comb_maf, colors = col, mutsig = mutsig, mutsigQval = 0.1, 
         genes=cm_genes, keepGeneOrder = T, GeneOrderSort = F, #don't sort samples by gene mut
         removeNonMutated=F,
         clinicalFeatures = c("Response", "Sample_source"), sortByAnnotation = TRUE, annotationOrder=c("CR","PR","SD","PD","SPP"),
         annotationColor = annot_colors)
```
