### ISSUE TITLE
Cooncoplot improvements

### ISSUE THREAD

**Issue by simonlee184** [PoisonAlien/maftools#296]
Hi Anand,
    Oncoplot works great and the new modifications have been receiving a lot of praise from all the lab members! One of the major figures I make are comparisons as seen in coOncoplot. However, coOncoplot is missing some added features from oncoplot which were really great.
1) The additionalFeature argument which added a white dot to the plot as well
2) The top argument which allowed me to select how many top genes I wanted to show. At the moment, the default for cooncoplot is at 5, but I'm not sure how I can customize it.

Thank you so much for your time in making this amazing tool.

Simon

**Comment by PoisonAlien** [comment]
Hello,

1. I have included few arguments to CoOncoplots, could you try it again let me know by tomorrow ? Tomorrow is the last day to update bioconductor branch and it will help me to include these changes there as well. 

2. You can use `genes` argument 

Hope this helps. Let me know if it works.

**Comment by simonlee184** [comment]
Fantastic! I'm able to add the additionalFeatures now along with all the modifications, thank you so much!

**Comment by PoisonAlien** [comment]
Glad it worked and thanks for testing. I am closing this issue for now.
