### ISSUE TITLE
NEWS Version Inconsistent with DESCRIPTION

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#297]
The NEWS file mentions 2.0.0 in anticipation of the next Bioconductor update, but the description file has 1.9.55 as its version. For the package version to automatically become 2.0.0 when the next Bioconductor update happens in the next few hours, the version number in the DESCRIPTION file should be 1.99.x so that it automatically becomes 2.0.0 during the update. Otherwise, the next release version will automatically become 1.10.0 rather than 2.0.0. Hope you can change the version in the DESCRIPTION file to 1.99.0 in the next couple of hours and quickly commit to Bioconductor!

**Comment by PoisonAlien** [comment]
Omg, thank you so much! Will do it ASAP.

**Comment by PoisonAlien** [comment]
Hi,
Thanks again for timely reminder. It successfully released as version 2 in release.
