### ISSUE TITLE
how to change annotation size?

### ISSUE THREAD

**Issue by 632771630** [PoisonAlien/maftools#299]

**Comment by 632771630** [comment]
![image](https://user-images.githubusercontent.com/49688226/57209048-6a2f1d80-7009-11e9-8920-b2cd3778080d.png)
![image](https://user-images.githubusercontent.com/49688226/57209085-977bcb80-7009-11e9-808b-0cf1a0d6f8eb.png)
![image](https://user-images.githubusercontent.com/49688226/57209107-ab273200-7009-11e9-8a39-55c6b2ae7163.png)

**Comment by 632771630** [comment]
Thank you so much for an amazing tool. I am trying to make an oncoplot ,but the annotation has some problems

**Comment by ShixiangWang** [comment]
Why not you use `annotationFontSize`?

**Comment by 632771630** [comment]
![image](https://user-images.githubusercontent.com/49688226/57209578-8d5acc80-700b-11e9-99c7-bc9b6650ab25.png)
I use it....but

**Comment by 632771630** [comment]
i guess I don't express what i mean,sorry

**Comment by PoisonAlien** [comment]
Hi,
Could you be more specific on the issue? Are you trying to change font sizes for annotations?
Also please post your sessionInfo ?

**Comment by 632771630** [comment]
yes,when I add  three or more annotation,it look too thin 
![image](https://user-images.githubusercontent.com/49688226/57216777-6c05da80-7023-11e9-9477-bd56b2835018.png)

**Comment by PoisonAlien** [comment]
Only way is to save the image to a pdf file. You will have to play around `legendFontSize`, and `annotationFontSize` to get the right value.

**Comment by 632771630** [comment]
thanks

**Comment by 632771630** [comment]
one more question？ how to extrat oncoplot name order？

**Comment by PoisonAlien** [comment]
You can use `showTumorSampleBarcodes = TRUE` and it will print the names. However you cant extract the sample names itself.
