### ISSUE TITLE
Unable to load MAF file using maftools::read.maf (without loading the entire package)

### ISSUE THREAD

**Issue by brunogrande** [PoisonAlien/maftools#30]
I have developed the habit of calling package functions directly using the `::` notation in R. This way, I don't need to worry about function name conflicts. When doing this to load a MAF file using `maftools::read.maf()`, I run into an error (`could not find function "vcr"`). I can circumvent this error by loading the entire package, but I would prefer not to have to do this. Can you update the package such that the `vcr` function is internally available without me having to load the package? Thanks!

I've included below simple steps to reproduce the error and workaround. 

```
> laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
> laml = maftools::read.maf(maf = laml.maf, removeSilent = T, useAll = F)
reading maf..
Mutation_Status not found. Assuming all variants are Somatic and validated.
Excluding 475 silent variants.
[...]
Creating oncomatrix (this might take a while)..
Error in ifelse(test = length(as.character(x)) > 1, no = as.character(x),  : 
  could not find function "vcr"


> library(maftools)
> laml = maftools::read.maf(maf = laml.maf, removeSilent = T, useAll = F)
reading maf..
Mutation_Status not found. Assuming all variants are Somatic and validated.
Excluding 475 silent variants.
[...]
Creating oncomatrix (this might take a while)..
Sorting..
Summarizing..
[...]
Frequently mutated genes..
[...]
Done !
```

**Comment by PoisonAlien** [comment]
Hi,
I see the problem here. Apparently vcr function has an issue with being called via namespace. I will try to fix it soon. 
Thank you.

**Comment by PoisonAlien** [comment]
Hi,
Sorry, it took some time but I have fixed it. You can install recent version from GitHub (should be on bioconductor release by weekend).
