### ISSUE TITLE
coOncoplot for GISTIC2 results

### ISSUE THREAD

**Issue by jgarces02** [PoisonAlien/maftools#303]
Hi (again) @PoisonAlien, 

And is there any trick to draw the coOncoplot for GISTIC2 results only? I've seen the #188 issue but I haven't a MAF file neither mutation information... any idea? Thanks again!

**Comment by PoisonAlien** [comment]
Ohh.. I see. 
For now its not possible. But I am happy to update the mafCompare function to support gistic objects. I will let you know when its done.

**Comment by MaryGoAround** [comment]
Hello

Is it possible now to have mafCompare function to support gistic objects?

**Comment by PoisonAlien** [comment]
Unfortunately it is not possible yet. 
Also I apologize to @jgarces02 for my tardiness in addressing this. I will implement it in my free time.

**Comment by jgarces02** [comment]
Please, @PoisonAlien. That's not important at all! Thanks!
