### ISSUE TITLE
oncoplot sample number error and annotation bar height control

### ISSUE THREAD

**Issue by HChen1216** [PoisonAlien/maftools#304]
Hi,

I'm using oncoplot and find that the sample number shown in the figure is wrong. I double checked the Tumor_Sample_Barcode column and the correct sample number was returned. But the figure shows more samples. So confused about this.

And is it possible to control the annotation bar height?  

Many thanks!

**Comment by PoisonAlien** [comment]
Hello,
Are you referring to the title of the oncoplot ? How did you generate maf object, did you directly read the file with read.maf ?

No, its not possible to change annotation bar height :|  I would suggest you to save the plot to an pdf file proper height and width to get the best out of it.

**Comment by HChen1216** [comment]
Hi,
I used read.maf to generate the maf object: maf <- read.maf("res.maf", clinicalData = cli). Both the title of the oncoplot and the summary information of the maf object show 103 samples. But when I read the data using res.maf <- read.table("res.maf", sep = "\t", header = T, skip = 1, stringsAsFactors = F), the unique sample number is 101.

Thank you for the confirmation of the annotation bar height issue. I will have a try. :)

**Comment by PoisonAlien** [comment]
Hmm.. I can't imagine any reason why this discrepancy would happen. 
Is it possible to share your maf file so that I can track the issue? If you dont want to attach it here, you can mail me at anandmt3@gmail.com
You can remove all the sensitive data and change barcodes if necessary. Of course if you're not comfortable sharing, I completely understand.

**Comment by HChen1216** [comment]
Sure, very happy to share with you, it's public data! I used vcf2maf to generate the MAF file. It's about 650M..So, is it possible to send you this size? I will try.

**Comment by HChen1216** [comment]
Sure, I will send you this file. I used vcf2maf to generate the MAF file. It's about 650M..So, is it possible to send you this size? I will try.

**Comment by HChen1216** [comment]
I just tried and failed due to the file size limit...

**Comment by HChen1216** [comment]
Great news! I just tried maf <- read.maf(maf = res.maf, , clinicalData = cli) instead of maf <- read.maf("res.maf", clinicalData = cli), it is correct now! I guess it's due to the "removing all the sensitive data" you mentioned above.

Thank you so much!

**Comment by PoisonAlien** [comment]
Hmm.. I still wonder what caused it in the first place. Anyway, please feel free to reopen the issue if you face the issue again.
