### ISSUE TITLE
coOncoPlot: showing sample names has no effect

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#306]
It only adds white space for them but doesn't print them.

**Comment by PoisonAlien** [comment]
I doubt it. I made a dummy maf with sample names made up of numeric values and it prints them. Any chance you can share a reproducible file? Also does `oncoplot` displays sample names with these mafs ?

**Comment by lbeltrame** [comment]
My guess is that again we're dealing with sample names that are made up of only numbers.

**Comment by wangdatou2009** [comment]
Same situation with @lbeltrame 
Try showSampleNames= TRUE with all kinds of SampleNamefont, and it only adds white space for them but doesn't print them.

**Comment by wangdatou2009** [comment]
@PoisonAlien  You can rerun your code for test data in latest commit and no print sample name  

#Primary APL MAF
primary.apl = system.file("extdata", "APL_primary.maf.gz", package = "maftools")
primary.apl = read.maf(maf = primary.apl)
#Relapse APL MAF
relapse.apl = system.file("extdata", "APL_relapse.maf.gz", package = "maftools")
relapse.apl = read.maf(maf = relapse.apl)

genes = c("PML", "RARA", "RUNX1", "ARID1B", "FLT3")

#Shows sample name
coOncoplot(m1 = primary.apl, m2 = relapse.apl, m1Name = 'PrimaryAPL', m2Name = 'RelapseAPL', genes = genes, removeNonMutated = TRUE, showSampleNames = TRUE)

**Comment by wangdatou2009** [comment]
The bug is still there

**Comment by PoisonAlien** [comment]
Hello @wangdatou2009 ,
I tested several tcga datasets and still I can't reproduce the issue. It seems to be working. Could you provide me with a reproducible example?

**Comment by vnrajapakse** [comment]
I'm also noting this issue unfortunately, with the example data set you kindly provided. 
I'm working on a MacBook Pro (OS Version 10.14.6).

**Comment by PoisonAlien** [comment]
Hi @vnrajapakse ,
Thanks for pointing it out. I checked it and for some reason it does not print the names in the first attempt. But re-running the command seems to work. Could you please try this and let me know if this is the same for you?

**Comment by vnrajapakse** [comment]
Hello @PoisonAlien ,
Thank you for your response (and super helpful package)! I tried re-running the command, but this didn't work for me. I put some debug statements inside the if(showBarcodes) { .. } blocks at lines 237 and 245 of print_mat.R. The sample names are properly captured in the rownames of the nm matrix object (as expected). The reasonable looking text() call strangely isn't having an effect. I was wondering about a Mac/RStudio-version specific issue, but I can't yet pin it down to this.
This bit of toy code outputs labels in the plot on my laptop.

plot.new()
nm <- matrix(1:20, nrow = 10)
rownames(nm) <- paste0("row", seq_len(nrow(nm)))
barcode_size <- 0.5
image(nm)
text(x = 0:nrow(nm)/nrow(nm), y = 0,
           labels = rownames(nm), srt = 90, font = 1,
           cex = barcode_size, adj = 1)

**Comment by PoisonAlien** [comment]
Okay, I changed from `text` to `mtext`. It seems to be working fine now. Could you check it once and let me know? You will have to install from GitHub.

```r
BiocManager::install(pkgs = "poisonalien/maftools")
```

**Comment by vnrajapakse** [comment]
Yes - the labels appear now. Thanks so much!
