### ISSUE TITLE
Interpreting the mafCompare output

### ISSUE THREAD

**Issue by JulyJly** [PoisonAlien/maftools#307]
Hi, I'm using your wonderful maftools. It's very useful. I have a question about the mafCompare result. This function performs fisher test on 2x2 contigency table generated from two cohorts to find differentially mutated genes. But the p values of the genes listed in output are not all < 0.05. So my question is how to understand each column of the output? The genes listed in the output are all differentially mutated genes? Thanks!

**Comment by PoisonAlien** [comment]
Hello,
Interpretation is quite simple. First column is the gene name followed by number of mutated samples in the two cohorts that are being compared. Rest of the column are p-value and odds ratios from fishers test. 

Function performs fishers test on all genes above that are mutated above `minMut` in at-least one of the cohorts. However, not all genes in the results are significant. You'll have to use p-value to describe a threshold of significance. That being said fisher test is also sensitive to sample sizes. If your cohorts are small in size its hard to get significanc tp-values.

Hope this helps.

**Comment by JulyJly** [comment]
Hi, thank you for your detailed explanation. It's very clear now! May I ask another question? The default value of minMut is 5. Can I set it to 0?

**Comment by PoisonAlien** [comment]
Yes you can. But be aware - it might give some false positives.

**Comment by lamz138138** [comment]
@JulyJly Hi, I want to know how mafcompare decide whether the gene is mutated in the sample? From the code, it seemed the gene is mutated if it have one mutation, no matter it is intron, exon, synonymous mutation or nonsynonmouse mutation, am I right?

Thanks in advance!

**Comment by lamz138138** [comment]
@PoisonAlien  Hi, I want to know how mafcompare decide whether the gene is mutated in the sample? From the code, it seemed the gene is mutated if it have one mutation, no matter it is intron, exon, synonymous mutation or nonsynonmouse mutation, am I right?

@JulyJly I'm suppose to mention PoisonAlien, so I delete previous post, sorry!

Thanks in advance!

**Comment by PoisonAlien** [comment]
Hello @lamz138138 ,
`mafCompare` only uses any number of nonsynoymous mutations. Silent mutations are not counted.
