### ISSUE TITLE
When analyzing more genes, gene names and percentages are not aligned in coOncoplot 

### ISSUE THREAD

**Issue by JulyJly** [PoisonAlien/maftools#308]
Hi, when I used coOncoplot to compare mutation frequency between two cohorts, I focused on 37 important genes. It is very convenient and works very well. But the gene names and percentages are not aligned in the output figure. And I tried less genes like 5 genes, it has good alignment. I tried to add   arguments to control, none worked. So, how can I address this problem? Thanks!

**Comment by PoisonAlien** [comment]
Is it possible to share the image ?

**Comment by JulyJly** [comment]
![image](https://user-images.githubusercontent.com/50419916/57536834-a4026b80-730a-11e9-8d92-9d7be78ae409.png)

**Comment by PoisonAlien** [comment]
Hi,
Thanks for reporting the issue. It was indeed a bug when the number of genes are larger. I have fixed it. Could you please install from GitHub and let me know if this helps ?

**Comment by JulyJly** [comment]
Hi, I have installed the latest version and it has good alignment now! Thanks for your update! It is very useful!
