### ISSUE TITLE
Factor Levels of Annotations Ignored

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#309]
If one column of annotations is a factor, the order of levels is ignored and they are drawn in alphabetical order. An example of when this is bad is

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
annotateTable <- data.frame(Tumor_Sample_Barcode = levels(laml@data[["Tumor_Sample_Barcode"]]),
                            AlcoholConsumption = factor(sample(c("Low", "Med", "High"), 193, replace = TRUE), levels = c("Low", "Med", "High")))
oncoplot(maf = laml, annotationDat = annotateTable, clinicalFeatures = "AlcoholConsumption",
         groupAnnotationBySize = FALSE, sortByAnnotation = TRUE)
```

It is desirable to consider the factor levels so that the groups are drawn as Low, Med, High from left to right. I will specify `annotationOrder` in the meantime, but it doesn't work for NA values. If I have a group of patients with NA, `annotationOrder = c("Low", "Med", "High", NA)` doesn't work correctly to put the missing values at the end (far right side of plot).

Even without manual ordering, NA values seem to not work. In the vignette, there is one LAML patient with missing FAB_classification in the plot at the end of Section 0.6.

```r
table(LAMLclinical[, "FAB_classification"], useNA = "always")

  M0   M1   M2   M3   M4   M5   M6   M7 <NA> 
  19   44   44   21   39   19    3    3    1 
```

In the legend is a dark grey box with an empty text label but there is a blank rectangle for the right-most patient in the annotation bar rather than the grey rectangle it should be.

![image](https://user-images.githubusercontent.com/631218/57508080-eb591e00-7343-11e9-9442-e72ce8c57ff4.png)

**Comment by PoisonAlien** [comment]
I am not really a big fan of factors. They always assume things and messes up regular code. I usually convert the data to characters which are much easier to work with. You will have to use `annotationOrder` - just like you did. 

I have fixed the issue with `NA`s. Please try again and let me know if this helps. While using `annotationOrder` put NA in quotes. i.e,`annotationOrder = c("Low", "Med", "High", "NA")`

**Comment by DarioS** [comment]
I can get it sorted how I want.
