### ISSUE TITLE
Gene symbols are converted to date

### ISSUE THREAD

**Issue by kpjonsson** [PoisonAlien/maftools#31]
Great package. However, I found that somehow—I can't figure out where in the code—the `read.maf` function converts certain gene symbols to dates à la Excel.

**Comment by PoisonAlien** [comment]
Hi,
I myself haven't observed any such conversions among the files that I have used, and it's not supposed to happen! What platform are you on (windows/nix) ?

**Comment by kpjonsson** [comment]
Sorry my bad. I realized it only happened when I also read a `cnTable` and that turned out to be the source of the problem.
