### ISSUE TITLE
annotationColor Error

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#310]
If I specify `annotationColor`, I get an error

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
annotateTable <- data.frame(Tumor_Sample_Barcode = levels(laml@data[["Tumor_Sample_Barcode"]]),
                            Gender = factor(sample(c("Male", "Female"), 193, replace = TRUE)))
oncoplot(maf = laml, annotationDat = annotateTable, clinicalFeatures = "Gender",
         groupAnnotationBySize = FALSE, sortByAnnotation = TRUE, annotationColor = list(Gender = c("pink", "blue")))
```
results in the error `'legend' is of length 0`. What is the necessary format of `annotationColor` ? The vignettes nor the `oncoplot` function's documentation provide any details. I would like to find at least one example somewhere.

**Comment by PoisonAlien** [comment]
Hi,
Sorry that there is no documented example for this. I have updated vignette and it should be up soon. You were almost close in your example. It should be a list of **named** vectors. 

```r
oncoplot(maf = laml, annotationDat = annotateTable, clinicalFeatures = "Gender",
         groupAnnotationBySize = FALSE, sortByAnnotation = TRUE, 
annotationColor = list(Gender = c("Male" = "pink","Female" = "blue")))
```

**Comment by DarioS** [comment]
The new example is helpful but the description of the variable contains only "Must be a named list." The named vectors part is a vital addition, I think.
