### ISSUE TITLE
read.maf Silently Converts Spaces in Clinical Values to Underscores

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#314]
If there is a column of data with values that contain spaces, they are automatically converted to underscores. For example, I have an Age column with "Less Than 45 Years" and "45 Years or Older".  It would be nice if the output plots didn't have to have Less_Than_45_Years and 45_Years_or_Older showing on them, which looks more like a variable name in code rather than a plot label. Also, it was surprising that values were changed because it isn't documented.

**Comment by PoisonAlien** [comment]
Hi,
Sorry for late reply. 
Yes, by default [it](https://github.com/PoisonAlien/maftools/blob/master/R/summarizeMaf.R#L170) converts spaces to underscore, which makes life bit easier in downstream analysis IMO. But, you're rite - I shouldn't mess up the values. I have commented it out. This was done in earlier days of development when I was testing with TCGA annotations which were real MESS.
Thanks.
