### ISSUE TITLE
When adding cnv data, coOncoplot error

### ISSUE THREAD

**Issue by JulyJly** [PoisonAlien/maftools#315]
Hi, when I tried to add cnv data into my mutation data with the cnTable, I didn't get the expected coOncoplot. My maf object is like this:
> maf
An object of class  MAF 
                        ID summary        Mean Median
......
 5:      Missense_Mutation    8461 83.77227723     68
 6:      Nonsense_Mutation     431  4.26732673      4
 7:       Nonstop_Mutation      12  0.11881188      0
 8:            Splice_Site     248  2.45544554      2
 9: Translation_Start_Site      10  0.09900990      0
10:                  total    9162 90.71287129     73
11:                    Amp    1810 17.92079208     18
12:                    Del       6  0.05940594      0
13:              CNV_total    1816 17.98019802     18

But my coOncoplot is like this:
![image](https://user-images.githubusercontent.com/50419916/57709521-d4ab1380-7630-11e9-9938-4ebbe834632c.png)

Only one sample displays cnv information. Actually my cnv data just includes the genes shown in the figure for the memory saving. So all 1816 cnv should be included in the figure. It looks like that only the samples with no mutation could show the cnv information.

I feel so confused. Any suggestions would be greatly appreciated! Thanks!

**Comment by PoisonAlien** [comment]
Hello,
Can you post your cnv table here? 
It should contain three columns contain `gene name`,`Sample name` and `copy number status`. It appears that your table has only one sample name under `Sample name` column.

**Comment by JulyJly** [comment]
Hi, this is the first 10 rows of my cnv data:
> cnv.table[1:10,]
     gName        sName status
37   MED12 DTB-003-BL_T    Amp
66  RSPO21 DTB-005-BL_T    Amp
72     AR1 DTB-005-BL_T    Amp
89   GNAS2 DTB-008-BL_T    Amp
116 BRCA13 DTB-009-BL_T    Amp
119 CDK123 DTB-009-BL_T    Amp
139 RNF433 DTB-009-BL_T    Amp
141  SPOP3 DTB-009-BL_T    Amp
146    AR3 DTB-009-BL_T    Amp
148 MED123 DTB-009-BL_T    Amp

**Comment by JulyJly** [comment]
It looks like that only the samples with no mutation could display the cnv information.

**Comment by PoisonAlien** [comment]
Hmm.. Okay, I do not have a reproducible example. I will figure out soon..

**Comment by JulyJly** [comment]
Hi,
When I checked the web page regarding maftools (https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#61_required_input_files), it states that an optional copy number data if available. Can be GISTIC output or a custom table containing **sample names, gene names and copy-number status (Amp or Del)**. I just want to confirm with you the order of sample names and gene names. Thanks!

**Comment by JulyJly** [comment]
Hi,
I share the data with you via Dropbox by using your email anandmt3@gmail.com. Could you please help me figure out where I am wrong? Thanks very much!
> load("maf.RData")
> ls()
[1] "cnv.table" "res2.maf" 

cnv.table is the copy number data and res2.maf is the mutation data.

**Comment by PoisonAlien** [comment]
Hello,
Everything seem to be working with the files you shared. What is the issue?

**Comment by JulyJly** [comment]
Hi, the issue is cnv and mutation cannot be shown simultaneously in a same sample. Hong Chen 邮箱：hongchenbioinfo@gmail.com 签名由 网易邮箱大师 定制 On 06/15/2019 05:24, Anand Mayakonda wrote: Hello, Everything seem to be working with the files you shared. What is the issue? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by PoisonAlien** [comment]
You can. 

```r
load('~/Dropbox/maftools/maf.RData')
x = read.maf(maf = res2.maf, cnTable = cnv.table)
#choose random 20 CNV genes
tar_genes = sample(cnv.table[,.N,gName][order(N, decreasing = TRUE)][, gName], size = 20)
oncoplot(maf = x, genes = c(tar_genes, "TP53"))
```
![test](https://user-images.githubusercontent.com/8164062/59555406-deb68e00-8fb1-11e9-9c61-24eb11b9fba2.png)

**Comment by JulyJly** [comment]
Thank you so much for your help! I have figured it out!
