### ISSUE TITLE
Oncoplot, 'subscript out of bounds' and 'not equal to array extent' error

### ISSUE THREAD

**Issue by a00101** [PoisonAlien/maftools#317]
```
target_genes = c("MUTATED_GENE","NON-MUTATED_GENE")

oncoplot(maf=maf_data, genes=target_genes, draw_titv = TRUE,
         removeNonMutated=FALSE)
```

Hi. I'm PhD candidate student in South Korea.
maftools is most useful tools i've ever seen. 

Can it be possible removeNonMutatedGenes=FALSE ? 
Because we focus on the some targeted genes.
what should i do?

Thanks.

**Comment by PoisonAlien** [comment]
Hello,
 You're doing it wrong. your `target_genes` should contain names of genes that you would like to plot. 
e.g;
```r
target_genes = c("TP53", "CDH1")
```
