### ISSUE TITLE
Error thrown in oncodrive function

### ISSUE THREAD

**Issue by rdmorin** [PoisonAlien/maftools#32]
I am getting this error sometimes when I run oncodrive:
my.sig = oncodrive(maf =mymaf, AACol = aacol, pvalMethod = 'zscore',minMut = 5)

Estimating background scores from synonymous variants..
  |                                                                      |   1%Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  :
  length of 'dimnames' [2] not equal to array extent
Calls: oncodrive ... Ops.data.table -> NextMethod -> Ops.data.frame -> matrix
Execution halted

I can't seem to find the cause of this issue.

**Comment by PoisonAlien** [comment]
Hi,
I too have observed this error. Recently data.table had a major [update](https://cran.r-project.org/web/packages/data.table/news.html) (Change log itself a 3 full web pages!) I guess it has something to do with it, I will correct it soon. It seems to work when pvalMethod is set to 'combined' though.

**Comment by PoisonAlien** [comment]
Hi,
I have fixed it. Thank you.
