### ISSUE TITLE
Within-cohort mafCompare

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#320]
It is desirable to be able to choose a column or multiple columns from the clinical annotation to create groups of patients from a single MAF object and do the exact tests based on those (e.g. Partition the samples into smokers and non-smokers, then test for differences in mutation frequency). I thought about creating two objects using `subsetMaf` but it doesn't allow queries on clinical data columns.

**Comment by PoisonAlien** [comment]
`clinicalEnrichment` does this exact thing, except only it doesn't plot it like mafcompare. Maybe try this and see if it helps?

**Comment by DarioS** [comment]
It does what I want. The two functions are quite similar and could be merged into one. If the first two arguments were `m1` and `m2`, `m2` being NULL could indicate a within-cohort comparison should be done and if it were not NULL, then it could mean a between-cohort comparison.
