### ISSUE TITLE
mafSurvival doesn't show confidence interval in KM plot

### ISSUE THREAD

**Issue by zengxiaofei** [PoisonAlien/maftools#321]
```R
mafSurvival(maf=luad, genes=c("TP53", "TTN", "MUC16"), time="days_to_last_follow_up", Status="days_to_death", isTCGA=TRUE, showConfInt=TRUE)
```
Actually I found that the function `mafSurvival.R` does not have the code to process this argument.

![QQ截图20190520184135](https://user-images.githubusercontent.com/22426230/58016918-8f577c00-7b31-11e9-8561-7687e3fe760c.png)

**Comment by PoisonAlien** [comment]
Hello,
Sorry this argument is a reminiscent of older version, and has been deprecated since. I will remove this in next update. Or do you prefer to show CI bands?

**Comment by zengxiaofei** [comment]
Thanks for your reply. Does “deprecated” mean that CI was considered to be inappropriate / not recommended  in the KM plot?

**Comment by PoisonAlien** [comment]
No, its just previous versions used to show CI band, and now I removed the option. I will remove `showConfInt` argument in next update. 
Would you prefer to include CI band?

**Comment by zengxiaofei** [comment]
I'm just learning to use this nice R package and testing available functions & arguments. It's not neccesary for me, but maybe someone else would need it.  : )

**Comment by PoisonAlien** [comment]
Ah got it. Thank you, will take care of it.
