### ISSUE TITLE
clinicalEnrichment Converts F into FALSE and Crashes

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#322]
It is common for clinicians to record gender as M and F. Even if I input the gender column as character type in the creation of a MAF object, it gets converted into `FALSE` during `clinicalEnrichment`, hence the mysterious error information about a logical variable.

```r
> str(MAF@clinical.data)
Classes ‘data.table’ and 'data.frame':	39 obs. of  5 variables:
 $ Gender              : chr  "M" "F" "M" "M" ...
 $ Age                 : chr  "45_Years_or_Older" "45_Years_or_Older" "45_Years_or_Older" "45_Years_or_Older" ...
 $ smoking             : chr  "No" "No" "No" "Yes" ...
 $ alcohol             : chr  "Low" "Low" "Low" "High" ...
 $ Tumor_Sample_Barcode: chr  "OC10" "OC7" "OC6" "OC17" ...
 - attr(*, ".internal.selfref")=<externalptr> 

> clinicalEnrichment(MAF, clinicalFeature = "Gender")
Sample size per factor in Gender:

 F  M 
17 22 
 Error in bmerge(i, x, leftcols, rightcols, xo, roll, rollends, nomatch,  : 
  x.'cf' is a character column being joined to i.'Feature_2' which is type 'logical'. Character columns must join to factor or character columns. 
```

In the meantime, I will use `case_when` function from `dplyr` to relabel the values.

**Comment by ShixiangWang** [comment]
@DarioS It did have the issue. However, you can now use the latest version of **maftools** because the author has fixed it.

I find the problem comes from `reshape2::melt()` and open an issue https://github.com/hadley/reshape/issues/89

**Comment by PoisonAlien** [comment]
Thanks @ShixiangWang , However here the function uses `data.table::melt()`

**Comment by ShixiangWang** [comment]
@PoisonAlien I checked the `melt()` and find `data.table` use `reshape2::melt()` inside to process class `matrix`.

```
> data.table::melt
function (data, ..., na.rm = FALSE, value.name = "value") 
{
    if (is.data.table(data)) {
        UseMethod("melt", data)
    }
    else {
        ns = tryCatch(getNamespace("reshape2"), error = function(e) stop("The melt generic in data.table has been passed a ", 
            class(data)[1L], " (not a data.table) but the reshape2 package is not installed to process this type. Please either install reshape2 and try again, or pass a data.table to melt instead."))
        ns$melt(data, ..., na.rm = na.rm, value.name = value.name)
    }
}
<bytecode: 0x7ff39bb198d0>
<environment: namespace:data.table>
```

Anyway, I think you can close this issue now. :)

**Comment by PoisonAlien** [comment]
`data.table` doesn't [depend](https://github.com/Rdatatable/data.table/blob/master/R/fmelt.R#L1) on `reshape2`. Also from 1.12.3 `data.table::melt` doesnt work on matrix/data.frame objects as it forces user to convert it to `data.table`. Altogether yes, its fixed. Thanks :)
