### ISSUE TITLE
# samples in the oncoplot

### ISSUE THREAD

**Issue by patidarr** [PoisonAlien/maftools#324]
Hi,

As you are getting  total # samples from maf file, it maybe incorrect in cases where maf is only created on targeted panel or it includes actionable variants only, for such cases would it be possible for you to either get the #number of samples from clinical annotation file or from an user provided argument and calculate all the % (gene level and cohort level top header) using this number as denominator?
Thanks,
Rajesh

**Comment by PoisonAlien** [comment]
HI,
These are rare cases, and dont know how often one would expect. But, I am happy to include and argument to provide a custom cohort size. I will let you know once its done.

**Comment by patidarr** [comment]
Thanks @PoisonAlien, will wait for the update.

**Comment by PoisonAlien** [comment]
Hi Rajesh,
Sorry for the delay. I have added `cohortSize` argument to `oncoplot` which should do the trick. Please let me know if this helps.

**Comment by patidarr** [comment]
Thank you!!
