### ISSUE TITLE
oncoplot removeNonMutated Error

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#325]
If `removeNonMutated` is changed from its default to FALSE and `genes` has a gene symbol with no mutations, the plot fails. I read the documentation and realised that the parameter only affects samples and not genes. I think it would be good if the user provides a gene symbol to oncoplot that it would not be dropped automatically. The user might want to highlight that the gene is not mutated in any sample (discover the gene in one cohort, be disappointed by the validation cohort). In the minimal example below, BRAF is not mutated and this seems to be a problem.

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
oncoplot(laml, genes = c("TP53", "BRAF", "BCOR"), removeNonMutated = FALSE)
```

results in `Error in dimnames(x) <- dn: length of dimnames [1] not equal to array extent`.

**Comment by PoisonAlien** [comment]
Its already there. You need to set `fill = TRUE` and it should do the trick. Let me know if this helps.

```r
oncoplot(laml, genes = c("TP53", "BRAF", "BCOR"), removeNonMutated = FALSE, fill = TRUE)
```

**Comment by DarioS** [comment]
It works. But, the example code which triggers the error is a valid use case (user wants to keep all samples in the plot but doesn't mind if the unchanged genes are dropped), so it is a bug nonetheless to end in error.

Perhaps the definition of `fill` should also be changed.

>  If TRUE draws genes and samples as blank grids even when they are not altered.

It only has an effect on genes, not on samples, so "and samples" ought to be deleted.

Finally, if I use `removeNonMutated = FALSE` and `fill = TRUE`, I get progress message "BRAF not found in MAF. Excluding it.." which is incorrect because BRAF is kept in the plot.
