### ISSUE TITLE
cat Messages

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#326]
From the developer of knitr, a [criticism of cat usage](https://yihui.name/knitr/demo/output/):

> Many people like to use `cat()` to write messages in R, and this is a very bad practice, because it is inconvenient to turn off such messages. When we really mean messages, we should use `message()`. These regular messages can be conveniently suppressed by `suppressMessages()` or captured by knitr. Some package authors did not seem to pay attention to this issue; when we load a package or use functions in a package, we may see fake messages that cannot be suppressed.

Could maftools please use `message` instead?

**Comment by PoisonAlien** [comment]
It used to be messages until earlier versions, but somehow I found `cat` to be more elegant, though I agree `message` has many benefits. I will shift to message gradually.

**Comment by ShixiangWang** [comment]
I have seen @PoisonAlien your `verbose` option setting in many functions, I think this can be also closed

**Comment by DarioS** [comment]
Regardless, the [Bioconductor Style Guide](https://bioconductor.org/developers/how-to/coding-style/) requests that developers use `message` and not `cat`.

> - `message()` communicates diagnostic messages (e.g., progress during lengthy computations) during code evaluation.
> - `cat()` or `print()` are used only when displaying an object to the user, e.g., in a `show` method.

**Comment by ShixiangWang** [comment]
@DarioS You are right at some point. However, @PoisonAlien has provided a solution `verbose` to bypass it. I think an option here is better than function `suppressMessages()` in many cases.

```r
# Current solution
read.maf(maf, verbose = FALSE)
# Follow the style
suppressMessages(read.maf(maf))
```

I agree that `message()` is a better option than `cat()`, I always use `message()` in my projects.  But I will take it as @PoisonAlien mentioned that he found `cat()` to be more elegant in implementation.
