### ISSUE TITLE
subsetMaf Causes Oncoplot to be Flipped and Repeated

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#328]
The samples appear on the y-axis instead of their usual axis and all of them have the same percentage and weird-looking sample barcodes. An example is

```r
library(maftools)
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
laml <- subsetMaf(laml, genes = c("TP53", "BRAF", "BCOR"), isTCGA = TRUE)
oncoplot(laml, genes = c("TP53", "BRAF"))
```

**Comment by PoisonAlien** [comment]
It has nothing to do with subsetMaf. Oncoplot won't work with single gene (>1 genes required for plotting). In your example TP53 is the only mutated gene. That being said, it works if you use `fill=TRUE`. I have made proper error messages for these cases. 

```r
oncoplot(laml, genes = c("TP53", "BRAF"), fill = TRUE)
```
