### ISSUE TITLE
Recommended way to subset with multiple queries?

### ISSUE THREAD

**Issue by genomics-kl** [PoisonAlien/maftools#329]
Hello  @PoisonAlien,

Do you have a recommended way to make multiple subsets on a MAF object? I have used `lapply` to call `subsetMaf` for unique `query` parameters but not sure how to combine those subsetted MAF objects back into one MAF object.

Perhaps you have another suggested approach? Basically, I have a list of specific variants that I want to extract based on Chromosome, vcf_pos and Variant_Type.

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
`lapply` or `for` loop, both should be fine for subsetting. However, there is no option for merging multiple MAF objects. I am happy push a function for that. I will let you know soon..

**Comment by genomics-kl** [comment]
Thanks for the prompt reply! I appreciate your adding this feature to this very useful package. In the meantime, I was able to work around this for my particular use case by chaining the unique query strings together with ` | `. Here's an example in case this turns up in anyone's searches: `"(Chromosome == 'chr7' & vcf_pos == '151859768' & Variant_Type == 'INS') | (Chromosome == 'chr7' & vcf_pos == '151962134' & Variant_Type == 'SNP')"`.

**Comment by PoisonAlien** [comment]
Hi,
I am glad that you figured it out. I have also pushed a function `merge_mafs` which takes a list of MAF objects and returns a single merged MAF. You can try it if you'd like. 
Thanks for reporting. I am closing the issue, please feel to re-open if you find any issues.
