### ISSUE TITLE
lollipopPlot error 

### ISSUE THREAD

**Issue by crazyhottommy** [PoisonAlien/maftools#33]
I just installed the latest `maftools`, and has an error

```
Error in `[.data.table`(prot.dat, , .N, .(Variant_Classification, conv,  : 
  column or expression 2 of 'by' or 'keyby' is type list. Do not quote column names. Usage: DT[,sum(colC),by=list(colA,month(colB))]
In addition: Warning message:
In lollipopPlot(maf = SCLC.maf, gene = "TP53", AACol = "HGVSp_Short",  :
  NAs introduced by coercion

```

I think it has to do with the data.table package. It was working before.

Thanks,
Tommy

**Comment by PoisonAlien** [comment]
Hi Tommy,
Yes. This is an issue with recent updates to [data.table](https://cran.r-project.org/web/packages/data.table/news.html). Just found out they bumped it to major 1.10.0 two days ago. I will fix it by evening. 
Thanks for reporting.

**Comment by PoisonAlien** [comment]
Do you still have this issue ? I am not able to reproduce this issue with updated data.table.

**Comment by PoisonAlien** [comment]
I found the cause and I have fixed it. Can you try and let me know ?

**Comment by crazyhottommy** [comment]
Thanks! it is now woking great!
thanks for your great user support.

Tommy

**Comment by crazyhottommy** [comment]
by the way, now it is ignoring the intron mutations and mutations in splice regions. It will be good to show it in the plot as well. 

Thanks!
Tommy

**Comment by PoisonAlien** [comment]
By Intronic mutations you mean synonymous ones ? Whole idea of lollipop plot is to show distribution of variations in a across the cohort. Any hotspots would show up as taller stick, making it clear. This information is lost if its drawn per sample.

**Comment by crazyhottommy** [comment]
I got it. sometimes I just want to show all mutations in a gene in a sample-wise manner just for visualization.

**Comment by PoisonAlien** [comment]
Oh, for now only way to do so is subset your maf per sample and draw the plot.
