### ISSUE TITLE
Sample ordering and scale in `plotTiTv`

### ISSUE THREAD

**Issue by t-neumann** [PoisonAlien/maftools#330]
Is there any rational of how the samples are ordered in the `plotTiTv` function? And can this be selected manually?

Also, what are the bars scaled to? Looks like 100%, but some bars (I have both SNVs and Indels in my dataset) do not get to 100%.

**Comment by PoisonAlien** [comment]
Hi,
They are ordered by sample names, except that there is no specific order. I can push an argument for manual sample ordering if it helps.

Yes, they should add up to 100% and only those variants which are annotated as "SNP" in Variant_Type column are used for TiTv estimation. Its hard to guess why this number won't add up to 100 in your case. Maybe some INDELS are wrongly annotated as SNPs perhaps?

**Comment by t-neumann** [comment]
That would be very helpful for keeping a consistent ordering across plots.

Hm so that is how the object from the `titv` function looks like:

```
> ABC.titv
$fraction.contribution
    Tumor_Sample_Barcode       C>A       C>G      C>T       T>C       T>A      T>G
 1:                ABC_1  9.794752  8.287867 36.86672 26.396467  7.300598 7.014809
 2:               ABC_10  2.306452  1.016131 86.96364  3.653502  4.049291 1.607058
 3:               ABC_11  8.757885  8.248423 41.09656 25.084910  6.865599 6.380398
 4:               ABC_13 11.440881  9.430349 34.27477 25.849689  8.042125 6.629966
 5:               ABC_14 14.011246  8.809747 35.59044 23.383318  8.013121 5.623243
 6:               ABC_15 10.164488  8.899199 34.56348 23.935049  7.148882 7.486293
    Tumor_Sample_Barcode       C>A       C>G      C>T       T>C       T>A      T>G

$raw.counts
    Tumor_Sample_Barcode  C>A  C>G    C>T   T>C   T>A  T>G
 1:                ABC_1  377  319   1419  1016   281  270
 2:               ABC_10 8782 3869 331121 13911 15418 6119
 3:               ABC_11  361  340   1694  1034   283  263
 4:               ABC_13  478  394   1432  1080   336  277
 5:               ABC_14  598  376   1519   998   342  240
 6:               ABC_15  482  422   1639  1135   339  355
    Tumor_Sample_Barcode  C>A  C>G    C>T   T>C   T>A  T>G


$TiTv.fractions
   Tumor_Sample_Barcode       Ti        Tv
1                 ABC_1 63.26319 32.398025
2                ABC_10 90.61714  8.978931
3                ABC_11 66.18147 30.252305
4                ABC_13 60.12446 35.543322
5                ABC_14 58.97376 36.457357
6                ABC_15 58.49852 33.698861

```

Don't really see anything off there.

**Comment by PoisonAlien** [comment]
Row sums should be 100 for every sample. 

```r
rowSums(ABC.titv$fraction.contribution[,2:7])
```

In your case this seems to be slightly off :|

**Comment by t-neumann** [comment]
Exactly that is also what I noticed. Any idea where this could come from?

**Comment by PoisonAlien** [comment]
I can't think of any, I will go through the function again to double check. Any chance you could share a reproducible example? Maybe for one of those sample which is showing this discrepancy? Its fine if you're not comfortable with sharing, I will figure out soon.

**Comment by t-neumann** [comment]
Sorry that would be breaking confidentiality agreements. Are you calculating `$fraction.contribution` from `$raw.counts`? If not, then maybe this is where the discrepancy is coming from?

**Comment by PoisonAlien** [comment]
No problem, I understand. Yes, fractions are estimated from counts data. How much discrepancy do you observe? Is it more than 0.05% (rowsums)?

**Comment by t-neumann** [comment]
Definitely

![image](https://user-images.githubusercontent.com/17272623/58426859-152d7700-809e-11e9-9f33-d875f6e796af.png)

**Comment by PoisonAlien** [comment]
Okay this is a lot! One reason might be there might be missing or non-standard values  in `Reference_Allele` and `Tumor_Seq_Allele2` columns. I will update the function to check for these and let you know if it helps to track the issue.

**Comment by PoisonAlien** [comment]
Hi,
I have included an argument `sampleOrder` which should help in ordering the barplot. Also now the titv function checks and warns if there are any non-standard Ti/Tv conversions are there. Please let me know if this helps.

**Comment by t-neumann** [comment]
Cool it looks like it works. Can you also tell me what the warning message exactly means?

```
Warning message:
In titv(maf = MCC, plot = FALSE, useSyn = TRUE) :
  Non standard Ti/Tv class: 42769TRUE
```

Am I missing out on some mutations now here that would skew the Ti/Tv distribution?

**Comment by PoisonAlien** [comment]
There are 12 possible types of SNPs, which can be classified into 6 classes [2 Transitions and 4 Transverions](https://www.mun.ca/biology/scarr/Transitions_vs_Transversions.html) Your data seems to have something other than the below mentioned 12 events (only for point mutations). 

```r
"A>C" "A>G" "A>T" "C>A" "C>G" "C>T" "G>A" "G>C" "G>T" "T>A" "T>C" "T>G"
```

I think you should double check it since it seems to be quite a lot.

**Comment by t-neumann** [comment]
Looks like this was all INDELs:

```
> mafDat$con[!mafDat$con %in% names(conv)]
  [1] "CA>-"                                       "C>-"                                       
  [3] "A>-"                                        "T>-"                                       
  [5] "C>-"                                        "CAAGGAGGAGT>-"                             
  [7] "C>-"                                        "TGTCCT>-"                                  
  [9] "A>-"                                        "CAA>-"                                     
 [11] "ACCCAGCTGTT>-"                              "->GCGCACACACCCATCT"                        
 [13] "A>-"                                        "A>-"                                       
 [15] "AACCAGTCGATCCAACTGTAAAA>-"                  "G>-"                                       
 [17] "C>-"                                        "A>-"                                       
 [19] "GCCCGCC>-"                                  "->CCGCCACCGCCA"                            
 [21] "->G"                                        "->ACC"                                     
 [23] "AG>-"                                       "->TG"                           
```

Should the not be recognized and filtered before going into the SNP analysis?

**Comment by PoisonAlien** [comment]
I think these variants are somehow wrongly annotated as `SNP` in variant_type column. You can double check it. How did you generate this file?

**Comment by t-neumann** [comment]
Hm I use annovar - that would be the corresponding line for one of the variants from the annovar.txt file:

```
grep CAAGGAGGAGT *txt

ABC_10.hg38_multianno.txt:chr12	4580831	4580841	CAAGGAGGAGT    	-      	exonic 	DYRK4  	.      	frameshift deletion    	DYRK4:ENST00000537719.5:exon3:c.140_150del:p.R48Afs*12,DYRK4:ENST00000539701.5:exon4:c.167_177del:p.R57Afs*12      	12p13.32       	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	. 	..      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	. 	..      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	. 	..      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	. 	..      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	.      	. 	..      	.      	.      	.      	.      	.      	.      	.      	.      	.      	Name=nsv1040098,nsv832318,dgv88n21,nsv483060,nsv557123 	0.25   	24.2572	.      	chr12  	4580830	.      	ACAAGGAGGAGT   	A 	24.2572 	PASS   	.      	GT:DP4:CD4:refMQ:altMQ:refBQ:altBQ:refNM:altNM:fetSB:fetCD:zMQ:zBQ:MQ0:VAF     	0/0:10,20,0,0:30,0,0,0:60:.:38.3333:.:1.5:.:1:1:.:.:0:0	0/1:40,32,19,23:72,0,42,0:60:60:38.5694:39.5714:1.04167:13.4286:0.33:1:0:1.55667:0 	0.368
```

Don't really see a misannotation in the raw file.

**Comment by PoisonAlien** [comment]
Thats clearly an INDEL. It shouldn't be annotated as SNP in MAF. 
Did you use `annovarToMaf` for converting to maf?

**Comment by t-neumann** [comment]
Yes exactly:

```
ABC <-annovarToMaf(paste0(root,list.files(root,pattern="hg38_multianno.txt")),
                   refBuild="hg38",MAFobj=FALSE,Center="IMP")
```

**Comment by PoisonAlien** [comment]
Okay got it! 
It was indeed a bug in the `annovarToMaf` function. Sorry for the trouble, could you try it again and let me know if this helps?

**Comment by t-neumann** [comment]
Yes now it looks like no more parsing errors pop up. Thx!
