### ISSUE TITLE
Identified clusters with inferHeterogeneity

### ISSUE THREAD

**Issue by jgarces02** [PoisonAlien/maftools#331]
Hi @PoisonAlien, 

I've got a question (maybe a bit obvious, but I cannot understand it), if you please. With the function `inferHeterogeneity` some clusters are calculated with user-indicated or with all _Tumor_Sample_Barcode_ unique values... my question is if all clusters determined in each one _Tumor_Sample_Barcode_ are independent or the red one in one sample corresponds to the other red cluster in the other samples and so on... 

![image](https://user-images.githubusercontent.com/27858969/58429016-b1f31300-80a4-11e9-8069-fb43f36f83e5.png)

![image](https://user-images.githubusercontent.com/27858969/58429034-cafbc400-80a4-11e9-9ec1-02f33fec95b3.png)

Thanks for your help!

**Comment by PoisonAlien** [comment]
Hi,
They are sample specific and are completely independent between samples.  Hope this helps.

**Comment by jgarces02** [comment]
Ok, I understand... and is there any way to make these clusters in a sample-related manner? Thanks

**Comment by PoisonAlien** [comment]
No. Heterogeneity is sample specific and hard to associate between samples. I am not sure if there are any methods which associate clones between samples.

**Comment by jgarces02** [comment]
That's a pitty! I'd be absolute perfect then... but thanks a lot anyway!
