### ISSUE TITLE
removeNonMutated function

### ISSUE THREAD

**Issue by simonlee184** [PoisonAlien/maftools#334]
Hi Anand,
    When I try the removeNonMutated argument with the oncoplot, I keep getting the following error: 
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

Would you happen to know if anyone else has had this issue previously? the argument seems self explanatory, but I'm not sure where it might have went wrong.

**Comment by PoisonAlien** [comment]
Hi Simon,
It appears similar to #325 
Maybe take a look at it, and if it doesn't help I can track it down. In short, you might want to run it with `fill = TRUE` to avoid error due to non-mutated genes. Let me know if it helps.

**Comment by simonlee184** [comment]
Awesome, it works! Thank you very much for looking up the previous issue. Everyone is really excited about maftools and how easy it is to customize.
