### ISSUE TITLE
Gistic visualization for LUAD and LUSC

### ISSUE THREAD

**Issue by Akyanus** [PoisonAlien/maftools#336]
Hi,

I want to obtain gistic result for LUAD and LUSC cancer type and I want to use your package. But I don't have an idea about gistic file. 

I obtained tcga maf file and some plots with your codes, but I could'n work with GISTIC file. Your codes for laml. What about other cancer types? Can you help for this? How can I obtain gistic file for LUAD or LUSC?
Thank you

**Comment by PoisonAlien** [comment]
Hello,
I would suggest you to check out [tcga firehose](https://gdac.broadinstitute.org). It includes results for all TCGA cohorts including GISTIC results. I would also recommend you to read a bit more on [GISTIC documentation](ftp://ftp.broadinstitute.org/pub/GISTIC2.0/GISTICDocumentation_standalone.htm). 

Hope this helps.
