### ISSUE TITLE
plotEnrichmentResults can not be plotted into multiple figure panels

### ISSUE THREAD

**Issue by ShixiangWang** [PoisonAlien/maftools#337]
Dear @PoisonAlien,

It failed when I want to include multiple plots from `plotEnrichmentResults` into one figure by `par(mfrow = c(3, 2))` or `layout()` function.

I read your code, but I cannot figure out why it does not work but simple `barplot()` works.

An example is given as the following: 

```
> laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
> laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')
> laml = read.maf(maf = laml.maf, clinicalData = laml.clin)
-Reading
-Validating
-Silent variants: 475 
-Summarizing
-Processing clinical data
-Finished in 0.201s elapsed (0.711s cpu) 
> en = clinicalEnrichment(laml, 'FAB_classification')
Sample size per factor in FAB_classification:

M0 M1 M2 M3 M4 M5 M6 M7 
19 44 44 21 39 19  3  3 
> plotEnrichmentResults(en)
> layout(matrix(1:6, byrow=TRUE, ncol=2))
> plotEnrichmentResults(en)
> plotEnrichmentResults(en)
> plotEnrichmentResults(en)
> layout(matrix(1:6, byrow=TRUE, ncol=2))
> barplot(1:10)
> barplot(1:10)
> barplot(1:10)
> barplot(1:10)
> barplot(1:10)
> barplot(1:10)
```

![image](https://user-images.githubusercontent.com/25057508/59179085-85a2c080-8b93-11e9-9525-df9e71a393be.png)

![image](https://user-images.githubusercontent.com/25057508/59179091-8c313800-8b93-11e9-89a9-6c199def9216.png)

Best,
Shixiang

**Comment by PoisonAlien** [comment]
That function uses [`add_legend`](https://github.com/PoisonAlien/maftools/blob/96a70f71147ace00748caaf612c3d06c0fc47a7a/R/plotClinicalEnrichment.R#L63) for plotting legends outside the margin which in-turn messes up the layout. If you think this is not an ideal then I am happy to revert it back to the default `legend`.

**Comment by ShixiangWang** [comment]
@PoisonAlien May you add an option to handle this instead of revert it back?

**Comment by PoisonAlien** [comment]
Its fine actually. I used it only because base `legend` is quite tedious to position on the plot. I will fix it..

**Comment by ShixiangWang** [comment]
@PoisonAlien Thanks :)

**Comment by PoisonAlien** [comment]
I have fixed it.

**Comment by ShixiangWang** [comment]
Thanks.
