### ISSUE TITLE
plotmafsummary percentage order

### ISSUE THREAD

**Issue by ahwanpandey** [PoisonAlien/maftools#339]
Hello,

I just noticed that the percentages do not match the height of the barplot, I thought that the percentages would be ordered highest to lowest?

![image](https://user-images.githubusercontent.com/8450532/59324928-4eafe480-8d24-11e9-8309-03b1ecb8992b.png)

Thanks.

**Comment by PoisonAlien** [comment]
Hello,

Yes that is the case. Bars are sorted based on total mutations. However labels represent % of samples mutated. In this case, `DNMT3A` has more mutations in less samples (54 variants from 48 samples) i.e, some of the samples have more than one mutation in `DNMT3A` (multihit). 

```r
> getGeneSummary(x = laml)[,.(Hugo_Symbol, total, MutatedSamples, AlteredSamples)]
       Hugo_Symbol total MutatedSamples AlteredSamples
   1:        FLT3    52             52             52
   2:      DNMT3A    54             48             48
   3:        NPM1    34             33             33
   4:        IDH2    20             20             20
   5:        IDH1    18             18             18
  ---                                                
1237:      ZNF689     1              1              1
1238:      ZNF75D     1              1              1
1239:      ZNF827     1              1              1
1240:       ZNF99     1              1              1
1241:        ZPBP     1              1              1
```

But I understand how it can be confusing. I will change fix the % to show `MutatedSamples`. 

Thanks for noticing.

**Comment by PoisonAlien** [comment]
Okay it seems the current option is the best way. Other way would be to order based on the % of samples mutated which would shift the bars. So I will let it be the way it is.

**Comment by gt7901b** [comment]
Hi, Is there a way to only show plot of top mutated genes?

**Comment by PoisonAlien** [comment]
Hi,

Yes. Try `maftools::mafbarplot()`.
