### ISSUE TITLE
Oncoplot allowing for SNV and Amp/Del in same cell

### ISSUE THREAD

**Issue by kpjonsson** [PoisonAlien/maftools#34]
Hi,

The ComplexHeatmap package allows for the simultaneous plotting of SNVs/indels _and_ amplification/deletion in a cell. Is this something you could incorporate in the oncoplot function?

See https://github.com/jokergoo/ComplexHeatmap/blob/fcaccd8ac595eb41c5cb48efeda119daf5e02fef/vignettes/s8.oncoprint.Rmd

**Comment by PoisonAlien** [comment]
Hi,
Its already there in oncoplot. An example from [vignette](http://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#including-copy-number-data-into-oncoplots.).

**Comment by kpjonsson** [comment]
But if the same sample has both a SNV/indel and deletion/amplification, only SNV/indel is shown.

**Comment by PoisonAlien** [comment]
Ahh ! Okay, got it! I will implement it soon. Thank you for suggestion.

**Comment by kpjonsson** [comment]
Thanks. Shouldn't be too hard, I think/hope.

**Comment by crazyhottommy** [comment]
when a gene has two SNVs in the same gene, one is missense and the other is in the splice site. oncoplot only choose one for plotting?

Thanks!

**Comment by kpjonsson** [comment]
Yeah, those situations are tricky. You can imagine a solution that draws to boxes within the cell, but it get messy once there's more than two mutations in the same sample and gene.

**Comment by PoisonAlien** [comment]
Genes with two hit (or more) are hard to represent. In that case it will be annotated as Multi_Hit. I have also put a Note about this in [vignette](http://www.bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#drawing-oncoplots.) But recent update to data.table (Ugh!) affected the way table is being cast, which is also why copynumbers are not getting plotted on top of variants. I have fixed all these, I will push a commit soon.

**Comment by kpjonsson** [comment]
Cool!

**Comment by PoisonAlien** [comment]
Hi,
I have fixed the issue. Can you install from GitHub let me know if it works for you ?

```{r}
devtools::install_github(repo = "PoisonAlien/maftools")
```

**Comment by kpjonsson** [comment]
Did some quick testing, and it seems to work, looks good.

You might want to consider switching the graphical representation. In my opinion it looks better when the copy-number alteration fills the whole cell and SNVs/indels part of the cell. 
Example from cBioPortal: 
![image](https://cloud.githubusercontent.com/assets/4834443/21143033/01959198-c113-11e6-9db6-ad9a46b1de8b.png)

**Comment by PoisonAlien** [comment]
Since the tool was focused on MAF file, it made sense to fill cells with mutations. 
But yes, cbioportal one looks good too. Maybe in next update I will include an argument to fill cells with cnv/mutations. I should also change CNV into deep and shallow events as in cBioportal. 
For now I will close this issue.
Thanks.

**Comment by kpjonsson** [comment]
Thanks for doing this!

I've made some not-very-pretty changes to to the `oncoplot` function to work according to my wishes. In case you're interested in having a look: https://gist.github.com/kpjonsson/86f82ad40e4ce08a76d7c3a7f7a4c01a

**Comment by PoisonAlien** [comment]
Hi, Thanks for sharing. If it improves upon original plot, I will port your changes.

**Comment by kpjonsson** [comment]
Sure, test it and let me know if you have any questions.
