### ISSUE TITLE
Height of top bar plot in oncoprint

### ISSUE THREAD

**Issue by ahwanpandey** [PoisonAlien/maftools#340]
Hello,

Is there any way to specifically adjust the height of the top barplot in the oncoprint. When I want to plot a lot of genes in the oncoprint, I have to make the height of the PDF large enough, but this makes the top barplot really large too. And there is also a lot of whitespace as well. the main oncoprint doesn't adjust too well I think,

![image](https://user-images.githubusercontent.com/8450532/59402865-99446600-8de3-11e9-8aec-3780cd23245b.png)

### The older versions had better adjustments I think.

![image](https://user-images.githubusercontent.com/8450532/59402908-c85ad780-8de3-11e9-983e-3bbc9120898d.png)

Thanks!

**Comment by PoisonAlien** [comment]
Hello,

I have included two arguments `sepwd_genes` and `sepwd_samples` which controls the width of the white grid lines. Decrease it to enhance the colours. 

Unfortunately, the top bar plot (and rest) sizes are fixed and can't be changed :|

**Comment by ahwanpandey** [comment]
No problem. Thanks for trying to help out!

**Comment by PoisonAlien** [comment]
Did `sepwd_genes` and `sepwd_samples` help?
