### ISSUE TITLE
trinucleotideMatrix function error with hg19

### ISSUE THREAD

**Issue by milgri** [PoisonAlien/maftools#341]
coad.maf = 'TCGA.COAD.muse.7d9db44b-21ee-46e2-8a43-ecf00c295b28.somatic.maf'
#  'CYT-High-or-low_COAD_READ/colonHigh.tsv'
coad = read.maf(maf = coad.maf)

coad
getSampleSummary(coad)
getGeneSummary(coad)
getFields(coad)
write.mafSummary(maf = coad, basename = 'coad_High')

library(BSgenome.Hsapiens.UCSC.hg19, quietly = TRUE)
coad.tnm = trinucleotideMatrix(maf = coad, ref_genome = "BSgenome.Hsapiens.UCSC.hg19")

all the code lines until the last one work well, the last one produces error:

> coad.tnm = trinucleotideMatrix(maf = coad, ref_genome = "BSgenome.Hsapiens.UCSC.hg19")
-Extracting 5' and 3' adjacent bases
Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 274: 'allow.nonnarrowing' is FALSE and the supplied start (82033820) is > refwidth + 1

**Comment by PoisonAlien** [comment]
Hello,
Are you sure your mac is from hg19? It appears you're using different build, probably hg38. Please double check and let me know.

**Comment by milgri** [comment]
Good morning,
it is possible I am using hg38 build. Is there a possibility to change it in data sets (since in RStudio I only see the option to use hg19)?
Thank you for your time and help.

**Comment by ShixiangWang** [comment]
@milgri  Just change `hg19` to `hg38` in code

```
library(BSgenome.Hsapiens.UCSC.hg38, quietly = TRUE)
coad.tnm = trinucleotideMatrix(maf = coad, ref_genome = "BSgenome.Hsapiens.UCSC.hg38")
```

**Comment by milgri** [comment]
The problem is that there is no package "BSgenome.Hsapiens.UCSC.hg38" that I could install: 
![image](https://user-images.githubusercontent.com/51790531/59658530-91ead700-91ac-11e9-939e-7e3f93da19d3.png) 
![image](https://user-images.githubusercontent.com/51790531/59658545-9dd69900-91ac-11e9-9f61-cd10d1a60e81.png)

**Comment by ShixiangWang** [comment]
@milgri You can install it with commands:

```
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
```

Then use it.

**Comment by milgri** [comment]
So it was quite a silly mistake, thank you very much for your help, everything works perfectly now.
