### ISSUE TITLE
Any plans to include the new DBS signatures from COSMIC?

### ISSUE THREAD

**Issue by ahwanpandey** [PoisonAlien/maftools#343]
Hello,

I was wondering if you had any plans to include the Double Base Substitution (DBS) Signatures from COSMIC?

https://cancer.sanger.ac.uk/cosmic/signatures/DBS

They also have updated their Single Base Substitution (SBS) Signatures.

https://cancer.sanger.ac.uk/cosmic/signatures/SBS/

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Thanks for pointing it out. I wasn't aware of DSB signatures. I will read more, but It seems doable. I will work on it.

**Comment by ahwanpandey** [comment]
Here's a library that can create all the required contexts for SBS, DBS and INDEL signatures. Maybe you can leverage it?

https://rdrr.io/github/steverozen/ICAMS/man/ICAMS.html

**Comment by PoisonAlien** [comment]
Since its not on CRAN or Bioconductor, importing it as a dependency or suggests would be difficult. I think this can be done easily with little tweak to `trinucleotideMatrix` function.

**Comment by ShixiangWang** [comment]
@PoisonAlien This package is available at CRAN <https://cran.r-project.org/web/packages/ICAMS/index.html>, however, no vignette can be found to understand the workflow although the basic idea is described at `ICAMS.rd`.  I read some code and find it may be hard to be compatible with maftools. I agree with you that modifying `trinucleotideMatrix` would be the best option.

**Comment by ahwanpandey** [comment]
I think the SBS and DBS signatures would be straighforward like you mention. The INDEL signatures might not be as straightforward. 

https://cancer.sanger.ac.uk/cosmic/signatures/ID

I have been able to use ICAMS on my VCFs to generate all the SBS, DBS and INDEL signatures. I thought it would be nice to have this functionality built into maftools itself as it is already a one stop solution to a lot of things you can do with mutation data.

In any case, the source code might help give you a head-start to implementing the INDEL signatures if you ever would like to implement it.

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the input. I do want to include it - its just due to my PhD work load I am not able to spend enough time on it. I will sure look into it. Hopefully I would be able to do it in next few weeks.

**Comment by PoisonAlien** [comment]
This may not be the way you wanted it, but they have been included in the known signature database. You can try `compareSignatures` with `sig_db  = 'SBS'`. 
Thanks for the input again. I am closing the issue for now, please feel free to reopen if necessary.
