### ISSUE TITLE
how to customize the names on the x-axis in plottitv 

### ISSUE THREAD

**Issue by SaraYones** [PoisonAlien/maftools#344]
I want to rename the values on the x-axis to be as "C:G>T:A', 'C:G>G:C', 'C:G>A:T', 'T:A>A:T', 'T:A>C:G','T:A>G:C" instead of the other representation (the 6 mutations) because it is misleading. Is there anyway to do that ?

**Comment by PoisonAlien** [comment]
Hello,
These are hard-coded labels. I am afraid you there is no way to rename them. May I ask why do you think labels are misleading? They're pretty [standard](https://www.mun.ca/biology/scarr/Transitions_vs_Transversions.html) representations in the context of Transitions/Transversions.

**Comment by SaraYones** [comment]
I have checked in multiple sources and other packages like this one "https://genviz.org/module-03-genvisr/0003/03/01/tvti_GenVisR/" they always have a label which makes it easier for the reader to follow. Also,  my supervisor thinks that we should include these labels. I will have to do it in photoshop or Inkscape in this case but i think it will be an enhancement to include a label for the transitions and transversions in this plot

**Comment by PoisonAlien** [comment]
Hmm.. Okay, I agree they are more readable. I will push the changes with modified labels and update you. 
Thanks!
