### ISSUE TITLE
lots of bright lines on the oncoplot

### ISSUE THREAD

**Issue by zhaoliang0302** [PoisonAlien/maftools#345]
I plot about 900 samples and the data is downloaded from TCGA, the color is not obvious whatever zoom in or out

![image](https://user-images.githubusercontent.com/42333702/59744134-7bc04200-92a4-11e9-9dba-8fc623cf3a18.png)
![image](https://user-images.githubusercontent.com/42333702/59744159-87ac0400-92a4-11e9-9f8d-8722f692a969.png)

**Comment by PoisonAlien** [comment]
Hi,
This issue is similar to #340 
Install the tool from GitHub and decrease the values for argument `sepwd_samples` in oncoplot and it should minimize the width of white border lines. Let me know if it helps.

**Comment by zhaoliang0302** [comment]
I can just install maftools_2.0.10.tar.gz from github, can't get the newest version 2.0.15.
`BiocManager::install("PoisonAlien/maftools")`

**Comment by PoisonAlien** [comment]
Its fine. Its still 2.0.10 on GitHub - Its just says 2.0.15 in the [NEWS](https://github.com/PoisonAlien/maftools/blob/master/inst/NEWS). Do you see any error while installing?

**Comment by zhaoliang0302** [comment]
> Its fine. Its still 2.0.10 on GitHub - Its just says 2.0.15 in the [NEWS](https://github.com/PoisonAlien/maftools/blob/master/inst/NEWS). Do you see any error while installing?

I tried sepwd_samples = 0 to 2, it still has gap between samples and color is light

**Comment by PoisonAlien** [comment]
Usually it works with smaller width. Also try saving your plot to pdf with larger width to get most of it. That being said,  with samples size as large as yours its hard to draw a heatmap distinguishing samples.

**Comment by zhaoliang0302** [comment]
The old version maftools performs well, I think it's a bug of new version(light gap becomes obvious when zoom in or out even pdf with larger width), can you fix it?
Thanks

**Comment by PoisonAlien** [comment]
Older version used draw the plots with ComplexHeatmap library but I moved all the plots to base graphics because of customization. Reverting back would take lots of code change and I dont have enough time to do that. Maybe I will do it gradually but for now it will remain the same. Sorry for the inconvenience :|

**Comment by zhaoliang0302** [comment]
I set the parameter `sepwd_samples = 0` and still has a white gap between samples. Maybe it's the gap caused unusual oncoplot, can you check it?

**Comment by PoisonAlien** [comment]
I checked on TCGA BRCA cohort with 1020 samples and seems ok to me.

```r
> TCGAmutations::tcga_load(study = "BRCA")
> png(filename = "~/Documents/temp/brca_default.png")
> oncoplot(maf = tcga_brca_mc3)
> dev.off()
```
Default oncoplot
![brca_default](https://user-images.githubusercontent.com/8164062/59768403-998da700-92a4-11e9-94b9-6b2689934692.png)

```r
> png(filename = "~/Documents/temp/brca_sep0.1.png")
> oncoplot(maf = tcga_brca_mc3, sepwd_samples = 0.1)
> dev.off()
```
with `sepwd_samples = 0.1`
![brca_sep0 1](https://user-images.githubusercontent.com/8164062/59768481-ba55fc80-92a4-11e9-9ba2-0b70957c4012.png)

similarly with `sepwd_samples = 0`

![brca_sep0](https://user-images.githubusercontent.com/8164062/59768531-d0fc5380-92a4-11e9-9d75-e8bd3f5e9d94.png)

**Comment by zhaoliang0302** [comment]
I tried mutect2 data from TCGAbiolinks, it still has white gap and won't change with the sepwd_samples parameter
> library(TCGAbiolinks)
> mut <- GDCquery_Maf(tumor = "LIHC", pipelines = "mutect2")
> library(maftools)
> maf <- read.maf(maf = mut)
> pdf("oncoplotTop20.pdf",width = 12,height = 6)
> oncoplot(maf = maf,
         top = 20,
         sepwd_samples = 0
         )
> dev.off()

**Comment by zhaoliang0302** [comment]
I also tried the same code you provided using TCGAmutations package and still can't get the same plot as you showed above. Can you provide your sessionInfo of R?
Much Thanks

**Comment by PoisonAlien** [comment]
Here is it. Check for maftools commit version under source and see if you have the same.

```r
> sessioninfo::package_info(pkgs = "maftools")
 package        * version  date       lib source                                
 assertthat       0.2.1    2019-03-21 [1] CRAN (R 3.6.0)                        
 BH               1.69.0-1 2019-01-07 [1] CRAN (R 3.6.0)                        
 bibtex           0.4.2    2017-06-30 [1] CRAN (R 3.6.0)                        
 cli              1.1.0    2019-03-19 [1] CRAN (R 3.6.0)                        
 cluster          2.0.9    2019-05-01 [1] CRAN (R 3.6.0)                        
 codetools        0.2-16   2018-12-24 [1] CRAN (R 3.6.0)                        
 colorspace       1.4-1    2019-03-18 [1] CRAN (R 3.6.0)                        
 cometExactTest   0.1.5    2018-01-29 [1] CRAN (R 3.6.0)                        
 crayon           1.3.4    2017-09-16 [1] CRAN (R 3.6.0)                        
 data.table       1.12.3   2019-06-15 [1] Github (Rdatatable/data.table@eea0a7b)
 digest           0.6.18   2018-10-10 [1] CRAN (R 3.6.0)                        
 doParallel       1.0.14   2018-09-24 [1] CRAN (R 3.6.0)                        
 dplyr            0.8.0.1  2019-02-15 [1] CRAN (R 3.6.0)                        
 fansi            0.4.0    2018-10-05 [1] CRAN (R 3.6.0)                        
 foreach          1.4.4    2017-12-12 [1] CRAN (R 3.6.0)                        
 ggplot2          3.1.1    2019-04-07 [1] CRAN (R 3.6.0)                        
 glue             1.3.1    2019-03-12 [1] CRAN (R 3.6.0)                        
 gridBase         0.4-7    2014-02-24 [1] CRAN (R 3.6.0)                        
 gtable           0.3.0    2019-03-25 [1] CRAN (R 3.6.0)                        
 iterators        1.0.10   2018-07-13 [1] CRAN (R 3.6.0)                        
 labeling         0.3      2014-08-23 [1] CRAN (R 3.6.0)                        
 lattice          0.20-38  2018-11-04 [1] CRAN (R 3.6.0)                        
 lazyeval         0.2.2    2019-03-15 [1] CRAN (R 3.6.0)                        
 maftools         2.0.10   2019-06-20 [1] Github (poisonalien/maftools@3d5f787) 
 magrittr         1.5      2014-11-22 [1] CRAN (R 3.6.0)                        
 MASS             7.3-51.4 2019-03-31 [1] CRAN (R 3.6.0)                        
 Matrix           1.2-17   2019-03-22 [1] CRAN (R 3.6.0)                        
 mgcv             1.8-28   2019-03-21 [1] CRAN (R 3.6.0)                        
 munsell          0.5.0    2018-06-12 [1] CRAN (R 3.6.0)                        
 nlme             3.1-139  2019-04-09 [1] CRAN (R 3.6.0)                        
 NMF              0.21.0   2018-03-06 [1] CRAN (R 3.6.0)                        
 pillar           1.3.1    2018-12-15 [1] CRAN (R 3.6.0)                        
 pkgconfig        2.0.2    2018-08-16 [1] CRAN (R 3.6.0)                        
 pkgmaker         0.27     2018-05-25 [1] CRAN (R 3.6.0)                        
 plogr            0.2.0    2018-03-25 [1] CRAN (R 3.6.0)                        
 plyr             1.8.4    2016-06-08 [1] CRAN (R 3.6.0)                        
 purrr            0.3.2    2019-03-15 [1] CRAN (R 3.6.0)                        
 R6               2.4.0    2019-02-14 [1] CRAN (R 3.6.0)                        
 RColorBrewer     1.1-2    2014-12-07 [1] CRAN (R 3.6.0)                        
 Rcpp             1.0.1    2019-03-17 [1] CRAN (R 3.6.0)                        
 registry         0.5-1    2019-03-05 [1] CRAN (R 3.6.0)                        
 reshape2         1.4.3    2017-12-11 [1] CRAN (R 3.6.0)                        
 rlang            0.3.4    2019-04-07 [1] CRAN (R 3.6.0)                        
 rngtools         1.3.1.1  2019-04-19 [1] CRAN (R 3.6.0)                        
 scales           1.0.0    2018-08-09 [1] CRAN (R 3.6.0)                        
 stringi          1.4.3    2019-03-12 [1] CRAN (R 3.6.0)                        
 stringr          1.4.0    2019-02-10 [1] CRAN (R 3.6.0)                        
 survival         2.44-1.1 2019-04-01 [1] CRAN (R 3.6.0)                        
 tibble           2.1.1    2019-03-16 [1] CRAN (R 3.6.0)                        
 tidyselect       0.2.5    2018-10-11 [1] CRAN (R 3.6.0)                        
 utf8             1.1.4    2018-05-24 [1] CRAN (R 3.6.0)                        
 viridisLite      0.3.0    2018-02-01 [1] CRAN (R 3.6.0)                        
 withr            2.1.2    2018-03-15 [1] CRAN (R 3.6.0)                        
 wordcloud        2.6      2018-08-24 [1] CRAN (R 3.6.0)                        
 xtable           1.8-4    2019-04-21 [1] CRAN (R 3.6.0)                        

```
