### ISSUE TITLE
Clipping of Sample Names in Oncoplot

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#346]
If `showTumorSampleBarcodes` is TRUE, the sample identifiers are often only partially visible. Even the example in the help page is truncated `oncoplot(maf = laml, top = 3, showTumorSampleBarcodes = TRUE)`. Could oncoplot be modified to automatically choose a more suitable height for the x-axis labels?

**Comment by PoisonAlien** [comment]
ggplot2 and lattice does this automatically, but I am not aware if there is a way to auto adjust it in base graphics. I will search for options..

**Comment by DarioS** [comment]
It happens to gene names, too.

![image](https://user-images.githubusercontent.com/631218/60068927-32fd0300-9754-11e9-818b-bf5f7f50310d.png)

**Comment by PoisonAlien** [comment]
Hi,
I have added `barcode_mar` and `gene_mar` argument to `oncoplot`. Increase these values to improve the margin width to accommodate longer texts. Can you test it and let me know if it helps?

**Comment by DarioS** [comment]
It is what I needed.

**Comment by tingchiafelix** [comment]
Hi,
Thanks for adding these margin funcitons. I'm wondering if you can also add margin function for annotation legend? I definitely can reduce the size of annotation font size, but the size looks so small.

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay. I have added `legend_height` argument to oncoplot. You can increase it to your wish and default value 4. Please try and let know of this helps. Thanks.
