### ISSUE TITLE
Bug in lollipopPlot2

### ISSUE THREAD

**Issue by fish0316** [PoisonAlien/maftools#350]
Please try the codes:

library(maftools)
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools') 
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') 
laml = read.maf(maf = laml.maf, clinicalData = laml.clin)
laml@gene.summary[18,]

lollipopPlot(maf = laml, gene = 'SMC1A', AACol = 'Protein_Change', showMutationRate = TRUE)

**There are 5 missense mutations and 1 splice sites.**

lollipopPlot2(m1 = laml, m2 = laml, AACol1 ='Protein_Change', AACol2='Protein_Change', 
              m1_name = "laml", m2_name = "laml",
              gene = "SMC1A")

**There are 3 missense mutations & 3 splice sites**
**The used datas are the same. There should be different result.**   

**I think the probelem is :
the two lines in lollipopPlot2**

col1 = col[unique(as.character(m1.lp[[1]][, Variant_Classification]))] 
col2 = col[unique(as.character(m2.lp[[1]][, Variant_Classification]))]

**should be**

col1 = col[(as.character(m1.lp[[1]][, Variant_Classification]))]
col2 = col[(as.character(m2.lp[[1]][, Variant_Classification]))]

**Comment by PoisonAlien** [comment]
Hello,
Could you post your session info? I believe you're using an older version. Could you also install the package from GitHub and see if you can reproduce this?

**Comment by fish0316** [comment]
Thank you for your reply.

Session info:
- Packages --------------------------------------------------------------------------------
 package              * version date       lib source           
maftools             * 1.8.10  2019-04-14 [1] Bioconductor 


After install the package from GitHub:
- Packages --------------------------------------------------------------------------------
 package              * version date       lib source  
 maftools       * 2.0.10  2019-06-27 [1] Github (PoisonAlien/maftools@d2c6598)


I can't reproduce this problem after install maftools from GitHub.
Thank you for your reply and suggestion .
