### ISSUE TITLE
Oncoplot with mutsigCV and genes

### ISSUE THREAD

**Issue by duttaind** [PoisonAlien/maftools#352]
Hello,

Thanks for making a very nice tool for variant annotation and visualization.

I am getting an error when I tried to create oncoplot with specific genes and mutsigCV result.
If I don't have genes then it creates oncoplot with mutsigCV p values. But if I ask for specific genes with genes as an argument then it shows this error: object 'ms.smg' not found.

Please let me know if genes with mutsigCV is possible or not. 
Thanks

**Comment by PoisonAlien** [comment]
Hello,
maftools picks the genes from MutSig results rather than depending on user inputs. Only way to change it would be to use `q` value threshold. 
If you really want to show q values for selected genes, then pass the mutsig results to `exprn` argument. You can find an example in the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/oncoplots.html#05_including_expression_(or_any)_values). 
Let me know if it helps.

**Comment by duttaind** [comment]
Thanks for your reply. It is working now  with exprn. But it is only showing couple of genes, i.e if I am trying to show 20 genes, out of those , 4 of the genes q values are not showing. I have checked gene symbols in exprn, they are there. So is there any cutoff  in expern argument. Please let me know,

**Comment by PoisonAlien** [comment]
If any q-values are zero it wont show up. If you did convert to `-log10` scale, zero q-vlaues would result in `Inf`. You will have to replace those zeros with smallest possible values supported by your system. You can refer [here](https://github.com/PoisonAlien/maftools/blob/master/R/oncoplot.R#L99-L100) to see how oncoplot does it.

**Comment by duttaind** [comment]
Thanks for your reply. I did check , q values are not 0 , for example for one of the gene which is not showing up is q=0.678936 and -log10=0.1681712 or for another gene not showing up (-log10(0.007548684). My genes list are not all <=0.05. Please suggest.

**Comment by duttaind** [comment]
is the expression plot depends on expressions of other genes in that set, in code I found it says"xlim = rev(-exprs_bar_lims), ylim = c(0, nrow(exprsTbl)). 

Please suggest if there is anything else I can check, as I am not able to move forward with Oncoplot as these genes are not showing up. Thanks.

**Comment by PoisonAlien** [comment]
Oh I am sorry, I totally overlooked the issue. Could you please post your entire commands?

**Comment by duttaind** [comment]
oncoplot(maf = neuro,exprsTbl = ms_res,bg="#FFFFFF",clinicalFeatures = 'type',sortByAnnotation = TRUE)

here maf is named as neuro with clinical feature. And ms_res had gene & q values ( -log10).

Thanks.

**Comment by PoisonAlien** [comment]
Hello, 
I am having hard time reproducing your issue.

```r
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')
laml = read.maf(maf = laml.maf, clinicalData = laml.clin, verbose = FALSE)

#Process mutsig results
laml.mutsig = system.file("extdata", "LAML_sig_genes.txt.gz", package = "maftools")
ms = read.delim(file = laml.mutsig, stringsAsFactors = FALSE)
ms = ms[,c("gene", "q")]
ms$q = -log10(ms$q)

set.seed(seed = 1024)
#Choosing random 10 of top 50 genes for plotting
random_genes = sample(x = head(ms$gene, 50), size = 10, replace = FALSE)
oncoplot(maf = laml, exprsTbl = ms, genes = random_genes)
```

Did you try using `genes` argument?

**Comment by duttaind** [comment]
Thanks. I was able to get it to work with genes argument.
