### ISSUE TITLE
lollipopPlot Line Height and Axis Range

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#354]
If two samples have the same mutation (e.g. p.G266R) then the line reaches 2. However, if there are two missense mutations resulting in different amino acids (e.g. p.R273C and p.R273H), maftools draws the line with height 1. I expect the line to reach 2 because both mutations are missense and in the same position. In my plot, the number of mutations at a position is either 1 or 2, but I can't make the y-axis range smaller than 1 to 5, which creates a lot of white space. Also, the documentation page of the function should mention the source of the domains (i.e. PFAM).

**Comment by PoisonAlien** [comment]
Hello,
I dont think thats the case. There are two points, but they are repelled hence it appears as one. You could test it with `collapsePosLabel = FALSE, printCount = TRUE, labelPos = 273`. 

Default scale for line height `5` which is done similar to protein mapper on cBioPortal.

**Comment by DarioS** [comment]
You are correct. They are being plotted in the same place but are both there. Could it possible to treat both mutations as the same and get a bar of height 2 because they are both missense mutations or is it a bad idea? Sometimes, repelling puts something in a PFAM domain outside of the domain so I wish not to use it.

**Comment by PoisonAlien** [comment]
Usual practice is to separate them since the type of conversion has it own effect even though they occur at same position. In LAML, `DNMT3A` hotspot R882 has two variants - `R882C` and `R882H` - and both differ in their mode of action.

**Comment by DarioS** [comment]
That's a good reason for them to remain separate.
