### ISSUE TITLE
Any way to include variation like gene fusion in oncoplot?

### ISSUE THREAD

**Issue by ShixiangWang** [PoisonAlien/maftools#355]
Hello @PoisonAlien,

Currently, I don't know if there is a way to include gene fusion into oncoplot.

Best,
Shixiang

**Comment by PoisonAlien** [comment]
You can add `Fusion` as one of the entry in `Variant_Classification`. And while readin maf use `vc_nonSyn` argument to consider `Fusion` as one of the non-syn VC. While plotting you will have to [define](https://bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/oncoplots.html#02_changing_colors_for_variant_classifications) a color code for `Fusion` events.

**Comment by ShixiangWang** [comment]
It sounds good. Thanks.
