### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by sallytxl** [PoisonAlien/maftools#356]
Hi I am trying to install maftools, but continuing to get the error message as below.
BiocManager::install('maftools')

"installation path not writeable, unable to update packages: cluster, nlme"

I updated these two packages, but still not working.

I am using R 3.6.0.

Thanks!

**Comment by ShixiangWang** [comment]
This is not a problem of maftools. You have no write permission to R package directory. You have to change the permission mode or set a personal R library directory.

**Comment by PoisonAlien** [comment]
Hello @sallytxl ,
This is something has to be fixed from your end since it relates to permissions. I am closing this issue.

**Comment by sallytxl** [comment]
Thank you. I will look into it.

Best,
Sally
