### ISSUE TITLE
oncoplot - transpose matrix

### ISSUE THREAD

**Issue by for8ver3** [PoisonAlien/maftools#357]
Hi, thanks for this wonderful tool package. 
My question, is there a way to transpose the matrix such that the individual genes are listed as columns and samples as rows? 

Thanks in advance!

**Comment by ShixiangWang** [comment]
I think the easiest way is to transpose the whole generated figure. :)

**Comment by PoisonAlien** [comment]
Hi @for8ver3 ,
No its not possible to transpose the matrix with current implementation. Easiest way would be as @ShixiangWang suggested, generate a simple oncoplot without rowbar or colbar and rotate it in Illustrator (or in any other image manipulating tool)
