### ISSUE TITLE
oncoplot: column bar does not align with heatmap when setting drawRowBar=F

### ISSUE THREAD

**Issue by jyu2012** [PoisonAlien/maftools#360]
please see the attached figure. Thanks!

test code: 
>oncoplot(maf=laml,showTumorSampleBarcodes=T,barcode_mar=10,drawRowBar=F)

![image](https://user-images.githubusercontent.com/8505264/60913813-0c06fc80-a23d-11e9-8cf3-b6db942a5d6c.png)

**Comment by jyu2012** [comment]
i changed one line code in oncoplot.R for ploting the main matrix (set right marigin from 3 to 5)  and it seems work. not sure if it was patched completely.

  if(showTumorSampleBarcodes){
    if(!drawRowBar & !drawColBar){
      par(mar = c(barcode_mar, gene_mar, 2.5, 5), xpd = TRUE)
    }else if(!drawRowBar & drawColBar){
      par(mar = c(barcode_mar, gene_mar, 0, **### 5**), xpd = TRUE)

**Comment by PoisonAlien** [comment]
Nice catch! I can reproduce this error. I will fix it soon, thank you for reporting.

**Comment by PoisonAlien** [comment]
Hello,
Thanks again. I have fixed it. Could you please try and let me know if this helps.
