### ISSUE TITLE
feature request [oncoplot]: customize height/width of column bars/row bars.

### ISSUE THREAD

**Issue by jyu2012** [PoisonAlien/maftools#361]
would it be possible to add parameters in oncoplot such that users can reduce/increase space of column bars and row bars?

It's great to see we can customize barcode and gene margins now.

thanks!

**Comment by PoisonAlien** [comment]
Hello, 
You could try `sepwd_genes`, `sepwd_samples` arguments. These options are only available in GitHub version. Let me know if this helps.

**Comment by jyu2012** [comment]
thanks! the sepwd_genes and sepwd_samples only affected the main heatmap/matrix. What I meant was the top frequency bars and row bars at the right panel. would it be possible to have similar margin parameters as barcode_mar/gene_mar to adjust their space? for example, what if I like to reduce the size of top frequency bar and right-panel frequency bar so that I could have more room for the main matrix/heatmap? sorry for the confusion if i didn't explain clearly.

Thanks!

**Comment by PoisonAlien** [comment]
Ah, I see what you mean. Unfortunately its not possible for now. 
But, I can push some changes for this. I will update you when its done.
