### ISSUE TITLE
Allowed variant classification

### ISSUE THREAD

**Issue by duttaind** [PoisonAlien/maftools#362]
Hello,

Thanks for this great analysis R package. I am working with it and in my data some of the variants are synonymous or frame shift mutations, so I read these in with readmaf, maftools couldn't recognize them. It says:
Non MAF specific values in Variant_Classification column

Can you please direct me what are the allowed values for variant classification column. In addition while calculating top mutated genes, does maftools account for silent variants such as synonymous.

Thanks.

**Comment by ShixiangWang** [comment]
There is an option `vc_nonSyn` in `read.maf()` function  you can set your own classfication.

```
Provide manual list of variant classifications to be considered as non-synonymous. Rest will be 
considered as silent variants. Default uses Variant Classifications with High/Moderate variant 
consequences. http://asia.ensembl.org/Help/Glossary?id=535: "Frame_Shift_Del", "Frame_Shift_Ins", 
"Splice_Site", "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", 
"In_Frame_Del","In_Frame_Ins", "Missense_Mutation"
```

More detail run `?read.maf` in R console.

**Comment by duttaind** [comment]
Thanks Shixiang for the response. I was able to read in other variants but they are not showing up in color legend. I mean there is no color designation. How can I set that up. I read ?read.maf but I didn't saw an option.

Please let me know.

**Comment by PoisonAlien** [comment]
You will have to define color codes for `Variant_Classifications`
By default standard entries will be color coded. Others will have to specified manually. See [here](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/oncoplots.html#02_changing_colors_for_variant_classifications) for details on how to do it.

**Comment by duttaind** [comment]
Thank you.
