### ISSUE TITLE
Error in Oncoplot with only 1 variant classification

### ISSUE THREAD

**Issue by shrivatsk** [PoisonAlien/maftools#367]
I attempted to run the Oncoplot function on some MAF-formatted data. However, I kept receiving the error: 
`Error in samp_sum[colnames(numMat), , ] : incorrect number of dimensions`

After some debugging it looked like this issue came up only when the Variant_Classification column had a single type of variant. In my case, all of the variants that were trying to be plotted were missense variants. It appeared that this came about when the column names of the oncomatrix were being retrieved - having only one variant type may have caused R to create a vector instead of a data frame which might have led to this issue.

Could you please confirm the nature of the error or suggest a fix?

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
I am sorry for the late reply. Would it be possible to provide a reproducible example?

**Comment by PoisonAlien** [comment]
Hi,
Thanks for reporting. I was able to reproduce it and indeed it was a bug. I have fixed it - could you please try it on your dataset and let me know? You will have to install from GitHub..

**Comment by shrivatsk** [comment]
Awesome, it works correctly now.

Thanks Anand!
