### ISSUE TITLE
library(NMF) failed

### ISSUE THREAD

**Issue by rescuz** [PoisonAlien/maftools#368]
When i load NMF package,it failed,the information is :
Error: package or namespace load failed for ‘NMF’:
 .onAttach failed in attachNamespace() for 'NMF', details:
  call: if (n > 2) n <- n - 1L
  error: missing value where TRUE/FALSE needed
 Could you give me some advice,many thanks!

**Comment by PoisonAlien** [comment]
Hi,
This is unrelated to maftools. It appears that your `NMF` installation has issues. Maybe you will have to try re-installing it.
