### ISSUE TITLE
extractSignatures bug appeared

### ISSUE THREAD

**Issue by t-neumann** [PoisonAlien/maftools#369]
Hi @PoisonAlien 

I have pulled a recent bugfix from GitHub and now tried to rerun (unrelated) the `extractSignatures` function on data I never touched.

Now this throws an error - I suspect it might be related to some code change?

```
> dummy.sign = extractSignatures(mat = dummy.tnm, nTry = 6, plotBestFitRes = FALSE)
-Estimating optimal factorization rank
Error in .prepareFastSubset(isub = isub, x = x, enclos = parent.frame(),  : 
  RHS of == is length 0 which is not 1 or nrow (5). For robustness, no recycling is allowed (other than of length 1 RHS). Consider %in% instead.
```

Does this tell you anything?

**Comment by PoisonAlien** [comment]
Yes, It's coming from `data.table`. I recently updated the way optimal number of signatures is chosen. However I never encountered this. I will check if I can reproduce it..

**Comment by PoisonAlien** [comment]
Hi,
I am not able to reproduce the issue. Could you please post your `data.table` version?

**Comment by PoisonAlien** [comment]
Okay, found the bug and fixed it. Please try it again and let me know if it works. Cubic spline function used for rank estimation started complaining for lower number of signatures, and I had to revert it back to the original method. Thanks for reporting.

**Comment by t-neumann** [comment]
Works again - thanks a lot!

**Comment by duttaind** [comment]
I am having the error again, which version of maftools I should use. Currently I am using v2.0.15.
Thanks.

**Comment by t-neumann** [comment]
@duttaind I think you just need to pull the newest from Github via the `devtools` package - that worked for me.
