### ISSUE TITLE
oncoplot for Variant_Classification of UNKNOWN

### ISSUE THREAD

**Issue by crazyhottommy** [PoisonAlien/maftools#37]
Hi,

For my maf file, some variants are classified as UNKNOWN by annovar. on the oncoplot, it does not have any color showing it. 

Thanks,
Ming

**Comment by PoisonAlien** [comment]
Hi Ming,

By default oncoplot colors variant classifications according to MAF specififcations. UNKNOWN is not one of the standard variant classifications. You will have to manually specify color codes for them. Here are the default ones.

```r
c('Nonstop_Mutation','Frame_Shift_Del','IGR','Missense_Mutation','Silent','Nonsense_Mutation',                           'RNA','Splice_Site','Intron','Frame_Shift_Ins','Nonstop_Mutation','In_Frame_Del','ITD','In_Frame_Ins',
                           'Translation_Start_Site',"Multi_Hit", 'Amp', 'Del')
```

**Comment by crazyhottommy** [comment]
Thanks! I guess I need to customize the plot by complexHeatmap. how to get the matrix for plotting oncoplot? If I specify `writeMatrix =T`, where can I get the matrix?

**Comment by PoisonAlien** [comment]
It should be in your working directory under the name onco_matrix.txt

**Comment by crazyhottommy** [comment]
Thanks, I found it. may be good to clarify in the documentation.
