### ISSUE TITLE
co-occurrence is misspelled in the mutual exclusion and co-occurrence plot also the order of the display of genes should be based upon user based criteria (not only p-values)

### ISSUE THREAD

**Issue by SaraYones** [PoisonAlien/maftools#373]
Hello,

co-occurrence is written as "co-occurrence" in the plot also if I want to compare two ME plots I want the order of genes in the two plots to be the same but the order is dependant on p values so can you modify it  for example (specify a flag as an argument for the function for ordering based on p-values for example or based on the same order of the genes list that was given to function as a parameter?

**Comment by SaraYones** [comment]
It is misspelled written as "co occurance" in the plot

**Comment by PoisonAlien** [comment]
Hello,
Thanks for pointing out the typo. I have corrected it. Also, there is an argument `geneOrder` in the function which you can use to manually order the genes in plot. Please try it out and let me know if it helps.
