### ISSUE TITLE
failed to load the gistic files

### ISSUE THREAD

**Issue by anyone1985** [PoisonAlien/maftools#375]
Hi, 

I've some problem when I read the gistic files. The following is the error information. Please help me. Thanks.

> bcg.gistic <- readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gis)
-Processing Gistic files..
--Processing amp_genes.conf_90.txt
--Processing del_genes.conf_90.txt
--Processing scores.gistic
--Summarizing by samples
Error in `levels<-`(`*tmp*`, value = as.character(levels)) :
  factor level [3] is duplicated

**Comment by PoisonAlien** [comment]
Would it be possible to provide a reproducible example?

**Comment by anyone1985** [comment]
Thank you for your reply. I find there is a mismatch of sample names between gistic and maf files. I have build the maf object successfully.
