### ISSUE TITLE
Copy-number values per gene 

### ISSUE THREAD

**Issue by JulyJly** [PoisonAlien/maftools#379]
Hi, regarding copy number data in a matrix format, with rows are genes and columns are samples (this is Gene Level Copy Number Scores provided in TCGA and CCLE), how can I include the copy number data into maftools? Do I have to first transform the matrix into a 3-column matrix for the cnTable? Thanks!

**Comment by DarioS** [comment]
If you're downloading the TCGA copy number from Genomic Data Commons, you're in for a challenge. The column headings aren't patient barcodes, but aliquot barcodes. The Bioconductor package TCGAutils recently got support for aliquot ID to patient ID conversion, though. You need at least version 1.5.5 of the package. Use `UUIDtoBarcode` function.

**Comment by PoisonAlien** [comment]
Hi @JulyJly ,
Sorry for late reply. Were you able to figure it out? Copy number data should be a 3 column `data.frame` or `data.table`. See [here](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/oncoplots.html#03_including_copy_number_data_into_oncoplots) for details.
