### ISSUE TITLE
oncoplot writes on existing plot

### ISSUE THREAD

**Issue by krcoombes** [PoisonAlien/maftools#38]
Using maftools version 1.0.40.

When I call oncoplot, it does not clear an existing plot window, but instead draws in to of the existing material. I suspect that the problem arises in the use of ComplexHeatmap some where, but haven't been able to track down exactly where.

**Comment by PoisonAlien** [comment]
Hi,
Yes its due to how ComplexHeatmap draws it using grids. I will add `dev.new` to the function to make it draw in new window. For now you will have to clear it manually.
