### ISSUE TITLE
502 Proxy Error

### ISSUE THREAD

**Issue by WRui** [PoisonAlien/maftools#381]
hi, when I running 'oncotate' to annotate the mutations, it returns error "cannot open URL 'http://portals.broadinstitute.org/oncotator/mutation/1_6648307_6648307_C_A': HTTP status was '502 Proxy Error'". Could you please help me to fix it?

**Comment by xiw588** [comment]
Hi Wrui, 

Have you fixed the problem? I have the same problem when running the function oncotate and nobody replied. Please let me know if you have any ideas. 
Thank you

**Comment by PoisonAlien** [comment]
Hi Both,
Please accept my apologies for the late reply. Thing is Broads [oncotator](http://portals.broadinstitute.org/oncotator) web API seems to be down since a while. This is causing the issue in fetching the  annotations. Unfortunately this will only be fixed when the API is back online :|
