### ISSUE TITLE
Interaction Between genes and top Parameters

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#382]
If the user specifies `genes`, the value of `top` is ignored.

**Use Case**
The user is interested in tumour suppressor genes and downloads a database from [TSGene](https://bioinfo.uth.edu/TSGene/).

```r
> tumourSuppressors <- read.delim("Human_TSGs.txt")[, "GeneSymbol"]
> length(tumourSuppressors)
[1] 1217
```

There are 1217 genes. The user wants to see the top 10 mutated tumour suppressor genes `top = 10` , but maftools creates an unreadable plot containing all of the genes.

A second problem is that it doesn't seem possible to only plot copy number variants, even if providing a dummy MAF object. For example,

```r
MAFnone <- data.frame(Hugo_Symbol = "FAKE-IGNORE", Chromosome = '.', Start_Position = '.', End_Position = '.', Reference_Allele = '.',
               Tumor_Seq_Allele2 = '.', Variant_Classification = "Missense", Variant_Type = '.',
               Tumor_Sample_Barcode = "SP13-2986primaryTissue", stringsAsFactors = FALSE)
```

Then, when I do `oncoplot(MAFnone, top = 10)` I get 9 copy number genes and the fake missense mutation in the MAF table in the bottom row of the oncoplot, even though there are plenty of high frequency copy number variants which could be in place of the fake gene rare SNP. I have to set `top = 11` to see the top 10 copy number genes, as shown below.

![image](https://user-images.githubusercontent.com/631218/63066732-e7462900-bf4e-11e9-86dc-f194c1e0c77b.png)

**Comment by PoisonAlien** [comment]
Hi, 
Sorry for the late reply.

1. `top` and `genes` arguments are mutually exclusive. If you're interested in top ten genes from your list of genes, you would have to provide those specific 10 genes to `genes` argument. Top only applies to "top" genes in the MAF object.

2. The way "top" genes in oncoplot is [chosen](https://github.com/PoisonAlien/maftools/blob/master/R/oncoplot.R#L124) is based on output from `getGeneSummary`. Maybe check check the output from `getGeneSummary` of your object?

**Comment by DarioS** [comment]
O.K. the second problem still stands, though. One gene that has a mutation is always plotted, even if the top genes are all copy number genes.
