### ISSUE TITLE
Bar Heights in Oncoplot Wrong When Copy Number Used

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#383]
If both SNVs and copy number are plotted, the bar chart only counts samples that have either a SNV or a copy number change, but not both. A minimal example which can simply be copied and pasted for testing:

```r
library("maftools")

mutations <- data.frame(Hugo_Symbol = rep(c("TP53", "TSC2"), c(4, 1)),
                        Chromosome = '.',
                        Start_Position = '.',
                        End_Position = '.',
                        Reference_Allele = '.',
                        Tumor_Seq_Allele2 = '.',
                        Variant_Classification = "Missense_Mutation",
                        Variant_Type = '.',
                        Tumor_Sample_Barcode = c("Adam", "Ben", "Chris", "David", "Edward"), stringsAsFactors = FALSE)

copyNumbers <- data.frame(Gene = c("TP53", "TP53", "TP53", "TP53", "BRAF", "TP53"), 
                          Person = c("Adam", "Ben", "Chris", "David", "David", "Zena"),
                          Copy = rep("Amp", 6), stringsAsFactors = FALSE)

MAF <- read.maf(mutations, cnTable = copyNumbers)
oncoplot(MAF)
```

Notice how TP53 is altered for 83% of samples but the bar's length only reaches to 1 out of 5. The bars above each column have the correct height.

**Comment by PoisonAlien** [comment]
Hi @DarioS ,
Sorry for the delay in addressing the issue, and thanks for reporting. 
There is no easy way to represent these. I have annotated them as `Complex_Event` (Mutation+Amp/Del). Please pull the updated version and let me know.

**Comment by DarioS** [comment]
It's plotted in a reasonably meaningful way in the updated version.
