### ISSUE TITLE
Problems of running oncotate

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#384]
Hi, I got the following error message when I try to run oncotate 
![Screen Shot 2019-08-16 at 8 20 24 PM](https://user-images.githubusercontent.com/31411260/63204194-485f2100-c063-11e9-84cd-10724f2b680f.png)
And the same problem happened when I ran the sample code:
sample.var = data.frame(chromsome = c('chr4', 'chr15'), Start = c(55589774, 41961117),
end = c(55589774, 41961117), ref = c('A', 'TGGCTAA'), alt = c('G', '-'),
Tumor_Sample_Barcode = c('fake_1', 'fake2'))
write.table(sample.var, 'sampleVars.txt', sep='\t',quote = FALSE, row.names = FALSE)
##var.maf <- oncotate(maflite = 'sampleVars.txt', header = TRUE)

Can anybody help me fix this problem?

Thank you.

**Comment by PoisonAlien** [comment]
Hi, Sorry for the late response. It appears `oncotator` api is down - including the [web interface](http://portals.broadinstitute.org/oncotator). I couldn't reproduce the error. Do you still have the issue?
