### ISSUE TITLE
Bug Report: using annovarToMaf to load annovar result without mutation in exon

### ISSUE THREAD

**Issue by wangshun1121** [PoisonAlien/maftools#388]
I'm using `annovarToMaf` function in latest maftools_2.0.16  release  to load my annotation result [X.annovar.hg19_multianno.txt](https://github.com/PoisonAlien/maftools/files/3589857/X.annovar.hg19_multianno.txt)

```
annovarToMaf("X.hg19_multianno.txt,table="refGene")
```

and got following error infos:

```
-Reading annovar files
--Tumor_Sample_Barcode column not found. Creating sample IDs from filenames
-Processing Exonic variants
Error in data.table::tstrsplit(x = as.character(ann_exonic$Func.refGene),  : 
  'keep' should contain integer values between 0 and 0.
```

I tried same command on my MacBook, where maftools's release is 1.8.10, annotation infos were loaded.

Then I checked the code of [annovarToMaf.R](https://github.com/PoisonAlien/maftools/blob/master/R/annovarToMaf.R), at 123ed row:

```
# https://github.com/PoisonAlien/maftools/blob/master/R/annovarToMaf.R # row 123 
 ann_exonic[, Func.refGene := data.table::tstrsplit(x = as.character(ann_exonic$Func.refGene), split = ";", keep = 1)]
```

In my file, there is neither `exonic` nor `splicing` mutation, can't such annovar results be loaded using `annovarToMaf`?

**Comment by PoisonAlien** [comment]
Hello @wangshun1121 ,
Thank you for reporting.. Indeed it was a bug. I have taken care of it. Could you please try and let me know? 

P.S; sorry for late response.

**Comment by wangshun1121** [comment]
It’s too late now in China, I will try it tomorrow

**Comment by PoisonAlien** [comment]
No problem, take your time.

**Comment by wangshun1121** [comment]
I tried your latest commit, this time the bug was fixed!

**Comment by rohankodgule** [comment]
```
> annovar_mafs = lapply(annovar_ops, annovarToMaf, Center = 'WashU', refBuild = 'hg38') #convert to MAFs using annovarToMaf
-Reading annovar files
--Tumor_Sample_Barcode column not found. Creating sample IDs from filenames
Error in data.table::tstrsplit(Gene.refGene, split = ";", keep = 1) : 
  'keep' should contain integer values between 0 and 0.
```
