### ISSUE TITLE
Error in FUN(X[[i]], ...) : subscript out of bounds with pfamDomains

### ISSUE THREAD

**Issue by carbonwei** [PoisonAlien/maftools#389]
Hi, 
I was working on the public TCGA LUAD dataset, functions including plotmafSummary, plotVaf, oncoplot, plotOncodrive, and lollipopPlot worked with the data.
>tcga_load(study = "LUAD") 
Loading objects:
tcga_luad_mc3
>LUAD = read.maf(maf = tcga_luad_mc3@data, clinicalData = tcga_lua d_mc3@clinical.data)
NOTE: Remluaded 2858 duplicated variants
>LUAD.pfam = pfamDomains(maf = LUAD)
Assuming protein change information are stored under column HGVSp_Short. Use argument AACol to override if necessary.
Error in FUN(X[[i]], ...) : subscript out of bounds

And pfamDomains can work properly with a subset of my data selected by genes.  
I saw an earlier ticket https://github.com/PoisonAlien/maftools/issues/43 about filtering /editing the annotation, but the link included is no longer available. Could you please help me by how I can deal with this case? Thanks a lot.

**Comment by PoisonAlien** [comment]
Hello!
It seems to be working fine. Can you post your sessionInfo?

```r
> tcga_load(study = "LUAD")
Loading objects:
  tcga_luad_mc3
Successfully loaded TCGA LUAD!
Please cite https://doi.org/10.1016/j.cels.2018.03.002 for MAF source.

>pfamDomains(maf = tcga_luad_mc3)
```

Btw, you dont have use `read.maf` again on an already built MAF object. You can just use the loaded `tcga_luad_mc3` as an input for all functions.
