### ISSUE TITLE
plotmafSummary insists on reusing old plot windows

### ISSUE THREAD

**Issue by krcoombes** [PoisonAlien/maftools#39]
Using maftools 1.0.40 with R 3.3.0 and BioConductor 3.4 on a Windows machine. (All of BioConductor has just been upgraded to the latest version.)

I have two different MAF files, and want to compare the results of plotmafSummary in side-by-side windows.  However, even if I call "windows()" to initialize a new device, it insists on plotting the second version in the first window (even though it was marked as "inactive" when the command was issued). That is, you get this behavior:

plotmafSummary(maf2) # appears in dev 2
windows() # creates new dev 3
plotmafSummary(maf3) # still appears in dev 2

You can work around this by creating a bunch of windows and killing the lower-numbered ones, which may hint at the source of the problem. In other words, if you use the following commands, you can display three different MAF files:

windows() # open dev 2
windows() # dev 3
windows() # dev 4
\# manually kill devices 2 and 3
plotmafSummary(maf4) # shows in dev4
windows() # new dev 2
windows() # new dev 3
\# manually kill dev 2
plotmafSummary(maf3) # shows in dev 3
windows() # new dev 2
plotmafSummary(maf2) # shows in dev 2

Anything else, however, and subsequent calls to plotmafSummary appear in the window with the lowest device number.

**Comment by PoisonAlien** [comment]
I am not sure how to arrange them in same window, since a plotting window is already defined while arranging multiple plots through grid.
