### ISSUE TITLE
Bug in oncoplot and related functions

### ISSUE THREAD

**Issue by anfederico** [PoisonAlien/maftools#390]
There seems to be a bug when calling the ComplexHeatmap package through oncoplot() and related functions.

For example:
```R
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
oncoplot(maf = laml, top = 3)
```

```
Error in ComplexHeatmap::Heatmap(mat, na_col = bg, rect_gp = grid::gpar(type = "none"),  : 
  unused argument (top_annotation_height = grid::unit(2, "cm"))
```

Here are my specs
```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

ComplexHeatmap_2.1.0 
maftools_2.1.0 
```

Any idea what the problem might be?

**Comment by PoisonAlien** [comment]
Hi,
This is weird. maftools does not depend on ComplexHeatmap anymore for oncoplots. Could you try to restart your R session or re-install the package and tray again?

**Comment by anfederico** [comment]
Re-installing from GitHub worked. Thanks.
