### ISSUE TITLE
mafCompare: altered numbers in two groups can be misleading

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#391]
I had two groups with different characteristics loaded from a single MAF, then subsetted runtime. When invoking `mafCompare` I noticed in the results a very puzzling line:

```
Hugo_symbol    M1     M2 pVal
POLE           10    10    4.416563e-07
```
It is not clear (but perhaps I did not interpret the result correctly) how `POLE` is a differentially mutated gene, given it appears in both cohorts with the exact same numbers.

**Comment by lbeltrame** [comment]
As the total sample size of individual groups matter,, I can figure out why it would be significant, but it is misleading for a biologist that would look at these results.

**Comment by PoisonAlien** [comment]
Yes, it is due to differences in cohort size. 10/100 is completely a different game than 10/25. Easy way is to represent these results is with `coOncoplot`.

**Comment by lbeltrame** [comment]
Indeed. This is not a real issue, so closing.

**Comment by MaryGoAround** [comment]
Dear @PoisonAlien this question may be irrelevant but I am not able to solve that

By this code I got this plot but after saving the margin (tumour names) are not completely showing

```
> laml.mutload = tcgaCompare(maf = laml,cohortName = "Cohort",rm_zero = FALSE,decreasing = TRUE,logscale = TRUE,primarySite = TRUE,col = c("grey30", "red"),medianCol = "black")
Performing pairwise t-test for differences in mutation burden..
> 
```

![Rplot04](https://user-images.githubusercontent.com/60115705/87657554-e2878780-c752-11ea-9fe9-d591ab228085.png)

Is it a way to show tumour names completely?
