### ISSUE TITLE
gisticChromPlot Error

### ISSUE THREAD

**Issue by Tinalxt** [PoisonAlien/maftools#392]
Hi,

I used the gisticChromPlot function but got an error.
I think that is because my data had not  significant amp cnvs.

The code is as follow:
```
>laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, 
                         gisticDelGenesFile = del.genes, gisticScoresFile = scores.gis, isTCGA = FALSE)
>gisticChromPlot(gistic = laml.gistic, markBands = "all")
Error in if (nrow(gis.scores[["Amp"]]) > 0) { : 
  argument is of length zero
```
I used the same files in R 3.5 and it was worked but not in R 3.6.
Is this a problem caused by the version of R?

**Comment by PoisonAlien** [comment]
Hi,
Its hard to guess the issue. Could you please post your sessionInfo? Also is there any chance to get a reproducible example data?

**Comment by Tinalxt** [comment]
> Hi,
> Its hard to guess the issue. Could you please post your sessionInfo? Also is there any chance to get a reproducible example data?
[all_lesions.conf_99.txt](https://github.com/PoisonAlien/maftools/files/3639552/all_lesions.conf_99.txt)
[del_genes.conf_99.txt](https://github.com/PoisonAlien/maftools/files/3639553/del_genes.conf_99.txt)
[amp_genes.conf_99.txt](https://github.com/PoisonAlien/maftools/files/3639554/amp_genes.conf_99.txt)
[scores.gistic.txt](https://github.com/PoisonAlien/maftools/files/3639559/scores.gistic.txt)





Hi, this are my files and sessioninfo.
─ Session info ─────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Sierra 10.12.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  zh_CN.UTF-8                 
 ctype    zh_CN.UTF-8                 
 tz       Asia/Shanghai               
 date     2019-09-22                  

─ Packages ─────────────────────────────────────────────
 package                     * version   date       lib source        
 assertthat                    0.2.1     2019-03-21 [1] CRAN (R 3.6.0)
 bibtex                        0.4.2     2017-06-30 [1] CRAN (R 3.6.0)
 Biobase                     * 2.44.0    2019-05-02 [1] Bioconductor  
 BiocGenerics                * 0.30.0    2019-05-02 [1] Bioconductor  
 BiocManager                   1.30.4    2018-11-13 [1] CRAN (R 3.6.0)
 BiocParallel                  1.18.1    2019-08-06 [1] Bioconductor  
 Biostrings                  * 2.52.0    2019-05-02 [1] Bioconductor  
 bitops                        1.0-6     2013-08-17 [1] CRAN (R 3.6.0)
 BSgenome                    * 1.52.0    2019-05-02 [1] Bioconductor  
 BSgenome.Hsapiens.UCSC.hg19 * 1.4.0     2019-08-26 [1] Bioconductor  
 circlize                    * 0.4.7     2019-08-21 [1] CRAN (R 3.6.0)
 cli                           1.1.0     2019-03-19 [1] CRAN (R 3.6.0)
 clue                          0.3-57    2019-02-25 [1] CRAN (R 3.6.0)
 cluster                       2.1.0     2019-06-19 [1] CRAN (R 3.6.1)
 codetools                     0.2-16    2018-12-24 [1] CRAN (R 3.6.1)
 colorspace                    1.4-1     2019-03-18 [1] CRAN (R 3.6.0)
 ComplexHeatmap              * 2.0.0     2019-05-02 [1] Bioconductor  
 crayon                        1.3.4     2017-09-16 [1] CRAN (R 3.6.0)
 curl                          4.0       2019-07-22 [1] CRAN (R 3.6.0)
 data.table                    1.12.2    2019-04-07 [1] CRAN (R 3.6.0)
 DelayedArray                  0.10.0    2019-05-02 [1] Bioconductor  
 digest                        0.6.20    2019-07-04 [1] CRAN (R 3.6.0)
 doParallel                    1.0.15    2019-08-02 [1] CRAN (R 3.6.0)
 dplyr                         0.8.3     2019-07-04 [1] CRAN (R 3.6.0)
 foreach                       1.4.7     2019-07-27 [1] CRAN (R 3.6.0)
 GenomeInfoDb                * 1.20.0    2019-05-02 [1] Bioconductor  
 GenomeInfoDbData              1.2.1     2019-08-25 [1] Bioconductor  
 GenomicAlignments             1.20.1    2019-06-18 [1] Bioconductor  
 GenomicRanges               * 1.36.0    2019-05-02 [1] Bioconductor  
 GetoptLong                    0.1.7     2018-06-10 [1] CRAN (R 3.6.0)
 ggplot2                       3.2.1     2019-08-10 [1] CRAN (R 3.6.0)
 GlobalOptions                 0.1.0     2018-06-09 [1] CRAN (R 3.6.0)
 glue                          1.3.1     2019-03-12 [1] CRAN (R 3.6.0)
 gridBase                      0.4-7     2014-02-24 [1] CRAN (R 3.6.0)
 gtable                        0.3.0     2019-03-25 [1] CRAN (R 3.6.0)
 IRanges                     * 2.18.2    2019-08-24 [1] Bioconductor  
 iterators                     1.0.12    2019-07-26 [1] CRAN (R 3.6.0)
 jsonlite                      1.6       2018-12-07 [1] CRAN (R 3.6.0)
 lattice                       0.20-38   2018-11-04 [1] CRAN (R 3.6.1)
 lazyeval                      0.2.2     2019-03-15 [1] CRAN (R 3.6.0)
 **maftools                    * 2.0.16    2019-08-14 [1] Bioconductor**  
 magrittr                      1.5       2014-11-22 [1] CRAN (R 3.6.0)
 Matrix                        1.2-17    2019-03-22 [1] CRAN (R 3.6.1)
 matrixStats                   0.54.0    2018-07-23 [1] CRAN (R 3.6.0)
 munsell                       0.5.0     2018-06-12 [1] CRAN (R 3.6.0)
 NMF                           0.21.0    2018-03-06 [1] CRAN (R 3.6.0)
 pheatmap                    * 1.0.12    2019-01-04 [1] CRAN (R 3.6.0)
 pillar                        1.4.2     2019-06-29 [1] CRAN (R 3.6.0)
 pixmap                      * 0.4-11    2011-07-19 [1] CRAN (R 3.6.0)
 pkgconfig                     2.0.2     2018-08-16 [1] CRAN (R 3.6.0)
 pkgmaker                      0.27      2018-05-25 [1] CRAN (R 3.6.0)
 plyr                          1.8.4     2016-06-08 [1] CRAN (R 3.6.0)
 png                           0.1-7     2013-12-03 [1] CRAN (R 3.6.0)
 purrr                         0.3.2     2019-03-15 [1] CRAN (R 3.6.0)
 R6                            2.4.0     2019-02-14 [1] CRAN (R 3.6.0)
 randomcoloR                 * 1.1.0     2017-12-08 [1] CRAN (R 3.6.0)
 RColorBrewer                * 1.1-2     2014-12-07 [1] CRAN (R 3.6.0)
 Rcpp                          1.0.2     2019-07-25 [1] CRAN (R 3.6.0)
 RCurl                         1.95-4.12 2019-03-04 [1] CRAN (R 3.6.0)
 registry                      0.5-1     2019-03-05 [1] CRAN (R 3.6.0)
 reshape2                    * 1.4.3     2017-12-11 [1] CRAN (R 3.6.0)
 rjson                         0.2.20    2018-06-08 [1] CRAN (R 3.6.0)
 rlang                         0.4.0     2019-06-25 [1] CRAN (R 3.6.0)
 rngtools                      1.4       2019-07-01 [1] CRAN (R 3.6.0)
 Rsamtools                     2.0.0     2019-05-02 [1] Bioconductor  
 rtiff                       * 1.4.6     2019-03-21 [1] CRAN (R 3.6.0)
 rtracklayer                 * 1.44.3    2019-08-24 [1] Bioconductor  
 Rtsne                         0.15      2018-11-10 [1] CRAN (R 3.6.0)
 S4Vectors                   * 0.22.0    2019-05-02 [1] Bioconductor  
 scales                        1.0.0     2018-08-09 [1] CRAN (R 3.6.0)
 sessioninfo                   1.1.1     2018-11-05 [1] CRAN (R 3.6.0)
 shape                         1.4.4     2018-02-07 [1] CRAN (R 3.6.0)
 stringi                       1.4.3     2019-03-12 [1] CRAN (R 3.6.0)
 stringr                       1.4.0     2019-02-10 [1] CRAN (R 3.6.0)
 SummarizedExperiment          1.14.1    2019-07-31 [1] Bioconductor  
 survival                      2.44-1.1  2019-04-01 [1] CRAN (R 3.6.1)
 tibble                        2.1.3     2019-06-06 [1] CRAN (R 3.6.0)
 tidyselect                    0.2.5     2018-10-11 [1] CRAN (R 3.6.0)
 V8                            2.3       2019-07-02 [1] CRAN (R 3.6.0)
 withr                         2.1.2     2018-03-15 [1] CRAN (R 3.6.0)
 wordcloud                     2.6       2018-08-24 [1] CRAN (R 3.6.0)
 XML                           3.98-1.20 2019-06-06 [1] CRAN (R 3.6.0)
 xtable                        1.8-4     2019-04-21 [1] CRAN (R 3.6.0)
 XVector                     * 0.24.0    2019-05-02 [1] Bioconductor  
 zlibbioc                      1.30.0    2019-05-02 [1] Bioconductor

**Comment by PoisonAlien** [comment]
Hello,
Sorry for late reply, and Thank for the example files. Indeed there were no significant peaks in your dataset to highlight. However if you increase your `fdrcutOff = 0.3` you will see some peaks getting highlighted. In any case, I have made tiny changes to the function to handle such situations. You can install it form GitHub if you would like. Please let me know if it helps.
