### ISSUE TITLE
trinucleotideMatrix

### ISSUE THREAD

**Issue by Macy-Zhao** [PoisonAlien/maftools#395]
Hi, 
Resently, I used extractSignatures to get signatures,but it alway reported bug as below.
So, how could I can deal with this bug?
Thank you very much for replying!
`Timing stopped at: 1635 856.7 351.6
Error in str_out(i) : object 'i' not found
Calls: extractSignatures ... anyStrings -> isTRUE -> validityMethod -> paste -> str_out
In addition: Warning messages:
1: In cor(d.consensus, d.coph, method = "pearson") :
  the standard deviation is zero
2: In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled core 3 did not deliver a result, all values of the job will be affected
3: In (function (...)  :
  NAs were produced due to errors in some of the runs:
        -#2[r=2] -> (list) object cannot be coerced to type 'double' [in call to 'which.min']
Execution halted`

**Comment by ShixiangWang** [comment]
please run library(NMF) firstly and see if it works.

**Comment by Macy-Zhao** [comment]
I did ,but still presented this bug!

**Comment by PoisonAlien** [comment]
Hi,
It appears your matrix is malformed. 
1. Try to run `extractSignatures`  with `pConstant = 0.1` 
2. If above doesn't work can you share your output from `trinucleotideMatrix`  as an Rds file?

**Comment by Macy-Zhao** [comment]
Well done! Then I have another problem, that is the genes on the picture which is from  plotEnrichmentResults are overlap with the number of samples,and it's hard to see which gene clearly. I'm sure no parameter to control, so How to solve this problem ? In addition,how could you  add ylab and which means is x-axis?

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. Its hard to imagine the issue, Is it possible to post a `png` of the image?

**Comment by Macy-Zhao** [comment]
the issue is the position indicated by the arrow on this image, the gene is covered by the number, and I want to add ylab and y-axis on this image ? 
How could I deal?
![微信图片_20191023154044](https://user-images.githubusercontent.com/49973279/67369755-29719380-f5ac-11e9-8c42-b4caace36285.png)

**Comment by PoisonAlien** [comment]
Hi,
You can save the plot to some high res pdf and it should be okay. Or you can use `annoFontSize` and `geneFontSize` argument to control font sizes.

Regarding the label, once you run the above function use `mtext` to add labels to the existing plot.

```r
plotEnrichmentResults(enrich_res = fab.ce, pVal = 0.05)
mtext(text = "Fraction", side = 2, las = 3, line = 2)
```

Hope this helps. Let me know if you have any followup questions.

**Comment by Macy-Zhao** [comment]
Thank you very much! Will you consider annotation of p-value below each gene, such as the star and dot presents the p-value like this picture as below?

![微信图片_20191024104520](https://user-images.githubusercontent.com/49973279/67449016-57f27b80-f64b-11e9-846c-1905442efeec.png)

**Comment by Tinalxt** [comment]
> Hi,
> It appears your matrix is malformed.
> 
> 1. Try to run `extractSignatures`  with `pConstant = 0.1`
> 2. If above doesn't work can you share your output from `trinucleotideMatrix`  as an Rds file?

Hi,
I had the same wrong message when used the extractSignatures function.
I have no idea what's wrong with my data.
How could I can deal with this bug?
`laml.sign = estimateSignatures(mat = laml.tnm, nTry = 6, pConstant = 0.1)
-Running NMF for 6 ranks
Compute NMF rank= 2  ... Timing stopped at: 0 0 0.005
ERROR
Compute NMF rank= 3  ... Timing stopped at: 0 0 0.006
ERROR
Compute NMF rank= 4  ... Timing stopped at: 0.004 0 0.005
[laml_tnm.zip](https://github.com/PoisonAlien/maftools/files/3999432/laml_tnm.zip)


ERROR
Compute NMF rank= 5  ... Timing stopped at: 0 0.004 0.006
ERROR
Compute NMF rank= 6  ... Timing stopped at: 0 0.004 0.005
ERROR
Error in (function (...)  : All the runs produced an error:
        -#1 [r=2] -> Error: memory could not be allocated for instance of type big.matrix [in call to 'big.matrix']
        -#2 [r=3] -> Error: memory could not be allocated for instance of type big.matrix [in call to 'big.matrix']
        -#3 [r=4] -> Error: memory could not be allocated for instance of type big.matrix [in call to 'big.matrix']
        -#4 [r=5] -> Error: memory could not be allocated for instance of type big.matrix [in call to 'big.matrix']
        -#5 [r=6] -> Error: memory could not be allocated for instance of type big.matrix [in call to 'big.matrix']
`

**Comment by ShixiangWang** [comment]
@Tinalxt Do you use the latest version of maftools? I don't find any problem. Do you run `library(NMF)` firstly?

```
> test = readRDS("~/Downloads/laml_tnm")
> library(NMF)
载入需要的程辑包：pkgmaker
载入需要的程辑包：registry

载入程辑包：‘pkgmaker’

The following object is masked from ‘package:base’:

    isFALSE

载入需要的程辑包：rngtools
载入需要的程辑包：cluster
NMF - BioConductor layer [OK] | Shared memory capabilities [NO: bigmemory] | Cores 7/8
  To enable shared memory capabilities, try: install.extras('
NMF
')
> library(maftools)
> res = extractSignatures(test, n = 3)
-Running NMF for factorization rank: 3
-Finished in0.859s elapsed (0.837s cpu)
> devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  zh_CN.UTF-8                 
 ctype    zh_CN.UTF-8                 
 tz       Asia/Shanghai               
 date     2019-12-25                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version    date       lib source                            
 assertthat     0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                    
 backports      1.1.5      2019-10-02 [1] CRAN (R 3.6.0)                    
 bibtex         0.4.2      2017-06-30 [1] CRAN (R 3.6.0)                    
 Biobase      * 2.46.0     2019-10-29 [1] Bioconductor                      
 BiocGenerics * 0.32.0     2019-10-29 [1] Bioconductor                      
 callr          3.4.0      2019-12-09 [1] CRAN (R 3.6.0)                    
 cli            2.0.0      2019-12-09 [1] CRAN (R 3.6.0)                    
 cluster      * 2.1.0      2019-06-19 [2] CRAN (R 3.6.1)                    
 codetools      0.2-16     2018-12-24 [2] CRAN (R 3.6.1)                    
 colorspace     1.4-1      2019-03-18 [1] CRAN (R 3.6.0)                    
 crayon         1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                    
 data.table     1.12.8     2019-12-09 [1] CRAN (R 3.6.0)                    
 desc           1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                    
 devtools       2.2.1      2019-09-24 [1] CRAN (R 3.6.0)                    
 digest         0.6.23     2019-11-23 [1] CRAN (R 3.6.0)                    
 dlstats        0.1.3      2019-11-14 [1] CRAN (R 3.6.0)                    
 doParallel     1.0.15     2019-08-02 [1] CRAN (R 3.6.0)                    
 dplyr          0.8.3      2019-07-04 [1] CRAN (R 3.6.0)                    
 ellipsis       0.3.0      2019-09-20 [1] CRAN (R 3.6.0)                    
 fansi          0.4.0      2018-10-05 [1] CRAN (R 3.6.0)                    
 foreach        1.4.7      2019-07-27 [1] CRAN (R 3.6.0)                    
 fs             1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                    
 ggplot2        3.2.1.9000 2019-12-19 [1] Github (tidyverse/ggplot2@351eb41)
 glue           1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                    
 gridBase       0.4-7      2014-02-24 [1] CRAN (R 3.6.0)                    
 gtable         0.3.0      2019-03-25 [1] CRAN (R 3.6.0)                    
 iterators      1.0.12     2019-07-26 [1] CRAN (R 3.6.0)                    
 jsonlite       1.6        2018-12-07 [1] CRAN (R 3.6.0)                    
 lattice        0.20-38    2018-11-04 [2] CRAN (R 3.6.1)                    
 lifecycle      0.1.0      2019-08-01 [1] CRAN (R 3.6.0)                    
 maftools     * 2.2.10     2019-12-16 [1] Bioconductor                      
 magrittr       1.5        2014-11-22 [1] CRAN (R 3.6.0)                    
 Matrix         1.2-18     2019-11-27 [2] CRAN (R 3.6.0)                    
 memoise        1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                    
 munsell        0.5.0      2018-06-12 [1] CRAN (R 3.6.0)                    
 NMF          * 0.21.0     2018-03-06 [1] CRAN (R 3.6.0)                    
 packrat        0.5.0      2018-11-14 [1] CRAN (R 3.6.0)                    
 pacman       * 0.5.1      2019-03-11 [1] CRAN (R 3.6.0)                    
 pillar         1.4.2      2019-06-29 [1] CRAN (R 3.6.0)                    
 pkgbuild       1.0.6      2019-10-09 [1] CRAN (R 3.6.0)                    
 pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 3.6.0)                    
 pkgload        1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                    
 pkgmaker     * 0.27       2018-05-25 [1] CRAN (R 3.6.0)                    
 plyr           1.8.5      2019-12-10 [1] CRAN (R 3.6.0)                    
 prettyunits    1.0.2      2015-07-13 [1] CRAN (R 3.6.0)                    
 processx       3.4.1      2019-07-18 [1] CRAN (R 3.6.0)                    
 ps             1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                    
 purrr          0.3.3      2019-10-18 [1] CRAN (R 3.6.0)                    
 R6             2.4.1      2019-11-12 [1] CRAN (R 3.6.0)                    
 RColorBrewer   1.1-2      2014-12-07 [1] CRAN (R 3.6.0)                    
 Rcpp           1.0.3      2019-11-08 [1] CRAN (R 3.6.0)                    
 registry     * 0.5-1      2019-03-05 [1] CRAN (R 3.6.0)                    
 remotes        2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                    
 reshape2       1.4.3      2017-12-11 [1] CRAN (R 3.6.0)                    
 rlang          0.4.2      2019-11-23 [1] CRAN (R 3.6.0)                    
 rngtools     * 1.4        2019-07-01 [1] CRAN (R 3.6.0)                    
 rprojroot      1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                    
 rstudioapi     0.10       2019-03-19 [1] CRAN (R 3.6.0)                    
 scales         1.1.0      2019-11-18 [1] CRAN (R 3.6.0)                    
 sessioninfo    1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                    
 stringi        1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                    
 stringr        1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                    
 survival       3.1-8      2019-12-03 [2] CRAN (R 3.6.0)                    
 testthat       2.3.1      2019-12-01 [1] CRAN (R 3.6.0)                    
 tibble         2.1.3      2019-06-06 [1] CRAN (R 3.6.0)                    
 tidyselect     0.2.5      2018-10-11 [1] CRAN (R 3.6.0)                    
 usethis        1.5.1      2019-07-04 [1] CRAN (R 3.6.0)                    
 withr          2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                    
 wordcloud      2.6        2018-08-24 [1] CRAN (R 3.6.0)                    
 xtable         1.8-4      2019-04-21 [1] CRAN (R 3.6.0)                    

[1] /Users/wsx/R_library
[2] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

**Comment by ShixiangWang** [comment]
@PoisonAlien This issue is inactive and should be closed. I can't see a reason to make it open :).
