### ISSUE TITLE
survival analysis for all mutated genes

### ISSUE THREAD

**Issue by anyone1985** [PoisonAlien/maftools#396]
For our data, we hope to identify which mutated genes were significantly associated with an increased risk of relapse. However, I found in the vignette that maftools could do the survival analysis once for one gene. I'd like to know if there is any way to do survival analysis for all mutated genes and show the HR and P-value.

**Comment by PoisonAlien** [comment]
Hi, 
There is no direct way to do it as of now, but I think easiest way would be to loop over the gene list.. I will see if I can make a function out of it..

**Comment by PoisonAlien** [comment]
Hello,
Thanks again. I have made few functions to automate this.
`survGroup` is the function which loops over a set of genes (or geneset of size `N`) and calculates survival. 

example usage:
```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml.clin <- system.file("extdata", "tcga_laml_annot.tsv", package = "maftools")
laml <- read.maf(maf = laml.maf,  clinicalData = laml.clin)
survGroup(maf = laml, top = 20, geneSetSize = 1, time = "days_to_last_followup", Status = "Overall_Survival_Status")
```

above function uses top 20 mutated genes and estimates survival for every gene. You can increase geneSetSize to predict a combination of genes which might be associated with poor survival. 

Please try it and let me know if this helps you. You will have to install from GitHub `devel` branch

```r
BiocManager::install(pkgs = "poisonalien/maftools@devel")
```

**Comment by anyone1985** [comment]
Thanks a lot. It is very helpful.

**Comment by PoisonAlien** [comment]
I hope it worked. Thanks for the issue.

**Comment by MjelleLab** [comment]
Hi, I wonder if the p-values from survGroup are adjusted for multiple testing? You are testing a bunch of different genes. Same goes for the mafSurvGroup where you test combination of genes. Maybe this should be specified in the tutorial. Regards. @PoisonAlien
