### ISSUE TITLE
missing required fields from MAF: Hugo_Symbol

### ISSUE THREAD

**Issue by gianfilippo** [PoisonAlien/maftools#397]
Hi,

I have a gatk generated MAF file and I am trying to read it with read.maf. It fails at the validation stage with the following:

-Reading
-Validating
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  : 
  missing required fields from MAF: Hugo_Symbol

Do you have any suggestions ?

Thanks

**Comment by PoisonAlien** [comment]
Hello,
Make sure your file is MAF according to the [specifications](https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/#protected-maf-file-structure).. Could you please provide me with a sample file.. maybe top 100 rows?

**Comment by gianfilippo** [comment]
Hi,

the sample file is attached. I left the header as well, for you to see the gatk commands I used to generate it.

[sample.maf.zip](https://github.com/PoisonAlien/maftools/files/3679287/sample.maf.zip)

Thanks
Gianfilippo

**Comment by PoisonAlien** [comment]
Hello,
Thank you for the sample file. I took a look at it, and although it looks like an maf file - its weirdly formatted. R has trouble reading it in since the columns are seperated neither by tab nor by comma. I see that you have used Funcotator for annotations, which I have no experience with. Could you maybe try [vcf2maf](https://github.com/mskcc/vcf2maf) on your raw Mutect output?

**Comment by gianfilippo** [comment]
Hi,

thanks. I will do that and let you know.

Best

**Comment by sahuno** [comment]
Dear all,

`vcf2maf` came with its own problems while installing on our servers/getting it to work. 

Use `read.delim()` function in `R` to first read the .maf file generated by **funcotator** (specifying these options) and then parse it to `read.maf()` function to get a maf object.

Example codes below;

```
single.maf.delim <- read.delim(file = "/path/to/maf.file.generated.from.foncotator.maf", sep = "\t", header = TRUE, fill = TRUE, comment.char = "#")
maf.object <- read.maf(maf=single.maf.delim) ###optional, add clinical annotation file with "clinicalData" argument in read.maf()
```

you can use this to merge multiple `.maf` files produced by `foncotator` and use `maftools` to read and perform your downstream analysis/visualizations

```
###reading mutiple .maf files as a large list
setwd("/path/to/annotated.with.foncotator.maf.files.maf")
maf.filenames <- list.files(full.names=TRUE)  
list.all.maf.files <- lapply(maf.filenames,function(i){
  read.delim(i, sep = "\t", header = TRUE, fill = TRUE, comment.char = "#")
})                        

###merging the all the .maf files
merged_mafs_files <- maftools::merge_mafs(list.all.maf.files)                                      

###check to see if everything is okay  
getSampleSummary(merged_mafs_files)                                    
getGeneSummary(merged_mafs_files) 
```

Best of luck

**Comment by PoisonAlien** [comment]
Okay found a workaround. `data.table` has a quote argument which helps. Could you please try again and let me know if `read.maf` works on your funcotator output? You will have to re-install from Github.

**Comment by jungminchoilab** [comment]
@PoisonAlien Could you please elaborate how to fix this using data.table? I am having the same issue after annotating mutect2.vcf with the funcotator. I also tried suggestions from @sahuno which did not work in my hands.

Thanks so much for making this tool available to the field.

**Comment by PoisonAlien** [comment]
Hi @jungminchoilab ,
Is its possible to share reproducible sample output file?

**Comment by jungminchoilab** [comment]
Hi @PoisonAlien, thanks for your prompt response. Please see below and let me know if you are having issues downloading a file.

[an example maf file](https://www.dropbox.com/s/lly272sddnxzm9n/YUL0207P.combined.mutect2.strelka2.funcotated.maf?dl=0)

**Comment by PoisonAlien** [comment]
Thanks for sharing your file. It seems to work for me. What version of the package are you using? 
Another thing I noticed from your file is that the entries in `Tumor_Sample_Barcode` columns are set to `NA`. This will be of trouble, and you will have to populate this column with corresponding sample names.

**Comment by jungminchoilab** [comment]
Thanks again for checking @PoisonAlien . The version that I installed is maftools_2.2.10. Which one am I supposed to use?

Apparently, funcotator does not annotate tumor sample ID. I will re-annotate it properly. Is normal sample ID also required?

**Comment by PoisonAlien** [comment]
Could you please install the tool from `GitHub` and try again. 
I am considering of adding an argument to `read.maf` for adding sample names parsed from file names - in case `Tumor_Sample_Barcode` columns are empty as in this case. Would that be helpful? 
No, normal sample IDs are not required.

**Comment by jungminchoilab** [comment]
As suggested, I re-installed the tool from GitHub and the version is now maftools_2.3.10 .

I also ran funcotator again and properly annotated a tumor_sample_barcode column (please see below).

[re-annotated maf](https://www.dropbox.com/s/tx4secbal79x2r5/YUL0207P.combined.mutect2.strelka2.funcotated.maf?dl=0)

Unfortunately, I am re-producing the same error message and wonder what might have gone wrong.

```
> library(maftools)
> #path to MAF file
> test.maf = system.file('extdata', 'YUL0207P.combined.mutect2.strelka2.funcotated.maf', package = 'maftools') 
> test.ar = read.maf(maf = test.maf)
-Reading
-Validating
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  : 
  missing required fields from MAF: Hugo_Symbol
```
I do appreciate your kind help @PoisonAlien .

**Comment by PoisonAlien** [comment]
You dont have to run `system.file` command. Its only for accessing example files that are bundled with the packages. Juts pass the path to your maf file.

e.g;
```r
x = maftools::read.maf(maf = "~/Downloads/YUL0207P.combined.mutect2.strelka2.funcotated (1).maf")
```

P.S; Maftools would be of little help in case of single sample, you would need two or more samples to take advantage of all the functions.

**Comment by jungminchoilab** [comment]
@PoisonAlien hmm, same error... and yes, I have multiple cases for the analysis but wanted to troubleshoot with one sample first.

```
> test.maf = maftools::read.maf(maf = "/Users/jungminchoi/mutect2/YUL0207P.combined.mutect2.strelka2.funcotated.maf")
-Reading
-Validating
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  : 
  missing required fields from MAF: Hugo_Symbol
```

**Comment by PoisonAlien** [comment]
I can not think of any reasons why it should give an error. I works for me with the same file. 
Anyway could you check following commands:

```r
mymaf <-
      data.table::fread(
        file = "/Users/jungminchoi/mutect2/YUL0207P.combined.mutect2.strelka2.funcotated.maf",
        sep = "\t",
        stringsAsFactors = FALSE,
        verbose = FALSE,
        data.table = TRUE,
        showProgress = TRUE,
        header = TRUE,
        fill = TRUE,
        skip = "Hugo_Symbol",
        quote = ""
      )
> test.maf = maftools::read.maf(maf = mymaf)
```

**Comment by jungminchoilab** [comment]
Thanks for your patience, @PoisonAlien ! Now getting another error...

```
> test.maf = maftools::read.maf(maf = mymaf)
-Validating
-Silent variants: 12 
-Summarizing
-Processing clinical data
--Missing clinical data
Error in maftools::read.maf(maf = mymaf) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/maftools/R/maftools.rdb' is corrupt
In addition: Warning message:
In maftools::read.maf(maf = mymaf) : internal error -3 in R_decompress1
```

**Comment by PoisonAlien** [comment]
No problem. I am sorry that you are getting these errors.
For above error you need to restart your R session and it should be fine. 
If you still get an error, do you mind opening a new issue. I don't want to spam others linked with the issue.

**Comment by jungminchoilab** [comment]
Will do. Thanks so much again for solving this for me.

**Comment by naiem836** [comment]
i have problem running this code 

mymaf <-
  data.table::fread(
    file = "data_mutations.maf",
    sep = "\t",
    stringsAsFactors = FALSE,
    verbose = FALSE,
    data.table = TRUE,
    showProgress = TRUE,
    header = TRUE,
    fill = TRUE,
    skip = "Hugo_Symbol",
    quote = ""
  )

test.maf = maftools::read.maf(maf = mymaf)


#Get the sample information
sample_info = read.table(file="clinicaldata_tcga_bc_f.tsv", sep="\t", header=T)

laml_tcga = read.maf(maf = test.maf, clinicalData = sample_info )


####333################################
test.maf = maftools::read.maf(maf = mymaf)
-Validating
--Removed 5396 duplicated variants
-Silent variants: 51626
-Summarizing
--Possible FLAGS among top ten genes:
  TTN
  MUC16
  SYNE1
-Processing clinical data
--Missing clinical data
-Finished in 3.300s elapsed (3.090s cpu)
> #Get the sample information
> sample_info = read.table(file="clinicaldata_tcga_bc_f.tsv", sep="\t", header=T)

laml_tcga = read.maf(maf = test.maf, clinicalData = sample_info ) 
-Reading Error in file.info(file) : invalid filename argument

**Comment by PoisonAlien** [comment]
Hi,

Note that `test.maf` should be a path to the maf file or a data.frame/data.table. In your last command `test.maf` is already an maf object.

**Comment by naiem836** [comment]
Thank you. The code worked, but another issue has popped up.

After running .....all things 

mymaf <-
  data.table::fread(
    file = "data_mutations.maf", sep = "\t",stringsAsFactors = FALSE,verbose = FALSE,data.table = TRUE,showProgress = TRUE,
    header = TRUE,
    fill = TRUE,
    skip = "Hugo_Symbol",
    quote = "")
    
##Get the sample information
sample_info = read.table(file="clinicaldata_tcga_bc_f.tsv", sep="\t", header=T)
laml_tcga = read.maf(maf = mymaf, clinicalData = sample_info,verbose = TRUE )

#################
issue ; Error in summarizeMaf(maf = nonSyn, anno = clinicalData, chatty = verbose) : 
  Tumor_Sample_Barcode column not found in provided clinical data. Rename column containing sample names to Tumor_Sample_Barcode if necessary.

############### 
some people said It has an issue when (mymaf file) here can't recognize the nonsynonymous mutation . so added 

#################
mymaf <-
  data.table::fread(
    file = "data_mutations.maf", sep = "\t",stringsAsFactors = FALSE,verbose = FALSE,data.table = TRUE,showProgress = TRUE,
    header = TRUE,
    fill = TRUE,
    skip = "Hugo_Symbol",
    quote = "",vc_nonSyn=c("Missense_Mutation", "Nonsense_Mutation"))

##### but 
Error in data.table::fread(file = "data_mutations.maf", sep = "\t", stringsAsFactors = FALSE,  : 
  unused argument (vc_nonSyn = c("Missense_Mutation", "Nonsense_Mutation"))
#########
The argument here remains unrecognized
