### ISSUE TITLE
Error in apply(X = apobec.fisher.dat, 1, function(x) { :    dim(X) must have a positive length

### ISSUE THREAD

**Issue by Tato14** [PoisonAlien/maftools#398]
Hi!

I am trying to run `trinucleotideMatrix` on a set of samples. I upload the maf file without problems but when I run this command I have an error:

```
> laml.tnm = trinucleotideMatrix(maf = PGDx_maf,
+                                ref_genome = "BSgenome.Hsapiens.UCSC.hg19")
-Extracting 5' and 3' adjacent bases
-Extracting +/- 20bp around mutated bases for background C>T estimation
-Estimating APOBEC enrichment scores
--Performing one-way Fisher's test for APOBEC enrichment
Error in apply(X = apobec.fisher.dat, 1, function(x) { : 
  dim(X) must have a positive length
```

Any idea why is this happening? Thanks!

**Comment by yabin2018** [comment]
hi,

I just met the same problem these days. I sovled by changing the order of two column  : Tumor_Seq_Allele1 and Tumor_Seq_Allele2 in my maf file.  For I found " T  T  C " in "lamlmafsummary.maf_maftools.maf" while my maf file is "A T A" in three columns.

Hope it can help you.

**Comment by PoisonAlien** [comment]
Hi both,
Please accept my apologies for the late reply. 
@Tato14 Did you figure out the issue?

**Comment by Tato14** [comment]
Hi,

Yes @yabin2018 point me to the solution. The error was caused because the Reference_Seq_Allele, Tumor_Seq_Allele1 and Tumor_Seq_Allele2 were empty in my maf file. Reconstructing this columns solved the issue.

Thanks!
