### ISSUE TITLE
What are columns in oncoplot?

### ISSUE THREAD

**Issue by dhwani2410** [PoisonAlien/maftools#399]
In oncoplot, there is a heatmap and barplot on top of it. what does each block represent? Is it representation for 193 samples? 
which means there are 193 columns? or something else? can you please brief the details about the plot , also what does shading of heatmap tell? Ther can be multiple variations in a gene including multiple types (Missense, frameshift,etc) but each block has only one color in heat map

**Comment by PoisonAlien** [comment]
Hello,
Please accpet my apologies for the late response. Regarding the plot, its quite simple representation of overall somatic landscape. Each row in the heatmap matrix represents a `gene` and each column represents a `sample`. Each block is color coded according to the type of variant (which is represented by `Variant_Classification` in the maf file). Color codes are annotated in legend. When a gene is mutated more than once in the same sample - it is color coded by black indicating its a `Multi_Hit` variant. When a block in the matrix is `gray` - it means that the gene (row) is a `wild type` in that sample (column).

Top bar plot shows total number of variants in each sample (i.e column in the matrix). Side bar plot shows total number of variants in a particular gene (i.e rows in the matrix). 

Hope this helps. You can also refer to TCGA landmark articles which always begin with this kind of plot. Here is an example from [Melanoma](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4580370/figure/F1/) project (Figure-1A)
