### ISSUE TITLE
SKCM MAF from GDC can not be read

### ISSUE THREAD

**Issue by rolfhaut** [PoisonAlien/maftools#40]
Hi,

Looks like a really nice package. With the example file it does work like a charm. I just have the problem that when I try to look at the SKCM data availabe from GDC, I'm not able to read the maf file.
The following error occurs:
reading maf..
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names

Maybe it is a trivial problem, but beeing a novice to R I wasn't able to solve it. Any suggestion to be ablte to load the file?
Thanks
David

**Comment by PoisonAlien** [comment]
Hi,

I just downloaded SKCM from GDC (I believe this is the one : https://gdc-portal.nci.nih.gov/files/49540f53-3228-4a65-8854-ebd2f4a8f5ce ) and it works fine on my Mac. However I guess you're on Windows and the input file is gzipped ? Can you uncompress gz file to plain text and try again ?

**Comment by rolfhaut** [comment]
Hi,

That was indeed the problem. 
Thanks
David

**Comment by krcoombes** [comment]
I'm not convinced that this issue should be closed without changing either the code or the documentation.  The man page for 'read.maf' says that the 'maf' argument is a
    "tab delimited MAF file. File can also be gz compressed." 
But (at least on Windows as far as I can determine), whenever I pass in a gzipped MAF file, I get the same error about more columns than column names. If I first manually gunzip the file, it works just fine. I view the failure of the performance to match the documentation as a still-open bug.

**Comment by PoisonAlien** [comment]
Hi,
Yes you are right about it. I will try to fix it by weekend. I guess its because the first line of input file is a comment (generally indicating MAF version) and read.csv is struggling to handle it.

**Comment by krcoombes** [comment]
Not sure why you would use read.csv instead of read.table for a
tab-separated file. But even less sure of why you get different results
when gunzip-ing in R instead of with an external tool. Is it as simple as
making sure you include the "skip=1" parameter?

**Comment by PoisonAlien** [comment]
There is not much difference between table an csv reader, hence I used read.csv. Regarding second point yes, even I am not sure about whats going on. skip=1 will skip header if there are no comment lines, better way is to use `comment.char = "#"`. Most of the maf files I checked are on either linux or MacOS, I will check again on windows machines and fix it soon.

**Comment by zayni** [comment]
Hi,
getting errors this morning. I am a Mac User

reading maf..
Error in data.table::fread(input = maf, sep = "\t", stringsAsFactors = FALSE,  : 
  Input is either empty or fully whitespace after the skip or autostart. Run again with verbose=TRUE.
 It was working well yesterday. Not sure what is going on?

**Comment by tiagochst** [comment]
You might be able to use TCGAbilinks to download the data and use with maftools, an example is in the bottom page.
https://www.bioconductor.org/packages/devel/bioc/vignettes/TCGAbiolinks/inst/doc/mutation.html

```
library(TCGAbiolinks)
library(maftools)
maf <- GDCquery_Maf("SKCM", pipelines = "muse") %>% read.maf(removeSilent = TRUE, useAll = FALSE)
```

**Comment by rafalcode** [comment]
worth mentioning you need 
library(magrittr)
for the "%>%"

**Comment by tiagochst** [comment]
@PoisonAlien I'm not sure you were going to create a GUI, but I  just added your tool to [TCGAbiolinksGUI](https://bioconductor.org/packages/release/bioc/html/TCGAbiolinksGUI.html) 
Your package is awesome, nice work!

[Youtube Video](https://youtu.be/SH7W9sowleI)

**Comment by PoisonAlien** [comment]
wow this is amazing! Thank you for the effort and making maftools a part of TCGABiolinks :)
