### ISSUE TITLE
Documentation: clarify what each dot means in plotVaf

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#401]
That was an actual question asked when showing some of the results on my data: in case a sample has multiple variants in the same gene, are they averaged, or is the VAF plotted for each of them (so, each "dot" in the plot is a single variant)?

**Comment by PoisonAlien** [comment]
Hi,
I am sorry for the late reply. Regarding the plot, there is no data aggregation on vaf values. They are drawn as is. Each point is a mutation - you can see the total number of mutations on top annotation values. I hope this helps.
