### ISSUE TITLE
TiTv plot in the maftools vignette is very different from MC3 set.

### ISSUE THREAD

**Issue by tangwei1129** [PoisonAlien/maftools#402]
I plotted LAML dataset of TCGA from MC3 for TiTv ratio plot (ratio = ~1). I found it is very different from the TiTv plot in the maftools vignette (ratio = ~3). do you know what is causing the difference between two data sources?

**Comment by PoisonAlien** [comment]
Hi,
Please accept my apologies for the late reply. Regarding the issue, Yes! Indeed there is a significant difference between `MC3` and the normal maf - especially for LAML. Here is an excerpt from the MC3 [publication](https://www.ncbi.nlm.nih.gov/pubmed/29596782) regarding the issue.

> For some cancer types, tumor cells profuse into the normal cells, causing issues in the identification of somatic variants. The best example of this is acute myeloid leukemia (LAML), which affects blood and bone marrow. Normal tissue samples (skin biopsies) from LAML patients often contain blood enriched with tumor cells. This can cause variant calling programs to mislabel somatic mutations as germline. The MC3 pipeline is conservative, attempting to remove all false-positive germline calls. Much of the original MAF created by the TCGA LAML AWG was derived by manual interventions, including Sanger sequencing data not included as part of the TCGA data catalog, to recover variants that would have otherwise been uncalled. As a result, the open-access MC3 call set only recovered 44% of the variants called in the original MAF (Figure S1).

I think MC3 variant calling pipelines being strict as they are, removed most of the validated variants.
