### ISSUE TITLE
oncotator discontinued

### ISSUE THREAD

**Issue by Sebbyyy** [PoisonAlien/maftools#403]
Hi,

since oncotator is discontinued - is this gonna be updated to use with their new foncotator?

**Comment by PoisonAlien** [comment]
Hi @Sebbyyy ,
Please accept my apologies for the late reply. For the upcoming Bioconductor release (which is in a week) I have removed `oncotate` function from the package. However, I am not aware of the `Funcotator` output. It doesn't seem to support MAF format yet. I will keep an eye on it. If you have a sample output from the tool - please feel free to share it ,and I am happy to write a parser for it (depending on the complexity).

**Comment by Sebbyyy** [comment]
Hi @PoisonAlien,

No problem.

I honestly do not know much about the funcotator currently. It is run by the Broad again so I assume very similar (https://software.broadinstitute.org/gatk/documentation/article?id=11193).

My understanding is that it is an updated better version of oncotator? Seems to be vcf or maf output and just can't input a maf.

**Comment by PoisonAlien** [comment]
Actually this issue has been raised previously #397 
MAF was generated from funcotator but somehow the format was weird. Yes, it would be great if you can find an example.

**Comment by Sebbyyy** [comment]
@PoisonAlien Sorry about the delay.

See attached. The actual output comes in a .txt format but same data.

[VCF Funcotator Input.xlsx](https://github.com/PoisonAlien/maftools/files/3833428/VCF.Funcotator.Input.xlsx)
[Funcotator Output.xlsx](https://github.com/PoisonAlien/maftools/files/3833429/Funcotator.Output.xlsx)

**Comment by sahuno** [comment]
@PoisonAlien please any update on this? 
I have .maf files generated with foncotator but can't get maftools to read  it. 
Thanks for your support!

```
> laml.colon=read.maf(maf ="path/to/sample.hg38-filtered.annotated.maf")
-Reading
-Validating
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  : 
  missing required fields from MAF: Hugo_Symbol
```

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.0.16     Biobase_2.44.0      BiocGenerics_0.30.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3          plyr_1.8.5          pillar_1.4.3        compiler_3.6.0      RColorBrewer_1.1-2  BiocManager_1.30.10 rngtools_1.4       
 [8] iterators_1.0.12    tools_3.6.0         digest_0.6.23       lattice_0.20-38     lifecycle_0.1.0     tibble_2.1.3        gtable_0.3.0       
[15] gridBase_0.4-7      NMF_0.21.0          pkgconfig_2.0.3     rlang_0.4.2.9000    Matrix_1.2-18       foreach_1.4.7       bibtex_0.4.2.2     
[22] registry_0.5-1      rstudioapi_0.10     withr_2.1.2         dplyr_0.8.3         pkgmaker_0.31       stringr_1.4.0       cluster_2.1.0      
[29] wordcloud_2.6       grid_3.6.0          tidyselect_0.2.5    data.table_1.12.8   glue_1.3.1          R6_2.4.1            survival_3.1-8     
[36] reshape2_1.4.3      ggplot2_3.2.1       purrr_0.3.3         magrittr_1.5        splines_3.6.0       scales_1.1.0        codetools_0.2-16   
[43] assertthat_0.2.1    xtable_1.8-4        colorspace_1.4-1    stringi_1.4.5       lazyeval_0.2.2      doParallel_1.0.15   munsell_0.5.0      
[50] crayon_1.3.4       
```

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. I do not have a sample funcotator for clear checking, do you think you can share one? You can remove any personal info. Also I came across this [tweet](https://twitter.com/RiyueSunnyBao/status/1208187652408774657?s=20) about empty quotes in funcotator output being the culprit. Maybe you can check it?

**Comment by ejoffe19** [comment]
Hi, 

Any plan on implementing Funcotator in MAFtools ?
With the deprecation of Oncotator this is extremely needed. 

Thanks
E

**Comment by PoisonAlien** [comment]
Hi,
You can directly use MAF output from funcotator, it should work.

**Comment by ejoffe19** [comment]
Thanks, my problem is that I need a wrapper that is capable of annotating similar to your prior Oncotate function which was fantastic. 
I have several dataset from different sources and I have been wanting to have them all annotated on the same pipeline.

**Comment by PoisonAlien** [comment]
`Oncotate` function used to query `Oncotator` web API for annotations. However, funcotator lacks the API feature which makes its impossible to for on-the-fly annotations.

**Comment by ejoffe19** [comment]
Are you familiar with Rcwl Pipelines
Maybe it can somehow assist - but I couldn't figure out the input types I need to arrange for it. 

BTW, thanks for answering and for an amazing package - really makes my life easier.

**Comment by PoisonAlien** [comment]
Thanks, and I am glad that you find it useful.
Variant annotations are ideally best done outside the R. Maybe using annovar, vcf2maf or the new funcotator which seems pretty good. Running from within R makes it slower and messy IMO.
