### ISSUE TITLE
Allow Sorting to Include Copy Number Variants

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#405]
Oncoplot uses `MutatedSamples` rather than `AlteredSamples` for sorting. But, if I have a small gene set of a hundred or so genes, and I want to plot the top 10 altered genes, such that sorting based on CNV is also included, it can't be done. I would like to request that a user option be made available to choose altered or mutated sorting. Although it's not informative in most cases, it is in some cases, such as when many samples have EGFR amplification.

**Comment by PoisonAlien** [comment]
Hi,
I can push some changes. Meanwhile you can try `genes` argument and it should work.

**Comment by PoisonAlien** [comment]
Hello,
I have added an argument `altered` to `oncoplot`. Could you please try it before Monday if possible and let me know? Thanks!

**Comment by DarioS** [comment]
It works for me. Perhaps a paragraph should be added to Customizing Oncoplots vignette describing when it's useful (i.e. small and specific gene set) and when it's not (i.e. all genes).
