### ISSUE TITLE
How to choose the priority of gene mutation

### ISSUE THREAD

**Issue by zhaozheng** [PoisonAlien/maftools#406]
I was wondering what type of mutation would be shown that genes with more than one variant type of each variant in the cell.
For example, take a gene which has Missense mutation and Frameshift. How to select to show Missense mutation or Frameshift? I guess that there is a mutation type priority in this tools.
Thanks!

**Comment by PoisonAlien** [comment]
Hello,
Such complex variants are often represented as `Multi_Hit`. There is no prioritisation of variant types being done, and there is no option to do so for now.

**Comment by zhaozheng** [comment]
I've learned. Many thank for you~
