### ISSUE TITLE
Incorrect Altered Gene Ordering

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#407]
I used `altered = TRUE` for my oncoplot of real data. A gene with four variants is shown higher than genes with five variants. So, the percentages on the right side of the plot are not strictly descending.

![image](https://user-images.githubusercontent.com/631218/67653416-661eff80-f99d-11e9-8422-41496bd2d270.png)

I also wonder if it is simple to get a plot sorted only by copy number variants, removing TP53 above.

**Comment by DarioS** [comment]
The cause of this is that I still had `sortByMutation = TRUE` which must be removed for alteration sorting.

**Comment by PoisonAlien** [comment]
Nice catch :+1:
