### ISSUE TITLE
Question on how read.maf works alongside mafSurvival

### ISSUE THREAD

**Issue by aguardio** [PoisonAlien/maftools#408]
Hey, not sure if this is the right place to post this, if not if I can be pointed in the right direction I would appreciate that.
I'm going through a previous project done by someone else and I want to know what happens when using
read.maf(maf_file, clinical_data)

In the case that the list of "tumor_sample_barcode" present in the maf_file is a subset of the list of "tumor_sample_barcode" present in clinical_data.
i.e. I am inputting clinical data for patients I don't have the MAF data for.
I believe when I do this, the "Formal class MAF" file generated contains:
within data the samples in the original maf file
within clinical.data all of the clinical data.

Now, if using this Fomal Class MAF file I call the function mafSurvival filtering by a list of genes. I think this plots the total number of samples in the clinical data.
So it classes all the mutants with MAF data as mutants, but the wildtype group will include some samples that I don't have MAF data for, so some of these samples could actually be mutants.
The reason I think this is the case is because the total number plotted (i.e. mutant + wildtype) is greater than the number of samples with mutation annotations.

I know thta the way around this would be to ensure that the clinical data used includes only the samples with mutation annotations. However I want to confirm that with the method outlined above the result is what I think it is.

Thank you!

**Comment by aguardio** [comment]
In case this is still unclear:

If I had a maf file with 3 samples 1 of which has a mutation in one of the specified genes, and a clinical data file with 10 samples (the 3 with annotations and another 7).
After doing 
complete_maf -> read.maf(maf, clinical)
and 
mafSurvival(complete_maf, ...)
Will the output plot be 1 mutant vs 9 wildtype or 1 mutant vs 2 wildtype?

Thank you!

**Comment by ShixiangWang** [comment]
@aguardio In your case, I think the answer is **1 mutant vs 9 wildtype**. I used the example code to test this, we can see `48+145=193` which equals the number of samples in clinical data while records in mutation data is 192. 

```
> laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
> laml.clin <- system.file("extdata", "tcga_laml_annot.tsv", package = "maftools")
> laml <- read.maf(maf = laml.maf,  clinicalData = laml.clin)
-Reading
-Validating
-Silent variants: 475 
-Summarizing
-Processing clinical data
-Finished in 0.359s elapsed (1.182s cpu) 
> mafSurvival(maf = laml, genes = 'DNMT3A', time = 'days_to_last_followup', Status = 'Overall_Survival_Status', isTCGA = TRUE)
Looking for clinical data in annoatation slot of MAF..
Number of mutated samples for given genes: 
DNMT3A 
    48 
Median survival..
    Group medianTime   N
1: Mutant        243  48
2:     WT        366 145
Removed 11 samples with NA's

> length(unique(laml@data$Tumor_Sample_Barcode))
[1] 192
> nrow(laml@clinical.data)
[1] 193
```

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. When you read your maf file with clinical data, `read.maf` will only retain those samples for which clinical info is available; rest will be removed. In you case both maf and clinical data will contain 3 samples. Once you generate maf file, you can double check this with `getClinicalData()`.

**Comment by aguardio** [comment]
Right, thank you. So maybe this maf object was created a different way. Because there is definitely more clinical data than mutation annotations.
When I run your example: 
nrow(laml@clinical.data)
I get the total number of clinical data, 290.
But the MAF object only contain annotations for ~100

**Comment by aguardio** [comment]
Here is the preview of the data:
First image is from laml, the second is from my database.
![image](https://user-images.githubusercontent.com/44000045/68086401-82121d80-fe43-11e9-8029-9a0dc0ab15ab.png)


![image](https://user-images.githubusercontent.com/44000045/68086384-63138b80-fe43-11e9-90ef-4105e3c44e9a.png)

So in this case, seeing as the extra samples for which there is only clinical data have not been removed. When I use mafSurvival based on mutations in specific genes, I get all the samples without annotations as "wildtype".

Please let me know if I am misreading the summary of the maf objects, but to me the "factor with x levels" within data tells me how many samples have mutation data. And the clinical data tab says there are 290 samples. Whereas in the laml example both numbers are the same.

Thanks again

**Comment by PoisonAlien** [comment]
I think, your maf object was generated with older version of maftools. You can re read your maf and clinical data and check again if this is reproducible?

**Comment by aguardio** [comment]
Thank you, unfortunately I don't know how the maf object was created. But it is good to know that it is probably an issue with an older version. I will keep this in mind.

Thanks

**Comment by aguardio** [comment]
I extracted the mutations and the clinical data and then re-read the maf and it did ignore the other clinical features. So thank you. It must have been an older version.
