### ISSUE TITLE
mafSurvival how are NA values handled?

### ISSUE THREAD

**Issue by aguardio** [PoisonAlien/maftools#409]
Hello, 
I was going through an analysis which used mafSurvival, the survival data is in this format:
![image](https://user-images.githubusercontent.com/44000045/68196688-db4b8f80-ffb0-11e9-9d2c-35d3e501bb7f.png)

So times are in a different column if the sample is alive or not.
I then combined the two columns so there were no NAs, since the event column tells you about the status of the sample.

The way I have always done survival analysis is by passing in a list of times and a list of binary events. There should be no NA values anywhere, if there are these samples are ignored.

However this analysis did:
mafSurvival(maf_object, times="days_to_death", Status="Event")
The output is this:
![image](https://user-images.githubusercontent.com/44000045/68197020-6462c680-ffb1-11e9-8529-7cd62aa28625.png)

When it says it removed 29 samples with NA's, what does this mean? Does it mean these samples were not used for the survival analysis? I'm confused because Group 1 and Group 2 still have the complete dataset, 17+43=60.

When I run
mafSurvival(maf_object, times="time", Status="Event")
The output is this:
![image](https://user-images.githubusercontent.com/44000045/68197164-adb31600-ffb1-11e9-8335-9dfad6b9a488.png)

WIth the same numbers in each group.

So how does mafSurvival handle the missing / NA values in the days_to_death column?

Thank you!

**Comment by PoisonAlien** [comment]
Hi,
I am sorry for the confusion. It does [remove](https://github.com/PoisonAlien/maftools/blob/master/R/mafSuvival.R#L118) `NA`'s. Its just the median survival printed is [before](https://github.com/PoisonAlien/maftools/blob/master/R/mafSuvival.R#L111) removing NAs, hence it looks the same in both cases. But survival curves will not be affected by any of this. I will correct the issue.

**Comment by PoisonAlien** [comment]
Could you please install the package from GitHub and let me know if the fix helps?

**Comment by aguardio** [comment]
Thank you, and would you agree that the best practice is to use the time column, as it has the most information? i.e. it includes right censored data.

Thanks

**Comment by PoisonAlien** [comment]
I am not an expert in survival analysis, but I do think that best practice is to include censored data. Please do go for a second opinion. Try [stats exchange](https://stats.stackexchange.com/), usually response is quite fast and reliable. 
I am closing this issue for now. Thanks for reporting.
