### ISSUE TITLE
lollipopPlot fails when called with a MAF file containing only 1 protein change

### ISSUE THREAD

**Issue by Dana-Farber** [PoisonAlien/maftools#41]
`
Error in createOncoMatrix(maf, chatty = verbose) :   object 'gene' not found
`

I'm calling the lollipopPlot via
`
laml = read.maf(maf = paste0("../../li_",site,".maf"), removeSilent = T, useAll = F)
l=lollipopPlot(maf = laml, gene = 'TP53', AACol = 'Protein_Change', labelPos = 'all' )
`

The MAF file has only 3 rows: the header, a single data row, a blank row. Duplicating the data row does the trick but messes the diagram because it plots the fictitious point.

**Comment by PoisonAlien** [comment]
Hi,

It appears that you have only one sample in your maf file. Can you add more dummy Tumor Sample Barcodes and see if it works ?

**Comment by Dana-Farber** [comment]
That's what I did. Is the library not supposed to work when you have only 1 sample?!

**Comment by PoisonAlien** [comment]
Yes. With only one sample many functions fail to run, because MAF is assumed to be from a cohort rather than a single sample.
