### ISSUE TITLE
clarification of codes used in TCGA MC3

### ISSUE THREAD

**Issue by Sumithrasank** [PoisonAlien/maftools#410]
I am looking at the clinical data from LUAD using TCGAmutations. Here is my code 
TCGAmutations::tcga_load(study = "LUAD")
tcga_luad_mc3@clinical.data$tobacco_smoking_history
shows 5 levels for this column Levels: 1 2 3 4 5
Could you let me know what category each of the numerical codes belong to e.g Smoker, Non-Smoker etc.
Thanks

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the daly. I just compiled these clinical annotations as is from TCGABiolinks package. I am not sure what these levels mean. Sorry :|

**Comment by ShixiangWang** [comment]
@Sumithrasank  You can google it. I had the same question a year ago and found some useful information.

* Lifelong Non-smoker (less than 100 cigarettes smoked in Lifetime) = 1
* Current smoker (includes daily smokers and non-daily smokers or occasional smokers) = 2
* Current reformed smoker for > 15 years (greater than 15 years) = 3
* Current reformed smoker for ≤15 years (less than or equal to 15 years) = 4
* Current reformed smoker, duration not specified = 5
* Smoking History not documented = 7

![](https://upload-images.jianshu.io/upload_images/3884693-f2a7947c619f1eed.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

> https://groups.google.com/forum/#!topic/cbioportal/irEXZRj9Who

Hope it can help you.
