### ISSUE TITLE
Where can i find integrating variants and copy number alteration?

### ISSUE THREAD

**Issue by a00101** [PoisonAlien/maftools#411]
I find this page, and saw this part '###Integrating somatic variants and copy number alterations'
https://github.com/sbg/maftools

How can I draw this figure?

Thanks in advance.

**Comment by PoisonAlien** [comment]
Hi,
Please refer to the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/oncoplots.html#03_including_copy_number_data_into_oncoplots). They have been well documented.

**Comment by a00101** [comment]
thank you for your answer.
But you misunderstood my question.
please check this fig
https://github.com/PoisonAlien/PoisonAlien.github.io/blob/master/images/image12.png

**Comment by PoisonAlien** [comment]
Oh I see! 
Unfortunately this feature has been deprecated and no longer can be used :|

But if you still like to try, you can install the tool from `pub` branch of GitHub. 

```r
devtools::install_github(repo = "PoisonAlien/maftools", ref = "pub")
```

Note that this brach hasn't been updated from over a year and I am not sure it will work as expected.

**Comment by a00101** [comment]
Can you tell me more about the code you draw figure?

**Comment by PoisonAlien** [comment]
If you install the package from `pub` branch, you will have to run the below command.

```r
tcga.ab.009.seg <- system.file("extdata", "TCGA.AB.3009.hg19.seg.txt", package = "maftools")
plotCBSsegments(cbsFile = tcga.ab.009.seg, maf = laml, labelAll = TRUE)
```

Above function plots copy-number data using CBS segments, and highlights all the mutations from the sample on to it. 

Corresponding vignette is [here](https://github.com/PoisonAlien/maftools/blob/pub/vignettes/maftools.Rmd#L201)
