### ISSUE TITLE
read.maf is broken?

### ISSUE THREAD

**Issue by Sebbyyy** [PoisonAlien/maftools#412]
When I library maftools, I get this error:

`Warning: namespace ‘Biobase’ is not available and has been replaced
by .GlobalEnv when processing object ‘libPaths’
Warning: namespace ‘Biobase’ is not available and has been replaced
by .GlobalEnv when processing object ‘libPaths’`

I think this is why read.maf isn't working as previous mafs I have easily read are coming up with errors:

`-Reading
-Validating
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  : 
  missing required fields from MAF: Hugo_Symbol`

My file definitely has that column. I checked on previously read mafs and they now give the same error

session info:
`R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] maftools_2.0.10    BiocManager_1.30.9 nlme_3.1-141       cluster_2.1.0      reshape2_1.4.3     forcats_0.4.0     
 [7] stringr_1.4.0      dplyr_0.8.3        purrr_0.3.3        readr_1.3.1        tidyr_1.0.0        tibble_2.1.3      
[13] ggplot2_3.2.1      tidyverse_1.2.1   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         lubridate_1.7.4    lattice_0.20-38    assertthat_0.2.1   zeallot_0.1.0      digest_0.6.22     
 [7] packrat_0.5.0      foreach_1.4.7      gridBase_0.4-7     R6_2.4.1           cellranger_1.1.0   plyr_1.8.4        
[13] backports_1.1.5    httr_1.4.1         pillar_1.4.2       rlang_0.4.1        lazyeval_0.2.2     readxl_1.3.1      
[19] rstudioapi_0.10    data.table_1.12.6  Matrix_1.2-17      splines_3.6.1      munsell_0.5.0      broom_0.5.2       
[25] compiler_3.6.1     modelr_0.1.5       pkgconfig_2.0.3    pkgmaker_0.27      tidyselect_0.2.5   codetools_0.2-16  
[31] crayon_1.3.4       withr_2.1.2        grid_3.6.1         jsonlite_1.6       xtable_1.8-4       gtable_0.3.0      
[37] lifecycle_0.1.0    registry_0.5-1     magrittr_1.5       scales_1.0.0       bibtex_0.4.2       cli_1.1.0         
[43] stringi_1.4.3      doParallel_1.0.15  xml2_1.2.2         generics_0.0.2     vctrs_0.2.0        wordcloud_2.6     
[49] RColorBrewer_1.1-2 NMF_0.21.0         iterators_1.0.12   tools_3.6.1        glue_1.3.1         hms_0.5.2         
[55] rngtools_1.4       parallel_3.6.1     survival_3.1-7     colorspace_1.4-1   rvest_0.3.5        haven_2.1.1  `

**Comment by Sebbyyy** [comment]
Biobase had to be separately installed now when previously it did not.

**Comment by PoisonAlien** [comment]
Hello,
Its definitely not related to biobase. It seems you;re still using a bit older version. Could you may be try to update the package and try again?

**Comment by Sebbyyy** [comment]
@PoisonAlien 
this is with maftools 2.0.16

Still unable to find Hugo_Symbol in this maf.

But fread -> read.maf works?

**Comment by PoisonAlien** [comment]
Is it possible to share a sample set? Maybe top 100 rows?

**Comment by ShixiangWang** [comment]
Does it work for the example maf file provided by maftools?

**Comment by Sebbyyy** [comment]
@PoisonAlien 

[sample.xlsx](https://github.com/PoisonAlien/maftools/files/3856399/sample.xlsx)

@ShixiangWang 

Yes it does. There seems to be something broken in the file about the Hugo_Symbol but I cannot figure what. Even the sample with only 100 rows, it does not work.

**Comment by ShixiangWang** [comment]
@Sebbyyy It looks fine for me. Could you upgrade your maftools and run the same commands to take a look?

```
> library(readxl)
> library(maftools)
> maf = read_excel("sample.xlsx")
                                                                                                                                     
> maf = read.maf(maf)
-Validating
-Silent variants: 37 
-Summarizing
-Processing clinical data
--Missing clinical data
-Finished in 0.062s elapsed (0.201s cpu) 
> devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  zh_CN.UTF-8                 
 ctype    zh_CN.UTF-8                 
 tz       Asia/Shanghai               
 date     2019-11-18                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version  date       lib source        
 assertthat     0.2.1    2019-03-21 [1] CRAN (R 3.6.0)
 backports      1.1.5    2019-10-02 [1] CRAN (R 3.6.0)
 callr          3.3.2    2019-09-22 [1] CRAN (R 3.6.0)
 cellranger     1.1.0    2016-07-27 [1] CRAN (R 3.6.0)
 cli            1.1.0    2019-03-19 [1] CRAN (R 3.6.0)
 crayon         1.3.4    2017-09-16 [1] CRAN (R 3.6.0)
 data.table     1.12.6   2019-10-18 [1] CRAN (R 3.6.0)
 desc           1.2.0    2018-05-01 [1] CRAN (R 3.6.0)
 devtools       2.2.1    2019-09-24 [1] CRAN (R 3.6.0)
 digest         0.6.22   2019-10-21 [1] CRAN (R 3.6.0)
 ellipsis       0.3.0    2019-09-20 [1] CRAN (R 3.6.0)
 fs             1.3.1    2019-05-06 [1] CRAN (R 3.6.0)
 glue           1.3.1    2019-03-12 [1] CRAN (R 3.6.0)
 lattice        0.20-38  2018-11-04 [2] CRAN (R 3.6.1)
 maftools     * 2.2.0    2019-10-29 [1] Bioconductor  
 magrittr       1.5      2014-11-22 [1] CRAN (R 3.6.0)
 Matrix         1.2-17   2019-03-22 [2] CRAN (R 3.6.1)
 memoise        1.1.0    2017-04-21 [1] CRAN (R 3.6.0)
 packrat        0.5.0    2018-11-14 [1] CRAN (R 3.6.0)
 pacman       * 0.5.1    2019-03-11 [1] CRAN (R 3.6.0)
 pillar         1.4.2    2019-06-29 [1] CRAN (R 3.6.0)
 pkgbuild       1.0.6    2019-10-09 [1] CRAN (R 3.6.0)
 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 3.6.0)
 pkgload        1.0.2    2018-10-29 [1] CRAN (R 3.6.0)
 prettyunits    1.0.2    2015-07-13 [1] CRAN (R 3.6.0)
 processx       3.4.1    2019-07-18 [1] CRAN (R 3.6.0)
 ps             1.3.0    2018-12-21 [1] CRAN (R 3.6.0)
 R6             2.4.0    2019-02-14 [1] CRAN (R 3.6.0)
 RColorBrewer   1.1-2    2014-12-07 [1] CRAN (R 3.6.0)
 Rcpp           1.0.2    2019-07-25 [1] CRAN (R 3.6.0)
 readxl       * 1.3.1    2019-03-13 [1] CRAN (R 3.6.0)
 remotes        2.1.0    2019-06-24 [1] CRAN (R 3.6.0)
 rlang          0.4.1    2019-10-24 [1] CRAN (R 3.6.0)
 rprojroot      1.3-2    2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi     0.10     2019-03-19 [1] CRAN (R 3.6.0)
 sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
 survival       2.44-1.1 2019-04-01 [2] CRAN (R 3.6.1)
 testthat       2.2.1    2019-07-25 [1] CRAN (R 3.6.0)
 tibble         2.1.3    2019-06-06 [1] CRAN (R 3.6.0)
 usethis        1.5.1    2019-07-04 [1] CRAN (R 3.6.0)
 withr          2.1.2    2018-03-15 [1] CRAN (R 3.6.0)
 wordcloud      2.6      2018-08-24 [1] CRAN (R 3.6.0)

[1] /Users/wsx/R_library
[2] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

**Comment by Sebbyyy** [comment]
@ShixiangWang 

Worked for me if I import the csv/xlsx first into R instead of trying to read a maf straight into R.

Never had problem before.

I am unable to update my maftools past 2.0.16 through bioconductor though. Just deleted it and reinstalled.

`- Session info -------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Australia.1252      
 ctype    English_Australia.1252      
 tz       Australia/Brisbane          
 date     2019-11-18                  

- Packages -----------------------------------------------------------------------------------------------------------------------
 package      * version date       lib source        
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports      1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
 bibtex         0.4.2   2017-06-30 [1] CRAN (R 3.6.0)
 Biobase      * 2.44.0  2019-05-02 [1] Bioconductor  
 BiocGenerics * 0.30.0  2019-05-02 [1] Bioconductor  
 BiocManager    1.30.10 2019-11-16 [1] CRAN (R 3.6.1)
 callr          3.3.2   2019-09-22 [1] CRAN (R 3.6.1)
 cli            1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
 cluster        2.1.0   2019-06-19 [1] CRAN (R 3.6.0)
 codetools      0.2-16  2018-12-24 [2] CRAN (R 3.6.1)
 colorspace     1.4-1   2019-03-18 [1] CRAN (R 3.6.0)
 crayon         1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 data.table     1.12.6  2019-10-18 [1] CRAN (R 3.6.1)
 desc           1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
 devtools     * 2.2.1   2019-09-24 [1] CRAN (R 3.6.1)
 digest         0.6.22  2019-10-21 [1] CRAN (R 3.6.1)
 doParallel     1.0.15  2019-08-02 [1] CRAN (R 3.6.1)
 dplyr          0.8.3   2019-07-04 [1] CRAN (R 3.6.1)
 ellipsis       0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
 foreach        1.4.7   2019-07-27 [1] CRAN (R 3.6.0)
 fs             1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
 ggplot2        3.2.1   2019-08-10 [1] CRAN (R 3.6.1)
 glue           1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
 gridBase       0.4-7   2014-02-24 [1] CRAN (R 3.6.0)
 gtable         0.3.0   2019-03-25 [1] CRAN (R 3.6.0)
 installr     * 0.22.0  2019-08-02 [1] CRAN (R 3.6.1)
 iterators      1.0.12  2019-07-26 [1] CRAN (R 3.6.0)
 lattice        0.20-38 2018-11-04 [2] CRAN (R 3.6.1)
 lazyeval       0.2.2   2019-03-15 [1] CRAN (R 3.6.0)
 maftools     * 2.0.16  2019-08-14 [1] Bioconductor  
 magrittr       1.5     2014-11-22 [1] CRAN (R 3.6.0)
 Matrix         1.2-17  2019-03-22 [2] CRAN (R 3.6.1)
 memoise        1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
 munsell        0.5.0   2018-06-12 [1] CRAN (R 3.6.0)
 NMF            0.21.0  2018-03-06 [1] CRAN (R 3.6.0)
 packrat        0.5.0   2018-11-14 [1] CRAN (R 3.6.0)
 pillar         1.4.2   2019-06-29 [1] CRAN (R 3.6.0)
 pkgbuild       1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
 pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 3.6.1)
 pkgload        1.0.2   2018-10-29 [1] CRAN (R 3.6.1)
 pkgmaker       0.27    2018-05-25 [1] CRAN (R 3.6.0)
 plyr           1.8.4   2016-06-08 [1] CRAN (R 3.6.0)
 prettyunits    1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
 processx       3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
 ps             1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
 purrr          0.3.3   2019-10-18 [1] CRAN (R 3.6.1)
 R6             2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
 RColorBrewer   1.1-2   2014-12-07 [1] CRAN (R 3.6.0)
 Rcpp           1.0.3   2019-11-08 [1] CRAN (R 3.6.1)
 registry       0.5-1   2019-03-05 [1] CRAN (R 3.6.0)
 remotes        2.1.0   2019-06-24 [1] CRAN (R 3.6.1)
 reshape2       1.4.3   2017-12-11 [1] CRAN (R 3.6.0)
 rlang          0.4.1   2019-10-24 [1] CRAN (R 3.6.1)
 rngtools       1.4     2019-07-01 [1] CRAN (R 3.6.1)
 rprojroot      1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi     0.10    2019-03-19 [1] CRAN (R 3.6.0)
 scales         1.0.0   2018-08-09 [1] CRAN (R 3.6.0)
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
 stringi        1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
 stringr      * 1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
 survival       3.1-7   2019-11-09 [2] CRAN (R 3.6.1)
 testthat       2.3.0   2019-11-05 [1] CRAN (R 3.6.1)
 tibble         2.1.3   2019-06-06 [1] CRAN (R 3.6.0)
 tidyselect     0.2.5   2018-10-11 [1] CRAN (R 3.6.0)
 usethis      * 1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
 withr          2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
 wordcloud      2.6     2018-08-24 [1] CRAN (R 3.6.0)
 xtable         1.8-4   2019-04-21 [1] CRAN (R 3.6.0)

[1] C:/Users/Sebastian Walpole/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.1/library`

**Comment by ShixiangWang** [comment]
@Sebbyyy I got your point.

You did the following commands to read MAF file?

```
> library(maftools)
> maf = read.maf("sample.xlsx")
-Reading
Error in data.table::fread(input = maf, sep = "\t", stringsAsFactors = FALSE,  : 
  skip='Hugo_Symbol' not found in input (it is case sensitive and literal; i.e., no patterns, wildcards or regex)
```

This is not an issue related to maftools package.

As the document from https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/ described,

> Mutation Annotation Format (MAF) is a **tab-delimited** text file with aggregated mutation information from VCF Files and are generated on a project-level

You misunderstand the file format. When the input is a file path, `read.maf()` will read it by `data.table::fread()` with `sep='\t'`. It cannot be used to read xlsx and CSV file, only the TSV file is accepted.

I don't know why you can't upgrade your maftools, maybe you need to upgrade Bioconductor version before upgrading maftools.

The latest version of Bioconductor is 3.10, you can check it with:

```
> BiocManager::version()
[1] ‘3.10’
```

**Comment by Sebbyyy** [comment]
@ShixiangWang 

That is not the error I get.

`-Reading -Validating Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants, : missing required fields from MAF: Hugo_Symbol`

It is not an fread error. As fread can read the csv then parse the object through read.maf


Had to uninstall all packages related to Bioconductor weirdly for it to update from 3.9 -> 3.10 which allowed maftools to be updated.

**Comment by ShixiangWang** [comment]
So why you get error with csv file but upload a excel file for testing? You can install latest version directly from GitHub.

**Comment by PoisonAlien** [comment]
Hi @Sebbyyy ,
do not use excel files as input. R is not really good at reading them (without specific libraries). Please try to stick with `tsv` files. If you want you can `gz` compress them.

**Comment by Sebbyyy** [comment]
@ShixiangWang @PoisonAlien 
That was purely a github issue. It only allowed an xlsx file when I tried to attach the csv file.

I try to exclusively use CSVs.

Sorry about that.

**Comment by PoisonAlien** [comment]
No worries. Please do let us know if you have other issues. Please close this issue if you feel it has been answered.

**Comment by ShixiangWang** [comment]
@Sebbyyy I see. As @PoisonAlien mentioned, please just use TSV file for maftools.
