### ISSUE TITLE
Feature request: oncodrive return altered sample IDs

### ISSUE THREAD

**Issue by ShixiangWang** [PoisonAlien/maftools#413]
Dear @PoisonAlien,

I tried `oncodrive()` function today. I want to get the samples the driver exists, I found the function returns a column called `AlteredSamples`, so I think it is possible. Could you add this feature?

Best,
Shixiang

**Comment by PoisonAlien** [comment]
Hi @ShixiangWang 
Actually you can run `genesToBarcodes` on genes of interest (in this case driver gene) and it should the job.

**Comment by ShixiangWang** [comment]
I got it, thanks :).
