### ISSUE TITLE
Question about could not find function "mafSurvGroup"

### ISSUE THREAD

**Issue by ravinsit06** [PoisonAlien/maftools#414]
Hello I was trying to see the genes which associated with poor survival but it gave the error that could not find Survgroup when I run the command.
prog_geneset = survGroup(maf = laml, top = 20, geneSetSize = 2, time = "days_to_last_followup", Status = "Overall_Survival_Status", verbose = FALSE).

Can somebody help me in rectifying this issue

**Comment by ShixiangWang** [comment]
you have to install the latest version of this package

**Comment by ravinsit06** [comment]
Thank you ShixiangWang I updated it and its working fine.

**Comment by ShixiangWang** [comment]
You are welcome.
