### ISSUE TITLE
somaticInteractions Flexibility To Show Counts

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#418]
I would like to be able to plot counts of instead of negative log p-value by setting an option. The number could be inside the cell in the heatmap, to avoid too many colours in the colour scale.

**Comment by PoisonAlien** [comment]
This is a nice idea. I will follow up on it, and what numbers would be inside the cells? Number of exclusive/co-occurring events?

**Comment by PoisonAlien** [comment]
Okay I have pushed some changes with more flexibility on display. 
Below command shows counts of events (occurring/mut-exclusive) for significant pairs. 

```r
somaticInteractions(maf = laml, top = 10, showCounts = TRUE, showSigSymbols = FALSE)
```

These can be further customised with arguments `showCounts` `countstats` `countType`. Please try them and let me know.

**Comment by DarioS** [comment]
It looks nice. But I see NA values in the plot.

![image](https://user-images.githubusercontent.com/631218/69500640-e448d480-0f50-11ea-9650-5dd51b0b4002.png)

Also, it would be more consistent if `countstats` was `countStats` to have the same style as other parameters.

**Comment by PoisonAlien** [comment]
Those `NA` are zero counts. I could have replaced them with zeros but for some reason I wasn't comfortable. I will fix it.
