### ISSUE TITLE
somaticInteractions Uses Anti-conservative Fisher's Exact Test

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#419]
The test is anti-conservative because it makes assumptions about independence

> A commonly used test for both co-occurrence and mutual exclusivity is Fisher’s exact test applied to a 2×2 contingency table. The validity of this test depends on the assumption that genes’ alterations across tumours are independent and identically distributed (i.i.d.).

Discrete Independence Statistic Controlling for Observations with Varying Event Rates (DISCOVER) is a solution to the problem published in [Genome Biology in 2016](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1114-x). There is an R package implementing it. Could it be an option - perhaps even the default - for `somaticInteractions`?

**Comment by PoisonAlien** [comment]
Package seems to be not on CRAN/Bioconductor and this might be an issue on making it as a dependency :|

**Comment by DarioS** [comment]
Damn, DISCOVER is awful. Remarkably, there aren't any manual pages for the functions. It's a shame the developers of it don't care about software development like you do!

**Comment by PoisonAlien** [comment]
Closing this issue for now.
