### ISSUE TITLE
lollipopPlot does not render correctly close lollipops

### ISSUE THREAD

**Issue by Dana-Farber** [PoisonAlien/maftools#42]
![screen shot 2017-02-20 at 9 01 52 pm](https://cloud.githubusercontent.com/assets/25375373/23147829/fdbf5eea-f7af-11e6-9069-eb514d857c1a.png)

There are respectively 
`
p.S37F count=13;
p.D32Y count=12;
p.S33F count=11;
p.T41I count=10;
p.G34E count=9;
`
Those with counts <=10 are rendered correctly, after that the 11, 12 and 13 are messed up.

**Comment by PoisonAlien** [comment]
Yeah, I am aware of this and its something I am working on currently (and also to fix domain sizes which often changes if mutation load is high). Meanwhile, can you try setting `repel=TRUE` and see if it works for you ? Its a naive method, so plot might not look pretty!

**Comment by PoisonAlien** [comment]
Hi,

I have pushed a fix to lollipop plot along with several improvements. Can you give it a try and let me know ? Install it from Github. Naming closely spaced variants is still little bit tricky, but clustering is taken care of with proper scaling of y-axis.
