### ISSUE TITLE
somaticInteractions Excessive Top Margin

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#420]
I see plots like below on Debian 9 and Windows 10 in a new R session.

![image](https://user-images.githubusercontent.com/631218/69127045-9a4d9200-0afd-11ea-93f7-d284561cf928.png)

Curiously, the plot in the vignette looks fine.

**Comment by PoisonAlien** [comment]
How does it look when you save it to a pdf of proper dimension?

**Comment by DarioS** [comment]
Also has enormous margins.
