### ISSUE TITLE
read.maf fails due to 'Hugo_Symbol' not found in input 

### ISSUE THREAD

**Issue by omarwagih** [PoisonAlien/maftools#421]
I get this error trying to load a maf file downloaded from https://github.com/mcfrith/last-genome-alignments

Is the MAF mis-formated somehow?

```
> x = read.maf('~/Downloads/hg38-mm10-2.maf.gz')
-Reading
Error in data.table::fread(cmd = paste("zcat <", maf), sep = "\t", stringsAsFactors = FALSE,  : 
  skip='Hugo_Symbol' not found in input (it is case sensitive and literal; i.e., no patterns, wildcards or regex)
```

**Comment by PoisonAlien** [comment]
Hi,
I am afraid that the file you are trying to read is `Multiple Alignment Format`. This tool is intended to process `Mutation Annotation Format` files. Sorry for the acronym discrepancies.
