### ISSUE TITLE
import clinical data?

### ISSUE THREAD

**Issue by AngelaDaddyRoy** [PoisonAlien/maftools#422]
hello
I recently use maftools analyzing TCGA-COAD samples, just have no idea how to prepare clinical data.
after downloading maf file and clinical supplements data , I tried to make my own clinical table as simple as this:

Tumor_Sample_Barcode | stage
-- | --
TCGA-3L-AA1B | Stage I
TCGA-4N-A93T | Stage IIIB
TCGA-4T-AA8H | Stage IIA
TCGA-5M-AAT4 | Stage IV
TCGA-5M-AAT6 | Stage IV
TCGA-5M-AATE | Stage IIA
TCGA-A6-2670 | Stage IIA
TCGA-A6-2671 | Stage IV
TCGA-A6-2672 | Stage IIIB
TCGA-A6-2674 | Stage IV
TCGA-A6-2675 | Stage IIA
TCGA-A6-2676 | Stage IIB

this file was extracted from TCGA clinical supplements data
then I readed the maf:
```
coad <- read.maf(maf ="./TCGA.COAD.muse.70cb1255-ec99-4c08-b482-415f8375be3f.DR-10.0.somatic.maf.gz",clinicalData = "./coad-clinical.csv")
```
however ,the `coad@clinical.data` keeps emtpy
```
> coad@clinical.data
Empty data.table (0 rows and 2 cols): Tumor_Sample_Barcode,stage
```
how can get/download mafs clinical data?

**Comment by ShixiangWang** [comment]
Please set `isTCGA=TRUE` and take a try.

![image](https://user-images.githubusercontent.com/25057508/69474087-2100b880-0df7-11ea-90e5-880afed19a3e.png)

**Comment by AngelaDaddyRoy** [comment]
thanks，I realized it's the  "Short/Long" barcode issue. after changing my barcode from "TCGA-XX-XXXX" to "TCGA-XX-XXXX-XX-XX-XXXX" solves the problem, set isTCGA not working in my case, thanks for the reply.
