### ISSUE TITLE
Legend Ordering Not Intuitive

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#424]
I am using the options `sortByAnnotation = TRUE`, `groupAnnotationBySize = FALSE` and `annotationOrder = c(1:4, "NA")` and the samples in the heatmap are plotted in a desirable order. However, the clinical legend is in an unappealing, seemingly random order.

![image](https://user-images.githubusercontent.com/631218/69510258-45dc6380-0f90-11ea-9c3c-bf4770214834.png)

**Comment by PoisonAlien** [comment]
Now the legends are sorted with `NA` last.
