### ISSUE TITLE
lollipopPlot for mouse genome

### ISSUE THREAD

**Issue by t-neumann** [PoisonAlien/maftools#425]
Hi,

I am using `maftools` now to also visualize mouse exome data.

I wanted to use the `lollipopPlot` function to visualize AA changes, but from what I can tell it will only work with human annotations. Is there any way to get it to run on mouse genes?

**Comment by PoisonAlien** [comment]
Hi,
At the moment maftools uses a file with hardcoded domain structures for human proteins. I have not compiled such file for mouse genes. If you still want to draw, you can convert your gene symbols to upper case (e.g, `Brca` to `BRCA`) under `Hugo_Symbol` column, and try. But I do not know how valid this approach (depends on how the domains are conserved between two species).

**Comment by t-neumann** [comment]
Ok that did not work out - I now manually created lolliplots.
