### ISSUE TITLE
Creating subset of maf files

### ISSUE THREAD

**Issue by agustin-guardiola** [PoisonAlien/maftools#426]
Hey, 
I'm wondering if there is a built in or easy way of creating a subset of a maf object.

I thought when I used
read.maf() with a full maf object and a subset of samples in the clinical data argument
the result would be just the samples that appear in both clinical and maf arguments.
But it only blocks the samples that appear in clinical but have no annotations.

For clarity, I want to create a maf object of the intersection in the venn diagram.
I know I could do this manually, just wondering if there is a faster way.

![Untitled Diagram (2)](https://user-images.githubusercontent.com/57628802/69532434-b58d2700-0f6d-11ea-8337-d06a02616219.png)

I want to use functions like oncodrive in only a subset of the full maf object to look for discrepancies.

Thank you

**Comment by PoisonAlien** [comment]
Hi,
`read.maf` would retain all the samples irrespective of clinical data. However there is a function called `subsetMaf` which might be of helpful in this case. You can pass tumor sample barcodes of interest (in this case samples for which annotation available) to get a subsetted version of original maf. I hope this helps.

**Comment by agustin-guardiola** [comment]
Yes that's perfect, it seemed like a feature that would be somewhere, just didn't know where.

Thanks!

**Comment by PoisonAlien** [comment]
Oh, also there is a vignette [entry](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#111_subsetting_maf) for subset operations in case you need more information.
