### ISSUE TITLE
Is it possible to extract information about which mutations are in each cluster found by oncodrive?

### ISSUE THREAD

**Issue by agustin-guardiola** [PoisonAlien/maftools#427]
Can I easily extract which mutations are within each of the clusters in each of the genes. 
For example if the oncodrive results say there are 35 mutations in clusters and there are 3 clusters, can extract each cluster and its contents?

Thanks

**Comment by PoisonAlien** [comment]
This unfortunately cant be done for now. But I am happy to implement it.

**Comment by agustin-guardiola** [comment]
Thanks, I think it would be interesting.
