### ISSUE TITLE
removeNonMutated function is not showing non-mutated samples

### ISSUE THREAD

**Issue by carladosanjos** [PoisonAlien/maftools#428]
Dear Anand,

I have a file with clinical features and the main maf file, but some samples are not in the maf file because they don't have mutations. So, I am trying to display all the samples (mutated and non-mutated) using 'oncoplot' function with 'removeNonMutated = FALSE' argument, but the non-mutated samples does not show up in the plot - no error displayed. I also tried the 'fill = TRUE' argument, but it hasn't work either.

Would you please let me know how to include non-mutated samples using oncoplot?

Best wishes,

Carla

**Comment by PoisonAlien** [comment]
Hi Clara,
These samples with no mutation - do they still have any synonymous mutations, like intergenic/intronic? If the sample name itself is not in maf file then it wont show up in the plot. A simple workaround would be to add some dummy intronic variants and assign them to these missing samples. It should work.
