### ISSUE TITLE
math.score numeric error

### ISSUE THREAD

**Issue by t-neumann** [PoisonAlien/maftools#429]
Hi,

I'm trying to use the `math.score` function, but it throws me an error:

```
math.score(maf,vafCol="VAF")
Error in vaf - median(vaf) : non-numeric argument to binary operator
```

I don't know where this is happening, since originally it looks like you are converting the `t_vaf` column into something numeric anyways before that step.

**Comment by PoisonAlien** [comment]
Can you try now?

**Comment by t-neumann** [comment]
Thx - works!

**Comment by AMLove628** [comment]
I'm having a similar issue with MATH.score. 

> math.score(maf = PCAgz, vafCutOff = 0.075)
t_vaf field is missing, but found t_ref_count & t_alt_count columns. Estimating vaf..
Error in t_ref_count + t_alt_count : 
  non-numeric argument to binary operator

**Comment by PoisonAlien** [comment]
Hello @AMLove628 
Sorry for the delay. I have fixed the issue now. Could you please try again and let me know if this helps? You will have to install from GitHub.

**Comment by AMLove628** [comment]
Aye! Thank you.
I will try Tuesday!

**Comment by AMLove628** [comment]
Math.Score works now! Thank you!
I'm curious if there is a simple way to filter MAFs using tumor sample barcode. I have 186 samples that I'm interested in pulling out and analyzing separately.
