### ISSUE TITLE
Error in lollipopPlot

### ISSUE THREAD

**Issue by vmurigneu** [PoisonAlien/maftools#43]
Hi, 
I am getting an error when trying to use the lollipopPlot function for certain genes. It is working well for some genes.  
Here is the command :
FOXO1.lpop = lollipopPlot(maf = laml, gene = 'FOXO1', AACol = 'amino_acid_change',labelPos="all")
Error in FUN(X[[i]], ...) : subscript out of bounds

Thanks for your help,
Valentine

**Comment by PoisonAlien** [comment]
For these genes with the problem, how is protein changes are represented ? Are they HGVSp or HGSVSp_Short (ex. p.L2195Pfs*30 or p.Leu2195ProfsTer30)?

**Comment by vmurigneu** [comment]
I think none of them. The protein changes are coming from Snpeff: ex p.A486G

**Comment by PoisonAlien** [comment]
Yes, thats HGSVSp_Short. This error was not suppose to occur. Can you paste some example conversions for genes with this error ?

**Comment by vmurigneu** [comment]
It looks like I got an error only when the protein change is equals to "p.". See below: 
MEF2B	.	UQCCG	hs37d5	19	19258521	19258521	.	Nonsense_Mutation	SNP	G	A	A	Unknown	Untested	Somatic	.	S15	p.	ENSG00000213999	ENST00000410050	HIGH	373	159	532

**Comment by PoisonAlien** [comment]
Oh. This is an issue with annotation itself, so only way is to correct them. I quickly checked annotation for above variant and it looks like, conversion should be `p.Arg127*` (See here: http://portals.broadinstitute.org/oncotator/report/884cbf99bf1b30453a96d2913a40f382)

**Comment by vmurigneu** [comment]
yes I used a previous script from my team and never realized the conversion was not good for variants with a stop_gained.
Thanks for your help !
