### ISSUE TITLE
Converting annovar annotation to maf

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#430]
Hello

Thank you for your nice software

Sorry, I have a bunch of annovar annotated .vfc files (.txt now). I want to convert them to maf by annovarToMaf

I know for each of them I should do

```
> var.annovar = system.file("extdata", "annovar.txt", package = "maftools")
> var.annovar.maf2=annovarToMaf(annovar=var.annovar, Center = NULL, refBuild = "hg19", tsbCol = NULL,
+              table = "refGene",, basename = NULL, sep = "\t",
+              MAFobj = FALSE)
```

Is there anyway to convert them all together or simultaneously to maf because one by one seems painful

Thank you for any help

**Comment by PoisonAlien** [comment]
You dont have to convert them one by one. Just pass them all to `annovar` argument. It will read them all and outputs an `maf` object.

```r
var.annovar = c("foo1.annovar.txt", "foo2.annovar.txt", 'foo3.annovar.txt)
annovarToMaf(annovar = var.annovar)
```

**Comment by beginner984** [comment]
Thank you to be so responding 

If I have more than 100 files .txt suffix like file.txt, is there anyway to put all at the same time in var.annovar  object without having to put their name one by one in a vector?

**Comment by PoisonAlien** [comment]
Yeah, you can do that. Take a look at [list.files](https://www.math.ucla.edu/~anderson/rw1001/library/base/html/list.files.html) function. It returns list of files with file extension of your choice.
