### ISSUE TITLE
Clinical Data Download Fails on Windows

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#431]
On Windows computer (in office, Windows 7 32-bit)

```r
> GDCdownload(clinical)
Downloading data for project TCGA-HNSC
trying URL 'https://gdc.cancer.gov/system/files/authenticated%20user/0/gdc-client_v1.4.0_Windows_x64.zip'
Content type 'application/zip' length 16374028 bytes (15.6 MB)
downloaded 15.6 MB

GDCdownload will download: 167.697538 MB
Executing GDC client with the following command:
H:\Windows\Documents\gdc-client.exe download -m gdc_manifest.txt
Error in move(i, file.path(path, i)) : 
  I could not find the file: 52398f96-f15d-4468-bfc3-9692a1fb006f
```

On Debian computer

```r
> GDCdownload(clinical)
Downloading data for project TCGA-HNSC
GDCdownload will download 8 files. A total of 942.121 KB
Downloading as: Tue_Dec__3_16_11_23_2019.tar.gz
Downloading: 150 kB
```

I seem to get the right data on Debian. Why does it install software and try to download 167 MB instead of 942 KB?

**Comment by ShixiangWang** [comment]
This is not an issue related to this package. You can report it at https://github.com/BioinformaticsFMRP/TCGAbiolinks/issues

**Comment by PoisonAlien** [comment]
Yup. TCGAbiolinks would be a proper place for this. 
CC @tiagochst

**Comment by DarioS** [comment]
Oops, trying to do too much before running out of the office. Would be good to be able to move it to TCGAbiolinks but Tiago has been notified so here is O.K., too.
