### ISSUE TITLE
Getting error in finding mutational signatures

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#437]
Hi

Sorry

I am trying to find mutational signature but I am getting error

Can you help please?

```
> laml.tnm = trinucleotideMatrix(maf = laml, prefix = 'chr', add = FALSE, ref_genome = "BSgenome.Hsapiens.UCSC.hg19")
Warning in trinucleotideMatrix(maf = laml, prefix = "chr", add = FALSE,  :
  Chromosome names in MAF must match chromosome names in reference genome.
Ignorinig 3349731 single nucleotide variants from missing chromosomes 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, X, 21, 22, Y, M
Error in trinucleotideMatrix(maf = laml1, prefix = "chr", add = FALSE,  : 
  Zero SNPs to analyze! Maybe add or remove prefix?
> laml.tnm = trinucleotideMatrix(maf = laml, prefix = 'chr', add = TRUE, ref_genome = "BSgenome.Hsapiens.UCSC.hg19")
Warning in trinucleotideMatrix(maf = laml, prefix = "chr", add = TRUE,  :
  Chromosome names in MAF must match chromosome names in reference genome.
Ignorinig 3349731 single nucleotide variants from missing chromosomes chrchr1, chrchr2, chrchr3, chrchr4, chrchr5, chrchr6, chrchr7, chrchr8, chrchr9, chrchr10, chrchr11, chrchr12, chrchr13, chrchr14, chrchr15, chrchr16, chrchr17, chrchr18, chrchr19, chrchr20, chrchrX, chrchr21, chrchr22, chrchrY, chrchrM
Error in trinucleotideMatrix(maf = laml1, prefix = "chr", add = TRUE,  : 
  Zero SNPs to analyze! Maybe add or remove prefix?
```
This is the link to my maf object

https://www.dropbox.com/s/kw3bljcy5rayl2s/laml.rds?dl=0

Sorry to bothering you

**Comment by PoisonAlien** [comment]
Hi,
Please refer to the help page for `?trinucleotideMatrix()` for usage details. Argument `prefix` should be used when the naming convention for chromosome differs between maf and BSgenome object. Here it appears that your chromosome names in your maf file are in UCSC style i.e, with `chr` prefix. You are using `BSgenome.Hsapiens.UCSC.hg19` object which also has `chr` prefix. So you dont have to add/remove any prefixes. Below command works for me..

```r
> laml = readRDS(file = "~/Downloads/laml.rds")
> library(BSgenome.Hsapiens.UCSC.hg19)
> laml_tnm = trinucleotideMatrix(maf = laml, ref_genome = BSgenome.Hsapiens.UCSC.hg19)
-Extracting 5' and 3' adjacent bases
-Extracting +/- 20bp around mutated bases for background C>T estimation
-Estimating APOBEC enrichment scores
--Performing one-way Fisher's test for APOBEC enrichment
---APOBEC related mutations are enriched in  5.755 % of samples (APOBEC enrichment score > 2 ;  8  of  139  samples)
-Creating mutation matrix
--matrix of dimension 139x96
```

**Comment by beginner984** [comment]
Thank you

Sorry is it possible that I don't have any signature in my because I am getting this

```
> library('NMF')
> laml.sign = estimateSignatures(mat = laml_tnm, nTry = 4)
-Running NMF for 4 ranks
-Finished in 00:02:09 elapsed (13.5s cpu) 
> #Compate against original 30 signatures 
> laml.og30.cosm = compareSignatures(nmfRes = laml.sig, sig_db = "legacy")
Error in 1:ncol(w) : argument of length 0
```

I also tried for another signature 

```
> laml.v3.cosm = compareSignatures(nmfRes = laml.sig, sig_db = "SBS")
Error in 1:ncol(w) : argument of length 0
```

In my sig file however I have 2 mutation with FDR < 0.05

**Comment by PoisonAlien** [comment]
Hi, 
Please read the [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/maftools.html#9113_signature_analysis) regarding signature analysis. `estimateSignatures` is a function which gives you an idea of how many possible signature you might expect in your data. Once you have this number, you will have to run `extractSignatures` - results of which can be passed to `compareSignatures`.

**Comment by beginner984** [comment]
Hi

I found was the problem; In vignete there is no `extractSignatures `code line so I found that in document :)

```
> laml.sign <- extractSignatures(mat = laml.tnm, plotBestFitRes = FALSE,n=3)
-Running NMF for factorization rank: 3
-Finished in3.230s elapsed (3.240s cpu)
> laml.og30.cosm = compareSignatures(nmfRes = laml.sign, sig_db = "legacy")
-Comparing against COSMIC signatures
------------------------------------
--Found Signature_1 most similar to COSMIC_6
   Aetiology: defective DNA mismatch repair [cosine-similarity: 0.909]
--Found Signature_2 most similar to COSMIC_17
   Aetiology: Unknown [cosine-similarity: 0.986]
--Found Signature_3 most similar to COSMIC_8
   Aetiology: Unknown [cosine-similarity: 0.775]
```
------------------------------------

**Comment by PoisonAlien** [comment]
Yes, you were right. I will fix it soon. Please accept my apologies, and thanks for reporting.

**Comment by beginner984** [comment]
Not at all

To be honest I must be so thankful for developing such an amazing software

**Comment by Usamahussein551980** [comment]
Hi there,
Thank you for the amazing tool.

I got the following error and failed to resolve it, could you please guide me to solve it?

> dbcl.tnm = trinucleotideMatrix(maf = dbcl, ref_genome = "BSgenome.Hsapiens.UCSC.hg19")
-Extracting 5' and 3' adjacent bases

Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 338: 'allow.nonnarrowing' is FALSE and the supplied start (81280647) is > refwidth + 1

**Comment by PoisonAlien** [comment]
Hi,
This happens when you use wrong reference build. Please make sure if your reference genome is indeed `hg19`.

**Comment by Usamahussein551980** [comment]
Thanks for your reply, I solved the issue.
I am still have a naive question:
I using GDC dataset open access, but still don't know where can I find the Amino_acid_change column in the clinical data.
Actually, I downloaded the MAF files and merg them, then the clinical data of the same MAF dataset from the same site (GDC), but many information are missing in the clinical data file.
Do you have any key to get these missing data of the clinical part.
Thank you

**Comment by PoisonAlien** [comment]
Hi,
`Amino_acid_change` won't be in clinical data. It will be in the MAF file. 
Sometimes it will be named differently - `HGVSp` `HGVSp_short` `AA_change` etc as there is no standard naming convention.

**Comment by Usamahussein551980** [comment]
Thank you so much for your quick help.
I got it.
