### ISSUE TITLE
How to access to full ICGC data

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#439]
Hi

Sorry I found `icgcSimpleMutationToMAF` a very interesting function to work on public data. By luck I am working on `ESCA` as you exemplified that for this function in maftools vignette but I found that you are just using a toy data and very small. This might totally irrelevant to your package but may I please ask how I can access the full `simple_somatic_mutation.open.ESCA-CN.sample.tsv.gz` file?

Thank you

**Comment by PoisonAlien** [comment]
I think you will have to browse ICGC data portal. Its been a while since I checked it, and I dont remember by-heart.
