### ISSUE TITLE
Rainfall plot assumes MAF rows are ordered on start position

### ISSUE THREAD

**Issue by rdmorin** [PoisonAlien/maftools#44]
I have found that Rainfall plot gets a lot of NA values from the diff function when the chromosomal positions in the original MAF are not ordered. Is it possible that the MAF data could be ordered this way before running the function? I am not sure it is safe to assume the users will always have sorted MAFs.

**Comment by PoisonAlien** [comment]
Hi ,
Chromosomes are ordered according to Chromosome name (after removing prefix if any and converting to numeric) followed by position, before running diff function ([here](https://github.com/PoisonAlien/maftools/blob/9d8529f0918ef01b269df293a1114511acd40a97/R/readSegs.R#L94)) I am not sure why NAs are generated. Does input maf has missing values ?

**Comment by rdmorin** [comment]
You're right. I must have modified my MAF object after loading it. I seem to recall I was modifying the tumor_sample_barcode in place. This probably caused the issue and should not affect users if they don't modify the MAF object.
