### ISSUE TITLE
 Hi， Recently I found error of maftools "https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#9_analysis"

### ISSUE THREAD

**Issue by weilan-yuan** [PoisonAlien/maftools#442]

**Comment by weilan-yuan** [comment]
get "laml.sign = estimateSignatures(mat = laml.tnm, nTry = 4) "
laml.se = signatureEnrichment(maf = laml, sig_res = laml.sig) this "laml.sig" is error ,"laml.sign" maybe right.

**Comment by PoisonAlien** [comment]
Hi,
Sorry there is a missing command in the vignette  for the function `extractSignatures`

```r
laml.sig = extractSignatures(mat = laml.tnm, n = 3, pConstant = 0.1)
```

Above output `laml.sig` is passed to `signatureEnrichment`. I have fixed it, but the changes are yet to appear on Bioconductor.

**Comment by PoisonAlien** [comment]
Thanks again. Vignette is fixed now.

**Comment by weilan-yuan** [comment]
thank you very much
