### ISSUE TITLE
Is this possible to produce such a plot 

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#443]
Hi

Thanks for this software. Can we show alongside the plots come from GISTIC visualization? Something like this
![nihms271566f1](https://user-images.githubusercontent.com/43682980/71184656-fed14d80-2271-11ea-8d4f-1f2712ef1b35.jpg)

Thank you in advance for any help for getting this

**Comment by PoisonAlien** [comment]
Maybe not the same plot, but this one comes [close](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#821_genome_plot) enough. You can suggest me if there is something that you like me to add.

**Comment by beginner984** [comment]
Exactly I noticed https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#821_genome_plot in your software that is why I think that would be great any possibly of adding gene for this function to come up with something shown in that paper

Please go ahead for that if this is possible

**Comment by PoisonAlien** [comment]
Hi,

I have pushed some changes which enables highlights mutations on chromplot. Could you please try it and let me know if it works for you? You will have to install from GitHub.

example usage with builtin `laml` cohort:

```r
gisticChromPlot(gistic = laml.gistic, maf = laml, mutGenes = c("TP53", "DNMT3A", "RUNX1"))
```

**Comment by beginner984** [comment]
Thank you

With this maf object

https://www.dropbox.com/s/3bs3mtymi6w1dkr/res.rds?dl=0
and gistic.laml
https://www.dropbox.com/s/0uq7or8wxyb87ih/laml.gistic?dl=0

I got this picture

![Rplot122](https://user-images.githubusercontent.com/43682980/71449973-1b600080-271e-11ea-8a90-90ab50c70c12.png)
Only showing TP53
```

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] maftools_2.2.20

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3          magrittr_1.5       
 [3] splines_3.6.1       wordcloud_2.6      
 [5] xtable_1.8-4        lattice_0.20-38    
 [7] R6_2.4.1            rlang_0.4.2        
 [9] fastmap_1.0.1       tools_3.6.1        
[11] grid_3.6.1          data.table_1.12.8  
[13] htmltools_0.4.0     remotes_2.1.0      
[15] survival_2.44-1.1   digest_0.6.23      
[17] Matrix_1.2-17       shiny_1.4.0        
[19] BiocManager_1.30.10 RColorBrewer_1.1-2 
[21] later_1.0.0         promises_1.1.0     
[23] curl_4.2            mime_0.8           
[25] compiler_3.6.1      httpuv_1.5.2       
> 
gisticChromPlot(gistic = laml.gistic, maf = laml, mutGenes = c("TP53", "DNMT3A", "RUNX1"))
```
Is it possible to show all genes in those picks?

In this paper https://doi.org/10.1038/s41588-018-0331-5 about genes spanning in each pick of GISTIC says that:

> 
> A peak would often sit next to, but not overlap, a well-characterized oncogene or tumor suppressor. To
> account for this tendency, we widened the amplification peak sizes upstream and
> downstream by twice the size of each peak to ensure that we captured all possible
> drivers. Our expression analysis allowed us to then remove false positives from this
> wider region, and called drivers were still highly enriched in genes closer to the
> centers of GISTIC peak regions.

But I am not sure what they mean

**Comment by beginner984** [comment]
Sorry that would be possible to have all significant GISTIC regions and spanning genes in visualizing gistic results as shown in this picture?
![71184656-fed14d80-2271-11ea-8d4f-1f2712ef1b35](https://user-images.githubusercontent.com/43682980/71564800-1bd50000-2a6c-11ea-8418-33f9764c4e30.jpg)

**Comment by PoisonAlien** [comment]
By default `gisticChromPlot` highlights top 5 significantly altered peaks. You will have to set `markBands = 'all'` to highlight them all. Also see `?gisticChromPlot` for more details. This is also shown in the [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/maftools.html#82_visualizing_gistic_results). 

For the warning message regarding `Could not find mutations`, I think your maf file lacks these mutations. Hence the warning. 

For highlighting the genes within a copy number altered region, its not possible for now. I will gradually implement it.

**Comment by complexgenome** [comment]
@beginner984 Hi - were you able to generate the plot you were interested in?

**Comment by beginner984** [comment]
Hi not this one but I managed to plot figure 3 in this paper 

https://pubmed.ncbi.nlm.nih.gov/34298611/

If the heat map in figure 3 helps I have the code to create that
     On Thursday, August 8, 2024 at 04:49:48 PM GMT+1, Sanjeev ***@***.***> wrote:  
 
 


@beginner984 Hi - were you able to generate the plot you were interested in?

**Comment by complexgenome** [comment]
@beginner984 Hi,
Thanks for your response.
Sure, Figure 3 heatmap code would be very helpful.

Best,
CG

> Hi not this one but I managed to plot figure 3 in this paper https://pubmed.ncbi.nlm.nih.gov/34298611/ If the heat map in figure 3 helps I have the code to create that On Thursday, August 8, 2024 at 04:49:48 PM GMT+1, Sanjeev ***@***.***> wrote: @beginner984 Hi - were you able to generate the plot you were interested in? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by beginner984** [comment]
I have created this thread at that time so the code is here Changing legend color and lable · Issue #662 · jokergoo/ComplexHeatmap

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Changing legend color and lable · Issue #662 · jokergoo/ComplexHeatmap

With this code I have this complexheatmap left_annotation = rowAnnotation(Peak = anno_text(left_anno$Peak), Perc...
 |

 |

 |




    On Friday, August 9, 2024 at 01:06:57 PM GMT+1, Sanjeev ***@***.***> wrote:  
 
 


@beginner984 Hi,
Thanks for your response.
Sure, Figure 3 heatmap code would be very helpful.

Best,
CG


Hi not this one but I managed to plot figure 3 in this paper https://pubmed.ncbi.nlm.nih.gov/34298611/ If the heat map in figure 3 helps I have the code to create that On Thursday, August 8, 2024 at 04:49:48 PM GMT+1, Sanjeev @.> wrote: @beginner984 Hi - were you able to generate the plot you were interested in? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.>
