### ISSUE TITLE
Hi I use maftools “mafSurvival” function plot the KRAS mutation/wildtype to find out the mistake with the tail of  KM line 

### ISSUE THREAD

**Issue by weilan-yuan** [PoisonAlien/maftools#444]

**Comment by weilan-yuan** [comment]
the KM line is different from the R survival package result .

**Comment by bellqiu** [comment]
Image1:
==
![image1](https://www.fnvalley.com/maf-survival/image1.png)

Image2:
==
![image2](https://www.fnvalley.com/maf-survival/image2.png)

**Comment by ShixiangWang** [comment]
Could you show your example code?

**Comment by ShixiangWang** [comment]
Could you show your example code?

**Comment by PoisonAlien** [comment]
Hi,
Please post your command used and `sessionInfo`.

**Comment by weilan-yuan** [comment]
thank you for reply. I try it again  and the mistake is not by the mafsurvival function ,but my data is mistake . 






At 2019-12-26 01:28:03, "Anand Mayakonda" <notifications@github.com> wrote:

Hi,
Please post your command used and sessionInfo.
