### ISSUE TITLE
Adding extra column and information to maf

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#445]
Hi
I had called my somatic mutation by Strelka then annotated by annovar and annovar2maf from your software. I noticed my maf does not have variant allele frequency (VAF) column. I therefore tried to calculated VAF for each of my .VCF from Strelka. Is these any way to add VAF for each sample to my big maf object? 

Lets say this is my maf object for 21 samples 

https://www.dropbox.com/s/3bs3mtymi6w1dkr/res.rds?dl=0

For these 21 samples I calculated VAF separately. I want to add VAF to my maf, is it possible?

This is  extracted information including VAF from one of my vcf files
[LP6008336-DNA_H02_vs_LP6008333-DNA_H02.snp.pass.vcf.parsed.txt](https://github.com/PoisonAlien/maftools/files/4003702/LP6008336-DNA_H02_vs_LP6008333-DNA_H02.snp.pass.vcf.parsed.txt)

 

Thank you

**Comment by PoisonAlien** [comment]
This is beyond the scope package usage. Sorry, but you will have to figure out this.

**Comment by beginner984** [comment]
Thank you so much

As I mentioned, I had calculated VAF for each sample I then manually add VAF column to my VAF

This is VAF plot for one sample

![Rplot123](https://user-images.githubusercontent.com/43682980/71564763-a5d09900-2a6b-11ea-9dd0-41e51ad9d32d.png)

I guess VAFs are too low because I have only one sample in my maf object
