### ISSUE TITLE
Changing oncoplot in a specific way

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#446]
Sorry to be this much annoying 

I need help please 

I have a list of genes that have been previously reported in the COSMIC database about ESCA. I also have my own maf object for my tumours in ESCA

How can I show the status of COSMIC genes in oncoplot of my maf object please?

Something like this
![nihms474888f4](https://user-images.githubusercontent.com/43682980/71494529-7a507300-280d-11ea-931b-ea2ebe227be4.jpg)

For example showing in my oncoplot if a gee has been previously reported in COSMIC or any information like if this is a false positive (belong to big gene families like TTN1, etc)
Thank you for any help

**Comment by PoisonAlien** [comment]
You can add a column in your `maf` file with COSMIC status for variants (e.g, yes or no). While plotting use the argument `additionalFeature` to highlight specific attributes.

E.g;

```r
oncoplot(maf = my_maf,  additionalFeature = c("COSMIC", "yes"))
``` 

See [here](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/oncoplots.html#07_highlighting_samples) for an example.

**Comment by beginner984** [comment]
Hello
Thank you so much

Sorry

I have a maf object I then tried to extract my data from that to add extra column like COSMIC information; So

maf=laml@maf.silent

> laml = read.maf(maf = a, clinicalData = NULL)
-Validating
--Non MAF specific values in Variant_Classification column:
  Unknown
--Non MAF specific values in Variant_Type column:
  MNP
-Silent variants: 471853 
Error in read.maf(maf = a, clinicalData = NULL) : 
  No non-synonymous mutations found
Check `vc_nonSyn`` argumet in `read.maf` for details

How I can retrieve my original maf from maf object? I had converted annovar annotation to maf by your sofware

**Comment by PoisonAlien** [comment]
There is no direct way. Best way would be to write your maf object with `write.mafSummary` which should generate the maf to an output file. Then add your cosmic status to it and read it back again.

**Comment by beginner984** [comment]
I done so

```
data=laml@data

data$COSMIC <- ifelse(data$Hugo_Symbol %in% gene_list,yes = "yes",no = "no")

laml = read.maf(maf = data, clinicalData = NULL)

oncoplot(maf = laml,  additionalFeature = c("COSMIC", "yes"))
```

I am not sure if I am doing correct because 

```
> dim(data) 
[1] 2450  129
```



![Rplot123](https://user-images.githubusercontent.com/43682980/71596517-445d0880-2b05-11ea-8281-fd64bd64e85a.png)

**Comment by PoisonAlien** [comment]
I will not recommend altering the maf object with `@`. Write your maf object with `write.mafSummary` once you generate your maf file from your annovar outputs. 

For example;

```r
write.mafSummary(maf = laml, basename = "my_maf")
```

Above command should generate `my_maf_maftools.maf` tsv file. Read this file into R using your favourite command like `read.table` or `data.table::fread`. Then add COSMIC status to this file. This ensures that you are not missing anything. What you were doing earlier is adding information to only non-syn variants. This is the final data.frame that you should be reading with `read.maf`

Also I am not sure what you are trying to do but, not all mutations for a given gene will be in COSMIC. You will have to check which variant of a gene is annotated by COSMIC based on protein change or genomic loci. In your example image, you see that not all `ERBB2` are annotated by COSMIC, only some of them are.

**Comment by beginner984** [comment]
Thank you so much very very useful comment about getting main maf from maf object

About adding COSMIC, I am also note quite sure. My supervisor has asked me to enrich my annovar annotation with a list of false positive genes, driver genes for ESCA reported by other studies and COSMIC drivers. I then thought to add these columns to my maf for visualization although I am not certain about any usefulness of this

**Comment by beginner984** [comment]
Hello

I have added extra columns to my maf like **_COSMIC_**, **_FRANKEL_**, **_cancer_damaging_alteration_**, **_cancer_helper_** but for example says 


```
> oncoplot(maf = laml,  additionalFeature = c("FRANKEL", "yes"))
Warning message:
In oncoplot(maf = laml, additionalFeature = c("FRANKEL", "yes")) :
  No samples are enriched for yes in FRANKEL
>
```
While I have **_yes_** for added gene list
> dim(maf[maf$FRANKEL=="yes",])
[1] 607 133
> 

How it is possible?

This is my maf, please can you have a look?

https://www.dropbox.com/s/7unfevgjdvfcix0/maf.rds?dl=0

Thank you

**Comment by PoisonAlien** [comment]
That means none of the top mutated genes are `yes` for `FRANKEL`.  Only below genes in your maf belong to `yes`.

```r
> m@data[FRANKEL == 'yes'][,.N,.(FRANKEL, Hugo_Symbol)]
 FRANKEL Hugo_Symbol N
 1:     yes      ARID1B 1
 2:     yes       ARID2 1
 3:     yes       EPHA2 1
 4:     yes       SCN3A 2
 5:     yes         MET 1
 6:     yes    CCDC102B 1
 7:     yes       NIPBL 2
 8:     yes        MDM2 1
 9:     yes       ZFHX3 1
10:     yes       SLIT2 1
11:     yes       ERBB2 1
12:     yes        MSH3 1
13:     yes       CCNE1 1
```

Using above genes works.
```r
> yes_genes = m@data[FRANKEL == 'yes'][,.N,.(FRANKEL, Hugo_Symbol)][,Hugo_Symbol]
> yes_genes
 [1] "ARID1B"   "ARID2"    "EPHA2"    "SCN3A"    "MET"      "CCDC102B" "NIPBL"    "MDM2"    
 [9] "ZFHX3"    "SLIT2"    "ERBB2"    "MSH3"     "CCNE1" 
> maftools::oncoplot(maf = m, genes = yes_genes, additionalFeature = c("FRANKEL", "yes"))
```

Also, I would appreciate if you can restrict your questions to tool related bugs or errors. Most of the questions seem to be pretty basic. you will just have to spend some time figuring them out.
