### ISSUE TITLE
Change oncoplot title

### ISSUE THREAD

**Issue by showteeth** [PoisonAlien/maftools#448]
Hi,       
Is there any way to **change** the default title **Altered in xxx of xxx samples** to something else or **add** a sup title?       
Thank you for any help!

**Comment by PoisonAlien** [comment]
Hi,
I have added `titleText` argument to `oncoplot` function. 

```r
oncoplot(maf = my_maf, titleText = "my custom title")
```

You will have to reinstall from GitHub. Let me know if this helps.

**Comment by showteeth** [comment]
Yes, it works!     
Thank you for such timely help!
