### ISSUE TITLE
Error in seq.default(0, max(colSums(gs.dat)) + 2, length.out = 4) :    'to' must be a finite number

### ISSUE THREAD

**Issue by Subhi** [PoisonAlien/maftools#449]
I loaded a maf file with 7 mutations and I got this error

**Comment by PoisonAlien** [comment]
Hi,
Could you please post your complete command?

**Comment by Subhi** [comment]
The command:
plotmafSummary(maf = cell1, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)



I have attcahed the maf as well
[A.txt](https://github.com/PoisonAlien/maftools/files/4031150/A.txt)

**Comment by PoisonAlien** [comment]
Your maf contains only one sample. `maftools` works well with multi sample cohort, and most functions will result in error with single sample. There is very little I can do to here :|

**Comment by Subhi** [comment]
I was able to get it running for other maf with similar single sample! This is the only maf that failed.

**Comment by PoisonAlien** [comment]
Okay I think I found the source. Could you try again? You will have to install from GitHub. 
Also, if you have multiple samples, it would be easier if you can combine them into one single maf.

**Comment by Subhi** [comment]
I re-installed from GitHub but still the same error.

"Error in seq.default(0, max(colSums(gs.dat)) + 2, length.out = 4) : 
  'to' must be a finite number
In addition: Warning message:
In max(colSums(gs.dat)) : no non-missing arguments to max; returning -Inf"

**Comment by PoisonAlien** [comment]
It seems to work on my system with the same `A.txt` maf file. Can you post your sessionInfo with devtools?

```r
> devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       macOS  10.15.2              
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2020-01-08                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────
 package      * version date       lib source                               
 assertthat     0.2.1   2019-03-21 [1] CRAN (R 3.6.0)                       
 backports      1.1.5   2019-10-02 [1] CRAN (R 3.6.0)                       
 BiocManager    1.30.10 2019-11-16 [1] CRAN (R 3.6.0)                       
 callr          3.4.0   2019-12-09 [1] CRAN (R 3.6.0)                       
 cli            2.0.0   2019-12-09 [1] CRAN (R 3.6.0)                       
 crayon         1.3.4   2017-09-16 [1] CRAN (R 3.6.0)                       
 curl           4.3     2019-12-02 [1] CRAN (R 3.6.0)                       
 data.table     1.12.8  2019-12-09 [1] CRAN (R 3.6.0)                       
 desc           1.2.0   2019-06-16 [1] Github (r-lib/desc@c860e7b)          
 devtools       2.2.1   2019-09-24 [1] CRAN (R 3.6.0)                       
 digest         0.6.23  2019-11-23 [1] CRAN (R 3.6.0)                       
 ellipsis       0.3.0   2019-09-20 [1] CRAN (R 3.6.0)                       
 fansi          0.4.0   2018-10-05 [1] CRAN (R 3.6.0)                       
 fs             1.3.1   2019-05-06 [1] CRAN (R 3.6.0)                       
 glue           1.3.1   2019-03-12 [1] CRAN (R 3.6.0)                       
 lattice        0.20-38 2018-11-04 [1] CRAN (R 3.6.0)                       
 maftools     * 2.2.20  2020-01-08 [1] Github (poisonalien/maftools@8d94c64)
 magrittr       1.5     2014-11-22 [1] CRAN (R 3.6.0)                       
 Matrix         1.2-18  2019-11-27 [1] CRAN (R 3.6.0)                       
 memoise        1.1.0   2017-04-21 [1] CRAN (R 3.6.0)                       
 pkgbuild       1.0.6   2019-10-09 [1] CRAN (R 3.6.0)                       
 pkgload        1.0.2   2018-10-29 [1] CRAN (R 3.6.0)                       
 prettyunits    1.0.2   2015-07-13 [1] CRAN (R 3.6.0)                       
 processx       3.4.1   2019-07-18 [1] CRAN (R 3.6.0)                       
 ps             1.3.0   2018-12-21 [1] CRAN (R 3.6.0)                       
 R6             2.4.1   2019-11-12 [1] CRAN (R 3.6.0)                       
 RColorBrewer   1.1-2   2014-12-07 [1] CRAN (R 3.6.0)                       
 Rcpp           1.0.3   2019-11-08 [1] CRAN (R 3.6.0)                       
 remotes        2.1.0   2019-06-24 [1] CRAN (R 3.6.0)                       
 rlang          0.4.2   2019-11-23 [1] CRAN (R 3.6.0)                       
 rprojroot      1.3-2   2018-01-03 [1] CRAN (R 3.6.0)                       
 rstudioapi     0.10    2019-03-19 [1] CRAN (R 3.6.0)                       
 sessioninfo    1.1.1   2018-11-05 [1] CRAN (R 3.6.0)                       
 survival       3.1-8   2019-12-03 [1] CRAN (R 3.6.0)                       
 testthat       2.3.1   2019-12-01 [1] CRAN (R 3.6.0)                       
 usethis        1.5.1   2019-07-04 [1] CRAN (R 3.6.0)                       
 withr          2.1.2   2018-03-15 [1] CRAN (R 3.6.0)                       
 wordcloud      2.6     2018-08-24 [1] CRAN (R 3.6.0)                       

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

**Comment by Subhi** [comment]
> devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-01-08                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version   date       lib source                               
 acepack                1.4.1     2016-10-29 [3] CRAN (R 3.5.0)                       
 annotate               1.60.1    2019-03-07 [3] Bioconductor                         
 AnnotationDbi          1.44.0    2018-10-30 [3] Bioconductor                         
 assertthat             0.2.1     2019-03-21 [3] CRAN (R 3.5.2)                       
 backports              1.1.5     2019-10-02 [3] CRAN (R 3.5.2)                       
 base64enc              0.1-3     2015-07-28 [3] CRAN (R 3.5.0)                       
 BiasedUrn              1.07      2015-12-28 [3] CRAN (R 3.5.0)                       
 Biobase                2.42.0    2018-10-30 [3] Bioconductor                         
 BiocGenerics           0.28.0    2018-10-30 [3] Bioconductor                         
 BiocParallel           1.16.6    2019-02-10 [3] Bioconductor                         
 bit                    1.1-14    2018-05-29 [3] CRAN (R 3.5.0)                       
 bit64                  0.9-7     2017-05-08 [3] CRAN (R 3.5.0)                       
 bitops                 1.0-6     2013-08-17 [3] CRAN (R 3.5.0)                       
 blob                   1.2.0     2019-07-09 [3] CRAN (R 3.5.2)                       
 broom                  0.5.3     2019-12-14 [3] CRAN (R 3.5.2)                       
 callr                  3.4.0     2019-12-09 [3] CRAN (R 3.5.2)                       
 checkmate              1.9.4     2019-07-04 [3] CRAN (R 3.5.2)                       
 cli                    2.0.0     2019-12-09 [3] CRAN (R 3.5.2)                       
 clonevol               0.99.11   2019-08-22 [2] Github (hdng/clonevol@7aff737)       
 cluster                2.1.0     2019-06-19 [3] CRAN (R 3.5.2)                       
 colorspace             1.4-1     2019-03-18 [3] CRAN (R 3.5.2)                       
 crayon                 1.3.4     2017-09-16 [3] CRAN (R 3.5.0)                       
 data.table             1.12.8    2019-12-09 [1] CRAN (R 3.5.2)                       
 DBI                    1.1.0     2019-12-15 [2] CRAN (R 3.5.2)                       
 DelayedArray           0.8.0     2018-10-30 [3] Bioconductor                         
 desc                   1.2.0     2018-05-01 [3] CRAN (R 3.5.0)                       
 DESeq2                 1.22.2    2019-01-04 [3] Bioconductor                         
 devtools               2.2.1     2019-09-24 [1] CRAN (R 3.5.2)                       
 digest                 0.6.23    2019-11-23 [1] CRAN (R 3.5.2)                       
 dplyr                  0.8.3     2019-07-04 [3] CRAN (R 3.5.2)                       
 ellipsis               0.3.0     2019-09-20 [1] CRAN (R 3.5.2)                       
 epiR                   1.0-10    2019-11-24 [2] CRAN (R 3.5.2)                       
 fansi                  0.4.0     2018-10-05 [3] CRAN (R 3.5.0)                       
 foreign                0.8-74    2019-12-26 [1] CRAN (R 3.5.2)                       
 Formula                1.2-3     2018-05-03 [3] CRAN (R 3.5.0)                       
 fs                     1.3.1     2019-05-06 [3] CRAN (R 3.5.2)                       
 genefilter             1.64.0    2018-10-30 [3] Bioconductor                         
 geneplotter            1.60.0    2018-10-30 [3] Bioconductor                         
 generics               0.0.2     2018-11-29 [3] CRAN (R 3.5.0)                       
 GenomeInfoDb           1.18.2    2019-02-12 [3] Bioconductor                         
 GenomeInfoDbData       1.2.0     2019-01-29 [3] Bioconductor                         
 GenomicRanges          1.34.0    2018-10-30 [3] Bioconductor                         
 ggplot2                3.2.1     2019-08-10 [1] CRAN (R 3.5.2)                       
 ggpubr                 0.2.4     2019-11-14 [3] CRAN (R 3.5.2)                       
 ggsignif               0.6.0     2019-08-08 [3] CRAN (R 3.5.2)                       
 glue                   1.3.1     2019-03-12 [3] CRAN (R 3.5.2)                       
 gridExtra              2.3       2017-09-09 [1] CRAN (R 3.5.0)                       
 gtable                 0.3.0     2019-03-25 [3] CRAN (R 3.5.2)                       
 Hmisc                  4.3-0     2019-11-07 [3] CRAN (R 3.5.2)                       
 htmlTable              1.13.3    2019-12-04 [3] CRAN (R 3.5.2)                       
 htmltools              0.4.0     2019-10-04 [3] CRAN (R 3.5.2)                       
 htmlwidgets            1.5.1     2019-10-08 [3] CRAN (R 3.5.2)                       
 httr                   1.4.1     2019-08-05 [3] CRAN (R 3.5.2)                       
 IRanges                2.16.0    2018-10-30 [1] Bioconductor                         
 jsonlite               1.6       2018-12-07 [3] CRAN (R 3.5.0)                       
 km.ci                  0.5-2     2009-08-30 [3] CRAN (R 3.5.0)                       
 KMsurv                 0.1-5     2012-12-03 [3] CRAN (R 3.5.0)                       
 knitr                  1.26      2019-11-12 [1] CRAN (R 3.5.2)                       
 lattice                0.20-38   2018-11-04 [3] CRAN (R 3.5.2)                       
 latticeExtra           0.6-28    2016-02-09 [3] CRAN (R 3.5.0)                       
 lazyeval               0.2.2     2019-03-15 [3] CRAN (R 3.5.2)                       
 lifecycle              0.1.0     2019-08-01 [2] CRAN (R 3.5.2)                       
 locfit                 1.5-9.1   2013-04-20 [3] CRAN (R 3.5.0)                       
 **maftools             * 2.2.20    2020-01-07 [1] Github (PoisonAlien/maftools@8d94c64)**
 magrittr               1.5       2014-11-22 [3] CRAN (R 3.5.0)                       
 Matrix                 1.2-18    2019-11-27 [3] CRAN (R 3.5.2)                       
 matrixStats            0.55.0    2019-09-07 [3] CRAN (R 3.5.2)                       
 memoise                1.1.0     2017-04-21 [3] CRAN (R 3.5.0)                       
 munsell                0.5.0     2018-06-12 [3] CRAN (R 3.5.0)                       
 nlme                   3.1-143   2019-12-10 [3] CRAN (R 3.5.2)                       
 nnet                   7.3-12    2016-02-02 [3] CRAN (R 3.5.2)                       
 OncoCast               0.1.0     2019-02-07 [3] Github (shenmskcc/OncoCast@df18a7b)  
 pillar                 1.4.3     2019-12-20 [2] CRAN (R 3.5.2)                       
 pkgbuild               1.0.6     2019-10-09 [3] CRAN (R 3.5.2)                       
 pkgconfig              2.0.3     2019-09-22 [1] CRAN (R 3.5.2)                       
 pkgload                1.0.2     2018-10-29 [3] CRAN (R 3.5.0)                       
 plotly                 4.9.1     2019-11-07 [2] CRAN (R 3.5.2)                       
 prettyunits            1.0.2     2015-07-13 [3] CRAN (R 3.5.0)                       
 processx               3.4.1     2019-07-18 [3] CRAN (R 3.5.2)                       
 ps                     1.3.0     2018-12-21 [3] CRAN (R 3.5.0)                       
 purrr                  0.3.3     2019-10-18 [3] CRAN (R 3.5.2)                       
 R6                     2.4.1     2019-11-12 [3] CRAN (R 3.5.2)                       
 RColorBrewer           1.1-2     2014-12-07 [3] CRAN (R 3.5.0)                       
 Rcpp                   1.0.3     2019-11-08 [1] CRAN (R 3.5.2)                       
 RCurl                  1.95-4.12 2019-03-04 [3] CRAN (R 3.5.2)                       
 remotes                2.1.0     2019-06-24 [3] CRAN (R 3.5.2)                       
 rlang                  0.4.2     2019-11-23 [2] CRAN (R 3.5.2)                       
 rpart                  4.1-15    2019-04-12 [3] CRAN (R 3.5.2)                       
 rprojroot              1.3-2     2018-01-03 [3] CRAN (R 3.5.0)                       
 RSQLite                2.2.0     2020-01-07 [3] CRAN (R 3.5.2)                       
 rstudioapi             0.10      2019-03-19 [3] CRAN (R 3.5.2)                       
 S4Vectors              0.20.1    2018-11-09 [3] Bioconductor                         
 scales                 1.1.0     2019-11-18 [3] CRAN (R 3.5.2)                       
 sessioninfo            1.1.1     2018-11-05 [3] CRAN (R 3.5.0)                       
 stringi                1.4.3     2019-03-12 [3] CRAN (R 3.5.2)                       
 stringr                1.4.0     2019-02-10 [3] CRAN (R 3.5.2)                       
 SummarizedExperiment   1.12.0    2018-10-30 [3] Bioconductor                         
 survival               3.1-8     2019-12-03 [2] CRAN (R 3.5.2)                       
 survminer              0.4.6     2019-09-03 [3] CRAN (R 3.5.2)                       
 survMisc               0.5.5     2018-07-05 [3] CRAN (R 3.5.0)                       
 testthat               2.3.1     2019-12-01 [3] CRAN (R 3.5.2)                       
 tibble                 2.1.3     2019-06-06 [2] CRAN (R 3.5.2)                       
 tidyr                  1.0.0     2019-09-11 [2] CRAN (R 3.5.2)                       
 tidyselect             0.2.5     2018-10-11 [3] CRAN (R 3.5.0)                       
 usethis                1.5.1     2019-07-04 [3] CRAN (R 3.5.2)                       
 vctrs                  0.2.1     2019-12-17 [2] CRAN (R 3.5.2)                       
 viridisLite            0.3.0     2018-02-01 [3] CRAN (R 3.5.0)                       
 withr                  2.1.2     2018-03-15 [3] CRAN (R 3.5.0)                       
 wordcloud              2.6       2018-08-24 [3] CRAN (R 3.5.0)                       
 xfun                   0.11      2019-11-12 [2] CRAN (R 3.5.2)                       
 XML                    3.98-1.20 2019-06-06 [3] CRAN (R 3.5.2)                       
 xtable                 1.8-4     2019-04-21 [3] CRAN (R 3.5.2)                       
 XVector                0.22.0    2018-10-30 [3] Bioconductor                         
 zeallot                0.1.0     2018-01-28 [2] CRAN (R 3.5.0)                       
 zlibbioc               1.28.0    2018-10-30 [3] Bioconductor                         
 zoo                    1.8-6     2019-05-28 [3] CRAN (R 3.5.2)                       

[1] /Users/nandakus/.RLibrary
[2] /Users/nandakus/Library/R/3.5/library
[3] /Library/Frameworks/R.framework/Versions/3.5/Resources/library

**Comment by PoisonAlien** [comment]
This seems ok. Error that you are facing is it with the same file `A.txt`?

**Comment by Subhi** [comment]
It worked now!

Thanks :)
