### ISSUE TITLE
File uploading

### ISSUE THREAD

**Issue by zayni** [PoisonAlien/maftools#45]
Hi,
getting errors this morning. I am a Mac User

reading maf..
Error in data.table::fread(input = maf, sep = "\t", stringsAsFactors = FALSE, :
Input is either empty or fully whitespace after the skip or autostart. Run again with verbose=TRUE.
It was working well yesterday. Not sure what is going on?
Can you please help

**Comment by PoisonAlien** [comment]
Hi,

Its hard to say without a reproducible example. Can your share your file if you're okay with it ? or can you try to read using `data.table::fread(maf_file)` and see if you get the same error ? Is the file same as yesterday, error says file might be empty. Can you check the contents ?

**Comment by zayni** [comment]
Error in data.table::fread(coad.maf) : 
  Input is either empty or fully whitespace after the skip or autostart. Run again with verbose=TRUE.
I looked at the file. It is fine. Same as yesterday TCGA..COAD mutect file

Thanks a lot!
Ashiq

**Comment by PoisonAlien** [comment]
Is it compressed ? If so, can you decompress and try again ? Can you upload it here ?

**Comment by zayni** [comment]
It is not compressed at all. It is larger than 10MB. But it has all 32 fields of TCGA file 
Thanks for your time 

Zayni

**Comment by zayni** [comment]
Here is the link

https://portal.gdc.cancer.gov/files/706d5716-be1e-4482-a867-61dec69557c8

**Comment by PoisonAlien** [comment]
Hi,

Just downloaded the file and checked on macOS (Sierra) and Ubuntu, works fine for me. 

```r
coad = read.maf(maf = '~/Downloads/gdc_download_20170410_034802/706d5716-be1e-4482-a867-61dec69557c8/TCGA.COAD.mutect.706d5716-be1e-4482-a867-61dec69557c8.somatic.maf.gz')
```

can you post your command ?

**Comment by zayni** [comment]
library("maftools")
> suppressPackageStartupMessages(require(maftools))
> coad.maf = system.file(maf ='~/Downloads/gdc_download_20170410_034802/706d5716-be1e-4482-a867-61dec69557c8/TCGA.COAD.mutect.706d5716-be1e-4482-a867-61dec69557c8.somatic.maf.gz', package = 'maftools')
> coad = read.maf(maf = laml.maf, removeSilent = TRUE, useAll = FALSE)
Error in is.data.frame(x = maf) : object 'laml.maf' not found
> coad = read.maf(maf = coad.maf, removeSilent = TRUE, useAll = FALSE)
reading maf..
Error in data.table::fread(input = maf, sep = "\t", stringsAsFactors = FALSE,  : 
  Input is either empty or fully whitespace after the skip or autostart. Run again with verbose=TRUE.

**Comment by zayni** [comment]
Thanks a lot !

**Comment by PoisonAlien** [comment]
Okay! you don't have to run first line `system.file`, since it points to example maf file which comes with the package. For your coad maf, you just need to provide downloaded file name (with path) to `read.maf`. 

Try this:
```r

coad = read.maf(maf = '~/Downloads/gdc_download_20170410_034802/706d5716-be1e-4482-a867-61dec69557c8/TCGA.COAD.mutect.706d5716-be1e-4482-a867-61dec69557c8.somatic.maf.gz', removeSilent = TRUE, useAll = FALSE)
```

**Comment by zayni** [comment]
Awesome ! It worked. Thanks you so much

**Comment by PoisonAlien** [comment]
No problem :)
