### ISSUE TITLE
exprsTbl graph plotting with the wrong alignment?

### ISSUE THREAD

**Issue by pickledgrape** [PoisonAlien/maftools#451]
Hi PoisonAlien, this is an awesome tool!

I find that when I use oncoplot with an expression table, the alignment of expression values are not plotting correctly. I can show you what I mean: 

![Rplot_github](https://user-images.githubusercontent.com/59489189/72450412-f3dde000-377f-11ea-824b-cbf89fd69e02.png)

The gene CREBBP holds the highest expression table value, .85, yet that score is plotted next to 10p11.22, and CREBBP shows no score at all. Any ideas of what is going on? There seems to be no issues with naming conventions in the data frames.

**Comment by pickledgrape** [comment]
To add, none of the gene positions are present in the gene column of the expression table yet they are still plotted.

**Comment by ShixiangWang** [comment]
The plot may be affected by the CNV, could you remove the CNV data and plot again to check this?

**Comment by PoisonAlien** [comment]
Hi,
Thanks for using the package and I am glad that you find the package useful. 
Is it possible to provide a reproducible example?

**Comment by pickledgrape** [comment]
@ShixiangWang you are right the CNV data is causing this problem. When it's removed the enrichment table plots amazingly. I know that the gene addresses present in the CNV are NOT present in the maf file. Do you know of any fix?

This code reproduces the original plot:
lglsamplesmaf = read.maf(lglsamples,cnTable = CNV, clinicalData = clinical)

oncoplot(maf = lglsamplesmaf,fontSize = .5, genes = genes_for_analysis, exprsTbl = Score_table, )

The score table contains two columns, gene and score value but not every gene is present.

**Comment by PoisonAlien** [comment]
Thanks @ShixiangWang for pointing out. 
@pickledgrape  I have fixed it. Could you please reinstall from GitHub and let me know if it helps?

**Comment by pickledgrape** [comment]
Great fix, everything plots properly now. Thanks!
