### ISSUE TITLE
Confusion on oncoplot

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#454]
Hi

Sorry for this silly confusion

I have a clinical data in TRG column I am sure all are responder

```
> print(a$TRG)
 [1] responder responder responder responder responder responder responder responder responder responder responder responder
[13] responder responder responder responder responder responder responder responder responder
Levels: non-responder responder
> 
```
But in oncoplot I am getting some NA for TRG like this
![Rplot](https://user-images.githubusercontent.com/43682980/72742675-22a1ef00-3ba2-11ea-978c-9897a5768db9.png)

I am wondering how it is possible?

This is my R object

https://www.dropbox.com/s/hzt1fc4miftfqjm/my_weird_oncoplot.RData?dl=0

**Comment by PoisonAlien** [comment]
Hi,
Your clinical is missing information for 4 samples. You can see this while reading your maf also.

```r
> x = read.maf(maf = maf, clinicalData = clinnical)
-Validating
--Removed 2 duplicated variants
--Non MAF specific values in Variant_Classification column:
  Unknown
--Non MAF specific values in Variant_Type column:
  MNP
-Silent variants: 411134 
-Summarizing
--Possible FLAGS among top ten genes:
  AHNAK2
  OBSCN
-Processing clinical data
--Annotation missing for below samples in MAF:
  LP6008460-DNA_A04
  LP6008460-DNA_D01
  LP6008460-DNA_F02
  LP6008460-DNA_G03
-Finished in 4.908s elapsed (5.196s cpu)
```

These are the 4 samples with `NA` in the onocplot.
