### ISSUE TITLE
forestPlot for a set of genes

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#455]
Hello

By using forestPlot function we nicely can compare two cohorts. Supposing we added an extra column to maf file, let's say cancer driver genes which has 1 if a gene is driver and 0 if no evidence of being a driver for any genes in maf file. Can we only compare two maf object for genes in cancer driver column with 1? I mean comparing two cohorts only regarding a set of genes

Thank you for any intuition

**Comment by PoisonAlien** [comment]
Hi,
Yes you can do that. You will have to subset your mafs and compare them.

For example,

```r
> driver_maf = subsetMaf(maf = maf, query = "is_driver == 1")
> passenger_maf = subsetMaf(maf = maf, query = "is_driver == 0")

> driver_vs_pass = mafCompare(driver_maf, passenger_maf)
> forestPlot(driver_vs_pass)
```
I hope I understood your question correctly.
I hope I understood your question correctly.
