### ISSUE TITLE
Output MAF has column names in wrong order if input column order is not default

### ISSUE THREAD

**Issue by Syksy** [PoisonAlien/maftools#457]
Hello,

I had an ANNOVAR output file where the columns `"Chr", "Start", "End", "Ref"`, "Alt" were not in this order; instead they were `"Chr", "Ref", "Alt", "Start", "End"`. The file had been manually altered.

At the following line in `annovarToMaf`:
`colnames(ann)[which(colnames(ann) %in% c("Chr", "Start", "End", "Ref", "Alt"))] = c("Chromosome", "Start_Position", "End_Position", "Reference_Allele", "Tumor_Seq_Allele2")`
the R script assumes that the data has to be in the default ordering and then assigns the new column names accordingly. However, this resulted in wrong column names in my case, as the comparison is done using `%in%`. How about using the `match`-function to map the column names in `ann` to the 5 desired column names in the input data instead?

I ended up just re-sorting my input file to the default column order again, but with above change such additional step wouldn't be necessary.

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Sorry for late reply and thank you for the suggestion. I have fixed it, please do try. I am closing the issue for now, please feel free to reopen if necessary.
