### ISSUE TITLE
Variant_Type is assigned 'SNP' for INDELs if '-' character is not used

### ISSUE THREAD

**Issue by Syksy** [PoisonAlien/maftools#458]
Hello,

My ANNOVAR output file contains the Ref/Alt information in following format for indels:
```
Ref  Alt
CAC  C
A    AGC
```
... where I would expect the former entry to be assigned a `DEL`, and the latter entry an `INS` for their `Variant_Type` output.
The implementation of `annovarToMaf` has the commented out former implementation, where number of characters were compared exactly for this purpose:
```
    ann[,ref_alt_diff := nchar(Ref) - nchar(Alt)]
    #ann[, Variant_Type := ifelse(ref_alt_diff == 0 , yes = "SNP", no = ifelse(ref_alt_diff < 0 , yes = "INS", no = "DEL"))]

```
However, the current implementation relies mainly on either `Ref` or `Alt` being assigned a `-` character:
```
    ann$Variant_Type = apply(ann[,.(Ref, Alt)], 1, function(x) {
      xx = which(x == '-')
...
```
Since neither my `Ref` or `Alt` merely contain the character `'-'`, my entries are incorrectly classified as `SNP`s. The `INS`/`DEL` cases don't seem to be reachable if the `Ref`/`Alt` are presented in my example format. Would it be possible to incorporate the character count comparison for such data as mine?

It seems the output MAF data.frame contains the correct information in the column `Variant_Classification` (such as `Frame_Shift_Del`, `In_Frame_Del`, ...), even if `Variant_Type` comes out as `SNP`.

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
I think I have fixed it (havent tested it). Could you please try again and let me know if this helps (you will have to install from GitHub)?
Thanks for reporting.

**Comment by Chitanda-Satou** [comment]
Hi, your format of data does not follow the standard of MAF. So, use tools **vcf2maf** to convert files into MAFs.

Your issue has been fixed in previous modifications of **annovarToMaf**. I think there is no need to modify the code of maftools. 

But ANNOVAR will bring you more troubles, far more than this one you met. **vcf2maf** is strongly recommended.
