### ISSUE TITLE
Extending Somatic Interactions to Pathway interaction

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#462]
Hi

Is it possible to get same thing like `Somatic Interactions` for `Oncogenic Signalling Pathways` ? I mean co-occurrence or mutually exclusiveness for pathways instead of genes within or among maf files 

Thank you

**Comment by PoisonAlien** [comment]
I am closing this issue since it wont be possible.

**Comment by beginner984** [comment]
Sorry @PoisonAlien 

Please look at this figure 

![Untitled](https://user-images.githubusercontent.com/43682980/83948773-9c680b80-a817-11ea-9b40-f4cdf226d27f.png)

Figure 4 part b this article 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6420087/
