### ISSUE TITLE
Combining GISTIC and copy number

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#463]
Hi

I want to show my copy number changes and GISTIC in one plot but each time I can show only one of these 

For example this is for copy number
![Rplot01](https://user-images.githubusercontent.com/43682980/73354284-40034700-428d-11ea-9e7c-67b5aa9fcf35.png)

And this is when I add GISTIC

![Rplot02](https://user-images.githubusercontent.com/43682980/73354369-76d95d00-428d-11ea-92ee-b12d9ab1cfd5.png)

This is my command

```
>  oncoplot(
+    maf = laml.plus.cn,
+    draw_titv = FALSE,
+    clinicalFeatures = c('died',"tratment","Gender","Smoking","RP.TumourGradingDifferentiationStatus"),
+    additionalFeature = c("FRANKEL", "yes"),
+    sortByAnnotation = TRUE
+  )
Following columns are missing from annotation slot of MAF. Ignoring them..
[1] "tratment"
> oncoplot(maf = laml.plus.gistic, top = 10)
>
``` 
Thank you

**Comment by PoisonAlien** [comment]
Its not possible to combine both, since these options are mutually exclusive. You can either use GISTIC or custom table.
