### ISSUE TITLE
Confusion from forestPlot

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#464]
Hi

Sorry whatever I try to get the logic of forestPlot I fail. What are you putting into the odds ratio? I can see this as odds of having the PML gene, but odds ratio has me confused. Why odd ratio is negative (apart from taking log)

![untitled](https://user-images.githubusercontent.com/43682980/73360897-c45cc680-429b-11ea-9e86-d19b6d59a12e.png)

Thank you for any help

**Comment by PoisonAlien** [comment]
Hello,
Odds ratios are from Fishers exact test estimated from `mafCompare` function. 

```r
> pt.vs.rt <- mafCompare(m1 = primary.apl, m2 = relapse.apl, m1Name = 'Primary',
                       m2Name = 'Relapse', minMut = 5)
> pt.vs.rt
$results
   Hugo_Symbol Primary Relapse         pval         or       ci.up      ci.low      adjPval
1:         PML       1      11 1.529935e-05 0.03537381   0.2552937 0.000806034 0.0001376942
2:        RARA       0       7 2.574810e-04 0.00000000   0.3006159 0.000000000 0.0011586643
3:       RUNX1       1       5 1.310500e-02 0.08740567   0.8076265 0.001813280 0.0393149868
4:        FLT3      26       4 1.812779e-02 3.56086275  14.7701728 1.149009169 0.0407875250
5:      ARID1B       5       8 2.758396e-02 0.26480490   0.9698686 0.064804160 0.0496511201
6:         WT1      20      14 2.229087e-01 0.60619329   1.4223101 0.263440988 0.3343630535
7:        KRAS       6       1 4.334067e-01 2.88486293 135.5393108 0.337679367 0.4897762916
8:        NRAS      15       4 4.353567e-01 1.85209500   8.0373994 0.553883512 0.4897762916
9:      ARID1A       7       4 7.457274e-01 0.80869223   3.9297309 0.195710173 0.7457273717

$SampleSummary
    Cohort SampleSize
1: Primary        124
2: Relapse         58
```

In the above list `results` contains details about fishers output. Simple way to interpret the first row is that the odds of observing  `PML` gene in `Primary` APL is quite low (0.03 times than in relapse). Similarly, 4th row, odds of observing `FLT3` in primary is quite high (3.56 times more likely than in relapse). These are the values plotted in forestplot on log10 scale. Hope this helps.

**Comment by beginner984** [comment]
Thank you very much

Quite explanatory

In my case 

![Picture1](https://user-images.githubusercontent.com/43682980/73367177-11926580-42a7-11ea-9156-e8293f143ac7.png)

**Comment by PoisonAlien** [comment]
`7 out of 94` is significantly different from `7 out of 31`

**Comment by beginner984** [comment]
Apologise @PoisonAlien 

I have compared two mafs

```
> head(pt.vs.rt$results)
   Hugo_Symbol Primary Relapse        pval       or      ci.up   ci.low   adjPval
1:        NAV3       0       8 0.007407514 0.000000  0.6570311 0.000000 0.1708848
2:        TPTE       5       0 0.013670784      Inf        Inf 1.254574 0.1708848
3:      AHNAK2       9       3 0.025101015 4.879954 31.1648231 1.063497 0.1915460
4:       ERBB4       0       6 0.030647360 0.000000  1.0033597 0.000000 0.1915460
5:      GABRA4       0       5 0.061822725 0.000000  1.3189994 0.000000 0.2575947
6:       KCNQ3       0       5 0.061822725 0.000000  1.3189994 0.000000 0.2575947
>
```

The results says that `ERBB2` has been mutated in none of 30 primary samples versus 6 of 38 relapse samples

But this plot likely says that ERBB2 has been mutated only once in both groups

![Rplot01](https://user-images.githubusercontent.com/43682980/84608493-aab6c700-aeaa-11ea-98b9-1d2c3b799581.png)

Thank you for any help

**Comment by PoisonAlien** [comment]
Results in from mafCompare has no `ERBB2`. Its `ERBB4`.
