### ISSUE TITLE
Help with oncoPlot

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#465]
Hi

In oncoPlot how I can know the specific  `TumorSampleBarcode` from oncoPlot?

Please look at these oncoPlot drawn by 
`oncoplot(maf = laml, top = 10,  showTumorSampleBarcodes = TRUE)`

![Rplot124](https://user-images.githubusercontent.com/60115705/73615653-862f1200-45cf-11ea-93fe-d1513591ef1f.png)

If I want to know the `TumorSampleBarcode` of some highly mutated samples how I can know when `TumorSampleBarcodes`  are not clear and I can not read ID of each bar

Thank you for any help

**Comment by PoisonAlien** [comment]
Hello,
Its always tricky when you have lots of samples. You can do two things. Play around `barcode_mar` and `SampleNamefontSize` arguments. Also save your plot to high res pdf with large height and width.
