### ISSUE TITLE
Discrepency of segment mean and GISTIC oncoplot

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#466]
Good morning 

I have read gistic results along with MAF and by 

```
laml.plus.gistic = read.maf(
  maf = my.maf,
  gisticAllLesionsFile = all.lesions,
  gisticAmpGenesFile = amp.genes,
  gisticDelGenesFile = del.genes,
  gisticScoresFile = scores.gis,
  isTCGA = FALSE,
  verbose = FALSE, 
  clinicalData = my.clin
)

oncoplot(maf = laml.plus.gistic, top = 10)
```

I have this

![Picture2](https://user-images.githubusercontent.com/43682980/73735691-94983d80-4737-11ea-9027-dd2921a10387.png)

I also have read CN alterations and by

```
laml.plus.cn = read.maf(maf = my.maf,
                        cnTable = my.cn.data,
                        verbose = FALSE)


oncoplot(maf = laml.plus.cn, top = 5)
```
I have 

![Picture1](https://user-images.githubusercontent.com/43682980/73735842-c7dacc80-4737-11ea-9569-5b01ecaaff34.png)

If you please look at these plots, `CDKN2A `has deletion in `14 out of 33 samples` by `GISTIC` while has deletion only in `3/33` samples in `custom copy number data`

Could you please help in getting intuition how this is possible. I guessed the swapped way makes more sense if a number of samples have deleted segments (segment mean < -1) among which only some segments/genes are significantly detected (by GISTIC)

So you think this confusion comes from my wrong segment mean calculation or running GISTIC?

 Thank you for any help

**Comment by beginner984** [comment]
Sorry I am still struggling with this confusion

What is your threshold in GISTIC to be called deleted or amplified? I really don't know how describe this for myself

People says that GISTIC scoring for deletion and amplification like 2,1,0,-1,-2 scores come in 
all_thresholded.by_gene file which contains these calls for each gene.file but maftools does not use this file to show GISTIC

all_lesions files has thresholded calls for GISTIC peaks.  In this case the deletion calls 1 and 2 can be considered -1 and -2.

Please correct me if I am wrong

Thank you

**Comment by ShixiangWang** [comment]
@beginner984 I got your email. I cannot find a problem with the two plots above. Could you show some of your custom copy number data?

**Comment by ShixiangWang** [comment]
@beginner984 I also check the code to read the gistic2 data. I can tell you that the deletion status comes from all.lesions file. Maftools does not use any threshold to define if a gene altered. The data comes from gistic2.

https://github.com/PoisonAlien/maftools/blob/acdfbb638d72ba3084d98425ea446d2735f97dd9/R/readGistic.R#L39-L80

I cannot find any problem in the code. The issue may be raised by either your segment_mean value of custom copy number data (like threshold, transformation) or something else.

**Comment by PoisonAlien** [comment]
Hello @beginner984 ,
As @ShixiangWang pointed it out, amp or deletion status is obtained from `all_lesions` file based on the [values](https://github.com/PoisonAlien/maftools/blob/acdfbb638d72ba3084d98425ea446d2735f97dd9/R/readGistic.R#L72-L79). For your case, check how many samples have been deleted for `CDKN2A`.

1. Open your `del_genes` file and search for the column containing `CDKN2A` gene. It should be probably under `9q21.32` or something seimilar.
2. Go back to `all_lesions` file and search how many samples are annotated as deletion (1/2) for the row `9q21.32`  

That's how `maftools` parses and maps gistic results from genomic segments to sample names. Hope this helps. Please refer to GISTIC documentation for details.

**Comment by MaryGoAround** [comment]
Hi both

I got GISTIC part by maftools but my confusion is when CDKN2A recognised as deleted in 13 samples by GISTIC that does mean in 13 samples peak containing CDKN2A have been selected in 13 samples but segmentation file says that only 3 samples have CKDN2A deleted

My boss asked me to find the reason but I can not :(

**Comment by PoisonAlien** [comment]
Unfortunately I can not answer for these discrepancies. The function only sees whats present in the GISTIC output.

**Comment by MaryGoAround** [comment]
Thank you @ PoisonAlien :(
