### ISSUE TITLE
oncodrive and OncodriveCLUSTL

### ISSUE THREAD

**Issue by elenapapaleo** [PoisonAlien/maftools#467]
I was interested to try the oncodrive function but I noticed that the OncodriveCLUST is now outdated (see a message on the corresponding webpage:http://bg.upf.edu/group/projects/oncodrive-clust.php) and that now there is new algorithm OncodriveCLUSTL so I was wondering if it will be or not implemented in maftools to decide how to proceed.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for pointing it out. I was not aware of the updates made. However, I have not immediate plans to implement it into maftools :|
