### ISSUE TITLE
readin error for gzipped maf

### ISSUE THREAD

**Issue by ruolin** [PoisonAlien/maftools#468]
I just started to use R maftools. It is a great package, however there seems to be a bug when reading gzipped maf. 
For example, using this public file from TCGA https://portal.gdc.cancer.gov/files/995c0111-d90b-4140-bee7-3845436c3b42
Version: maftools_2.0.16 

reading using maftools yields 75811 records
        `nrow(tcga.brca.somatic.maf@data) `

however using fread yields 120988 records. 
I have seen some SNV being assigned to wrong samples using maftools. This is a critical problem since it will affect everything.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for using maftools and I am glad you find it useful. Regading the issue, `MAF` object includes only non-synonymous variants under `@data` slot, rest synonymous goes under `@maf.silent` slot. If you add up both it should be equal to your original number of rows.

```r
> nrow(brca@maf.silent) + nrow(brca@data)
120988
```

**Comment by ruolin** [comment]
Great. Thanks.
