### ISSUE TITLE
[estimateSignatures] error 

### ISSUE THREAD

**Issue by Hchang77** [PoisonAlien/maftools#469]
Hello

I  run the example codes for maftools. ( TCGA LAML MAF file)

I have error message when I try estimageSignatures.

I can get successful results when I try other analysis with NMF package.

Regards,

############

laml.sign = maftools::estimateSignatures(mat = laml.tnm, nTry = 6)
-Running NMF for 6 ranks
Compute NMF rank= 2  ... Timing stopped at: 1.21 0.02 2.98
ERROR
Compute NMF rank= 3  ... Timing stopped at: 1.41 0 3.36
ERROR
Compute NMF rank= 4  ... Timing stopped at: 1.3 0 3.22
ERROR
Compute NMF rank= 5  ... Timing stopped at: 1.48 0.02 4.48
ERROR
Compute NMF rank= 6  ... Timing stopped at: 2.11 0.03 4.8
ERROR
Error in (function (...)  : All the runs produced an error:
	-#1 [r=2] -> NMF::nmf - 10/10 fit(s) threw an error.
# Error(s) thrown:
  - run #1: non-conformable arrays
	-#2 [r=3] -> NMF::nmf - 10/10 fit(s) threw an error.
# Error(s) thrown:
  - run #1: non-conformable arrays
	-#3 [r=4] -> NMF::nmf - 10/10 fit(s) threw an error.
# Error(s) thrown:
  - run #1: non-conformable arrays
	-#4 [r=5] -> NMF::nmf - 10/10 fit(s) threw an error.
# Error(s) thrown:
  - run #1: non-conformable arrays
	-#5 [r=6] -> NMF::nmf - 10/10 fit(s) threw an error.
# Error(s) thrown:
  - run #1: non-conformable arrays

**Comment by ShixiangWang** [comment]
please load NMF package firstly.

**Comment by Hchang77** [comment]
Thank you for your rapid response.
I re-installed the NMF package and re-try the estimageSignatures according to your response.
However, I got the error again. 
Can I ask you another solution for this?

**Comment by ShixiangWang** [comment]
@Hchang77 I see you used the example data. Could you show all commands, your R session and their output here?

like 

```r
library(maftools)
library(NMF)
...
sessionInfo()
```

**Comment by PoisonAlien** [comment]
Maybe use the `pConstant = 0.1` and see if it helps.

**Comment by ShixiangWang** [comment]
@Hchang77 Yes, try @PoisonAlien suggested,  the example data should add a small constant for avoiding the problem from NMF decomposition. I think `pConstant = 1e-9` is okay.

**Comment by Hchang77** [comment]
Thank you for the nice anwer. The problem was solved.
And Thank you to the researchers  who made this wonderful program.
