### ISSUE TITLE
hg19 fasta

### ISSUE THREAD

**Issue by zayni** [PoisonAlien/maftools#47]
I was wondering which hg19 fasta is need for mutational plots

Thanks a lot!

Zayni

**Comment by PoisonAlien** [comment]
Hi,

All hg19 are same, except Ensemble doesn't use 'chr' prefix whereas ucsc does. See argument `prefix` while running  `trinucleotideMatrix` to add or remove prefixes.

**Comment by zayni** [comment]
Thanks a lot ! got it
Also, prepareMutsig functions is not working . Am I doing anything wrong ?
"prepareMutSig(maf = laml)
Error: could not find function "prepareMutSig"""

**Comment by PoisonAlien** [comment]
Hi,

Which version of maftools are you using ? Its on 1.2.0 on Bioconductor. Try updating it.
