### ISSUE TITLE
[SurvGroup] hr (hazard ratio)

### ISSUE THREAD

**Issue by Hchang77** [PoisonAlien/maftools#470]
Hello

I try your example (TCGA LAML MAF file) according to your introduction.
When I run the code  'SurvGroup'  for LAML data, I get the results as below (which is the same as those in your introduction)

SurvGroup function is to get the genes which are associated with POOR survival. 
However, three gene sets in the results are related with GOOD survival, because hr (Hazard ration) is below 1. (although P value is above 0.05)

Can I improve this results?

     Gene_combination P_value    hr  WT Mutant
  1:      FLT3_DNMT3A 0.00104 2.510 164     18
  2:      DNMT3A_SMC3 0.04880 2.220 176      6
  3:      DNMT3A_NPM1 0.07190 1.720 166     16
  4:      DNMT3A_TET2 0.19600 1.780 176      6
  5:        FLT3_TET2 0.20700 1.860 177      5
  6:        **NPM1_IDH1** 0.21900 **0.495** 176      6  
  7:      DNMT3A_IDH1 0.29300 1.500 173      9
  8:       IDH2_RUNX1 0.31800 1.580 176      6
  9:        FLT3_NPM1 0.53600 1.210 165     17
 10:      **DNMT3A_IDH2** 0.68000 **0.747** 178      4 
 11:      **DNMT3A**_NRAS 0.99200 **0.986** 178      4

**Comment by PoisonAlien** [comment]
Hi,
`SurvGroup` simply returns the p-value and HR for combination of genes. You will have to interpret the results. In the above case first two rows would be of interest solely based on p-values.

**Comment by Hchang77** [comment]
Thank you for your answer.
Can I ask you one more question for survGroup?
The results for gene-set depends on the top value. 
survGroup(..., top= 20,...)

For example with  TCGA LAML MAF file, top five gene-sets were different between top=20 and =5.

# top=20
   Gene_combination P_value    hr  WT Mutant
 1:      FLT3_DNMT3A 0.00104 2.510 164     18
 **2:      DNMT3A_SMC3 0.04880 2.220 176      6**
 3:      DNMT3A_NPM1 0.07190 1.720 166     16
 **4:      DNMT3A_TET2 0.19600 1.780 176      6
 5:        FLT3_TET2 0.20700 1.860 177      5**
 6:        NPM1_IDH1 0.21900 0.495 176      6
 7:      DNMT3A_IDH1 0.29300 1.500 173      9
 8:       IDH2_RUNX1 0.31800 1.580 176      6
 9:        FLT3_NPM1 0.53600 1.210 165     17
10:      DNMT3A_IDH2 0.68000 0.747 178      4
11:      DNMT3A_NRAS 0.99200 0.986 178      4

# top=5
 Gene_combination P_value    hr  WT Mutant
1:      FLT3_DNMT3A 0.00104 2.510 164     18
2:      DNMT3A_NPM1 0.07190 1.720 166     16
3:        NPM1_IDH1 0.21900 0.495 176      6
4:      DNMT3A_IDH1 0.29300 1.500 173      9
5:        FLT3_NPM1 0.53600 1.210 165     17
6:      DNMT3A_IDH2 0.68000 0.747 178      4

**Comment by PoisonAlien** [comment]
`top` argument corresponds to number of top highly mutated genes. As in top rows of `getGeneSummary()` output.

**Comment by Hchang77** [comment]
Thank you for your detailed response.
I understand that  firstly, survGroup function selects the candidate genes according to  the mutation frequency (in the top 20) and then calcutates gene-sets with significant P-value for survival.
