### ISSUE TITLE
Setting Altered Changes Annotation Colour Order

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#471]
Changing nothing else apart from the value of `altered`, the clinical data colouring swaps labels (for WGD but not for the second variable).

![image](https://user-images.githubusercontent.com/631218/74301479-4c1bf800-4da7-11ea-9836-7f8b48f52c6b.png)

This seems unintended.

**Comment by PoisonAlien** [comment]
Hello,
Sorry for the delay in getting back. Can you post your command? Does it happen when you manually provide colours for annotations?

**Comment by DarioS** [comment]
I could not trigger it using a minimal example, so you'll need to load the attached R objects [testData.zip](https://github.com/PoisonAlien/maftools/files/4272820/testData.zip) The command is

```r
load("testData.RData") # After unzipping.
oncoplot(MAF, colors = customColours, top = 50, showTumorSampleBarcodes = TRUE, removeNonMutated = FALSE,
         clinicalFeatures = c("WGD", "TP53_LOH"), sortByAnnotation = TRUE, sortByMutation = TRUE,
         annotationOrder = c("No", "Yes"), genesToIgnore = "TTN",
         gene_mar = 6, barcode_mar = 11)
```

Just add `altered = TRUE` to get the swapping of WGD legend.

**Comment by PoisonAlien** [comment]
Thanks for the data. I can reproduce it. I will take a look into it soon. Meanwhile you can use `annotationColor` argument to define color codes which should maintain the correct color order.

```r
oncoplot(
  MAF,
  colors = customColours,
  top = 50,
  showTumorSampleBarcodes = TRUE,
  removeNonMutated = FALSE,
  clinicalFeatures = c("WGD", "TP53_LOH"),
  sortByAnnotation = TRUE,
  sortByMutation = TRUE,
  annotationOrder = c("No", "Yes"),
  genesToIgnore = "TTN",
  gene_mar = 6,
  barcode_mar = 11,
  altered = TRUE,
  annotationColor = list(
    WGD = c("Yes" = "red", "No" = "blue"),
    TP53_LOH = c("Yes" = "red", "No" = "blue")
  )
)
```

**Comment by DarioS** [comment]
Swapping still happens in the latest release of maftools.

**Comment by PoisonAlien** [comment]
Hi, 
I'm on holidays. I'll fix them the next week.

**Comment by DarioS** [comment]
Stale but important.

**Comment by talban14** [comment]
I believe this is still an issue with the latest version.  It is also reversing colors on annotations at baseline.
