### ISSUE TITLE
Question about the meaning of mutation percentage in oncoplot

### ISSUE THREAD

**Issue by ShixiangWang** [PoisonAlien/maftools#472]
Dear @PoisonAlien,

I created an oncoplot with `MutSig` and `GISTIC` results included, like http://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/oncoplots.html#04_including_significance_values, but the percentage seems not right.

![image](https://user-images.githubusercontent.com/25057508/74590205-5fe58980-5047-11ea-8ff7-13171727ecf5.png)

What's the meaning of mutation percentage shown on the right? It is for variants from `MAF` object, or also include CNV info?

It also may be caused by `sepwd_samples = 0`, but if I don't change it to 0, the plot would be ugly.
 
```
oncoplot(maf_plus_gistic,
  mutsig = mutsig, mutsigQval = 0.05, sortByMutation = TRUE,
  logColBar = TRUE, sepwd_samples = 0, draw_titv = TRUE
)
```

I also checked an oncoplot from http://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/oncoplots.html#031_gistic_results, the mark for `del` is variable, am I right?

![image](https://user-images.githubusercontent.com/25057508/74590445-637a1000-5049-11ea-83db-9c2f6e8bb180.png)

Best,

Shixiang

**Comment by ShixiangWang** [comment]
I just created an oncoplot without GISTIC2 data.

![image](https://user-images.githubusercontent.com/25057508/74590725-e734fc00-504b-11ea-9089-dd410a1ee209.png)

I think the problem comes from plotting function.

**Comment by PoisonAlien** [comment]
Hello @ShixiangWang ,
Sorry for the delay. I will look into it.. 

> I think the problem comes from plotting function.

I doubt the same..

**Comment by PoisonAlien** [comment]
Hi @ShixiangWang ,
Sorry for the delay, and thanks for noticing the borders for copy-number variants. I have fixed it and it should be consistent with the grid size. Regarding the mutation rate, its a fraction of number altered samples to the total number of samples in the cohort. You can check the altered samples (either mutation or CNV) with  `getGeneSummary`. Hope this helps.

**Comment by ShixiangWang** [comment]
Thanks
