### ISSUE TITLE
Add more than one additionalFeature in oncoplot

### ISSUE THREAD

**Issue by Tato14** [PoisonAlien/maftools#476]
As you mention in the code, you can add `additionalFeature` using "a vector of length two indicating column name in the MAF and the factor level to be highlighted". Is it possible to add more than one `additionalFeature` pair with and specific `shape` or `color` for each? Following your example: 

Intead of: additionalFeature = c("Tumor_Seq_Allele2", "C")
Use: additionalFeature = c(("Tumor_Seq_Allele2", "C"), ("Tumor_Seq_Allele2", "G"))

Thanks!

**Comment by PoisonAlien** [comment]
Hello,
With the current implementation it is not possible. But I am happy to implement it. I will update it and let you know.

**Comment by Tato14** [comment]
That would  be awesome! Thanks!

**Comment by PoisonAlien** [comment]
Hello again,
I have pushed some changes which should add help to map more than one additional features. Could you please try and let me know if it works for you? example usage is as below. `additionalFeature` should be a list of vectors to be highlighted. Below example will highlight all variants on chromosome 13 and mutated to C.

```r
oncoplot(
  maf = laml,
  additionalFeature = list(c("Chromosome", "13"), c("Tumor_Seq_Allele2", "C")),
  additionalFeatureCol = c("red", "green"),
  additionalFeaturePch = c(12, 13)
)
```

Hope this helps.

**Comment by Tato14** [comment]
Hi, 

Seems that it doesn't work for me:

```
oncoplot(maf = LMMC_Oligo_MAF,
          additionalFeature = list(c("Tumor_Seq_Allele2", "C"), c("Chromosome", "11")),
          additionalFeatureCol = c("red", "green"),
          additionalFeaturePch = c(12, 13))
Missing fields. Ignoring them.. 
[[1]]
[1] "Tumor_Seq_Allele2" "C"                

Error in `[.data.table`(maf.dat, , default.fields, with = FALSE) : 
  When with=FALSE, j-argument should be of type logical/character/integer indicating the columns to select.
```

**Comment by PoisonAlien** [comment]
Just to be sure, you installed it from GitHub again rite?

**Comment by Tato14** [comment]
It worked in my laptop. I am not sure if there is some R version problems. In any case the code you pushed works nicely :smile: 
Thanks

**Comment by PoisonAlien** [comment]
Thanks for checking. I am closing the issue for now, please feel free to reopen if necessary.
