### ISSUE TITLE
Problems in mafSurvival

### ISSUE THREAD

**Issue by Kevinhokahey** [PoisonAlien/maftools#477]
Hello 
This is Kevin. Thank you so much for this package. It is wonderful. I download TCGA-LUAD maf data from TCGA and try to learn more of this package. In the process of survival analysis, I tried to use mafSurvival to compare the survival outcomes of different genes. Unfortunately, it showed as below:
Median survival..
Group medianTime N
1: WT 626 772
Error in survdiff.fit(y, groups, strata.keep, rho) :
There is only 1 group

I have no idea why there is only WT group without mutant group. The maf should be fine because I have tried oncoplot before move to the survival analysis. 
Thank you so much.

**Comment by PoisonAlien** [comment]
Hello Kevin,
Could you please post your full command? Also check if your gene of interest is really mutated or not.

**Comment by Kevinhokahey** [comment]
Hello. The full commands are as follow: 
`> luad.clin="clinical.tsv"
> luad.maf="TCGA.LUAD.maf.gz"
> library(maftools)
> luad<-read.maf(maf=luad.maf)
> data<-read.table(luad.clin,sep="\t",header=TRUE,stringsAsFactors = FALSE)
> library(dplyr)
data<-rename(data,c("Tumor_Sample_Barcode"="submitter_id"))
> data$days_to_last_follow_up=as.numeric(data$days_to_last_follow_up)
> data$vital_status[data$vital_status=="Dead"]<-"1"
> data$vital_status[data$vital_status=="Alive"]<-"0"
> mafSurvival(maf=luad, genes="TP53", time='days_to_last_follow_up', Status='vital_status',clinicalData=data,isTCGA=TRUE)`
I changed the column name of the clinical data table and coded the vital status as "1/0".  Then I try to do a survival analysis in gene TP53. I believed this gene must be mutated. But after I typed in all these commands, it turned out to be only 1 group. 

BTW, if I changed some commands:
'>luad<-read.maf(maf=luad.maf, clinicalData=data)
>mafSurvival(maf=luad, genes="TP53", time='days_to_last_follow_up', Status='vital_status',isTCGA=TRUE)'
I put "clinicalData=data" in the first command rather than the next one. The result turned out to be:

Looking for clinical data in annoatation slot of MAF..
Number of mutated samples for given genes: 
TP53 
 270 
Median survival..
Empty data.table (0 rows and 3 cols): Group,medianTime,N
Error in survival::Surv(time = Time, event = Status) : 
  Time variable is not numeric

This is really confusing. Thank you so much for your help.

**Comment by Kevinhokahey** [comment]
> Hello Kevin,
> Could you please post your full command? Also check if your gene of interest is really mutated or not.

Hello. The full commands are as follow:
`
luad.clin="clinical.tsv"
luad.maf="TCGA.LUAD.maf.gz"
library(maftools)
luad<-read.maf(maf=luad.maf)
data<-read.table(luad.clin,sep="\t",header=TRUE,stringsAsFactors = FALSE)
library(dplyr)
data<-rename(data,c("Tumor_Sample_Barcode"="submitter_id"))
data$days_to_last_follow_up=as.numeric(data$days_to_last_follow_up)
data$vital_status[data$vital_status=="Dead"]<-"1"
data$vital_status[data$vital_status=="Alive"]<-"0"
mafSurvival(maf=luad, genes="TP53", time='days_to_last_follow_up', Status='vital_status',clinicalData=data,isTCGA=TRUE)`

I changed the column name of the clinical data table and coded the vital status as "1/0". Then I try to do a survival analysis in gene TP53. I believed this gene must be mutated. But after I typed in all these commands, it turned out to be only 1 group.

BTW, if I changed some commands:
'
luad<-read.maf(maf=luad.maf, clinicalData=data)
mafSurvival(maf=luad, genes="TP53", time='days_to_last_follow_up', Status='vital_status',isTCGA=TRUE)
'

I put "clinicalData=data" in the first command rather than the next one. The result turned out to be:

Looking for clinical data in annoatation slot of MAF..
Number of mutated samples for given genes:
TP53
270
Median survival..
Empty data.table (0 rows and 3 cols): Group,medianTime,N
Error in survival::Surv(time = Time, event = Status) :
Time variable is not numeric

This is really confusing. Thank you so much for your help.

**Comment by ShixiangWang** [comment]
Could you try set status to integer instead of character?

```r
data$vital_status[data$vital_status=="Dead"]<-1
data$vital_status[data$vital_status=="Alive"]<- 0
```

If still get an error, please print the output of the following commands:

```r
getSampleSummary(luad)
str(data)
```

**Comment by PoisonAlien** [comment]
Okay let me try downloading the data from GDC and see if I can reproduce the issue.

**Comment by Kevinhokahey** [comment]
> Could you try set status to integer instead of character?
> 
> ```r
> data$vital_status[data$vital_status=="Dead"]<-1
> data$vital_status[data$vital_status=="Alive"]<- 0
> ```
> 
> If still get an error, please print the output of the following commands:
> 
> ```r
> getSampleSummary(luad)
> str(data)
> ```

Thanks for your reply. I try to set status to integer following your suggestion. But the error still exists.
The output is as follow:
           Tumor_Sample_Barcode Frame_Shift_Del Frame_Shift_Ins In_Frame_Del In_Frame_Ins
  1: TCGA-17-Z031-01A-01W-0746-08              35               8            3            0
  2: TCGA-05-4382-01A-01D-1931-08              32              13            2            1
  3: TCGA-55-8506-01A-11D-2393-08              96              38            7            0
  4: TCGA-55-7994-01A-11D-2184-08              43              10            2            1
  5: TCGA-L9-A7SV-01A-11D-A397-08              22               8            2            1
 ---                                                                                       
561: TCGA-L4-A4E6-01A-11D-A24D-08               0               1            0            1
562: TCGA-44-6148-01A-11D-1753-08               1               0            0            0
563: TCGA-55-8513-01A-11D-2393-08               2               0            0            0
564: TCGA-55-7816-01A-11D-2167-08               0               1            0            1
565: TCGA-49-AARR-01A-11D-A410-08               0               0            0            0
     Missense_Mutation Nonsense_Mutation Nonstop_Mutation Splice_Site Translation_Start_Site total
  1:              1638               111                2          47                      3  1847
  2:              1303               113                2          50                      2  1518
  3:              1203                88                0          45                      5  1482
  4:              1133                95                1          35                      2  1322
  5:              1132               109                4          32                      2  1312
 ---                                                                                              
561:                 5                 0                0           0                      0     7
562:                 5                 0                0           0                      0     6
563:                 3                 0                0           0                      0     5
564:                 2                 0                0           0                      0     4
565:                 3                 0                0           0                      0     3

str(data)
Classes ‘data.table’ and 'data.frame':	1034 obs. of  161 variables:
 $ case_id                                 : chr  "e0acafdd-06d0-48a6-bd68-577ef666a419" "e0acafdd-06d0-48a6-bd68-577ef666a419" "bab43415-d413-40be-a4c0-2c40a52afe6a" "bab43415-d413-40be-a4c0-2c40a52afe6a" ...
 $ Tumor_Sample_Barcode                    : chr  "TCGA-95-7947" "TCGA-95-7947" "TCGA-44-2668" "TCGA-44-2668" ...
 $ project_id                              : chr  "TCGA-LUAD" "TCGA-LUAD" "TCGA-LUAD" "TCGA-LUAD" ...
 $ age_at_index                            : chr  "67" "67" "51" "51" ...
 $ age_is_obfuscated                       : chr  "--" "--" "--" "--" ...
 $ cause_of_death                          : chr  "--" "--" "--" "--" ...
 $ cause_of_death_source                   : chr  "--" "--" "--" "--" ...
 $ created_datetime                        : chr  "--" "--" "--" "--" ...
 $ days_to_birth                           : chr  "-24752" "-24752" "-18856" "-18856" ...
 $ days_to_death                           : chr  "--" "--" "761" "761" ...
 $ demographic_id                          : chr  "d3d64a9e-1b32-51a3-a30e-529027d399a4" "d3d64a9e-1b32-51a3-a30e-529027d399a4" "8c08c48a-dee8-5400-9e26-9c968a47702f" "8c08c48a-dee8-5400-9e26-9c968a47702f" ...
 $ ethnicity                               : chr  "not hispanic or latino" "not hispanic or latino" "not hispanic or latino" "not hispanic or latino" ...
 $ gender                                  : chr  "male" "male" "male" "male" ...
 $ occupation_duration_years               : chr  "--" "--" "--" "--" ...
 $ premature_at_birth                      : chr  "--" "--" "--" "--" ...
 $ race                                    : chr  "white" "white" "white" "white" ...
 $ state                                   : chr  "released" "released" "released" "released" ...
 $ submitter_id.1                          : chr  "TCGA-95-7947_demographic" "TCGA-95-7947_demographic" "TCGA-44-2668_demographic" "TCGA-44-2668_demographic" ...
 $ updated_datetime                        : chr  "2019-07-31T20:41:15.322866-05:00" "2019-07-31T20:41:15.322866-05:00" "2019-07-31T15:14:10.035142-05:00" "2019-07-31T15:14:10.035142-05:00" ...
 $ vital_status                            : int  0 0 1 1 0 0 0 0 0 0 ...
 $ weeks_gestation_at_birth                : chr  "--" "--" "--" "--" ...
 $ year_of_birth                           : chr  "1944" "1944" "1958" "1958" ...
 $ year_of_death                           : chr  "--" "--" "--" "--" ...
 $ age_at_diagnosis                        : chr  "24752" "24752" "18856" "18856" ...
 $ ajcc_clinical_m                         : chr  "--" "--" "--" "--" ...
 $ ajcc_clinical_n                         : chr  "--" "--" "--" "--" ...
 $ ajcc_clinical_stage                     : chr  "--" "--" "--" "--" ...
 $ ajcc_clinical_t                         : chr  "--" "--" "--" "--" ...
 $ ajcc_pathologic_m                       : chr  "M0" "M0" "M0" "M0" ...
 $ ajcc_pathologic_n                       : chr  "N0" "N0" "N0" "N0" ...
 $ ajcc_pathologic_stage                   : chr  "Stage IA" "Stage IA" "Stage IB" "Stage IB" ...
 $ ajcc_pathologic_t                       : chr  "T1a" "T1a" "T2" "T2" ...
 $ ajcc_staging_system_edition             : chr  "7th" "7th" "6th" "6th" ...
 $ anaplasia_present                       : chr  "--" "--" "--" "--" ...
 $ anaplasia_present_type                  : chr  "--" "--" "--" "--" ...
 $ ann_arbor_b_symptoms                    : chr  "--" "--" "--" "--" ...
 $ ann_arbor_clinical_stage                : chr  "--" "--" "--" "--" ...
 $ ann_arbor_extranodal_involvement        : chr  "--" "--" "--" "--" ...
 $ ann_arbor_pathologic_stage              : chr  "--" "--" "--" "--" ...
 $ annotation_id                           : chr  "--" "--" "--" "--" ...
 $ case_id.1                               : chr  "--" "--" "--" "--" ...
 $ case_submitter_id                       : chr  "--" "--" "--" "--" ...
 $ category                                : chr  "--" "--" "--" "--" ...
 $ classification                          : chr  "--" "--" "--" "--" ...
 $ created_datetime.1                      : chr  "--" "--" "--" "--" ...
 $ creator                                 : chr  "--" "--" "--" "--" ...
 $ entity_id                               : chr  "--" "--" "--" "--" ...
 $ entity_submitter_id                     : chr  "--" "--" "--" "--" ...
 $ entity_type                             : chr  "--" "--" "--" "--" ...
 $ legacy_created_datetime                 : chr  "--" "--" "--" "--" ...
 $ legacy_updated_datetime                 : chr  "--" "--" "--" "--" ...
 $ notes                                   : chr  "--" "--" "--" "--" ...
 $ state.1                                 : chr  "--" "--" "--" "--" ...
 $ status                                  : chr  "--" "--" "--" "--" ...
 $ submitter_id.2                          : chr  "--" "--" "--" "--" ...
 $ updated_datetime.1                      : chr  "--" "--" "--" "--" ...
 $ best_overall_response                   : chr  "--" "--" "--" "--" ...
 $ breslow_thickness                       : chr  "--" "--" "--" "--" ...
 $ burkitt_lymphoma_clinical_variant       : chr  "--" "--" "--" "--" ...
 $ child_pugh_classification               : chr  "--" "--" "--" "--" ...
 $ circumferential_resection_margin        : chr  "--" "--" "--" "--" ...
 $ classification_of_tumor                 : chr  "not reported" "not reported" "not reported" "not reported" ...
 $ cog_liver_stage                         : chr  "--" "--" "--" "--" ...
 $ cog_neuroblastoma_risk_group            : chr  "--" "--" "--" "--" ...
 $ cog_renal_stage                         : chr  "--" "--" "--" "--" ...
 $ cog_rhabdomyosarcoma_risk_group         : chr  "--" "--" "--" "--" ...
 $ created_datetime.2                      : chr  "--" "--" "--" "--" ...
 $ days_to_best_overall_response           : chr  "--" "--" "--" "--" ...
 $ days_to_diagnosis                       : chr  "--" "--" "--" "--" ...
 $ days_to_last_follow_up                  : num  477 477 246 246 610 610 852 852 739 739 ...
 $ days_to_last_known_disease_status       : chr  "--" "--" "--" "--" ...
 $ days_to_recurrence                      : chr  "--" "--" "--" "--" ...
 $ diagnosis_id                            : chr  "8f9d1140-b278-57db-bda1-a79e0a0d2685" "8f9d1140-b278-57db-bda1-a79e0a0d2685" "62552a9f-3f39-5833-b1c6-6466e93a530e" "62552a9f-3f39-5833-b1c6-6466e93a530e" ...
 $ enneking_msts_grade                     : chr  "--" "--" "--" "--" ...
 $ enneking_msts_metastasis                : chr  "--" "--" "--" "--" ...
 $ enneking_msts_stage                     : chr  "--" "--" "--" "--" ...
 $ enneking_msts_tumor_site                : chr  "--" "--" "--" "--" ...
 $ esophageal_columnar_dysplasia_degree    : chr  "--" "--" "--" "--" ...
 $ esophageal_columnar_metaplasia_present  : chr  "--" "--" "--" "--" ...
 $ figo_stage                              : chr  "--" "--" "--" "--" ...
 $ first_symptom_prior_to_diagnosis        : chr  "--" "--" "--" "--" ...
 $ gastric_esophageal_junction_involvement : chr  "--" "--" "--" "--" ...
 $ gleason_grade_group                     : chr  "--" "--" "--" "--" ...
 $ goblet_cells_columnar_mucosa_present    : chr  "--" "--" "--" "--" ...
 $ gross_tumor_weight                      : chr  "--" "--" "--" "--" ...
 $ icd_10_code                             : chr  "C34.1" "C34.1" "C34.1" "C34.1" ...
 $ igcccg_stage                            : chr  "--" "--" "--" "--" ...
 $ inpc_grade                              : chr  "--" "--" "--" "--" ...
 $ inpc_histologic_group                   : chr  "--" "--" "--" "--" ...
 $ inrg_stage                              : chr  "--" "--" "--" "--" ...
 $ inss_stage                              : chr  "--" "--" "--" "--" ...
 $ international_prognostic_index          : chr  "--" "--" "--" "--" ...
 $ irs_group                               : chr  "--" "--" "--" "--" ...
 $ irs_stage                               : chr  "--" "--" "--" "--" ...
 $ ishak_fibrosis_score                    : chr  "--" "--" "--" "--" ...
 $ iss_stage                               : chr  "--" "--" "--" "--" ...
 $ largest_extrapelvic_peritoneal_focus    : chr  "--" "--" "--" "--" ...
 $ last_known_disease_status               : chr  "not reported" "not reported" "not reported" "not reported" ...
 $ laterality                              : chr  "--" "--" "--" "--" ...
  [list output truncated]
 - attr(*, ".internal.selfref")=<externalptr>

**Comment by Kevinhokahey** [comment]
> Okay let me try downloading the data from GDC and see if I can reproduce the issue.

Thank you so much. The file I downloaded from TCGA is TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf.gz. And its clinical data which is  a zip contains clinical.tsv.
I used Mac Terminal gdc_client to download the data.

**Comment by PoisonAlien** [comment]
Seems to work for me.

```r
> cd = data.table::fread(input = "~/Downloads/clinical.project-TCGA-LUAD.2020-03-01/clinical.tsv")
> colnames(cd)[2] = "Tumor_Sample_Barcode"
> cd$surv_status = ifelse(test = cd$vital_status == "Dead", yes = 1, no = 0)
> luad = read.maf(maf = "~/Downloads/clinical.project-TCGA-LUAD.2020-03-01/0458c57f-316c-4a7c-9294-ccd11c97c2f9/TCGA.LUAD.mutect.0458c57f-316c-4a7c-9294-ccd11c97c2f9.DR-10.0.somatic.maf.gz", clinicalData = cd, isTCGA = TRUE)
> mafSurvival(maf = luad, genes = "TP53", time = "days_to_last_follow_up", Status = "surv_status")
```
Can you try with above commands on your end?

**Comment by Kevinhokahey** [comment]
> ```r
> mafSurvival(maf = luad, genes = "TP53", time = "days_to_last_follow_up", Status = "surv_status")
> ```

Seems to work for me as well~ You are amazing!
But I really have no idea why it did not work at the first time. I think there must be something wrong with my commands but I am just not good enough to find it. 
Thank you so much for your help!
