### ISSUE TITLE
removing duplicates 

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#478]
Hi, When I run annovarToMaf using the txt file generated by ANNOVAR, I got the message that 693 duplicates were removed. I am wondering what are the standards for removing duplicates here and if there is any way to prevent it from removing the so-called duplicates if I don't want it to since there are not exactly the duplicates based on my criteria. 

Thank you.

**Comment by PoisonAlien** [comment]
Hello,
Duplicates are [removed](https://github.com/PoisonAlien/maftools/blob/master/R/validateMaf.R#L26) based on variants occurring at same position in the same sample. If you dont want to remove them, then just convert your txt files to maf data.frame with `MAFobj = FALSE`. Then pass the resulting data.frame to `read.maf` function with argument `removeDuplicatedVariants = FALSE`. Hope this helps.

**Comment by xiw588** [comment]
Thank you for your quick response. It works! But I am still a bit confused since I looked back to the original dataset generated by ANNOVAR and actually I didn't see the removed rows were duplicated based on the definition you gave here. So the sample here is the subject, right? 

Thank you for your help.

**Comment by xiw588** [comment]
And also, do you know how to change the margin of the figure (either for oncogenic pathways) and oncoplot with gene names cropped. 
![Screen Shot 2020-03-05 at 2 35 28 PM](https://user-images.githubusercontent.com/31411260/76018996-0ad2c000-5eef-11ea-90ca-0beb6f5b4e05.png)

**Comment by PoisonAlien** [comment]
Hi,
Yes, sample here means the subject. For oncoplot you can use `gene_mar` argument to increase the default space. See `?oncoplot` for more details.
