### ISSUE TITLE
Filter based annotation of variations in a MAF file

### ISSUE THREAD

**Issue by biobug16** [PoisonAlien/maftools#479]
Hi @PoisonAlien I am a newbie. 
I have maf files from our collaborators and want to perform variant effect prediction using PolyPhen , SIFT etc. Is there a workflow which I can follow to further annotate the effects of variations in the MAF files, may be using filter based annotation from annovar. I found many posts related to annovar to maf conversion but could not find anything for the reverse.
Kindly guide.
Thanks

**Comment by ShixiangWang** [comment]
VEP may be good for you

**Comment by PoisonAlien** [comment]
Hello @biobug16 ,
As suggested VEP would be a good option. You could also use [vcf2maf](https://github.com/mskcc/vcf2maf) which would directly take your maf and runs vep on it. Since this is not really tool related question I am closing this issue.
