### ISSUE TITLE
error in R studio

### ISSUE THREAD

**Issue by classycammy** [PoisonAlien/maftools#48]
Hi

Recently, I have downloaded the latest version of maftools in Rstudio in Mac. However, when I was loading the library, there is an error generated:

> library("maftools")
Error: package or namespace load failed for ‘maftools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rtracklayer/libs/rtracklayer.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rtracklayer/libs/rtracklayer.so, 6): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rtracklayer/libs/rtracklayer.so
  Reason: image not found

Any advise will be deeply appreciated.

**Comment by PoisonAlien** [comment]
Hi, 

Did you install it from Bioconductor ? It appears there is an issue with rtracklayer package. Could you try re-installing `rtracklayer` package ?

**Comment by classycammy** [comment]
Hi

I downloaded the tar.gz package from Bioconductor and loaded into R studio. Could this be the issue? Thank you so much for the help.


Cheers,
Camelia

**Comment by PoisonAlien** [comment]
Yes! Always install bioconductor packages through `biocLite` command. Run below code from your RStudio and it should work fine.

```r
source("https://bioconductor.org/biocLite.R")
biocLite("maftools")
```

Let me know if this doesn't work.

**Comment by classycammy** [comment]
Thanks very much for the help! I truly appreciate it.



--
Cheers
Cam

**Comment by PoisonAlien** [comment]
No problem. I hope it worked.

**Comment by lc0704** [comment]
Hi i have the same problem and i tried to run your codes: source("https://bioconductor.org/biocLite.R")
biocLite("maftools")
, but sadly it does not work for me....Do you have any other suggestions?
