### ISSUE TITLE
lollipopPlot2 error if there are not any mutation

### ISSUE THREAD

**Issue by carcarre11** [PoisonAlien/maftools#480]
Hi,
First of all congratulations because maftools is amazing. I could see that in lollipopPlot2 when you are comparing two different maf, there is an error if one of the maf has no mutations in the gene selected. In some cases, if you are comparing two maf files is because you would like show differences in the mutational phenotype between these two maf , showing that in one group there are mutations and are concentrated in the same domain and in the other group there are not any mutations. I recommend you to eliminate that error and generate only a warning.

**Comment by PoisonAlien** [comment]
Good point indeed. Thank you for the suggestion. I will fix it soon.

**Comment by PoisonAlien** [comment]
Hello,
Thanks again. I have fixed the issue. Could you please install again from GitHub and let me know if it works for you?

```r
BiocManager::install("PoisonAlien/maftools")
```

**Comment by carcarre11** [comment]
Hi,
Yes it works perfectly thanks a lot!. Only a little thing, if there are not any mutations in a gene in both maf the error message is  'At least one of the maf should contain mutations'. I would print also the gene name, it would be useful when you call the function in a loop with a list of interesting genes in which you don't know the mutation status in the groups before, to eliminate it from the list.

**Comment by PoisonAlien** [comment]
It prints the gene name prior to plotting. Thanks for the suggestions. I am closing the issue now, please feel free to reopen if necessary.
