### ISSUE TITLE
Filtering some variants before analysis

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#483]
Hello

I am using annular output as input for maftools

Is it possible in any stage to remove 1000 genome common variants common in at least 5% of samples before doing any analysis?

Actually I noticed my samples have a high mutational burden so I think it is more wise to remove gremlin variants before analysis by maftools

Thank you for any help

**Comment by PoisonAlien** [comment]
Hello,
Please note that `annovarToMaf` function only converts file formats. It does not do any sort of filtering. Having said that it is your responsibility to perform further necessary filtering steps. Have a look at `subsetMaf` function which might help you to filter by certain criteria. But there are no functions to perform specific filtering steps as you suggested.
