### ISSUE TITLE
Oncoplot and oncomatrix

### ISSUE THREAD

**Issue by kaigu1990** [PoisonAlien/maftools#484]
Maftools is a perfect tool, I'm used to clinical analysis by maftools
Recently, I find oncoplot don't rely on complexheatmap. There are some discordant layout when I plot oncoplot based on my data. And I also have some personal need, so I update oncoplot and oncomatrix code. Main changes:

* add anno_height feature to adjust the height of annotation layout
* Adjust the space between each legends because I have ten clinical features to show in graph.
* add drawBox feature to add a box around main matrix
* add drawExtraBar feature to replace mutation data in topbar because maybe someone would like show extra numeric cilical data

Visual description is below:
![Rplot03](https://user-images.githubusercontent.com/22772592/76705097-89620580-6718-11ea-97d9-d40814a2ebfd.png)

I have forked your project in [https://github.com/kaigu1990/maftools](https://github.com/kaigu1990/maftools)

**Comment by ShixiangWang** [comment]
@kaigu1990 Kai, you should provide a pull request instead of an issue.

I am curious why you introduce white space?

![image](https://user-images.githubusercontent.com/25057508/76735480-f4a2ea80-679f-11ea-9d17-bc3452205373.png)

**Comment by kaigu1990** [comment]
@ShixiangWang Shixiang, I‘m unfamiliar with pulling request so don't use it hastily.
The query you point out is result that there are some synonymous mutation (not including in maftools) in my MAF data, but I don't add them in vc_nonSyn parameter

**Comment by PoisonAlien** [comment]
Hi thank you both. 
This has been implemented. I closing the issue.
