### ISSUE TITLE
RFE: allow setting y limits in gisticChromPlot

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#485]
The reason for this request is that often I get requests from the wet lab that plots should all have the same scale for publication purposes. This is currently not possible in gisticChromPlot.

**Comment by PoisonAlien** [comment]
Hi,
I have made an argument `y_lims` to the function. Please try it and let me know if it works for you.

Example:
```r
gisticChromPlot(laml.gistic, y_lims = c(-0.2, 0.2))
```

**Comment by lbeltrame** [comment]
Works, thanks!
