### ISSUE TITLE
Is this possible to achieve this visualisation by maftools

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#486]
Hi

Indeed, this is not an issue with your software rather my query about the possibility of a sort of visualisation

Please, you imagine I have two groups of patients for which I want to look at mutations in a fixed set of genes

That would be great if one could show hits and type of mutation for each gene in each group in a way to be comparable like the below figure 

![Picture](https://user-images.githubusercontent.com/43682980/77422008-b1123700-6dc4-11ea-97e3-b41ae5b36346.png)

If there any function in your software to make this possible? If not do you have any suggestion to achieve such a view?

Thanks in advance

**Comment by PoisonAlien** [comment]
Well, closest option for you is cooncoplot. Split your maf into `naive` and `treated`. Use `coOncoplot`. You can even compare these cohorts with `mafCompare` to get statistically significant results, and show them as a `forestplot`.
But if you want the exact visualisation, I can implement a function for it. It looks fairly simple.

**Comment by beginner984** [comment]
Thank you so much for responding
Please, you imagine for instance the hits for TP53 is definitely different for two groups even by annotation  samples and group them, again hits and mutation type are not separated well
That would be extremely helpful if you go ahead with such a function
Thanks again in advance

**Comment by beginner984** [comment]
Hello

I have added GISTIC to mutation to each group

This is oncoplot for first group

![Rplot09](https://user-images.githubusercontent.com/43682980/77491098-bd35dd00-6e34-11ea-8d30-cbc21d339728.png)

And this is oncoplot for second group

![Rplot11](https://user-images.githubusercontent.com/43682980/77491149-df2f5f80-6e34-11ea-9dc8-b4940a71f20e.png)

But when I tried both side by side by this line note all genes being shown

`coOncoplot(m1 = a, m2 = b, m1Name = 'Response', m2Name = 'Nonresponse',removeNonMutated = TRUE)`

![Rplot12](https://user-images.githubusercontent.com/43682980/77491237-1f8edd80-6e35-11ea-8a62-f2d82308732e.png)

This is my mafs

https://www.dropbox.com/s/p0bzfb10uw8mq0b/a.maf?dl=0

https://www.dropbox.com/s/hhnmu79jj1bkvom/b.maf?dl=0

**Comment by PoisonAlien** [comment]
Hello,
Thanks again. I have implemented a function `coBarplot` which should do what you are asking for. Please install from GitHub for the update. Please let me know if this helps.

Example usage with example maf files in maftools:
```r
> coBarplot(m1 = primary.apl, m2 = relapse.apl, m1Name = 'Primary APL', m2Name = 'Relapse APL')
```
![image](https://user-images.githubusercontent.com/8164062/77560135-54df0e00-6ebd-11ea-96d7-69709246d5e4.png)

**Comment by beginner984** [comment]
That was simply amazing 

Is it possible to sort the genes based on percentage regarding one cohort to make the plot more tidy?

**Comment by PoisonAlien** [comment]
It keeps the same order of the given genes. 
Anyway, I have added `orderBy` argument. Set it `m1` or `m2`. Set it to `NULL` (default) to keep the same order as in `genes`.

**Comment by beginner984** [comment]
Thank you so much 

I don't know why I am getting error

```

> coBarplot(
+   a,
+   b,
+   genes = t(frankel),
+   m1Name = "Response",
+   m2Name = "Nonresponse",
+   colors = NULL,
+   normalize = TRUE,
+   yLims = NULL,
+   borderCol = "gray",
+   titleSize = 1,
+   geneSize = 0.8,
+   showPct = FALSE,
+   pctSize = 0.7,
+   axisSize = 0.8,
+   legendTxtSize = 1,orderBy="b")
Error in match.arg(arg = orderBy, choices = c("m1", "m2"), several.ok = FALSE) : 
  'arg' should be one of “m1”, “m2”
> coBarplot(
+   a,
+   b,
+   genes = t(frankel),
+   m1Name = "Response",
+   m2Name = "Nonresponse",
+   colors = NULL,
+   normalize = TRUE,
+   yLims = NULL,
+   borderCol = "gray",
+   titleSize = 1,
+   geneSize = 0.8,
+   showPct = FALSE,
+   pctSize = 0.7,
+   axisSize = 0.8,
+   legendTxtSize = 1,orderBy=b)
Error in match.arg(arg = orderBy, choices = c("m1", "m2"), several.ok = FALSE) : 
  'arg' must be NULL or a character vector
>
```

**Comment by PoisonAlien** [comment]
I think the error is quite clear. `orderBy` can only be `m1` or `m2`. Not `b`.
