### ISSUE TITLE
annovar  add startloss and startgain as functional consequences that affects the first ATG codon

### ISSUE THREAD

**Issue by 2236529177** [PoisonAlien/maftools#487]
annovar  add startloss and startgain as functional consequences that affects the first ATG codon, but maftools does not support this, and some keys in maftools function annovarToMaf is duplicated, like ncRNA

will here add the updates in annoar, thanks a lot.
another question is how somaticInteractions calculate the co-occurence?

![image](https://user-images.githubusercontent.com/25199946/77609711-ae961580-6f5b-11ea-9f38-23a58138d995.png)

**Comment by PoisonAlien** [comment]
Hello,
I can not seem to find `startloss` and `startgain` in annovar [specification](http://annovar.openbioinformatics.org/en/latest/user-guide/gene/#output-file-2-refseq-gene-annotation). Could you point me to the right source.

`somaticInteractions` uses fishers test based odds ratio for co-occurance or exclusive events. Please do refer to publication for more details.

**Comment by 2236529177** [comment]
thanks a lot.
1   here is the new update about the startloss and gain
https://doc-openbio.readthedocs.io/projects/annovar/en/latest/
![image](https://user-images.githubusercontent.com/25199946/77627819-6dfdc280-6f82-11ea-8bc9-412d04436177.png)

<br>
2 yes , I have read the output, it used F test, for small numbers, use exact test.
<br>
3  
![image](https://user-images.githubusercontent.com/25199946/77628460-0c8a2380-6f83-11ea-988f-d3efd53a66b5.png)

<br>
4  process go on for too long
![image](https://user-images.githubusercontent.com/25199946/77628810-84584e00-6f83-11ea-9bb0-6811a6dd23a3.png)
<br>
5  how this rate is calculated?
![image](https://user-images.githubusercontent.com/25199946/77628910-aa7dee00-6f83-11ea-814b-f2cca506fd4c.png)

**Comment by 2236529177** [comment]
![image](https://user-images.githubusercontent.com/25199946/77629304-44459b00-6f84-11ea-9fb5-1aec9542c721.png)

**Comment by 2236529177** [comment]
![image](https://user-images.githubusercontent.com/25199946/77631444-8b815b00-6f87-11ea-8834-63af0729fbbc.png)

**Comment by PoisonAlien** [comment]
Hello,
1. Mutation rate is the ratio of number of samples where a gene is mutated to the total number of samples. Thats an example maf file fromTCGA AML cohort obtained from Brad firehose database.
2. Can;t help here. You will have to wait till it finishes. Also I would not recommend using `oncodriveClust`, it is an old algorithm. There is an updated version from the original developers. See #467 
3. `plotMafSummary` orders bars on absolute number of mutations. Since `DNMT3A` is mutated multiple times (shown as `multi_hit` in black bars in oncoplot) in some of the patients its drawn plotted at the top.
4. Please read refer to the documentation `?rainfallPlot` for details. If you do not provide a sample name, it will choose most mutated sample. 

Regarding your earlier question, yes `ncRna` appears to be duplicated. I will correct it and its of no harm.

**Comment by PoisonAlien** [comment]
I have [added](https://github.com/PoisonAlien/maftools/blob/master/R/annovarToMaf.R#L103-L104) `startloss` (corresponding to `Translation_Start_Site` in MAF). However I am not sure about `startgain`, so I have set it to `unknown` for the moment. Let me know if you have any idea. Thanks.

**Comment by 2236529177** [comment]
thanks  a lot.
about the startgain , I even do not what it is , since start, it should start, why said gain, so maybe  the author kaiwang of annovar knows this.

**Comment by 2236529177** [comment]
when will the startgain be added into the maftools packages 
#Install from Bioconductor repository
BiocManager::install("maftools")

**Comment by PoisonAlien** [comment]
I plan to incorporate these changes in upcoming bioconductor release (should be in April). Meanwhile you can install from GitHub.

```r
BiocManager::install("poisonalien/maftools")
```

**Comment by 2236529177** [comment]
is the data in tcgaCompare of updated as TCGA? the example in https://bioconductor.riken.jp/packages/3.8/bioc/vignettes/maftools/inst/doc/maftools.html#78_plotting_vaf different from the data run by myself, its ylab used TMB directly. so in this case, **you divided 
mutaion number in each with 38M(exom length) or something else** ? but you know, always the maf made by ourselfves, always not exome, but panel data
[image](https://user-images.githubusercontent.com/25199946/77716870-1317aa00-701a-11ea-89d2-6943858cbb3d.png)

**Comment by PoisonAlien** [comment]
Hi please read the documentation for `? tcgaCompare`
There are arguments `capture_size` and `tcga_capture_size` which allows you to provide your custom panel size, and  TCGA exome capture size (default 50mb) respectively. If you do not wish to normalise set them to `NULL` - but it is not a good idea.
