### ISSUE TITLE
weird peak in GISTIC data

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#488]
Hello

I saw a peak in deletion but in plot that appears in amplification

![Picture1](https://user-images.githubusercontent.com/43682980/77675218-8ec71780-6f84-11ea-9671-5e4a63b4c395.png)

`6p25.3` has been `deleted` based on GISTIC data but I don't know why shows as amplified 

This is my maf object plus to gistic

https://www.dropbox.com/s/3lej3gvq0744k8q/gistic_maf?dl=0

**Comment by PoisonAlien** [comment]
Hi,
Please restrict your questions to bugs and errors. I would strongly suggest that you go through the GISTIC output file formats and their contents.

**Comment by beginner984** [comment]
Sorry @PoisonAlien  is it possible to add `markBands` argument to `gisticOncoPlot` function so that we are able to visualise selectively because sometimes peaks with higher incidences are not necessarily biologically interesting.
