### ISSUE TITLE
A little bug in line 239 in summarizeMaf.R

### ISSUE THREAD

**Issue by jmzeng1314** [PoisonAlien/maftools#49]
In your code: colnames(mdf) = gsub(pattern = "^X", replacement = "", colnames(mdf))
which means you consider that our samples will be marked as numeric, and in R , it will add a "X" for the sample name. 
But if our sample's name begin with X, you also remove the "X" , which cause a bug just like below:
oncomat.copy[, colnames(mdf)] : subscript out of bounds

We should change our sample's name as the only solution now. 
May you can fix that bug.

**Comment by PoisonAlien** [comment]
Hi,
Fair point and agreed. Thanks for suggestion, I will fix it soon.

**Comment by PoisonAlien** [comment]
Hi,

I have commented out the line. It seems to be working fine, could you please try it out and let me know. Install it from Github.
