### ISSUE TITLE
A boolean matrix alteration per gene per sample

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#491]
Hello @PoisonAlien 

Again, this is not an issue with maftools

How I can obtain alterations in a boolean matrix for a set of genes? I mean in a way where samples are in rows and genes in columns; in such a matrix 1 is if a given gene has altered in a given sample and 0 when there is no altercation in this gene in this sample (regardless of type of mutation)

Thank you in any case

**Comment by PoisonAlien** [comment]
There is an internal function which does this. You can call it with `:::`

```r
> om = maftools:::createOncoMatrix(m = laml, g = c("DNMT3A", "FLT3"))
> names(om)
[1] "oncoMatrix"    "numericMatrix" "vc"
```
It will return a list of matrices which includes a `numericMatrix` element which is what you're interested in. Values are integer coded for the variant classification, and those codes are explained in `vc` slot.

```r
> om$vc
                  0                   1                   2                   3 
                 "" "Missense_Mutation"       "Splice_Site" "Nonsense_Mutation" 
                  4                   5                   6                   7 
  "Frame_Shift_Del"      "In_Frame_Ins"      "In_Frame_Del"         "Multi_Hit" 
```

**Comment by beginner984** [comment]
Sorry @PoisonAlien 

Given a maf object, how we define the average of mutated gene per sample? 

I mean for a list of genes let's say cancer drivers

I thought of creating a boolean matrix, then converting everything > 1 to 1 and finally averaging the 1s

But I am not sure if this makes sense

**Comment by PoisonAlien** [comment]
Can you describe this in more detail? I can't seem to understand what you mean by `average of mutated gene per sample`

**Comment by beginner984** [comment]
Sorry @PoisonAlien  you alright, what I have asked was unclear

Actually yesterday I showed the boss that a list of cancer drivers are exclusively mutated in non-responders to chemotherapy using maftools compare function of two maf objects

She then asked me what is the average of mutated drivers in each group (responders and non-responders)

I hope I have understood her well and can convey the message
