### ISSUE TITLE
gisticOncoPlot ignores par(mfrow)

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#493]
I'm trying to display two heatmaps from different GISTIC runs side by side. I thought I could use just `par` to do so, but it looks like it doesn't work.

I made a test trying to plot the same GISTIC object twice:

```r
> par(mfrow=c(2,1))
> gisticOncoPlot(gistic)
> gisticOncoPlot(gistic)
```

The plot occupies the whole plotting area regardless of what `par` does. I assume it's the sum of multiple plots itself? (I didn't look at the code yet)

**Comment by lbeltrame** [comment]
A look at the code tells that for many (probably good) reasons `par` and `layout` are used, so this will never be able to work properly at this point.

**Comment by PoisonAlien** [comment]
Yes that is correct. 
I am not aware of any ways to combine plots when the plotting functions itself are using `layout`.

**Comment by lbeltrame** [comment]
Indeed, so back to manual assembly with Inkscape it is. ;)
