### ISSUE TITLE
splitting oncoplot on assay

### ISSUE THREAD

**Issue by erikagedvilaite** [PoisonAlien/maftools#494]
Hello, 

I am new to this tool and was wondering if I can get some pointers. I have a simple plot:

oncoplot(maf = MAF,top = 10,drawRowBar=T,drawColBar=T)

I have a column annotated as "Assay" - and would like to split my oncoplot based on the annotation that it carries. Can you help me out?

Best,
Erika

**Comment by PoisonAlien** [comment]
Hello,
It's not possible to split the plot for now. But you can add your annotation to the plot and [sort](https://www.bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/oncoplots.html#06_including_annotations) it which should do the job. 

For example in you case it would be,
```r
oncoplot(maf = MAF, clinicalFeatures = "Assay", sortByAnnotation = TRUE)
```
Please let me know if this helps.

**Comment by erikagedvilaite** [comment]
Hello,

Thank you for a quick responce! I tried that before and here is the error:
```
" Following columns are missing from annotation slot of MAF. Ignoring them..
[1] "Assay"
Make sure at-least one of the values from provided clinicalFeatures are present in annotation slot of MAF. Here are available annotaions..
[1] "Tumor_Sample_Barcode"
Error in parse_annotation_dat(annotationDat = maf, clinicalFeatures = clinicalFeatures) : Zero annotaions to add! You can also provide custom annotations via annotationDat argument."
```
"Assay" is 17th field:
```
  [1] "Hugo_Symbol"                   "Entrez_Gene_Id"                "Center"                       
  [4] "NCBI_Build"                    "Chromosome"                    "Start_Position"               
  [7] "End_Position"                  "Strand"                        "Variant_Classification"       
 [10] "Variant_Type"                  "Reference_Allele"              "Tumor_Seq_Allele1"            
 [13] "Tumor_Seq_Allele2"             "dbSNP_RS"                      "dbSNP_Val_Status"             
 [16] "Tumor_Sample_Barcode"          "**Assay**"                         "Tumor_Sample_record"   
```       
Stay safe

**Comment by PoisonAlien** [comment]
I see that assay is in the MAF file itself. Best way would be to create a data-frame or a tsv file with sample annotations - containing sample names and their corresponding features (e.g `assays`).

Something like below

```r
> sample_assays
Tumor_Sample_Barcode   Assay
Sample-1 Assay-T
Sample-2 Assay-Z
Sample-3 Assay-Q
Sample-4 Assay-J
Sample-5 Assay-S
```

You can include as many features as you want for every sample in the MAF, and read it along the maf. Then the oncoplot command should work with `clinicalFeature`.

```r
> MAF = read.maf(maf = "my.maf", clinicalData = sample_assays)
> oncoplot(maf = MAF, clinicalFeatures = "Assay", sortByAnnotation = TRUE)
```

Hope this helps.

**Comment by erikagedvilaite** [comment]
Thank you! Works like a charm! Thanks for such a nifty tool!
