### ISSUE TITLE
VAF plot feature request

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#495]
Hello

Is it possible to plot VAF for a set of genes in two maf object as `lollipopPlot2` function does?

I mean we have two groups and we want to know how VAF is in two groups in a set of genes in one plot

Thank you

**Comment by beginner984** [comment]
Sorry when you are going add a new feature to your software, how we know when you have added that we then would have to reinstall the software?

**Comment by PoisonAlien** [comment]
I usually notify the person opening the issue (in this case it would be you). I will let you know once I address it.

**Comment by PoisonAlien** [comment]
Hello,
Sorry for the delay. I have added the `vafCompare` which compares VAF from two cohorts. Could you please check and let me know if this is what you wanted?

Usage:
```r
> TCGAmutations::tcga_load(study = "LUAD")
> TCGAmutations::tcga_load(study = "LUSC")
> vafComapre(m1 = tcga_luad_mc3, tcga_lusc_mc3)
```

See `?vafComapre` for complete details and arguments.

**Comment by beginner984** [comment]
Sorry

vafComapre is not working

Have you removed that from your software?

```
> vafComapre(m1 = a, m2 = b)
Error in vafComapre(m1 = a, m2 = b) : 
  could not find function "vafComapre"
```

**Comment by PoisonAlien** [comment]
There was a #511 typo in the command name. I have corrected it. It should be `vafCompare` and not `vafComapre`

**Comment by beginner984** [comment]
Thank you. Sorry if no `ns` on the plot that means significant?

![Rplot95](https://user-images.githubusercontent.com/43682980/80795123-85d4f180-8b93-11ea-8d1e-5d6eaf2ca3b4.png)

For example `NAV3` here does not have `ns` but `TP53` has, does this mean `VAF` of `NAV3` is different between `m1` and `m2`?

**Comment by PoisonAlien** [comment]
`ns` usually means not-significant. 
In this case NAV3 doesnt have mutations so there are no values to perform any kind of test. Hence the blank.
