### ISSUE TITLE
tcgacompare reverse order of plot

### ISSUE THREAD

**Issue by tomsuntom** [PoisonAlien/maftools#497]
Hi PoisonAlien,

Want to say your package maftools is really wonderful! You are doing such a great service to the scientific genomic research community.

A quick suggestion: the tcgacompare command that generates the tumor mutation burden plot is currently displaying tumors with the highest TMB starting on the left. This is the opposite of convention where the highest tumors usually start on the right, like here.

![Screen Shot 2020-04-09 at 8 41 23 PM](https://user-images.githubusercontent.com/42565156/78960304-8271ad00-7aa2-11ea-8a15-4ae8cacb6b40.png)

Is it possible to modify the command to reverse the order of plotting?

Thanks!

**Comment by PoisonAlien** [comment]
Hello,
Thank you for your kind words and suggestion. I have pushed a fix for this. 
From now by default, cohorts are organised in increasing order (the way you wanted). However, you can set `decreasing = TRUE` for reversing it. Let me know if this helps.
