### ISSUE TITLE
Oncoprint output in text format 

### ISSUE THREAD

**Issue by aditisk** [PoisonAlien/maftools#499]
Hello,

Is it possible to export the Oncoprint output as a text file ? The figure gets too crowded after about 50 genes and I would like to look at all the mutated genes so it would be easy to have it as a text file.

Is there an easy way to do this ?

Thanks.

**Comment by PoisonAlien** [comment]
Yes. Use `writeMatrix = TRUE` in oncoplot function and it should generate an output tsv file `onco_matrix.txt`. Genes and samples would be in the same order as in the plot.
