### ISSUE TITLE
CNV/RNAseq data into oncoplot

### ISSUE THREAD

**Issue by jungminchoi** [PoisonAlien/maftools#5]
This is a great resource for the visualization of cancer data!

I was wondering if you can include an option to indicate the copy number alteration and/or rna expression data in the oncoplot like OncoPrinter does (http://www.cbioportal.org/oncoprinter.jsp).

Thanks so much again!

**Comment by PoisonAlien** [comment]
Hi,

Sorry for late reply (was on vacation). Yes, it is possible to include copy number data in oncoplot. What kind of data do you have for copy number ? Is it an output from gistic (for ex. *.del_genes.conf_90.txt) ?

**Comment by jungminchoi** [comment]
Hope you had a relaxing vacation. Yes, I use our in-house CNV data format but the output from gistic sounds great too. Also, in case we have fpkm values for the genes from the RNAseq data, would it be feasible to indicate the expression level?

Many thanks again!

**Comment by PoisonAlien** [comment]
Got it. Better to include gistic since its the one which is widely used. I will push a commit soon.

**Comment by PoisonAlien** [comment]
Hi, sorry for the delay. Now you can include copy number data into oncoplots. Either you can provide copy number as Gistic results or as a simple table with sample, gene name and copy number info. Let me know if this works for you.
