### ISSUE TITLE
Questions about getting the APOBEC-specific count

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#500]
Hi, 

I am wondering if it is possible for us to get the total number of APOBEC mutation for each sample using maftools. 

Thank you for your help. 

Best regards,
Xinan

**Comment by PoisonAlien** [comment]
Hi,
Please refer to `trinucleotideMatrix` function. It uses previously described [method](https://www.ncbi.nlm.nih.gov/pubmed/23852170) to estimate APOBEC enrichment. Results contain number of apobec and non-apobec associated mutations per sample.

**Comment by xiw588** [comment]
Thank you for your explanation and help!

**Comment by xiw588** [comment]
Hi, I just want to double confirm that when calculating the APOBEC mutation, do people only include T[C>T]W and T[C>G]W (W -> A or T). Is there any filtering or exclusion criteria? 

Thank you.

**Comment by PoisonAlien** [comment]
Hi APOBEC mutations are attributed to `tcw` context. There is no other criteria.

**Comment by ShixiangWang** [comment]
@xiw588 When you run `?maftools::trinucleotideMatrix` in your R console, you will see the calculation method and its reference.

![image](https://user-images.githubusercontent.com/25057508/79321509-1083e280-7f3e-11ea-9cf3-fe03e0385bb7.png)

**Comment by xiw588** [comment]
@ShixiangWang  Thank you for your help. I will look into the reference paper. Actually I am just calculating the APOBEC count rather than APOBEC enrichment. But this also helps, Thank you!

**Comment by xiw588** [comment]
@PoisonAlien  Thank you for your clarification!

**Comment by xiw588** [comment]
Hi,

I have a follow-up question regarding trinucleotideMatrix function. Is there any exclusion criteria for this function that make some observations are removed from the result? 
Basically, what I want is all the transversion and transition situation count for each observation. 

Thank you.

**Comment by ShixiangWang** [comment]
You can filter mutations before reading it

**Comment by xiw588** [comment]
@ShixiangWang  What I meant here is some samples were automatically removed by applying trinucleotideMatrix function, which is not expected. I don't know the reasons behind that and I want to have the information for each sample.

**Comment by ShixiangWang** [comment]
Set useSyn to TRUE？

**Comment by xiw588** [comment]
Yes, I set useSyn = TRUE but still get two samples removed. I don't know why they were removed since every sample supposed to have a matrix, right?

**Comment by ShixiangWang** [comment]
The two samples may have no SBS counts.

You can try https://github.com/ShixiangWang/sigminer to get all samples, even there are no SBS mutations

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read_maf(maf = laml.maf)

## If you have MAF already, just use sig_tally
mt_tally <- sig_tally(
    laml,
    ref_genome = "BSgenome.Hsapiens.UCSC.hg19",
    mode = 'SBS',
    use_syn = TRUE)
```

**Comment by xiw588** [comment]
Thank you for your response. I tried to run as you suggested but got the error message ''Error: 'cli_alert_info' is not an exported object from 'namespace:cli''

Do you know what is going on? 

Thank you.

**Comment by ShixiangWang** [comment]
Could you reinstall the cli package and try again

**Comment by PoisonAlien** [comment]
Hi @xiw588 ,
`trinucleotideMatrix` does not remove any samples. Maybe some of your samples do not have any SNVs?

**Comment by xiw588** [comment]
@PoisonAlien  Oh I see! That could be the point! Let me check. Thank you for your help!
