### ISSUE TITLE
Oncoplot by maftools: sort columns by mutation counts

### ISSUE THREAD

**Issue by yusukesano46** [PoisonAlien/maftools#502]
Hello,

Thank you so much for an amazing tool.
I am trying to see if I can change the order of samples in the oncoplot by mutation counts.
I want to sort the top bars so that the height of the bars becomes lower toward the right.

Thank you in advance!

**Comment by PoisonAlien** [comment]
Hi,
Thank you and I am glad you find it useful. Regarding the question, `oncoplot` always orders the samples based on gene frequency. You can use `sampleOrder` argument to pass the manual ordering.

**Comment by yusukesano46** [comment]
Thank you for your help!
