### ISSUE TITLE
Combining pathway, somatic mutation and copy number in one plot

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#503]
Hello @PoisonAlien 

As you know well by the feedbacks, your software is amazing

In a paper I saw this figure 

<img width="488" alt="79174006-46678080-7df1-11ea-8bab-2a0124361f7b" src="https://user-images.githubusercontent.com/43682980/79387892-5489de00-7f64-11ea-9034-d26eb31d39da.png">

Given a group of samples and a list of genes for which we have mutation and GISTIC data enriched in some defined pathways like cell cycle and p53 as shown in this figure

Map of functional alterations for a group of patients. Genes (rows) encoding components p53–DNA repair; are affected by selected functional events (percent of samples altered and types of alteration are represented by colored squares) across group of samples in column. Alterations of the pathway are observed stacked green bar plots at bottom

For me getting such a plot by myself almost is impossible

That would be very informative, we can see type and percentage of alterations (copy number + mutation) and the contribution of these alterations in defined pathways

I have 15 samples and 19 genes

This is the boolean matrix of mutation for 15 samples and 19 genes

https://www.dropbox.com/s/6oysoesbdunob3n/Boolean_values%20for%20mutations.rds?dl=0

This is my GISTIC data for 15 samples and 19 genes

https://www.dropbox.com/s/q289603j8ndfpwx/GISTIC.rds?dl=0

Among my genes PIK3CA, EGFR, ERBB2, PTEN are in RTK pathway

And

CDKN2A and CCNE1 are in cell cycle pathway

Is this possible at all for you to implement such a feature in your software to such a visualisation?

**Comment by PoisonAlien** [comment]
Is [this](https://bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/oncoplots.html#08_group_by_pathways) what you have wanted? 
Also checkout similar functions `tcgaDriverBP` and [OncogenicPathways](https://bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/maftools.html#99_oncogenic_signaling_pathways). 
I can still improve them based on your suggestion if needed.

**Comment by PoisonAlien** [comment]
Hi, As the error says, dont pass it as a list. Use a data.frame (or a data.table) as in the [example](https://bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/oncoplots.html#08_group_by_pathways).

```r
genes = data.table::data.table(
  genes = c("TP53", "WT1", "DNMT3A", "IDH1", "IDH2", "RUNX1", "CEBPA"),
  pathways = rep(c("Tumors Suppressors", "DNAm", "TF"), times = c(3, 2, 2))
)

oncoplot(maf = laml, pathways = genes)
```

**Comment by beginner984** [comment]
Thank you

By pathway feature user can convey a lot of information at once

I am wondering if it is possible to add this feature to oncobarplot?

For instance I have 3 groups
![Rplot17](https://user-images.githubusercontent.com/43682980/79668660-61017700-81ae-11ea-9f6c-04bc398e730a.png)


People won't know the contribution of each pathway in each group

But with pathway contribution in an oncobarplot we can look at groups comparatively at pathways and mutation types and frequencies

**Comment by PoisonAlien** [comment]
This would be bit tricky and I dont know how to separate that info in the main plot.
Best way would be to split your maf by group and draw an oncoplot each group :|

**Comment by beginner984** [comment]
Thank you so much

For one of my group I have used OncogenicPathways function which gives 

```
> OncogenicPathways(maf = maf)
Pathway alteration fractions
       Pathway  N n_affected_genes fraction_affected
 1:    RTK-RAS 85               45         0.5294118
 2:        WNT 68               30         0.4411765
 3:      NOTCH 71               26         0.3661972
 4:      Hippo 38               15         0.3947368
 5:       PI3K 29               14         0.4827586
 6:   TGF-Beta  7                6         0.8571429
 7: Cell_Cycle 15                4         0.2666667
 8:       NRF2  3                3         1.0000000
 9:       TP53  6                3         0.5000000
10:        MYC 13                3         0.2307692
> 
>
```

This function gives the fraction of mutated genes in each pathway. I am wondering is it possible to include the `fraction (contribution) of each pathway across samples`? For instance let's say we have 100 samples, 45 of 85 genes in RTK-RAS pathway have been mutated, how many of samples having this mutated genes? If so, when comparing two groups, we are able to compare affected pathways among groups for example we can say the alteration in cell cycle pathway has happened more severe in non-responders group to chemotherapy.

I am not sure how is it possible, something like tcgacompare or only adding extra column to show the percentage of affected samples by each pathway
