### ISSUE TITLE
how you get all the all the protein domains of gene

### ISSUE THREAD

**Issue by dj10086** [PoisonAlien/maftools#504]
hi, professor,
I am looking for a file which contails all the protein domains and postions like you show here, can you give me some help, thanks a lot
![image](https://user-images.githubusercontent.com/61576362/79405957-584f4c00-7fc8-11ea-9e7c-e431219051c9.png)

**Comment by PoisonAlien** [comment]
Hello,
There is a database of all protein structures and pfam domains bundled with maftools package. 
You can read it using following command.
```r
> prot_db = system.file('extdata', 'protein_domains.RDs', package = 'maftools')  
> prot_db = readRDS(file = prot_db)
```

**Comment by dj10086** [comment]
thanks a lot, I tried you method, and it is useful
I also get the desired data from ensemble biomart. which contains more information, but  I see you data contains not only pfam ,but also many other protein database, so is this data you update with the new release of the protein database?

**Comment by PoisonAlien** [comment]
No. I have not updated this in a while, and to be honest I will not update this any further.

**Comment by dj10086** [comment]
thanks  a lot.

**Comment by ahy1221** [comment]
Hi @PoisonAlien , 

I am also wondering that how do you compile such protein database for the maftools?  Would you guide me to compile a customized database for mouse by myself ?

Yao
