### ISSUE TITLE
Error while running signatureEnrichment

### ISSUE THREAD

**Issue by aditisk** [PoisonAlien/maftools#506]
Hi,

I am trying to run the signatureEnrichment function (I followed the steps before getting to this step mentioned in the tutorial) and getting an error message pasted below. I have 2 MAF files (12 samples and 6 samples) and it works on the one with 12 samples without any error.

> ic.se = signatureEnrichment(maf = ic_maf, sig_res = ic.sig)
Running k-means for signature assignment..
Performing pairwise and groupwise comparisions..
Sample size per factor in Signature:

Signature_1 Signature_2 Signature_3 
          1           2           3 
Error in .checkTypos(e, names_x) : Object 'Analysis' not found amongst

**Comment by PoisonAlien** [comment]
Hi, to be honest 6 samples is way too low for (de-novo) signature analysis. In your case I would suggest you to use more supervised methods like [sigminer](https://github.com/ShixiangWang/sigminer) or [deconstructSigs](https://github.com/raerose01/deconstructSigs) which provide better estimation of signature loads per samples.
