### ISSUE TITLE
Subsetting may by specific mutations

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#507]
Hello

I have two groups of distinct patients 

I have created maf file for each group independently 

I am interested in subsetting `mutations unique to each group` and `mutations ubiquitious between two groups`

I guess the results would be maf file unique to each group and maf containing information common between groups

But to be honest I don't know how to do that even I am not quite certain in an intuition behind this idea

I only know how to subset maf for a list of genes

Please you may help me?

Thanks a lot

**Comment by ShixiangWang** [comment]
This is interesting, I will try adding a feature.

**Comment by ShixiangWang** [comment]
You can install it by

```r
BiocManager::install("ShixiangWang/maftools")
```

I defined three set operation functions for MAF, you can view it at https://github.com/ShixiangWang/maftools/blob/a062180ca3e3a042aadcafc80c38b44abce498b2/R/setMaf.R

After installing, you can try using `intersectMaf()` and `setdiffMaf()` for your purpose.

They all have the same parameters:

```
function(x, y, mafObj = TRUE, ...)
```

Note that you can pass any other arguments defined in `subsetMaf()` function to subset the MAF firstly.

I haven't tested the functions, I hope get your feedback to see if they are right on the way.

**Comment by MaryGoAround** [comment]
Thank you

If I have maf_A and maf_B

If I have want mutations `specific` to maf_A which function I should use?

I run

```
> maf_A=read.delim("res.txt")
> maf_B=read.delim("pre.txt")
> intersect(maf_A, maf_B, mafObj = TRUE)
Error in intersect(maf_A, maf_B, mafObj = TRUE) : 
  unused argument (mafObj = TRUE)
>  
```

**Comment by ShixiangWang** [comment]
please check the fun name and need maf object as input

**Comment by ShixiangWang** [comment]
@MaryGoAround Sorry that I forgot exporting the functions. Please reinstall it by

```r
BiocManager::install("ShixiangWang/maftools")
```

Then run 

```
> library(maftools)
> ?setMaf
```

You will see how the documentation and examples to use them.

```
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
## Generate two example MAF objects
x <- subsetMaf(maf = laml, tsb = c('TCGA-AB-2816'), genes = c("DNMT3A", "FLT3"))
x@data
y <- subsetMaf(maf = laml, tsb = c('TCGA-AB-2802'), genes = c("DNMT3A", "FLT3"))
y@data

setdiffMAF(x, y, mafObj = FALSE)
setdiffMAF(x, y)

intersectMAF(x, y, mafObj = FALSE)
intersectMAF(x, y)

# This is similar to merge_mafs()
unionMAF(x, y, mafObj = FALSE)
unionMAF(x, y)
```

**Comment by PoisonAlien** [comment]
Hello @MaryGoAround ,
Could you please install from `github` and let me know if it works for you? I have checked on several TCGA cohorts and it seems to do the job. Let me know if this helps.

**Comment by beginner984** [comment]
Thank you 

For intersecting two maf files I am getting this plot

```
> laml=intersectMAF(x, y, mafObj = TRUE)
> oncoplot(laml)
```

![Rplot33](https://user-images.githubusercontent.com/43682980/79752773-bbb0e500-830c-11ea-9c84-efb226e29057.png)

And for setdiff I have this plot for one group


```
> laml=setdiffMAF(x, y,mafObj = TRUE)
> oncoplot(laml,top = 50)
> 
```

![Rplot34](https://user-images.githubusercontent.com/43682980/79753396-c5871800-830d-11ea-90c3-8c92cbe0c2e6.png)

For anther group I got confused because the number of patients in `maf file` is not matched with the number of patients in built `maf object` by `read.maf` function


```
 unique(maf_file$Tumor_Sample_Barcode)
 [1] LP2000325-DNA_A01 LP2000329-DNA_A01 LP6005334-DNA_B02 LP6005334-DNA_C02
 [5] LP6005334-DNA_H03 LP6005409-DNA_B02 LP6005409-DNA_E02 LP6005409-DNA_F01
 [9] LP6005409-DNA_H01 LP6005500-DNA_C03 LP6005500-DNA_G01 LP6005500-DNA_H03
[13] LP6005690-DNA_A02 LP6005690-DNA_E01 LP6005935-DNA_D02 LP6005935-DNA_F01
[17] LP6008031-DNA_B02 LP6008031-DNA_D01 LP6008031-DNA_E01 LP6008051-DNA_A01
[21] LP6008051-DNA_B01 LP6008202-DNA_F02 LP6008269-DNA_H05 LP6008280-DNA_B02
[25] LP6008280-DNA_D02 LP6008337-DNA_B07 LP6008337-DNA_F06 LP6005334-DNA_F03
[29] LP6005690-DNA_E02 LP6005690-DNA_F02 LP6008031-DNA_D02 LP6008202-DNA_A03
[33] SM-4AX87         
33 Levels: LP2000325-DNA_A01 LP2000329-DNA_A01 ... SM-4AX87
> 

> unique(maf_object@data$Tumor_Sample_Barcode)
 [1] LP6005334-DNA_C02 LP6005500-DNA_C03 LP6005500-DNA_G01 LP6005500-DNA_H03
 [5] LP6005690-DNA_A02 LP6005690-DNA_E01 LP6008031-DNA_E01 LP6008337-DNA_F06
 [9] LP2000325-DNA_A01 LP2000329-DNA_A01 LP6005334-DNA_B02 LP6005334-DNA_H03
[13] LP6005409-DNA_B02 LP6005409-DNA_E02 LP6005690-DNA_F02 LP6005935-DNA_D02
[17] LP6005935-DNA_F01 LP6008031-DNA_B02 LP6008031-DNA_D01 LP6008031-DNA_D02
[21] LP6008051-DNA_A01 LP6008051-DNA_B01 LP6008202-DNA_A03 LP6008202-DNA_F02
[25] LP6008269-DNA_H05 LP6008280-DNA_B02 LP6008280-DNA_D02 LP6008337-DNA_B07
[29] SM-4AX87          LP6005409-DNA_F01 LP6005409-DNA_H01
31 Levels: LP2000325-DNA_A01 LP2000329-DNA_A01 ... SM-4AX87
```

Where these 2 patients have gone that I am not finding them in maf object?

**Comment by PoisonAlien** [comment]
Those two patients prolly dont have any nonSyn mutations. You can check `maf_object@maf.silent$Tumor_Sample_Barcode`

**Comment by PoisonAlien** [comment]
I am closing the issue now. Please feel free to reopen if necessary.

**Comment by MaryGoAround** [comment]
Hello

Am I right that 

`laml=setdiffMAF(x, y,mafObj = TRUE)` gives mutations only on maf object `x` because that is first and `laml=setdiffMAF(y, x,mafObj = TRUE)` gives mutations only in maf object `y` because that has come first?

Thank you

**Comment by ShixiangWang** [comment]
Yes it is similar to setdiff in R

**Comment by PoisonAlien** [comment]
Yes, results are relative to first maf object.

**Comment by MaryGoAround** [comment]
Dear @PoisonAlien 

In literature I see people speak about deleterious mutations

Is this possible to subset a maf object on mutations with deleterious and/or moderate impacts? I don't mean by providing a list of genes rather from annotation columns in maffile (I am really not sure by literature mention like SIFT score)

Thank

**Comment by MaryGoAround** [comment]
@PoisonAlien is it correct if for getting mutations in protein-coding regions I do this

```
laml_coding=laml[laml$Func.refGene=="exonic",]

laml_Non_coding=laml[!laml$Func.refGene=="exonic",]
```

I want to look at mutation burden in coding and non coding parts of genome separately

**Comment by MaryGoAround** [comment]
Hello @PoisonAlien 

I need your advice please

I have a very big file from vcd parsing like

```
> head(vcf[,1:6])
             Sample Type CHROM     POS REF ALT
1 LP6005334_DNA_H01  SNV  chr1  782112   G   A
2 LP6005334_DNA_H01  SNV  chr1 1026918   C   T
3 LP6005334_DNA_H01  SNV  chr1 1133283   C   T
4 LP6005334_DNA_H01  SNV  chr1 1431511   G   A
5 LP6005334_DNA_H01  SNV  chr1 1742395   C   T
6 LP6005334_DNA_H01  SNV  chr1 1864994   G   A
> 
```

And for the same samples I have a maf file by maftools

I want to extract non-synonymous mutations in maf object/file from the above big file

From maf I learned how to subset but I don't know from reverse way

Please can you guid me?

Thank you

**Comment by PoisonAlien** [comment]
Hi,
Everything in `data` slot of `MAF` object are non-synonymous variants. Synonymous variants are stored under `maf.silent` slot.

**Comment by MaryGoAround** [comment]
Thank you @PoisonAlien 

I have a maf by Maftools, from the same samples I have 

```
       Sample Type CHROM     POS REF ALT
1 LP6005334_DNA_H01  SNV  chr1  782112   G   A
2 LP6005334_DNA_H01  SNV  chr1 1026918   C   T
3 LP6005334_DNA_H01  SNV  chr1 1133283   C   T
4 LP6005334_DNA_H01  SNV  chr1 1431511   G   A
5 LP6005334_DNA_H01  SNV  chr1 1742395   C   T
6 LP6005334_DNA_H01  SNV  chr1 1864994   G   A
> 
```
Parsed from .vcf

I want only this in information from maf

Whatever I am trying 

`intersect(maf,parsed_data)
`
Says

`data frame with 0 columns and 0 rows`

You may help me how to intersect this data?

Because what I have in parsed data are clonal mutations that I why I want them in maf
