### ISSUE TITLE
Adding extra feature to OncogenicPathways function

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#509]
Thank you so much for every kindly and smart effort you put to answer our concerns 

If I have three distinct groups of patients 
For one of my group I have used OncogenicPathways function which gives 

```
> OncogenicPathways(maf = maf)
Pathway alteration fractions
       Pathway  N n_affected_genes fraction_affected
 1:    RTK-RAS 85               45         0.5294118
 2:        WNT 68               30         0.4411765
 3:      NOTCH 71               26         0.3661972
 4:      Hippo 38               15         0.3947368
 5:       PI3K 29               14         0.4827586
 6:   TGF-Beta  7                6         0.8571429
 7: Cell_Cycle 15                4         0.2666667
 8:       NRF2  3                3         1.0000000
 9:       TP53  6                3         0.5000000
10:        MYC 13                3         0.2307692
> 
>
```

This function gives the fraction of mutated genes in each pathway. I am wondering is it possible to include the `fraction (contribution) of each pathway across samples`? For instance let's say we have 100 samples, 45 of 85 genes in RTK-RAS pathway have been mutated, how many of samples having this mutated genes? If so, when comparing two groups, we are able to compare affected pathways among groups for example we can say the alteration in cell cycle pathway has happened more severe in non-responders group to chemotherapy.

I am not sure how it is possible, something like `tcgacompare` to have statistics or only `adding extra column to show the percentage of affected samples by each pathway`

For instance I have plotted this for these groups of patients but one have manually add the percentage of altered samples especially painful for a lot of genes and groups of patients

<img width="1032" alt="Screenshot 2020-04-19 at 23 31 07" src="https://user-images.githubusercontent.com/43682980/79702080-f3327980-8299-11ea-8c6d-acb2796b2722.png">

Thank you for any help as always

**Comment by PoisonAlien** [comment]
Could you please check again. I have pushed some modifications. Thanks.

**Comment by beginner984** [comment]
Thank you it is exactly what I meant

If you got any time in feature, please you may add something to plot two maf objects in two colours bars then people can show the difference of altered pathways or occurrence between groups at a glance

I am nothing in R so I am not able to add any commitment or change in my mind :(

**Comment by PoisonAlien** [comment]
Sure. 
In a week, new Bioconductor 3.11 is scheduled to release. I am busy in fixing some stuffs and wont be adding any new features. Maybe later..

**Comment by beginner984** [comment]
Sorry @PoisonAlien 

I have asked this in a newest issue but I think I should ask this here because this is a relevant post

Long time I have been trying a way to compare each of individual signalling pathways to report dysreregulation biased in each group by showing p-value but I failed 

This is a code I have been trying to get the proportion of altered samples for each pathway in one group

[Code for one group.txt](https://github.com/PoisonAlien/maftools/files/4804313/Code.for.one.group.txt)


Please, is it possible for you to implement such a function to maftools?

maf objects could be for mutation or together with copy number and compare the proportion of altered samples for each of individual signalling pathways

**Comment by PoisonAlien** [comment]
Hello @beginner984 
I beg you to refrain your issues to bugs/errors. Maftools **can not** solve all your queries with the analysis. These things has to be solved by you. I would also suggest you to take some statistic classes or consult a senior bioinformatician. 

Above query is trivial. You have two groups and with different levels of mutated samples. Its a classic case for fishers exact test. 

For example.. 
```r
> m1_sample_size = 1020
> m1_mutated_samples= 14 

> m2_sample_size = 404
> m2_mutated_samples = 21

#Do a fishers test for differences in proprtions
> fisher.test(x = matrix(
  c(
    m1_sample_size,
    m1_mutated_samples,
    m2_sample_size,
    m2_mutated_samples
  ),
  nrow = 2
))

	Fisher's Exact Test for Count Data

data:  matrix(c(m1_sample_size, m1_mutated_samples, m2_sample_size, m2_mutated_samples), nrow = 2)
p-value = 0.0001945
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 1.814436 8.126939
sample estimates:
odds ratio 
  3.783102 
```

**Comment by beginner984** [comment]
Hello @PoisonAlien 

By `OncogenicPathways `I see one sample has been affected by `MYC `pathway but `oncoplot `shows no sample

![Rplot](https://user-images.githubusercontent.com/43682980/100851918-ba888e80-347d-11eb-9f72-a4ff16d1622e.png)

![Rplot01](https://user-images.githubusercontent.com/43682980/100851948-c3796000-347d-11eb-8727-9f39c9782559.png)

Please, do you think I interpret this right?

**Comment by PoisonAlien** [comment]
Hi again,
MYC pathway does not contain just the MYC gene. It's a collection of genes involved in the pathway. In this case, the MYC pathway has 13 genes of which one of the genes is affected (1/13).
 
You can check with `PlotOncogenicPathways`

```r
PlotOncogenicPathways(maf = laml, pathways = "MYC", fullPathway = TRUE)
```

**Comment by beginner984** [comment]
Thank you so much, I really could not solve this 

Sorry is this possible, two have two colours for pathways plot if we tend to plot two groups (here only red is possible)

Can we order the bar plots for two mafs?

**Comment by PoisonAlien** [comment]
It's not possible, unfortunately.
