### ISSUE TITLE
Can't plot certain genes only

### ISSUE THREAD

**Issue by rsklav** [PoisonAlien/maftools#51]
I only want to plot the significantly mutated genes with oncoplot. 

This is what I type: 
_oncoplot(maf = mm, genes = c("NRAS", "KRAS", "BRAF", "DIS3", "TP53", "ACTG1", "TRAF3"))_

And this is the error message I get:
_Error in numMat[geneOrder[geneOrder %in% rownames(numMat)], ] : 
  subscript out of bounds_

**Comment by PoisonAlien** [comment]
Hi,
I am not sure whats happening. Can you check to see if the following output contains all your selected genes?

```r
getGeneSummary(x = mm)[Hugo_Symbol %in% c("NRAS", "KRAS", "BRAF", "DIS3", "TP53", "ACTG1", "TRAF3")]
```

**Comment by rsklav** [comment]
Yep, this works fine!


________________________________

**Comment by PoisonAlien** [comment]
Hi,

Its hard to track down the issue without a working example. If you don't mind, can you share your file ? You can mail me at anandmt3@gmail.com if you don't wanna attach it here.
