### ISSUE TITLE
Questions about transversions and transitions 

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#510]
Hi, I have some questions about the way that maftools present the distribution of transversion and transitions using Titv and plotTiTv. I understand that transition refers to A-G and C-T while transversions refer to the rest of the combinations. I am wondering why TiTv only shows the distributions of the six alterations rather than the 12 in total. Can anyone explain the reasons for this and the rational behind when calculating the proportion of transversion and transitions.

Thanks

**Comment by ShixiangWang** [comment]
Because the pyrimidine base of the Watson-Crick base-pair has become a community standard.

e.g. when you see a mutation `A>G`, it will be converted to `T>C` in the opposite strand.

**Comment by xiw588** [comment]
I undertand the Watson-Crick base-pair rule but still confused. So basically the assumption here is the opposite strand would be converted correspondingly after the mutation occurs. So there isn't any situation that breaks the A-T and C-G rule, which could be a possible situation that evades the DNA repair mechanism. 

Here I listed all the 12 situations of transversions and transitions with the opposite strand in parentheses. 

A>G (T>C) A>T(T>A) A>C (T>G) T>G (A>C) T>C (A>G) T>A (A>T) C>G (G>C) C>T (G>A) C>A (G>T) G>T(C>A) G>C (G>C) G>A (C>T)
Are you saying that all the same alteration pattern would be counted only once regardless of which strand the mutation occurs? 


Thanks.

**Comment by ShixiangWang** [comment]
Yeah.  12 mutation types can be divided into patterns that start with 'C' or 'T'.

Therefore we get `C>A, C>G, C>T, T>A, T>C, T>G`.

Typically we read a mutation from 5' to 3' and don't care which strand it belongs to. There may be strand bias, however it has to be determined by the location of the mutation and strand how the mutation records in Maf or Vcf.
