### ISSUE TITLE
Pan-cancer comparison

### ISSUE THREAD

**Issue by Kevinhokahey** [PoisonAlien/maftools#513]
Hi Guys
I have some question on the section of Pan-Cancer Comparison. I downloaded the maf data of LUSC from TCGA and try to use "pancanComparison" to analyze it. Since it needs the results from MutSigCV, I used an online website to finish the MutSigCV analysis. The website is genepattern. And I finally got the file of "LUSC.sig_genes.txt".
Then I try to do the pan-cancer comparison. 
`lusc.mutsig<-"/Users/XXX/tcga/LUSC.sig_genes.txt"
pancanComparison(mutsigResults = lusc.mutsig,qval=0.1,cohortName = lusc,inputSampleSize = 200,label=1)`
There comes an error. 
"Error in as.character.default(new("MAF", data = list(Hugo_Symbol = c("TARDBP",  : 
  no method for coercing this S4 class to a vector"

Would you please give me some suggestions? Thank you very much.

**Comment by PoisonAlien** [comment]
Hi,
Is it possible to share your `LUSC.sig_genes.txt` file?

Also, just a heads up. `pancanComparison` is being deprecated in the upcoming bioconductor release (scheduled for next week) and will no longer be available.

**Comment by Kevinhokahey** [comment]
Sure. Please see the attach. 
It is a shame to hear this news. Is there any alternative function for the pancanComparsion? 
Thank you very much.
[LUSC.sig_genes.txt](https://github.com/PoisonAlien/maftools/files/4512046/LUSC.sig_genes.txt)

**Comment by PoisonAlien** [comment]
It seems at given q-value threshold (q<0.1) there are no genes specific to LUSC. But increasing it to 0.2 identifies two genes `CUL3` and `OR2G6`.

```r
pancanComparison(mutsigResults = "~/Downloads/LUSC.sig_genes.txt",qval=0.2,cohortName = "lusc",inputSampleSize = 200,label=1)
```

There is a new function called `tcgaDriverBP` which takes an MAF object and compares compares a set of genes to known TCGA [drivers](https://pubmed.ncbi.nlm.nih.gov/29625053/) drivers.

**Comment by Kevinhokahey** [comment]
I see. Thank you so much. There will be a new introduction of new version maftools package, right?
Looking forward to it. Have a good day. Stay safe and healthy. 
Thank you .

**Comment by Kevinhokahey** [comment]
BTW, one last question. I am not fully understand the variates in the LUSC.sig_genes.txt. What are the meaning of "p" and "q"? Thanks.

**Comment by ShixiangWang** [comment]
p means p value, q means q value, i.e. FDR (adjust p value).

**Comment by Kevinhokahey** [comment]
Thank you so much. I've leant a lot.
