### ISSUE TITLE
One solution of "Following genes from MutSig results are not available in MAF"

### ISSUE THREAD

**Issue by Chitanda-Satou** [PoisonAlien/maftools#514]
Hi, dear @PoisonAlien ,

One can often see warning messages like this：
![image](https://user-images.githubusercontent.com/32410912/80052779-138a5e80-854e-11ea-9263-c2229cf3f966.png)

I found a reason for this problem. 
When we run mutsigcv, we first need to prepare the input file with the **preparemutsig()** function of maftools. Just like:
```
foo <- prepareMutSig(maf = maf)
```
This function uses the corresponding table in “hugo_to_mutSigSymbol.txt.gz” to convert “Hugo_Symbol” to "MutSig_Synonym". However, the oncoplot function does not have the function of turning "MutSig_Synonym" back to “Hugo_Symbol”. As a result, some genes will be lost.

**Comment by PoisonAlien** [comment]
Hi,
ideally you should use the same maf that was used for mutsigCV to avoid such problems.

**Comment by Chitanda-Satou** [comment]
Using mutsigCV's MAF is really a solution. 

I wrote a function to convert the gene name back.

 : )
