### ISSUE TITLE
merge_mafs

### ISSUE THREAD

**Issue by dlivgni** [PoisonAlien/maftools#515]
Hi, 

I have some problems with the merge_mafs function (I keep getting the error saying that it could not find function "merge_mafs")
I have loaded the maf files with the read.maf function and then tried to merge them by this command: 

merge_mafs(mafs = c(maf1, maf2, maf3))
The same with the function: MyMaf = maftools:::merge_mafs(maf = c(maf1, maf2, maf3)) 

I am using R version 3.5.2 (2018-12-20) and maftools_1.8.10 

Thank you!

**Comment by PoisonAlien** [comment]
Hi,
You are using way older version of maftools. Please update it and it should be visible. Install it from GitHub if possible. 

```r
BiocManager::install(pkgs = "poisonalien/maftools")
```
