### ISSUE TITLE
How to plot both synonymous and non-synonymous mutations in oncoplot

### ISSUE THREAD

**Issue by dlivgni** [PoisonAlien/maftools#516]
Hi, 

First of all, thank you for an amazing tool - it is really helpful!

I have one question - I have some mutations in the TERT promoter region which I want to include in my oncoplot. I can see that the mutation in the TERT promoter is included when I use the nonSyn = silent function:

maf <- read.maf(maf = "SCC", verbose = T, clinicalData = "Clinicaldata.txt", vc_nonSyn = silent)
>getSampleSummary (maf)
  Hugo_Symbol 
1:       KMT2D     
2:        TERT      
3:        TP53       

However, when I try to use the oncoplot function, only the non-synonymous mutations are included in the plot. And if I try to visualize the TERT mutation by the oncostrip function, it shows 0%. Is there any way to include both the synonymous and the non-synonymous mutations in the same oncoplot? 

Thank you!

**Comment by PoisonAlien** [comment]
Hi, 
You should add the variant classifications that you want to be considered as non-syn. For example below example considers all Variant classifications `Silent` as non-synonymous.

```r
#Default non-synonymos variants
> vc_nonsyn = c("Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site", "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del","In_Frame_Ins", "Missense_Mutation")

#Add silent to the list (in your case check what TERT promoter variants are classified as)
> vc_nonsyn = c(vc_nonsyn, "Silent")
#Read it and plot it
> x = read.maf(maf = "my.maf", vc_nonSyn = vc_nonsyn)
> oncoplot(maf = x)
```

Hope this helps.

**Comment by dlivgni** [comment]
Thank you for your quick reply. 
The TERT promoter is classified as a "5'Flank" and I have added this to the silent vector. It is shown in the getGeneSummary, but it is still not figuring in the oncoplot/oncostrips.. Are there additional arguments I have to add to the oncoplot function?

**Comment by PoisonAlien** [comment]
Ah, I see the issue now. Turns out there is no color code for `5'Flank` in the database and they will probably drawn as white blanks. Below is the solution.

```r
#Known color codes
> vc_cols = maftools:::get_vcColors()
#Add your favourite color for 5'Flank to the list and plot
> vc_cols = c(vc_cols, "5'Flank" = "maroon")
> oncoplot(maf = x,  colors = vc_cols)
```
