### ISSUE TITLE
Showing mutational load with a same scale

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#518]
Hello @PoisonAlien 

I have two groups

![1](https://user-images.githubusercontent.com/43682980/80917319-ef9cf900-8d55-11ea-9bde-853dcee1a6e2.png)

![2](https://user-images.githubusercontent.com/43682980/80917323-f4fa4380-8d55-11ea-9476-17c642a97226.png)

Is there any way to show mutation per sample with the scale? I thought in combining two groups by showing barcode but I noticed patients are placed irregularly regardless of their own groups.

**Comment by PoisonAlien** [comment]
This would not be possible because they are cohort specific. 
But, If you want to show differences in mutation load you can use `tmb`

```r
> par(mfrow = c(1, 2))
> tmb(maf = maf1)
> tmb(maf = maf2)
```

**Comment by MaryGoAround** [comment]
Sorry, given two maf objects what you mean by tab

```
> par(mfrow = c(1, 2))
> tmb(maf = maf1)
Error in tmb(maf = maf1) : could not find function "tmb"
```

You mean oncoplot?

**Comment by PoisonAlien** [comment]
You will have to update the package for this function.

**Comment by beginner984** [comment]
Excuse me @PoisonAlien, by 

`tmb(maf = laml,captureSize = 50,logScale = FALSE)
`
I see Median : 1.84/mb, does this mean that `1.84 per each 50 mega bases of the genome` because `captureSize = 50`?

![Rplot09](https://user-images.githubusercontent.com/43682980/83887621-9bb07600-a740-11ea-9185-d6488d2a827b.png)

When I put `captureSize = 1`, I get this

![Rplot10](https://user-images.githubusercontent.com/43682980/83887709-bb479e80-a740-11ea-967e-5696297e25ee.png)

Because I am working on a cancer for which a reference paper has been published in which says `median was 6.4 such mutations per mega base` , that is why I worry I may I calculate TMB wrong that I see TMB as `1.84`

**Comment by PoisonAlien** [comment]
Capture size indicates the size of genome that is sequenced. For example exome-seq with Agilent [sureselect](https://www.agilent.com/en-eu/promotions/sureselect-human-all-exon-v7) kit captures ~50mb of the genome. If you observe 100 mutations then your TMB is 100/50 = 2per mb. 
Probably there are more fancier ways to estimate TMB but here its just a simple division with capture size.

**Comment by beginner984** [comment]
Sorry @PoisonAlien 

I have to groups of patients for them I plotted mutational burden like this

![Picture1](https://user-images.githubusercontent.com/43682980/83947502-4becb000-a80f-11ea-8c2a-f3f8933afd57.png)

My boss says I should find a way to make Y axis at the same scale I mean by bared eyes we can see the differences

Is there any possible change to the function can to this?

**Comment by PoisonAlien** [comment]
No its not possible.

**Comment by PoisonAlien** [comment]
Can you post the below output?

```r
getSampleSummary(ms)[Tumor_Sample_Barcode %in% c("LP6008202-DNA_B03", "LP6008460-DNA_F02", "s59")]
```

`total` is the number of variants (excluding CNVs, and syn mutations) in a sample.

**Comment by beginner984** [comment]
Thank you 

```
> getSampleSummary(ms)[Tumor_Sample_Barcode %in% c("LP6008202-DNA_B03", "LP6008460-DNA_F02", "s59")]
   Tumor_Sample_Barcode Frame_Shift_Del Frame_Shift_Ins In_Frame_Del In_Frame_Ins
1:                  s59               1               2            2            0
2:    LP6008460-DNA_F02               1               1            1            1
3:    LP6008202-DNA_B03               0               0            0            0
   Missense_Mutation Nonsense_Mutation Nonstop_Mutation Splice_Site total
1:                48                 2                0           0    55
2:                39                 3                1           2    49
3:                 7                 0                0           0     7
> 
> 
```

**Comment by PoisonAlien** [comment]
Seems ok to me.

**Comment by beginner984** [comment]
Hello @PoisonAlien 

I am really struggling with this

I have 177 samples (30 responders to chemotherapy and 147 non responders)
By `tmb` function I calculated `total_perMB` for a big maf of 177 samples

I them compared total_perMB of responders and non responders by Wilcoxon test which was significantly higher in responders

The problem is here;

When I calculated total_perMB from 30 responders and 147 non responders in two independent maf for each group, total_perMB was not significant this time

Is sample size affect total_perMB? Or I may be do something wrong elsewhere 

Thank you for any help

**Comment by beginner984** [comment]
Hello

    I have total number of mutation per sample

    I want to convert that to total number of mutations per giga base

    I googled for that

    People say I should divide the numbers of mutations by the total sequenced megabases for each sample

    But I am not sure what is the total sequenced megabases for each sample here and how I can get that

Can you help me here please?
