### ISSUE TITLE
Sub-clonal fraction using cancer cell fraction

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#519]
Hello

`inferHeterogeneity` function clusters VAF to infer clonality

Can we use Cancer Cell Fraction (CCF) instead of VAF to get something like 
![Untitled](https://user-images.githubusercontent.com/60115705/80929695-079c6900-8da6-11ea-81a4-fb50f474c389.png)

Which says 

`The faction of tumour cells carrying the variant is represented on the x axis (1 1⁄4 100% of tumour cells), and the probability density (on an arbitrary scale) on the y axis. Grey bars represent the histogram of mutations, with the fitted distribution as a dark purple line. The 95% posterior confidence intervals for the fitted distribution are represented by a pale blue area. `

I am not sure, is it possible to elaborate the function to do this? Or using CCF instead of what maftools now supports

**Comment by ShixiangWang** [comment]
copy number data is necessary for doing this

**Comment by MaryGoAround** [comment]
Thank you, which specific copy number data? Major and total allele for tumour, purity, ploidy?

**Comment by ShixiangWang** [comment]
The total copy number is okay, this can be done by ABSOLUTE or [Ccube](https://github.com/keyuan/ccube), etc. I think there are many options for this. You can get the CCF firstly and then plot it by base plot or ggplot2. I agree that the feature may be important for studying, but I don't think it should be implemented in maftools due to impractical,  but this depends on @PoisonAlien

**Comment by PoisonAlien** [comment]
It is not as straight forward as it seems. I am no expert in tumor heterogeneity, and for CCF one has to take into account purity, ploidy, LOH events. There are already plethora of tools which does exactly these thing (ABSOLUTE seems to be the crowd favorite). Just implementing plotting option would not add much to the tool.

**Comment by MaryGoAround** [comment]
Thank you @PoisonAlien  and @ShixiangWang  I did not mean just changing the plotting view rather I meant elaborating the function with CCF instead of VAF asking the users to provide ploidy and purity even tumour copy number as integer

**Comment by MaryGoAround** [comment]
Sorry @PoisonAlien , if I manually replace VAF with CCF in the function would I get the clustering? Actually my ultimate goal is to cluster CCF values to see if a mutation is clonal or sub-clonal discarding the ambiguous ones. maftools does such a clustering although I am not sure for maftools at which confidence interval a VAF values called clonal or sub-clonal. I have found implementing this clustering out of maftools very complicated that is why I am troubling you too much

I have raw CCF values myself but I know I would need binomial distribution of that for getting clustering

**Comment by PoisonAlien** [comment]
Yeah you can try that, just pass the column name containing your CCF values to `vafCol` argument. It should work. 
Also you may want to look at [sciClone](https://github.com/genome/sciclone) and [clonevol](https://github.com/hdng/clonevol )packages.

**Comment by MaryGoAround** [comment]
Sorry again, end plot by maftools returns some clusters like clusters 1, 2, 3, 4 and outlier

In maftools output how we define mutations in which clusters are clonal or sub-clonal?

Thank you

**Comment by PoisonAlien** [comment]
This is out of the scope of the software itself.
Having said that if its of any help, I had [answered a similar question on Biostars](https://www.biostars.org/p/339074/#339223) once. Maybe check it once.

**Comment by MaryGoAround** [comment]
Sorry, `having two groups of patients`, can we calculate heterogeneity for each group at once (as whole)? I mean, in each maf object, we assume different patients in samples barcode column are all the same therefore we would finish with one VAF distribution for each group instead of having VAF clustering for each patient itself

**Comment by PoisonAlien** [comment]
These things you will have to figure out. There is no option to perform this.

**Comment by MaryGoAround** [comment]
> The total copy number is okay, this can be done by ABSOLUTE or [Ccube](https://github.com/keyuan/ccube), etc. I think there are many options for this. You can get the CCF firstly and then plot it by base plot or ggplot2. I agree that the feature may be important for studying, but I don't think it should be implemented in maftools due to impractical, but this depends on @PoisonAlien

Sorry @ShixiangWang  I looked at Ccube in this link which simulates input and returns results 

https://github.com/keyuan/ccube/blob/master/vignettes/ccube.Rmd

From the results how can I understand if a specific mutation is clonal or sub-clonal? Please you may have a look? thank you

**Comment by ShixiangWang** [comment]
@MaryGoAround Could you read the info?

![image](https://user-images.githubusercontent.com/25057508/81679946-304aef80-9485-11ea-8952-350d9dd577b5.png)

If an SNV is clonal, its CCF should be exactly 1 (at least very close to 1).

**Comment by MaryGoAround** [comment]
Yes @ShixiangWang you right, in this link says that

https://www.researchgate.net/publication/329368882_Ccube_A_fast_and_robust_method_for_estimating_cancer_cell_fractions

`The peak at CCF=1 corresponds to the clonal cluster.`

**Comment by MaryGoAround** [comment]
Sorry @ShixiangWang  finally I could run ccube on my data, but I can not find clusters number in the results for instance like maftools says cluster 1, 2 , etc

Can you see where clusters are in the results?

**Comment by ShixiangWang** [comment]
@MaryGoAround This is out of the scope of maftools, could you post your question on https://github.com/keyuan/ccube/issues. I think the authors of cube would like to answer your question. Please post your result snapshot in ccube issue.
