### ISSUE TITLE
add multiple types of mutations

### ISSUE THREAD

**Issue by igordot** [PoisonAlien/maftools#520]
This is the waterfall plot from the [TCGA-PDAC](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5964983/) paper:

![nihms898701f1](https://user-images.githubusercontent.com/6363505/81124863-87d8e080-8f04-11ea-8d4d-95a54ebdcdef.jpg)

Most of it can be recreated with maftools. However, notice that it has "Germline" classification for variants that generates a distinct representation (a gray border) for those events.

You cannot add "Germline" to the `Variant_Classification` column. I thought `additionalFeature` did that, but that only adds an additional layer to the variants. Thus, if you have gemline and non-germline events in the same gene, it is labeled "Multi_Hit". I was hoping for something like copy number status where the copy number events are independent of other mutations. Is there a way to do that with maftools?

**Comment by PoisonAlien** [comment]
Hi,
You can include samples with `Germline` status in the copy number table and it should work. Below is the example using example AML file.

```r
#path to TCGA LAML MAF file
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')

#Random 20 samples
dummy.samples = c("TCGA-AB-2898", "TCGA-AB-2879", "TCGA-AB-2920", "TCGA-AB-2866", 
                  "TCGA-AB-2892", "TCGA-AB-2863", "TCGA-AB-2994", "TCGA-AB-3007", 
                  "TCGA-AB-2992", "TCGA-AB-2860", "TCGA-AB-2917", "TCGA-AB-2859", 
                  "TCGA-AB-2822", "TCGA-AB-2936", "TCGA-AB-2897", "TCGA-AB-3008", 
                  "TCGA-AB-2883", "TCGA-AB-2957", "TCGA-AB-2946", "TCGA-AB-2943"
)

#Genarate random germline status for above samples
gl.status = sample(
  x = c('Germline', 'idk,maybe..'),
  size = length(dummy.samples),
  replace = TRUE
)

gl.data = data.frame(
  Gene = "NPM1",
  Sample_name = dummy.samples,
  is_germline = gl.status,
  stringsAsFactors = FALSE
)

head(gl.data)

Gene  Sample_name is_germline
1 NPM1 TCGA-AB-2898 idk,maybe..
2 NPM1 TCGA-AB-2879    Germline
3 NPM1 TCGA-AB-2920    Germline
4 NPM1 TCGA-AB-2866    Germline
5 NPM1 TCGA-AB-2892    Germline
6 NPM1 TCGA-AB-2863    Germline

laml.plus.cn = read.maf(maf = laml.maf, cnTable = gl.data)

oncoplot(
  maf = laml.plus.cn,
  genes = c("DNMT3A", "NPM1"),
  drawRowBar = FALSE,
  drawColBar = FALSE,
  showTitle = FALSE
)
```

![Rplot02](https://user-images.githubusercontent.com/8164062/81148289-4be16200-8f7c-11ea-9224-c0c90793edc4.png)

Would this work? You will have to install the tool from `GitHub` though, since it hasnt been pushed to Bioconductor yet.

**Comment by igordot** [comment]
I tried this in the Bioconductor version and it did not work. It indeed works in the current GitHub version.

I guess this was added in response to a similar recent issue, which I just noticed: https://github.com/PoisonAlien/maftools/issues/490

**Comment by igordot** [comment]
There is a way to specify custom colors for different mutation types. Is there a way to modify how the copy number mutations look otherwise? For example, to change the size, shape, or alpha?

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. Yes, this update was related to #490. 
Unfortunately it is not possible to change shape or size. However you can change colors by providing named vector of colors for every level in the custom data.

for above example

```r
#maftools default colors for known variant classifications
vc_cols = maftools:::get_vcColors()
#colors for your additional values
my_cols = c("#f3a683", "#f7d794")
#Set alpha if you would like
#my_cols = grDevices::adjustcolor(col = my_cols, alpha.f = 0.9)
names(my_cols) = c('Germline', 'idk,maybe..')

vc_cols = c(vc_cols, my_cols)

oncoplot(
  maf = laml.plus.cn,
  genes = c("DNMT3A", "NPM1"),
  drawRowBar = FALSE,
  drawColBar = FALSE,
  showTitle = FALSE, colors = vc_cols
)

``` 

Hope this helps..

**Comment by ipstone** [comment]
Thanks @PoisonAlien -- a related question: with this modification of cnTable, can we continue to use the 'cnv_status' in the cnTable (to show copy number changes), together with the is_germline column?
