### ISSUE TITLE
Question about tcgaDriverBP function

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#521]
Hello

I just discovered `tcgaDriverBP` in your software

I am wondering you are passing only a subset of TCGA drivers and associated pathways to `tcgaDriverBP` function or this function uses what available by now on user's maf object?

I am asking because only a handful of my genes have been assigned to TCGA pathways

Thanks for any information

**Comment by PoisonAlien** [comment]
Hi,
By deafult it uses top 20 genes from the maf to compare against tcga drivers obtained from [here](https://www.ncbi.nlm.nih.gov/pubmed/29625053). 
Use `top` or `genes` argument to compare more genes.
