### ISSUE TITLE
estimateSignatures not found

### ISSUE THREAD

**Issue by jeff-meng** [PoisonAlien/maftools#522]
Hi! I've been using maftools for a while and it's awesome. I've been trying lately to do some signatures analysis following your online guide, but I'm having trouble finding `estimateSignatures`. At first, I thought it's because my maftools version is old, but I still couldn't find it after updating maftools. Also, I don't have `plotCophenetic` but I have `extractSignatures` Any idea what might be going on? Please see my code and sessionInfo below. Thank you!

`> comb_maf.sign = estimateSignatures(mat = comb_maf.tnm, nTry = 6)`
Error in estimateSignatures(mat = comb_maf.tnm, nTry = 6) : 
  could not find function "estimateSignatures"
`> comb_maf.sign = maftools::estimateSignatures(mat = comb_maf.tnm, nTry = 6)`
Error: 'estimateSignatures' is not an exported object from 'namespace:maftools'
`> maftools::estimateSignatures`
Error: 'estimateSignatures' is not an exported object from 'namespace:maftools'

I just updated maftools today.
sessionInfo() shows I'm running maftools_2.4.05:

`> sessionInfo()`
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg19_1.4.0 BSgenome_1.50.0                  
 [3] rtracklayer_1.42.2                NMF_0.22.0                       
 [5] cluster_2.1.0                     rngtools_1.5                     
 [7] pkgmaker_0.31.1                   registry_0.5-1                   
 [9] devtools_2.3.0                    usethis_1.6.1                    
[11] colorspace_1.4-1                  RColorBrewer_1.1-2               
[13] VariantAnnotation_1.28.13         Rsamtools_1.34.1                 
[15] Biostrings_2.50.2                 XVector_0.22.0                   
[17] SummarizedExperiment_1.12.0       DelayedArray_0.8.0               
[19] BiocParallel_1.16.6               matrixStats_0.56.0               
[21] GenomicRanges_1.34.0              GenomeInfoDb_1.18.2              
[23] IRanges_2.16.0                    S4Vectors_0.20.1                 
[25] maftools_2.4.05                   Biobase_2.42.0                   
[27] BiocGenerics_0.28.0  
...

**Comment by ShixiangWang** [comment]
Still old. You can install it from GitHub

**Comment by jeff-meng** [comment]
Hmm... I'm a bit confused. I just updated maftools today. Now, when I try to install:

`> install_github(repo = "PoisonAlien/maftools")`
Using github PAT from envvar GITHUB_PAT
Skipping install of 'maftools' from a github remote, the SHA1 (b907d03d) has not changed since last install.
  Use `force = TRUE` to force installation

**Comment by jeff-meng** [comment]
I forced the installation and I realized there were two error messages about invalid "uid" and "gid" values. Is that a problem? Please see below.

> install_github(repo = "PoisonAlien/maftools", force=T)
> Using github PAT from envvar GITHUB_PAT
> Downloading GitHub repo PoisonAlien/maftools@master
> ✓  checking for file ‘/private/var/folders/y1/4j1g876s5l72902tr2x_qgndr4k45x/T/RtmpUGEc3K/remotesb0522999b4be/PoisonAlien-maftools-b907d03/DESCRIPTION’ ...
> ─  preparing ‘maftools’:
> ✓  checking DESCRIPTION meta-information
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building ‘maftools_2.4.05.tar.gz’
>    Warning: invalid uid value replaced by that for user 'nobody'
>    Warning: invalid gid value replaced by that for user 'nobody'
>    
> Installing package into ‘/Users/jeffmeng/Library/R/3.5/library’
> (as ‘lib’ is unspecified)
> * installing *source* package ‘maftools’ ...
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> * DONE (maftools)

**Comment by ShixiangWang** [comment]
Please close it if the problem fixed

**Comment by ShixiangWang** [comment]
In most cases you can ignore warnings in R

**Comment by PoisonAlien** [comment]
I am guessing there are multiple versions of R installed and there is a conflict in the library path?
I am closing this issue as its not directly related to maftools.
