### ISSUE TITLE
Regarding inferHeterogeneity

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#525]
Hi, 

Is there any way that we could get the tumor heterogeneity for all samples rather than specifying a sample id or the top 5?  

Thank you.

**Comment by ShixiangWang** [comment]
Could you set the argument `tsb`?

**Comment by xiw588** [comment]
Do you mean by listing all the ids I want to show ? There are 1000 ids in total

**Comment by ShixiangWang** [comment]
Yeah, you can get them from `MAF` object or your input. You don't need to input them by hand.

**Comment by PoisonAlien** [comment]
@xiw588 You can loop around all samples. This is what maftools would be doing anyways..

```r
tsbs = as.character(getSampleSummary(x = laml)[,Tumor_Sample_Barcode])

lapply(tsbs, function(x) {
  maftools::inferHeterogeneity(maf = laml,
                               tsb = x,
                               vafCol = "i_TumorVAF_WU")
})
```

**Comment by xiw588** [comment]
@PoisonAlien Thank you very much for your help.
