### ISSUE TITLE
Reading maf for each individual samples jointly

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#526]
Hello

I have downloaded maf.txt for each individual sample from broad institute maf dashboard. I want to have an union maf for all in a way sample names are in sample barcode column as usual 

I have tried 

```
> getwd()
[1] "/Users/mi1d17/Downloads/gdac.broadinstitute.org_ESCA.Mutation_Packager_Oncotated_Calls.Level_3.2016012800.0.0"
>

> read.maf(list.files())
-Reading
Error in data.table::fread(file = maf, sep = "\t", stringsAsFactors = FALSE,  : 
  Internal error: freadR input not a single character string: a filename or the data itself. Should have been caught at R level.
In addition: Warning messages:
1: In if (is.na(file_info$size)) stop("File '", file, "' does not exist or is non-readable. getwd()=='",  :
  the condition has length > 1 and only the first element will be used
2: In if (!file_info$size) { :
  the condition has length > 1 and only the first element will be used
```

Is there any function in maftools to perform this?

Thank you so much

**Comment by ShixiangWang** [comment]
Use a for loop to creat a maf list and then merge them？

**Comment by PoisonAlien** [comment]
You should use `merge_mafs`.

**Comment by MaryGoAround** [comment]
sorry @PoisonAlien can you help me in knowing from where I can find gistic files needed for Maftools? I have been lucky to find maf files of my cancer of interest in broad institute dashboard but I have no clue where I can find gistic files for this toga samples.

excuse me if this question is irrelevant with the main post

**Comment by PoisonAlien** [comment]
You can find them on TCGA [firehose](http://gdac.broadinstitute.org/) for all cohorts. 
Click on `analysis` for your interested cohort -> Copy number analysis -> copy number gistic 2 -> Download results

**Comment by MaryGoAround** [comment]
Sorry @PoisonAlien 

Thank you for helping me

I have a list of samples from TCGA which clinical data says they have not received chemotherapy

Is there anyway to get gistic information from a list of samples from `Copy number analysis -> copy number gistic 2` ?

Because in gistic results does not have tumour barcode or at least I can not see tumour barcode to subset the data

I have tried to use segmentation and marker file from firehose to be able to run gistic only on my list of samples but likely marker file is not comparable with marker file and says

```
[fi1d18@cyan01 man]$ ./run_gistic_test
--- creating output directory ---
--- running GISTIC ---
Setting Matlab MCR root to /temp/hgig/fi1d18/man/MATLAB_Compiler_Runtime
GISTIC version 2.0.23
 
GISTIC 2.0 input error detected:
80177 segment start or end positions in '/temp/hgig/fi1d18/man/seg/seg.txt' do not match any markers in '/temp/hgig/fi1d18/man/seg/marker.txt'.
First bad position is 6:170903919 at line 21.
```

**Comment by PoisonAlien** [comment]
You dont need to run GISTIC. They are already results from GISTIC. Go [here](http://gdac.broadinstitute.org/runs/analyses__2016_01_28/reports/cancer/ACC-TP/CopyNumber_Gistic2/nozzle.html) for example and click on `Download results` - > `analysis results`. You can directly read thm with maftools.

**Comment by MaryGoAround** [comment]
Thank you

In the link we are seeing three files, one is likely amplification, one deletion and the other one seems to be gistic score

So for reading those by your software via this code

```
all.lesions <- system.file("extdata", "all_lesions.conf_99.txt", package = "maftools")
amp.genes <- system.file("extdata", "amp_genes.conf_99.txt", package = "maftools")
del.genes <- system.file("extdata", "del_genes.conf_99.txt", package = "maftools")
scores.gis <- system.file("extdata", "scores.gistic", package = "maftools")

laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gis, isTCGA = TRUE)
```

I am not sure which file is `all.lesions` and which file is `scores.gis`

**Comment by MaryGoAround** [comment]
Sorry you are right I found that

<img width="1280" alt="Screenshot 2020-05-21 at 16 53 14" src="https://user-images.githubusercontent.com/60115705/82577942-9de0d500-9b83-11ea-8d8b-998e5556bbe5.png">

Is there any way to extract my list of samples from the made laml.gistic?

I have tried to subset my samples but gives error

```
> subsetMaf(laml.gistic,tsb = c("TCGA-2H-A9GF","TCGA-2H-A9GF"),mafObj = FALSE)
Error in subsetMaf(laml.gistic, tsb = c("TCGA-2H-A9GF", "TCGA-2H-A9GF"),  : 
  no slot of name "maf.silent" for this object of class "GISTIC"
> 
```

**Comment by PoisonAlien** [comment]
Unfortunately its not possible to subset gistic object.
