### ISSUE TITLE
getSampleSummary Doesn't Tabulate Samples With No Mutations

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#527]
If I have a MAF object that has Tumor_Sample_Barcode that is a factor with more levels than there are present in the table (a couple of samples have zero mutations), `getSampleSummary` won't show them. It would be nice if it had a `drop` argument (e.g. `drop = FALSE`).

**Comment by ShixiangWang** [comment]
It is true and should be considered.

**Comment by PoisonAlien** [comment]
Hi,
`getSampleSummary` is intended to provide summaries for samples with at-least one non-synonymous mutaton. 
In this case, there is `mafSummary` function which returns everything regardless of the type of mutation. Can you try it and let me know if this is what you wanted?

**Comment by DarioS** [comment]
That'll do.

**Comment by PoisonAlien** [comment]
Hi both,
Yes I agree that those samples should be shown in the output - it makes more sense. 
I have changed `getSampleSummary` to include non-mutated samples as well (with zeros).
