### ISSUE TITLE
incorrect n_mutated_groups by clinicalEnrichment 

### ISSUE THREAD

**Issue by Jihoon-Yoon** [PoisonAlien/maftools#529]
**Describe the issue**
Hi.
Thanks for your great work!

I tried "clinicalEnrichment" function and noticed that the calculated numbers of n_mutated_groups by "clinicalEnrichment" and the mutations displayed by "oncoplot" are different.

For example, it is correctly counted that 7 samples have BRCA2 mutations by oncoplot,
however, when use "clinicalEnrichment" function, there are only 2 BRCA mutations in the result
by $groupwise_comparision
> here is also a small typo "groupwise_comparison" may be correct.

**Command**
Res.ce = clinicalEnrichment(maf = onco.res, minMut = 5, clinicalFeature = 'Res')
CE.res <- Res.ce$groupwise_comparision
```r
```

**Session info**
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.5    maftools_2.4.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       lattice_0.20-41    crayon_1.3.4       assertthat_0.2.1   grid_4.0.0         R6_2.4.1           lifecycle_0.2.0    magrittr_1.5      
 [9] pillar_1.4.3       rlang_0.4.6        rstudioapi_0.11    data.table_1.12.8  Matrix_1.2-18      vctrs_0.2.4        ellipsis_0.3.0     splines_4.0.0     
[17] RColorBrewer_1.1-2 tools_4.0.0        glue_1.4.0         purrr_0.3.4        survival_3.1-12    compiler_4.0.0     pkgconfig_2.0.3    tidyselect_1.0.0  
[25] tibble_3.0.1 

```r
```

**Comment by PoisonAlien** [comment]
Hi,
I believe one of your group has has only two BRCA mutation. They are not total number of samples with BRCA (which is what would be shown in oncoplot) rather they are number of samples within a particular group with BRCA mutations.

**Comment by Jihoon-Yoon** [comment]
Dear Anand Mayakonda,

I really appreciate your great work
I was trying to attach figures regarding this issue on github, but it didn’t work.
So, here, I share the results.

This is the oncoplot displaying 7 samples with BRCA mutations among 115 samples.
[cid:image001.jpg@01D6329B.F3048E10]

This is the results from clinicalEnrichment, CE.res
[cid:image002.png@01D6329C.DC706A10]

There are only two samples included in the calculation 2/23 in group1 and 0/92 in group2. 2+0 = 2
The total numbers of mutations used in the calculations are also incorrect for other genes, such as NOTCH1 and ARID1A.
The total numbers of mutations for NOTCH1 and ARID1A is 6+4=10, 3+2=5 in clinicalEnrichment, but in the oncoplot they are 11 and 13, respectively.
I am wondering why these different results are coming from.

Best regards,

Jihoon Yoon

**Comment by PoisonAlien** [comment]
Its hard to imagine the issue without a reproducible example. I also don't see your output from `CE.res`. You can just copy paste your output from R. 

One more thing to remember is that the test compares number of **mutated samples** and **not the number of mutations**. If a sample has multiple mutations in the same gene, its still a single sample.
