### ISSUE TITLE
Problem with oncoplot and nonmutated samples

### ISSUE THREAD

**Issue by oddmundn** [PoisonAlien/maftools#530]
I am trying to make an oncoplot with the oncoplot function of the maftools package (version 2.4.0), using R version 4.0.0. Everything is fine as long as I don't try to plot the nonmutated samples. But when I call:

    oncoplot(maftest,removeNonMutated=FALSE)

Error in top_bar_data[, colnames(numMat), drop = FALSE] : 
  subscript out of bounds

....I get the error message above. My MAF file contains nonmutated samples, having just a name, but otherwise empty. Is there an issue with the format of those nonmutated rows in the MAF file or have I found a bug? I did not experiece this message with a previous version of R/BionConductor and maftools.

sessionInfo() R version 4.0.0 (2020-04-24) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Manjaro Linux

Matrix products: default BLAS: /usr/lib/libblas.so.3.9.0 LAPACK: /usr/lib/liblapack.so.3.9.0

locale: [1] LCCTYPE=enUS.utf8 LCNUMERIC=C
[3] LCTIME=enUS.UTF-8 LCCOLLATE=enUS.utf8
[5] LCMONETARY=enUS.UTF-8 LCMESSAGES=enUS.utf8
[7] LCPAPER=enUS.UTF-8 LCNAME=C
[9] LCADDRESS=C LCTELEPHONE=C
[11] LCMEASUREMENT=enUS.UTF-8 LC_IDENTIFICATION=C

attached base packages: [1] stats graphics grDevices utils datasets methods base

other attached packages: [1] maftools_2.4.0

loaded via a namespace (and not attached): [1] compiler4.0.0 Matrix1.2-18 tools4.0.0 RColorBrewer1.1-2 [5] survival3.1-12 splines4.0.0 grid4.0.0 data.table1.12.8 [9] lattice_0.20-41

**Comment by PoisonAlien** [comment]
I can reproduce this. Thank you for reporting. I will fix it soon.

**Comment by PoisonAlien** [comment]
Hi,
I have fixed the issue. Could you please try it out and let me know if it fixes the issue?
You will have to install from GitHub.

```r
BiocManager::install("PoisonAlien/maftools")
```

**Comment by oddmundn** [comment]
Yes, it works.
Thank you very much!

Oddmund

On Thursday, May 21, 2020 11:55 CEST, Anand Mayakonda <notifications@github.com> wrote:
 
 
Hi,
I have fixed the issue. Could you please try it out and let me know if it fixes the issue?
You will have to install from GitHub.BiocManager::install("PoisonAlien/maftools")
