### ISSUE TITLE
plotVaf color palette

### ISSUE THREAD

**Issue by Michael-T64** [PoisonAlien/maftools#531]
Hello,

Would it be possible to allow users to specify the color palette for the plots that are generated using plotVaf?

Thanks

**Comment by PoisonAlien** [comment]
Hello,
Unfortunately its not possible for now as they are hardcoded. 
But I am happy to make it as an argument. I will implement it soon.

**Comment by PoisonAlien** [comment]
Hi, 
I have added `color` argument to `plotVaf`. Could you try it out and let me know if it helps? You will have to install from GitHub.

```r
BiocManager::install("PoisonAlien/maftools")
```

**Comment by Michael-T64** [comment]
Hi,

Yep that worked perfectly for what I needed. Thanks so much for the super quick response!
