### ISSUE TITLE
geneCloud

### ISSUE THREAD

**Issue by kunstner** [PoisonAlien/maftools#532]
Hi,

I'm using maftools v2.4.05 and I am wondering what happened to the 'geneCloud' command. I found it quite useful in previous versions.

Thanks,
 Axel

**Comment by PoisonAlien** [comment]
Hi,
Since the function was barely used and added an extra dependacy to the package, I removed it in 2.4.0 :|
But I have hosted it on [gist](https://gist.github.com/PoisonAlien/3f8752a89c1d63f64afe55b441621223) that you can source it and use. You will need `wordcloud` installed.

```r
> library("wordcloud")
> devtools::source_gist(id = "https://gist.github.com/PoisonAlien/3f8752a89c1d63f64afe55b441621223")
> geneCloud(input = your_maf)
```

**Comment by kunstner** [comment]
Wonderful! Many thanks.
