### ISSUE TITLE
Background color gisticOncoPlot

### ISSUE THREAD

**Issue by kunstner** [PoisonAlien/maftools#533]
Hi, 

I wonder whether it is possible to add a parameter to the gisticOncoPlot function for setting a different background color similar to the oncoplot function.

Best,
 Axel

**Comment by PoisonAlien** [comment]
Hi,
Please accept my apologies. I somehow missed to followup on this issue. 
I have added `bgCol` argument to `gisticOncoPlot` which should do the job. Let me know if this helps.

**Comment by kunstner** [comment]
Hi,

many thanks. Works as expected.

Best,
 Axel

**Comment by MaryGoAround** [comment]
Hello

Is this possible to show only peaks we want in `gisticOncoPlot` like `markBands` argument in ``gisticChromPlot`?

Thanks you
