### ISSUE TITLE
somaticInteraction color - wrong direction

### ISSUE THREAD

**Issue by ipstone** [PoisonAlien/maftools#537]
Thanks for this great/very useful maftools!

I began to use somaticInteraction to test some mutation interactions (using the latest github version, details below). Though the somaticInteraction calculation result shows the interaction are mutually exclusive but **somehow the color scale is opposite for some cases:**

![Screen Shot 2020-05-28 at 5 35 00 PM](https://user-images.githubusercontent.com/825723/83199397-18bf6800-a10f-11ea-9350-5bddb50c7ac9.png)

![Screen Shot 2020-05-28 at 5 35 28 PM](https://user-images.githubusercontent.com/825723/83199409-1ceb8580-a10f-11ea-8c77-07326aa21e1f.png)

When I switched to an older version of maftools (maftools_2.2.0) , the color looks ok now:
![Screen Shot 2020-05-28 at 6 15 23 PM](https://user-images.githubusercontent.com/825723/83199457-3a205400-a10f-11ea-95a8-4b72f401186e.png)

I am guessing there might be an issue with the color in the somaticInteractions (though when I am running the included laml demo samples, the color looks correct).

```
> packageVersion("maftools")
[1] ‘2.4.5’
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/ipstone/miniconda3/lib/libopenblasp-r0.3.7.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ipfun_0.0.1       data.table_1.12.8 maftools_2.4.05  

loaded via a namespace (and not attached):
 [1] compiler_3.6.1     Matrix_1.2-18      tools_3.6.1        RColorBrewer_1.1-2
 [5] survival_3.1-8     R.methodsS3_1.8.0  splines_3.6.1      grid_3.6.1        
 [9] R.utils_2.9.2      R.oo_1.23.0        lattice_0.20-38   

```

**Comment by ipstone** [comment]
I suspect now, it might be the older version of other packages such as RColorBrewer etc. causing this issue (I remembered when installing the github version of maftools there was prompt to update other dependent packages - which I didn't do).

I will test again on a clean install on arch Linux to see if this is the cause.

**Comment by PoisonAlien** [comment]
Could you provide me with a reproducible example? I have tested it on multiple tcga cohorts and it seems to be fine.

**Comment by ipstone** [comment]
Thanks @PoisonAlien : I think it's most likely due to other 'outdated' package on my system - I am closing this ticket.
