### ISSUE TITLE
Make FLAGS a Global Variable in User Workspace to Improve Its Accessibility

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#542]
Line 39 of summarizeMaf function defines the top 20 FLAGS. Could it be turned into a global variable, so that users could easily make use of it in other analyses (e.g. `oncoplot`)? Perhaps all 100 genes should be in the vector, to allow users to subset it to a smaller number (e.g. Top 25) themselves.

**Comment by PoisonAlien** [comment]
Hi,
I am not so comfortable with global variables in R. I have made an internal function `flags` that you can access with `maftools:::flags()`. I will export it in the next coming BC release. 
Let me know if this helps.
