### ISSUE TITLE
9.5.1 Forest plots : What is the base number in the log odds ratio?

### ISSUE THREAD

**Issue by ninnywolf** [PoisonAlien/maftools#545]
Dear Dr. Mayakonda,
Sorry to bother you. I have a question when using Maftools.
In the 9.5.1 Forest plots section, i wonder what is the base number in the plotted graph? Is it 10 or e？
Thanks for your time.

Yours,
Grant Lang

**Comment by PoisonAlien** [comment]
Hi,
No worries at all. It is `log10` of OR.

**Comment by ninnywolf** [comment]
> Hi,
> No worries at all. It is `log10` of OR.

Dear Dr. Mayakonda, 
Thank you very much!
