### ISSUE TITLE
Enable Clinical Variable Assignment to Lollipop Stem Colour

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#546]
I had a request from a biologist to assign a variable from the clinical data (e.g. smoking status) to the stem colour in the lollipop plot, which is always grey. Could it be possible to do by the next release?

**Comment by PoisonAlien** [comment]
That's actually a good idea. 
Yeah sure, I will do my best.

**Comment by DarioS** [comment]
Maybe not after I thought about it more. You could have the same location for both values of the variable and then there would be overplotting and one of them would not be visible. I guess that `lolliipopPlot2` is a safer solution.

**Comment by PoisonAlien** [comment]
Yeah its more complicated when you have more than two values for a clinical variable. (e.g, `Smoking status = low, inter, high`). In that case the bar length should be color coded with multi colors, with their length being proportional to the number of events? As below example..

<img width="81" alt="Screenshot 2020-06-09 at 11 21 10 AM" src="https://user-images.githubusercontent.com/8164062/84130255-542d3100-aa43-11ea-93fe-c817d4cddc4d.png">

**Comment by DarioS** [comment]
Oh, that would be nice, now that I see the sketch. It generalises simply to more than two categories, so would provide something more flexible than lollipop2.

**Comment by PoisonAlien** [comment]
This is more complicated than I expected. Closing it :D
