### ISSUE TITLE
Network of mutational changes

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#548]
Hello @PoisonAlien 

I have a suggestion

maftools nicely plots the proportion of affected genes and pathways

Tools like `HotNet2` systematically identifies the genes or pathways showing the most recurrent mutational changes 

Like here that prioritise the nodes in the network by the mutations they have

![Untitled](https://user-images.githubusercontent.com/60115705/84292173-ef0a3600-ab3d-11ea-98b7-ba84c96f804a.png)

I am wondering is it possible to implant such an idea in maftools?

Thank you anyway

**Comment by PoisonAlien** [comment]
Hello,
`Hotnet2`, `Dendrix` they are all meant for a specific purpose to identify set of genes (>2) that are mutated in mutually exclusive manner. This would not be possible to implement in maftools.

**Comment by MaryGoAround** [comment]
Thank you @PoisonAlien 

maftools displays mutually exclusiveness and co-occurance of mutated genes

Can maftools does the same for copy number altered genes (or combination of mutation and copy number altered).

**Comment by PoisonAlien** [comment]
Unfortunately CNVs are not supported.
