### ISSUE TITLE
Oncoplot Genes in At Least A Number of Samples Option

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#549]
It would be nice to have an option similar to `top` that allowed the user to specify all genes with variants in at least a minimum number of samples. I'm trying to plot all genes mutated in 3 or more patients out of 20 and using trial and error to set `top` but it could be made easier.

**Comment by PoisonAlien** [comment]
Hi,
I have added `minMut` argument to `oncoplot`.
Usage:

```r
# Draws all genes with 5% mutation rate (if minMut <1, it will be considered as % mutated)
oncoplot(maf = laml, minMut = 0.05)

# Draws all genes with 5 alterations 
oncoplot(maf = laml, minMut = 5)
```
Please check this and let me know if it works as expected..

**Comment by DarioS** [comment]
Very convenient!
