### ISSUE TITLE
Gene-Sample Mutation Count Matrix

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#55]
Currently, there is a function `getGeneSummary` and another `getSampleSummary`. It's almost what I'm looking for. What I need to do is create a matrix of genes (rows) vs. samples (columns) where the values in the matrix are the number of non-synonymous mutations for a particular gene of a particular sample. A function that does the gene-sample summarisation would be convenient to use via maftools.

**Comment by PoisonAlien** [comment]
Hi,

This seems like a nice idea. I will implement it soon.

**Comment by PoisonAlien** [comment]
Hi,
I have added a new function `mutCountMatrix` which will create such matrix. You can install maftools from github and try it out. Let me know if you find any errors or bugs. 

Thanks.

**Comment by DarioS** [comment]
It seems good to me.

**Comment by kguion1** [comment]
Quick clarifying question: Does the `mutCountMatrix` include silent mutations or does it only count what have been defined as non-silent and ignore the mutations stored  in `maf.silent`?

**Comment by ShixiangWang** [comment]
@kguion1 please read the doc of a function before posting an issue. At default, only non-silent mutations are included.

![image](https://user-images.githubusercontent.com/25057508/119617004-e6d10680-be33-11eb-9928-7616d2cb80e5.png)

**Comment by kguion1** [comment]
my apologies. I did actually read the documentation. However, I am new to some of the biology terminology and did not immediately understand that synonymous variants is referring to silent mutations. Thank you for your quick response.
