### ISSUE TITLE
can maftools summary the base transform of each gene, like the following excel

### ISSUE THREAD

**Issue by 2236529177** [PoisonAlien/maftools#550]
the table contains the ref and alt base in each column, will maftools creat such a function.
thanks  a  lot
![image](https://user-images.githubusercontent.com/25199946/84680441-50c70780-af65-11ea-90c9-9e12fa24343f.png)

**Comment by PoisonAlien** [comment]
Hi,
This seems quite straight forward that can be done with couple of melt and cast functions. If it is really helpful, then I can implement it. I will let you know..

**Comment by 2236529177** [comment]
really helpful，thanks  a lot

**Comment by PoisonAlien** [comment]
Hi,
I have implemented this feature in the `devel` branch. Could you please test it and let me know ?
See `?refAltMat` for details.

```r
BiocManager::install(pkgs = "poisonalien/maftools@devel")

# example MAF
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)

# usage
refAltMat(m = laml) # generate whole matrix
refAltMat(m = laml, genes = 'DNMT3A') #Restrict output to DNMT3A gene
refAltMat(m = laml, tsb = 'TCGA-AB-2987') #Restrict output to the sample TCGA-AB-2987
```
