### ISSUE TITLE
not all annotation legends are visible

### ISSUE THREAD

**Issue by nygr** [PoisonAlien/maftools#552]
**Describe the issue**
A clear and concise description of what the issue is.
Hi, i have the following code (below)

and when it prints the plot it only shows legend for clinical features until "Analysis" and the rest it cuts out, and spaces between the clinical features legend is so big. How to fix this? I have tried using larger device size and larger pdf width when printing the plot but it doesnt work. 

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
oncoplot(maf=tn_t_maf, fontSize = 0.6,mutsig ="/Users/nygrpetr/Desktop/Work/DNA_seq/nktcl_tn_sig_edit" ,  mutsigQval = 0.01,
         clinicalFeatures = c( "Malignancy","Sex", "Age", "Analysis", "Study"), annotationFontSize = 1, top = 20,
         showTumorSampleBarcodes = F, SampleNamefontSize = 0.5, drawColBar = T, drawRowBar = F,
         sortByAnnotation=F, removeNonMutated = F
         )
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Could you please your sessionInfo?
