### ISSUE TITLE
geneCloud has been removed?

### ISSUE THREAD

**Issue by 2236529177** [PoisonAlien/maftools#555]
Dear professor,
geneCloud has been removed?  I want to use the maf file to draw a gene cloud like following
thanks a lot.
![image](https://user-images.githubusercontent.com/25199946/85871975-bcc92b80-b801-11ea-84ca-eaf15f3d7227.png)

**Comment by PoisonAlien** [comment]
Hi, 
yes - this function has been removed in the new releases. If you still would like to use it, check out the issue #532

**Comment by 2236529177** [comment]
Thanks a lot
function(input, minMut = 3, col = NULL, top = NULL, genesToIgnore = NULL, ... )

which parameter can set the plot be a circle or rectangle or any other shapes

**Comment by PoisonAlien** [comment]
There is no such parameter. You can pass additional arguments to the function and they will be passed to `wordcloud`

**Comment by 2236529177** [comment]
and the minMut means the gene mutation sample numbers or others?

**Comment by PoisonAlien** [comment]
Hi,
`minMut` refers to `Minimum number of samples in which a gene is required to be mutated.`
Also there is no `shape` argument in wordcloud. You can check the available options with `?wordcloud::wordcloud()`

**Comment by 2236529177** [comment]
thanks a lot
