### ISSUE TITLE
Hello, when i use subsetMaf() function, an error was present 'Can not cast an empty data.table'

### ISSUE THREAD

**Issue by ltgmri** [PoisonAlien/maftools#558]
Hello, when when i use subsetMaf() function to extract special samples ,an  an error was present  that is: 
'Error in dcast.data.table(data = vc, formula = Tumor_Sample_Barcode ~  :  Can not cast an empty data.table'

the detailed questions was below:

the code is    
```r
maf_1_high <- subsetMaf(maf=maf_1, tsb = c('TCGA-AG-A002'), isTCGA = TRUE)
```

when i use 'getSampleSummary(maf_1) ` to get the sample summary, the first sample is 'TCGA-AG-A002-01A-01W-A00K-09 ' 

the sample is really exist, but i can't extract it.

```r
class(maf_1) 
[1] "MAF"
attr(,"package")
[1] "maftools"

sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] TCGAbiolinks_2.16.1 maftools_2.4.10     data.table_1.12.8  
```

I have been engaged for 2 days for this problem,Looking forward to your reply. Thank you very much!

**Comment by PoisonAlien** [comment]
Hi,
Setting `isTCGA = TRUE` will truncate the barcode to first 12 characters. That means your maf should also be generated with `isTCGA = TRUE` while reading with `read.maf`. This seems to be not the case here since your maf has the full length barcode. 

Could you try with full barcode name as in below and it should work.

```r
maf_1_high <- subsetMaf(maf=maf_1, tsb = c('TCGA-AG-A002-01A-01W-A00K-09'))
```

**Comment by ltgmri** [comment]
Thank you very much!, it really works. According your instruction, when i use read.maf() function to read data, the parameter isTCGA = FALSE changed to True, then i can use this code
maf_1_high <- subsetMaf(maf=maf_1, tsb = c('TCGA-AG-A002'), isTCGA = TRUE). 
But when i use only the 12 characters, may be there will be duplicate sample names, because the sample from different parts of the same patient wil be given the same same barcode.
Will it affect data import and the subsequent data analysis?

**Comment by ltgmri** [comment]
By the way, when i use coOncoplot() to plot the different mutation in two groups, the default genes number is 5, how to display the top 10  different mutation genes. thank you.

**Comment by PoisonAlien** [comment]
Yes, it will affect the downstream analysis. 
`isTCGA` exists to speed up some processes where annotations are usually available with 12 characters whereas barcodes in MAF are not. I suggest not to use `isTCGA` argument.

Also there is no top argument for coOncoplot. Use `genes` instead.
