### ISSUE TITLE
Add clinical data to survGroup

### ISSUE THREAD

**Issue by Tato14** [PoisonAlien/maftools#559]
There are some PFS/OS predictors that join both Clinical an Mutation signatures to develop kind of a "Score". An illustrative example would be [this one](https://ashpublications.org/blood/article/134/Supplement_1/122/426293/Evaluation-of-the-m7-FLIPI-in-Patients-with)

Could it be possible to include one or more than one clinical variable in maftools mutation survival analysis to combine both molecular and clinical information?

**Comment by PoisonAlien** [comment]
Hi,
If I understand correctly you are suggesting to add support for multivariate survival analysis?

**Comment by Tato14** [comment]
Hi @PoisonAlien,

Sorry If do not explain myself properly. Uhm, yes I guess multivariate survival analysis would be a good starting point. 

Actuall,y the link above builds kind of a linear (not sure) model using both mutations in specific genes and clinical features as categorical variables and give a prediction on OS. 

What I had in mind was something more related with this. If I understood how `survgGroup` works, it looks for samples with specific mutations (one or more than one), use them as categorical variables (Mutation/No Mutation) and builds the survival curves comparing between groups, iteratively. I was thinking more on add more categorical variables that you could specify (like some clinical data) in the iteration process. Ideally rather than binary, the clinical variables would be multicatogerical so I am not sure if this could be easy to implement.

**Comment by PoisonAlien** [comment]
I see.. I can not comment on the difficulty part but, I would be happy to give it a try (it might take a while though).

**Comment by Tato14** [comment]
It would be great! Ping me if you think I can contribute somehow! Thanks!

**Comment by Tato14** [comment]
I worked a little bit on this. I could manage to include binary clinical labels in `mutMat` doing:

```
mutMat$Tumor_Sample_Barcode <- rownames(mutMat)
explanatory = c("Age", "Sex", "Tumor_Sample_Barcode")
CL_to_mat <- Clinical_Data %>% select(all_of(explanatory))
mutMat <- left_join(mutMat, CL_to_mat, by=c("Tumor_Sample_Barcode" = "Tumor_Sample_Barcode"))
rownames(mutMat) <- mutMat$Tumor_Sample_Barcode
mutMat <- subset(mutMat, select=-c(Tumor_Sample_Barcode))
```

And generating again `genes` and `genesCombn`:
```
genes <- colnames(mutMat)
genesCombn = combn(x = genes, m = geneSetSize)
```

It's quite dirty but it seems to work in my samples. However, I am unsure how to manage multiple label variables issue since I don't know how to transform this line:
```
genesTSB = names(which(rowSums(mm) == geneSetSize))
```
into something that would accept multilabels and escalate. Any ideas?

**Comment by Tato14** [comment]
As a workaround for the non-binary variables I can generate some intuitive results by transforming them to `n` binary variables as explained [here](https://rdrr.io/cran/varhandle/man/to.dummy.html). 

For this you need to refactor this variables prior to `left_join` and follow the steps as the message above

**Comment by PoisonAlien** [comment]
I am working on a separate function on the devel branch. I will update you once I have it working. 
It seems to become complex with multiple categories within a group.
