### ISSUE TITLE
read.maf Changes Sample ID Format

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#56]
The change of format makes it difficult to match the samples to other data, such as RNA-seq expression.

```
> str(CM1)
Classes ‘data.table’ and 'data.frame':	56929 obs. of  120 variables:
 $ Hugo_Symbol                  : chr  "PRAMEF17" "DPYD" "CHIAP2" "CAPZA1" ...
     ...                        ...
 $ Tumor_Sample_Barcode         : chr  "TCGA-AG-3909-01A-01W-1073-09" "TCGA-AG-3909-01A-01W-1073-09" "TCGA-AG-3909-01A-01W-1073-09" "TCGA-AG-3909-01A-01W-1073-09" ...
 $ Matched_Norm_Sample_Barcode  : chr  "TCGA-AG-3909-10A-01W-1073-09" "TCGA-AG-3909-10A-01W-1073-09" "TCGA-AG-3909-10A-01W-1073-09" "TCGA-AG-3909-10A-01W-1073-09" ...
      ...                        ...

> MAF1 <- read.maf(CM1, useAll = FALSE)
> str(MAF1)
Formal class 'MAF' [package "maftools"] with 10 slots
  ..@ data                          :Classes ‘data.table’ and 'data.frame':	37272 obs. of  120 variables:
  .. ..$ Hugo_Symbol                  : chr [1:37272] "PRAMEF17" "DPYD" "CAPZA1" "KCNK1" ...
     ...                        ...
  .. ..$ Tumor_Sample_Barcode         : Factor w/ 136 levels "TCGA.AF.2687.01A.02D.1733.10",..: 40 40 40 40 40 40 40 40 40 40 ...
  .. ..$ Matched_Norm_Sample_Barcode  : chr [1:37272] "TCGA-AG-3909-10A-01W-1073-09" "TCGA-AG-3909-10A-01W-1073-09" "TCGA-AG-3909-10A-01W-1073-09" "TCGA-AG-3909-10A-01W-1073-09" ...
       ...                        ...
```

As this example shows, the sample IDs of the tumours have had hyphens replaced by periods. Also, it's probably undesirable that one column is a factor but the other is a character vector. They should probably both be characters, since you'd never use the factor levels in a linear model, for example (only 1 sample per patient).

**Comment by PoisonAlien** [comment]
Hi,

In most of the cases when data is converted into matrix or a data frame, hyphens in headers are automatically converted to periods. This leads to inconsistencies for downstream processes. For example try reading any matrix or data frame with column headers containing hyphens and they will read as periods by read.table or read.delim. To avoid this, hyphens are converted to  periods. 

Regarding factors, many other functions in maftools require total number of samples from the cohort which is often best persevered when converted to factors/levels. 

I do understand this is bit annoying, but for now this is the simplest way to avoid hyphens :|

**Comment by DarioS** [comment]
Now that you explain it, I understand why you'd want to use factors. For example, `length(levels(IDs))` is a quick way to calculate the number of samples contained in the MAF file.

I know that R will automatically do the conversion from hyphens to periods in column names and I see that you have pre-empted it in `validateMaf`.

```
maf$Tumor_Sample_Barcode = gsub(pattern = '-', replacement = '.', x = as.character(maf$Tumor_Sample_Barcode))
```

For `data.frame` and `matrix` variables, it's not necessary to avoid hyphens and spaces in column names. For example,

```
> dataTable <- data.frame(`TCGA-AB-1234` = 1:2, `TCGA-AB-2345` = 9:10, check.names = FALSE)
> dataTable
  TCGA-AB-1234 TCGA-AB-2345
1            1            9
2            2           10
> dataMatrix <- matrix(c(1:2, 9:10), ncol = 2, dimnames = list(NULL, c("TCGA-AB-1234", "TCGA-AB-2345"))) 
> dataMatrix
     TCGA-AB-1234 TCGA-AB-2345
[1,]            1            9
[2,]            2           10
```

Conversion means that the tumour and normal samples are using a different naming system.

```
> head(maf[, 16:17])
           Tumor_Sample_Barcode  Matched_Norm_Sample_Barcode
1: TCGA.AG.3909.01A.01W.1073.09 TCGA-AG-3909-10A-01W-1073-09
2: TCGA.AG.3909.01A.01W.1073.09 TCGA-AG-3909-10A-01W-1073-09
3: TCGA.AG.3909.01A.01W.1073.09 TCGA-AG-3909-10A-01W-1073-09
4: TCGA.AG.3909.01A.01W.1073.09 TCGA-AG-3909-10A-01W-1073-09
5: TCGA.AG.3909.01A.01W.1073.09 TCGA-AG-3909-10A-01W-1073-09
6: TCGA.AG.3909.01A.01W.1073.09 TCGA-AG-3909-10A-01W-1073-09
```

It also means that the output of functions like `mutCountMatrix` needs users to make changes such as `gsub("\\.", '-', colnames(mutationCounts))` before the mutation matrix can be matched by sample to a gene expression matrix, such as one created by TCGAbiolinks.

The NCI Wiki recommends [avoiding the barcode in favour of UUID](https://wiki.nci.nih.gov/display/TCGA/Universally+Unique+Identifier), because they can change for a sample if it's previously thought to be a primary cancer, but later identified as metastasis, for example. Would it bet better to report UUID instead of barcode to the users of maftools?

**Comment by PoisonAlien** [comment]
Oh.. wasn't aware of `check.names` ! I will try and see if it works good, it should solve this issue. Thanks for pointing me towards it. 

I agree with using UUID, but again I think its not as widely used as barcodes. Most of the tools used to generate maf still uses Tumor_Sample_Barcode as to represent sample IDs; for e.g; vcf2maf. Maybe for now using `Tumor_Sample_Barcode` would be better way (or making UUID as an optional argument to `read.maf`). 

Let me try fixing naming issue. Thanks again.

**Comment by PoisonAlien** [comment]
Hi fixed this in recent push. No samples names wont get messed up and remains as is. Thank you for the suggestion.
