### ISSUE TITLE
Adding new feature to survival analysis

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#560]
Hello @PoisonAlien 

I have two mafs for two groups of patients. Is this possible to know genomic alteration in which genes differently related to survival between groups?

Let's say KRAS is being altered but can we know if KRAS related to survival in one groups and not in the other one

I think something like multivariate works, if a group is responder group and the other group is non responders, if KRAS genomic changes related to survival differently in two groups?

Thank you

**Comment by PoisonAlien** [comment]
Wouldn't it be simpler to just show two plots side by side for each group?

```r
#Add dummy response variable
laml@clinical.data$Response = sample(x = c("Yes", "No"), size = 193, replace = TRUE)
#Create two groups 
laml_R = subsetMaf(maf = laml, clinQuery = "Response %in% 'Yes'")
laml_NR = subsetMaf(maf = laml, clinQuery = "Response %in% 'No'")

#Plot survival
par(mfrow = c(1, 2))
mafSurvival(maf = laml_NR, time = 'days_to_last_followup', genes = 'DNMT3A', Status = "Overall_Survival_Status", addInfo = F)
legend(x = "bottomright", legend = "Non-responders", bg = "gray60")
mafSurvival(maf = laml_R, time = 'days_to_last_followup', genes = 'DNMT3A', Status = "Overall_Survival_Status", addInfo = F)
legend(x = "bottomright", legend = "Responders", bg = "gray60")
```

![Rplot02](https://user-images.githubusercontent.com/8164062/86215621-15d7ed00-bb7d-11ea-97f7-b3d26cf66f0c.png)

**Comment by beginner984** [comment]
Thank you much

I guess that could be like a multivariate thing. If we going two mafs and we have response to chemotherapy and non response to chemotherapy like a `1 , 0` vector, genomic alteration in a given gene in another vector, survival can be looked in terms of interaction of response and genomics alterations

To be honest I am not even sure

**Comment by PoisonAlien** [comment]
I am closing this for now.

**Comment by beginner984** [comment]
Good morning @PoisonAlien 

Thank you

How I get access to a vector of mutation status of genes (Let's say 0 , 1 or whatever els that I am not aware) which Maftools itself internally extract to feed that into survival analysis? If so I would be able to do survival analysis manually myself in a close view

**Comment by PoisonAlien** [comment]
Its bit more complex than that. You can check out the source code [here](https://github.com/PoisonAlien/maftools/blob/master/R/mafSuvival.R#L121).
