### ISSUE TITLE
saving maftools plots to outputfile

### ISSUE THREAD

**Issue by jotes35** [PoisonAlien/maftools#561]
**Describe the issue**
Is there a function that allows you to save maftools plots to output file For example if I have a MAF object and i use the  _plotmafSummary_ function. How do I export the figures generated to an output file called _summary.png_

This will come in handy in situations where I have access to only commandline interface such as an hpc environment

**Comment by PoisonAlien** [comment]
Hi,
An plot in R can be saved with `pdf` `png` `tiff` `jpeg` `bmp` commands. You need to call them before plotting and end them once you;re done. Use `?png` for details on file dimensions, resolution etc. 

```r
png(filename = "maf_summary.png")
plotmafSummary(my_maf)
dev.off()
```
There should be `maf_summary.png` with your plot in the working directory.
