### ISSUE TITLE
tcgaCompare Allows Only One MAF Object Input

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#562]
My collaborator researches head and neck cancer and has data of two types; oral carcinoma and cutaneous carcinoma. Oral carcinoma has a mutation rate of 3 to 6 mutations per megabase. Cutaneous carcinoma has a mutation rate of 50 to 300 mutations per megabase. It would be desirable to plot both types on the same plot with tcgaCompare. Also, the function description contains "33 TCGA cohorts derived from MC3 project." There should be a link to the MC3 project using `\references{}` in the Rd file. It looks like MC3 uses a few different variant callers and it's unclear from the documentation which one is used. MuTect2? MUSE?

**Comment by PoisonAlien** [comment]
Hi,
`tcgaCompare` does take multiple MAFs as input. 

```r
tcgaCompare(maf = c(maf1, maf2))
```

Variant caller column is deleted from the maf objects to keep the size low. You can still get this information in [original MAF](https://gdc.cancer.gov/about-data/publications/mc3-2017) file provided by MC3 under the column `NCALLERS`.

**Comment by DarioS** [comment]
Ah, they can be concatenated.
