### ISSUE TITLE
tcgaCompare Plot Without Any TCGA Cohort

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#563]
I have whole genome sequencing data and so the MAF object contains mutation from across the genome. `tcgaCompare` is based on TCGA's exome sequencing data and the mutation rate typically differs between exons and intergenic regions, because most intergenic regions are not under functional constraint. Therefore, I am trying to remove all TCGA cohorts by using `tcgaCompare(maf = laml, cohortName = "AML", tcga_cohorts = "")` which causes an error message "Something went wrong. Provide correct names for 'tcga_cohorts' arguments". Could there perhaps be a version of this function not dependent on TCGA data and just plots the user's MAF object(s) ? Or, do you know of any project which did SNV calling using TCGA whole genomes? I heard that Genomic Data Commons is currently doing that.

**Comment by PoisonAlien** [comment]
Hi,
I can modify the function to work without tcga cohorts. About the second part, I do not know any such studies with TCGA whole genomes.

**Comment by Vyoma24** [comment]
> I have whole genome sequencing data and so the MAF object contains mutation from across the genome. `tcgaCompare` is based on TCGA's exome sequencing data and the mutation rate typically differs between exons and intergenic regions, because most intergenic regions are not under functional constraint. Therefore, I am trying to remove all TCGA cohorts by using `tcgaCompare(maf = laml, cohortName = "AML", tcga_cohorts = "")` which causes an error message "Something went wrong. Provide correct names for 'tcga_cohorts' arguments". Could there perhaps be a version of this function not dependent on TCGA data and just plots the user's MAF object(s) ? Or, do you know of any project which did SNV calling using TCGA whole genomes? I heard that Genomic Data Commons is currently doing that.

I'm facing similar problem.What solution were you able to come up with?Any help in this direction would be appreciated.

**Comment by DarioS** [comment]
I used GENCODE Genes to subset the VCF records to only the ones which overlap with a known exon, to consider only the SNVs which could also be detected using exome sequencing. It depends on biological focus you are investigating, though. Disappointingly, Genomics Data Commons still does not have TCGA whole genome SNV calls available.

**Comment by PoisonAlien** [comment]
Hi both,
Mutational load from TCGA cohorts in `tcgaCompare` is derived from [MC3](https://gdc.cancer.gov/about-data/publications/mc3-2017) maf file. Fortunately MC3 also provides the [target BED](https://api.gdc.cancer.gov/data/7f0d3ab9-8bef-4e3b-928a-6090caae885b) file. Best way would be subset your MAF object to this BED regions and compare against tcga cohorts. 

GDC does not provide WGS SNPs due to privacy concerns - you will have download the BAM files and redo the calling if at all required. Also not many cohorts are sequenced for whole genome. Only few samples from LAML were done for WGS since mutational load was severely low. Another option would be to search for ICGC cohorts but I doubt they will include intergenic variants/SNPs.

**Comment by DarioS** [comment]
Just for a bit of context, I asked the data coordination centre a few months ago and they are currently in the process of realigning all of the TCGA whole genome sequencing data to hg38. There are a few thousand files in the project. Our research group has downloaded some data for HNSC. It's tricky to process because different samples use different instruments and different read lengths. Some samples are pairs of 51 bases reads, some others are pairs of 101 bases reads. Some cancer samples have about 8 times read coverage and the others have about 60 times read coverage. Thoughtful experimental design is not TCGA's strong point!
