### ISSUE TITLE
How to remove annotation border 

### ISSUE THREAD

**Issue by LuffyLuffy** [PoisonAlien/maftools#564]
Hi, there,
If FAB_classification is too much, the white border would cover the FAB set color. 
![image](https://user-images.githubusercontent.com/15357865/86864915-9b6d1700-c100-11ea-8137-aac6bbe23630.png)

library(maftools)
#path to TCGA LAML MAF file
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
#clinical information containing survival information and histology. This is optional
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')

laml = read.maf(maf = laml.maf,
                clinicalData = laml.clin,
                verbose = FALSE)
aml_genes = c("TP53", "WT1", "PHF6", "DNMT3A", "DNMT3B", "TET1", "TET2", "IDH1", "IDH2", "FLT3", "KIT", "KRAS", "NRAS", "RUNX1", "CEBPA", "ASXL1", "EZH2", "KDM6A")

#Variant allele frequcnies (Right bar plot)
aml_genes_vaf = subsetMaf(maf = laml, genes = aml_genes, fields = "i_TumorVAF_WU", mafObj = FALSE)[,mean(i_TumorVAF_WU, na.rm = TRUE), Hugo_Symbol]
colnames(aml_genes_vaf)[2] = "VAF"
oncoplot(maf = laml, genes = aml_genes,
         clinicalFeatures = 'FAB_classification',
         bgCol = NULL,borderCol = NULL)

**Comment by PoisonAlien** [comment]
Hi,
Are you referring to the color of grid lines? I have added `annoBorderCol` argument to `oncoplot`. Set it to `NA` (by default) to remove the border or any other color of your choice.

**Comment by LuffyLuffy** [comment]
> Hi,
> Are you referring to the color of grid lines? I have added `annoBorderCol` argument to `oncoplot`. Set it to `NA` (by default) to remove the border or any other color of your choice.

Great, It works out! It looks better!
