### ISSUE TITLE
Oncoplot x-axis Label Rotation

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#565]
I would like there to be an option to rotate the labels to a different angle, such as 45 degrees.

**Comment by PoisonAlien** [comment]
X-label as in sample names?

**Comment by PoisonAlien** [comment]
I have added `barcodeSrt` argument. Set it to 45 (by default its 90)

**Comment by DarioS** [comment]
Yes, the sample identifiers.
