### ISSUE TITLE
tcgaCompare Select Cohort Sub-type

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#566]
Many of the TCGA cohorts have two main sub-types. For example, CESC's description is "TCGA studied two main types of cervical cancer: squamous cell carcinoma ... and adenocarcinoma ...". Similarly, for ESCA, "TCGA studied the two most common types of esophageal cancer: squamous cell ... and adenocarcinoma ...". These sub-types are not recorded in maftools data.

```r
> head(tcga.cohort)
   cohort Tumor_Sample_Barcode total                    site
1:    ACC         TCGA-OR-A5KB  1841 Adrenal Gland Carcinoma
2:    ACC         TCGA-PK-A5HB   975 Adrenal Gland Carcinoma
3:    ACC         TCGA-OR-A5JA   473 Adrenal Gland Carcinoma
4:    ACC         TCGA-OR-A5LJ   400 Adrenal Gland Carcinoma
5:    ACC         TCGA-OR-A5J5   351 Adrenal Gland Carcinoma
6:    ACC         TCGA-OR-A5JB   283 Adrenal Gland Carcinoma
```

Could the sub-type be recorded and `tcgaCompare` be modified to enable restriction to sub-type? Sub-types have somewhat different genomic characteristics. I guess the x-axis text would also need to have a companion parameter to `cohortName` for TCGA cohorts, perhaps `TCGAcohortsNames`, so that they could be appropriately re-labelled. For example, it would be more appropriate to write ESCC instead of ESCA if it was restricted to the squamous cell carcinoma sub-type.

**Comment by PoisonAlien** [comment]
This would better done manually since not all cohorts have subtype information and are not uniformly distributed. Whenever available subtypes are encoded in `clinical.data` slot usually under `histological` or `pathology` column.

```r
> tcga_cesc_mc3@clinical.data[,.N,histological_type]
                               histological_type   N
1:              Cervical_Squamous_Cell_Carcinoma 254
2:           Endocervical_Type_of_Adenocarcinoma  21
3:                                 Adenosquamous   6
4:  Mucinous_Adenocarcinoma_of_Endocervical_Type  17
5: Endocervical_Adenocarcinoma_of_the_Usual_Type   6
6:     Endometrioid_Adenocarcinoma_of_Endocervix   3

> tcga_esca_mc3@clinical.data[,.N,primary_pathology_histological_type]
   primary_pathology_histological_type  N
1:   Esophagus_Squamous_Cell_Carcinoma 96
2:       Esophagus_Adenocarcinoma,_NOS 89
``` 

You could easily subset these mafs into your subtypes of interest and then pass them to `tcgaComapre`.

**Comment by DarioS** [comment]
It is not in the overall summary file. `$ grep histological mc3.v0.2.8.PUBLIC.maf` shows nothing. Do you mean I need to get the TCGA Cohort Variant Calls which are Controlled Access to do this analysis?

**Comment by PoisonAlien** [comment]
Nope. MC3 maf file does not contain any clinical information about samples. It doesnt even mention the cancer type for the samples - let alone subtypes. I had to match the sample IDs to clinical data that I extracted from GDC databases or from TCGABiolinks and compile them.

**Comment by DarioS** [comment]
It won't be easy.
