### ISSUE TITLE
Clinical features with same labels are colored similarly in Oncoplot

### ISSUE THREAD

**Issue by pkhoueiry** [PoisonAlien/maftools#567]
**Describe the issue**
When two clinical features have the same labels, oncoplot colors them similarly and according to the first color chosen.

**Comment by PoisonAlien** [comment]
How does it look when you provide a manual list of colors?

**Comment by pkhoueiry** [comment]
Here is an example

```
clinical <- as.data.frame(cbind(Gender = Gender,
                                TimeToDeath = cut(TimeToDeath, breaks = c(1, 10, 20, 30, 40, 50), right = FALSE, labels = c("1-10", "10-20", "20-30", "30-40", "40-50")),
                                TimeToRecurrence = cut(TimeToRecurrence, breaks = c(1, 10, 20, 30, 40, 50), right = FALSE, labels = c("1-10", "10-20", "20-30", "30-40", "40-50"))))

library(RColorBrewer)
genderColors = c("blue", "pink")
time2DeathColors = RColorBrewer::brewer.pal(n = 5, name = "Blues")
time2RecurrenceColors = RColorBrewer::brewer.pal(n = 5, name = "Greens")

names(genderColors) = c("M", "F")
names(time2DeathColors) = c("1-10", "10-20", "20-30", "30-40", "40-50")
names(time2RecurrenceColors) = c("1-10", "10-20", "20-30", "30-40", "40-50")

annotationColor = list(Gender = genderColors, TimeToDeath = time2DeathColors, TimeToRecurrence = time2RecurrenceColors)

oncoplot(maf = maf, removeNonMutated = TRUE, colors = col, showTumorSampleBarcodes = FALSE,  clinicalFeatures = c("Gender", "TimeToDeath", "TimeToRecurrence"), annotationColor = annotationColor)
```

In this case, both `TimeToDeath` and `TimeToRecurrence` end up colored with `Blues` although `Greens` is specificied for `TimeToRecurrence`. 

My only way to overcome that was to change the labels for `TimeToRecurrence` to have them as `labels = c("_1-10", "_10-20", "_20-30", "_30-40", "_40-50")`.

It looks like colors are associated to labels instead of the pair clinical feature and labels!!!

This wasn't the case in previous version of `maftools`

**Comment by PoisonAlien** [comment]
Okay, I have fixed it. Could you please try it again and let me know? You will have to install from GitHub.
