### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by antu2817** [PoisonAlien/maftools#568]
Hi 
I used right column for AACol  (HGVSp_short) but I get the follwoing error
 "Error in lollipopPlot(maf = laml, gene = "Pigr", AACol = "HGVSp_Short",  : 
  Structure for protein Pigr not found" 
I can see amino acids changes availabe for this gene in maf file. Just for your reference I am using maftools for mouse genome. 

Thanks

**Comment by antu2817** [comment]
Hi
Thank you for your prompt response, I will run the analysis as you
suggested.
I am also planning to run somatic interaction analysis of maftools for
mouse variants, I believe that this module supports mouse genome and also
the analysis is purely based on the list of mutations and their
variant allele frequencies. Please confirm the same.
Thank you!!!

**Comment by PoisonAlien** [comment]
Yeah it should be fine for `somaticInteractions`

**Comment by antu2817** [comment]
Hi,
Thank you very much for the clarification.
