### ISSUE TITLE
Question about somaticInteractions

### ISSUE THREAD

**Issue by MaryGoAround** [PoisonAlien/maftools#569]
@PoisonAlien 

This is not an issue, this is question or may be a feature request

By `somaticInteractions` we can get mutual exclusive and co occurred mutated genes

If I add GISTIC data to my maf, is this function account for copy number altered genes too or only care about mutational status of genes?

If function does not care about copy number, please can you add that to the function?

Thank you so much

**Comment by PoisonAlien** [comment]
Hi,
It does counts CN events as well. 
I just realized the numbers in the plot show only mutation counts, I will fix it. But the results are fine.

**Comment by MaryGoAround** [comment]
@PoisonAlien 

Is there a way to do co occurrence and mutual exclusiveness for two pair pathway?

In this paper

https://www.biorxiv.org/content/10.1101/082552v1.full

They consider a pair of pathways co occurred if their genes co mutated significantly (Bt Fisher's exact test)

If the genes in pair of pathways are common they should bereaved

I could not what they meant by co mutated genes though

Is this possible to implant this in maftools?

**Comment by PoisonAlien** [comment]
Hi,
Unfortunately its not possible for me to implement it at the moment.
