### ISSUE TITLE
A bug in annovar2Maf?

### ISSUE THREAD

**Issue by aleiyishi** [PoisonAlien/maftools#570]
Hi Poison,
I run the annovar2Maf using the example data provided in the maftools package. I could not figure this problem below out:

![image](https://user-images.githubusercontent.com/14121102/87253164-7c2d0b80-c4ab-11ea-8079-fe0721365021.png)

Why are "RNA"s placed in the Variant_Classification column for nonsynonymous SNVs and frameshift insertions?

Thanks for your time!

**Comment by PoisonAlien** [comment]
Hi,
`annovar2Maf` simply converts annovar outputs to maf. It does not do any sort of filtering for synonymous or non-synonymous variants. This is done after generating `MAF` object with `read.maf`.
