### ISSUE TITLE
Coding sequence length of mutation position

### ISSUE THREAD

**Issue by Mussa1122** [PoisonAlien/maftools#572]
Hello

I have learned that by 

```
> om = maftools:::createOncoMatrix(m = laml,laml@data$Hugo_Symbol)
> 
> om=om$numericMatrix

> head(om[1:2,1:2])
       TCGA-AB-2945 TCGA-AB-2965
FLT3              2            7
DNMT3A            2            2
> 
```

We can get total number of mutation for gene g1 in sample s1

Mutational frequency per sample, for instance for DNMT3A would be, 2/4 and 2/4

But Coding sequence length of DNMT3A and FLT3 is different so mutation frequency should be adjusted for this especially if different mutations happen on different transcripts with with CDS length

I have obtained human CDS length from biomart 

Could you please help me how I can match CDS of each mutational position?

I want to adjust for CDS length

I googled for this but no luck yet

Very appreciated

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay in responding. The values in `om$numericMatrix` are not number of mutations. They are rather numeric codes for type of variant classification. If you want this count matrix use `maftools::mutCountMatrix(maf = laml)`. If you're simply looking for mutation load per gene then use `getGeneSummary(x = laml)`

For the second part are you trying to get the transcript name for the mutated gene?

**Comment by beginner984** [comment]
Thank you to save me to wrongly use `om$numericMatrix`

Having mutation counts

```
> head(maftools::mutCountMatrix(maf = laml))[1:5,1:5]
       TCGA-AB-2965 TCGA-AB-2945 TCGA-AB-2993 TCGA-AB-2869 TCGA-AB-2981
DNMT3A            1            1            1            1            1
FLT3              1            1            1            1            1
NPM1              1            1            1            1            1
TET2              1            0            0            0            0
IDH2              0            0            0            0            0
> 
```
Is this possible to normalise this matrix for coding sequence length?

Like

`1000*total number of mutations in gene1 in sample1/CDS Length`

The problem with above definition is this:

`What if a gene has a few different transcripts with mutations? For example, gene A has 3 mutations in transcriptA1 and 5 mutations in transcriptA2. Thus, CDS length of gene should be like A= (3* CDS length of transcriptA1  +   5* CDS length of transcriptA2)/(3+5)`

Is there any way to get CDS length of each mutation so matrix can be weighted fairly

I am not sure if this is possible or not

Highly appreciated

**Comment by Mussa1122** [comment]
> Hi,
> Sorry for the delay in responding. The values in `om$numericMatrix` are not number of mutations. They are rather numeric codes for type of variant classification. If you want this count matrix use `maftools::mutCountMatrix(maf = laml)`. If you're simply looking for mutation load per gene then use `getGeneSummary(x = laml)`
> 
> For the second part are you trying to get the transcript name for the mutated gene?

Yes please

**Comment by PoisonAlien** [comment]
Unfortunately there is no way to guess the transcript info from the genomic loci alone. 
But in most of the standard annotations generated by `annovar` or `VEP` or `vcf2maf` this information is stored under one of the transcripts column. You will have to parse this column.

**Comment by Mussa1122** [comment]
Hello

As you thought us, `maftools::mutCountMatrix(maf = laml)` returns `mutation counts (boolean values if a gene mutated in a sample or not)`

Is there any way to get the same count matrix for copy number status of a list of genes having gistic already added to maf object?

I want to do some machine learning of genomic alteration status which needs such a matrix 

So that would be greatly appreciated if I can something mutation counts matrix for copy number

**Comment by PoisonAlien** [comment]
It does include copy number events in the output.

e.g, TP53 is amplified in maf+gistic object.
```r
> rowSums(maftools::mutCountMatrix(maf = laml)[c("TP53", "FLT3"), ])
TP53 FLT3 
  19   52 
> rowSums(maftools::mutCountMatrix(maf = laml.plus.gistic)[c("TP53", "FLT3"), ])
TP53 FLT3 
  34   52 
```

**Comment by Mussa1122** [comment]
Thank you

Is this possible to get a numerical matrix only contain copy number status of genes from Maftools?

I have being trying to subtract the matrix from each other to get copy number changes only but as genes and samples are not the same (due to removal of non mutated genes , etc), I could not accomplish with this

**Comment by Mussa1122** [comment]
Hello @PoisonAlien 

The number from laml@summary are non-synonymous mutations or total mutations?

I have a maf object

```
> laml.plus.gistic@summary
                   ID summary         Mean Median
 1:        NCBI_Build      NA           NA     NA
 2:            Center      NA           NA     NA
 3:           Samples      36           NA     NA
 4:            nGenes    3040           NA     NA
 5:   Frame_Shift_Del      44   1.22222222    1.0
 6:   Frame_Shift_Ins      27   0.75000000    0.0
 7:      In_Frame_Del      15   0.41666667    0.0
 8:      In_Frame_Ins       1   0.02777778    0.0
 9: Missense_Mutation    2690  74.72222222   76.0
10: Nonsense_Mutation     139   3.86111111    3.0
11:  Nonstop_Mutation       4   0.11111111    0.0
12:       Splice_Site      64   1.77777778    2.0
13:             total    2984  82.88888889   85.0
14:               Amp    6198 172.16666667  185.5
15:               Del    3439  95.52777778   99.5
16:         CNV_total    9637 267.69444444  282.0
```
S0 2984 is the total number of non-syn ?

If yes, where are the statistics for total number of mutations?

Thank you so much

**Comment by PoisonAlien** [comment]
Yes they are only for non-syn mutations. You can use `mafSummary` to get the complete summary.

Lot of your questions are `how do I do this?` rather than the bug reports or actual issues. I have put a significant effort in documentation and I would appreciate if you can go through the help pages and list of available functions before asking questions. Thanks!

**Comment by Mussa1122** [comment]
Sorry for that and thank you for helping us.
