### ISSUE TITLE
Getting error in adding var to oncoplot

### ISSUE THREAD

**Issue by Mussa1122** [PoisonAlien/maftools#573]
Hello 

I get this error

```
> aml_genes_vaf = subsetMaf(maf = laml, genes = aml_genes, fields = "T_VAF", mafObj = FALSE)[,mean(T_VAF, na.rm = FALSE), Hugo_Symbol]
Error in gmean(T_VAF, na.rm = FALSE) : 
  Type 'character' not supported by GForce sum (gsum). Either add the prefix base::sum(.) or turn off GForce optimization using options(datatable.optimize=1)
```

**Comment by PoisonAlien** [comment]
Hi,
This error seems to be related to `data.table` rather than `maftools`. Based on the error message I guessing the values in `T_VAF` are not numeric which leads to error in sum estimation. You can try converting to numeric before calling mean function.

```r
> aml_genes_vaf = subsetMaf(maf = laml, genes = aml_genes, fields = "T_VAF", mafObj = FALSE)[,mean(as.numeric(T_VAF), na.rm = FALSE), Hugo_Symbol]
```

**Comment by Mussa1122** [comment]
> Hi,
> This error seems to be related to `data.table` rather than `maftools`. Based on the error message I guessing the values in `T_VAF` are not numeric which leads to error in sum estimation. You can try converting to numeric before calling mean function.
> 
> ```r
> > aml_genes_vaf = subsetMaf(maf = laml, genes = aml_genes, fields = "T_VAF", mafObj = FALSE)[,mean(as.numeric(T_VAF), na.rm = FALSE), Hugo_Symbol]
> ```

Fab

**Comment by Mussa1122** [comment]
I don't have any MutSig data rather I have value for significant genes by dndscv software, therefore, can we add extra q value bar out of MutSig?

**Comment by PoisonAlien** [comment]
You pass any values to `leftBarData` or `rightBarData`.

**Comment by Mussa1122** [comment]
After creating plots, when I want to save them in R, for some of them says `Image is too big` and the annotation in footages of oncoplot be invisible or like the below picture from maf compare x axis is cropped 

![AGCY8](https://user-images.githubusercontent.com/68249398/87937556-dbcb7e00-ca8c-11ea-88a4-6ea8dcc26157.png)

You suggest any personal solution to be able to save images completely?

**Comment by PoisonAlien** [comment]
I have commented out hard-coded margins. You can define your own margins.. 
Please re-install from GitHub.

```r
par(mar = c(10, 3, 2.5, 1.5), cex = 0.8)
tcgaCompare(...)
```

**Comment by PoisonAlien** [comment]
`par` has no effect on `plotMafSummary`. I only changed it for `tcgaCompare`. 
Also, above command works on my system. You can try to restart and check without par.

**Comment by Mussa1122** [comment]
Dear @PoisonAlien 

I have been doing some sanity check on my data

I have data of before and after metatastis separately 

From `getSampleSummary` slot, wilcox.test says total mutation is higher in after metatastis (p-value = 0.03225). I then used `tmb` function which says `total_perMB` is higher after metatastis exactly with a same p-value (does not seem odd to you the same p-value for both test?)

I looked at `pairwise_t_test` from 

`tcgaCompare(maf = c(laml1,laml2),cohortName = c("Before","After"),rm_zero = FALSE,decreasing = TRUE,logscale = TRUE,primarySite = TRUE,col = c("grey30", "red"),medianCol = "black")
`
But this time p-value is 0.97 although again after metatastis have higher mutation

You think why TMB is not the same with `tmb` and `pairwise_t_test` from `tcgaCompare` ?

**Comment by PoisonAlien** [comment]
Hi,
Note that `getSampleSummary` contains raw values and not normalized to per MB whereas, `tmb` normalises.
