### ISSUE TITLE
Hotspot variants visualization issue

### ISSUE THREAD

**Issue by chansbro** [PoisonAlien/maftools#575]
Hello. 

I'm currently working with maftools to visualize IonTorrent NGS data which contains information about hotspot variants we've selected (i.e. ~1,400 variants). 

The problem is whenever I tried to visualize it with oncoplot, the graph looks odd like below.

![1](https://user-images.githubusercontent.com/50089847/88348766-40d2ec80-cd89-11ea-9c53-acd5042cc52e.PNG)

This is a summary of the MAF file.

```{r}
An object of class  MAF 
                   ID summary     Mean Median
 1:        NCBI_Build  GRCh37       NA     NA
 2:            Center       .       NA     NA
 3:           Samples      20       NA     NA
 4:            nGenes      48       NA     NA
 5:   Frame_Shift_Del    1655   91.944   93.0
 6:   Frame_Shift_Ins     625   34.722   33.0
 7:      In_Frame_Del     802   44.556   45.0
 8:      In_Frame_Ins     201   11.167   11.0
 9: Missense_Mutation   14296  794.222  793.0
10: Nonsense_Mutation    1779   98.833   99.0
11:       Splice_Site     663   36.833   37.0
12:             total   20021 1112.278 1109.5
```

So I took a look at each VCF file and found out that VCF data includes 1,400 hotspot variants, even mutation frequency (allele frequency) is zero or less than 1%. 

In addition, VCF files include variants with low total depth (total depth < 500). 

**My question is when visualizing and analyzing MAF data using maftools, is there any way to take out those variants with no mutation frequency?** 

**Is it okay to include all of hotspot variants even with 0 allele frequency or low total depth in the MAF file?**

**Or does maftools recognize all the variants listed in MAF file as detected?**

How can we remove them if we should not include them in MAF file?

Thank you for your help in advance.

**Comment by PoisonAlien** [comment]
Hi,
`maftools` does not do any sort of QC or filtering. You will have to take care of them - such as getting rid of germline events, low read counts, VAF filtering, SNPs, etc. 

Ideally your MAF would contain high confidence somatic calls. 
Take a look at `subsetMaf` function which might be of help to you.
