### ISSUE TITLE
plotmafSummary incomplete

### ISSUE THREAD

**Issue by nickhir** [PoisonAlien/maftools#576]
Hi,
I am working with a large maf file (>500.000 variants and > 30 samples). 
When I try to call  ```plotmafSummary``` the following error occures:

**Error in seq.default(0, max(colSums(gs.dat)) + 2, length.out = 4) : 
  'to' must be a finite number
In addition: Warning message:
In max(colSums(gs.dat)) : no non-missing arguments to max; returning -Inf**

Nonetheless, a part of the summary plot is generated. To be more precise, the "Variant Type" and "SNV Class" and part of the "Variant classification summary".

Weirdly enough, if i try to plot the oncoplot with the same maf file, it works without any issues and produces the desired output.
Any idea what I am doing wrong?

Any help is appreciated.

**Comment by PoisonAlien** [comment]
Hi,
It's hard to guess the issue without a reproducible example. But could you please check if there are any undesired or non numeric values in `getGeneSummary(maf)[1:10, .(Hugo_Symbol, AlteredSamples)]`?

**Comment by nickhir** [comment]
Thanks for the quick response.
I already checked that... everything looks good.
I also tried to delete every variation except ~20 of that maf file, and the error stayed the same.

**Comment by PoisonAlien** [comment]
A reproducible minimal example would be great. 
You can remove any sensitive info, change barcodes, if you prefer.

**Comment by nickhir** [comment]
Link: https://we.tl/t-EcHvbNiPV8

I have included another maf file, which I also processed and which did not cause any issues.

**Comment by PoisonAlien** [comment]
Thanks for the files. They seem ok to me. There were no errors on my system with both the files. 
Could you post your sessioninfo?

**Comment by nickhir** [comment]
Oh, interesting
Btw, this is how the output looks like for me.
![summaryMaf](https://user-images.githubusercontent.com/49643134/88387514-e3539580-cdb2-11ea-8d32-33d242815277.png)

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] optparse_1.6.6  maftools_2.2.10

loaded via a namespace (and not attached):
 [1] compiler_3.6.3     Matrix_1.2-18      tools_3.6.3        RColorBrewer_1.1-2 survival_3.1-8    
 [6] Rcpp_1.0.2         getopt_1.20.3      wordcloud_2.6      splines_3.6.3      grid_3.6.3        
[11] data.table_1.12.6  lattice_0.20-38  
```

**Comment by PoisonAlien** [comment]
It definitely should not look like above if your sample size is >30.  
Its only possible when your sample size and mutation loads are extremely low.

**Comment by nickhir** [comment]
Unfortunately it also looks similar to this when I use the entire maf file.
