### ISSUE TITLE
is the percent  wrong in the sixth picture(last)?

### ISSUE THREAD

**Issue by nordhuang** [PoisonAlien/maftools#577]
**Describe the issue**

Is the percent sorted  in a descending order ?  It do not deplay in a descending order from the up to the botttom in the example from the url (https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html)
 

**Command**
Please post your commands and the output (errors or any unexpected output)

```plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
```

**Session info**
Run `sessionInfo()` and post the output below

```R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] maftools_2.4.05
```

**Comment by nordhuang** [comment]
plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)

**Comment by ShixiangWang** [comment]
It is easy to understand to give a snapshot

![image](https://user-images.githubusercontent.com/25057508/88609813-a1c73100-d0b7-11ea-9ca5-c2fed37c20db.png)

**Comment by PoisonAlien** [comment]
Hi,

Please see the issue #339 for details.
