### ISSUE TITLE
Defining peaks in gisticOncoplot

### ISSUE THREAD

**Issue by Mussa1122** [PoisonAlien/maftools#579]
Hello

`gisticOncoPlot` function is really nice because we can see how many samples have been altered for a given peak

Is this possible to define the peaks we want to visualise ? Nothing like `markBands` argument in `gisticChromPlot`?

Can q value for each peak being added as extra to the plot?

**Comment by Mussa1122** [comment]
I have tried to ignore some bands by `bandsToIgnore` to get what I want to show but whatever I ignore again something is showing

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue. Let me look into it..

**Comment by PoisonAlien** [comment]
Helloe @Mussa1122 ,
Sorry for the delay. I have added `bands` arguments to the function and you should be able to draw your desired peaks. 

```r
gisticOncoPlot(gistic = laml.gistic, bands = c("DP_2:5q31.2", "DP_3:7p12.1", "DP_6:12p13.2", "DP_7:12q21.33", "AP_4:21q22.2"))
```
