### ISSUE TITLE
How to merge multiple maf data into one?

### ISSUE THREAD

**Issue by venkan** [PoisonAlien/maftools#581]
I am downloading multiple datasets from ICGC using `maftools::icgcSimpleMutationToMAF`. I also have TCGA mutational data which was downloaded using `TCGAmutations::tcga_load`. I wanted to merge all the data and then using that for `oncostrip`

```
x = maftools::icgcSimpleMutationToMAF(icgc = "simple_somatic_mutation.open.LICA-CN.tsv.gz", 
                                      addHugoSymbol = TRUE, MAFobj = TRUE)
y = maftools::icgcSimpleMutationToMAF(icgc = "simple_somatic_mutation.open.LINC-JP.tsv.gz", 
                                      addHugoSymbol = TRUE, MAFobj = TRUE)

library(TCGAmutations)
TCGAmutations::tcga_load(study = "LIHC")
getGeneSummary(x = tcga_lihc_mc3)
```

Is there a way to merge the data from ICGC and TCGA cohorts?

**Comment by PoisonAlien** [comment]
Hi,
Try `maftools::merge_mafs()` function.

**Comment by PoisonAlien** [comment]
Btw, please install fro GitHub or use the recent version from Bioconductor (2.4.05 onward) since there was a bug in `merge_maf` which got fixed recently. #538

**Comment by venkan** [comment]
> Btw, please install fro GitHub or use the recent version from Bioconductor (2.4.05 onward) since there was a bug in `merge_maf` which got fixed recently. #538

`maftools::merge_mafs` worked for me in merging ICGC maf data. And I wanted to merge TCGA data also.

```
BiocManager::install("PoisonAlien/TCGAmutations")
library(TCGAmutations)
TCGAmutations::tcga_load(study = "LIHC")
getGeneSummary(x = tcga_lihc_mc3)

Error in getGeneSummary(x = tcga_lihc_mc3) : 
  object 'tcga_lihc_mc3' not found
```

How do I get tcga data and merge that to merged ICGC data?

**Comment by venkan** [comment]
> Hi,
> Try `maftools::merge_mafs()` function.

thank you very much
