### ISSUE TITLE
repel points in lollipopPlot is not working (MafTools)

### ISSUE THREAD

**Issue by snoopy84** [PoisonAlien/maftools#584]
Hey all

I am trying to use repel=T in lollipopPlot() but the output plot does not repel the a.a. labels 

Any solution for this?

Cheers

**Comment by PoisonAlien** [comment]
Hi,
`repel` argument has been deprecated for a while now and no longer supported.

**Comment by snoopy84** [comment]
Cheers

"repel" would be very helpful when the lollipopPlots are too crowded

**Comment by PoisonAlien** [comment]
Agree. Since all of the plots completely implemented using base graphics - I could not find something like `ggrepel` to avoid text collision.
