### ISSUE TITLE
Adjusting gisticChromPlot

### ISSUE THREAD

**Issue by Mussa1122** [PoisonAlien/maftools#585]
Hello

I have this `gisticChromPlot`

![Picture1](https://user-images.githubusercontent.com/68249398/89919672-80a42b80-dbf3-11ea-861a-9fe5905e10ca.png)

As you are considering peak name getting mingled with corresponding peak bar even with the adjacent peak

I tried to play with arguments but no success to make that like peak name is not crossing the bar and become more visible 

Is the any way to do that?

**Comment by PoisonAlien** [comment]
Hi,
If I understand your question correctly, you have trouble with overlapping texts? You could try something below..

```r
par(srt = 45, xpd = TRUE)
gisticChromPlot(laml.gistic)
```

**Comment by Mussa1122** [comment]
Thank you

This indeed helps but can we please plot in a way by which peak name is far from the bar as much as possible?

As you are seeing here, peak name interrupts with bars

![Picture1](https://user-images.githubusercontent.com/68249398/90633029-3affe800-e21d-11ea-9902-b7dc4928364a.png)

**Comment by clersdom** [comment]
Hi @Mussa1122 
Did you manage to increase the space between labels and the bars for the gisticChromPlot?
Thanks!
