### ISSUE TITLE
plotmafSummary 'warning messages'

### ISSUE THREAD

**Issue by amandah-w** [PoisonAlien/maftools#586]
I am using maftools to generate the maf file summary and I am encountering several issues. 
First I wanted to ask what the x-axis of these plots interpret (as I was confused)?
Secondly, I wanted to ask how I could resolve the issues where all my top 10% genes show 100%. (I have attached an image) 

Would it be possible to help me out with this? 

My command was:
`plotmafSummary(maf = maf, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = TRUE)`

However, I receive the following warning message:
`Warning message:
In titv(maf = maf, useSyn = TRUE, plot = FALSE)
Non standard Ti/Tv class: 167TRUE`

![issue](https://user-images.githubusercontent.com/69547924/89956538-4788ad00-dc2d-11ea-85d8-ec37aaa99749.png)

**Comment by PoisonAlien** [comment]
Hi @amandah-w ,
Sorry for the delay. Somehow I overlooked the issue. 

1. X-axis is number of variants summarized by variat type, classification, and TiTv.
2. Something is fishy with your plot. How many samples do you have? Also what do you see in `getGeneSummary` output for your maf?
3. It means there are some variants which can not be classified into any of the 6 Transition/Transversion classes. Could be NAs or anything else. Please do check how these were generated.

**Comment by amandah-w** [comment]
Thank you for your reply @PoisonAlien, 
I have basically converted the vcf files to maf. I have 335 samples I'm working with simultaneously. 
I have observed that I may need to filter out mutations that do not meet the PASS criteria. 
Would it be possible to give guidance on how to filter out variants (including the germline mutations) that do not meet the PASS criteria in the maf files?

**Comment by PoisonAlien** [comment]
I thought so.. Well for starters this is recommended:
1. Get rid of germline variants (those present in control samples)
2. If your maf file has dbSNP annotations, remove those which have AF > 0.01 in general population (you can research more and decide which threshold to use but 0.01 seems to be fine)
3. If you have gnomAD annotations, do the same and get rid of those with AF > 0.01
4. Make sure you retain those variants present in clinivar and annotated in COSMIC
5. You can remove variants with VAF and not supported by good number of reads
