### ISSUE TITLE
MafCompare ForestPlot Argument

### ISSUE THREAD

**Issue by AMLove628** [PoisonAlien/maftools#587]
Dearest Poison Alien-

Sorry to bother again, but I'm trying to do a large MAF comparison and it's too crowded to read. I tried to adjust argument by using:
forestPlot(mafCompareRes = LRIG1Compare, pVal = 0.05, width = 10, height = 12)

However, width, height, and show arguments aren't running, even if I c/p the example script:
as such:
forestPlot(mafCompareRes = LRIG1Compare, pVal = 0.05, show = pVal, color = NULL,  width = 5, height = 6)
It returns: unused arguments (show = pVal, width = 5, height = 6)

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
You seem to be using old version. Could you please update and try again. Also you can save your using`pdf`  or `png` - just like any other plot with base commands.
