### ISSUE TITLE
mafSurvive: Error in data.table::fread(file = maf, sep = "\t", stringsAsFactors = FALSE,  :    File '' does not exist or is non-readable. 

### ISSUE THREAD

**Issue by jdjdj0202** [PoisonAlien/maftools#588]
Hi. I have a problem dealing with mafSurvive function.
I have an error message following:
Error in data.table::fread(file = maf, sep = "\t", stringsAsFactors = FALSE,  :    File '' does not exist or is non-readable. 
When I go to the working directory, there are two files of "tcga_laml.maf.gz" and "tcga_laml_annot.tsv". 
I don't understand why this error pops up. 
Below are the commands I used. 

**Command**
Please post your commands and the output (errors or any unexpected output)

laml.maf=system.file('extdata', 'tcga_laml_maf.gz', package='maftools')
laml.clin=system.file('extdata', 'tcga_laml_annot.tsv', package='maftools')
laml=read.maf(maf=laml.maf, clinicalData=laml.clin)    # <-- The error occurred in here.
mafSurvival(maf=laml, genes="DNMT3A", time="days_to_last_followup", Status="Overall_Survival_Status", isTCGA=TRUE)

**Session info**
> laml.maf=system.file('extdata', 'tcga_laml_maf.gz', package='maftools')
> laml.clin=system.file('extdata', 'tcga_laml_annot.tsv', package='maftools')
> laml=read.maf(maf=laml.maf, clinicalData=laml.clin)
-Reading
Error in data.table::fread(file = maf, sep = "\t", stringsAsFactors = FALSE,  : 
  File '' does not exist or is non-readable. getwd()=='G:/LM20/20 BI'

I am a beginner. I am learning the R and often frustrating errors come. 
I would really appereciate it if you give me some advice. 
Thank you so much.

**Comment by jdjdj0202** [comment]
I am sorry to bother you. I've solved the problem. 
The file name was 'tcga_laml.maf.gz'. 
Thanks.

**Comment by arpit20328** [comment]
@jdjdj0202 How did you solved it ? I have similar problem

**Comment by PoisonAlien** [comment]
Hello @arpit20328 ,
Could you please post your complete command and `sessionInfo`?

**Comment by arpit20328** [comment]
#These two commands ran well
laml.maf <- system.file("extdata", "arpit.maf", package = "maftools")
laml.clin <- system.file("extdata", "clinical.tsv", package = "maftools")

#This command is not running
laml <- read.maf(maf = laml.maf, clinicalData = laml.clin)

#Error in data.table::fread(file = maf, sep = "\t", stringsAsFactors = FALSE,  : 
#File '' does not exist or is non-readable. getwd()=='D:/Downloads/DSG/dsgproject'

**Comment by PoisonAlien** [comment]
Hi,
`system.file()` function is only used to access the example MAF file bundled with the `maftools` package. You do not have to run those commands. In your case, you should provide the absolute path to your MAF file.

e.g.,
```r
my_maf = "D:/Downloads/DSG/dsgproject/my.maf" 

m = read.maf(maf = my_maf)
```

Hope this helps.

**Comment by arpit20328** [comment]
#These two commands ran well
m = read.maf(maf = 'arpit.maf')
n = read.csv('clinical.tsv',  sep ="\t",  row.names =  NULL ,check.names = FALSE, header = TRUE, stringsAsFactors = FALSE )


#This command is not running
laml <- read.maf(maf = m, clinicalData = n)

#Error in file.info(file) : invalid filename argument

**Comment by arpit20328** [comment]
Please help in this regard

**Comment by PoisonAlien** [comment]
Could you please do a `head(m)`? 
It should be a path to the file or a `data.frame`. If it's a file, make sure it exists.

**Comment by arpit20328** [comment]
head(m)
Error in x[seq_len(n)] : object of type 'S4' is not subsettable

**Comment by PoisonAlien** [comment]
It seems like m is already a `MAF` object. 

```r
> class(m)
[1] "MAF"
attr(,"package")
[1] "maftools"
```

If so, then you are all set!

**Comment by arpit20328** [comment]
yes Mm is MAF file , but how do i now proceed with survival analysis ?

**Comment by arpit20328** [comment]
*m

**Comment by PoisonAlien** [comment]
Please refer to the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#94_Survival_analysis) for an example. Also, do check `?mafSurvival` for details. 
It appears you're quite new to R programming. It might take a while for you to figure things out. `GitHub` is mainly intended for bug reports and feature requests. You will have to figure out tool usage on your own..
