### ISSUE TITLE
somaticinteractions - coloring issue

### ISSUE THREAD

**Issue by kzkedzierska** [PoisonAlien/maftools#589]
**Describe the issue**
Investigating both the output of the function `somaticInteractions` and the plot, I find that colour scheme does not match.

![](https://i.ibb.co/72ZzVrQ/maftools.png)

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
> temp <- somaticInteractions(maf = endo, genes = swi_snf$Hugo_symbol)
> temp[pair == "ARID1A, SMARCC1"]
     gene1  gene2      pValue oddsRatio  00 11  01 10        Event
1: SMARCC1 ARID1A 0.001799119  3.161837 339 22 214 11 Co_Occurence
              pair event_ratio
1: ARID1A, SMARCC1      22/225
```

Both objects can be accessed [here (Dropbox link)](https://www.dropbox.com/sh/z9tthkzxrt9og8p/AADYkChkGw1RfST19whRpE-Ka?dl=0). `endo` is a UCEC and UCS subset of TCGA mc3 MAF and `swi_snf` is Table 1 from [this paper](https://www.sciencedirect.com/science/article/pii/S1040842817303815?via%3Dihub#tbl0005).

**Session info**

```r
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.4.05

loaded via a namespace (and not attached):
 [1] lattice_0.20-41    crayon_1.3.4       dplyr_1.0.2        grid_4.0.2        
 [5] R6_2.4.1           nlme_3.1-147       lifecycle_0.2.0    magrittr_1.5      
 [9] pillar_1.4.6       rlang_0.4.7        data.table_1.13.0  Matrix_1.2-18     
[13] ellipsis_0.3.1     vctrs_0.3.2        generics_0.0.2     splines_4.0.2     
[17] RColorBrewer_1.1-2 glue_1.4.1         purrr_0.3.4        survival_3.1-12   
[21] compiler_4.0.2     pkgconfig_2.0.3    tidyselect_1.1.0   tibble_3.0.3      
```

**Comment by PoisonAlien** [comment]
Ah! I see the issue now. This was potentially highlighted in PR #505 but I made it as an optional. Indeed colors are in wrong directions here. Below command draws it correctly. 

```r
temp <- somaticInteractions(maf = endo, genes = siw_snf$Hugo_symbol, limitColorBreaks = TRUE)
```

I will make `limitColorBreaks = TRUE` by default to avoid these conflicts. Thanks for reporting and I apologize for the mistake.

**Comment by kzkedzierska** [comment]
Don't worry, I managed to work this out. In the meantime, I made a similar plot with ggplot2 (also added multiple test correction).

![image](https://user-images.githubusercontent.com/31040515/90634451-9cc15180-e21f-11ea-82de-b0846e25729e.png)

Would you be interested in PR that would take it from base R plotting to ggplot2 or not really? 

I make no promises as it would be my first time contributing to big projects but if you would be interested in that I can give it a go.

**Comment by kzkedzierska** [comment]
Btw. it still colours some of the interactions improperly 
```r
temp <- somaticInteractions(maf = endo, genes = swi_snf$Hugo_symbol, limitColorBreaks = TRUE)
temp %>% filter(pair == "ARID1A, BCL7B")
   gene1  gene2 pValue oddsRatio  00 11  01 10        Event          pair event_ratio
1: BCL7B ARID1A      1  1.113525 346  3 233  4 Co_Occurence ARID1A, BCL7B       3/237
```

![image](https://user-images.githubusercontent.com/31040515/90634778-28d37900-e220-11ea-987f-c86b2fbf6287.png)

**Comment by PoisonAlien** [comment]
Hmm.. Let me have a look and fix this. The way co-occurrences or mut-exclusiveness determined is based on odds rations (>1 co-occurance, <1 mut-exlc).  Here the palette seems to struggle with this. Your ggplot version seems much better. For the PR, I really appreciate the help, but the only reason the plots are not ggplot based because of unwanted dependancies it brings along with it (stringr, plyr, magritr and other tidy-verse). Otherwise I would have been more than happy to accept the PR :|

**Comment by kzkedzierska** [comment]
I think it might struggle as the results are uneven - mostly co-occurrences, with almost no mutual exclusivity...

as for PR, sure, no worries!

**Comment by PoisonAlien** [comment]
Okay, I think I have figured it out. Could you please check it again and let me know?
