### ISSUE TITLE
How to display sample names in coOncoplot?

### ISSUE THREAD

**Issue by raunakms** [PoisonAlien/maftools#59]
If I need to display sample names in coOncoplot, how do I do that? I realize it uses functions from ComplexHeatmap, but no parameter that I could could manually change.

**Comment by raunakms** [comment]
Never mind, I solved the issue myself. In coOncoplot.R, I added the parameter "showTumorSampleBarcodes = TRUE" inside getOncoPlot functions (line #54 and #56). Perhaps this is a parameter to be added in the function.

**Comment by PoisonAlien** [comment]
Hi,
Glad it worked for you. I will add this as an argument to coOncoplot.

**Comment by PoisonAlien** [comment]
I have added two arguments `showSampleNames` and `SampleNamefont` to control sample names and their font sizes in `coOncoplot`. Thanks for the suggestion.

**Comment by aditisk** [comment]
Hi @PoisonAlien, is there a way to use a different set of sample names than the TumorSampleBarcodes in the oncoplots ? I only found the "showTumorSampleBarcodes = TRUE" argument but no way to specify another set of names.

Thanks.

**Comment by PoisonAlien** [comment]
Hi,
Its not possible to change sample names unfortunately. Only way is to change them in your MAF file itself.
