### ISSUE TITLE
Request for a sampleOrder feature in coOncoplot

### ISSUE THREAD

**Issue by chansbro** [PoisonAlien/maftools#592]
Hello. I would like to request a feature of ordering sample in coOncoplot.

Just like in oncoplot sampleOrder, we can check if provided sampleOrder is in each maf data.

Thank you!

**Comment by PoisonAlien** [comment]
Okay, I have added `sampleOrder1` and `sampleOrder2` arguments to `coOncoplot`. Could you please check it and let me know?

```r
#Random samples
m1samps = sample(levels(getSampleSummary(x = primary.apl)[,Tumor_Sample_Barcode]), size = 10)
m2samps = sample(levels(getSampleSummary(x = relapse.apl)[,Tumor_Sample_Barcode]), size = 10)

coOncoplot(
  m1 = primary.apl,
  m2 = relapse.apl,
  removeNonMutated = T,
  showSampleNames = T,
  sampleOrder1 =  m1samps,
  sampleOrder2 =  m2samps
)
```
