### ISSUE TITLE
Additional feature request - Oncoplot axis reverse

### ISSUE THREAD

**Issue by chansnotes** [PoisonAlien/maftools#597]
Hello, many thanks to maftools package maintainer. 

Regarding oncoplot and coOncoplot, would it be possible to add an axis reverse feature?

Right now x-axis represents each patient sample, but I think it would be visually helpful if we can draw the same plot with y-axis to represent each sample.

Thank you!

**Comment by PoisonAlien** [comment]
This would require lots of code change. I am swamped with other work at the moment, so it might take a while to implement it.
