### ISSUE TITLE
somaticInteractions function results vary under maftools version

### ISSUE THREAD

**Issue by sunandinis** [PoisonAlien/maftools#601]
**Describe the issue**
somaticInteractions function when used on same data under two different versions of maftools 2.4.5 and 2.0.16 shows different results. Particularly,  pair of genes which show occurrence under version 2.0.16 are shown to be mutually exclusive under version 2.4.5.

```r
```

**Session info**
Below is the screenshot from version 2.0.16
![Screen Shot 2020-08-30 at 11 17 51 PM](https://user-images.githubusercontent.com/70071661/91682395-07736680-eb17-11ea-9120-1b3f8318ea7b.png)

Below is the screenshot from version 2.4.5
![Screen Shot 2020-08-30 at 11 19 40 PM](https://user-images.githubusercontent.com/70071661/91682457-40134000-eb17-11ea-9a67-e399750283ae.png)
```r
```

**Comment by PoisonAlien** [comment]
Hi,
There was an unfortunate bug which caused some colors to be inverted when depending on the number of events. (See here #589 ) I have fixed it in GitHub version - which should be the correct one. 
Please install from GitHub. Fixed version should appear on Bioconductor soon.

**Comment by PoisonAlien** [comment]
Bioconductor version should work fine as well. I am closing the issue. Please feel free to reopen if necessary.
