### ISSUE TITLE
read.maf , output truncation

### ISSUE THREAD

**Issue by kkanchi10** [PoisonAlien/maftools#606]
Hi, I am trying to read in a maf file with more than 500 samples using read.maf, but my getSampleSummary has only 34 samples . Am I missing any option to read in large maf files?
**Command**
Please post your commands and the output (errors or any unexpected output)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
How did you generate your maf file? Also can you run below commands and check you can actually see all 500+ samples?

```r
maf = data.table::fread(file = "my.maf")
maf[,.N,Tumor_Sample_Barcode]
```

**Comment by kkanchi10** [comment]
Hi, 

Sorry for the delay in response from my end.
when I read the maf file using 
maf_parse = data.table::fread(file = "my.maf")
maf_parse[,.N,Tumor_Sample_Barcode]
I see all the samples listed but when I read the maf using read.maf as below , I am getting the error as below.

> maf_parse_read = read.maf(maf = maf_parse)
-Validating
--Removed 5013 duplicated variants
Error: vector memory exhausted (limit reached?)

**Comment by PoisonAlien** [comment]
Hi,
Do you still see the missing samples issue with `removeDuplicatedVariants = FALSE` in `read.maf`?

**Comment by kkanchi10** [comment]
Hi,
The missing sample issue was resolved, 
Thanks for yourr suggestion.
