### ISSUE TITLE
HELP !!!

### ISSUE THREAD

**Issue by AteeqKhaliq** [PoisonAlien/maftools#61]
Hi,
While running  mutational signatures, i have encountered the following error. I am not able to debug it. Please help me. I am a not tech guy, trying to understand my .maf file.
I am using Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa as my reference file.
It would be of a GREAT HELP if you can help me sorting out this issue.

Error as follows!!!
```
contigs in maf:
 [1] "chr10" "chr12" "chr22" "chr3"  "chr1"  "chr2"  "chr4"  "chr9"  "chr7" 
[10] "chr16" "chr17" "chr19" "chr6"  "chr13" "chr11" "chr20" "chr18" "chr5" 
[19] "chr14" "chr15" "chrX"  "chr8"  "chr21" "chrY" 
missing reference contigs from fasta file.
 [1] "chr10" "chr12" "chr22" "chr3"  "chr1"  "chr2"  "chr4"  "chr9"  "chr7" 
[10] "chr16" "chr17" "chr19" "chr6"  "chr13" "chr11" "chr20" "chr18" "chr5" 
[19] "chr14" "chr15" "chrX"  "chr8"  "chr21" "chrY" 
Contig names in MAF must match to contig names in reference fasta. Ignorinig 29573 single nucleotide variants from chr10, chr12, chr22, chr3, chr1, chr2, chr4, chr9, chr7, chr16, chr17, chr19, chr6, chr13, chr11, chr20, chr18, chr5, chr14, chr15, chrX, chr8, chr21, chrY
Error in trinucleotideMatrix(maf = laml, ref_genome = "/home/ateeqanees/mutation/centos/gr37.fasta",  : 
  Zero mutations to analyze! Maybe add or remove prefix?
```
Thanks a Ton !!!
Zac

**Comment by PoisonAlien** [comment]
Hi,

Can you post your command ?

Also can you check if the chromosome names in input MAF file has 'chr' prefix ?

**Comment by AteeqKhaliq** [comment]
Hi,
Thanks a lot for quick reply,
I am using the following command:
lung.tnm = trinucleotideMatrix(maf = lung, ref_genome = '/GRCh38.dna_sm.primary_assembly.fa', 
                               prefix = 'chr', add = TRUE, ignoreChr = 'chr23', useSyn = TRUE)
I have attached my .maf file, please have a look. It has the following column (first few) 

Hugo_Symbol | Entrez_Gene_Id | Center | NCBI_Build | Chromosome
-- | -- | -- | -- | --
ANKRD23 | 200539 | bcgsc.ca | GRCh37-lite | 2
HOXD8 | 3234 | bcgsc.ca | GRCh37-lite | 2
CASP8 | 841 | bcgsc.ca | GRCh37-lite | 2

Please help me out, my knowledge in this is very limited.

Thanks a lot,
Zac





[lung.zip](https://github.com/PoisonAlien/maftools/files/1272727/lung.zip)

**Comment by PoisonAlien** [comment]
Hi,
No problem! 
Anyways, its working fine for me.  You should note that,
*  your input MAF file uses GRCH37 (aka hg19) as reference genome but you're providing GRCh38 (`ref_genome = '/GRCh38.dna_sm.primary_assembly.fa'`) as `ref_genome`.  
* Chromosome names in MAF file have no `chr` prefix, you should add one - which you already did. But make sure chromosome names in your reference genome also has `chr` prefix - in any case maftools will give an error/warnings if there is mismatch in the way chromsomes are named among input maf and reference genome file.

```r
>lung = read.maf(maf = '~/Downloads/lung')

> lung
An object of class  MAF 
                        ID     summary    Mean Median
 1:             NCBI_Build GRCh37-lite      NA     NA
 2:                 Center    bcgsc.ca      NA     NA
 3:                Samples          96      NA     NA
 4:                 nGenes        7607      NA     NA
 5:        Frame_Shift_Del         277   2.885    2.0
 6:        Frame_Shift_Ins         173   1.802    1.0
 7:           In_Frame_Del          79   0.823    0.0
 8:      Missense_Mutation       11568 120.500  106.0
 9:            Splice_Site         322   3.354    3.0
10: Translation_Start_Site          25   0.260    0.0
11:                  total       12444 129.625  114.5

> lung.tnm = trinucleotideMatrix(maf = lung, ref_genome = '~/NGS/ref_genomes/hg19.fa', prefix = 'chr', add = TRUE, useSyn = TRUE)
reading ~/NGS/ref_genomes/hg19.fa (this might take few minutes)..
contigs in fasta file:
 [1] "chr1"  "chr2"  "chr3"  "chr4"  "chr5"  "chr6"  "chr7"  "chr8"  "chr9"  "chr10" "chr11" "chr12" "chr13" "chr14" "chr15" "chr16" "chr17" "chr18" "chr19" "chr20" "chr21" "chr22"
[23] "chrX"  "chrY"  "chrM" 
contigs in maf:
 [1] "chr1"          "chr2"          "chr3"          "chr5"          "chr6"          "chr7"          "chr8"          "chr9"          "chr10"         "chr11"         "chr12"        
[12] "chr13"         "chr14"         "chr16"         "chr17"         "chr18"         "chr19"         "chr20"         "chr22"         "chrX"          "chr4"          "chr15"        
[23] "chrMT"         "chr21"         "chrGL000209.1" "chrGL000219.1" "chrY"          "chrGL000205.1" "chrGL000212.1" "chrGL000218.1" "chrGL000192.1" "chrGL000241.1" "chrGL000229.1"
missing reference contigs from fasta file.
[1] "chrMT"         "chrGL000209.1" "chrGL000219.1" "chrGL000205.1" "chrGL000212.1" "chrGL000218.1" "chrGL000192.1" "chrGL000241.1" "chrGL000229.1"
Contig names in MAF must match to contig names in reference fasta. Ignorinig 54 single nucleotide variants from chrMT, chrGL000209.1, chrGL000219.1, chrGL000205.1, chrGL000212.1, chrGL000218.1, chrGL000192.1, chrGL000241.1, chrGL000229.1
Extracting 5' and 3' adjacent bases..
Extracting +/- 20bp around mutated bases for background estimation..
Estimating APOBEC enrichment scores.. 
Performing one-way Fisher's test for APOBEC enrichment..
APOBEC related mutations are enriched in 25% of samples (APOBEC enrichment score > 2 ; 24 of 96 samples)
Creating mutation matrix..
matrix of dimension 96x96
```

Let me know if you still have issues.

**Comment by AteeqKhaliq** [comment]
Thanks a lot for this help, i will download the GRCH37 and work on it :) thanks a lot, its of great help for me !!! it means a lot...
Thanks again ,
Zac..

**Comment by PoisonAlien** [comment]
No problem at all. 
Just a heads up,

If you're using maftools from Bioconductor, there is a major bug in `trinucleotideMatrix` function. This has been fixed in github repository, maybe you should install it from github and try..

```
library("devtools")
install_github(repo = "PoisonAlien/maftools")
```

**Comment by AteeqKhaliq** [comment]
HI,
Thanks a lot for your help, i have successfully executed the program and got some very good results. 
Meanwhile, i am not able to save the matrix into .csv file. how can i save the 'laml.sign' into a .csv file for my future reference? I tried using the following code but its throws error.

> write.csv(laml.sign, file = "ESCA_signature.csv",row.names=FALSE, na="")
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class "structure("NMFfit", package = "NMF")" to a data.frame

Thanks a lot for your kind help,
Have a great day ahead !!!
Zac

**Comment by PoisonAlien** [comment]
Hi,
Sorry for late reply. `laml.sign` is a list. So it contains,
* scaled signatures
* contribution of each signatures to each sample
* cosine similariry matrix of identified signatures against all (30) validated signatures from Sanger.
* NMF object

you can see by `names(laml.sign)` 
You can access each element either by `laml.sign[[1]]` or laml.sign$

If you want to write to output file,
```r
write.delim(laml.sign$signatures, file = "ESCA_signature.csv", row.names = TRUE, quote = FALSE)
```

**Comment by AteeqKhaliq** [comment]
Hi, 
Thanks a lot for your kind help! it indeed helped me so much. Thanks again !
I have one last query to make, Is it possible to get all 30 genes signature? currently i am getting only 2 or 3 depending on the best p value(extractSignatures), can i get all detected signatures from my .maf against validated signatures?
I need to have all detected signatures against validated one, can we extract this from maftools? please let me know how this to be done.
Thanks a Ton, your help is indeed invaluable, highly appreciated. 
Have a great day ahead,
Zac.

**Comment by PoisonAlien** [comment]
Hi,
sorry for late reply. 

In short, No you can't detect all 30 signatures. maftools detects de-novo signatures and compares them to validated signatures for best match. 
Also see here #62
