### ISSUE TITLE
Making genes italic

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#611]
Hello

Is it possible to make genes italic in `coBarplot`?

[Rplot05.pdf](https://github.com/PoisonAlien/maftools/files/5218351/Rplot05.pdf)

**Comment by PoisonAlien** [comment]
It is not possible. Also there is a bug `coBarplot` which struggles with CN events. I will fix it by the end if the day.. You can see it in your plot as well (as white segments). #609

**Comment by PoisonAlien** [comment]
Btw, I have fixed the blank issue #609. I also noticed that gene names are already in italics, what version are you using?

**Comment by beginner984** [comment]
Thank you

This is the version 

```
> library(maftools)
Warning message:
package ‘maftools’ was built under R version 4.0.2 
> 
```

**Comment by PoisonAlien** [comment]
You have to post the version of `maftools`. 
Anyways install again from GitHub for the fixed version.
