### ISSUE TITLE
vector memory exhausted (limit reached?)

### ISSUE THREAD

**Issue by kkanchi10** [PoisonAlien/maftools#613]
Hi,

when I read the maf file using
maf_parse = data.table::fread(file = "my.maf")
maf_parse[,.N,Tumor_Sample_Barcode]
I see all the samples listed but when I read the maf using read.maf as below , I am getting the error as below.

    maf_parse_read = read.maf(maf = maf_parse)
    -Validating
    --Removed 5013 duplicated variants
    Error: vector memory exhausted (limit reached?)

**Comment by ShixiangWang** [comment]
Try this? https://stackoverflow.com/questions/51295402/r-on-macos-error-vector-memory-exhausted-limit-reached

![image](https://user-images.githubusercontent.com/25057508/93285053-94e8d300-f806-11ea-9c01-36e71453da33.png)

**Comment by kkanchi10** [comment]
yes, clearing the large unused files and increasing the R_MAX_VSIZE solved the problem. Now I am able to read the file. Thanks for your help

**Comment by PoisonAlien** [comment]
Glad you could work this out. I am closing this issue. I will answer the rest on your older issue.
