### ISSUE TITLE
The difference between lollipopPlot and lollipopPlot2

### ISSUE THREAD

**Issue by paulhtyang** [PoisonAlien/maftools#614]
To Whom IT May concern,

Please see the two plots generated by two functions, lollipopPlot and lollipopPlot2 respectively.
![image](https://user-images.githubusercontent.com/37505714/93355372-fd867e80-f80b-11ea-8791-b910fe33477f.png)
![image](https://user-images.githubusercontent.com/37505714/93355398-05462300-f80c-11ea-9f04-4f4395acc5eb.png)
The second plot looks like a repeat labeling in the protein domains. This might be a bug in the function of lollipopPlot2.
Thanks,
Paul

**Comment by PoisonAlien** [comment]
Indeed it was. Thanks for pointing. I have fixed it. You will have to re-install from GitHub for the patched version.

**Comment by paulhtyang** [comment]
Thanks for your prompt reply.
I forgot to point out the somatic mutation rate (25% vs. 27.27%) labeled in
these two figures. Please feel free to let me our thoughts about this issue.
Thanks,

*Hsih-Te (Paul) Yang, PhD*

*Sr. Oncology Bioinformatician*

*Levine Cancer Institute, Atrium Health*

https://www.mendeley.com/profiles/hsih-te-yang/

**Comment by PoisonAlien** [comment]
Hi,
It looks like they are not the same cohorts in the plots. Could you please double check?
I tried the functions on several tcga cohorts and could not reproduce your discrepancies.

**Comment by paulhtyang** [comment]
Hello Anand,

Thanks for your effort on this matter. Yes, you are completely correct. I
found the wrong input MAF object in the plot function.
Sorry about that.
All the best,
Paul

**Comment by PoisonAlien** [comment]
No worries. Thanks again for the contribution.
