### ISSUE TITLE
Lollipop Plot "structure for protein "-----" not found"

### ISSUE THREAD

**Issue by whitejaa** [PoisonAlien/maftools#616]
Good Day,

**I am running the following command:**
```r
lollipopPlot(maf = Three_outOF_five_FuncAnnos_COSMIC.maf, 
gene = 'SIMC1', 
AACol = 'HGVSp', 
showMutationRate = TRUE, 
labelPos = 'all')

Error in lollipopPlot(maf = Three_outOF_five_FuncAnnos_COSMIC.maf, gene = "SIMC1",  : 
  Structure for protein SIMC1 not found.
```

I have successfully generated numerous lollipop plots without error but gene SIMC1 returns an error. How can I correct this error? Thanks!

**Comment by whitejaa** [comment]
Looking through the function code, I see that "protein_domains.RDs" is used as the reference to build the protein models. How can I modify this file to contain the data for SIMC1? Thanks!

**Comment by PoisonAlien** [comment]
Hi,
If you can provide the link to protein structure of SIMC1, I will update the database.

**Comment by whitejaa** [comment]
Thanks for the quick assist!

C5orf25 is an alias of SIMC1, so I am providing 2 links...
**One for SIMC1:**
https://www.uniprot.org/uniprot/Q8NDZ2
**and one for C5orf25:**
https://www.proteomicsdb.org/proteomicsdb/#protein/proteinDetails/73096/summary

Proteomicsdb actually shows the structure but I am note if that is all you need. Thanks again!

**Comment by PoisonAlien** [comment]
It weird that this protein has no domains. I also checked this in cBioPortal and it seems to be the case.
Can you confirm? I will go ahead and add it to the db,,

**Comment by Mussa1122** [comment]
Sorry @PoisonAlien, for lollipop plot, what is the matched column in maf object with **Protein_Change** column in cBioPortal website?

https://www.cbioportal.org/mutation_mapper

**Comment by PoisonAlien** [comment]
@Mussa1122 This is the column containing protein alteration information. It has no standard name in the maf object and depends on the annotation tool. You will have to check it.

**Comment by PoisonAlien** [comment]
Hello @whitejaa ,
I have added `SIMC1` structure to the database. Please install from GutHub for patched version.

**Comment by whitejaa** [comment]
Thanks for the quick help! I will try it again.

**Comment by beginner984** [comment]
Hello @PoisonAlien  

Is the anyway to add protein name to the lollipop plot? I have done that manually but does not seem so good

<img width="530" alt="Screenshot 2020-10-19 at 10 24 25" src="https://user-images.githubusercontent.com/43682980/96426629-65f2c200-11f5-11eb-92ae-c58e1316422b.png">

**Comment by PoisonAlien** [comment]
Hi, 
Protein names along with refseq IDs are always shown in the lollipop plot as headers.

**Comment by beginner984** [comment]
Sorry you meats like this?

```
> lollipopPlot(
+     maf2,
+     gene = "PBRM1",
+     AACol = "aaChange",
+     labelPos = NULL,
+     labPosSize = 0.9,
+     showMutationRate = TRUE,
+     showDomainLabel = TRUE,
+     cBioPortal = FALSE,
+     refSeqID = "c.C2761T")
Error in lollipopPlot(p2, gene = "KCNQ3", AACol = "aaChange", labelPos = NULL,  : 
  c.C2761T not found!
> 
```

**Comment by PoisonAlien** [comment]
They are the headers. Please see `?lollipopPlot` and vignette for details.

<img width="591" alt="Screenshot 2020-10-19 at 1 08 51 PM" src="https://user-images.githubusercontent.com/8164062/96443113-63e82d80-120c-11eb-9b70-27c1992a5e4e.png">

**Comment by beginner984** [comment]
Sorry I mean something like this picture 
![nihms474888f3](https://user-images.githubusercontent.com/43682980/96446162-f4bd0a00-1208-11eb-9b7a-f81adc8b65e9.jpg)

**Comment by PoisonAlien** [comment]
Okay! Based on all your comments and issues opened, it seems you have very specific needs. `maftools` can only generate standard figures. Also, its hard to implement something that would satisfy everyone's custom needs. I can not help you with these tiny details, you will have to do these yourself. Maybe edit them illustrator..

**Comment by beginner984** [comment]
You are certainly right. Thank you for all your sincere helps. I thought maybe there is an argument to connect protein to the mutation but now realised I should do that manually.

**Comment by thscandolara** [comment]
Hello @PoisonAlien! 
I would like to report that PALB2 has a problem as well. 

Here is the code
```

> lollipopPlot(
+   maf = maf,
+   gene = 'PALB2',
+   AACol = 'Protein_Change',
+   showMutationRate = TRUE,
+   labelPos = 882
+ )
Error in lollipopPlot(maf = maf, gene = "PALB2", AACol = "Protein_Change",  : 
  Structure for protein PALB2 not found.
> 
```

I already tried running the code using refseqID as well as proteinID, however none of them works.
Do you have a solution? 
Thank you!

**Comment by PoisonAlien** [comment]
Hi @thscandolara 

I have updated the database. Please reinstall the package from GitHub for the changes.

**Comment by thscandolara** [comment]
Thank you @PoisonAlien! =)

**Comment by thscandolara** [comment]
@PoisonAlien I got this error while trying to reinstall the package:

Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.2 (2021-11-01)
Installing github package(s) 'PoisonAlien/maftools'
Error: Failed to install 'maftools' from GitHub:
  cannot open URL 'https://api.github.com/repos/PoisonAlien/maftools/commits/HEAD'
