### ISSUE TITLE
addReadCounts bam-readcount wrapper 

### ISSUE THREAD

**Issue by andreabc** [PoisonAlien/maftools#617]
Hi, I came across the addReadCounts function in an older maftools version (https://www.rdocumentation.org/packages/maftools/versions/0.99.30/topics/addReadCounts) I was wondering why it's not also in the latest package? Thank you!

**Comment by PoisonAlien** [comment]
Hi,
It was removed due Bioconductor package restrictions. `addReadCounts` uses a `system` command to execute `bam-readcounts`. Bioconductor unfortunately does not allow system commands to be used in packages. Hence it has to be dropped. 
Try [basecounts](https://github.com/PoisonAlien/basecounts) if are interested in extracting depth info..

**Comment by andreabc** [comment]
Awesome, thanks!
