### ISSUE TITLE
get the file of G-scores of cytoband

### ISSUE THREAD

**Issue by DrZhaoJie** [PoisonAlien/maftools#618]
Hello!
      I really enjoy your package!  I'd like to ask some questions. 

```r
gisticChromPlot(gistic = laml.gistic, markBands = "all")
```   
present the G-scores of cytoband. I'd like to know how can I get the specific value, in other words, text file of G-scores of cytoband. Thank you very much!

**Comment by PoisonAlien** [comment]
Hello,
They are parsed from `scores.gistic` file generated by GISTIC itself.

**Comment by DrZhaoJie** [comment]
Hello,
Thank you very much.
I looked at the scores.gistic file as follows, which provided only the G-scores of region on chromosome based on the start and end position.
![image](https://user-images.githubusercontent.com/55881098/94383026-702f1c80-0171-11eb-8ef5-eafebfbd35cc.png)
I tried to comment the cytoband with the start and end position of chromosome with the cytoband.txt file as follows, which seemed not matching and it didn't work.
![image](https://user-images.githubusercontent.com/55881098/94383139-c0a67a00-0171-11eb-8214-3fd9744843e0.png)
So, I'd like to know how can I get the specific value of G-scores of cytoband, which was visualized by 
gisticChromPlot(gistic = laml.gistic, markBands = "all")
Thank you very much!

**Comment by PoisonAlien** [comment]
Hi ,
gistic scores are not calculated for cytobands. Cytobands are highlighted based on the regions estimated as significant by GISTIC itself. You can check them with `getCytobandSummary()`.

**Comment by DrZhaoJie** [comment]
Hi,
I know that gisticBubblePlot(gistic = laml.gistic), this picture was the visualization of the results of getCytobandSummary().
![image](https://user-images.githubusercontent.com/55881098/94553241-ce035780-028a-11eb-88e1-52d8344a3762.png)
"gistic scores are not calculated for cytobands". Then, what did the G-scores  and the highlighted cytoband in this picture mean? How may I understand this picture? Thank you very much.!

![Uploading image.png…]()

**Comment by PoisonAlien** [comment]
Hi,
I would suggest you to read the documentation of GISTIC output files as it makes things clearer. [Here](https://software.broadinstitute.org/software/igv/GISTIC) you will find brief note about `scores.gistic` file. It contains scores for genomic segments along with amp/del status and significance values. I am just plotting these scores along the chromosome lengths. Segments are annotated with cytoband labels which is also outputted by gistic (but are stored in `all_lesions.conf_xx.txt`).  Hope this helps.

**Comment by DrZhaoJie** [comment]
Hi,
Thank you very much. I got it! Yeah, I'd like to annotate the segments with cytoband labels. But honestly, I didn't make it by match all_lesions.conf_99.txt and scores.gistic file for LUSC [cancer.

[LUSC.zip](https://github.com/PoisonAlien/maftools/files/5309416/LUSC.zip)

**Comment by Mussa1122** [comment]
Hello @PoisonAlien 

I have GISTIC results for a specific gene

Oncoplot says genes has amplification in 9 samples

![Rplot](https://user-images.githubusercontent.com/68249398/94875220-0ef69a00-044c-11eb-996c-7934a56d74d5.png)

I firstly checked `all_thresholded.by_genes.txt` file but `FZD1` is 


`FZD1	8321	7q21.13	0	0	-1	0	0	1	0	0	0	2	-1	0	0	-1	0	0	0	0	0	1	0	0	0	2	-1	-1	0`

Amplified in `4 samples (positive)` and  deleted in `5 samples (negative)`

I then looked at `all_lesions.conf_95.txt` file and searched for `7q21.13` but I did not find that instead I found `9 samples `amplified in `7q21` as oncoplot shows like

`Amplification Peak  6	7q21.2 	chr7:88050002-93790000(probes 135958:136551)  	chr7:91314039-92811010(probes 136298:136456)  	chr7:91314039-92840000(probes 136298:136459)  	0.020799	0.020799		0: t<1; 1: 1<t< 0.9; 2: t>0.9	0	0	0	0	0	2	0	2	0	2	0	0	1	0	0	0	0	1	0	2	0	2	2	2	0	0	0`


My question to you, please, is how in oncoplot we have 9 amplified samples but actual copy number of 5 samples is negative (deletion)?

Please can you help me in getting this?

Thank you

**Comment by PoisonAlien** [comment]
There seems to be something wrong with the plot. Top and side bar plots are not aligned to the main plot. Could you please post your complete command? Or share your data if possible?

**Comment by Mussa1122** [comment]
Thank you so much

I have attached the full GISTIC output folder, mutation maf file matched with GISTIC samples

https://www.dropbox.com/s/n8bg2ocphqohyob/Full_GISTIC.zip?dl=0

https://www.dropbox.com/s/vdfusblm9nydf53/Full_maf.rds?dl=0

This is the command I used to merge GISTIC with mutations

```
all.lesions =
  system.file("extdata", "all_lesions.conf_95.txt", package = "maftools")
amp.genes =
  system.file("extdata", "amp_genes.conf_95.txt", package = "maftools")
del.genes =
  system.file("extdata", "del_genes.conf_95.txt", package = "maftools")
scores.gis =
  system.file("extdata", "scores.gistic", package = "maftools")

#Read GISTIC results along with MAF
laml.plus.gistic = read.maf(
  maf = Full_maf,
  gisticAllLesionsFile = all.lesions,
  gisticAmpGenesFile = amp.genes,
  gisticDelGenesFile = del.genes,
  gisticScoresFile = scores.gis,
  isTCGA = FALSE,
  verbose = FALSE, 
  clinicalData = NULL
)
> oncoplot(laml.plus.gistic,genes = c("APC","CHD4","DKK2","FZD1","LZTR1","RNF43","TCF7L1
+ ","WNT1","WNT4","WNT5A","WNT5B"))
> 

```

Actually all I was trying to have a count matrix of copy number altered genes for which as you thought us by this we can get the count matrix for mutations

`maftools::mutCountMatrix(maf = laml)`

If I want for copy number I should subtract (keeping the same genes order and samples)

 `maftools::mutCountMatrix(maf = laml.plus.gistic)` **-**  `maftools::mutCountMatrix(maf = laml)`

I done that and got confusion as posted here

**Comment by Mussa1122** [comment]
Sorry @PoisonAlien  did you please detect where I am doing something wrong to get this?

**Comment by PoisonAlien** [comment]
I'm traveling and will be back on Monday. I'll get back to you then.

**Comment by PoisonAlien** [comment]
Hi,
The file `all_thresholded.by_genes.txt` is never used in importing results. Only the results from `ampGenes`, `delGenes` and `all_lesions` are used for figuring out which genes are amplified or deleted. As you see in the all_lesions results, amplification peak `7q21.2` is amplified in 9 samples and this regions contains FZD1 gene (7 deep amplified and 2 shallow). These are the same results which are plotted in oncoplot. 

```r
                            cytoband          variable value
1: Amp_7q21.2_chr7:88050002-93790000 LP6008336-DNA_H01     2
2: Amp_7q21.2_chr7:88050002-93790000 LP6005334-DNA_H01     2
3: Amp_7q21.2_chr7:88050002-93790000 LP6008460-DNA_D01     2
4: Amp_7q21.2_chr7:88050002-93790000 LP6005500-DNA_D03     1
5: Amp_7q21.2_chr7:88050002-93790000               s18     1
6: Amp_7q21.2_chr7:88050002-93790000               s30     2
7: Amp_7q21.2_chr7:88050002-93790000               s67     2
8: Amp_7q21.2_chr7:88050002-93790000               s80     2
9: Amp_7q21.2_chr7:88050002-93790000               s86     2
``` 

I can not comment on the `all_thresholded` files. Maybe ask for help on GISTIC forum, maybe they will be able to clarify things.

**Comment by DrZhaoJie** [comment]
Hi, how can I annotate the segments in the scores.gistic file with cytoband labels? Thank you very much!

**Comment by beginner984** [comment]
Thank you @PoisonAlien very helpful

If I want count matrix of copy number changes, can I use this approach?
(keeping the same genes order and samples)

`maftools::mutCountMatrix(maf = laml.plus.gistic) - maftools::mutCountMatrix(maf = laml)`

**Comment by PoisonAlien** [comment]
@DrZhaoJie Please use the argument `markBands` to label cytobands. Check the output from `getCytobandSummary` to get the list the `Cytoband` that can be named with `gisticChromPlot`. 

@beginner984 Use `mutCountMatrix` with argument `countOnly = 'Amp'` to get counts of amplifications.  `?mutCountMatrix` for details.

**Comment by DrZhaoJie** [comment]
@PoisonAlien Yeah! Thank you! The G-scores of the region with start and end position of chromosome were available in scores.gistic file. But how can I get the G-scores value of the cytoband corresponding with the region?

**Comment by PoisonAlien** [comment]
Hi,
No its not possible. They are not summarised for each cytoband. They are estimated for genomic segments.

**Comment by beginner984** [comment]
Hello @PoisonAlien and thank you

When for a fixed list of genes, I check the number of genes coming out from

`maftools::mutCountMatrix(maf = laml.plus.gistic) - maftools::mutCountMatrix(maf = laml)
`
and 

```
mutCountMatrix(
  laml.plus.gistic,
  includeSyn = FALSE,
  countOnly ="Amp",
  removeNonMutated = TRUE
)

```
I noticed a dramatic reduction of genes coming out from the first approach to `mutCountMatrix`

I checked one gene and I noticed the results (1,0) for both approaches is the same but only the number of genes reduced

Does it because `mutCountMatrix` only take recurrently amplified and deleted genes into account or the first approach is totally wrong?

**Comment by PoisonAlien** [comment]
Do not use the first approach.

**Comment by DrZhaoJie** [comment]
@PoisonAlien  All right. Thank you very much.

**Comment by beginner984** [comment]
Hello @PoisonAlien 

I had asked the author of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5957269/ about how she obtained GISTIC score for a list of genes because she mentioned this in the paper

`copy number amplifications (defined as GISTIC score ≥2) and blue indicates homozygous deletions (GISTIC score ≤-2)`

And she replied me like this

`you need to identify the copy number of the regions these genes lie in. It’s been a long time since I worked with GISTIC scores so I don’t remember the details exactly. But if I recall correctly the all_lesions.conf_95.txt file contains GISTIC scores per region. If so, then you need to intersect these regions with the coordinates of your genes of interest (you can use the GenomicRanges package to do that). That will then give you the GISTIC score per gene. Sometimes you have one gene overlapping multiple regions with different scores. In that case, I just take the average of the scores.`

Is it the same maftools is doing?

**Comment by PoisonAlien** [comment]
Hi,
It is not doing any such thing. amp/del genes are parsed from `amp_genes`  and `del_genes` files. 
`scores .gistic` is only used for plotting.

**Comment by beginner984** [comment]
Hello

I think I am seeing something wrong with oncoplot

In this plot we are seeing deletion in SMAD4

But SMAD4 is not neither in **del_genes.conf_95.txt** nor the residing peak is in **all_lesions.conf_95.txt** 

![Rplot02](https://user-images.githubusercontent.com/43682980/96053850-487dcb00-0e78-11eb-864e-8ff078d0290e.png)

oncoplot(laml.plus.gistic,genes = c("SMAD4","RPL22"))

This is my whole maf here
https://www.dropbox.com/s/naxsi2fyks9oot5/laml.plus.gistic.rds?dl=0
Please you may have a look to see what is happening

**Comment by PoisonAlien** [comment]
It is not a CN deletion. Its a `Frame_Shift_Del`. 
CN deletions are in smaller rectangles where as point mutations and INDELS are in large rectangles.

**Comment by Mussa1122** [comment]
Sorry @PoisonAlien from this function

```
mutCountMatrix(
  laml.plus.gistic,
  includeSyn = FALSE,
  countOnly ="Amp",
  removeNonMutated = TRUE
)
```

Is it possible to separate gain and loss? This is an important distinction and I think I should not just bundle everything together in getting a matrix of boolean values for copy number altered samples

Is it possible at all?

I tried both `countOnly ="Amp"` and `countOnly ="Del" `but the results was the same

**Comment by PoisonAlien** [comment]
Hello,
Could you please provide an example where you find both the results are the same? I couldn't reproduce your issue.

```r
#maf file
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
#clinical information containing survival information and histology. This is optional
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')

all.lesions =
    system.file("extdata", "all_lesions.conf_99.txt", package = "maftools")
amp.genes =
    system.file("extdata", "amp_genes.conf_99.txt", package = "maftools")
del.genes =
    system.file("extdata", "del_genes.conf_99.txt", package = "maftools")
scores.gis =
    system.file("extdata", "scores.gistic", package = "maftools")

#Read GISTIC results along with MAF
laml.plus.gistic = read.maf(
    maf = laml.maf,
    gisticAllLesionsFile = all.lesions,
    gisticAmpGenesFile = amp.genes,
    gisticDelGenesFile = del.genes,
    gisticScoresFile = scores.gis,
    isTCGA = TRUE,
    verbose = FALSE, 
    clinicalData = laml.clin
)


ampcounts = maftools::mutCountMatrix(maf = laml.plus.gistic, countOnly = "Amp")
delcounts = maftools::mutCountMatrix(maf = laml.plus.gistic, countOnly = "Del")

#They are not the same results
>identical(x = ampcounts, y = delcounts)
FALSE

#TP53 is deleted in AML and should only be in `delcounts`
> "TP53" %in% rownames(ampcounts) 
FALSE

> "TP53" %in% rownames(delcounts) 
TRUE
```

**Comment by Mussa1122** [comment]
Sorry you alright 

My mistake

<img width="1280" alt="Screenshot 2020-11-06 at 11 47 45" src="https://user-images.githubusercontent.com/68249398/98362895-ee5ec880-2025-11eb-9b00-3ebfc15851bf.png">

So

```
ampcounts = maftools::mutCountMatrix(maf = laml.plus.gistic, countOnly = "Amp")
delcounts = maftools::mutCountMatrix(maf = laml.plus.gistic, countOnly = "Del")
```

Gives boolean values for amplified/deleted genes. What I should put in the function if I need count matrix for all non-synonymous mutations?

Thank you

**Comment by PoisonAlien** [comment]
Hi,
once again, please read the help page. It is **NOT** a boolean matrix.  It is a count matrix. 

```
Generates a count matrix of mutations. i.e, the number of mutations per gene per sample.
```
If you want the count matrix of all non-syn mutations, do not use the argument `countOnly`.

**Comment by DrZhaoJie** [comment]
Hi,
Sorry to ask the question again. The number of mutations per gene per sample can be more than 1? Shouldn't the mutation of  one gene be yes or not? In other words, boolean.


> Hi,
> once again, please read the help page. It is **NOT** a boolean matrix. It is a count matrix.
> 
> ```
> Generates a count matrix of mutations. i.e, the number of mutations per gene per sample.
> ```
> 
> If you want the count matrix of all non-syn mutations, do not use the argument `countOnly`.

**Comment by DrZhaoJie** [comment]
> Hello @PoisonAlien
> 
> I had asked the author of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5957269/ about how she obtained GISTIC score for a list of genes because she mentioned this in the paper
> 
> `copy number amplifications (defined as GISTIC score ≥2) and blue indicates homozygous deletions (GISTIC score ≤-2)`
> 
> And she replied me like this
> 
> `you need to identify the copy number of the regions these genes lie in. It’s been a long time since I worked with GISTIC scores so I don’t remember the details exactly. But if I recall correctly the all_lesions.conf_95.txt file contains GISTIC scores per region. If so, then you need to intersect these regions with the coordinates of your genes of interest (you can use the GenomicRanges package to do that). That will then give you the GISTIC score per gene. Sometimes you have one gene overlapping multiple regions with different scores. In that case, I just take the average of the scores.`
> 
> Is it the same maftools is doing?
> 
> If so, I guess the output of
> 
> ```
> mutCountMatrix(
>   laml.plus.gistic,
>   includeSyn = FALSE,
>   countOnly ="Amp",
>   removeNonMutated = TRUE
> )
> ```
> 
> is GISTIC scores?

Hi, you may want to get CNV values per gene per sample? I agree with the answer you got from the anthor.
In my view, merge the laml.gistic@numericMatrix and laml.gistic@data by cytoband column may be a more convenient way to get the CNV values per gene per sample. Duplications of genes may be given an average value. 
If I got wrong, please let me know. Thank you!

**Comment by DrZhaoJie** [comment]
Hi,
`laml.gistic@numericMatrix` presented the CNV numeric matrix of cytobands. How can I get the the CNV numeric matrix of genes like that? Thank you very much!

**Comment by DrZhaoJie** [comment]
@beginner984 @Mussa1122   @mtmorgan @PoisonAlien 
 Hi,
laml.gistic@numericMatrix presented the CNV numeric matrix of cytobands. How can I get the the CNV numeric matrix of genes like that? Thank you very much!

**Comment by PoisonAlien** [comment]
a. Yes, a sample can have multiple mutations in the same gene. They are usually annotated as `Multi_Hit` in the oncoplot. You can take the output from `mutCountMatrix` and replace all the values >0 with 1 to get a boolean matrix. 

b. Unfortunately there is no straightforward way to do this :|

**Comment by DrZhaoJie** [comment]
Hi.
    Thank you for your reply. As to the second question. I tried some ways. It was possible to do that.
As you gave ` laml.gistic@gene.summary`, it gave the column "altered samples". Maybe you did it by annotating the genes on the cytoband with "all_lesions.conf_99.txt", "amp_genes.conf_99.txt", "del_genes.conf_99.txt", right? So, you have `laml.gistic@numericMatrix` and "amp_genes.conf_99.txt", "del_genes.conf_99.txt", annotating the gens on the cytoband can produce laml.gistic@geneMatrix. But there was one problem. One gene can be annotated to multiple cytobands. How did you deal with that to give  ` laml.gistic@gene.summary`? Could you please try it? Or share your code on the gene annotation? Really thank you very much!

**Comment by PoisonAlien** [comment]
Hi,
See [here](https://github.com/PoisonAlien/maftools/issues/298#issuecomment-753468389)
