### ISSUE TITLE
Inappropriate proportions of the top10 mutated genes

### ISSUE THREAD

**Issue by asmlgkj** [PoisonAlien/maftools#620]
R3.6.3
plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)

Dear professor,
Thanks for this outersstanding tool to visualize snp data. I am reading your guidence  in https://www.bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html

but I found Inappropriate proportions of the top10 mutated genes, you  can see the 25% is longer than 27%， how should I understand this plot
![image](https://user-images.githubusercontent.com/50854682/94396212-0aa05780-0194-11eb-884e-1e3a595ffe1d.png)

**Comment by ShixiangWang** [comment]
@asmlgkj  If I am right, this is not a bug. I remember someone has asked this question. The fraction indicates how many samples out of all samples have this gene mutation. However, the bar height indicates total mutations in this gene, i.e. a sample may have multiple DNMT3A mutations.

@PoisonAlien Maybe you can add some description about the difference in maftools vignette.

**Comment by asmlgkj** [comment]
thanks a lot@ShixiangWang

**Comment by PoisonAlien** [comment]
Hi, @asmlgkj Please take a look at #400 for details. Let me know if something is unclear.
Thanks @ShixiangWang , I will add a note in the vignette.

**Comment by asmlgkj** [comment]
thanks a lot
do you consider add xlab and ylab for each of the subplot
@PoisonAlien

**Comment by PoisonAlien** [comment]
Hi,
I think the plot is pretty clear already with the labels. Where would you suggest to add the labels?

**Comment by asmlgkj** [comment]
> Hi,
> I think the plot is pretty clear already with the labels. Where would you suggest to add the labels?

![image](https://user-images.githubusercontent.com/50854682/94412528-78f11400-01ac-11eb-9c01-92500e31d841.png)
like such, thanks a lot

**Comment by PoisonAlien** [comment]
Plot titles actually describes each plot. If you're referring to the colour code for each box (in Variant Classification summary) - they are explained in the first plot (top left). Due to limited space, I could not put them here below the plot. 
As for the Variants per sample plot setting `showBarcodes = TRUE` will show up the sample names. Hope this helps.
