### ISSUE TITLE
somaticinteractions - feature request

### ISSUE THREAD

**Issue by vf2181** [PoisonAlien/maftools#622]
First, your package is awesome and I use it very ofter! 

I was wondering if there is a way to add copy number data to the somaticinteractions function? Or have an option to integrate it? 

The purpose will be: 
1. Check if there are any somatic mutations the have occurrence relationship with copy number alterations 

2. Some mutations (more likely loss of function) have both somatic and copy number alterations, and excluding copy number data might results in missing a significant relationship. 

Thanks!

Vitalay

**Comment by PoisonAlien** [comment]
Hi,
Could you be bit more specific. Because present implementation already considers CN events. 
You will have to integrate CN while reading in your maf file with `read.maf`. You can use results from either GISTIC or provide a custom gene table with CN status.

**Comment by beginner984** [comment]
Sorry @PoisonAlien  having two maf objects for two groups, is this possible to have the same order of genes in `somaticInteractions` ?

**Comment by PoisonAlien** [comment]
Yes it should be possible. Please see `? somaticInteractions` for details. 
You will have to use same `genes` and `geneOrder` arguments for both mafs.

**Comment by beginner984** [comment]
Thank you

I think the main post from the @vf2181 is asking to plot `mutual exclusivity/co-occurrence` of, for instance, amplified _CCDN1_ with any mutated genes because here likely the function just takes care of mutual exclusivity/co-occurrence between a pair of genes regardless of type of genomic changes `(CNV-CNV, mutation-CNV and mutation-mutation)`

**Comment by PoisonAlien** [comment]
In that case, you can subset your maf to include only CNV events or mutations of certain type and run the somaticInteractions.

**Comment by beginner984** [comment]
Thank you much

I have a list of genes which I want to pot but I get a range of errors

```
> somaticInteractions(maf = r, gene=c("CDKN2A","TP53","MYC","EGFR"), pvalue = c(0.05, 0.1))
Error in somaticInteractions(maf = r, gene = c("CDKN2A", "TP53", "MYC",  : 
  argument 2 matches multiple formal arguments
> 
```

Or 

```
>   somaticInteractions(
+     r,
+     top = 25,
+     genes = genes,
+     pvalue = c(0.05, 0.01),
+     returnAll = TRUE,
+     geneOrder = TRUE,
+     fontSize = 0.8,
+     showSigSymbols = TRUE,
+     showCounts = FALSE,
+     countStats = "all",
+     countType = "all",
+     countsFontSize = 0.8,
+     countsFontColor = "black",
+     colPal = "BrBG",
+     showSum = TRUE,
+     colNC = 9,
+     nShiftSymbols = 5,
+     sigSymbolsSize = 2,
+     sigSymbolsFontSize = 0.9,
+     pvSymbols = c(46, 42),
+     limitColorBreaks = TRUE
+   )
Error in somaticInteractions(r, top = 25, genes = genes, pvalue = c(0.05,  : 
  Genes in geneOrder does not match the genes used for analysis.
```
Do you know the reason of the errors please?

Thank you so much

**Comment by PoisonAlien** [comment]
Hi,

1. Argument is `genes= ` and not `gene = `

2. `geneOrder` takes gene names as input. For. ex; `geneOrder = c("DNMT3A", "IDH2", "FLT3", "TET2")`

Once again please read the help page. Also, make sure you're using correct names for arguments.

**Comment by beginner984** [comment]
Thank you

Now I get this
```
> genes=c("CDKN2A","TP53","EGFR","CDK6","GATAD1","SMAD4","GATA4","ARID1A","LIN7A","RNF43","ARID2","EPHA3","PBRM1","PIK3CA","PTEN","SCN3A","TSHZ3","APC","ERBB2","CCNE1")
> somaticInteractions(
+          Responders,
+       top = NULL,
+         genes = genes,
+          pvalue = c(0.05, 0.01),
+          returnAll = TRUE,
+          geneOrder = genes)
Error in interactions[geneOrder, geneOrder] : subscript out of bounds
>
```

![Picture1](https://user-images.githubusercontent.com/43682980/100635631-a717df00-3328-11eb-8a45-7cf00f1569a9.png)

**Comment by PoisonAlien** [comment]
This is a tricky situation and hard to account for. I can't think of any easy way to solve this :|
You will probably have to add a dummy synonymous variant for the missing gene in the maf file and read it again. I am not if it will work though.. You can try.
