### ISSUE TITLE
Incorrect deduplication cases in icgcSimpleMutationToMAF

### ISSUE THREAD

**Issue by Hu-JIN** [PoisonAlien/maftools#623]
**Describe the issue**
According to https://github.com/PoisonAlien/maftools/blob/2862f77734cead15623ffdc1565eafc0bed8c0ec/R/validateMaf.R#L26, icgcSimpleMutationToMAF uses (Chromosome, Start_Position, Tumor_Sample_Barcode) as the index to deduplicate variants. However, two different mutations may have the same Chromosome, Start_Position, and Tumor_Sample_Barcode. This will result in unique mutations being incorrectly filtered out. 

Example: ICGC sample SA499831 has the following two mutations:

- Mutation MU29843874, at chr2:69092859-69092859, a SNP of C>T.

- Mutation MU29843851, at chr2:69092859-69092859, an insertion of TT at that locus. 

So it is in fact a mutation of C>TTT, represented as 2 unique mutations in the file. After running icgcSimpleMutationToMAF on this sample, one of the two mutations is retained, but not both. The reason is as stated above, i.e., (Chromosome, Start_Position, Tumor_Sample_Barcode) is not a unique index of the variants. Further information should be taken into account, especially Reference_Allele and Tumor_Seq_Allele2.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for tracking the issue. I agree that the genomic loci with differing variant alleles should be accounted for. I have fixed it. You will have to pull it from GitHub for patched version.
