### ISSUE TITLE
Problem with merging maf files

### ISSUE THREAD

**Issue by Mussa1122** [PoisonAlien/maftools#624]
Hello

I am trying to merge two maf objects or maf files but all I get error

```
merge_mafs(lamlr,lamlp)
Error in as.list.default(X) :
no method for coercing this S4 class to a vector

merge_mafs(res1,pre)
Error in if (verbose) { : argument is not interpretable as logical
In addition: Warning message:
In if (verbose) { :
the condition has length > 1 and only the first element will be used
I don't know why I am getting error

```
This is my maf files 

https://www.dropbox.com/s/t1dzeqlvsmpoqkq/res1.rds?dl=0

https://www.dropbox.com/s/b5l6er7alucws03/pre.rds?dl=0

Thank you for any help

**Comment by PoisonAlien** [comment]
Hi,
Input needs to be a `list`.

```r
merge_mafs(list(pre, res1))
```

**Comment by Mussa1122** [comment]
Hello

Before merging a maf2 with maf1, _NAV3_ has been mutated 22% in maf2

![Rplot](https://user-images.githubusercontent.com/68249398/95801589-a4b6e280-0cf2-11eb-8fe5-8d53b92c5b79.png)

But after merging that with maf1, the mutation rate is 13%

![Rplot01](https://user-images.githubusercontent.com/68249398/95801658-f19ab900-0cf2-11eb-8b96-3acdfcb3196d.png)

I don't know what is happening for mutation rate

This is maf1, maf2 and merged mafs

https://www.dropbox.com/s/p4fh9e64clpnn5n/maf1.rds?dl=0

https://www.dropbox.com/s/f7dmkajeki83vna/maf2.rds?dl=0

https://www.dropbox.com/s/czai9ef1uw64dw4/merged_maf.rds?dl=0

Please can you have a look?

Thank you

**Comment by eibol1** [comment]
Hi, 

sorry for reopening this. Is there any way to merge the maf files with `ClinicalData` for example, from the TCGA?:

`laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') `

thanks!!
