### ISSUE TITLE
Incomplete oncoplot

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#625]
Hello

I am trying to draw an oncoplot having clinical data like

```
> oncoplot(d,  draw_titv = TRUE,clinicalFeatures = "Response")
Error in plot.new() : figure margins too large
> 
```

I get incomplete annotation without legend 

![Rplot](https://user-images.githubusercontent.com/43682980/96027382-b5309f80-0e4f-11eb-89b2-29132445ee51.png)

How I overcome this please having an oncoplot with annotation?

**Comment by PoisonAlien** [comment]
You need to increase the device size. If you're using Rstudio, you will have to enlarge the plot pane to accommodate the entire plot. If you are saving it to a pdf file, you will need to increase `width` and `height` of the document.

**Comment by beginner984** [comment]
Sorry this plot is the exact output after running the code. I mean even in rstudio I can not see the annotation and legends and therefore saving with whatever dimension I would to see that

**Comment by PoisonAlien** [comment]
Yeah, you will probably have to play with `legend_height`, `legendFontSize`, `annotationFontSize` etc to get it right.
Check `?oncoplot` for complete details.

**Comment by beginner984** [comment]
Sorry I employed the least number for the arguments you kindly suggested but still not working

<img width="1280" alt="Screenshot 2020-10-15 at 19 25 02" src="https://user-images.githubusercontent.com/43682980/96170985-2ccc0080-0f1c-11eb-961a-8c98f436004e.png">

**Comment by rpauly** [comment]
I am having the same issue...any solutions?

**Comment by PoisonAlien** [comment]
Try to increase `legend_height` (default 4) and `anno_height` (default 1). It should work.

**Comment by hjack123** [comment]
Same issue here, adjusted the heights and still don't see legend....

**Comment by hjack123** [comment]
if you add clinicalFeatures, the legend is gone, or being covered

**Comment by shaghayeghsoudi** [comment]
any solution to this problem? I am having the exact same issue

**Comment by FredoJones** [comment]
Yo everyone, I found a solution. It's embarrassingly simple. Just increase the plot window in proportion to the script/mkdown window, console and environment. This show be enough to include the rest of your legends and annots. Attached here a screenshot to give you the gist. It really worked for me! 
![solution](https://user-images.githubusercontent.com/83115495/198987187-00bb90eb-380d-4d7f-9388-cac973fcdd22.png)

> Hello
> 
> I am trying to draw an oncoplot having clinical data like
> 
> ```
> > oncoplot(d,  draw_titv = TRUE,clinicalFeatures = "Response")
> Error in plot.new() : figure margins too large
> > 
> ```
> 
> I get incomplete annotation without legend
> 
> ![Rplot](https://user-images.githubusercontent.com/43682980/96027382-b5309f80-0e4f-11eb-89b2-29132445ee51.png)
> 
> How I overcome this please having an oncoplot with annotation?
