### ISSUE TITLE
error in rainfallPlot "cannot mix zero-length and non-zero-length coordinates"

### ISSUE THREAD

**Issue by bkinnersley** [PoisonAlien/maftools#628]
Hello,

Thank you for a very useful package! I am interested in running the rainfallPlot function to detect potential regions of kataegis. This runs fine for most tumours I have tried it on, e.g. running example command:

`library(maftools)`

`input_maf = 'sample_id.GRCh38.PASS.MAF.gz'`

`input = read.maf(maf = input_maf)`

`rainfallPlot(maf = input, detectChangePoints = TRUE, ref.build = "hg38", savePlot = TRUE)`

However for a very small number I get the following error message:

Kataegis detected at:
     Chromosome Start_Position End_Position nMuts Avg_intermutation_dist Size Tumor_Sample_Barcode C>T T>C
1.    1                     630110            634494          8         626.2857                      4384  sample_id                      3        5

Error in arrows(x0 = maf.cpt$Start_Position_updated, y0 = 0, x1 = maf.cpt$Start_Position_updated, : 
     cannot mix zero-length and non-zero-length coordinates
Calls: rainfallPlot -> arrows
Execution halted

The errors always seem to occur if a potential region of kataegis is detected right at the start of chromosome 1 (with Start_Position and End_Position very similar and often the same as those in the example above)

Thanks very much!

**Comment by ShixiangWang** [comment]
Are you using the latest version of maftools from GitHub? Could you also post the data for debugging?

**Comment by bkinnersley** [comment]
Hello,

Thanks for the reply! Attached is my sessionInfo() - I used the latest version of maftools (v2.5.10)
![image](https://user-images.githubusercontent.com/34348939/97676186-28f5bd80-1a88-11eb-9e39-b44e7d52c8bc.png)

It is not possible to upload a whole MAF but here are the mutations in one MAF that seem to have caused the error:
![image](https://user-images.githubusercontent.com/34348939/97676643-d7016780-1a88-11eb-99a9-9e4ebb536e40.png)


Thanks very much

**Comment by ShixiangWang** [comment]
If you could provide some mutation records to reproduce the error, you should also attach a file so we can use it for import.

**Comment by bkinnersley** [comment]
Hello,

Unfortunately I cannot upload the whole MAF, but have created an initial subset that reproduces the issue, hope this helps

[example.zip](https://github.com/PoisonAlien/maftools/files/5464214/example.zip)

Thanks very much

**Comment by ShixiangWang** [comment]
@bkinnersley I have submitted a PR https://github.com/PoisonAlien/maftools/pull/629 to fix this issue. You can install the latest version from GitHub after @PoisonAlien accept the PR.

**Comment by PoisonAlien** [comment]
Hi @bkinnersley 
Thanks for opening the issue. I have pushed a fix using PR #629 
Please try it and feel free to reopen the issue if necessary.

**Comment by bkinnersley** [comment]
Thanks very much that fixed it
