### ISSUE TITLE
read.maf

### ISSUE THREAD

**Issue by Naziaahmad** [PoisonAlien/maftools#63]
Dear PoisonAlien,

I want to use silent variants but removeSilent is not working for latest install of maftools. It produces following error.

 Error in read.maf(maf = "3_UTR.maf", removeSilent = FALSE, useAll = FALSE) : 
  unused argument (removeSilent = FALSE).

I have installed it on another system a week ago and it was working perfectly.

**Comment by PoisonAlien** [comment]
Hi,

I recently made a lots of changes to maftools including to read.maf. 
In recent version synonymous variants will be kept in a separate slot and won't be mixed with non-synonymous variants. May I ask the purpose you're doing this for ? so that I can make changes if it makes sense. Is it only for plotting ?

**Comment by Naziaahmad** [comment]
Thank you for prompt reply.

Actually I want to check density and recurrency of mutations in 3' UTR
region of top genes.

Regards,

Nazia

**Comment by PoisonAlien** [comment]
Ah! Okay.. So this is only to get sample/gene summary statistics isn't it ?

**Comment by Naziaahmad** [comment]
Yes

**Comment by PoisonAlien** [comment]
Hi,
Can you install from github again. I have put new function `mafSummary` and it should get you what you're looking for. Please let me know if this is what you wanted.

**Comment by Naziaahmad** [comment]
Thank you so much.

It really worked exactly what i want.

Another suggestion is to add mutated sample per variant classification
along with the total mutated sample.

Thank you.

Regards,

Nazia

**Comment by MBeyens** [comment]
Hi,
I would like to plot the full summary of a cohort, so not only the limited defined categories in maftools; but also UTR's, intronic etc.  
Is there a way to do so? Like the plot plotmafSummary, but all then?

Thank you in advance!

**Comment by PoisonAlien** [comment]
Hi,
Sorry for late reply. You can include desired variant classifications in the plot. By default maftools uses variant Classifications with High/Moderate variant consequences as non-syn variant. You can provide a separate list via argument `vc_nonSyn` while reading maf with `read.maf` and it should do the trick.

**Comment by rong923** [comment]
Hi, same as @MBeyens, I wanted to plot every variant regardless of annotation. But read.maf does not recognize vc_nonSyn argument, any idea why? Thanks so much!

**Comment by PoisonAlien** [comment]
Hi,
What version of maftools are you using ? Could you post your session info and `read.maf` command ?

**Comment by rong923** [comment]
Thanks for the reply. Below is the information:
> source("https://bioconductor.org/biocLite.R")
Bioconductor version 3.5 (BiocInstaller 1.26.1), ?biocLite for help
A newer version of Bioconductor is available for this version of R,
  ?BiocUpgrade for help
> biocLite("maftools")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.1 (2017-06-30).
Installing package(s) ‘maftools’
trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/macosx/el-capitan/contrib/3.4/maftools_1.2.30.tgz'
Content type 'application/x-gzip' length 6329045 bytes (6.0 MB)


#####Command
laml <- read.maf(maf = var.annovar.maf,vc_nonSyn=c("UNKNOWN"))
Error in read.maf(maf = var.annovar.maf, vc_nonSyn = c("UNKNOWN")) : 
  unused argument (vc_nonSyn = c("UNKNOWN"))

**Comment by PoisonAlien** [comment]
Hi,
You're still using older version of maftools (1..2.30). Current version is 1.4.05
Please update and try again, it should work.

**Comment by rong923** [comment]
Thank you, it worked.
