### ISSUE TITLE
tcgaCompare：Incomplete image tags

### ISSUE THREAD

**Issue by WangYuan20190517** [PoisonAlien/maftools#630]
When I use tcgaCompare，the image tag couldn't display completely. I couldn't see the number at the top of the figure.

laml.mutload = tcgaCompare(maf = laml.maf, cohortName = 'CCDC18',logscale = TRUE)

**Comment by PoisonAlien** [comment]
Hi,
I could not reproduce your issue. But its always good to save the plot to a pdf with enough height. 

e.g,
```r
pdf(file = "tcga_tmb.pdf", height = 5, width = 8)
laml.mutload = tcgaCompare(maf = laml.maf, cohortName = 'CCDC18',logscale = TRUE)
dev.off()
```

**Comment by WangYuan20190517** [comment]
Hi,
Thank you very much! I have solved this problem.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PoisonAlien/maftools"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午4:13
收件人:&nbsp;"PoisonAlien/maftools"<maftools@noreply.github.com&gt;;
抄送:&nbsp;"王苑"<729686126@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [PoisonAlien/maftools] tcgaCompare：Incomplete image tags (#630)





 
Hi,
 I could not reproduce your issue. But its always good to save the plot to a pdf with enough height.
 
e.g,
 pdf(file = "tcga_tmb.pdf", height = 5, width = 8) laml.mutload = tcgaCompare(maf = laml.maf, cohortName = 'CCDC18',logscale = TRUE) dev.off()
