### ISSUE TITLE
Can I order the gene manually in oncoplot?

### ISSUE THREAD

**Issue by yeswzc** [PoisonAlien/maftools#631]
**Can I order the gene manually in oncoplot?**
I want to sort and display the genes manually.

Thanks!

**Comment by PoisonAlien** [comment]
Hi, 
Yes, you can do that. 

e.g, 

```r
maftools::oncoplot(maf = laml, genes = c("TP53", "DNMT3A", "NPM1"), keepGeneOrder = TRUE)
```

**Comment by yeswzc** [comment]
Wonderful, I was trying GeneOrderSort = F it doesn't change anything. I did not notice this parameter before. 
Thank you, Aien!
