### ISSUE TITLE
Clinical Enrichment OR

### ISSUE THREAD

**Issue by HHayman** [PoisonAlien/maftools#633]
**Describe the issue**
Heylo

Thanks for your work on the package, it's fantastic! :) 

I've come across a problem with the output from clinical enrichment, which I suspect is a misunderstanding of how the OR is presented. My interpretation is that I am getting an OR <1 for an effect in which the odds of being in group 1 is greater if a mutation is present (1). If I manually calculate the OR, I seem to be getting an OR of 10.57. I'm not sure what the OR_low/OR_high split is, and I can find no explanation to explain my different outcome.

Thanks!

**Command**
Please post your commands and the output (errors or any unexpected output)

```
Cohort.ce = clinicalEnrichment(maf = Cohort, clinicalFeature = 'Feature')

Cohort.ce$groupwise_comparision[p_value < 0.05]


    Hugo_Symbol Group1 Group2 n_mutated_group1 n_mutated_group2     p_value OR_low   OR_high
 1:      Gene_A      1   Rest          8 of 50         2 of 113 0.001340599      0 0.4143872
 2:         Gene_B      1   Rest         10 of 50         6 of 113 0.005781703      0 0.6274546
 3:      Gene_C      1   Rest         12 of 50         9 of 113 0.006520046      0 0.6716642
 4:     Gene_D      1   Rest          7 of 50         3 of 113 0.009835328      0 0.6405781
 5:          Gene_E      1   Rest         18 of 50        21 of 113 0.015085113      0 0.8181482
 6:       Gene_F      1   Rest          8 of 50         5 of 113 0.016710575      0 0.7556722
 7:       Gene_G      1   Rest          7 of 50         4 of 113 0.020523141      0 0.7797514
 8:      Gene_H      1   Rest          7 of 50         4 of 113 0.020523141      0 0.7797514
 9:       Gene_I      1   Rest          7 of 50         4 of 113 0.020523141      0 0.7797514
10:       Gene_J      1   Rest         11 of 50        10 of 113 0.022453955      0 0.8412036
    Hugo_Symbol Group1 Group2 n_mutated_group1 n_mutated_group2     p_value OR_low   OR_high
          fdr
 1: 0.2627574
 2: 0.3311370
 3: 0.3311370
 4: 0.3311370
 5: 0.3311370
 6: 0.3311370
 7: 0.3311370
 8: 0.3311370
 9: 0.3311370
10: 0.3311370
11: 0.3311370
12: 0.3311370
13: 0.3311370
14: 0.3311370
15: 0.3311370
16: 0.3311370
17: 0.3311370
18: 0.3311370
19: 0.3311370
20: 0.3663688
21: 0.4386645
          fdr


```

**Session info**
Run `sessionInfo()` and post the output below

```R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.6.05

loaded via a namespace (and not attached):
 [1] bit_4.0.4          compiler_4.0.0     Matrix_1.2-18      tools_4.0.0       
 [5] RColorBrewer_1.1-2 survival_3.2-7     tinytex_0.27       bit64_4.0.5       
 [9] splines_4.0.0      grid_4.0.0         data.table_1.13.2  xfun_0.19         
[13] lattice_0.20-41   
```

**Comment by PoisonAlien** [comment]
Hi,
Thanks for using maftools and I am glad that you find it useful. 

Regarding the question, the hypothesis that is being tested here is that there are lesser wild types in the group of interest compared to the rest of the samples.

From your results:

```r
> mat = matrix(data = c(42, 8, 111, 2), nrow = 2, dimnames = list(c("WT", "Mutant"), c("Group", "Rest")))
> mat
       Group Rest
WT        42  111
Mutant     8    2

> fisher.test(x = mat, alternative = 'l')

	Fisher's Exact Test for Count Data

data:  mat
p-value = 0.001341
alternative hypothesis: true odds ratio is less than 1
95 percent confidence interval:
 0.0000000 0.4143872
sample estimates:
odds ratio 
0.09615572 
```

You can interpret the odds ratio as the odds of being wild-type in the group is 0.09 times that of being a mutant. 

Inversely, you can check the odds of being mutant in the group.

```r
> mat = matrix(data = c(8, 42, 2, 111), nrow = 2, dimnames = list(c("Mutant", "WT"), c("Group", "Rest")))
> mat
       Group Rest
Mutant     8    2
WT        42  111

> fisher.test(x = mat)

	Fisher's Exact Test for Count Data

data:  mat
p-value = 0.001341
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
   1.966803 104.474082
sample estimates:
odds ratio 
   10.3998 
```

Here you would get the result that you were expecting (10 times more than that of WT in the group).

Now that I answered your question, it seems that your way of the second approach seems way better to understand.

**Comment by HHayman** [comment]
Thank you so much, I see what's happening now. I was reading the upper interval as the actual OR, so that I think is why I couldn't reverse engineer where I was going wrong. 

Is there a way to include the OR itself in the readout from;
'Cohort.ce$groupwise_comparision[p_value < 0.05]'?

**Comment by PoisonAlien** [comment]
No problem. My bad, I  will add it soon. I don't know why I didn't add it in the first place. Thanks for bringing it up.

**Comment by HHayman** [comment]
No worries :D

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue. I have fixed the issue and also now the odds-ratios are reversed. It now reports OR as the way you intended.
