### ISSUE TITLE
key not appearing on coBarplot

### ISSUE THREAD

**Issue by roshanipatel12** [PoisonAlien/maftools#634]
**Describe the issue**
I am making a coBarplot, but not all the variants present are appearing in the key. e.g. The red does not appear in the key.  Is there any advice you have that I can enter into the R command to make the full key appear please. 

**Command**
coBarplot(m1 = adenoma, m2 = normal, m1Name = 'adenomas', m2Name = 'normal tissue')

**Comment by PoisonAlien** [comment]
Hi,
Could you please post the output plot from the above command? By `key` do you mean the bottom legend?
You can scratch out the gene names if you don't want to display the results (set `geneSize = 0.01`).

**Comment by roshanipatel12** [comment]
Sorry... I'm new on here and learning. Yes I meant the legend size... and it worked now after I made the legendTxtSize smaller. 
Thanks for getting back to me.

**Comment by roshanipatel12** [comment]
Sorry... I'm new on here and learning. Yes I meant the legend size... and it worked now after I made the legendTxtSize smaller. 
Thanks for getting back to me.

**Comment by PoisonAlien** [comment]
No problem. I am closing the issue for now. Feel free to comment if you have more questions.
