### ISSUE TITLE
Is it possible to exclude specific genes from MAFsummary or Oncoplot

### ISSUE THREAD

**Issue by abkhan90** [PoisonAlien/maftools#635]
Hi!

Thank you for your excellent work.

I would like to exclude specific genes in the analysis of my samples. For example, in my tumor samples, mucins have high burn of meaningless mutations and I would like to exclude for top 10 lists. Is this possible? Thanks!!

**Comment by PoisonAlien** [comment]
Hi,
If you want to completely remove these genes (MUC1, MUC16, MUCx...) from your maf object then you can use `filterMaf` function.

Bleow example will remove all `MUCx` mutations from the object. 
```r
> maf_filtered = maftools::filterMaf(maf = laml, genes = c("MUC16", "MUC17", "MUC6"))
```

If you are just trying to ignore these from `oncoplot`, you can use the argument `genesToIgnore`. 

Hope this helps.
