### ISSUE TITLE
Extracting Kataegis table from rainfallPlot

### ISSUE THREAD

**Issue by ellchua** [PoisonAlien/maftools#636]
Hi, 

is there any way I can extract the kataegis table after running `rainfallPlot` with `detectChangePoints = TRUE`?

I tried assigning it to a variable, but the variable only gives back
```r
quartz_off_screen 
                2 
```

**Comment by PoisonAlien** [comment]
Hi,
Results are written to a tsv file under the working directory with the name  `<sample_name>_Kataegis.tsv`.

**Comment by ellchua** [comment]
Thanks! The help page from `?rainfallPlot` says "Results are written to an output file with suffix changePoints.tsv" so that's what I've been looking for and couldn't find it.

**Comment by PoisonAlien** [comment]
Oh! You are right. I will correct it. Thanks.
