### ISSUE TITLE
Gene Pathways in coOncoplots

### ISSUE THREAD

**Issue by HHayman** [PoisonAlien/maftools#637]
Heylo

I have used 'genes' and 'pathways' to create custom gene groups within my oncoplots, as shown, using this code;
![Oncoplot_Pathways](https://user-images.githubusercontent.com/75019173/100869900-a781b880-3495-11eb-85e3-e8b85be0b7cc.png)
`oncoplot(maf = Whole, pathways = pathways, gene_mar = 8, fontSize = 0.6)`

Using this code, I produce coOncoplots, no problem;
![coOncoplot](https://user-images.githubusercontent.com/75019173/100870750-0ac01a80-3497-11eb-82ab-65650e8f653f.png)
`coOncoplot(m1 = GroupA, m2 = GroupB, m1Name = 'GroupA', m2Name = 'GroupB', genes = genes, keepGeneOrder = TRUE)`

However, when I try to use 'pathways' in the coOncoplot, I get the error "unused argument (pathways = pathways)".
`coOncoplot(m1 = GroupA, m2 = GroupB, m1Name = 'GroupA', m2Name = 'GroupB', pathways = pathways)`

I couldn't (visually at least) see any reason why 'pathways' would not work, so I assumed that 'pathways' was just not included in the code for the 'coOncoplot' function, but is included for 'Oncoplot'. However, as I've been unable to troubleshoot it, I thought that it would be worth checking in case there is a technical restriction on using it.

I thought maybe it was because it is has no statistical test result for the gene pathways, and so can't add them to the plot as there is no comparison? If so, is there perhaps a way to overlay the gene pathways without a statistical comparison?

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Unfortunately, as you guessed it, `coOncoplot` does not support pathways yet. It is on my to-do list. But it might take a while since I have some other commitments.

**Comment by beginner984** [comment]
Hello @PoisonAlien 

Please have a look

```
> coOncoplot(
+     maf1,
+     maf2,
+     genes = genes,
+     m1Name = "Responders",
+     m2Name = "Non-responders",removeNonMutated = TRUE,keepGeneOrder = TRUE)
>
``` 

Is there any way to ignore genes which are 0% in both groups?

![Rplot05](https://user-images.githubusercontent.com/43682980/101540377-d1584500-3997-11eb-9a2d-f644b013022d.png)

**Comment by HHayman** [comment]
Have you tried using 'removeNonMutated = TRUE'?

Alternatively, if you use minmut=n during your comparison stage, there should be no comparison made and so maybe those genes won't be included in the coOncoplot?

**Comment by beginner984** [comment]
Yes that is in my code but that would remove non-mutated samples

**Comment by HHayman** [comment]
> Yes that is in my code but that would remove non-mutated samples

Sorry, missed that. Well, long-term I guess you'll want something more elegant, but for now; can you just rerun each coOncoplot and remove the 0% genes from your genes list?
