### ISSUE TITLE
Question about mafSummary

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#638]
Hello

I am struggling with some definition rather than reporting a bug or requesting a feature 

I have added GISTIC data to my maf

By `mafSummary`, we get `CNV_total`, `Amp `and `Del`

I looked at R scripts in code folder but I could not understand CNV_total comes from where, the  total number of genes, chromosome breakpoints or fraction of genome?
Thank you so much for any help

**Comment by PoisonAlien** [comment]
Hi,
`CNV_total` is the sum of `Amp` and `Del`columns. `Amp` and `Del` represent the number of samples in which the gene is affected. They are *NOT* `total number of genes, chromosome breakpoints or fraction of genome?`

**Comment by beginner984** [comment]
Thank you @PoisonAlien 

I have 27 samples

This is the results

```
> res@summary
                   ID summary        Mean Median
 1:        NCBI_Build      NA          NA     NA
 2:            Center      NA          NA     NA
 3:           Samples      27          NA     NA
 4:            nGenes    2733          NA     NA
 5:   Frame_Shift_Del      42   1.5555556      1
 6:   Frame_Shift_Ins      34   1.2592593      1
 7:      In_Frame_Del      20   0.7407407      0
 8:      In_Frame_Ins       5   0.1851852      0
 9: Missense_Mutation    2530  93.7037037     91
10: Nonsense_Mutation     133   4.9259259      5
11:  Nonstop_Mutation       7   0.2592593      0
12:       Splice_Site      64   2.3703704      2
13:             total    2835 105.0000000    104
14:               Amp    2961 109.6666667    111
15:               Del     665  24.6296296     27
16:         CNV_total    3626 134.2962963    136
>
```

So 3626 is the total combination of alerted samples for a given gene

Are these are all recurrently changed (by GISTIC)?

**Comment by beginner984** [comment]
Sorry @PoisonAlien how I can get the number of amplified and deleted genes for each sample from maf object?

Thank you very much

**Comment by PoisonAlien** [comment]
Use `getSampleSummary()` for per sample events
Use `getGeneSummary()` for per gene events
