### ISSUE TITLE
Feature Request of SNPs by Samples Matrix

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#64]
Could you please create a function to summarise a MAF file to a SNP genomic position by patient sample matrix? For example:

```
           TCGA-Sample-1 TCGA-Sample-2
chr1:12345    Hom             Het
chr2:98765    None            Het
```

There's already a function to count the number of mutations at a gene level summary, so this would make a wonderful addition to the API to allow a more detailed analysis of mutations.

**Comment by PoisonAlien** [comment]
Hi Dario,

Thanks for the suggestion. Will do implement it soon and let you know.

**Comment by PoisonAlien** [comment]
Hi,
I have added new function `gtMatrix`. Can you test it and let me know if this works for you ? Install from GitHub.

Thanks!

**Comment by DarioS** [comment]
It works well. It's not immediately clear what `gtMatrix` is short for. I'd call it `genotypeMatrix` which would be in the style of other function names in the package such as `trinucleotideMatrix`. Also there are a couple spelling mistakes in the description "Creates a **G**enotype matrix using allele **frequcies** (frequencies) or by **muatation** (mutation) status." In the Arguments section, "Define NULL" should be "Default NULL".

**Comment by PoisonAlien** [comment]
Thank you :)

I was in bit of a rush, so couldn't document well. I will fix them soon.
