### ISSUE TITLE
MAFtools and MultiAssayExperiment compatibility

### ISSUE THREAD

**Issue by emmaroth** [PoisonAlien/maftools#640]
Hi! I'm currently working with some MAF output and would love to include it in a MultiAssayExperiment along with some other assayed samples. MAFtools output is not currently compatible with MAE assay requirements. Is there any way to convert to objects like a SummarizedExperiment or eset?

**Comment by PoisonAlien** [comment]
Hi,
Unfortunately, it is something that can not be done with MAF objects. `SummarizedExperiment` is best suited for datasets resulting in numeric matrices.  Since MAFs are primarily annotation files, those data containers will not work for MAF objects.

**Comment by PoisonAlien** [comment]
Hi @emmaroth 

I hope you have been following the MAF to MAE discussions. This feature has been added to `maftools` and well `MultiAssayExperimentToMAF`. Please see [here](https://github.com/waldronlab/MultiAssayExperiment/discussions/285#discussioncomment-385546) for details. 
Thank you for the feature request. I am closing the issue for now. Please feel free to comment if necessary.

P.S: Conversion of MAF to MAE has a bit of limited functionalities for now (i.e, no CNV support yet). I will update them by release of 3.13 Bioconductor.
