### ISSUE TITLE
plotApobecDiff issue 

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#642]
**Describe the issue**
The figure produced by plotApobecDiff has been cut off and I don't know what is going on since when I applied the exact same code to another dataset, it worked perfectly. 

<img width="647" alt="Screen Shot 2020-12-10 at 11 11 41 PM" src="https://user-images.githubusercontent.com/31411260/101861187-74968f00-3b3d-11eb-9751-e9cf235ee149.png">

> **Command**

Please post your commands and the output (errors or any unexpected output)

```r
plotApobecDiff(tnm = ed.tnm, maf = Ed.maf)
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
I think there might be an issue with `ylim` estimation in the code. I will fix it soon.
Thanks for the opening the issue.

**Comment by PoisonAlien** [comment]
Hi,
Could you please try now and let me know if this fixes the issue? You will have to install from GitHub for the fix.

**Comment by xiw588** [comment]
Hi, 

I just tried it again and the same issue occurred. Thank you for your help!

**Comment by PoisonAlien** [comment]
Did you install from GitHub? You will have to restart your R session after the installation for the changes to take effect.

**Comment by xiw588** [comment]
I see. I will restart and try it again later! Thank you!

**Comment by xiw588** [comment]
Sorry for the delay, but I just re-installed the package from GitHub, reran the analysis and the issue has been resolved. Thank you for your help. Happy Holidays!
