### ISSUE TITLE
9.8 Oncogenic Signaling Pathways

### ISSUE THREAD

**Issue by DrZhaoJie** [PoisonAlien/maftools#647]
Hi, I enjoyed your package and kept exploring it. In this part: 9.8 Oncogenic Signaling Pathways, how can I add other Oncogenic Signaling Pathways? 
First, what database did you access the related genes on interesting pathways? 
Second, how can I add my interesting pathways to your OncogenicPathways(maf = laml) to output corresponding pathway results? 
Thank you very much!

**Comment by PoisonAlien** [comment]
Hi,
All the details are on the help page of the function. You can do `?OncogenicPathways` for more info.
Briefly,
1. This is the [article](https://pubmed.ncbi.nlm.nih.gov/29625050/) I used to fetch the curated pathways
2. You can use `pathways` argument of `OncogenicPathways` for a custom list of pathways.

Hope this helps.

**Comment by DrZhaoJie** [comment]
Hi, I have looked up the help page of the function. It was very clear and thank you very much.
1. Were gene sets from the Molecular Signatures Database (MSigDB)  available  to be utilized in this function?
2.  I read the article you recommended. In figure6B and figure6D, it presented the co-mutated pathways. Have you explored this?  May I have your Rcode if you had done this work.  Also for figure7, May I have your Rcode if you had portrayed the figure7?

**Comment by DrZhaoJie** [comment]
Hello, may I have your answer, please?

**Comment by PoisonAlien** [comment]
Sorry for the delay. Things are slow because of the holidays. 
1. It's up to you. You can generate a pathway list however you want - as long as it is in the right format.
2. fig 6D. No; fig 7 No; Checkout `drugInteractions` function which you might find useful.
