### ISSUE TITLE
Can not cast an empty data.table

### ISSUE THREAD

**Issue by zhang919** [PoisonAlien/maftools#649]
**Describe the issue**
Dear, 
Thanks for development maftools, But I got some error when I process my maf (CCLE_mutations.csv) download from https://depmap.org/portal/download/ .
When I try to use  plotmafSummary, I got following error: 
```
Error in dcast.data.table(data = maf.con.class.summary, formula = Tumor_Sample_Barcode ~  : 
  Can not cast an empty data.table
Warning message:
In titv(maf = maf, useSyn = TRUE, plot = FALSE) :
  Non standard Ti/Tv class: 5499TRUE

```
**Command**
Please post your commands and the output (errors or any unexpected output)

```r
data_mutations <- read.csv('CCLE_mutations.csv',
                     header = T, 
                     stringsAsFactors = F)

data_mutations$Tumor_Seq_Allele2 <- rep(NA, dim(data_mutations)[1])
data_mutations$Tumor_Sample_Barcode <- data_mutations$DepMap_ID
laml = read.maf(maf = data_mutations)

plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)

```

**Session info**
Run `sessionInfo()` and post the output below

```r
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.6.05 tibble_3.0.4    configr_0.3.5   ggplot2_3.3.3   dplyr_1.0.2     devtools_2.3.2  usethis_2.0.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         RColorBrewer_1.1-2 compiler_4.0.3     pillar_1.4.7       prettyunits_1.1.1  remotes_2.2.0     
 [7] tools_4.0.3        testthat_3.0.1     digest_0.6.27      pkgbuild_1.2.0     pkgload_1.1.0      lattice_0.20-41   
[13] jsonlite_1.7.2     memoise_1.1.0      lifecycle_0.2.0    gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.9       
[19] Matrix_1.2-18      cli_2.2.0          rstudioapi_0.13    yaml_2.2.1         curl_4.3           stringr_1.4.0     
[25] withr_2.3.0        desc_1.2.0         generics_0.1.0     fs_1.5.0           vctrs_0.3.6        rprojroot_2.0.2   
[31] grid_4.0.3         tidyselect_1.1.0   data.table_1.13.4  glue_1.4.2         R6_2.5.0           processx_3.4.5    
[37] fansi_0.4.1        survival_3.2-7     sessioninfo_1.1.1  callr_3.5.1        purrr_0.3.4        magrittr_2.0.1    
[43] splines_4.0.3      scales_1.1.1       ps_1.5.0           ellipsis_0.3.1     assertthat_0.2.1   colorspace_2.0-0  
[49] stringi_1.5.3      ini_0.3.1          RcppTOML_0.1.7     munsell_0.5.0      crayon_1.3.4      
```

Could you please give me more information about it?
Best.
Zhang

**Comment by PoisonAlien** [comment]
Hi,
It seems that the values in `Variant_Type` column are misformed. It should be `SNP` `INS` or `DEL`. Could you please double-check this?

**Comment by zhang919** [comment]
> 
> 
> Hi,
> It seems that the values in `Variant_Type` column are misformed. It should be `SNP` `INS` or `DEL`. Could you please double-check this?

Dear PoisonAlien,
Thanks for your so qiuickly reply. I think you are right by run following comand: 
`r
unique(data_mutations$Variant_Type)
`

> [1] "SNP" "DEL" "INS" "DNP" "TNP" NA

Does I must remove all another Variant_Type fistly?
Best.
Zhang

**Comment by PoisonAlien** [comment]
Wait, I just saw your code.

```r
data_mutations$Tumor_Seq_Allele2 <- rep(NA, dim(data_mutations)[1])
```

Is there a reason for setting `Tumor_Seq_Allele2` to `NA`? These are the mutated alleles that are used to plot TiTv events. Don't you have this information in the CSV file?

**Comment by zhang919** [comment]
> 
> 
> Wait, I just saw your code.
> 
> ```r
> data_mutations$Tumor_Seq_Allele2 <- rep(NA, dim(data_mutations)[1])
> ```
> 
> Is there a reason for setting `Tumor_Seq_Allele2` to `NA`? These are the mutated alleles that are used to plot TiTv events. Don't you have this information in the CSV file?

Yes, I find this filed is missing in the csv, Actually I am a rookie for maf file, I think this is because it is the sequencing of the cell line and there is no need to consider the issue of tumor purity. So I replace it with NA, could you please tell me its right?

Best.
Zhang

**Comment by PoisonAlien** [comment]
I downloaded the `CCLE_mutations.csv` file. It seems they don't have `Tumor_Seq_Allele2` column but instead, alt alleles are stored in `Tumor_Seq_Allele1`. Renaming that column to `Tumor_Seq_Allele2` should work fine.

```r
data_mutations <- data.table::fread("~/Downloads/CCLE_mutations.csv")

# Rename columns 
colnames(data_mutations)[which(colnames(data_mutations) == "Tumor_Seq_Allele1")] = "Tumor_Seq_Allele2"
colnames(data_mutations)[which(colnames(data_mutations) == "DepMap_ID")] = "Tumor_Sample_Barcode"

cc = maftools::read.maf(cc)
maftools::plotmafSummary(cc)
```

**Comment by zhang919** [comment]
> 
> 
> I downloaded the `CCLE_mutations.csv` file. It seems they don't have `Tumor_Seq_Allele2` column but instead, alt alleles are stored in `Tumor_Seq_Allele1`. Renaming that column to `Tumor_Seq_Allele2` should work fine.
> 
> ```r
> data_mutations <- data.table::fread("~/Downloads/CCLE_mutations.csv")
> 
> # Rename columns 
> colnames(data_mutations)[which(colnames(data_mutations) == "Tumor_Seq_Allele1")] = "Tumor_Seq_Allele2"
> colnames(data_mutations)[which(colnames(data_mutations) == "DepMap_ID")] = "Tumor_Sample_Barcode"
> 
> cc = maftools::read.maf(cc)
> maftools::plotmafSummary(cc)
> ```

Dear PoisonAlien, 
I am very grateful for your help. I mistakenly believe that Tumor_Seq_Allele1 and Tumor_Seq_Allele2 have completely different meanings because I read the instructions in https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/ . Thank you for your professional and timely help.

Best.
Zhang
