### ISSUE TITLE
ICGCtoMAF error

### ISSUE THREAD

**Issue by wp1g19** [PoisonAlien/maftools#652]
Appears writing the esad data to maf forms an incorrect file, the script is below.

 esad.maf <- icgcSimpleMutationToMAF(icgc = "/home/*****/ICGC/simple_somatic_mutation.open.ESAD-UK.tsv", MAFobj = TRUE)                                                                                                                                                                     |--------------------------------------------------|
|==================================================|
|--------------------------------------------------|
|==================================================|
--Removed 30371749 duplicated variants
--Found  7229646  variants with no Gene Symbols
--Annotating them as 'UnknownGene' for convenience
--Non MAF specific values in Variant_Classification column:
  NA
--Non MAF specific values in Variant_Type column:
  NA
Summarizing..
-Processing clinical data
--Missing clinical data
> read.maf(esad.maf)
-Reading
Error in file.info(file) : invalid filename argument

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay in responding. `icgcSimpleMutationToMAF` with `MAFobj = TRUE` will already return the data as an MAF object. You don't have to read it again with `read.maf`.

**Comment by wp1g19** [comment]
Hi Poison, the issue is that I've had to do this work on a supercomputer as the icgc esad tsv is 15gb, I'm looking for a way to export the maf so I can process it on my work PC.

**Comment by PoisonAlien** [comment]
Hi,
In that case you could try to get rid of unwanted columns which should reduce the object size significantly. 

Example on a 1M rows of your ESAD file
```r
#zcat simple_somatic_mutation.open.ESAD-UK.tsv.gz | head -n 1000000 > simple_somatic_mutation.open.ESAD-UK_1Mentries.tsv

> ic = maftools::icgcSimpleMutationToMAF(
  icgc = "~/Downloads/simple_somatic_mutation.open.ESAD-UK_1Mentries.tsv",
  removeDuplicatedVariants = F,
  addHugoSymbol = T
)

> print(object.size(ic), units = 'Mb')
3352.8 Mb

#Keep only required fields
> ic_min = ic[, .(
  Hugo_Symbol,
  Chromosome,
  Start_Position,
  End_Position,
  Reference_Allele,
  Tumor_Seq_Allele2,
  Tumor_Sample_Barcode,
  Variant_Classification,
  Variant_Type,
  aa_mutation
)]

> print(object.size(ic_min), units = 'Mb') #From 3.35G to 729M
729.5 Mb

> ic_m = read.maf(maf = ic, removeDuplicatedVariants = F) #Convert to MAF
> print(object.size(ic_min), units = 'Mb')
729.5 Mb
```
