### ISSUE TITLE
Issues of showing all the variants

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#654]
**Describe the issue**
I had an issue of showing all the variants included in my dataset. So the procedure of what I did is 1) annotate the variants using ANNOVA and input the annotated file into maftools. It seems ANNOVA removed a bunch of so-called invalid variants. Do you know if there is any way that I could include those removed variants in oncoplot? 

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
You should investigate why Annovar removed them and fix the issue or add those filtered variants back to the file.
