### ISSUE TITLE
Issues of subsetMaf()

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#655]
**Describe the issue**
Hi, I encountered a problem when applying the subsetMaf(). A few samples were removed when I subset the dataset based on a covariate column and I don't know what is the reason for that. 

**Command**
subsetMaf()

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
Could you please provide your sessionInfo and the commands?
