### ISSUE TITLE
gene alteration types in Oncogenic Signaling Pathways 

### ISSUE THREAD

**Issue by DrZhaoJie** [PoisonAlien/maftools#656]
Hi， Prof PoisonAlien
    I really enjoy your package and kept learning it. I have two questions to ask you.
(1) In this part: 9.8 Oncogenic Signaling Pathways, I want to present the gene alteration types in  oncogenic signaling pathways like this Figure 5 in the article [Oncogenic Signaling Pathways in The Cancer
Genome Atlas]. Have you ever did it in the maftools package? I would appreciate it if you could share your R code. Thank you very much!
![image](https://user-images.githubusercontent.com/55881098/105350741-913ae200-5c26-11eb-98ff-bec59dfe1776.png)
(2) In the help file, Usage OncogenicPathways(maf, pathways = NULL)
you said  pathways	Can be a two column data.frame/tsv-file with genes and correspoding pathwaymappings. 
I defined the pathways like this, but it run with an error. What's the right format of self-defined pathways? Thank you! 
![image](https://user-images.githubusercontent.com/55881098/105351449-8fbde980-5c27-11eb-94d7-8a57dd5c59c6.png)
![image](https://user-images.githubusercontent.com/55881098/105351470-964c6100-5c27-11eb-8e90-40b77e32fc60.png)

**Comment by PoisonAlien** [comment]
Hi,

1. Unfortunately I have not tried this. 

2. First column should be pathway name and second column must contain the gene names. You are almost there, just reorder the columns. Sorry for the mistake, I will correct it in the documentation. Please do let me know if you still get the error.

**Comment by DrZhaoJie** [comment]
Sorry, this is my defined pathway. As you can see, the first column was pathway name and the second column contain the gene names. It still got the same error. Maybe you may show me the right format with a picture? Thank you!
![image](https://user-images.githubusercontent.com/55881098/105363961-8f2d4f00-5c37-11eb-9c7d-da498904ae86.png)

**Comment by DrZhaoJie** [comment]
Hi, In this part: 9.8 Oncogenic Signaling Pathways. Did the mutation types of genes in the pathway include mutations, copy number changes, Fusions/Rearrangements/Epigenetic silencing? The mutation types I mentioned were from your reference article [Oncogenic Signaling Pathways in The Cancer Genome Atlas]. Thank you for your reply!

**Comment by PoisonAlien** [comment]
Hi,
I have trouble reproducing the issue. Could you please double-check if these genes exist in the maf?

**Comment by DrZhaoJie** [comment]
Hi,
Sorry and thank you. These genes didn't exist in the maf, and I changed another self-defined pathway, of which the genes partly exist in the maf. But it got the same error. Here are my Rcodes.
pathways <- read.csv("G:/test.csv", header = T)
colnames(pathways) <- c("Pathway", "Gene")
OncogenicPathways(maf = DNA01maf, pathways = pathways)
![image](https://user-images.githubusercontent.com/55881098/105380349-b93b3d00-5c48-11eb-8d16-52ef59b8ef67.png)

Besides, the input maf only covered nonSynonymous mutations in your demo. So how can I include mutation types like copy number changes, Fusions/Rearrangements/Epigenetic silencing to present altered signal pathways? It was conducted in the reference  [Oncogenic Signaling Pathways in The Cancer Genome Atlas].
Thank you very much!

**Comment by PoisonAlien** [comment]
Hi,

1. It seems that none of your provided pathways are affected, hence the error. I have pushed a commit that now emits a proper error message.

2. You can define your own list of variant classifications to be considered as non-syn while reading your maf file. Use the argument `vc_nonSyn` to provide your custom entires. They will all be considered for all the downstream functions wherever needed.

```r
my_nonsyn = c("Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site", "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del","In_Frame_Ins", "Missense_Mutation", "Fusions", "Rearrangements", "Epigenetic", "CNV")

mymaf = read.maf(maf = "my.maf", vc_nonSyn = my_nonsyn)
```

**Comment by DrZhaoJie** [comment]
Hi,

[pathway.zip](https://github.com/PoisonAlien/maftools/files/5856021/pathway.zip)
1. Sorry, I didn't agree with that. The error may come from other problems. My R code was as follows and the pathway file was attached. As you can see, genes of this pathway were mutated in PDAC samples. I also tried the other tumor types, and they all reported the same error.  Could you please check again?

```
pathways <- read.csv("G:/RTK_RAS_signalpathway.csv", header = T)
query_DNA <- GDCquery_Maf("PDAC", pipelines = "somaticsniper")
DNA01maf <- read.maf(maf = query_DNA)
sum(pathways$genes %in% DNA01maf@data$Hugo_Symbol)
#[1] 41
DNApathway <- OncogenicPathways(maf = DNA01maf, pathways = pathways)
#Error in seq.default(0.5, nrow(altered_pws), by = 1) :  wrong sign in 'by' argument

```

2. I tried the way you shared to add "Fusions", "Rearrangements", "Epigenetic", "CNV", but it seemed not to work. My R code was as follows.  I also tried the other tumor types like "COAD" "LUAD", and they all only reported SNP/SNA variation types. 
```
query_DNA <- GDCquery_Maf("SKCM", pipelines = "somaticsniper")
my_nonsyn = c("Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del","In_Frame_Ins", "Missense_Mutation", "Fusions", "Rearrangements", "Epigenetic", "CNV")
mymaf = read.maf(maf = query_DNA, vc_nonSyn = my_nonsyn)
table(mymaf@data$VARIANT_CLASS)
#SNV 
#185498 
table(mymaf@data$Variant_Classification)
#Missense_Mutation Nonsense_Mutation  Nonstop_Mutation 
#          174553             10880                65 
table(mymaf@data$Variant_Type)
#  SNP 
#185498 
```
Thank you very much!

**Comment by DrZhaoJie** [comment]
Hi, may I have your answer, please?  Really thank you very much!

**Comment by PoisonAlien** [comment]
Hi,

When I tried to run your command I get that error.

```r
query_DNA <- GDCquery_Maf("PDAC", pipelines = "somaticsniper")
Error in checkProjectInput(project) : 
  Please set a valid project argument from the column id above. Project TCGA-PDAC was not found.
```

Make sure that your MAF object is successfully created. Also, what version of the maftools package are you using? Could you please install it from GitHub and let me know if you see the same error.

2. You have to understand MAF format and what the data actually contains. If there are no mutations which are classified as `"Fusions", "Rearrangements", "Epigenetic", "CNV"`, then obviously they wont show up. Remember that TCGA MAFs only contains SNVs and INDELS and nothing else.

**Comment by DrZhaoJie** [comment]
Hi,
    Thank you for your reply. 
1. sorry. I changed the code as follows, it still represented such error.
```
setwd("G:/cor/TCGA_DNAmaf")
  pathways <- read.csv("G:/RTK_RAS_signalpathway.csv", header = T)
  query_DNA <- GDCquery_Maf("SKCM", pipelines = "somaticsniper")
  DNA01maf <- read.maf(maf = query_DNA)
  sum(pathways$genes %in% DNA01maf@data$Hugo_Symbol)
  #[1] 84
  DNApathway <- OncogenicPathways(maf = DNA01maf, pathways = pathways)
  #Error in seq.default(0.5, nrow(altered_pws), by = 1) :  wrong sign in 'by' argument
```
2. Of course. I agree with you that TCGA MAFs only contains SNVs and INDELS and nothing else.So how can I include mutation types like copy number changes, Fusions/Rearrangements/Epigenetic silencing to present altered signal pathways? It was conducted in the reference [Oncogenic Signaling Pathways in The Cancer Genome Atlas].
![image](https://user-images.githubusercontent.com/55881098/105625562-1a3f5c80-5e65-11eb-8979-46e06c5cb623.png)

Thank you very much!

**Comment by PoisonAlien** [comment]
Hi,

a. your code works for me.

```r
> DNApathway <- OncogenicPathways(maf = DNA01maf, pathways = pathways[,.(genes, Pathway)])
> DNApathway
   Pathway  N n_affected_genes fraction_affected Mutated_samples
1: RTK.RAS 85               NA                NA             411
   Fraction_mutated_samples
1:                 0.883871
```

Once again please update your package. 

b. Do you know which genes have/are `copy number changes, Fusions/Rearrangements/Epigenetic silencing`? Maftools won't figure it out for you. If you have this information, append them to the MAF file and read it again, with `vc_nonSyn` argument set to consider `copy number changes, Fusions/Rearrangements/Epigenetic silencing` in Variant_Classification columns as non-synonymous variants.
