### ISSUE TITLE
Oncoplot questions: multiple sorting and annotations

### ISSUE THREAD

**Issue by abkhan90** [PoisonAlien/maftools#657]
Hello!

Thanks again for this amazing package!

I was wondering if it is possible to sort onocoplots on more than one clinical annotation?

Also, is It possible to make the clinical annotations appear the same graphically as the somatic mutations? To clarify, clinical annotations appear as a bar at the bottom of the oncoplot; is it possible to make these appear the same as the mutations in the main body of the oncoplot? Thanks!

ABK

**Comment by PoisonAlien** [comment]
Hi,

a. You can manually order the oncoplot using `sampleOrder` argument. Use this to reorder the samples according to your sorted clinical data.

e.g,

```r
#path to TCGA LAML MAF file
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools') 
#clinical information containing survival information and histology. This is optional
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') 

laml = read.maf(maf = laml.maf, clinicalData = laml.clin)


clin_data = data.table::fread(input = laml.clin)
clin_data_sorted = clin_data[order(FAB_classification, days_to_last_followup)]

maftools::oncoplot(maf = laml, sampleOrder = clin_data_sorted$Tumor_Sample_Barcode)
```

b. No, unfortunatly annotations always appear at the bottom in their own layout. 

Hope this helps.
