### ISSUE TITLE
argument fn not work in mafSurvival() function

### ISSUE THREAD

**Issue by yikeshu0611** [PoisonAlien/maftools#660]
**argument fn not work in mafSurvival() function**
fn only exist in the argument part, so it can not save the picture as pdf

**Comment by PoisonAlien** [comment]
Hi,
Thanks for letting me know. Those arguments are not functional, and I have removed them. 
You can save the plots as you would normally by calling `pdf()` before running `mafSurvival()`.
Hope this helps.
