### ISSUE TITLE
Plot tumor mutation burden and MATH score

### ISSUE THREAD

**Issue by rajkump** [PoisonAlien/maftools#663]
Hi Anand,
  I am interested in plotting 'tumor mutation burden' and MATH score as a panels in the 'coOncoplot'. I was able to calculate 'tmb' and 'math.score' using respective functions. Could you please suggest me on how to add this to 'MAF' object or a better way to include those 'tmb' and 'math' as panels for 'coOncoplot'?
Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Hello Praveen,

1. You can add any deatils to sample information in the MAF object. In your case, if you have calculated TMB/MATH scores, you can merge the results to `clinical.data` slot of MAF object.

```r
library(maftools)
laml.maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #MAF file
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') #clinical data
laml = read.maf(maf = laml.maf, clinicalData = laml.clin)
laml_math = maftools::math.score(maf = laml, vafCol = "i_TumorVAF_WU")

# merge math scores with the clinical data
laml@clinical.data = merge(laml@clinical.data, laml_math[,.(Tumor_Sample_Barcode, MATH)], by = 'Tumor_Sample_Barcode', all.x = TRUE)

# ... do the same for TMB
```

2. Unfortunately `coOncoplot` does not allows to include any top or sidebar plots. The easiest way would be to plot two `oncoplot`s for the same set of genes with `keepGeneOrder = TRUE` and put them side by side in illustrator. You can use  `topBarData` to show TMB or MATH scores.


Hope this helps.

**Comment by rajkump** [comment]
Hi Anand,
   Great. Thanks so much for the quick reply.
Thanks,
Praveen
