### ISSUE TITLE
Request and couple of questions about mafCompare

### ISSUE THREAD

**Issue by rajkump** [PoisonAlien/maftools#665]
**Request**
Hi Anand,
   I am interested in `mafCompare` with confounding factor(s) adjustment. For instance, I would like to adjust the comparison for 'histology type' and 'subtype' of cancer. Please suggest if there is a way to do it with `mafCompare`? or any other better way?

**Question**
When performing mafCompare would you suggest using all 'mutated coding genes' or 'significantly mutated genes' like the one identified using MuSic2?

Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Hi Praveen,

1. Unfortunately I am not aware of any such tools. Also wouldn't it be easier just to compare samples belonging to same histology types?
2. You can use all the genes. SMGs would anyways be there in the top genes. Non-driver mutations wont be show up in the results as well if the frequency is too low.

**Comment by rajkump** [comment]
Hi Anand,
     Thank you so much.  For the 1st question I am trying to include all samples as one histology type sample is a small number. 
Thanks,
Praveen

**Comment by rajkump** [comment]
Hi Anand,
    Can you please let me know how to gene summary for samples? With getGeneSummary I am getting gene's and its associated mutation type but I would like sample wise data like the one used for oncoplot (like below)? Could you please suggest?


  | sample1 | sample2 | sample3 | sample4 | sample5 | sample6 | sample7 | sample8
-- | -- | -- | -- | -- | -- | -- | -- | --
Gene1 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 1
Gene2 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 1
Gene3 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 1
Gene4 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 1



Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Hi Praveen,

1. Sample size should be accounted for in Fisher's test. But unfortunately, I am not aware of any other sophisticated methods to perform DMG analysis :|

2. You can use `mutCountMatrix()` function to create such matrices. 

Hope this helps.

**Comment by rajkump** [comment]
Hi Anand,
   Thank you so much. I find plink package http://zzz.bwh.harvard.edu/plink/ for the inclusion of covariates. I will be exploring more and let you know how it goes.
Thanks,
Praveen

**Comment by PoisonAlien** [comment]
From what I have known, Plink is meant for population genetics and association studies. I don't think it suits your purpose.

**Comment by rajkump** [comment]
Hi Anand,
    Thank you. Yes it was population genetics. I was trying to borrow a statistical test to achieve DMG with covariates. Logistic regression with additive terms sounds good. Please let me know if you have any thoughts on that.
Thanks,
Praveen

**Comment by rajkump** [comment]
Hi Anand,
    Just want to let you know that I ended using firth logistic regression from the ‘logistf package.
Thanks,
Praveen
