### ISSUE TITLE
Density plot in lolipop 

### ISSUE THREAD

**Issue by vf2181** [PoisonAlien/maftools#666]
In the lollipopPlot/lollipopPlot2 function is there a chance you could possibly add a density plot option in the future? 

The sample output is depicted below:
![The-spectrum-of-APC-mutations-differs-between-classical-FAP-and-HB-patients-Lollipop-and](https://user-images.githubusercontent.com/17076598/108139511-331ae680-708e-11eb-9f73-e6b1711324b5.png)

Thanks you so much!

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the request. I will try to implement it in the coming days.

Also, just wondering what additional information does it provide?  The height of the sticks should already be conveying the same information, and the density overlay works nicely on oncogenes with mutational hotspots. For tumor suppressor genes which often lack such hotspots, the density wouldn't matter.

**Comment by vf2181** [comment]
Hey, 

Thank you so much, I really appreciate it. 
For me the density plot addition would help in the following case:

When you compare gene mutations between two different groups  (mostly tumor suppressors) you might not have hotspots, but the mutations might have higher density in a specific protein domain. 

For example, if you compare a gene from patients that responded to a certain drug to patients who did not respond you might not have hotspots, but the distribution of the mutations could be skewed towards a specific domain within the protein. And while extreme cases are easy to spot without density plot (like C terminal vs N terminal) it is easier to spot with a density plot when the differences are not extreme. 

I hope this makes sense. 

Thanks again!
