### ISSUE TITLE
problems using plotmafsummary

### ISSUE THREAD

**Issue by TomhitsJerry** [PoisonAlien/maftools#667]
Hi, i am new to maftools.
i use annovar to anno vcf file and then use maftools while at last get some errors.(my vcf file only have one sample):
![image](https://user-images.githubusercontent.com/22815603/108296441-86974c80-71d4-11eb-845a-dcfc6b10eced.png)

```
type='indel'
file='indel.exonic.upper'
var.annovar.maf = annovarToMaf(annovar =file, Center = 'NA', refBuild = 'mm10', tsbCol = 'Tumor_Sample_Barcode', table = 'refGene',sep = "\t")
write.table(x=var.annovar.maf,file=paste(type,".maf",sep=""),quote= F,sep="\t",row.names=F)
maf <- data.table::fread(paste(type,".maf",sep=""))
table(maf$Variant_Type)
var_maf = read.maf(maf =paste(type,".maf",sep=""))

```

#### error:
plotmafSummary(maf = var_maf, rmOutlier = TRUE, addStat = 'median')
Error in dcast.data.table(data = maf.con.class.summary, formula = Tumor_Sample_Barcode ~  : 
  Can not cast an empty data.table
 Warning message:
In titv(maf = maf, useSyn = TRUE, plot = FALSE) :
  Non standard Ti/Tv class: 1437TRUE
#### update solutions:
this error occurs due to there is no standard titv in maf.(need to check maf file).
  
#### error:
oncoplot(maf = var_maf, top = 30, fontSize = 12 ,showTumorSampleBarcodes = F )
Warning messages:
1: In min(x) : paras not exists in min; return Inf
#### update solutions:
this error occurs due to there is only one sample in maf.

#### error:
titv(maf = var_maf, plot = T, useSyn = FALSE)
![image](https://user-images.githubusercontent.com/22815603/108472905-4d400900-72c8-11eb-9013-28dcac45838c.png)
** why my titv plot generates like this, which seems weird? **
#### update solutions:
titv plot more than one sample's ti/tv. Because i only have one sample, so doesn't has mean、meadian or quantile，that's why my plot looks weird.

#### I wonder why this error occurs and thanks every suggestions that can help me solve this!

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay. I somehow overlooked the issue. How many samples do you have? If it is just one same, then maftools won't be of great help. It is intended to work with a cohort (>5 samples).
