### ISSUE TITLE
Feature request: remove FLAGs genes

### ISSUE THREAD

**Issue by adbeggs** [PoisonAlien/maftools#668]
Hi,

Great bit of software. Would be great if you could subset a MAF or even when you are readMaf to remove any genes highlighted by FLAGS (as you already do, but can't remove)

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Thank you and I am glad you find the tool useful. 
Sure, I will make `remove_flags` as an argument to `read.maf()`. Meanwhile, you can use `filterMaf()` to remove genes of your interest.

```r
# flags() is an internal function & is not exported. You can still access it by `:::`
flag_genes = maftools:::flags(top = 20)

laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)

#remove genes of interest
filterMaf(maf = laml, genes = flag_genes)
```

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the feature request. I have added `rmFlags` argument to `read.maf`. By default, it is set to `FALSE`.  You could set to `TRUE` and it will remove top 20 FLAGS. You can also set to a numeric value to change the default top 20 behaviour.

```r
> library(maftools)
> laml.maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #MAF file
> laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') #clinical data

# rmFlage = TRUE 
> laml = read.maf(maf = laml.maf, clinicalData = laml.clin, rmFlags = TRUE)
-Reading
-Validating
-Removing  20  FLAG genes
-Silent variants: 468 
-Summarizing
-Processing clinical data
-Finished in 0.686s elapsed (0.569s cpu) 

# or set it to a numeric value
> laml = read.maf(maf = laml.maf, clinicalData = laml.clin, rmFlags = 30)
-Reading
-Validating
-Removing  30  FLAG genes
-Silent variants: 466 
-Summarizing
-Processing clinical data
-Finished in 0.401s elapsed (0.337s cpu) 
```

Please try it from GitHub and let me know if it works for you. 
Thanks again.

**Comment by shuzoarthur** [comment]
Hi @PoisonAlien,

I'm facing the same problem as @adbeggs, thanks for the implementation of argument "rmFlags".
Could you share the source/references that you use to rank the top FLAG genes? I didn't find in the documentation.

Thanks.

**Comment by PoisonAlien** [comment]
Hi,

The flag list is from [here](https://link.springer.com/article/10.1186/s12920-014-0064-y) 
You can see the top 100 FLAGS used for filtering [here](https://github.com/PoisonAlien/maftools/blob/015a4cf8c69ba89a55a3fdcea911421509e9a198/R/summarizeMaf.R#L236). Hope this helps.
