### ISSUE TITLE
mutation signature

### ISSUE THREAD

**Issue by DrZhaoJie** [PoisonAlien/maftools#669]
Hi, thank you for your package and code. About the mutation signature, should I use maf file with [only non-synonymous nutations] or [synonymous and non-synonymous nutations] ? Thank you very much!
```


**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hello,
Ideally, you should ideally use everything (maftools does this by default).

**Comment by DrZhaoJie** [comment]
Hi, I download and read maf as the following two ways
```
query_DNA <- GDCquery_Maf("LUAD", pipelines = "somaticsniper")
(1) DNAmaf <- read.maf(maf = query_DNA)
(2) DNAallmaf <- read.maf(maf = query_DNA, vc_nonSyn = c(names(table(query_DNA$Variant_Classification))))  

```
(1) The first DNAmaf@data only includes nonsynonymous mutations as you defined defaultly
(2) The second DNAallmaf@data includes everything (synonymous and non-synonymous mutations).
So I should use the second method to analyze the mutation signature?
Thank you!

**Comment by PoisonAlien** [comment]
If you're using maftools for signature analysis you don't have to do the second step. The functions will take care of them.
But for other tools, the second step is the right one.

**Comment by DrZhaoJie** [comment]
Thank you for your clear answer!!
