### ISSUE TITLE
oncoplot: allow for arbitrary barcode order

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#67]
The lexicographic order used by `sortByAnnotation` sometimes is not what one wants, and so far putting samples in the right order involves hacks (creating a "temporary" column in the annotation which will force the right order).

**Comment by PoisonAlien** [comment]
Hi,
I guess for this, best way is to fetch annotation order from user as an argument and maintain that order. Is this what you meant, a custom ordering of annotation levels ?

**Comment by lbeltrame** [comment]
Either that, or an option along the lines of `sampleOrder=c("foo", "bar", "baz")`

**Comment by PoisonAlien** [comment]
Hmm.. Got it.

**Comment by PoisonAlien** [comment]
Hi,
I have added another argument to oncoplot (`annotationOrder`) where you can specify the order of annotations and it will maintain that order. You can try and see if this is something you wanted.

**Comment by crazyhottommy** [comment]
Hi,

I have the same question. 


```r
SCLC_meta
# A tibble: 16 x 5
   Tumor_Sample_Barcode patient smoking gender response
                  <chr>   <chr>   <chr>  <chr>    <chr>
 1            Pa01_pret    Pa01     yes      M       CR
 2           Pa01_recur    Pa01     yes      M       CR
 3            Pa02_pret    Pa02     yes      M       PR
 4           Pa02_recur    Pa02     yes      M       PR
 5            Pa03_pret    Pa03     yes      M       CR
 6            Pa03_mets    Pa03     yes      M       CR
 7            Pa04_pret    Pa04      no      F       PR
 8           Pa04_recur    Pa04      no      F       PR
 9            Pa04_mets    Pa04      no      F       PR
10            Pa05_pret    Pa05      no      M       CR
11           Pa05_recur    Pa05      no      M       CR
12           Pa06_prett    Pa06     yes      M       PR
13     Pa06_prett-chemo    Pa06     yes      M       PR
14            Pa06_mets    Pa06     yes      M       PR
15            Pa07_pret    Pa07     yes      M       PR
16           Pa07_recur    Pa07     yes      M       PR

oncoplot(maf = SCLC.maf, showTumorSampleBarcodes = T, top = 10,drawRowBar = T, drawColBar = T, removeNonMutated = F, annotationDat = SCLC_meta, clinicalFeatures = c("patient", "smoking", "gender", "response"), 
annotationOrder = SCLC_meta$Tumor_Sample_Barcode)
```

it is not ordering by the sample, how do I specify it?

Thanks!

**Comment by PoisonAlien** [comment]
Hi Ming,

`annotationOrder` would take levels of first clinicalFeatures. For example in your case,

```r
oncoplot(maf = SCLC.maf, showTumorSampleBarcodes = T, top = 10,drawRowBar = T, drawColBar = T, removeNonMutated = F, annotationDat = SCLC_meta, clinicalFeatures = c("patient", "smoking", "gender", "response"), 
annotationOrder = c("Pa01", "Pa02", "Pa03", "Pa04", "Pa05", "Pa06", "Pa07"))
```
Let me know if this works.

**Comment by crazyhottommy** [comment]
Hi,

I tried but it is not ordering as Pa01 Pa02...

even it works, I want to order the samples within Patients. e.g. Pa04_pre, Pa04_recur, Pa04_mets. if it is ordered alphabetically, it will be Pa04_met, Pa04_pre and Pa04_recur.

Thanks.
Tommy

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay, I have added an argument `sampleOrder` to oncoplot which should do the trick. Can you try it and let me know ?

**Comment by lbeltrame** [comment]
I'll make sure to check it, thanks.

**Comment by crazyhottommy** [comment]
confirmed that it is working. Thanks!

**Comment by PoisonAlien** [comment]
Thank you both for the help.
