### ISSUE TITLE
Oncoplot and Gisticplot -setting cell sizes 

### ISSUE THREAD

**Issue by clersdom** [PoisonAlien/maftools#670]
Hi @PoisonAlien 

I would like to align an oncoplot and a gisticplot for the same samples but the sizes of the cells for each gene and cytoband altered appear with different sizes in the respective plots. 
Is there an option already for this?

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay. By gistic plot, do you mean `gisticOncoPlot`? 
I guess if you're having a different number of rows in both the plots it will affect the overall plot layout and cell sizes.

**Comment by clersdom** [comment]
Hi, yes the `gisticOncoplot`. 

It would be great to fix the cell sizes somehow but thanks for your response!

**Comment by PoisonAlien** [comment]
Hi,
It is not possible to have the same plot scales for the data with different dimensions. You could try to align them in `Illustrator` for better results.
