### ISSUE TITLE
SNV and indel all mutation types.

### ISSUE THREAD

**Issue by DrZhaoJie** [PoisonAlien/maftools#672]
Hi, I downloaded and read the maf file with the following code for 20 cancer types. All of them had no indel mutations. It was unreasonable. I want to download files with both SNV and indel all mutation types. Where was I wrong?

`query_DNA <- GDCquery_Maf("ACC", pipelines = "somaticsniper")
`

**Comment by PoisonAlien** [comment]
Hi,
This is not really related to `maftools`. Maybe be open an issue on [TCGAbiolinks](https://github.com/BioinformaticsFMRP/TCGAbiolinks)?

CC: @tiagochst
