### ISSUE TITLE
add annotationOrder to coOncoplot [FR]

### ISSUE THREAD

**Issue by Tato14** [PoisonAlien/maftools#676]
Allow `coOncoplot` to reorder `clinicalFeatures1` and `clinicalFeatures2` with `annotationOrder` the same way that `oncoplot` does.
Thanks :smile:

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the FR. I have added `annotationOrder1` and `annotationOrder2` for the custom ordering of levels in `clinicalFeatures`. Please do test it and let me know.  Hope this helps.

**Comment by Tato14** [comment]
Works great! Thanks!
