### ISSUE TITLE
updating pfam domain information for lollipopPlot

### ISSUE THREAD

**Issue by bkinnersley** [PoisonAlien/maftools#677]
Hello,

I am encountering the following error when trying to create lollipopPlots for a small number of genes (SLAIN1, MAP3K21, NBPF19, NPIPB6):
"Error in lollipopPlot(maf = input, gene = "SLAIN1", AACol = "HGVSp", showMutationRate = TRUE, showDomainLabel = FALSE, labelPos = 'all', labPosAngle =0, printCount=TRUE, cBioPortal=FALSE)
      Structure for protein SLAIN1 not found"

As far as I can see this is due to the gene HGNC symbol not being present in the "protein_domains.RDs" file (https://github.com/PoisonAlien/maftools/blob/master/inst/extdata/protein_domains.RDs). I had a few questions about this:
1. Would it be possible to get instructions for how a user could update this protein_domains.RDs file to include pfam domain information for currently missing genes?
2. Could an option be added to allow pfam domain information to be added "on the fly" in the lollipopPlot command? 
3. Could an option be added in lollipopPlot to not require domain information if it is missing (e.g. just plot mutations not domains, rather than exit with an error message)?

Thanks very much!

**Comment by PoisonAlien** [comment]
Hi,

1. Yes, you can update the `RDs` file for your protein info and save it back. It should work. 
You can check the RDs for the file format. It has several columns but many of them are not necessary. Below is an example for adding `SLAIN1` structure to the database. Structure obtained from [cBioPortal](https://bit.ly/2O2yAwx)


```r
domain_data_src = system.file('extdata', 'protein_domains.RDs', package = 'maftools')
domain_data = readRDS(file = domain_data_src)

# your  SLAIN1 protetin structure (refseq.ID column is not necessary)
slain_motif = data.table::data.table(
  HGNC = "SLAIN1",
  aa.length = 568,
  Start = 187,
  End = 568,
  Label = "SLAIN",
  refseq.ID = "NM_001242868"
)

print(slain_motif)
HGNC aa.length Start End Label    refseq.ID
1: SLAIN1       568   187 568 SLAIN NM_001242868

# Add the protein structure to database
domain_data = data.table::rbindlist(
  l = list(domain_data, slain_motif),
  use.names = TRUE,
  fill = TRUE
)

# save back the database
saveRDS(object = domain_data, file = domain_data_src)

lollipopPlot(maf = your_maf, gene = "SLAN1")
```

2. I can add an argument for custom user input. The only reason I had not done it because there is no standard data format. Can you share an example pfam format?
3. For this at-least protein length should be known. 

In any case, you can always open an issue with missing protein structure - I am happy to update the database. (See #255 #616 )

**Comment by bkinnersley** [comment]
Hello,

Thanks very much for sending these detailed instructions! From these I was able to update pfam domain information for SLAIN1 as well as other transcripts and produce lollipopPlots. In fact as I have been annotating mutations to ensembl canonical transcripts rather than to refseq this provided a good opportunity to check that all domain/protein length annotations were consistent with these canonical ensembl transcripts. 

For question 2 am not sure if this would be a standard pfam format but the information specified in your "slain_motif" example should be reasonable to provide (as long as the user is clear that the transcript/domain definitions of course have to be consistent with those in the "AACol" specified in the lollipopPlot)?

Thanks again

**Comment by PoisonAlien** [comment]
Thanks for checking. I will add an additional argument for manual domain specification in upcoming BC release. I am closing the issue for now. Please feel free to comment if needed.

**Comment by bkohrn** [comment]
Just wanted to check...has there been any progress on the manual domain specification?

**Comment by PoisonAlien** [comment]
Hi,
I have not included such an option. Meanwhile, if you have a protein structure of interest, let me know, I am happy to include it in the database.

**Comment by for8ver3** [comment]
hi, whilst updating the domains manually one by one (save after each one), is there a way of removing an existing domain? Thanks.
