### ISSUE TITLE
Non agreement between lollipop plot and maf summary

### ISSUE THREAD

**Issue by beginner984** [PoisonAlien/maftools#678]
Hello @PoisonAlien 

I looked at a gene in my maf which looks like

```
> head(getGeneSummary(laml))
   Hugo_Symbol Missense_Mutation Nonsense_Mutation Splice_Site total MutatedSamples
1:        NAV3                 5                 2           1     8              8
   AlteredSamples
1:              8
>
```

You are seeing 

There are 8 counted in the table above. 5 missense, 2 nonsense, and 1 splice site mutation

But lollipop plot shows 7 like below

```
> lollipopPlot(maf =laml, gene = 'NAV3', AACol = 'aaChange', showMutationRate = TRUE)
Removed 1 mutations for which AA position was not available
>
```

Thank you in advance

**Comment by PoisonAlien** [comment]
Hi,
Your `Splice_Site` mutation has no `aaChange` information. Splice site variants are at the coding exon boundaries (2/3 base pairs). Usually, amino acid changes will not be available for such variants.
