### ISSUE TITLE
GISTIC parser only includes samples with aberrations in the total

### ISSUE THREAD

**Issue by lbeltrame** [PoisonAlien/maftools#68]
The title is a bit convoluted, but let's explain with an example:

. Let's imagine a cohort of 34 samples with GISTIC data
- Of these, 24 have gains identified in `amp_genes_conf_xx.txt` and the others haven't
- We load the results file and the amplified file only
- The percentages indicated by the plots are relative to 24 samples and not 34

That's because loading samples does not count those 10 samples which don't have any gain reported by GISTIC (but they are in the file, they're simply all zeros), which is not what I'd expect. I'd expect even the samples with no changes to be counted for the percentages of alteration.

**Comment by PoisonAlien** [comment]
Hi,
What version of maftools are you using ? and is this in oncoplot or gisticOnocoplot ?

**Comment by lbeltrame** [comment]
At the time when I saw this, the latest stable released through Bioconductor. The issue I'm seeing shows up in the plot (`gisticPlot`), but it's visible just by reading the GISTIC file and inspecting the resulting object.

**Comment by lbeltrame** [comment]
Looks accurate with recent master. Closing.
