### ISSUE TITLE
mafCompare() or clinicalEnrichment() using pathways instead of genes [FR]

### ISSUE THREAD

**Issue by Tato14** [PoisonAlien/maftools#681]
Group genes in specific pathways and perform comparison with `mafCompare()` or `clinicalEnrichement()`

**Comment by PoisonAlien** [comment]
Nice idea. I will see what I can do.

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay; I have been swamped with work. 
I have pushed the changes, and I would appreciate it if you could test them. `mafCompare` and `clinicalEnrichment` both now have an argument `pathways` which will summarize pathways before comparing. 

Ex:
 `mafCompare()`
```r
luad = TCGAmutations::tcga_load(study = "LUAD")
esca = TCGAmutations::tcga_load(study = "ESCA")

res <- maftools::mafCompare(m1 = LUAD, m2 = sarc, m1Name = 'Lung', m2Name = 'Sarcoma', minMut = 5, pathways = TRUE)
maftools::forestPlot(pt.vs.rt)
```

![image](https://user-images.githubusercontent.com/8164062/112297432-2f364180-8c96-11eb-949c-09e5db842d91.png)

`clinicalEnrichment()`
```r
res = maftools::clinicalEnrichment(maf = esca, pathways = T, clinicalFeature = "primary_pathology_histological_type")
```

Thanks for the FR.

**Comment by Tato14** [comment]
Hi!

Thanks for the great feature! I was wondering if would be possible to add custom pathways the same way you use `pathways` in `oncoplot` (df with gene and pathway).
