### ISSUE TITLE
Oncoplot Bar Charts Lacking Axes Titles

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#682]
A peer reviewer requested that the bar charts at the top and to the right have proper axes titles such as Number of Variants (top bars) and Number of Samples (right bars). Could these be made defaults?

**Comment by PoisonAlien** [comment]
I can do it. 
Also, wouldn't it be easier to add these details in illustrator?

**Comment by DarioS** [comment]
Yes, I use Inkscape. But it would be nice to save a step and have something satisfying to peer reviewers automatically.

**Comment by PoisonAlien** [comment]
I have pushed the changes. Let me know if it works.
By default, it will print `TMB` and `No. of samples` for top and right bar plots respectively.

**Comment by merckey** [comment]
Does this fix label the right bar to "No. of samples" even if the qvlaue from mutsig is provided as the rightBarData?
See https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/oncoplots.html,
barplot 0.4
Thanks.
