### ISSUE TITLE
OncodriveCLUST has been superseeded by OncodriveCLUSTL, could you update the oncodrive?

### ISSUE THREAD

**Issue by Feirun777** [PoisonAlien/maftools#684]
**Describe the issue**
A clear and concise description of what the issue is.

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue. Unfortunately, I have no immediate plans to update it. Sorry.
