### ISSUE TITLE
Bug in 'OncogenicPathways' function

### ISSUE THREAD

**Issue by huangwb8** [PoisonAlien/maftools#685]
OncogenicPathways not working
```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
OncogenicPathways(maf = laml)
```
The error is as following:
```
Error in graphics::layout(p, ...) : ...
```

**Comment by huangwb8** [comment]
Change to "lo = layout(matrix(c(1,2,3), 1, 3, byrow =F), widths = panelWidths)" in oncopathway.R would help. It seemed to be systematically problem of R instead of oncopathway.R

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. 
I have trouble reproducing the error. Could you please post your `sessionInfo`? I suspect it must be due to conflict between`graphics::layout` and `plotly::layout` (?)
