### ISSUE TITLE
Questions about the variant classification in maftools

### ISSUE THREAD

**Issue by lincj1994** [PoisonAlien/maftools#686]
```
            3'UTR           5'Flank             5'UTR   Frame_Shift_Del 
              250                13               133               487 
  Frame_Shift_Ins               IGR      In_Frame_Del      In_Frame_Ins 
              354                 1               651                92 
           Intron Missense_Mutation Nonsense_Mutation  Nonstop_Mutation 
             8793              6385               517                 2 
              RNA            Silent       Splice_Site           Unknown 
              278              3062               225               181
```
Here is a tab delimited MAF file. I created a oncoplot based on this maf using maftools and the output oncoplot presented the variant classification of Frame_Shift_Del, Frame_Shift_Ins, In_Frame_Del, In_Frame_Ins, Missense_Mutation, Nonsense_Mutation, and Splice_Site. While I found that most literature presented the oncoplot only with variant classification of Missense, Truncating, and InDel. I think that these literatures might consider missense = missense, truncating = nonsense + frameshift insertion + frameshift deletion, and in-frame indel = in-frame insertion + in-frame deletion. But how to deal with splice-site mutation? I wonder if those literatures have also reclassified it into missense, truncating, or in-frame indel mutations according to Reference_Allele and Tumor_Seq_Allele2 or just ignored it. Also, I think it will be helpful to add a parameter to oncoplot function, which can control the combination of these variant classifications to show a more concise oncoplot.
Thanks.

**Comment by PoisonAlien** [comment]
Hi,
I am not sure which literature you're referring to. But in general, `Splice_Sites` are truncating mutations.  
`lollipopPlot` function has an argument `cBioPortal` which [categorizes](https://github.com/PoisonAlien/maftools/blob/master/R/lollipopPlot.R#L130-L133) MAF `variant_classififcations` into `Truncating` `Missense` and `In_frame`. 
If it helps, I can implement the same in `oncoplot`.

**Comment by lincj1994** [comment]
Hi @PoisonAlien 
Thanks for your reply! I think it will be helpful to add such an argument to oncplot. And here is one of the literatures: Razavi P, Chang MT, Xu G, et al. The Genomic Landscape of Endocrine-Resistant Advanced Breast Cancers. Cancer Cell. 2018;34(3):427-438.e6. doi:10.1016/j.ccell.2018.08.008.

**Comment by PoisonAlien** [comment]
Hi 
Thanks for the reference. I have pushed the changes to `onocplot` which will classify existing `Variant_Classificatios` into `In-frame, Missense, or truncating`. 

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')
laml <- read.maf(maf = laml.maf, clinicalData = laml.clin)

# Set cBioPortal = TRUE for the changes
oncoplot(maf = laml, cBioPortal = TRUE, legend_height = 2, top = 10)
```

![image](https://user-images.githubusercontent.com/8164062/112464015-3ecf8c00-8d63-11eb-8233-c8e06746058e.png)

Note that, these changes are hard-coded. i.e, following changes are made:

```r
vc    vc.cbio
1:  Nonstop_Mutation Truncating
2:   Frame_Shift_Del Truncating
3: Missense_Mutation   Missense
4: Nonsense_Mutation Truncating
5:       Splice_Site Truncating
6:   Frame_Shift_Ins Truncating
7:      In_Frame_Del   In-frame
8:      In_Frame_Ins   In-frame
```

If you would like to make your own custom changes, easiest way would be change them in MAF file itself before processing it with `maftools`.  Hope this helps.
