### ISSUE TITLE
Feature Reqest for Comparative Oncoplots

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#687]
It would be nice to easily be able to place sample groups side-by-side and see percentages in each group. An illustrative example is

![image](https://user-images.githubusercontent.com/631218/112416269-76e1c980-8d79-11eb-960d-d2f44c6e37f6.png)

It's hard to get the device width right so the boxes have equal width if two separate plots are created, so automation is desired.

**Comment by PoisonAlien** [comment]
Thanks for the FR. It is doable but would require quite a bit of code change. I will implement it when I have enough time. Meanwhile, you can split your maf with `subsetMaf` into two cohorts `Responders` and `Non-responders`, and plot it with `coOncoplot`. Only caveat is it only supports two groups.

**Comment by DarioS** [comment]
I was unaware of coOncoplot. Perhaps it should be in See Also section of oncoplot's documentation. They seem related functions.
