### ISSUE TITLE
sample size in mafCompare

### ISSUE THREAD

**Issue by marcoreuszs** [PoisonAlien/maftools#694]
Hello, 

Thanks for your contribution to this package. I have been thinking about a problem when using mafCompare. MafCompare is to calculate the number of mutated genes in two MAFs, and then identify the differentially mutated genes based on Fisher's exact test, whether the sample size of two groups will have an impact on the results. Recently, when comparing the differentially mutated genes in the high and low immune groups, the sample size ratio of the two groups was 3:1, and some problems were found in the results.

Therefore, is there a regulation on the sample size? For example, the sample size of the two groups is not significantly different.
Looking forward to your reply. Thank you.

**Comment by PoisonAlien** [comment]
Hi,
AFAIK, it should not affect much. 
You could also try the chi-square test (if your sample size is large enough).

**Comment by marcoreuszs** [comment]
> Hi,
> AFAIK, it should not affect much.
> You could also try the chi-square test (if your sample size is large enough).

**Comment by marcoreuszs** [comment]
> Hi,
> AFAIK, it should not affect much.
> You could also try the chi-square test (if your sample size is large enough).

OK! thank you very much

**Comment by marcoreuszs** [comment]
> Hi,
> AFAIK, it should not affect much.
> You could also try the chi-square test (if your sample size is large enough).
