### ISSUE TITLE
How to get list of all mutated genes ?

### ISSUE THREAD

**Issue by arpit20328** [PoisonAlien/maftools#695]
**Describe the issue**
A clear and concise description of what the issue is.

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
Please do check the vignette. It has all the basic usage and details.

e.g, for the `laml` MAF object.
```r
#Shows sample summry.
getSampleSummary(laml)
#Shows gene summary.
getGeneSummary(laml)
#shows clinical data associated with samples
getClinicalData(laml)
#Shows all fields in MAF
getFields(laml)
```
