### ISSUE TITLE
Oncoplot incomplate plot

### ISSUE THREAD

**Issue by NurgulKaryagis** [PoisonAlien/maftools#697]
**Describe the issue**
I am trying to plot oncoplot. I have no clinical data. I take following error

**Command**

```r
mafBB=read.maf('BB.vep.maf')

oncoplot(mafBB)

Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf

```

**Session info**

```r
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=tr_TR.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=tr_TR.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=tr_TR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=tr_TR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.6.05

loaded via a namespace (and not attached):
[1] compiler_4.0.5     Matrix_1.3-2       tools_4.0.5        RColorBrewer_1.1-2 survival_3.2-10    splines_4.0.5      grid_4.0.5        
[8] data.table_1.14.0  lattice_0.20-41  
```

**Comment by PoisonAlien** [comment]
Hi,

What part of the plot is incomplete? Could please show the plot if possible?

**Comment by NurgulKaryagis** [comment]
![88eda508-8135-4a67-9761-542cf38d928f](https://user-images.githubusercontent.com/35428800/115713148-5c057380-a37e-11eb-8141-3c19d96862dd.png)

**Comment by PoisonAlien** [comment]
Hi,
There is no error here. You can ignore the warning. Also note that you have just one sample, `oncoplot` works the best when there are more that a few samples.

**Comment by NurgulKaryagis** [comment]
I merged my all samples and this is the result. It does not show mutations as I see. Does I interpret result wrong?


![458493ae-0c34-475b-8981-895bb5b84d03](https://user-images.githubusercontent.com/35428800/115715905-4776aa80-a381-11eb-9f41-04505b7ec3fe.png)

**Comment by PoisonAlien** [comment]
Hi,
It seems that every gene is mutated more than once in every sample, hence the `Multi_Hits`
I think you have not done the post annotation filtering. You will probably have remove SNPs and low QC variants.
