### ISSUE TITLE
lollipopPlot x-axis error?

### ISSUE THREAD

**Issue by kguion1** [PoisonAlien/maftools#698]
I am trying to use the lollipopPlot on the GENIE data. I have previously used this function with no issues on TCGA. When I plot the lollipopPlot for KRAS, the labels of the mutations do not match the x-axis. Thanks!

![image](https://user-images.githubusercontent.com/42556019/115793729-80af1a80-a381-11eb-96e5-ab54f6260f56.png)

**Comment by PoisonAlien** [comment]
Hi,
This is weird. Could you run the same function with `printCount = TRUE` and check the `pos` for `T20M`?

**Comment by kguion1** [comment]
![image](https://user-images.githubusercontent.com/42556019/115840443-8a13a380-a3d0-11eb-8d80-35fe41bf039a.png)

**Comment by PoisonAlien** [comment]
Is it possible to share a reproducible example?

```r
x = maftools::subsetMaf(maf = colorectal_maf, genes = "KRAS")
saveRDS(object = x, file = "kras_maf.RDs")
```

You can attach `kras_maf.RDs` here.

**Comment by kguion1** [comment]
[kras_maf.zip](https://github.com/PoisonAlien/maftools/files/6363771/kras_maf.zip)

**Comment by PoisonAlien** [comment]
Works fine on my system.

![image](https://user-images.githubusercontent.com/8164062/115841934-983be100-a41d-11eb-8157-aa129c8ebd7d.png)

What version are you using? Also how does the plot looks when you save it to a file?

**Comment by kguion1** [comment]
This is the plot when saved to a pdf. 

`pdf("GENIE_results/GENIE_v9/maf_analysis_results/lollipop_colorectal_maf.pdf")`

`lollipopPlot(maf = colorectal_maf, gene = 'KRAS', 
             labelPos="all", labPosSize = 0.9, labPosAngle = 90, titleSize = c(0.8,0.8), repel=TRUE, cBioPortal = FALSE  )`

`dev.off()`


![image](https://user-images.githubusercontent.com/42556019/115888796-2d33df80-a408-11eb-9caf-4f026c223fff.png)

**Comment by kguion1** [comment]
maftools_2.6.05

**Comment by kguion1** [comment]
I have been playing with the arguments and the error only occurs when `repel = TRUE`. I will not use this argument for now. Thank you for all your help. A final note, when I was debugging, I tried to use the `plotProtein` function and my system could not find this function as part of the maftools package, even when explicitly specifying it was part of maftools.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for letting me know. `repel = TRUE` has been deprecated. I will remove it in future updates. 
`plotProtein` is available on the GitHub version of the `maftools` and should be available on BioConductor in the upcoming release. Meanwhile, you can install it from GitHub with,

```r
BiocManager::install("PoisonAlien/maftools")
```

**Comment by kguion1** [comment]
OKay, great thank you!
