### ISSUE TITLE
Oncoplot missing center panel

### ISSUE THREAD

**Issue by kguion1** [PoisonAlien/maftools#699]
The oncoplot is missing the center panel. I tried saving to a larger pdf file and it is still missing. 
![image](https://user-images.githubusercontent.com/42556019/115833682-2d60ba80-a3c9-11eb-94f8-e5bc6d4b9115.png)

**Comment by PoisonAlien** [comment]
Hi,
Your sample size quite large, so the white gap between the columns is more prominent. Try changing the `sepwd_samples` to lower values. 

e.g,
```r
oncoplot(maf = laml, sepwd_samples = 0.1)
```

**Comment by kguion1** [comment]
Hi, thanks for the suggestion. Unfortunately the problem persists

**Comment by kguion1** [comment]
I also tried with only Male (so half the samples) with the same issue. The oncoplot function does work correctly with another dataset so I do not think there is an issue with my system necessarily. 

![image](https://user-images.githubusercontent.com/42556019/115839927-00fc6c80-a3d0-11eb-8d4d-a9ec5f85fd4c.png)

**Comment by PoisonAlien** [comment]
Even with `sepwd_samples = 0.001`?
In that case, `oncoplot` might not be a good visualization option for such large data.

**Comment by kguion1** [comment]
Yes even with 0.001. Okay, no worries! Thank you for all your work and quick response on this package, I've used a lot of the tools!
