### ISSUE TITLE
use to target-seq or WEX 

### ISSUE THREAD

**Issue by shirleydaidai** [PoisonAlien/maftools#7]
Hi,
This tool is really very helpful.
I wonder if it need to do gene length correction when I use oncoplot for my target sequencing data or exom sequencing data.
Thanks
Shirley

**Comment by PoisonAlien** [comment]
Hi,

I'm glad you found this tool useful. For oncoplots, no need for any length correction. You can plot them as it is. It doesn't matter which sequence source (can be WXS, WGS, Amplicon, etc) was used to detect variant.
