### ISSUE TITLE
oncoplot 

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#700]
**Describe the issue**
A clear and concise description of what the issue is.
I used oncoplot to draw the waterfall plot with the following code. I included all the variants and I checked that every sample had at least one variant. However, the oncoplot with the title of 'Altered in 92% of the samples'. Do you have an idea of what is the problem here? I would expect the alteration rate to be 100%. 

Thank you for your help.

**Command**
Please post your commands and the output (errors or any unexpected output)
advanced= read.maf(maf = var.annovar.maf,clinicalData = clinicalData,removeDuplicatedVariants = FALSE,useAll = TRUE,vc_nonSyn=vcNames) 
oncoplot(maf = advanced,top = 15,draw_titv = TRUE,gene_mar = 6,fontSize = 0.5,colors = vc_cols)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,

The % is estimated based on the mutations that are included in the `oncoplot`. Try with `removeNonMutated = FALSE`, it should show the samples with no mutations.

**Comment by xiw588** [comment]
Hi, Thank you for your suggestions. I tried but this still give me the # % < 100% and I actually checked the samples, all of them have at least one mutation including all the types. Any other possibility to solve this? Thank you!

**Comment by PoisonAlien** [comment]
Could you please post your exact commands and the `oncoplot`?

**Comment by xiw588** [comment]
Sure, using this code, silent, unknown mutations, etc were included in the figure as well but still got the percentage less than 100%. 

oncoplot(maf = advanced,top = 15,draw_titv = TRUE,gene_mar = 6,fontSize = 0.5,colors = vc_cols,removeNonMutated = TRUE)

**Comment by PoisonAlien** [comment]
So are you sure that you dont see any empty columns in the plot? Is it possible to attach the plot? You can crop out the gene names and other sensitive info. if you would like.

**Comment by xiw588** [comment]
<img width="698" alt="Screen Shot 2021-04-27 at 11 53 32 AM" src="https://user-images.githubusercontent.com/31411260/116272795-321dc980-a74f-11eb-9c5d-cd91bf707750.png">

**Comment by PoisonAlien** [comment]
Hi,
Your command should be,

```r
oncoplot(maf = advanced,top = 15,draw_titv = TRUE,gene_mar = 6,
fontSize = 0.5,colors = vc_cols,removeNonMutated = FALSE)
```

You have the `removeNonMutated = TRUE` in your command. Let me know if you still don't see any empty columns. I am pretty sure there are samples with no variants in these top 15 genes.

**Comment by xiw588** [comment]
Hi, I see! So the percentage of just for the top 15 genes rather than all, right? I thought this is the percentage for all mutations...

**Comment by PoisonAlien** [comment]
Yes, the stats in the title are only for the genes included in the plot.
