### ISSUE TITLE
Lollipop Plot "structure for protein "-----" not found"

### ISSUE THREAD

**Issue by ConDem94** [PoisonAlien/maftools#701]
Dear all,

I am trying to plot the amino acid changes of multiple somatic mutations on a single gene. Hugo symbol: **FAM205A**.

Although, when I try to run it, it gives the following error message:
"Structure of protein FAM205A not found.

I'm assuming there is no data on the structure of this protein in the current version of maftools. How can this be resolved? 

Thank you!

**Command:**
```
lollipopPlot(maf = maf_file, gene = 'FAM205A', AACol = 'HGVSp_Short', labelPos = 'all', legendTxtSize = 1.5, 
             showMutationRate = TRUE,showDomainLabel = F,pointSize = 3, labPosSize = 1.5,labPosAngle = 45, cBioPortal = T,
             defaultYaxis = T)
```

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue. I have updated the database with `FAM205A`. Please install the tool from GutHub and let me know if it works.

**Comment by ConDem94** [comment]
Hello,

I installed Github maftools again and it doesn't find the structure of FAM205A. Do I have to install just the function lollipopPlot()?

Sorry I'm fairly new to this.

Thank you!

**Comment by PoisonAlien** [comment]
No problem. You will have to run the below command.

```r
BiocManager::install("PoisonAlien/maftools")
```

Restart your R after the successful installation for a good measure. Updated maftools version should be `2.7.41`

**Comment by ConDem94** [comment]
Hello,

I have trouble installing the latest version of maftools (2.7.41) and I think it's because my Bioconductor package is out of date. I will try and update maftools and will then run the function. Thank you.

**Comment by PoisonAlien** [comment]
Hi,
`maftools` has no great deal of dependencies. It should fairly be simple.
What errors are you getting? Are you using Windows? 
If you can paste the error messages, I will be able to help.

In any case, if the problem persists, temporary solution would be to just download and replace the protein database.

```r
domain_data_src = system.file('extdata', 'protein_domains.RDs', package = 'maftools')
download.file(url = "https://github.com/PoisonAlien/maftools/raw/master/inst/extdata/protein_domains.RDs", 
destfile = domain_data_src)
```

**Comment by ConDem94** [comment]
Hi,

So I'm using windows, RStudio version (1.3.1093)

When I try to run BiocManager::install("PoisonAlien/maftools") this pops up:

BiocManager::install("PoisonAlien/maftools")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.10 (BiocManager 1.30.12), R 3.6.3 (2020-02-29)
Installing github package(s) 'PoisonAlien/maftools'
Downloading GitHub repo PoisonAlien/maftools@HEAD
√  checking for file 'C:\Users\cd317\AppData\Local\Temp\Rtmpq0flnJ\remotes48142db2452\PoisonAlien-maftools-f777816/DESCRIPTION' (855ms)
-  preparing 'maftools': (1.4s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (947ms)
-  checking for empty or unneeded directories
-  building 'maftools_2.7.41.tar.gz'
   
* installing *source* package 'maftools' ...
** using staged installation
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/cd317/R/R-PORT~1/App/R-PORT~1/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I"C:/Users/cd317/R/Library/Rhtslib/include" -I"C:/Users/cd317/R/Library/zlibbioc/include"        -O3 -Wall  -std=gnu99 -mtune=core2 -c ntcounts.c -o ntcounts.o
c:/Rtools/mingw_32/bin/gcc  -I"C:/Users/cd317/R/R-PORT~1/App/R-PORT~1/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I"C:/Users/cd317/R/Library/Rhtslib/include" -I"C:/Users/cd317/R/Library/zlibbioc/include"        -O3 -Wall  -std=gnu99 -mtune=core2 -c somaticfreq.c -o somaticfreq.o
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o maftools.dll tmp.def ntcounts.o somaticfreq.o C:/Users/cd317/R/Library/Rhtslib/usrlib/i386/libhts.a -L/lib/i386 -lcurl -lrtmp -lssl -lssh2 -lcrypto -lgdi32 -lz -lws2_32 -lwldap32 -lwinmm -lidn -LC:/Users/cd317/R/R-PORT~1/App/R-PORT~1/bin/i386 -lR
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lcurl
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lrtmp
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lssl
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lssh2
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lcrypto
C:/Rtools/mingw_32/bin/../lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lidn
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'maftools'
* removing 'C:/Users/cd317/R/Library/maftools'
Old packages: 'cluster', 'Matrix', 'mgcv', 'nlme', 'survival'
Update all/some/none? [a/s/n]: 

Now I don't have access to maftools as I can't download it. Is there a way to fix this? Thanks!

**Comment by PoisonAlien** [comment]
Ah, I see. For now, you could just install the package from Bioconductor again and replace the protein database.

```r
BiocManager::install("maftools")

# restart R 

domain_data_src = system.file('extdata', 'protein_domains.RDs', package = 'maftools')
download.file(url = "https://github.com/PoisonAlien/maftools/raw/master/inst/extdata/protein_domains.RDs", 
destfile = domain_data_src)
```

Let me know if this works.

**Comment by ConDem94** [comment]
Hello,

Thank you for your quick response.

I ran the aforementioned code, and when I try to run lollipopPlot() it gives this error:

**Error in readRDS(file = gff) : error reading from connection**

**Comment by PoisonAlien** [comment]
Did you restart your R? It should work.

**Comment by ConDem94** [comment]
Yes, I restarted R after running BiocManager::install("maftools"). 

I then ran: 

domain_data_src = system.file('extdata', 'protein_domains.RDs', package = 'maftools')
download.file(url = "https://github.com/PoisonAlien/maftools/raw/master/inst/extdata/protein_domains.RDs", 
destfile = domain_data_src)

but it still gives the same error message when I try to run this:

lollipopPlot(maf = all_genes_ged_maf, gene = 'FAM205A', AACol = 'HGVSp', labelPos = 'all', legendTxtSize = 1.5, 
             showMutationRate = TRUE,showDomainLabel = F,pointSize = 3, labPosSize = 1.5,labPosAngle = 45, cBioPortal = T,
             defaultYaxis = T)

Error in readRDS(file = gff) : error reading from connection

**Comment by PoisonAlien** [comment]
Ok, that's no good then. Here are possible solutions.

1. Restart again and try once more.
2. If the above doesn't work, would you mind updating your R to a newer version and installing `maftools` from GitHub? You may also want to update `Rtools` package to a newer version.

Sorry, I do not have much experience with the Windows system, so I have trouble guessing the issue.

**Comment by ConDem94** [comment]
Hello,

I am in the process of updating R/RStudio. I will let you know if this works! Thank you.
