### ISSUE TITLE
How to change the color of the TiTv plot using oncoplot.

### ISSUE THREAD

**Issue by lincj1994** [PoisonAlien/maftools#702]
Hi. I dont know if the maftools oncoplot can change the color of TiTv.

**Comment by PoisonAlien** [comment]
Hi,

I have added a new argument `titv_col` to the oncoplot which should enable custom color codes. Please install the tool from GitHub for the updated version.

```r
# generate some random color codes for the 6 TiTv classes 
titvcols = RColorBrewer::brewer.pal(n = 6, name = "Dark2")
names(titvcols) = c("C>T", "C>G", "C>A", "T>A", "T>C", "T>G")

# usage
luad = maftools::tcgaLoad(study = "luad")
maftools::oncoplot(maf = luad, draw_titv = TRUE, titv_col = titvcols)
```

Hope this helps and let me know if it works for you.
