### ISSUE TITLE
ALMS1 Protein Structure and Oncoplot Variant Classifications

### ISSUE THREAD

**Issue by whitejaa** [PoisonAlien/maftools#705]
Hi,

1- When I run the lollipopPlot function for ALMS1, I get the error message, "Structure for protein ALMS1 not found."
Will you please add it to maftools?

2- By default the oncoplot function does not show all variant types. Specifically, 3'UTR. 3'Flanking, Translation_Start_Site, Splice_Region, Intron and a few others are not shown when the plot is generated. Why is that?

THANKS!

Code-----------
lollipopPlot(
  maf = Nigerian_Tumor.maf,
  gene = 'ALMS1',
  AACol = "HGVSp",
  showMutationRate = TRUE,
  showDomainLabel = FALSE,
  roundedRect = TRUE,
  domainBorderCol = NA,
  legendTxtSize = 1.25,
  colors = test_pal_2,
  labelPos = 27,
  axisTextSize = c(1.5, 1.5),
  pointSize = 2
)

oncoplot(maf = Nigerian_Tumor.maf, 
top = 30, 
clinicalFeatures = c('Gsum'), 
colors = test_pal_2, 
annotationColor = GScolors
)

**Comment by PoisonAlien** [comment]
Hi,

1. I have added the ALMS1 to the database. Please install from GitHub for the update.
2. By default only non-synonymous variants are plotted. You can define your own list of variant classifications to be considered as non-syn. See `vc_nonSyn` in `?read.maf` for details.

**Comment by whitejaa** [comment]
Thanks for the quick assist. 

One last thing, how does maftools distinguish non-synonymous and synonymous mutations?

**Comment by PoisonAlien** [comment]
It stores `non-syn` and `syn` variants in two separate slots of MAF object. See `?MAF-class` for details.
