### ISSUE TITLE
Failed to installed on win10 by BiocManager::install("PoisonAlien/maftools")

### ISSUE THREAD

**Issue by YingYa** [PoisonAlien/maftools#708]
**Describe the issue**

Failed to installed on win10 by BiocManager::install("PoisonAlien/maftools")

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
BiocManager::install("PoisonAlien/maftools")

** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'maftools' in inDL(x, as.logical(local), as.logical(now), ...)
```

**Session info**
Run `sessionInfo()` and post the output below

```r
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936    LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                               LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.15 compiler_4.0.5      tools_4.0.5         remotes_2.3.0      
```

**Comment by ShixiangWang** [comment]
Did you try installing maftools directly from bioconductor with `BiocManager::install("maftools")`??

**Comment by PoisonAlien** [comment]
Hi,
could you please try the below command?

```r
BiocManager::install("poisonalien/maftools", INSTALL_opts="--no-multiarch")
```

**Comment by YingYa** [comment]
> Did you try installing maftools directly from bioconductor with `BiocManager::install("maftools")`??

Yes, I could installed maftools (v2.6.05) by BiocManager::install("maftools").

> could you please try the below command? BiocManager::install("poisonalien/maftools", INSTALL_opts="--no-multiarch")
Yes, I try the command but fail to install with the same error.

**Comment by PoisonAlien** [comment]
Hi,
Unfortunately, I do not have access to the windows system to crosscheck. Googling around, it seems the issue is inherent from R itself and you will probably have to fix it for yourself. I am sorry I cannot be more helpful. 
FWIW, try installing `Rtools` package which might help.

**Comment by YingYa** [comment]
> Hi,
> Unfortunately, I do not have access to the windows system to crosscheck. Googling around, it seems the issue is inherent from R itself and you will probably have to fix it for yourself. I am sorry I cannot be more helpful.
> FWIW, try installing `Rtools` package which might help.

Thanks. The rtools have been installed but not work.
I will try to fix the issue.
