### ISSUE TITLE
Cannot load a maf file

### ISSUE THREAD

**Issue by TamaraO** [PoisonAlien/maftools#71]
Hi, I am trying to load a maf file, and it seems to have correct format, according to the NCI page, but when I try to load it, I get an error message:
> mymaffile <- system.file('HCT.maf.subst', package = 'maftools')
> HCTmaf <- read.maf(maf = mymaffile, removeSilent = F, useAll = T, verbose = T)
reading maf..
Error in data.table::fread(input = maf, sep = "\t", stringsAsFactors = FALSE,  : 
  Input is either empty or fully whitespace after the skip or autostart. Run again with verbose=TRUE.
> 

Not sure what's causing this issue, and how I can resolve it. 

Thank you!

**Comment by PoisonAlien** [comment]
Hi,

You don't have to run first `system.file` command. You can directly pass your maf file to `read.maf`. 

```r
HCTmaf <- read.maf(maf ="/path/to/HCT.maf.subst", removeSilent = F, useAll = T, verbose = T)
```
