### ISSUE TITLE
Adding more than one additionalFeatures to Oncoplots

### ISSUE THREAD

**Issue by parvathisudha** [PoisonAlien/maftools#711]
Hi, 

I am using Maftools to generate Oncoplot. Also, using custom CN table for the copy number data. For one of the sample, I need to add 2 annotations.

An example of my CN table:

Gene    Sample_name     CN
CKS1B_CN        S1   Gain
CKS1B_CN        S2    Amplification
CKS1B_CN        S3    Deletion
CKS1B_CN        S10   Gain
CKS1B_CN        S10   LOH

Here S10, has 2 annotations. I gave LOH as an additionalFeature, and mark an 'x' for that. 

`oncoplot(maf = df.plus.cn.trans, altered = T, keepGeneOrder = T, genes = c(drivergenes3$DriverGene), colors = manualcolors, annotationFontSize = 1.2, legendFontSize = 1, drawColBar = F, gene_mar = 6, legend_height = 5, barcodeSrt = 90, sampleOrder = c(sample_order$Tumor_Sample_Barcode), additionalFeature = c("Variant_Classification", "LOH"), additionalFeaturePch = 4, additionalFeatureCex = .6, additionalFeatureCol = c("black"))`

![image](https://user-images.githubusercontent.com/13000751/118137675-79ed5380-b3d3-11eb-8ef1-e3d000354d3f.png)

But only one annotation for that sample is shown in the figure. I have marked Red color for Gain. Here, I would like to see a red color for Gain and a 'x' over that to show LOH. 
Actually, the command is only taking the first annotation for a sample from the Custom CN table. How can I mark 2 annotations as additional feature? Is there a way to do that? 

**Session info**

```R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.7.41

loaded via a namespace (and not attached):
[1] compiler_4.0.4     Matrix_1.3-3       tools_4.0.4        RColorBrewer_1.1-2 survival_3.2-11    splines_4.0.4      grid_4.0.4        
[8] data.table_1.14.0  lattice_0.20-41  
```

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. 

Would you mind sharing a reproducible example? Doesn't have to be the whole maf object, just subset you maf (with subsetMaf) for couple of samples (including the sample with issue) and save it as an rds file that you can attach here.

**Comment by SameerShankar** [comment]
Hi! I have a similar question to this. I have made an oncoplot based on data from 200 patients, and I would like to now add an annotation track as shown below (for the same 200 patients, for a given gene, information about whether there is aCN gain, loss, amplification, ...). How would I add such a track to an oncoplot?

<img width="583" alt="Screen Shot 2023-06-06 at 1 07 53 PM" src="https://github.com/PoisonAlien/maftools/assets/98920183/9467bbdf-91f3-4085-ae69-2eb8c3b9f687">
