### ISSUE TITLE
MafCompare: Applying the Haldane-Anscombe Correction for '0' Case Cells

### ISSUE THREAD

**Issue by HHayman** [PoisonAlien/maftools#718]
**Describe the issue**
When calculating an OR we can get a infinite value from a zero division and thus no OR. 

As far as I'm aware there is no especially good solution to this, but the best attempt to my knowledge is the 'Haldane-Anscombe' correction which adds 0.5 to all cells within any contingency tables that have cells with a value of '0'. It's not perfect, but the best option I think.

Typically, this would be done semi-manually prior to running a statistical test, but in this case the test runs within the larger MafCompare function. Is it feasible to add an option to apply the Haldane-Anscombe correction within MafCompare?

Thanks!

Apologies, the issues section seems really busy at the moment!

**Comment by ShixiangWang** [comment]
Did you mean you want to add an option to enable the so called H-A correction? I think your request is reasonable.

By the way, do you know any reference for H-A correction?

**Comment by HHayman** [comment]
Heylo

Yep, exactly. 

I came across it from this paper (post-panicked googling). Version (b) is the one I am referring to, but I think version (a) may be more standard. It seems to be regularly used but without discussion.
https://onlinelibrary.wiley.com/doi/epdf/10.1002/jrsm.1460

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the reference and details. 
I just did some tests and it seems that `fishers.test` rounds them to nearest integer. My guess is R implementation of FT only works with integers.

```r
fisher_mat = matrix(data = c(0, 124, 7, 0), byrow = TRUE, nrow = 2)
fisher_mat
     [,1] [,2]
[1,]    0  124
[2,]    7    0

# without 0.5
fisher.test(fisher_mat, conf.int = TRUE, conf.level = 0.95)
Fisher's Exact Test for Count Data

data:  fisher_mat
p-value = 8.96e-12
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.000000000 0.009965064
sample estimates:
odds ratio 
         0 

# with +0.5
fisher.test(fisher_mat + 0.5, conf.int = TRUE, conf.level = 0.95)

	Fisher's Exact Test for Count Data

data:  fisher_mat + 0.5
p-value = 5.431e-13
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.000000000 0.008536642
sample estimates:
odds ratio 
         0 

Warning message:
In fisher.test(fisher_mat + 0.5, conf.int = TRUE, conf.level = 0.95) :
  'x' has been rounded to integer: Mean relative difference: 0.01503759


# however adding one avoids 0 OR
 fisher.test(fisher_mat + 1, conf.int = TRUE, conf.level = 0.95)

	Fisher's Exact Test for Count Data

data:  fisher_mat + 1
p-value = 3.631e-11
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.00000000 0.02261943
sample estimates:
 odds ratio 
0.001635885 
``` 

Also here is a [thread](https://stats.stackexchange.com/questions/415604/interpreting-infinite-odds-ratio-and-confidence-interval-from-fishers-test) on adding 0.5 for fishers test. I do not know if adding 1 is a valid approach. I guess `Inf` should be fine? Let me know if you find any more references, I am happy to implement them.

**Comment by HHayman** [comment]
I agree, Inf should be absolutely fine for interpretation. The reason that it caused me an issue was that I wanted to rank by OR, so the Inf values were problematic, but I can manually shift them around for ranking purposes. 

It does that seem that people do also add 1 to cells but I'm not sure of the statistical validity of that, and if you have small numbers (such as I do) then increasing the value that you add to the cells is probably unwise. 

It might be that having the option there is (but with a specific decision to include it required from the user) useful, with the condition that people have to actively choose to use it and understand that there are limitations to it. 

Ultimately, perhaps it is better to leave it as it is and not cause confusion?

Thanks a lot for looking into this :)

**Comment by PoisonAlien** [comment]
Thanks. I will add an optional argument to add a positive constant and leave it up to the user. I guess it should be fine.. 

I am still struggling to find Windows system unfortunately, I am asking some wet lab friends and let you know soon regarding the installation issue.

**Comment by HHayman** [comment]
Thank you! No worries, I appreciate your workload.

**Comment by PoisonAlien** [comment]
I have added `pseudoCount` argument to `MafCompare`. When set to `TRUE` it will add 1 to the contigancy table with zeros which avoids `Inf` values. I hope this helps.

Still, I am not sure if you are able to pull the changes from GitHub, in case if you can not, you could just source the `mafCompare` script from GitHub and it should just work fine.

```r
source(file = url(description = "https://raw.githubusercontent.com/PoisonAlien/maftools/master/R/mafCompare.R"))
```
