### ISSUE TITLE
oncoplot top option not working

### ISSUE THREAD

**Issue by tooearly** [PoisonAlien/maftools#72]
Hi,
I have installed recent version, however oncoplot generate plot for all genes in spite of top is not null (for example, top = 10). Previous version was well working. 
Can you help for this problem.
Thank you.

**Comment by PoisonAlien** [comment]
Hi,

Could you paste your command ? How many genes are there in your maf ? Default value for top is 20 and if your MAF file contains less than 20 genes, it will plot all the genes.
