### ISSUE TITLE
write.table error to save maf file

### ISSUE THREAD

**Issue by kguion1** [PoisonAlien/maftools#720]
I have created and edited a maf file and now wish to save it. I tried the `write.table()` function; however, this is the error I get:

Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘structure("MAF", package = "maftools")’ to a data.frame

I am trying to save the maf file, really in any format so I can send it to a colleague. Thanks!

**Comment by PoisonAlien** [comment]
Hi,
You can use `write.mafSummary()`

**Comment by kguion1** [comment]
Okay thanks!

**Comment by kguion1** [comment]
I tried using the `write.mafSummary()` and the main maf file saves; however, when I read back in the `.maf` file, the clinical data is missing.

**Comment by PoisonAlien** [comment]
I just realized that the function did not write the clinical data to the output file. I have updated the function to include clinical data as well. You will have to reinstall the package from `GitHub`.

If you prefer not to reinstall, you can just manually write the clinical data to a file.

```r
data.table::fwrite(x = getClinicalData(maf),
                     file = "clinical_data.tsv", sep='\t',
                     quote = FALSE, row.names = FALSE)
```

**Comment by kguion1** [comment]
Okay, thank you. I am having trouble installing from github, so I will use your workaround. I have the same `permission denied`  for the `curl` and `rlang` dependencies error that other users seem to have. I have not seen a fix for this error.  Have you?

**Comment by PoisonAlien** [comment]
Unfortunately no :|
