### ISSUE TITLE
How to add NCBI_Build to maf object

### ISSUE THREAD

**Issue by kotliary** [PoisonAlien/maftools#721]
I create the maf object from a data frame. I don't have the MAF file for a specific data set and need to adjust the data in R code. The summary shows NCBI_Build as NA. Since I do know the build how can I add it properly to the maf object?
Thanks

**Comment by PoisonAlien** [comment]
Hi,

Usually, the MAF file contains a column `NCBI_build` from which this information is extracted. In the absence of the column, it gets set to `NA`. But if you know the build you can just add it to the MAF object manually.

```r
maf@summary$summary[1] = "hg19"
```

**Comment by kotliary** [comment]
Thanks
