### ISSUE TITLE
How can I control the font of annotation and clinicalFeatures

### ISSUE THREAD

**Issue by DonghaiYu** [PoisonAlien/maftools#726]
I use oncoplot to draw a graph, all the fonts of annotation and clinicalFeatures are all italic, how can I change them to normal?

R version: 4.0.5
maftools version: 2.6.5

**Comment by PoisonAlien** [comment]
Hi,

That should never happen. Try `dev.off()` and re-run your `oncoplot` command.

You could also set your font style beforehand with `par()`
e.g;

```r
par(font = 1)
oncoplot(maf = laml, clinicalFeatures = 'FAB_classification')
```
