### ISSUE TITLE
Save merged maf file

### ISSUE THREAD

**Issue by Anahit19** [PoisonAlien/maftools#729]
Hi,

I was wondering what is the best way to save merged maf file into one?

I want to merge 36 maf sample divided per 22 chromosome (792 files in total) to get a general statistics for all together, but currently facing a memory issue on my server.

So, I thought that as a workaround I can merge several files separately and then merge joined ones together rather then merging all 792 files at once.

Thank you again!

**Comment by PoisonAlien** [comment]
Hi,
If all of the files have the same columns, in the same order, you could just `cat` them from the command line. 

```
# Just extract the header (column names)
head foo.maf | grep ^Hugo-Symbol > merged.maf 
# Concatenate all MAFs (ignoring commented lines and header lines)
cat *.maf | grep -v "^Hugo" | grep "^#" >> merged.maf
```

**Comment by Anahit19** [comment]
I used these commands prior to merging in maftools and for some reason it produces inadequately huge output file.

**Comment by PoisonAlien** [comment]
In that case, you could only import selected columns, which should decrease the size of the object. See [here](https://github.com/PoisonAlien/maftools/issues/722#issuecomment-852365630)

**Comment by Anahit19** [comment]
Thank you!

**Comment by Anahit19** [comment]
Sorry for my late reply. Yes, thank you very much!

**Comment by Anahit19** [comment]
Hi, I was just wonderiint whether I can use maftools to save my merged maf file? 

When I use write.table@data slot I lose part of  the data.

Is there is a workaround?
