### ISSUE TITLE
clinical data retrieval

### ISSUE THREAD

**Issue by guillaume-rs** [PoisonAlien/maftools#731]
Hi,
Sorry for this a bit off-topic question :
Could you tell me where did you get the response clinical data for the LAML dataset (in the file tcga_laml_annot.tsv) ?
I have tried with the TCGAbiolinks package, but it actually includes much more NAs than in your file in the "days_to_last_followup" field.
(I'm trying automate clinical data retrieval to use MAFtools survGroup() on all TCGA datasets.
Thanks!

**Comment by PoisonAlien** [comment]
Hi,

It was a long time ago that I compiled this data (I think in 2016). Clinical data were extracted with TCGA Bio-links. I wouldn't be surprised if you don't see the same now since TCGA has been updating its data constantly whenever new information was obtained. It also depends on the GDC center.

**Comment by guillaume-rs** [comment]
Thank you for your quick response.
I've just found out that actually the "days_to_last_followup" column in "tcga_laml_annot.tsv" is a merge of both "days_to_last_followup" and "days_to_death" of the TCGA clinical file. So it explain the discrepency ;)

**Comment by PoisonAlien** [comment]
Haha.. super. Thanks for letting me know. I must have done it to create the example dataset.
