### ISSUE TITLE
Tumour mutational burden (TMB) and copy number variants (CNVs)

### ISSUE THREAD

**Issue by ConDem94** [PoisonAlien/maftools#732]
Hello,

I have recently generated a tmb (exome capture = 58 Mb) dataframe for my patient cohort (n = 23) which also includes copy number data. It seems that the tmb function also included the CNVs in the calculation, thus generating higher TMB values. 

Is this an acceptable output for investigating both the mutation and copy number variation burden?

Thanks!

**Command**
Please post your commands and the output (errors or any unexpected output)

```
CNV_maftools <- read.csv("directory/CNV_maftools.csv")
CNV_maftools <- CNV_maftools[,-1]

all_genes_maf <- read.maf(maf          = "directory/BCN_maftools.maf", 
                          cnTable      =  CNV_maftools, 
                          clinicalData = "directory/Clinical_data.csv",
                          verbose      = FALSE)

tmb_df <- tmb(all_genes_maf , captureSize = 58, logScale = TRUE)
```

**Comment by PoisonAlien** [comment]
Hi,

CNV is not used for TMB estimation. Could you please double-check again?

```r
CNV_maftools <- read.csv("directory/CNV_maftools.csv")
CNV_maftools <- CNV_maftools[,-1]

m1 <- read.maf(maf          = "directory/BCN_maftools.maf", 
                          cnTable      =  CNV_maftools, 
                          clinicalData = "directory/Clinical_data.csv",
                          verbose      = FALSE)

m2 <- read.maf(maf          = "directory/BCN_maftools.maf", 
                          clinicalData = "directory/Clinical_data.csv",
                          verbose      = FALSE)

tmb_df_m1 <- tmb(m1 , captureSize = 58, logScale = TRUE)
tmb_df_m2 <- tmb(m2 , captureSize = 58, logScale = TRUE)

all.equal(tmb_df_m1, tmb_df_m2)
```

The only way to get different output would in case if you have samples with only CNVs and no mutations. In that case, TMB would be zero or `Inf` for such samples..
