### ISSUE TITLE
detailing Multi_hit in oncoplot?

### ISSUE THREAD

**Issue by aelhossiny** [PoisonAlien/maftools#733]
**Describe the issue**
Hey, first thanks for such an incredible package for analysis and visualization! 

I have a  question regarding `oncoplot` function, for genes that have multi_hit mutations, is there a way to colorize the rectangle based on different types of `variant_classification` instead of having a single color indicating a multi_hit mutation? Something similar to plots combining SNV and CNV for a specific gene in the vignette

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
This was also asked in one of the previous issues. Unfortunately, it is hard to implement it and wasn't really worth the effort :|
