### ISSUE TITLE
Top 10 mutated genes

### ISSUE THREAD

**Issue by Anahit19** [PoisonAlien/maftools#736]
**Describe the issue**
Interpretation of the pattern 

**Command**
plotmafSummary(maf = maf_all, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)

Hi,

I am using maftools for summary statistics.
[Rplots.pdf](https://github.com/PoisonAlien/maftools/files/6720409/Rplots.pdf)

I was wondering why for top10 mutated genes all my percenters are 100% (please find it attached).

Thank you in advance,
Best,
Anahit

**Comment by PoisonAlien** [comment]
Hi,

It means the gene is mutated in all the samples. It is bit weird, I am guessing you have not done the filtering step?

**Comment by Anahit19** [comment]
Hi, 

Thank you for your reply!

This is the data of merged maf files coming from the vcfs genotyped with GVCF mode, applying VariantRecalibrator for filtering out snps and indels. My goal is to look at the variants in my population and compare those of other populations, as well as identify novel snps while comparing with dbsnp dataset. I did not use any further filters, which I think I should?

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the late reply. I misread the figure. They are not supposed to be 100%. From the description, it seems this is not a cancer cohort? Also how does the oncoplot looks for these top ten genes? Are they mutated in all?

**Comment by Anahit19** [comment]
Hi,

Yes, this is not a cancer cohort. It looks like this https://github.com/PoisonAlien/maftools/issues/727

Thank you very much!

**Comment by PoisonAlien** [comment]
Check the output from `getGeneSummary` and `getSampleSummary`. If they are altered in all the samples then it is what you see.
Also, in the plot you shared, the x-axis represents the number of mutations in the gene and the % represents the % of samples in which it is mutated. It is possible that the gene has more than one mutation. In that case, I would guess your plot is legit.

**Comment by Anahit19** [comment]
I have checked them with getGeneSummary and getSampleSummary.

I have 36 samples in total and the number of altered samples is different depending on the gene in getGeneSummary 

getGeneSummary(maf)$AlteredSamples
  [1] 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 36 35 35 35 35 35 35 35 34 34 34 33 32 32 32 32 31 30 30 29 29
 [47] 29 29 28 28 28 27 27 26 26 26 26 25 24 24 24 23 23 22 22 22 21 21 21 21 20 19 18 17 17 17 17 16 15 15 15 14 14 13 12 12 12 12 11 11 11 10
 [93] 10 10 10 10  9  8  8  8  7  7  7  7  6  6  6  6  6  6  6  5  5  5  5  4  4  4  4  4  4  3  3  3  3  3  3  3  2  2  2  2  2  2  2  2  2  2
[139]  2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1

I have also  different statistics for getSampleSummary.

Thank you very much!!
