### ISSUE TITLE
Cannot find function somaticInteractions

### ISSUE THREAD

**Issue by rsklav** [PoisonAlien/maftools#74]
Hello, 

 I am having two issues:

1) Although I reinstalled maftools, function somaticInteractions cannot be found.
2) Is there a way to rainfallPlot all samples in a single plot? For example, I have two mafs, each with mutations from a different type of tumor and I would like to see how they compare at the tumor level.

Can you please help?

Thanks,

R

**Comment by PoisonAlien** [comment]
Hi,

What version of maftools are you using ? Maybe try installing it from github since the newer version has not been updated on Bioconductor release branch yet. 

You can just call `pdf()` function and loop through all samples. Maybe something like this.

```r
mySamples = getSampleSummary(x = laml)[,Tumor_Sample_Barcode]
pdf(file = "rainfalls.pdf", width = 8, height = 3, paper = "special", bg = "white", pointsize = 9)
for(i in 1:length(mySamples)){
  rainfallPlot(maf = laml, tsb = mySamples[i])
}
dev.off()
```

**Comment by rsklav** [comment]
Thanks so much! 

However, I am now getting an error message: 
```
Error in subsetMaf(maf = m, genes = g, includeSyn = FALSE) : 
  no slot of name "clinical.data" for this object of class "MAF"
```

**Comment by PoisonAlien** [comment]
what version are you using ? Did you install it from GitHub ?

**Comment by rsklav** [comment]
Github, yes.
maftools             * 1.3.92

**Comment by PoisonAlien** [comment]
Oh! That is weird. Only thing I can imagine is you must have generated MAF object using older version of maftools, which doesn't have `clinical.data` slot. Can you read you maf file again using newer version and try if it works ? Sorry, recently I made changes to MAF object so there will be little bit discrepancies :|

**Comment by rsklav** [comment]
That is what it was! If I read.maf again (remove_Silent argument is now deprecated), then I get interactions. 

I know it is irrelevant to my post's title, however I am playing around with all these new cool functions and I am wondering if there is a way to call BSgenome for trinucleotide matrix generation, instead of downloading a fasta file. 

Anyway, thanks so much!

**Comment by PoisonAlien** [comment]
Yes, initial thought was to use BSgenome but then it would be much convenient to use same reference fasta file that was used to generate MAF, hence I sicked with fasta file. 
Check NEWS file (`news(package = "maftools")`) for version changes.
