### ISSUE TITLE
Two lines in mafSurvGroup.R to blame

### ISSUE THREAD

**Issue by wangshun1121** [PoisonAlien/maftools#741]
I tried to explore the impact of mutations in the ErbB pathway upon survival time, using following command lines:

```r
library(maftools)
laml = read.maf(maf = "Filtered.37patients.maf.gz",clinicalData = "clinic.txt")
ErbB_path = c("ERBB3","ERBB2","ERBB4","EGFR","KRAS","PIK3CA","MAPK10","MYC","SRC","HRAS","NRG1","BRAF","MAP2K4","NRAS","SOS2")
mafSurvGroup(maf = laml, geneSet = ErbB_path, time = 'OS.time',Status = 'Status')
```

When I tried to use `mafSurvGroup.R`, the command failed. Then I checked codes of this function, and I found following lines to blame:

https://github.com/PoisonAlien/maftools/blob/270305a393d4c64d78c5377f3a9ca3ddccc8bf3e/R/mafSurvGroup.R#L62-L63

```r
  mm = mutMat[,geneSet, drop = FALSE] # line 62
  genesTSB = names(which(rowSums(mm) == length(geneSet))) # line 63

...r

clinicalData$Group = ifelse(test = clinicalData$Tumor_Sample_Barcode %in% genesTSB, yes = groupNames[1], no = groupNames[2]) # line 67
```

> The line 62

In my gene set, there are some genes with no mutations. Then the data frame `mutMat`, which was calculated using internal function `createOncoMatrix` in line 58, only has columns of mutated genes. In my case, there three genes (MYC, SRC and MAP2K4) have no mutation, and I got following error info:

```r
Error in mutMat[, geneSet, drop = FALSE] : subscript out of bounds
```

> The line 63

Then I removed genes without mutation, and I got following error:

```r
Error in survdiff.fit(y, groups, strata.keep, rho) : 
  There is only 1 group
```

I checked the line 63 and following line 67, and realized that only patients with mutations on **ALL GIVEN GENES** were treated as Mutant group, otherwise Wildtype. That is the key issue I want to point out! In my case, I want to investigate impact of mutations in a PATHWAY, meaning that if there are any genes with mutations in this pathway, this pathway may potentially lose its function! 

Then here are my suggestions. Most directly, these two lines can be modified as following:

```r
mm = mutMat; # No need to filter genes this way! 
 genesTSB = names(which(rowSums(mm) > 0) # As long as any mutations were detected, the patient were grouped as Mutant!
```

Furthermore, in this function `mafSurvGroup.R`, there might  be a parameter for enrollment of mutate group: for example, if 10 genes were given, patients with at least 3 mutated genes were enrolled, otherwise as wild type.

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue and for going through the code. I have fixed the issue and added `minMut` argument. Note that by default it is set to `NA` - meaning all the genes from `geneSet` need to be mutated. You can set it to any number of your choice. Hope this helps, let me know..

**Comment by wangshun1121** [comment]
I tried the version of your latest commit, it works well! By the way, there are two suggestions:

1. Perhaps letting the default value of `minMut` be 1, rather than all, would be better;
2. `createOncoMatrix` is a useful function, at least for me, I think this function can be exported!

**Comment by PoisonAlien** [comment]
Hi,
Thank you for the suggestions. 
1. I did not change it since it would break the flow. I will have it changed in the next BC release, that I can announce it in the NEWS. 
2. Yes, this will be exported as well.
