### ISSUE TITLE
A ERROR in extractSignatures()

### ISSUE THREAD

**Issue by lizhan96** [PoisonAlien/maftools#743]
Dear Developer

I get a ERROR when I use the command `extractSignatures()`. 

```
Error in data.table::fread(input = system.file("extdata", "signatures.txt",  : 
  Input is empty or only contains BOM or terminal control characters

```
the error info told that there was no such file, and I found the error happened on the following exact code `system.file('extdata', 'signatures.txt', package = 'maftools')` when I checked the source code, how can I get that file?

Thanks!

**Comment by PoisonAlien** [comment]
Hi,
[extractSignatures](https://github.com/PoisonAlien/maftools/blob/master/R/extractSignatures.R) never uses that file. What version of the package are you using? Could you please post your sessionInfo?

**Comment by lizhan96** [comment]
> >   laml.sig = extractSignatures(mat = laml.tnm, n = i, pConstant = 0.001)
-Running NMF for factorization rank: 2
Error in data.table::fread(input = system.file("extdata", "signatures.txt",  :

Here is the sessionInfo. And maftools 2.8.0 I used.

**Comment by PoisonAlien** [comment]
Hi,
I don't see your sessionInfo. Also this error is only possible with maftools version 2.2.20 or below. Please make sure you're running the recent version.
