### ISSUE TITLE
Support for mm10 build for gisticChromPlot()

### ISSUE THREAD

**Issue by nruthen** [PoisonAlien/maftools#744]
Hello,

I noticed that the gisticChromPlot() function only supports the hg18, hg19, and hg38 builds. Would you consider adding support for the mm10 genome build or allowing users to specify a custom reference build? 

Very Best,
Neil

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the delay. I have no experience with mice genomic data. I have implemented crude support for mm versions but it seems to break many existing changes.  
To make sure it works stably, would it be possible for you to share a `gistic` object from mice?
