### ISSUE TITLE
Error in running clinicalEnrichment(

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#745]
**Describe the issue**
I tried to apply clinicalEnrichment but kept receiving the error messages as below. The levels of clinical feature in my dataset is not duplicated. 
Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [2] is duplicated

**Command**
A@clinical.data$clinical_feature<-factor(A@clinical.data$clinical_feature,levels = c('Stage1','','Stage2','Stage3','Stage4'))
clinicalEnrichment(maf = A, clinicalFeature = 'clinical_feature')

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by xiw588** [comment]
Any thoughts on this?

**Comment by PoisonAlien** [comment]
Hi,

It seems the `"` symbol in `levels` might be the issue here. Is that a typo?

**Comment by xiw588** [comment]
Hi, Oh actually its a typo. I am wondering if it is something wrong with characters as it worked well when it comes to numbers.

**Comment by PoisonAlien** [comment]
I have not seen any issues with the number/characters before. 
If you could provide a reproducible example, I can help to track the issue.
