### ISSUE TITLE
Lolipop with Mutant Allele Frequency instead of count

### ISSUE THREAD

**Issue by bkohrn** [PoisonAlien/maftools#746]
It would be useful if we could plot values other than count on the lollipop plot; in particular, we often find ourselves wanting to plot Mutant Allele Frequency.  Ideally, this would be accomplished by giving a column name for the values to plot.  I've managed to program a variation that works for plotting Mutant Allele Frequency from our .maf files, but I'm not sure how to make it more generally applicable.

**Comment by PoisonAlien** [comment]
Hi,

Is it possible to share a plot to demonstrate? I am guessing you would like to have VAF on the y-axis instead of frequency?

**Comment by haochenz96** [comment]
Thanks for the amazing tool! 

Same request here. Would be great if the function could take a dataframe of **unique** SNV records and a column of custom "height" data (e.g. VAF, number of samples) and make the plot.

A good reference could be:
<img width="768" alt="Screen Shot 2022-12-04 at 7 03 19 PM" src="https://user-images.githubusercontent.com/54121237/205540415-0e988d2a-d30a-470f-8115-865f4aea819a.png">
which was taken from this package (https://bioconductor.org/packages/release/bioc/vignettes/trackViewer/inst/doc/lollipopPlot.html#Change_the_height_of_a_lollipop_plot)
