### ISSUE TITLE
Error annovarToMaf function: skip='Chr' not found in input (it is case sensitive and literal; i.e., no patterns, wildcards or regex)

### ISSUE THREAD

**Issue by valemirici** [PoisonAlien/maftools#747]
I'm trying to convert an annovar output files into MAF using the fucntion annovarToMaf. 

I get this error.

-Reading annovar files Error in FUN(X[[i]], ...) :    skip='Chr' not found in input (it is case sensitive and literal; i.e., no patterns, wildcards or regex)

Could you help me? 

Thanks,
Valeria

**Comment by ShixiangWang** [comment]
Could you Show some rows of your input file？

**Comment by valemirici** [comment]
I solved the issue saving my table in txt format. 

Thank you!
