### ISSUE TITLE
One merged sample is recognized as two samples.

### ISSUE THREAD

**Issue by kenasada** [PoisonAlien/maftools#749]
Hello,

I have been having a trouble with concatenating a sample file.
My collaborator gave me two different txt files for each, which is SNP and INDEL file.
Therefore, I had to merge two files into one and need to work with several hundreds files.

Anyway, files have a # in the first row and the second row has header information like Hugo_Symbol, Enter_Gene_ID, Center, NCBI_Build, Chromosome, Start_Position, etc.
So what I did using Mac terminal was,
1. cat 1.INDEL.maf.txt | grep -v '^#' > 1.maf.txt
2. cat 1.SNP.maf.txt | grep -v '^#' | grep -v "Hugo_Symbol" >> 1.maf.txt

When I load 1.maf.txt into the maftools and draw the figure using oncoplot, it showed as two samples.
Therefore, I further manipulated 1.maf.txt to sort by chromosome to see what happens using a below script.
sort -k 5 1.maf.txt > 1_2.maf.txt
Unfortunately, oncoplot with 1_2.maf.txt gave me a same result, it still recognizes as two samples.

What am I support to do to over come this problem?
Any kind of suggestion should be helpful for me.

Thank you very much in advance!

**Comment by ShixiangWang** [comment]
Did you check the sample IDs in these two files are same?

**Comment by kenasada** [comment]
Thank you very much for your quick response.

There are no sample IDs but "reference_allele" column has two different names (INDEL or SNV).
I have renamed to unify them and now oncoplot works well as I expected.

Thank you again for your help.
I appreciate it.
