### ISSUE TITLE
Using maftools on germline data

### ISSUE THREAD

**Issue by oalavijeh** [PoisonAlien/maftools#751]
Firstly many thanks for maftools, it's really awesome! 

I am interested in plotting a lolliplop plot and your package makes really nice looking ones. I have germline SNV data and am trying to input it as a "maf" file, it is just a tab separated tsv file with the minimum headers as described on your bio conductor vignette, but it doesn't seem to read in. An example of the file I have created is below:
```

Hugo_Symbol	Chromosome	Start_Position	End_Position	Reference_Allele	Tumor_Seq_Allele2	Variant_Classification	Variant_Type	Tumour_Sample_Barcode 
CNCL	chr10	1586138	1586138	G	A	stop_gained	SNP	1
CNCL	chr10	1602439	1602442	CAG	C	frameshift_variant	DEL2
CNCL	chr10	1523884	1523884	G	A	stop_gained	SNP	3
CNCL	chr10	1592548	1592548	C	T	missense_variant	SNP	4
```

When I try to read this in I get:
```

> laml.maf = system.file('extdata', 'CNCL_cases.maf.csv', package = 'maftools')  
> laml = read.maf(maf = laml.maf) 

Reading Error in data.table::fread(input = maf, sep = "\t", stringsAsFactors = FALSE,  :    Input is empty or only contains BOM or terminal control characters
--
 

```

Not sure what I am doing here, I assume the input file is the problem? 

Many thanks

**Comment by PoisonAlien** [comment]
Hi,
You dont have to run the below line. It is only to access the example file included in the package.
```r
> laml.maf = system.file('extdata', 'CNCL_cases.maf.csv', package = 'maftools')  
```

In your case, it should just be the path to your maf file.

```r
> laml.maf = "CNCL_cases.maf.csv"
> laml = read.maf(maf = laml.maf) 
```

**Comment by oalavijeh** [comment]
Many thanks it worked well!
