### ISSUE TITLE
mafCompare output for genes with multiple variants

### ISSUE THREAD

**Issue by DadongZ** [PoisonAlien/maftools#752]
Hi I saw the outputs of mafCompare are reported by each gene. If a gene has multiple variants from each sample, which variant is used for the fisher test? Is it used the most divergent variant between two testing groups or any variant from a sample?

**Comment by PoisonAlien** [comment]
Hi,
Are you talking about `Multi_Hit` genes? In those cases, they are considered as just one event.

**Comment by DadongZ** [comment]
Thank you for your reply. Is there a way to test two groups by each variant?

**Comment by PoisonAlien** [comment]
Hi,
You should note that `mafCompare` checks for differences in mutational frequency of genes (regardless of the type of mutation) between two groups. If I understand correctly, you would like to check the frequency of certain variants within a gene (e.g., R882 in DNMT3A) between two groups? In that case, you would probably want to `subset` your maf file for only those hotspots and then run `mafCompare`.

**Comment by DadongZ** [comment]
Thanks. Actually I would like to do a global test for each variant between two groups. A minimum frequency threshold across the two groups might be applied such as > 5. Does it make sense? 

For example, mutations from a gene may have occurred on all samples (should be no difference from mafCompare()), but a certain mutation from this gene may just occurred on few of these samples and a test might be significant. This mutation might be clinically relevant instead of all mutations from the gene.

**Comment by PoisonAlien** [comment]
Unfortunately, it's not possible. This is where you might want to subset only your variants of interest and run the test.
Btw, there is an argument `minMut` in `mafCompare` if you would like to put a threshold.
