### ISSUE TITLE
Apply maftools based on CNS file generated by CNVkit

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#753]
**Describe the issue**
Hi, I want to apply maftools to CNV data based on CNS files generated by CNVkit. Each sample has each file. 
Do you know if this can be easily feed into maftools? 

Thank you. 

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,

I have no idea how the file looks like. Could you please provide an example file or paste few rows of the file?
I would suggest you run GISTIC on all those files to identify recurrently altered CNV regions, which can then be imported into `maftools`.

**Comment by wangshun1121** [comment]
Aha, I have similar demand, even though my CNV caller are cnv_facets and Sequenza rather than CNVkit. I wonder if maftools can accept CNV results from sources other than GISTIC.

**Comment by PoisonAlien** [comment]
Hi @wangshun1121 ,
Thanks for the issue and apologies for the delay. 
I would love to support other tools. Could you please share few outputs from `cnv_facets`  or `Sequenza`?

**Comment by wangshun1121** [comment]
[Facets.zip](https://github.com/PoisonAlien/maftools/files/7030173/Facets.zip)

This is an example of Facets results. The most important file is `*.vcf.gz`, which gave details of every CNV region. By the way, definition of CNV types can be found at https://github.com/dariober/cnv_facets/blob/44fdd18a4beb4f57c6e6e746d31a6399efdbc85b/bin/cnv_facets.R#L563-L577

**Comment by wangshun1121** [comment]
[Sequnza.zip](https://github.com/PoisonAlien/maftools/files/7030200/Sequnza.zip)

Here are Sequenza outputs. In this folder, `*_segments.txt` is most import, CNV regions' details are recorded.

**Comment by wangshun1121** [comment]
These two CNV callers are allele-specific, meaning that they can detect LOH regions without alteration of reads coverage: that's the advantage over callers depend only on coverage such as CNV-kit, and of course, GISTIC. In folders I shared, there are only results of one sample, perhaps we can use a file-list to import results of several samples into maftool.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for sharing. I will see what I can do. 
Btw, you'd like to use these results to merge with MAF and further visualizations rite? for example, oncoplot with CNV data.

**Comment by wangshun1121** [comment]
Both, if possible
