### ISSUE TITLE
No exons being plotted 

### ISSUE THREAD

**Issue by oalavijeh** [PoisonAlien/maftools#757]
Dear @PoisonAlien , 

Many thanks for taking the time to create this excellent tool.

I am trying to plot the a lollipop file against a gene but the gene itself is not appearing as per the accession number. The lolliplot below is what I am currently getting:

![image](https://user-images.githubusercontent.com/56344383/128000157-4e771084-5aa0-46c9-b15f-d8391b0731a9.png)

The gene in question is: https://www.ncbi.nlm.nih.gov/nuccore/NM_014714.4.  I see many more exons on the gene. The gene is at NM_014714 but I think I want to plot NM_014714.4 the latest version.

The code used is very simple:

```r
lollipopPlot(
  maf = laml,
  gene = 'IFT140',
  AACol = 'Protein_Change',
  showMutationRate = FALSE,
  labelOnlyUniqueDoamins = FALSE
)
```

I have also tried:

```r
> lollipopPlot(
+     maf = laml,
+     AACol = 'Protein_Change',
+     showMutationRate = FALSE,
+     labelOnlyUniqueDoamins = FALSE, refSeqID = "NM_014714.4", gene = "IFT140"
+ )
```

Error in lollipopPlot(maf = laml, AACol = "Protein_Change", showMutationRate = FALSE,  :
  NM_014714.4 not found!

Is there another way of plotting the exons accurately onto the plot?

Many thanks

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the late response. `refSeqID` should not contain any postfix, it should just be `NM_014714`. 
Hope this helps.
