### ISSUE TITLE
Customize color and thickness of the grid border on pathways

### ISSUE THREAD

**Issue by n-azussa** [PoisonAlien/maftools#759]
Hi!
Is there any ways to change line color and thickness?
Below an example. I want to change the color and the pathway line is way to much tick =)

![image](https://user-images.githubusercontent.com/84482814/128555840-ae3523e2-b9cb-434c-a397-d4f03ebbdcf7.png)

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue and apologies for the delay in responding. 

I have added two arguments `pwLineCol` and `pwLineWd` for controlling the color and width of the boxes. Hope this helps, please let me know if this works.

**Comment by n-azussa** [comment]
Hi, 
Thank you for your reply =)
I'm still not able to use those two arguments. There is a need for some update? I started again and update the packages, but nothing new... Can give me a tip?

**Comment by PoisonAlien** [comment]
Hi,

Yes, you will need to re-install the package from GitHub by running the below command.

```r
BiocManager::install("PoisonAlien/maftools")
```
You may also have to restart the r session after the installation.

**Comment by n-azussa** [comment]
Hi, 
I re-installed then restarted and still I'm not seeing those two arguments pwLineCol and pwLineWd.
 Should I try anything else?

**Comment by PoisonAlien** [comment]
Hi,
Did you install it properly? I have tested it on multiple computers and I can see the options in the update.

**Comment by n-azussa** [comment]
Apologies for not responding, Im still trying to update maftools but its causing some bug. 
I don't think the problem is maftools though but rather my computer or the version of something...

I've been unable to resolve the update issue:

* installing *source* package 'maftools' ...
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/**/***/****/R/win-library/4.1/maftools'
* restoring previous 'C:/**/***/****/R/win-library/4.1/maftools'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\**\***\****\R\win-library\4.1\00LOCK-maftools\maftools\libs\x64\maftools.dll to C:\**\***\****\R\win-library\4.1\maftools\libs\x64\maftools.dll: Permission denied.

**Comment by PoisonAlien** [comment]
I have never seen this error before. 
Maybe try manually deleting the installed package at `C:///***/R/win-library/4.1/maftools` ?

**Comment by n-azussa** [comment]
Hi, Im beginner for this.  Sorry for this dummy question, are these two arguments pwLineCol and pwLineWd linked to oncoplot, right!? Can you give an example in how to use?
I manually deleted and re-installed (version 2.8.0), but nothing changed.

**Comment by PoisonAlien** [comment]
Hi,
Yes, they are in `oncoplot`. Also after the update, you should see the version as `2.8.05`

Here is an example:

```r
#path to TCGA LAML MAF file
laml.maf = system.file('extdata', 'tcga_laml.maf.gz', package = 'maftools')
#clinical information containing survival information and histology. This is optional
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')

laml = read.maf(maf = laml.maf,
                clinicalData = laml.clin,
                verbose = FALSE)

oncoplot(maf = laml, pathways = "auto", gene_mar = 8, fontSize = 0.6, pwLineWd = 1.2, pwLineCol = "blue")
```

**Comment by n-azussa** [comment]
Hi;
I'm still having some issues to update maftools to version 2.8.05. =(
From BiocManager::install("maftools"), only version 2.8.0 is available. 
From BiocManager::install("PoisonAlien/maftools") , I receive an error
ERROR: compilation failed for package 'maftools'

Searching manually through my directories, I could find the "maftools_2.8.05.tar.gz"...but still not work

Downloading GitHub repo PoisonAlien/maftools@HEAD
√  checking for file 'C:\...\....\AppData\Local\Temp\Rtmpw58TO7\remotesb4c797678e4\PoisonAlien-maftools-9719868/DESCRIPTION' ... 
-  preparing 'maftools': (1.4s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (418ms)
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'maftools_2.8.05.tar.gz'
   
Installing package into ‘C:/.../.../Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'maftools' ...
** using staged installation
** libs

and then ERROR: compilation failed for package 'maftools'

Any suggestion!?

**Comment by ShixiangWang** [comment]
Did you include all info shown in the console? No valuable info from the latest reply.

**Comment by n-azussa** [comment]
Oh sorry, Here is all info showed in the console...

> BiocManager::install("PoisonAlien/maftools")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.13 (BiocManager 1.30.16), R 4.1.1 (2021-08-10)
Installing github package(s) 'PoisonAlien/maftools'
Downloading GitHub repo PoisonAlien/maftools@HEAD
√  checking for file 'C:\User\xxxx\AppData\Local\Temp\RtmpIZI8uW\remotes1f64358974f5\PoisonAlien-maftools-9719868/DESCRIPTION' ... 
-  preparing 'maftools': (2.1s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (429ms)
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'maftools_2.8.05.tar.gz'
   
* installing *source* package 'maftools' ...
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/User/xxxx/Documents/R/win-library/4.1/maftools'
* restoring previous 'C:/Users/xxxx/Documents/R/win-library/4.1/maftools'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\xxxx\Documents\R\win-library\4.1\00LOCK-maftools\maftools\libs\x64\maftools.dll to C:\Users\xxxx\Documents\R\win-library\4.1\maftools\libs\x64\maftools.dll: Permission denied
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/xxxx/AppData/Local/Temp/RtmpIZI8uW/file1f64121b2c4/maftools_2.8.05.tar.gz’ had non-zero exit status

=)

**Comment by n-azussa** [comment]
Ops, sorry. Here's all info showed in the console. =)

> BiocManager::install("PoisonAlien/maftools")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.13 (BiocManager 1.30.16), R 4.1.1 (2021-08-10)
Installing github package(s) 'PoisonAlien/maftools'
Downloading GitHub repo PoisonAlien/maftools@HEAD
√  checking for file 'C:\Users\XXXX\AppData\Local\Temp\RtmpSMUmKs\remotes6b878bc732b\PoisonAlien-maftools-9719868/DESCRIPTION' ... 
-  preparing 'maftools': (1.5s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (422ms)
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'maftools_2.8.05.tar.gz'
   
* installing *source* package 'maftools' ...
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.1/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'C:/Users/XXXX/Documents/R/win-library/4.1/Rhtslib/include' -I'C:/Users/XXXX/Documents/R/win-library/4.1/zlibbioc/include'        -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c ntcounts.c -o ntcounts.o
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.1/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'C:/Users/XXXX/Documents/R/win-library/4.1/Rhtslib/include' -I'C:/Users/XXXX/Documents/R/win-library/4.1/zlibbioc/include'        -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c somaticfreq.c -o somaticfreq.o
C:/rtools40/mingw32/bin/gcc -shared -s -static-libgcc -o maftools.dll tmp.def ntcounts.o somaticfreq.o C:/Users/XXXX/Documents/R/win-library/4.1/Rhtslib/usrlib/i386/libhts.a -L/lib/i386 -lcurl -lrtmp -lssl -lssh2 -lcrypto -lgdi32 -lz -lws2_32 -lwldap32 -lwinmm -lidn -LC:/PROGRA~1/R/R-41~1.1/bin/i386 -lR
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lcurl
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lrtmp
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lssl
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lssh2
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lcrypto
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lidn
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'maftools'
* removing 'C:/Users/XXXX/Documents/R/win-library/4.1/maftools'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/XXXX/AppData/Local/Temp/RtmpSMUmKs/file6b85e534edf/maftools_2.8.05.tar.gz’ had non-zero exit status

**Comment by ShixiangWang** [comment]
Try:

1. restart R session
2. remove maftools by `remove.packages("maftools")`, if failed, manually delete the `C:/User/xxxx/Documents/R/win-library/4.1/maftools`
3. install the latest version again.

**Comment by n-azussa** [comment]
Yeah, I follow your suggestion before, but still not working.

BiocManager::install("maftools"), only version 2.8.0 is available.

From BiocManager::install("PoisonAlien/maftools") , show ERROR: compilation failed for package 'maftools'

**Comment by ShixiangWang** [comment]
For error like 

```
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lcurl
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lrtmp
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lssl
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lssh2
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lcrypto
C:/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lidn
```

I guess you did not install rtools well. Maybe you should double check it.

**Comment by PoisonAlien** [comment]
Yes, make sure `rtools` is up to date. 
I will also push the changes to Bioconductor today and it should be available by tomorrow.

**Comment by n-azussa** [comment]
Thank You for Help and Support! I am grateful for all your suggestions, I will wait for the Bioconductor changes =)
I re-installed the new version rtools40, but still having the same problem. =(

**Comment by PoisonAlien** [comment]
Actually, you don't need to wait for it to update on Bioconductor. Below commands should work by directly sourcing the oncoplot function from GitHub.

```r
source("https://raw.githubusercontent.com/PoisonAlien/maftools/master/R/oncoplot.R")
source("https://raw.githubusercontent.com/PoisonAlien/maftools/master/R/oncomatrix.R")

oncoplot(maf = your_maf_object)
```

**Comment by ShixiangWang** [comment]
@PoisonAlien Nice workarounds.
