### ISSUE TITLE
custom grid size

### ISSUE THREAD

**Issue by hjack123** [PoisonAlien/maftools#760]
**Describe the issue**
Can we customize the grid size/shape on oncoprint Thanks!

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the delay in responding. I am not sure what you mean by grid shape/size, but you can control the space which separates the genes and samples with the arguments `sepwd_genes` and `sepwd_samples`.
