### ISSUE TITLE
How to get the new samples list when "sortByAnnotation" is set true in "oncoplot"?

### ISSUE THREAD

**Issue by wangjiangyuan** [PoisonAlien/maftools#765]
When sortByAnnotation  is set to TRUE, the number of the samples may not be the original number. And how to get the new samples list?
![image](https://user-images.githubusercontent.com/48577567/132099060-a3b502a6-b1c6-4d5a-807f-4a7f18e5ad07.png)

**Comment by PoisonAlien** [comment]
Hi,
`sortByAnnotation` does not affect the sample size. I just reorganize the columns (sample) by their groups.

**Comment by wangjiangyuan** [comment]
oh,sorry, I got something wrong. And I mean that I provide  maf, and I want to get a sorted list of samples.

**Comment by PoisonAlien** [comment]
You can use `writeMatrix = TRUE` and it will generate text file `onco_matrix.txt` in your working directory. This contains the underlying matrix in the same order.

Example using the MAF from vignette

```r
maftools::oncoplot(maf = laml, writeMatrix = TRUE, sortByAnnotation = TRUE, clinicalFeatures = "FAB_classification")
mat = read.delim(file = "onco_matrix.txt")

head(colnames(mat))
[1] "TCGA.AB.2934" "TCGA.AB.2928" "TCGA.AB.2853" "TCGA.AB.2895" "TCGA.AB.2879"
[6] "TCGA.AB.2900"
```

Hope this helps.

**Comment by wangjiangyuan** [comment]
Great, I try it as yours.  It works ! Thank you !

**Comment by wangjiangyuan** [comment]
Foremore, I want to sort by annotation as M0,M1,M2,M3, rather than the number of annotation type. How to do it?
![image](https://user-images.githubusercontent.com/48577567/132153409-ebcf44b1-3c1a-460e-971b-92160c461db7.png)

**Comment by PoisonAlien** [comment]
Hi,
Please check `?maftools::oncoplot()` for complete details. You can use `annotationOrder` argument to manually provide the levels.
