### ISSUE TITLE
How possible FLAGS are determined

### ISSUE THREAD

**Issue by rajkump** [PoisonAlien/maftools#766]
Hi Anand,
   I have a general question. Could you please let us know how possible FLAGS are determined?

--Possible FLAGS among top ten genes:

Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Hello Praveen,

FLAGS are derived from the below [publication](https://bmcmedgenomics.biomedcentral.com/articles/10.1186/s12920-014-0064-y). 

```
Shyr C, Tarailo-Graovac M, Gottlieb M, Lee JJ, van Karnebeek C, Wasserman WW. 
FLAGS, frequently mutated genes in public exomes. BMC Med Genomics 2014; 7: 64.
```

Hope this helps.

**Comment by rajkump** [comment]
Thank you very much
