### ISSUE TITLE
Reporting annovarToMaf error 

### ISSUE THREAD

**Issue by Zhr-Abdi** [PoisonAlien/maftools#772]
Hi, 

I have annovar format file and would like to convert it to maf format, but when I use the annovarToMaf to this conversion:

```
var.annovar <- system.file("extdata", "Annotated.somatic.merged.vcf.hg19_multianno.txt", package = "maftools")
var.annovar.maf <- annovarToMaf(annovar = "Annotated.somatic.merged.vcf.hg19_multianno.txt", 
                                Center = 'CSI-NUS', refBuild = 'hg19',tsbCol = 'Tumor_Sample_Barcode', 
                                table = 'refGene')
```
then I receive this error:

```
Missing required field in input file: 
[1] "Func.refGene"       "Gene.refGene"       "GeneDetail.refGene" "ExonicFunc.refGene"
[5] "AAChange.refGene"  
Error in annovarToMaf(annovar = "Annotated.somatic.merged.vcf.hg19_multianno.txt",  : 
```
How can I fix this problem? Would you mind helping me, please?

**Comment by PoisonAlien** [comment]
Hi,
Could you please make sure that the annovar output has all the required columns that are highlighted in the error message?

**Comment by Zhr-Abdi** [comment]
Thank you for your reply. I changed the names of columns in my annovar output file and so I passed the aforementioned error. 

`-Reading annovar files 
--Tumor_Sample_Barcode column not found. Creating sample IDs from filenames
-Processing Exonic variants
--Adding Variant_Classification
--Parsing aa-change
-Processing Non-exonic variants
--Adding Variant_Classification
-Adding Variant_Type
Finished in 1.623s elapsed (4.939s cpu)
`
But now I don't know how to get a `.maf` output file for drawing lollipopPlot. 
Would you mind helping me, please?

**Comment by PoisonAlien** [comment]
Hi,
It returns the converted data in MAF format. You can run the function with `MAFobj = TRUE` and, it should be enough for you to pass it to most of the maftools functions.

**Comment by Zhr-Abdi** [comment]
Dear Poison,
As you said I ran the following script, but no `.maf` file has been created yet in my current directory.

`var.annovar.maf <- annovarToMaf(annovar = "ann_test_hg19_multianno.txt", Center = 'CSI-NUS', refBuild = 'hg                           19', table = 'refGene', MAFobj = TRUE)
`

**Comment by Zhr-Abdi** [comment]
Thanks again.
Unfortunately, when I use `basename` I receive the new error :

```
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  :
  missing required fields from MAF: Tumor_Sample_Barcode
```
[here ](https://drive.google.com/file/d/1QgsCoK1DhN04rwNNtNG2eTxMXPguEBbJ/view?usp=drivesdk)is the sample of my annotated file.
