### ISSUE TITLE
Clinical features of Oncoplot

### ISSUE THREAD

**Issue by kenasada** [PoisonAlien/maftools#773]
First of all, I have been using maftools for a couple of month and I really appreciate that you provide such a great tool for us.

I wanted to put clinical features to my oncoplot, referring this issue for custom colors:
https://github.com/PoisonAlien/maftools/issues/236

This went well regarding the color but I am facing on something weird result of clinical features.
My sample has 2:1 ratio for smoking history and sex but visualized features do not look like that ratio.
It seems like 1:4 ratio I presume?
Additionally, there are NAs but my columns do not have any NA value.

![feature_1](https://user-images.githubusercontent.com/52488103/135003412-b1719286-8211-481f-8f16-6894799d1b64.PNG)

![feature_2](https://user-images.githubusercontent.com/52488103/135003431-1ec98515-3aab-456b-ae56-8c6c0a0dc54b.PNG)

I prepared my clinical features using your template tsv (tcga_laml_annot.tsv)  which is automatically downloaded into the extdata folder when I have installed maftools.

```
d1  = system.file('extdata', 'my_maf_file.txt.gz', package = 'maftools')
clinical = system.file('extdata', 'oncoplot_clinical.tsv', package = 'maftools')
d2 = read.maf(maf=d1, clinicalData = clinical)
getClinicalData(d2)

agecolors = RColorBrewer::brewer.pal(n = 6, name = 'YlOrRd')
names(agecolors)=c("30", "40", "50", "60", "70", "80")
sexcolors = RColorBrewer::brewer.pal(n = 6, name = 'Accent') 
names(sexcolors)=c("M", "F")
smokingcolors = RColorBrewer::brewer.pal(n = 6, name = 'Pastel1')
names(smokingcolors)=c("Smoker", "Never-smoker", "unknown")
anno_cols = list(Age=agecolors, Sex=sexcolors, Smoking_history=smokingcolors)

oncoplot(maf=d2, clinicalFeatures=c('Smoking_history','Sex', 'Age'), 
         annotationColor=anno_cols, sortByAnnotation=TRUE, writeMatrix=TRUE)

```

Actually my oncoplot_clinical.tsv has extra columns such as stage.
However, I do not think those extra columns affect the plot because I have once tried to run my code without having any additional columns but ended up in a same result.

Any kind of your feedback should be helpful.
Thank you very much in advance!

**Session info**
Run `sessionInfo()` and post the output below

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932    LC_MONETARY=Japanese_Japan.932
[4] LC_NUMERIC=C                   LC_TIME=Japanese_Japan.932    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.7    maftools_2.8.0

loaded via a namespace (and not attached):
 [1] magrittr_2.0.1     splines_4.1.0      tidyselect_1.1.1   lattice_0.20-44    R6_2.5.0          
 [6] rlang_0.4.11       fansi_0.5.0        tools_4.1.0        grid_4.1.0         data.table_1.14.0 
[11] xfun_0.24          R.oo_1.24.0        tinytex_0.33       utf8_1.2.2         DBI_1.1.1         
[16] ellipsis_0.3.2     assertthat_0.2.1   survival_3.2-11    tibble_3.1.3       lifecycle_1.0.0   
[21] crayon_1.4.1       Matrix_1.3-3       purrr_0.3.4        RColorBrewer_1.1-2 R.utils_2.10.1    
[26] vctrs_0.3.8        glue_1.4.2         compiler_4.1.0     pillar_1.6.2       R.methodsS3_1.8.1 
[31] generics_0.1.0     pkgconfig_2.0.3 
```

**Comment by PoisonAlien** [comment]
Hi,
Have you tried with `removeNonMutated = FALSE`? 
Let me know if it helps.

**Comment by kenasada** [comment]
Thank you very much for you feedback.
Unfortunately, no luck.
I see the same result.

**Comment by PoisonAlien** [comment]
Hi,
I can't think of any reason why would this happen. Is there any possibility of sharing some reproducible examples?

**Comment by kenasada** [comment]
Ok, I will prepare sharable and reproducible data.
I wii be out of town for a couple of days so I will work on it maybe next Monday or Tuesday.
I do keep you updated.
Thank you.

**Comment by kenasada** [comment]
Hi,
I simply added new feature "Smoking_history" in your tcga_laml_annot.tsv next to the "Overall_Survival_Status" column.
Since there are 200 samples (rows), top 1-100 samples were labeled as "Smoker" and 101-200 samples were labeled as "Never-smoker".
However, the oncoplot shows 1.13 : 1 ration (checked by my ruler) if I run the code with clinicalFeatures = 'Smoking_history'.
I think this 13% difference causes a trouble for an accurate visualization, particularly in my samples.
Would you give it a try if you can reproduce this?

**Comment by PoisonAlien** [comment]
Hi,

I dont seem to find any problems here.

```r
laml.maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #MAF file
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') #clinical data
laml = read.maf(maf = laml.maf, clinicalData = laml.clin)

laml@clinical.data$Smoking_history = rep(x = c("Smoker", "Never-smoker"), c(100, 93)) # approx. 2:2 
```

![image](https://user-images.githubusercontent.com/8164062/135821769-3ecf8951-f31c-4714-bb18-2e034d8ca3fe.png)

```r
laml@clinical.data$Smoking_history2 = rep(x = c("Smoker", "Never-smoker"), c(150, 43)) # 3:1 
```

![image](https://user-images.githubusercontent.com/8164062/135821837-7cb3ac6b-57f3-4636-825a-fef82739a2fb.png)

**Comment by kenasada** [comment]
Thank you for your quick response.
I got the same result if I run your code, suggesting there should be something wrong with my files.
I will figure out.

Thank you very much for all you have done for this troubleshooting.
