### ISSUE TITLE
Issue with reading the annovar format file

### ISSUE THREAD

**Issue by Sonia-Hook** [PoisonAlien/maftools#774]
Hi, 

I try to convert the annovar format file to MAF, but when I want to read my annovar file by this script:

```
var.annovar <- system.file("extdata", "Annotated.somatic.merged.vcf.hg19_multianno.txt", package = "maftools")
var.annovar.maf <- annovarToMaf(annovar = var.annovar, Center = 'CSI-NUS', refBuild = 'hg19',
                                tsbCol = 'Tumor_Sample_Barcode', table = 'refGene', MAFobj = TRUE)
```
 I receive the error below: 

```
Error in FUN(X[[i]], ...) : 
  Input is empty or only contains BOM or terminal control characters
```
Would you mind helping me with how to fix this error?

**Comment by PoisonAlien** [comment]
Hi,

You dont have to run the first `system.file()` command. Its only used to access the example file bundled with the package.
You can just directly pass your `Annotated.somatic.merged.vcf.hg19_multianno.txt` file to the `annovarToMaf` function.

**Comment by Sonia-Hook** [comment]
it works :)
Thanks a lot.
