### ISSUE TITLE
Oncoplot: top vs genes parameter

### ISSUE THREAD

**Issue by FriederikeHanssen** [PoisonAlien/maftools#775]
**Describe the issue**
I have a list of 435 genes of which I would like to only plot the top 10 in an Oncoplot.
However, it seems that all genes are being plotted. Is it possible to do this?

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
oncoplot(maf = laml, top = 10, genes = c("ABL1",
                                         "ABL2",
                                         "AJUBA",
                                         "AKT1",
                                         "AKT2",
                                         "AKT3",
                                         ...))
```

**Session info**
Run `sessionInfo()` and post the output below

```r
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Big Sur 11.6

Matrix products: default
LAPACK: /Users/monarchy/miniconda3/envs/test/lib/libopenblasp-r0.3.17.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.8.0

loaded via a namespace (and not attached):
[1] compiler_4.1.1     Matrix_1.3-4       tools_4.1.1        RColorBrewer_1.1-2
[5] survival_3.2-13    splines_4.1.1      grid_4.1.1         data.table_1.14.0 
[9] lattice_0.20-44   
```

**Comment by PoisonAlien** [comment]
Hi,

Your command is valid. It should just work fine and plot the ones passed to `genes`

**Comment by FriederikeHanssen** [comment]
hm, this is the output I am getting
![test](https://user-images.githubusercontent.com/12273093/135239841-1762d9f8-3ab2-479f-b495-46850d9374dc.png)
:

**Comment by PoisonAlien** [comment]
Yes, in the presence of 'genes' argument the 'top' is ignored.

If you're just interested in top ten genes, then 'top = 10' should be enough.

**Comment by FriederikeHanssen** [comment]
hm ok, then I have to find another workaround. For context, I have different oncopanels and only want to look at the genes that are present in all of them (the 435 genes) and of those only the top 10.
