### ISSUE TITLE
 could not find function "somaticInteractions"

### ISSUE THREAD

**Issue by zzygyx9119** [PoisonAlien/maftools#78]
Dear PoisonAlien,

I successfully created Oncoplot, LollipopPlot, and oncostrip using the amazing maftools. But I was stuck with the "somaticinteractions" tool which is supposed to show the cooccurring or mutually exclusive genes. I got the error saying "could not find function "somaticInteractions"".

Would you please help me out? Thanks. Although I can use oncostrip tool and do statistic analysis manually, but I would like to make the "somaticInteractions" tool work. 

Best,

Jeff

**Comment by PoisonAlien** [comment]
Hello,

It appears that you're still using older version. You can install recent version from Biocondutor or from Github.

**Comment by zzygyx9119** [comment]
Dear PoisonAlien,

Thanks a lot! I will try.

Best,

Jeff
