### ISSUE TITLE
Only one sample when reading multiple files

### ISSUE THREAD

**Issue by MjelleLab** [PoisonAlien/maftools#781]
I have a list of MAFs that I combine using the merge_maf function. However, the individual samples are not separated in the Mac object. The samples where created first by VEP on ensembl, then converted using vcf2maf. 

```

file_list = list.files(pattern="edit.line.VEP.maf$")    

```
file_list
 [1] "PANCNGS-006.edit.line.VEP.maf" "PANCNGS-048.edit.line.VEP.maf" "PANCNGS-061.edit.line.VEP.maf"
 [4] "PANCNGS-105.edit.line.VEP.maf" "PANCNGS-112.edit.line.VEP.maf" "PANCNGS-176.edit.line.VEP.maf"
 [7] "PANCNGS-178.edit.line.VEP.maf" "PANCNGS-181.edit.line.VEP.maf" "PANCNGS-185.edit.line.VEP.maf"
[10] "PANCNGS-186.edit.line.VEP.maf" "PANCNGS-189.edit.line.VEP.maf"

```
laml.mafs <- merge_mafs(file_list,verbose = T)

laml.mafs
```
```

An object of class  MAF 
                        ID summary  Mean Median
 1:             NCBI_Build  GRCh37    NA     NA
 2:                 Center       .    NA     NA
 3:                Samples       1    NA     NA
 4:                 nGenes    7130    NA     NA
 5:        Frame_Shift_Del     338   338    338
 6:        Frame_Shift_Ins     242   242    242
 7:           In_Frame_Del     222   222    222
 8:           In_Frame_Ins     143   143    143
 9:      Missense_Mutation    9467  9467   9467
10:      Nonsense_Mutation     861   861    861
11:       Nonstop_Mutation      14    14     14
12:            Splice_Site     324   324    324
13: Translation_Start_Site      19    19     19
14:                  total   11630 11630  11630
```

**Comment by PoisonAlien** [comment]
Hi @MjelleLab ,

Sorry for the late response. 
I am guessing of two possibilities, 
1. Can you check if the individual MAF files (from vcf2maf) have the column name `Tumor_Sample_Barcode`?  
2. And if the column exists, make sure they are all populated with the distinct name.
