### ISSUE TITLE
Question about the adjusted p-values reported in mafCompare

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#784]
**Describe the issue**
Hi, I am wondering what method you used for the adjusted p-values reported in mafCompare(). 

Thank you!

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,

Its [uses](https://github.com/PoisonAlien/maftools/blob/master/R/mafCompare.R#L115) `fdr`
