### ISSUE TITLE
subsetMaf Lost Columns if clinQuery Result is One Row

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#785]
One out of nine patients is not whole genome duplicated.

```r
> TCGAMAF@clinical.data
   Tumor_Sample_Barcode Purity Ploidy WGD TP53_LOH Inferred_Gender Microsatellite_Instability Group Cohort
1:       TCGA-BA-5149-P   0.52   3.10 Yes      Yes            Male                        MSS Young   TCGA
2:       TCGA-BA-6872-P   0.58   3.21 Yes      Yes            Male                        MSS Young   TCGA
3:       TCGA-BA-6873-P   0.41   3.71 Yes       No            Male                        MSS Young   TCGA
4:       TCGA-CN-4737-P   0.47   3.32 Yes      Yes            Male                        MSS Young   TCGA
5:       TCGA-CR-7382-P   0.22   2.11  No       No            Male                        MSS Young   TCGA
6:       TCGA-CV-7090-P   0.38   3.21 Yes       No            Male                        MSS Young   TCGA
7:       TCGA-CV-7180-P   0.27   3.33 Yes      Yes            Male                        MSS Young   TCGA
8:       TCGA-CV-7255-P   0.67   3.44 Yes      Yes          Female                        MSS Young   TCGA
9:       TCGA-CV-7416-P   0.64   2.63 Yes      Yes          Female                        MSS Young   TCGA
```

Subsetting by WGD, all columns except the first are lost.

```r
> TCGANotWGD <- subsetMaf(TCGAMAF, clinQuery = "WGD == 'No'")
-subsetting by clinical data..
--1 samples meet the clinical query
-Processing clinical data
> TCGANotWGD@clinical.data
   Tumor_Sample_Barcode
1:       TCGA-CR-7382-P
```

**Comment by PoisonAlien** [comment]
Thanks for the issue. Let me know if this helps.
R is such a weird language sometimes.

**Comment by shhabnsbwjd** [comment]
Facing same issue but something change

The code is not reading the column name in my clinical data
I am getting error ' subsetting by clinical data..
Error in .checkTypos(e, names_x) : 
  Object 'Histopathological_grade' not found amongst [Tumor_Sample_Barcode](url)
![Screenshot (2238)](https://user-images.githubusercontent.com/108682608/178750775-6d76d8a9-368f-46f6-ba79-8c291f6f9ebd.png)


And when I used ' laml_m4 = subsetMaf(maf = laml, clinQuery = "clinical_data$Histopathological_grade%in% 'I'")
it is giving me wrong information

**Comment by PoisonAlien** [comment]
Hi,

You dont need to say `clinical_data$Histopathological_grade`. Just use the column name.

```r
laml_m4 = subsetMaf(maf = laml, clinQuery = "Histopathological_grade%in% 'I'")
```

And make sure the column names do exist in the clinical data.

**Comment by PoisonAlien** [comment]
Is it possible to share a reproducible example?

**Comment by shhabnsbwjd** [comment]
> Is it possible to share a reproducible example?

Sorry I dont understand

**Comment by shhabnsbwjd** [comment]
Can you share a small example file with which I can reproduce your error? It is difficult for me to guess what is wrong.

here is the file 
[](url
[clinical_data.csv](https://github.com/PoisonAlien/maftools/files/9168247/clinical_data.csv)
)

**Comment by FriederikeHanssen** [comment]
Hey! I am experiencing the same issue. 

```
maf_subset <- subsetMaf(mafs_all_overlap, clinQuery  = "Treatment%in%'both'")
```

```
mafs_all_overlap@clinical.data

...
Tumor_Sample_Barcode  Normal_ID    Responder                Treatment
```

shows the column is there and I in other plots above in my script I could plot this condition.

I also tried with 
```
maf_subset <- subsetMaf(mafs_all_overlap, clinQuery  = "Treatment == 'both'")
But didn't work either. 
```
