### ISSUE TITLE
Error in (function (classes, fdef, mtable)  :    unable to find an inherited method for function ‘getSampleSummary’ for signature ‘"data.frame"’

### ISSUE THREAD

**Issue by peakdoctor** [PoisonAlien/maftools#788]
**Describe the issue**
when i use this package,the function cannot be used.
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘getSampleSummary’ for signature ‘"data.frame"’

**Command**
Please post your commands and the output (errors or any unexpected output)
commands
#figure1b
setwd("mutect")
#if (!require("BiocManager"))
#install.packages("BiocManager")
library(maftools)
thca.maf = read.csv("thca-mutect-maf.csv",header=TRUE)
plotmafSummary(maf =thca.maf, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
(.packages())#
packageVersion('maftools')

output
> #figure1b
> setwd("mutect")
> #if (!require("BiocManager"))
> #install.packages("BiocManager")
> library(maftools)
> thca.maf = read.csv("thca-mutect-maf.csv",header=TRUE)
> plotmafSummary(maf =thca.maf, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘getSampleSummary’ for signature ‘"data.frame"’
> (.packages())#
[1] "maftools"  "stats"     "graphics"  "grDevices" "utils"    
[6] "datasets"  "methods"   "base"     
> packageVersion('maftools')
[1] ‘2.10.0’

**Session info**
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by ShixiangWang** [comment]
You need to read the MAF data with `read.maf`.

**Comment by peakdoctor** [comment]
> You need to read the MAF data with `read.maf`.

thank you
