### ISSUE TITLE
GISTIC files for non-LAML cancer types

### ISSUE THREAD

**Issue by Victor-K27** [PoisonAlien/maftools#789]
Hey there! I am having trouble getting GISTIC files for breast cancer (BRCA) and other cancer types. In the example explained in Maftools (https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#references), they create the gist file using:

`all.lesions <- system.file("extdata", "all_lesions.conf_99.txt", package = "maftools")
amp.genes <- system.file("extdata", "amp_genes.conf_99.txt", package = "maftools")
del.genes <- system.file("extdata", "del_genes.conf_99.txt", package = "maftools")
scores.gis <- system.file("extdata", "scores.gistic", package = "maftools")

laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gis, isTCGA = TRUE)`

This however gets data only LAML. 

I have tried getting the GISTIC file for BRCA using: 
`gist <- getGistic("BRCA", type = "thresholded")`

I get a data frame that looks like this:
![Screenshot 2021-11-25 at 4 18 04 PM](https://user-images.githubusercontent.com/95042748/143475027-e71ee339-0873-43dd-a443-f363cfd27e95.png)

However, I cannot get the all_lesions.conf_99.txt, amp_genes.conf_99.txt, del_genes.conf_99.txt, and scores.gistic with anything I have tried. 

Does anyone know the way to get GISTIC files that work with the gisticChromPlot, gisticBubblePlot, gisticOncoPlot, and plotCBSsegments functions?

Thank you! :)

**Comment by PoisonAlien** [comment]
Hi,
`getGistic` is not a function from maftools.  
Try Borad Firehose to get the [GISTIC results](http://gdac.broadinstitute.org/runs/analyses__2016_01_28/reports/cancer/BRCA-TP/CopyNumber_Gistic2/nozzle.html).
