### ISSUE TITLE
Function genotypeMatrix is missing

### ISSUE THREAD

**Issue by SaraYones** [PoisonAlien/maftools#79]
I installed maftools in R and used read.maf to create a maf object however, I try to use  the genotypeMatrix function but it gives an error saying that "Error in genotypeMatrix(laml) : could not find function “genotypeMatrix”  i opened the source on github but i couldn’t the function i only found it in the manual. Is it missing or have you updated the package and removed it? Thanks in advance.

**Comment by PoisonAlien** [comment]
Hi,

Could you post your command and error message ? also what version of maftools are you using ? Its implemented in version >1.4.0
