### ISSUE TITLE
the latest package installed issue

### ISSUE THREAD

**Issue by honghh2018** [PoisonAlien/maftools#792]
Hi guys,
      i want to install the latest package of maftool into Centos7.3 on 4.0.3 R environment, but it was getting error lying below:
   what happen to this issue, and how to fix it
gcc version 7.3.
/usr/bin/ld: rANS_static.o: access beyond end of merged section (1194)
/usr/bin/ld: rANS_static.o: access beyond end of merged section (1200)
/usr/bin/ld: rANS_static.o: access beyond end of merged section (1189)
/usr/bin/ld: /share/nas1/Data/software/R/R-4.0.2/lib64/R/library/Rhtslib/usrlib/libhts.a(rANS_static.o)(.debug_info+0xbe3): reloc against `.text': error 2
/usr/bin/ld: final link failed: output unrepresentable sections 
collect2: error：ld return 1
make: *** [maftools.so] error 1
Best,
hanhuihong

**Comment by ShixiangWang** [comment]
It's a strange problem I never see before~ A quick workaround is installing an independent Conda environment with R4.0.3 and then installing the maftools. Hope @PoisonAlien have better solution :).

**Comment by honghh2018** [comment]
@ShixiangWang  thanks the reply. but i hope to run the maftools on Rstudio. the conda environment can not wok with conda.
But Thanks, i would try in the virtual envitonment

**Comment by PoisonAlien** [comment]
I have too never seen such an error. Maybe try @ShixiangWang 's suggestion.
Also were you trying to install from Bioconductor?

**Comment by ShixiangWang** [comment]
> @ShixiangWang thanks the reply. but i hope to run the maftools on Rstudio. the conda environment can not wok with conda. But Thanks, i would try in the virtual envitonment

You can include extra R library from conda environment in your RStudio.

**Comment by ShixiangWang** [comment]
And, maybe you can use the repository https://packagemanager.rstudio.com/client/#/repos/4/overview to directly install binary release of R package.
