### ISSUE TITLE
twosampleMR package, etc disappeared

### ISSUE THREAD

**Issue by HelenJung80** [PoisonAlien/maftools#793]
I would like to know whether some packages can disappears with time.
Several month ago, I installed packages named as twosampleMR and tryx.
But, I tried to install those at another computer, a message of "the package does not exist" "Not available" appears.
Can it happen?

**Comment by DarioS** [comment]
Yes, typically if you upgrade R, R will create a new folder for packages to be stored in. So, it won't see the folder of packages that were previously used in an older version of R. How does your question relate to maftools, though?
