### ISSUE TITLE
somaticinteraction : how DEL type make infomation miss?

### ISSUE THREAD

**Issue by pengbo233** [PoisonAlien/maftools#795]
### **grep TP53 maf.xls |cut -f1,10,11,12,13,16**
TP53    SNP     G       G       T       10007
TP53    SNP     G       G       A       07007
TP53    SNP     A       A       G       01023
TP53    SNP     C       C       T       01050
TP53    SNP     C       C       G       06003
TP53    SNP     G       G       T       01043
TP53    SNP     G       G       T       10010
TP53    SNP     G       G       T       10006
TP53    SNP     G       G       A       12005
TP53    SNP     A       A       T       12009
TP53    SNP     G       G       T       04004
TP53    SNP     G       G       A       07002
TP53    SNP     T       T       A       01035
TP53    SNP     G       G       A       01013
TP53    SNP     A       A       T       04001
TP53    SNP     G       G       A       01028
TP53    SNP     A       A       G       01029
TP53    SNP     T       T       C       01027
TP53    SNP     G       G       T       01030
TP53    SNP     G       G       T       03001
TP53    SNP     T       T       A       01012
TP53    SNP     G       G       A       01011
TP53    SNP     G       G       A       01018
TP53    SNP     G       G       C       01001
TP53    SNP     C       C       T       01007
TP53    SNP     G       G       T       01002
TP53    SNP     A       A       T       10011
TP53    SNP     T       T       A       10009
TP53    DEL     T       T       -       01015
TP53    DEL     GT      GT      -       01034
TP53    DEL     G       G       -       15001

### ****grep EGFR maf.xls |cut -f1,10,11,12,13,16
EGFR    SNP     A       A       G       01019
EGFR    INS     -       -       TGGCCAGCG       07007
EGFR    INS     -       -       ACCCCCACC       01023
EGFR    INS     -       -       TGGCCAGCG       01039
EGFR    INS     -       -       CCA     01050
EGFR    INS     -       -       CATCCCCAT       06003
EGFR    INS     -       -       TGGCCAGCG       01043
EGFR    INS     -       -       TGGCCAGCG       05010
EGFR    INS     -       -       CACGTG  10010
EGFR    INS     A       A       GGTT    10006
EGFR    INS     -       -       ACCCCC  12005
EGFR    INS     ACCCC   ACCCC   ACCCTCACCCT     13003
EGFR    INS     -       -       TGGCCAGCG       12009
EGFR    INS     GACAA   GACAA   GGCGGCAC        04004
EGFR    INS     -       -       CAGCGTGGA       06002
EGFR    INS     -       -       ACAACA  14003
EGFR    INS     -       -       CCA     14004
EGFR    INS     -       -       ACAACCCCC       01021
EGFR    INS     -       -       TGGCCAGCG       01015
EGFR    INS     -       -       ACCCCC  12007
EGFR    INS     -       -       TGGCCAGCG       07002
EGFR    INS     -       -       GCCAGCGTT       15003
EGFR    INS     -       -       TGGCCAGCG       01035
EGFR    INS     ACAACCCCT       ACAACCCCT       ACAACCACAACCCCT 05001
EGFR    INS     -       -       GTT     01024
EGFR    INS     -       -       CCA     01034
EGFR    INS     -       -       CAGCGTGGA       07004
EGFR    INS     -       -       TGGCCAGCG       01013
EGFR    INS     -       -       TGGCCAGCG       04001
EGFR    INS     -       -       TGGCCAGCG       01028
EGFR    INS     -       -       CAGCGTGGA       01029
EGFR    INS     -       -       CCA     01027
EGFR    INS     -       -       ACCCCC  01004
EGFR    INS     -       -       ACCCCCACCCCC    15001
EGFR    INS     -       -       CAGCGTGGA       01019
EGFR    INS     -       -       ACCCCC  03001
EGFR    INS     -       -       ACAACCCCC       01012
EGFR    INS     -       -       TGGCCAGCG       01020
EGFR    INS     -       -       CAGCGTGGA       01011
EGFR    INS     -       -       TGGCCAGCG       01018
EGFR    INS     -       -       GTC     01001
EGFR    INS     -       -       TGGCCAGCG       01007
EGFR    INS     -       -       CAGCGTGGA       01002
EGFR    INS     -       -       CAGCGTGGA       10011
EGFR    INS     -       -       GGG     10009
EGFR    CNV                             01050
EGFR    CNV                             04004
EGFR    CNV                             01034
EGFR    CNV                             01028
EGFR    CNV                             01027
EGFR    CNV                             01018
EGFR    CNV                             01002
EGFR    CNV                             10011

if I remove 
TP53    DEL     T       T       -       01015
TP53    DEL     GT      GT      -       01034
TP53    DEL     G       G       -       15001
from maf.xls

grep EGFR somaticInteractions.pairwise.tsv|grep TP53 
EGFR    TP53    0.125   0       3       NA      28      1       Mutually_Exclusive

but if I add TP53_DEL info ,
grep EGFR somaticInteractions.pairwise.tsv|grep TP53 

there is nothing about TP53 dna EGFR interaction,this is missing

what is requests for maf mutation type in them same gene in somaticinteraction() ?
Only SNP?
DEL must be filter from maf.xls?

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the late reply. What does the plot look like? Do you see TP53 and EGFR in both cases?
Also, note that by default the function uses the top 25 genes. You can increase it (with the `top` argument)  and see if the pair shows up.
