### ISSUE TITLE
minMut in oncoplot not working

### ISSUE THREAD

**Issue by nygr** [PoisonAlien/maftools#796]
I am plotting an oncoplot for certain genes, but would like to add criteria of minMut=4, however this is not working when I have genes= mylist in the oncoplot function, it plots all those genes even if there are no mutations. When I remove the genes list and use only minMut it works. 

My genes list is over 700 genes so would be super helpful if it could automatically not plot the ones without x mutations

**Command**
oncoplot(tn_t_maf,genes=genestoplot, minMut=4, writeMatrix = F,
         clinicalFeatures = c("Malignancy", "Group"), sortByAnnotation = T,
 fontSize = 0.4, sepwd_genes = 0.7)

**Comment by ShixiangWang** [comment]
@nygr  You can adapt your gene list to keep only genes with mutations:

```r
genelist = genelist[genelist %in% maf@gene.summary[, .N, by = Hugo_Symbol]$Hugo_Symbol]
```

**Comment by PoisonAlien** [comment]
@nygr Yes, you can filter the output from `getGeneSummary` according to the way you want and just plot the resulting genes.

Thanks, @ShixiangWang for answering many issues. Much appreciated :)
