### ISSUE TITLE
lollipopPlot2

### ISSUE THREAD

**Issue by rajkump** [PoisonAlien/maftools#798]
Hi Anand,
      I could not label the 'HGVSp_Short' fields in lollipopPlot2. I wanted to highlight few mutated loci so I made use of m1_label parameter to show few fields like c("p.H179D", "p.X225_splice") but end up getting a warning like the following,

````
Position p.H179D doesn't seem to be mutated. Here are the mutated foci.Position p.X225_splice doesn't seem to be mutated. Here are the mutated foci. 


Please note, I made sure to use AACol1 = "HGVSp_Short" and also that these mutated loci are present when I did m1_label = "all". 

In addition, the error/warning message  did not list the loci at the end of the sentence "Here are the mutated foci."

Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. Please do note that splice site mutations are often located within 2-3 bps of the CDS and hence can not be mapped onto the protein structure. Hence the error.

**Comment by rajkump** [comment]
Hi Anand,
    Thanks for the reply. These mutations are labelled when I use "m1_label=all" but not when I use "m1_label=c("p.H179D", "p.X225_splice") ". 

I do not think this is only related to splice mutations. Please let me know how can one label only few of the interested mutations. 

From the doc I see
m1_label Amino acid positions to label for m1 cohort. If ’all’, labels all variants. 
**[all works but how can we give only interested positions]**
m2_label Amino acid positions to label for m2 cohort. If ’all’, labels all variants

For example, in the lollipopPlot2 I would like to label only unique mutations on each side. I identified unique mutations from the 'HGVSp_Short' field of two maf files I am using for lollipopPlot2. Hence, I am using these few mutations for label like 'm1_label=c("p.H179D", "p.X225_splice") ' and 'm2_label = c("p.R190K")' but I am getting warning 'these are not mutated'. I am thinking that there should be a format I am suppose to use which I am missing. 

```
lollipopPlot2(
       m1 = maf.1,
       m2 = maf.2,
       gene = "TP53",
       AACol1 = "HGVSp_Short",
       AACol2 = "HGVSp_Short",
       m1_name = "Relapsed",
       m2_name = "Relapse free",
       m1_label = "all", #--all works but not when I do m1_label=c("p.H179D", "p.X225_splice")
       m2_label = "all",
       refSeqID = "NM_000546",
       proteinID = NULL,
       labPosAngle = 45,
       labPosSize = 1.5,
       colors = NULL,
       alpha = 1,
       axisTextSize = c(2, 2),
       pointSize = 2,
       roundedRect = TRUE,
       showDomainLabel = TRUE,
       domainBorderCol = "black",
       domainLabelSize = 2,
       legendTxtSize = 2,
       verbose = TRUE
     )

**Comment by PoisonAlien** [comment]
Hi,

The `label ` argument takes the position as input. It should be a numeric value.

e.g; `c(179, 225)` and not `c("p.H179D", "p.X225_splice")`

```r
lollipopPlot2(m1 = primary.apl, m2 = relapse.apl, gene = "FLT3",AACol1 = "amino_acid_change", AACol2 = "amino_acid_change", m1_name = "Primary", m2_name = "Relapse", m1_label = 835)
```

Hope this helps.

**Comment by rajkump** [comment]
Thank you very much. Can't wait to try out.
