### ISSUE TITLE
Genes in plotApobecDiff bar chart

### ISSUE THREAD

**Issue by mcewenrk** [PoisonAlien/maftools#80]
Hello,

Thanks for releasing a superb package. The plotApobec functionality is a great addition.

However, when I compare the top genes listed when plotApobecDiff is run, the pvalues reported are not the same as indicated by the asterisks in the bar chart in the bottom right panel of the associated figure.
I think the order in which the genes are sorted in the bar chart does not match the order in the table. 

For example,

Hugo_Symbol | Enriched | nonEnriched | pval
PIK3CA | 23 | 6 | 0.003589
TP53 | 61 | 35 | 0.004674
PIK3C2G | 7 | 0 | 0.015608
TSC2 | 9 | 1 | 0.021434
SLIT2 | 6 | 0 | 0.031248
CIC | 8 | 1 | 0.039047
...

Compare the pvalues above with the asterisks marking the genes in the bar chart; it would appear that the gene names have been incorrectly associated perhaps? PIK3CA should have "**" while CIC should have only one and yet this is swapped in the bar chart.
![apobec](https://user-images.githubusercontent.com/23632457/32454502-4cc31b66-c317-11e7-8f32-5b18dc4eeb4f.png)

**Comment by PoisonAlien** [comment]
Hi,

Thank for reporting and yes it appears to be the case! Also side boxplot showing mutation load seems to include synonymous mutations as well. I will fix it soon.

**Comment by PoisonAlien** [comment]
Hi,
Thanks again. I have fixed the issue. You can install recent version from GitHub and try.

**Comment by mcewenrk** [comment]
Fantastic - works for me -thanks!
