### ISSUE TITLE
Forest Plot P-values

### ISSUE THREAD

**Issue by Victor-K27** [PoisonAlien/maftools#801]
Hi all, 

When using the forestPlot function to plot results from mafCompare (Fisher's exact test) we can select the P-value threshold with the P-val argument. 

However, this does not consider the adjusted P-value. Is there any way to use the adjusted P-value instead?

```
fisher_test <- mafCompare(m1= sample_1_maf, m2= sample_2_maf, m1Name= "Sample1", m2Name= "Sample2", minMut = 5)
print(fisher_test)
forestPlot(mafCompareRes = fisher_test, pVal = 0.05)
```

Thank you for your time and consideration

**Comment by ShixiangWang** [comment]
@Victor-K27 

`forestPlot` has a specified argument for adjusted p value called `fdr`.

```r
> forestPlot
function (mafCompareRes, pVal = 0.05, fdr = NULL, color = c("maroon", 
    "royalblue"), geneFontSize = 0.8, titleSize = 1.2, 
    lineWidth = 1) 
```
