### ISSUE TITLE
Oncoplot order of panels

### ISSUE THREAD

**Issue by rajkump** [PoisonAlien/maftools#808]
Hi Anand,
    I would like to change the order of Oncoplot like annotation on top, and then the mutations plot and then the TMB? Please let me know of this. 

 I have another quick question regarding TMB. What will be capture size to use for WGS data? I have seen efforts to compute TMB from VCF files of individual samples. Will this be any different from TMB calculation from MAF file? Technically it should not be different right.

Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Hi,

1. Unfortunately It is not possible to reorder the panels :|
2. TMB is calculated for coding/exonic regions. So it depends on how you estimate it. 50MB should be fine IMO (going by recent WXS Agilent capture KIT). You could also get the recent GTF file from the ensemble and estimate the length of total exonic regions.

**Comment by rajkump** [comment]
Thanks for the reply. Thanks for your time again. Keep the great work going. Cancer patients in the future will benefit from your work.

Thanks,
Praveen
