### ISSUE TITLE
Move Oncoplot annotations to the top 

### ISSUE THREAD

**Issue by antonio-marra** [PoisonAlien/maftools#809]
Hello,
I was wondering if it would be possible to add a command that allows to move the phenobar(s) with annotations from the bottom to the top of the oncoplot. I'm trying to debug(oncoplot) and step through it but it would be great to have an easy command to do that.

Thanks so much,
Antonio

**Comment by PoisonAlien** [comment]
Hi,

Unfortunately, it is not possible to re-order the panels. I would like to make it an option but not anytime soon :|
