### ISSUE TITLE
How to merge multiple MAF files into a single MAF files? How to create sample/tumor_sample_barcode in MAF? 

### ISSUE THREAD

**Issue by Jwang412** [PoisonAlien/maftools#81]
Hi, I am new to use maftools. I have problems about input data files. 
Could you help me how to merge MAFs from all samples into a single MAF? And how to create sample/tumor_sample barcode in MAF? 
Many thanks!

**Comment by PoisonAlien** [comment]
Hi,
Have you already generated MAF files ? If so, it should contain tumor_sample_barcode column.

**Comment by Jwang412** [comment]
Hi,
I have already generated MAF files. I can find the tumor_sample_barcode in MAF file.
But I have another problem. How do I read the MAF file?
I try to use these code:
` source("https://bioconductor.org/biocLite.R")`
Bioconductor version 3.6 (BiocInstaller 1.28.0), ?biocLite for help

`biocLite("maftools")`
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.2 (2017-09-28).
Installing package(s) ‘maftools’
try URL 'https://bioconductor.org/packages/3.6/bioc/bin/windows/contrib/3.4/maftools_1.4.0.zip'
Content type 'application/zip' length 12863554 bytes (12.3 MB)
downloaded 12.3 MB

package ‘maftools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\josie.wang\AppData\Local\Temp\Rtmpkb8iQn\downloaded_packages
installation path not writeable, unable to update packages: mgcv

 `library(maftools)`

error: package or namespace load failed for ‘maftools’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘circlize’

 `df <- read.maf("CBCP00001-R1.maf", removeSilent = TRUE, useAll = FALSE)`

Error in read.maf("CBCP00001-R1.maf",  : 
  no this function "read.maf"  

I am pretty new to use bioconduter and cancer field for detecting significant somatic mutation variants.
Could you tell me how to conduct maftools?
Many thanks.

**Comment by Jwang412** [comment]
Hi, my another question is how to merge multiple MAF file into a single MAF file?

**Comment by PoisonAlien** [comment]
Hi, 
MAF files are just tab delimited text files, so you can simple use cat command from terminal to append all files into a single file.

Regarding using maftools, no need to use removeSilent = TRUE as it has been deprecated. What version of the maftools are you using ? See maftools [Vignette](http://www.bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html) for a complete case study.

**Comment by Huffyphenix** [comment]
Hi, how to combine mutiple MAF objects into one in R?

**Comment by Patmedi** [comment]
In my case, I used a cat command to merge multiple MAF files into one. I used:    cat */*.maf > filename.maf
I hope you find it useful.

**Comment by Patmedi** [comment]
In my case, I used a cat command to merge multiple MAF files into one. I used: cat */*.maf > filename.maf
I hope you find it useful.

**Comment by PoisonAlien** [comment]
Hello,
For now there is no function in maftools to do so. You can merge them into a single MAF with unix cat command and process it.

**Comment by HChen1216** [comment]
> Hello,
> For now there is no function in maftools to do so. You can merge them into a single MAF with unix cat command and process it.

Hi, I'm trying to use the merge_mafs() function to merge multiple maf files into a single MAF. however, it returned "Error in merge_mafs() : could not find function "merge_mafs"". It confused me because when I ?merge_mafs, it really returned the information of this function. I guess whether it's due to the warning messages when I library the maftools as below:

Warning messages:
1: no function found corresponding to methods exports from ‘GenomicRanges’ for: ‘concatenateObjects’ 
2: no function found corresponding to methods exports from ‘GenomicAlignments’ for: ‘concatenateObjects’ 

Any help would be greatly appreciated!

Many thanks!

**Comment by HChen1216** [comment]
Hi, I was trying to use the merge_mafs() function in maftools package to merge multiple maf files into a single MAF. However, it returned "Error in merge_mafs() : could not find function "merge_mafs"". It confused me because when I ?merge_mafs, it really returned the information of this function. I guess whether it's due to the warning messages when I library the maftools:

Warning messages:
1: no function found corresponding to methods exports from ‘GenomicRanges’ for: ‘concatenateObjects’
2: no function found corresponding to methods exports from ‘GenomicAlignments’ for: ‘concatenateObjects’

Any help would be greatly appreciated!

Many thanks!

**Comment by PoisonAlien** [comment]
Hi, 
Could you post your sessionInfo ? I wonder if you're still using an older version.
Also could you try calling merge_maf usinf namespace ? e.g, `maftools::merge_mafs()`

Let me know.

**Comment by HChen1216** [comment]
Hi, thank you for your reply! 
> maftools::merge_mafs()
Error: 'merge_mafs' is not an exported object from 'namespace:maftools'
> sessionInfo()
R version 3.5.3 (2019-03-11)
other attached packages:
[1] maftools_1.8.0      Biobase_2.42.0      BiocGenerics_0.28.0

**Comment by HChen1216** [comment]
Hi, thank you for your reply! I tried maftools::merge_mafs() before, but it didn't work.

maftools::merge_mafs()
Error: 'merge_mafs' is not an exported object from 'namespace:maftools'

sessionInfo()
R version 3.5.3 (2019-03-11)
other attached packages:
[1] maftools_1.8.0 Biobase_2.42.0 BiocGenerics_0.28.0

And then I installed the latest version (maftools_1.8.10) from Bioconductor, merge_mafs() still can not be used.

> library(maftools)
> merge_mafs()
Error in merge_mafs() : could not find function "merge_mafs"
> maftools::merge_mafs()
Error: 'merge_mafs' is not an exported object from 'namespace:maftools'

Thanks!

**Comment by PoisonAlien** [comment]
Hi, 
You're using older version of maftools. Could you try to install from GitHub and try again ?

**Comment by HChen1216** [comment]
Hi, thank you. The version is maftools_1.99.60 now. 

> library(maftools)
> merge_mafs()
Error in merge_mafs() : could not find function "merge_mafs"
> maftools::merge_mafs()
Error: 'merge_mafs' is not an exported object from 'namespace:maftools'
> ?merge_mafs()
starting httpd help server ... done
> sessionInfo()
R version 3.5.3 (2019-03-11)
other attached packages:
[1] maftools_1.99.60    Biobase_2.42.0      BiocGenerics_0.28.0

**Comment by PoisonAlien** [comment]
Hello,
Sorry for the late response. Do you still have the issue ?

**Comment by HChen1216** [comment]
Hi,

Yeah, this function still doesn't work. I used the cat command instead to combine all MAF files.

Thanks!

**Comment by PoisonAlien** [comment]
Oh no! I just realised I never exported this function :|  No wonder you can't access it.
But you can still access it with `:::` namespace. `maftools:::merge_mafs()`.

I am so sorry and thanks for opening the issue, I will update it in later versions.

**Comment by HChen1216** [comment]
Hi,
Thank you so much for your update! Right, maftools:::merge_mafs() works! :)

**Comment by biobug16** [comment]
Can any of you please guide how can I add sample/tumor_sample barcode in already generated MAF?

**Comment by PoisonAlien** [comment]
Hi,
If you have already generated the MAF, it should already have the `Tumor_Sample_Barcode` column.

**Comment by biobug16** [comment]
@PoisonAlien ,
Yes it has. But all my samples have same string “Tumor” in that column. Can i replace it with the sample name, as I want merge all these MAF in-order to make an oncoplot.

**Comment by PoisonAlien** [comment]
If you have used `mergeMafs` for merging, can you check if your (merged) maf has a column called `Source_MAF`? Maybe you can use it as a sample name by renaming it to `Tumor_Sample_Barcode`

**Comment by biobug16** [comment]
Hi @PoisonAlien 
After merging 3 MAF files into 1, I got following columns in my merged MAF:
```
maf_1@data$Hugo_Symbol
maf_1@data$Entrez_Gene_Id
maf_1@data$Center
maf_1@data$NCBI_Build
maf_1@data$Chromosome
maf_1@data$Start_Position
maf_1@data$End_Position
maf_1@data$Strand
maf_1@data$Variant_Classification
maf_1@data$Variant_Type
maf_1@data$Reference_Allele
maf_1@data$Tumor_Seq_Allele1
maf_1@data$Tumor_Seq_Allele2
maf_1@data$dbSNP_RS
maf_1@data$dbSNP_Val_Status
maf_1@data$Tumor_Sample_Barcode
maf_1@data$Matched_Norm_Sample_Barcode
maf_1@data$Match_Norm_Seq_Allele1
maf_1@data$Match_Norm_Seq_Allele2
maf_1@data$Tumor_Validation_Allele1
maf_1@data$Tumor_Validation_Allele2
maf_1@data$Match_Norm_Validation_Allele1
maf_1@data$Match_Norm_Validation_Allele2
maf_1@data$Verification_Status
maf_1@data$Validation_Status
maf_1@data$Mutation_Status
maf_1@data$Sequencing_Phase
maf_1@data$Sequence_Source
maf_1@data$Validation_Method
maf_1@data$Score
maf_1@data$BAM_File
maf_1@data$Sequencer
maf_1@data$Tumor_Sample_UUID
maf_1@data$Matched_Norm_Sample_UUID
maf_1@data$HGVSc
maf_1@data$HGVSp
maf_1@data$HGVSp_Short
maf_1@data$Transcript_ID
maf_1@data$Exon_Number
maf_1@data$t_depth
maf_1@data$t_ref_count
maf_1@data$t_alt_count
maf_1@data$n_depth
maf_1@data$n_ref_count
maf_1@data$n_alt_count
maf_1@data$all_effects
maf_1@data$Allele
maf_1@data$Gene
maf_1@data$Feature
maf_1@data$Feature_type
maf_1@data$Consequence
maf_1@data$cDNA_position
maf_1@data$CDS_position
maf_1@data$Protein_position
maf_1@data$Amino_acids
maf_1@data$Codons
maf_1@data$Existing_variation
maf_1@data$ALLELE_NUM
maf_1@data$DISTANCE
maf_1@data$STRAND
maf_1@data$SYMBOL
maf_1@data$SYMBOL_SOURCE
maf_1@data$HGNC_ID
maf_1@data$BIOTYPE
maf_1@data$CANONICAL
maf_1@data$CCDS
maf_1@data$ENSP
maf_1@data$SWISSPROT
maf_1@data$TREMBL
maf_1@data$UNIPARC
maf_1@data$RefSeq
maf_1@data$SIFT
maf_1@data$PolyPhen
maf_1@data$EXON
maf_1@data$INTRON
maf_1@data$DOMAINS
maf_1@data$GMAF
maf_1@data$AFR_MAF
maf_1@data$AMR_MAF
maf_1@data$ASN_MAF
maf_1@data$EAS_MAF
maf_1@data$EUR_MAF
maf_1@data$SAS_MAF
maf_1@data$AA_MAF
maf_1@data$EA_MAF
maf_1@data$CLIN_SIG
maf_1@data$SOMATIC
maf_1@data$PUBMED
maf_1@data$MOTIF_NAME
maf_1@data$MOTIF_POS
maf_1@data$HIGH_INF_POS
maf_1@data$MOTIF_SCORE_CHANGE
maf_1@data$IMPACT
maf_1@data$PICK
maf_1@data$VARIANT_CLASS
maf_1@data$TSL
maf_1@data$HGVS_OFFSET
maf_1@data$PHENO
maf_1@data$MINIMISED
maf_1@data$ExAC_AF
maf_1@data$ExAC_AF_AFR
maf_1@data$ExAC_AF_AMR
maf_1@data$ExAC_AF_EAS
maf_1@data$ExAC_AF_FIN
maf_1@data$ExAC_AF_NFE
maf_1@data$ExAC_AF_OTH
maf_1@data$ExAC_AF_SAS
maf_1@data$GENE_PHENO
maf_1@data$FILTER
```

But cannot locate the Source_MAF column in it. 
Please have a look.

**Comment by PoisonAlien** [comment]
Can you post your command? Also are you merging `maf` objects or `files`?

**Comment by biobug16** [comment]
Here are these
```
sam1_syn4985519_maf <- read.maf(maf ="tumorVsNormal_pat1_tumor_syn4985378_vs_norm_syn4985519.maf.gz", useAll = T, verbose = T)
sam1_syn4985596_maf <- read.maf(maf ="tumorVsNormal_pat1_tumor_syn4985596_vs_norm_syn4985519.maf.gz", useAll = T, verbose = T)
sam1_syn4987466_maf <- read.maf(maf ="tumorVsNormal_pat1_tumor_syn4987466_vs_norm_syn4985519.maf.gz", useAll = T, verbose = T)

maf_1=maftools:::merge_mafs(maf=c(sam1_syn4985519_maf,sam1_syn4985596_maf,sam1_syn4987466_maf), verbose = TRUE)

```

**Comment by PoisonAlien** [comment]
No need to perform first three steps. Just pass all your `maf.gz` to `merge_mafs` function. Let me know if you still have issues (which I think will be the case :|)

**Comment by biobug16** [comment]
Ok will try and update you on this.
Thanks!

**Comment by biobug16** [comment]
Hi @PoisonAlien 
Thank you, now I can see the **Source_MAF** after merging files instead of MAF object.

I have another question related to oncoplot(), I am using following command to rename my samples: 
`maf_merged@data$Tumor_Sample_Barcode=maf_merged@data$Source_MAF`

Will that be enough or do I need change something else before parsing the maf_merged object to oncoplot()?

**Comment by PoisonAlien** [comment]
This should work just fine. You may want to do the same for `maf_merged@maf.silent` slot.

**Comment by camcecc** [comment]
> No need to perform first three steps. Just pass all your `maf.gz` to `merge_mafs` function. Let me know if you still have issues (which I think will be the case :|)

Hi @PoisonAlien could you please share a way to pass many mafs into the merge_mafs function? I have more than 40 mafs, and the merging works only if I write them by hand...
Like, this works just perfectly:
```
merged <- merge_mafs(c(PRM_ICH_1,PRM_ICH_15))
```

But I can't make it work in a loop:

```
for(i in names){
  maf_merged_08092021 <- merge_mafs(i)
  return(maf_merged_08092021)
}
```
where "names" is the samples names' list that worked perfectly in the 40 mafs import into R.

**Comment by PoisonAlien** [comment]
Hi,
You could just grep all the files maf files with `list.files` and pass them to the `merge_mafs`

```r
```

**Comment by bobojin46** [comment]
> If you have used `mergeMafs` for merging, can you check if your (merged) maf has a column called `Source_MAF`? Maybe you can use it as a sample name by renaming it to `Tumor_Sample_Barcode`

Hi, I am trying to merge all the MAFs in-order to make an oncoplot but get an error. Can you please help me with that? 

code
`#change the Tumor_Sample_Barcode to what I want to show
hcc_merge_all_copy@data$Tumor_Sample_Barcode = hcc_merge_all_copy@data$Source_MAF
hcc_merge_all_copy@data$Tumor_Sample_Barcode <- gsub("_.*", "", hcc_merge_all_copy@data$Tumor_Sample_Barcode)

#determine the final order what I want to show
sample_order <- gsub("_.*", "", mafs)
sample_order <- substr(sample_order, start = 3, stop = nchar(sample_order))
<img width="371" alt="sample_order" src="https://github.com/PoisonAlien/maftools/assets/134360034/60775f7c-4396-400e-9015-729567d1aa6c">

#draw 
pdf("./waterfall_rename_4.pdf", bg="white",height = 5,width = 7)
oncoplot(hcc_merge_all_copy,
         showTumorSampleBarcodes = T,sampleOrder = sample_order)
dev.off()
[waterfall_rename_4.pdf](https://github.com/PoisonAlien/maftools/files/13601985/waterfall_rename_4.pdf)
 `

I use the orignal maf object and the Tumor_Sample_Barcode renamed maf object to draw oncoplots respectively. The latter one miss the bar chat showing TMB.
