### ISSUE TITLE
Oncoplot omits samples

### ISSUE THREAD

**Issue by rmnsimonyan** [PoisonAlien/maftools#811]
Hello!:) 

I am making oncoplots for a number of cancer patients, and I encounter the following issue all the time: some samples get automatically removed by the program, even when I set removeNonMutated=F, fill=T. Some of my annovar-annotated files are empty, because no mutations have been detected. Would that be reason or there is something else I am not taking into account? I am aiming for all the samples, even the ones without any mutations to be included in the plot. I would greatly appreciate any advice on this.

Thank you!
Arman

**Comment by PoisonAlien** [comment]
Hello Arman,

The easiest fix would be adding a dummy synonymous variant to the empty annovar files. That should add them to the plot and wont affect much of the analysis.

**Comment by nuttynutmore** [comment]
Hi there,

Thanks for such a great and easy to use tool, with very visually appealing results.

I am also experiencing the issue of non-mutated samples being omitted from oncoplots, despite using removeNonMutated = FALSE, fill = TRUE.  I have noted the use of dummy synonymous mutations as a workaround, however, as my pipeline is clinical grade, this is not professionally acceptable.  I note this issue has been open for nearly 18 months now- do you have any solutions planned for future releases of maftools?

Kind regards,
nuttynutmore
