### ISSUE TITLE
Changing labels of clinical features in oncoplot

### ISSUE THREAD

**Issue by stegosaurus12** [PoisonAlien/maftools#812]
Hi!

I am trying to change the labels for some clinical features after making an oncoplot. I was not able to find an argument within oncoplot to specify a list to customize labels similar to how you can customize colors for clinical features within oncoplot.

Thanks for your help!

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. I overlooked it. Unfortunately, it is not possible to do so. The only way would be to change the column names in the clinical annotation data the way you want it to be. Hope this helps.
