### ISSUE TITLE
somaticInteractions p-values multiple correction

### ISSUE THREAD

**Issue by ahwanpandey** [PoisonAlien/maftools#813]
Hello,

Do the somaticInteractions p-values need to be FDR adjusted?

Thanks,
Ahwan

**Comment by PoisonAlien** [comment]
Hi,
Yes, it would be ideal to do so.

**Comment by ahwanpandey** [comment]
Thanks. Maybe a future feature to add to the function so it outputs and plots adjusted p-values? I don't think I can plot the adjusted p-values with the current plot can i?

**Comment by PoisonAlien** [comment]
Thanks for the suggestion. For now, it is not possible to plot the adj p vals. However it is not difficult to implement, I will make the changes and let you know soon.

**Comment by ahwanpandey** [comment]
Thanks so much. Helpful and prompt as always!

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue again. I have pushed the changes. Could you please try it out and let me know if it works?
You will have to use the new argument `plotPadj = TRUE`.

**Comment by Silamp** [comment]
Hello :)
I think there is a slight mistake in line 236 of the code. In both line 234 and 236 it says paste "fdr" when it should say raw-pvalue in 236 I guess. At the moment, fdr is depicted on the plot no matter if plotPadj = TRUE or FALSE.

![somatic interactions](https://user-images.githubusercontent.com/101824642/159243562-06a65ce0-3568-4bd2-9f03-32500a1d3cb2.jpeg)

**Comment by PoisonAlien** [comment]
Hi,
Thanks for going through the code. The plots are generated as expected, only the labels were wrong. 
I have fixed it.

**Comment by ahwanpandey** [comment]
Hi, I can't seem to install maftools from gihub as I get similar errors as the post here:

https://github.com/PoisonAlien/maftools/issues/759

![image](https://user-images.githubusercontent.com/8450532/161162558-20aa8b23-c11c-40f8-a110-907ae11ac841.png)

Thanks.

**Comment by kandabarau** [comment]
my issue is somehow related.

**pltoPadj = TRUE** crashes somaticInteractions() on freshly github istalled maftools

packageVersion("maftools")
[1] ‘2.12.5’

 somaticInteractions(amlmds_maf, plotPadj = TRUE)
Error in `[.data.frame`(interactionsFDR, rownames(interactions), colnames(interactions)) : 
  undefined columns selected

is this working on your side?

Bests,
Sergey

**Comment by nfarnoud** [comment]
> my issue is somehow related.
> 
> **pltoPadj = TRUE** crashes somaticInteractions() on freshly github istalled maftools
> 
> packageVersion("maftools") [1] ‘2.12.5’
> 
> somaticInteractions(maf, plotPadj = TRUE) Error in `[.data.frame`(interactionsFDR, rownames(interactions), colnames(interactions)) : undefined columns selected
> 
> is this working on your side?
> 
> Bests, Sergey

Hi Sergey, Were you able to figure out the issue? I'm having the exact same error.
