### ISSUE TITLE
Oncoplot.R - leftBarData - Customisation

### ISSUE THREAD

**Issue by HHayman** [PoisonAlien/maftools#816]
Heylo

I am adding hazard ratios to an oncoplot, for each of the genes, and have been trying to find a way to conditionally colour the bars and add tick marks (specifically at '1'). Specifically, I would be colouring them on a threshold of 1, to clearly indicate lower/higher hazard. However, that I can tell I can't edit the side barplots in any way - would this be possible to include, please?

I did have a go myself but realised I can't just override the Oncoplot function and I'll need to pull etc, and wanted to see if it was easy enough to do from your end. Happy to have a go myself though :)

Thank you!

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue. I think it is doable. I will try to implement it and let you know. It might take a while though.

**Comment by HHayman** [comment]
Okidoki, that's great. Thank you! :)
