### ISSUE TITLE
gisticChromPlot annotation discrepancy 

### ISSUE THREAD

**Issue by brewert2** [PoisonAlien/maftools#821]
I am using gistic2 results to feed into maftools.

When I plotted my data, one gene showed up in red at the bottom (indicating amplification). However, this gene is not mentioned in the list which appears in the console. When I check the original gistic2 output (amp_genes.conf_95), this particular gene is not even listed.  Please advise why I see this discrepancy? 

Also, a couple of genes are supposed to be significant (deletion) but it shows up in black (indicating not significant) in the plot. 
Would you please explain why there are discrepancies? 

47:      NOTCH1  9      136496100    136757900   neutral  0.678823
48:      NOTCH1  9      136459985    136509720       Del  5.050682

59:      PTPN22   1      113819496    113852100   neutral  0.000000
60:      PTPN22   1      113682400    114128032         Del  1.571459

Thank you.

**Comment by ShixiangWang** [comment]
@brewert2 A minimal example dataset (along with code) can help develper check and debug this issue.
