### ISSUE TITLE
genes parameter in plotClusters can't accept list of genes

### ISSUE THREAD

**Issue by mike8115** [PoisonAlien/maftools#828]
If `genes` is a vector of gene names (ex. `c("TP53", "H3F3A")`), the following conditional statements will cause an error.
https://github.com/PoisonAlien/maftools/blob/7c0060b60de4f05a0256ad8a82355f044174f96c/R/plotClusters.R#L81
https://github.com/PoisonAlien/maftools/blob/7c0060b60de4f05a0256ad8a82355f044174f96c/R/plotClusters.R#L86

Error message:
`Error in if (genes == "CN_altered") { : the condition has length > 1`

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the late reply and thanks for reporting. I have pushed a patch (which may not be the best solution). Please install the package from GitHub and let me know if it helps.
