### ISSUE TITLE
how can I get sample list in cooncoplot data?

### ISSUE THREAD

**Issue by stellaoh** [PoisonAlien/maftools#83]
I run co-oncoplot by using maftools.
But I don't know how I can sample name. 

when I use oncoplot, I can get samples name by using writeMatrix=TRUE option. 

Help me, please :>

**Comment by PoisonAlien** [comment]
Hi,
You can run co-oncoplot with `showSampleNames = TRUE` and should label sample names. Is this what you wanted ?

**Comment by stellaoh** [comment]
Hi,
I know showSamplenames=TRUE option .
But I want to get sample list file.
(Ex. when I run oncoplot with writematrix=TRUE option, I can get "onco_matrix.txt file".)

And I want to plot annotation data.
But I don't know annotation method with cooncoplot.

 
Thanks.

**Comment by PoisonAlien** [comment]
For now there is no way to generate the matrix. However, there are other functions which I think will be useful for you. Try `genotypeMatrix` which should generate something similar to what you're asking.

Or `genesToBarcodes` function which will return sample list with the mentioned genes mutated.
