### ISSUE TITLE
mafSurvival function: Removed all samples with NA's

### ISSUE THREAD

**Issue by ZHOU-Zhengdong** [PoisonAlien/maftools#830]
Hello, PoisonAlien, thanks for this package, it's very useful, I  am new to this package and meet some problems, 
when I run mafSurvival, it seems all samples be remove, I don't understand how to solve it,

![18](https://user-images.githubusercontent.com/105055006/167447844-38fa4013-0fe1-4260-87da-61e331e899dc.png)

thank you very much and hope you could help.

**Comment by ShixiangWang** [comment]
@ZHOU-Zhengdong Please also report your clinical data with

```
maf@clinical.data
```

**Comment by ZHOU-Zhengdong** [comment]
@ShixiangWang 
thanks, the clinical data is downloaded from TCGA, please see the detail in the following screenshot.

![950e1ba638336a9757a49effe6b10d1](https://user-images.githubusercontent.com/105055006/167527208-bad5b8fd-053c-4068-b0c4-d5c519ff6b12.png)
![c4bd4e547a504e0451e1c37a4ce6b2e](https://user-images.githubusercontent.com/105055006/167527211-dd11cc3e-d846-4905-8281-5514188ff383.png)
![28ddf1c172e563ac0aa355bd2a0da38](https://user-images.githubusercontent.com/105055006/167527214-9a60191e-5c81-4682-a285-eb7c68bc871d.png)

**Comment by ShixiangWang** [comment]
You can see the valid data format from:

```
> laml.maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #MAF file
> laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') #clinical data
> laml = read.maf(maf = laml.maf, clinicalData = laml.clin)
> laml@clinical.data
     Tumor_Sample_Barcode FAB_classification days_to_last_followup Overall_Survival_Status
  1:         TCGA-AB-2802                 M4                   365                       1
  2:         TCGA-AB-2803                 M3                   792                       1
  3:         TCGA-AB-2804                 M3                  2557                       0
  4:         TCGA-AB-2805                 M0                   577                       1
  5:         TCGA-AB-2806                 M1                   945                       1
 ---                                                                                      
189:         TCGA-AB-3007                 M3                  1581                       0
190:         TCGA-AB-3008                 M1                   822                       1
191:         TCGA-AB-3009                 M4                   577                       1
192:         TCGA-AB-3011                 M1                  1885                       0
193:         TCGA-AB-3012                 M3                  1887                       0
```

The status should be changed to 0 or 1.

**Comment by ZHOU-Zhengdong** [comment]
thank you very much. I see, will have a try.

**Comment by ZHOU-Zhengdong** [comment]
I changed Dead status to 0, and Alive status to 1, It indeed works!!! thanks you!!!

**Comment by ZHOU-Zhengdong** [comment]
@ShixiangWang  I changed Dead status to 0, and Alive status to 1, It indeed works!!! thank you!!!
