### ISSUE TITLE
Structure for protein NRIP1 not found in Maftools

### ISSUE THREAD

**Issue by kix008** [PoisonAlien/maftools#832]
Good Day,

I am running the following command:

lollipopPlot(maf = TEC.maf, 
gene = 'NRIP1', 
AACol = 'HGVSp_Short',)

Error in lollipopPlot(maf = TEC.maf, gene = "NRIP1",  : 
  Structure for protein NRIP1 not found.

I have successfully generated numerous lollipop plots without error but gene NRIP1 returns an error. How can I correct this error? Thanks!

Here is a link to the protein:
https://www.uniprot.org/uniprot/P48552

**Comment by PoisonAlien** [comment]
Hello,

I have updated the database to include NRIP1. Please reinstall the package from GitHub for the patch.
