### ISSUE TITLE
trinucleotideMatrix function error

### ISSUE THREAD

**Issue by geejaytee** [PoisonAlien/maftools#833]
I have a MAF file generated using a version of the genome (GRCh38) which includes unplaced scaffolds. They are being ignored according to the trincleotideMatrix warning, but I'm still getting an error message when trying to find context for the signature analysis (I'm using hg38 for the context):
![Untitled](https://user-images.githubusercontent.com/27360278/169542975-3d94ac0c-6a43-4426-88ce-61475c2f2a7c.png)
The offending line is one from these unplaced scaffolds. Is there a way of filtering the MAF object directly prior to running this to remove the offending chromosomes, or would I need to filter the original text file that is imported?

**Comment by PoisonAlien** [comment]
Hi,

There is an argument `ignoreChr` to the function that you can use to filter the unwanted contigs. 
Hope this helps.
