### ISSUE TITLE
Using tcgaCompare() to plot mutation load between two cohorts

### ISSUE THREAD

**Issue by rajeha** [PoisonAlien/maftools#835]
Hi Anand,

Thank you for the tool! Would it be possible to generate a mutation load plot comparing two cohorts (rather than comparing one cohort to the 33 TCGA cohorts using tcgaCompare())?

**Comment by PoisonAlien** [comment]
Hi,

`tcgaCompare` can take multiple MAF objects and plot the TMB against all tcga cohorts. You can restrict the comparison against desired TCGA cohorts with the argument `tcga_cohorts`. However, you would need at least one tcga cohort to compare against :|
