### ISSUE TITLE
repel for plotOncodrive

### ISSUE THREAD

**Issue by AlexanderPic** [PoisonAlien/maftools#836]
Dear maftools-team,
would it be possible to implement a repel argument in the plotOncodrive function for an easier visualisation?

Thanks a lot for this package and your help!
Best,
Alexander

**Comment by PoisonAlien** [comment]
Hi,

Plots are generated with base graphics and it is not very flexible for labeling. However, you can take the results from `plotOncodrive` and plot it with `ggplot`.

Using example dataset:
```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
laml.sig <- oncodrive(maf = laml, AACol = 'Protein_Change', minMut = 5)

ggplot(data = laml.sig, aes(x = muts_in_clusters, y = -log10(fdr), label = Hugo_Symbol))+geom_point()+ggrepel::geom_text_repel()

```
