### ISSUE TITLE
why some lines in gistic peak are not straight?

### ISSUE THREAD

**Issue by hfl112** [PoisonAlien/maftools#837]
Hi developers,
I noticed some lines in this gistic2 are not straight, how can I change it?
![image](https://user-images.githubusercontent.com/33510929/171491276-beceff30-342c-48ed-89b1-5a5db1a8d7d6.png)

**Comment by daonslog** [comment]
Hi, I'd like to bump this question. I wonder the same thing. It is also shown on the docs (link below). Why is this the case?
Link: https://rdrr.io/bioc/maftools/man/gisticChromPlot.html

**Comment by daonslog** [comment]
Can this be reopened? An answer still hasn't been provided.
