### ISSUE TITLE
Fatal Bug about plotmafSummary plot

### ISSUE THREAD

**Issue by biosunsci** [PoisonAlien/maftools#840]
**Describe the issue**

As you can see here, the fig is captured from the official vignettes of maftools, section 7.1 Plotting MAF summary.
https://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html

The last fig of plotmafSummary displayed a wrong picture.
For the percentage is not accord to the bar width, and the gene symbol is wrong compare to the oncoplot result.

I think these may be caused by a misorder of the labels when plotting the figure.

![image](https://user-images.githubusercontent.com/15091103/174024796-82317660-8571-4a99-848b-e01a8fb021e2.png)

**Comment by PoisonAlien** [comment]
Hi,

It is not a bug. See #400 and #620 for details.

**Comment by biosunsci** [comment]
Thank you very much for the reply. 
I'll close the issue.
The current representation may be a little counterintuitive.
