### ISSUE TITLE
Protein Structure not found

### ISSUE THREAD

**Issue by vincentye2** [PoisonAlien/maftools#843]
Hi there,

I'm working on a project where we've generated tumours in mice and have sequenced it using WES. I'm attempting to visualize protein structure and mutations using lollipop plots. For example, one of the mutated genes I'm interested in is _Braf_.

When I use plotProtein for _Braf_ there is no structure, but it does exist for _BRAF_. However, because my MAF file has mutations in _Braf_ when I use lollipop plot for BRAF there are no mutations found. Is there any way to fix this?

**Comment by PoisonAlien** [comment]
Hi,
Maftools do not support the mouse genome, hence the error.
