### ISSUE TITLE
PlotmafSummary warning message

### ISSUE THREAD

**Issue by sinumol** [PoisonAlien/maftools#846]
Hi,
I got the following warning message while plotting plotmafSummary. And I am only getting the SNP variant plot in the graph. Please help me with this issue.

plotmafSummary(maf=oc, rmOutlier = TRUE, addStat= 'median', dashboard = TRUE, titvRaw= FALSE)
Warning message:
In titv(maf = maf, useSyn = TRUE, plot = FALSE) :
  Non standard Ti/Tv class: 1TRUE

![indel-snp-genomic-general-9](https://user-images.githubusercontent.com/80383206/177752259-286e9f28-8b69-4b2b-b6ea-64c25de7c59f.png)

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. I think your maf contains only SNVs and no indels.
