### ISSUE TITLE
Reading Clinical data with maftool

### ISSUE THREAD

**Issue by shhabnsbwjd** [PoisonAlien/maftools#847]
Hello,

I want to read my clinical data using maf tools. The data is in tsv format and I am reading it using the code;
read.maf(maf = "var.annovar.maf", clinicalData = "clinical_data.tsv", verbose = FALSE))

But i am getting this error
Error in is.data.frame(x = maf) : 
  argument "maf" is missing, with no default

What should I do?

**Comment by ShixiangWang** [comment]
Could you try running with `read.maf("var.annovar.maf", "clinical_data.tsv")` and also posting your session information? @shhabnsbwjd

**Comment by PoisonAlien** [comment]
Hi,
Whats is `var.annovar.maf`? Is it a file or a data.frame?

**Comment by shhabnsbwjd** [comment]
> Could you try running with `read.maf("var.annovar.maf", "clinical_data.tsv")` and also posting your session information? @shhabnsbwjd

Yes sure, let me try

**Comment by shhabnsbwjd** [comment]
![Screenshot (2236)](https://user-images.githubusercontent.com/108682608/178728719-7a981ac2-619e-4a23-a021-a957c1072f82.png)
not working

**Comment by PoisonAlien** [comment]
Hi,
It says the file does not exist. Please make sure you are providing the correct and full path to the file.

**Comment by ShixiangWang** [comment]
@shhabnsbwjd Try `dir()`, you may find the file does not exist as @PoisonAlien pointed out. You need to locate your file and set the full path to it, or you need to set working directory to the directory path where your data located with `setwd()`.
