### ISSUE TITLE
Subset genes in the initial steps

### ISSUE THREAD

**Issue by camcecc** [PoisonAlien/maftools#848]
Is there a way to subset genes and remove some of them (namely) from the maf file? 
Or, the opposite, only keep the ones we want to investigate more and would like to see more deeply (i.e. in the oncoprint)?
Thanks

**Comment by PoisonAlien** [comment]
Hi,

This is a very specific case. But if you know what genes, samples, or genomic regions, you are particularly interested in, you could use `subsetMaf`.

**Comment by PoisonAlien** [comment]
Unfortunately it is not possible :|
