### ISSUE TITLE
annovarToMaf

### ISSUE THREAD

**Issue by xiw588** [PoisonAlien/maftools#849]
**Describe the issue**
Hi I am trying to read in a dataset annotated by ANNOVAR, and the total number or rows should be 14841, however, it turned out to be only 13485 after reading in by annovarToMaf. I want to include all of the rows into the analysis, is there any way that I can do this? 

**Command**
var.annovar.maf = annovarToMaf(annovar = "Genomic_analysis/SNV_wANNOVAR.txt", 
                               Center = 'NA', 
                               refBuild = 'hg19', 
                               tsbCol = 'Tumor_Sample_Barcode', MAFobj = FALSE,
                               table = 'refGene',
                               sep = "\t")

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
Would it be possible to provide a reproducible example dataset? You can remove any sensitive information from the data if would like.

**Comment by PoisonAlien** [comment]
Hi,
It is difficult for me to guess what is happening without the data. You could run the below and check the output 

```r
maftools::genesToBarcodes(maf = maf, genes = "KRAS")
```
