### ISSUE TITLE
Label trinucleotide context in plotSignatures graphic

### ISSUE THREAD

**Issue by Adamtaranto** [PoisonAlien/maftools#85]
Does the poltSignatures function have a built in method for labelling individual bars in the resulting barplot with the corresponding trinucleotide context? As in Fig 5a from the Campbell _et al._ _Cell_ paper [Comprehensive Analysis of Hypermutation in Human Cancer](http://dx.doi.org/10.1016/j.cell.2017.09.048). 

If not, is it possible to get the trinucleotide labels + values from the extractSignatures object?

**Comment by PoisonAlien** [comment]
Hi,
Unfortunately for now there is no option. But they are in the order similar to the one used by Sanger framework, [like this](http://cancer.sanger.ac.uk/signatures/Signature-1.png).  
You can also check this with results. 
`rownames(sig$signatures)`

**Comment by aditibagchi** [comment]
Hi , 
I am new to using maftools but eager to learn. using trinucleotideMatrix()  is yielding the following error. 
 trinucleotideMatrix(TRial_1, ref_genome = '~/desktop/hg38.fa')
reading ~/desktop/hg38.fa (this might take few minutes)..
Extracting 5' and 3' adjacent bases..
Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 85: 'allow.nonnarrowing' is FALSE and the supplied start (145617289) is > refwidth + 1
> 

Can you please please help me with this.
Thank you 
Aditi

**Comment by PoisonAlien** [comment]
Hello,

Is your MAF file is generated with hg38 reference genome ? From error it appears that the chromosome length is smaller than the mutated base position. Make sure you are using the same reference build.

**Comment by aditibagchi** [comment]
Thank you so so  much fro the reply. Yes it is hg38 built ; I tried using that first got a similar error 

_trinucleotideMatrix(TRial_1, ref_genome = '~/desktop/hg38.fa')
reading ~/desktop/hg38.fa (this might take few minutes)..
Extracting 5' and 3' adjacent bases..
Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 85: 'allow.nonnarrowing' is FALSE and the supplied start (145617289) is > refwidth + 1_

here is the top part of my maf file, my colleague generated it .
       
  ID summary    Mean Median
 1:             NCBI_Build      NA      NA     NA
 2:                 Center      NA      NA     NA
 3:                Samples      34      NA     NA
 4:                 nGenes    3242      NA     NA
 5:        Frame_Shift_Del     123   3.618    3.0
 6:        Frame_Shift_Ins      56   1.647    1.0
 7:           In_Frame_Del      18   0.529    0.0
 8:           In_Frame_Ins      20   0.588    0.0
 9:      Missense_Mutation    3333  98.029   32.0
10:      Nonsense_Mutation     306   9.000    2.0
11:       Nonstop_Mutation       5   0.147    0.0
12:            Splice_Site     110   3.235    2.0
13: Translation_Start_Site       2   0.059    0.0
14:                  total    3973 116.853   42.5

I see that she did insert the NCBI build in the file, do you think inserting that will solve the problem.

Thanks again, :)
aditi

**Comment by PoisonAlien** [comment]
I dont think thats the issue. There seem to be some issue with the locus 145617289 which appears to be larger than the chromosome length itself. Can you check which chromosome this position belongs to ? You can grep it from terminal or you can run this below command in R.

```r
maftools::subsetMaf(maf = TRial_1, query = "Start_Position == 145617289", fields = "Chromosome")
```

**Comment by PoisonAlien** [comment]
Okay, thats weird. Its hard for me to guess whats wrong with it. Is it possible to share your MAF file ? You can attach it here or mail me at anandmt3@gmail.com , you can remove any sensitive information if thats the concern.

**Comment by aditibagchi** [comment]
Yup I think I can do that, let me see. Thanks again. It is weird I know I have tried.

**Comment by jrcodina96** [comment]
What happened in the end? I am having a similar error. I also can't find the locus that is giving error in my file.
