### ISSUE TITLE
"Multi-hit" in Oncoplot legend by default

### ISSUE THREAD

**Issue by espelpz** [PoisonAlien/maftools#850]
**Describe the issue**
Hi, 
"Multi-hit" label is included in Oncoplot legend by default even though my data do not include samples with more than one variant and thus the representation does not show any Multi-hit case, however it appears in the legend. 
How could I get rid of "Multi-hit" in legend?

**Command**
Here is the command I am running:
oncoplot(maf = maf.controles, top = 80, removeNonMutated = FALSE, showTumorSampleBarcodes = TRUE, drawColBar = FALSE, sampleOrder = unique(sort(controles.list$Sample)),  SampleNamefontSize = 0.8,  legend_height = 7)

Thank you!

**Comment by kunstner** [comment]
You can define your own color profile and omit Multi-hit in the profile. The label should disappear afterwards.
