### ISSUE TITLE
maftool package: No non-synonymous mutations found Check `vc_nonSyn`` argumet in `read.maf` for details

### ISSUE THREAD

**Issue by celluq** [PoisonAlien/maftools#851]
I have download the SNV data from TCGA database.
But this error was reported when a maf file was read by read.maf command. 
So what's the meaning of that? How to fix it?
Thank you so much for your help.

![捕获](https://user-images.githubusercontent.com/81560277/182057576-d5656221-b130-416b-bb71-ec20d890208d.JPG)

**Comment by ShixiangWang** [comment]
This typically means the input MAF data does not contain mutations that may have effects (on gene function). If you want to include all mutations, you should reset the `vc_nonSyn` option.

**Comment by celluq** [comment]
> 

Thank you so much for your help!

**Comment by zyffzi** [comment]
Could I know how to reset the vc_nonSyn option? Thanks a lot.

**Comment by ShixiangWang** [comment]
@zyffzi Run `?read.maf` in R console. Change the option to what you want to analyze.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/25057508/182085359-4ff45a8e-0261-482f-aac8-0ed1b899517f.png">

**Comment by zyffzi** [comment]
Thank you very much! I find that I can often successfully read individual MAT files.
<img width="530" alt="1" src="https://user-images.githubusercontent.com/110374882/182094902-dd85b329-64da-4515-8b88-74225affefc1.png">
<img width="345" alt="2" src="https://user-images.githubusercontent.com/110374882/182094979-aba1010d-d3e9-4145-a8ae-4b98ba4353cd.png">

However, when I use the Apply function to read all the MAT files in the folder:
<img width="747" alt="3" src="https://user-images.githubusercontent.com/110374882/182095216-7afe39db-6cbb-4c4c-b338-2b4de276448f.png">
**It displayed the same warning in the end:**

<img width="373" alt="4" src="https://user-images.githubusercontent.com/110374882/182095256-8e021567-54ae-41bf-b18a-eca1ad2d4ef7.png">
Have you ever encountered such a situation before? How can I solve it？
Thank you so much for your help.

**Comment by ShixiangWang** [comment]
For tcga data, you can use TCGAbiolinks. A solution for your error is manually set the `vc_nonSyn` to all mutation types in the `read.maf`.

**Comment by Yizhou-Y** [comment]
> 
Could you tell me how to set the vc_nonSyn to all mutation types？By vc_nonSyn = all/ture？

**Comment by ShixiangWang** [comment]
```r
library(maftools)

laml.maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #MAF file
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') #clinical data
laml = read.maf(maf = laml.maf, clinicalData = laml.clin, vc_nonSyn = c("Frame_Shift_Del", "Frame_Shift_Ins" ))
```

**Comment by matteocostacurta** [comment]
Hi, I am encountering exactly the same problem (described at the top).

I am testing maftools for use with 1000+ samples downloaded from TCGA. I am importing them manually and treating them as they were non-TCGA files as I will be obtaining mafs from whole exome sequencing of a bunch of clinical samples.

This is my code:

```
library(maftools)

setwd("/my/directory/path/with/maf/files")

file_list <- as.list(list.files(pattern="*.maf"))
maf_list <- list()

for (i in file_list) {
  print(i)
  maf_list[[i]] <- read.maf(maf=`i`, vc_nonSyn = NULL)
}

```
The for loop for read.maf stops at sample number 114 of 1091 with the aforementioned error.

I have tried to replace vs_nonSyn = NULL with any and all of the options in the description of the parameter vs_nonSyn in ?read.maf. When I do that, it stops at either sample number 1, or at sample 114 again.

Could you please advice how to solve the issue? 

Thank you so much!

**Comment by ShixiangWang** [comment]
Why not bind all maf files first and then import it with maftools?

```
library(data.table)
library(maftools)

file_list <- list.files(pattern="*.maf")
maf_list = lapply(file_list, function(x) data.table::fread(x)}
maf = rbindlist(maf_list)
mafObj = read.maf(maf)
```

**Comment by matteocostacurta** [comment]
It works a treat, thank you!

> Why not bind all maf files first and then import it with maftools?
> 
> ```
> library(data.table)
> library(maftools)
> 
> file_list <- list.files(pattern="*.maf")
> maf_list = lapply(file_list, function(x) data.table::fread(x))
> maf = rbindlist(maf_list)
> mafObj = read.maf(maf)
> ```

**Comment by sx998508** [comment]
hi Mr.Wang. Sorry to bother you in ur free time. i encountered the same question after i analyzed the raw-rna seq data using gatk call snp and indel. I used the annnovar to annotate my SNP, then i used the script like below
`for i in *.gene.anno.variant_function
  do
      sample=`echo $i| awk -F '.' '{print $1}'`
      cut -f '1-10' $i|sed '1d'|sed "s/$/\t${sample}/">>all_sample.txt
  done
  sed -i '1s/^/Chr\tStart\tEnd\tRef\tAlt\tFunc.refGene\tGene.refGene\tGeneDetail.refGene\tExonicFunc.refGene\tAAChange.refGene\tTumor_Sample_Barcode\n/' all_sample.txt`
 then i  successfully got the format for converting to MAF file and annovarToMaf function worked smoothly. but when i used read.maf and it kept warning me that 

> Error in read.maf(maf = "var_annovar.maf") : 
  No non-synonymous mutations found
Check `vc_nonSyn`` argumet in `read.maf` for details

then i followed ur advice to change my configuration from "Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site", "Translation_Start_Site","Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del","In_Frame_Ins", "Missense_Mutation". but none of them really worked. Maybe i can get some useful idea from you, really looking forward to ur reply.

here is my maf file made by annovarToMaf

_

ncRNA_splicing | WASH7P(NR_024540:exon10:c.1233-2->TGGGGGCATCGGCAAGGCCAAGCTGCGCAGCATGAAGGAGCGAAAGCTGGAGAAGAAGAAGCAGAAGGAGCAGGAGCA) | chr1 | 15040 | 15040 | indel | TGCTCCTGCTCCTTCTGCTTCTTCTTCTCCAGCTTTCGCTCCTTCATGCTGCGCAGCTTGGCCTTGCCGATGCCCCCA | Unknown | MNP | all_sample | - | TGCTCCTGCTCCTTCTGCTTCTTCTTCTCCAGCTTTCGCTCCTTCATGCTGCGCAGCTTGGCCTTGCCGATGCCCCCA | unknown | 410.27 | 14
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | ncRNA_intronic | WASH7P | chr1 | 15250 | 15250 | indel | CAGGGT | Unknown | MNP | all_sample | - | CAGGGT | unknown | 80.18 | 3
3 | ncRNA_exonic | WASH7P | chr1 | 15903 | 15903 | indel | C | Unknown | MNP | all_sample | - | C | unknown | 80.18 | 2
4 | ncRNA_intronic | WASH7P | chr1 | 16102 | 16104 | indel | - | Unknown | MNP | all_sample | GTG | - | het | 189.78 | 17

_
