### ISSUE TITLE
what "RNA" in Variant_Classification field mean in maf file 

### ISSUE THREAD

**Issue by jadonWong** [PoisonAlien/maftools#853]
**Describe the issue**
Hi, i am confused about the "RNA" in Variant_Classification field, can you please tell me what does it mean and how it be generated?

**Comment by PoisonAlien** [comment]
Hello Jadon,
Sorry for the late reply. In case if you're still wondering, RNA in Variant_Classification is the resulting consequence from the variant. See VEP for all the available [variant consequences](https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html). In MAF `RNA` would be one of the following VEP entires:
```
"mature_miRNA_variant", "exon_variant", "non_coding_exon_variant", 
"non_coding_transcript_exon_variant", "non_coding_transcript_variant", 
"nc_transcript_variant"
```

These values are generated by a variant annotation program such as VEP or annovar.  I hope this helps.
