### ISSUE TITLE
vafCompare issue

### ISSUE THREAD

**Issue by NewBee100** [PoisonAlien/maftools#854]
Hi PoissonAlien,
I constantly get an error message when using vafCompare on my own set of mutational samples.  
I've tried it on the TCGA studies as below, get the same error. 

**Command**

```r

> TCGAmutations::tcga_load(study = "LUAD") -> LUAD
 > TCGAmutations::tcga_load(study = "LUSC") -> LUSC
 > vafCompare(m1 = LUAD, m2 = LUSC)

t_vaf field is missing, but found t_ref_count & t_alt_count columns. Estimating vaf..
t_vaf field is missing, but found t_ref_count & t_alt_count columns. Estimating vaf..
Error in if (!is.na(sig)) { : the condition has length > 1
```

Is there a way to fix this? 

Many thanks!

**Comment by NewBee100** [comment]
Hi,

Any chance of an answer? It is a great package, it's a shame that some great features like vafcompare do not work, at least in my case.

**Comment by PoisonAlien** [comment]
Hello!
Sorry for my tardy response. Things have gotten really busy recently - I have not been able to answer any of the issues. It will be back to normal soon from next week.

**Comment by FriederikeHanssen** [comment]
HI! I am running into the same thing. Anyone figured out what the cause could be? :)

**Comment by ShixiangWang** [comment]
> HI! I am running into the same thing. Anyone figured out what the cause could be? :)

This is typically caused by the R4.2 version, as it would no longer support a vector as input of if expression.

**Comment by ShixiangWang** [comment]
> Thank you :) I will try to downgrade the R version

I will put a quick PR on this, please wait.

**Comment by ShixiangWang** [comment]
@NewBee100 @FriederikeHanssen Please try installing the PR and restart R to check if it works.

```
remotes::install_github("PoisonAlien/maftools#880")
```

**Comment by FriederikeHanssen** [comment]
works 🚀 thanks a lot :)

**Comment by ShixiangWang** [comment]
@FriederikeHanssen Thanks for pointing this out. I created a PR on wrong branch, I will update and let you known.

**Comment by ShixiangWang** [comment]
Please use the new PR, sorry for that.

```r
remotes::install_github("PoisonAlien/maftools#881")
```

**Comment by NewBee100** [comment]
Hi, It does not work for me, now the error message is 
``Error in graphics::layout(p, ...) : 
  argument "p" is missing, with no default `

I don't know what this means or how to solve this..

**Comment by ShixiangWang** [comment]
@NewBee100 Could you put all your commands and output for reproducing the error?

**Comment by NewBee100** [comment]
Good evening , I've tried again, now it worked 🤔
I had, possibly, too many other packages loaded, a conflict issue? ? Anyway, it's good now. Thank you!!!
