### ISSUE TITLE
Feature suggestion: Add sample names to TMB plot

### ISSUE THREAD

**Issue by FriederikeHanssen** [PoisonAlien/maftools#857]
Hi!

Thank you for providing this fantastic package  🤩 

I am currently using maftools 2.10.0. I have been using the `tmb()` plot. From reading through the manual it doesn't seem yet to be possible to label the resulting data points with the tumor sample barcode. It would be quite useful to us to have when later evaluating results of individual samples and cross checking how they relate to the TMB directly.

**Comment by MjelleLab** [comment]
You can just use the data frame produced and plot it using ggplot2.
