### ISSUE TITLE
oncplot(, top) limits samples, not genes

### ISSUE THREAD

**Issue by tiroshamit** [PoisonAlien/maftools#86]
Hi @PoisonAlien 
Thank you very much for this amazing tool and great support. I am really enjoying following you.

I have structured a maf file using this line:
maf_final = read.maf(maf = maf_obj, clinicalData = "C:/xxx/xxx.txt", useAll = TRUE)

and then wanted to make an oncoplot using this command:
oncoplot(maf_final, top = 10, fontSize = 10, removeNonMutated = TRUE)

I am editing my question:
In the oncoplot, indeed only the top 10 mutated genes are presented, but all the others are presented as well, but as a non-mutated genes. So I cannot decrease the number of rows in the plot.

Many thanks
Amit

**Comment by PoisonAlien** [comment]
Hi Amit,

I am glad that you found the tool useful and please accept my apologies for late reply. 
Do you still have the issue ? Can you post your command ?

**Comment by tiroshamit** [comment]
Hi PoisonAlien,
I think I figured this out in the meanwhile.
Great package, and great support! Thanks for both!

**Comment by PoisonAlien** [comment]
No problem. Glad to be of help.
