### ISSUE TITLE
Is there any possibility to add ClinicalData to merged maf files? 

### ISSUE THREAD

**Issue by eibol1** [PoisonAlien/maftools#864]
Hi, 

I have successfully merged my MAF files with `merge_mafs()` function. I created the MAF object and everything is good, I can plot the summaries and oncoplots. 

But I want to add ClinicalData when creating the MAF object like this: `maf_files <- merge_mafs(maf_list, ClinicalData = laml.clin)`, where:

`maf_list` is a list of maf files. 

`laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools')`

I got this error: 

```
> maf_files <- merge_mafs(maf = maf_list, ClinicalData = laml.clin)  
Merging 23 MAF files
Error in read.maf(maf = maf, verbose = verbose, ...) : 
  unused argument (ClinicalData = "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/maftools/extdata/tcga_laml_annot.tsv")

```

Does anyone know how to add clinical data to a maf list?

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. You have a typo - it should be `clinicalData` and not `ClinicalData `
