### ISSUE TITLE
How to convert RDS file to MAF to use it in maftools??

### ISSUE THREAD

**Issue by esraajamal** [PoisonAlien/maftools#869]
Thank you for this package ... I am just wondering how to convert a big RDS file to MAF file to be able to use it in maftools ??

Thanks in advance,

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. I do not know what are the contents of the RDs file. You could the object into R with `readRDS()` and if it is a data frame of MAF file, you could then pass the read object into `maftools::read.maf` .
