### ISSUE TITLE
Mutation burden 

### ISSUE THREAD

**Issue by patidarr** [PoisonAlien/maftools#87]
Hi,

Would it be possible to have the tcgaCompare to make a plot like https://www.nature.com/articles/nature12477/figures/1

Thanks,
Rajesh

**Comment by PoisonAlien** [comment]
Hi,
Plot generated by `tcgaCompare` is essentially the same plot with same interpretation. Unfortunately for now tool won't create the exact kind of plot.

**Comment by lxilxi** [comment]
@PoisonAlien, For tcgaCompare, Is it possible to change y-axis to "number of mutations per MB", which would be more helpful when compare studies with different capture size?  Thanks!

**Comment by PoisonAlien** [comment]
Hmm, I think its doable. What is your capture size ? I guess TCGA uses 55mb agilent kit, will check.

**Comment by lxilxi** [comment]
My capture is for targeted regions, so the size is very small.  It would be great if there could be a option to specify target size.

**Comment by patidarr** [comment]
@PoisonAlien, Any update on this, could use it today for a presentation...

**Comment by PoisonAlien** [comment]
Hi, Sorry :| 
Have been bit busy and this would require bit of coding without breaking existing code, it will take some time.

**Comment by jharenza** [comment]
Definitely would also love this enhancement with user specification of capture size!
