### ISSUE TITLE
Customozing Oncoplots Maf file : adding CN.Table from data.frame with error message "Error in file.info(file) : argument 'filename' incorrect"

### ISSUE THREAD

**Issue by capio78396** [PoisonAlien/maftools#871]
Hi, 

I have a problem dealing with the custom functions with a Maf file. 
I saw in the Customizing oncoplots R Markdown from 2022-04-26 (https://www.bioconductor.org/packages/devel/bioc/vignettes/maftools/inst/doc/oncoplots.html) that we could add copy number variations from a non-gistic file by using this function : 

laml.plus.cn = read.maf(maf = laml.maf,
                        cnTable = custom.cn.data,
                        verbose = FALSE)

I have tested it on my script using the laml file from TCGA and the "dummy CN file" and this is working. Now, when testing with my own files (Maf file and customed test CN table):

#test adding CN file to Maf File

> head(CN.Table)
  Hugo_Symbol Tumor_Sample_Barcode Variant_Classification
1        TP53             17R02878                    Del
2      DNMT3A              6538282                    Del
3      DNMT3A              8783792             ShallowAmp
4        BAP1              8739836                   Loss
5      ARID1A                72987                    Dup

> MafLIQUID.plus.CN = read.maf(MafLIQUID, cnTable = CN.Table)
-Reading
Error in file.info(file) : argument 'filename' incorrect

I have tested to merge my own CN.Table with the laml file from TCGA and this is working, meaning the issue does not come from my file format. 

I am quite a rookie on R but I could not find many information on these customizing functions for Maf File : any advice on this would be very much appreciated. 
Thanks so much.

**Comment by PoisonAlien** [comment]
Hi,

Is ` custom.cn.data` a data.frame or a path to the file?

**Comment by zetamui** [comment]
The cnTable is a txt file input, so cnTable='your_cntable.txt' a path pointing to your cntable file would work. I also find not much information around and hard to find your way around. Good luck!
