### ISSUE TITLE
Add non coding mutations in oncoplot

### ISSUE THREAD

**Issue by msubirana** [PoisonAlien/maftools#872]
Hi,

I want to add non coding mutations detected in a H3K27ac dataset in the oncoplot figure. I have a granges with affected h327ac regions per sample. Is it possible to integrate it to the maf object and plot them inside the oncoplot?

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. If you can represent your data in MAF format, you can do it, however, you would like it to be. 
Please share a sample format so that I can suggest you.

**Comment by xieduo7** [comment]
Hi @PoisonAlien , I share the same question with @msubirana.

I am plotting using WGS data. But the summary plot and the oncoplot only show several coding mutations: Missense_Mutation, Nonsense_Mutation, Frame_Shift_Del, In_Frame_Del, Frame_Shift_Ins, Splice_Site, and Multi_Hit. How can I display non-coding mutations such as 'Intron' muataion (the maf file contains these non-coding mutations but these plots don't show these)?

Best, 
Duo

**Comment by PoisonAlien** [comment]
Hi,

You can define your own set of `Variant_Classifications` to be considered as non-synonymous. Please check `vc_nonSyn` argument in `read.maf` function.
