### ISSUE TITLE
somaticInteractions error

### ISSUE THREAD

**Issue by jlac** [PoisonAlien/maftools#88]
When attempting to run the somaticInteractions analysis, I get the following error:

Error in hclust(dist(r)) : NA/NaN/Inf in foreign function call (arg 11)

Any idea what might be going wrong? The same man file and clinical data analyzes fine in other maftools modules, but fails for this one. Thanks!

Justin

**Comment by PoisonAlien** [comment]
Hi,

Please accept my apologies for late reply. 
Do you still have this issue ? Can you try increasing the top argument and see if it works (default is 25)

**Comment by mario2437** [comment]
I actually have the same problem.
I tried to increase the top argument but I still got the same error...
Thanks!

**Comment by PoisonAlien** [comment]
Hi,
Do you think you can share your maf file ? I know where the issue is coming from, but I want to make sure.

**Comment by sosug32** [comment]
I am also getting same error now and any suggestions to fix this problem?
