### ISSUE TITLE
OncoPlot number of samples discrepancy 

### ISSUE THREAD

**Issue by mdm68** [PoisonAlien/maftools#883]
Hi All! 

Hopefully a small question! 

The sample count shown on top of the oncoplot and the right bar ( No of samples) isn't right for me. Could you tell me how to display the correct number ( which is the total unique values found in "Tumor_Sample_Barcode" ? )

I get " Altered in 37 (168.18%) of 22 samples.  ( The TOTAL should've been 53 samples ) 

The only thing I noticed is, the 22 samples are only the count of samples that have a TP53 alteration. Im not sure where the 37 is coming from. ( Is it adding just the genes of AR & the TP53 ?) 

Hugo_Symbol |   | Frame_Shift_Del | Frame_Shift_Ins | In_Frame_Del | In_Frame_Ins | Missense_Mutation | Nonsense_Mutation | Splice_Site | total | MutatedSamples | AlteredSamples
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
TP53 |   | 3 | 2 | 1 | 0 | 13 | 0 | 3 | 22 | 19 | 19
AR |   | 0 | 0 | 1 | 0 | 14 | 0 | 0 | 15 | 11 | 11
BRCA2 |   | 3 | 0 | 0 | 0 | 3 | 1 | 0 | 7 | 7 | 7

**Comment by ShixiangWang** [comment]
Could you show your R commands for this? Particularly, it would be great if you could reproduce this with the example MAF builtin maftools.

**Comment by mdm68** [comment]
`library(maftools)
test_maf = read.maf('test.maf', isTCGA = FALSE)
oncoplot(test_maf, top = 5, altered = FALSE)`

**Comment by ShixiangWang** [comment]
@mdm68 I cannot reproduce this, could you provide your data? If your data is private, you can send me via `wang.shixiang@icloud.com`. I will destroy it after exploring this issue.

```
library(maftools)

laml.maf = system.file("extdata", "tcga_laml.maf.gz", package = "maftools") #MAF file
laml.clin = system.file('extdata', 'tcga_laml_annot.tsv', package = 'maftools') #clinical data
laml = read.maf(maf = laml.maf, clinicalData = laml.clin, isTCGA = FALSE)

oncoplot(laml, top = 5, altered = FALSE)

```

**Comment by mdm68** [comment]
Just sent! Thank you

**Comment by ShixiangWang** [comment]
@mdm68  I found this is because all your NCBI_Build coloumn is `NA`, this made a failed summary in MAF object.

```
                   ID summary
 1:        NCBI_Build  ABC_CR
 2:            Center      52
 3:           Samples      22
 4:            nGenes      18
 5:   Frame_Shift_Del       4
 6:   Frame_Shift_Ins       3
 7:      In_Frame_Del       1
 8:      In_Frame_Ins      68
 9: Missense_Mutation       3
10: Nonsense_Mutation       8
11:       Splice_Site     105
12:             total  ABC_CR
```

A PR https://github.com/PoisonAlien/maftools/pull/875 is fixing this. Considering it is not be merged yet, you can use the following workaround.

```
library(maftools)

maf = data.table::fread('~/../Downloads/ABC.maf')
maf$NCBI_Build = as.character(maf$NCBI_Build)
maf$NCBI_Build = "GRCh38" # Or 37 maybe
test_maf = read.maf(maf, isTCGA = FALSE)

oncoplot(test_maf, top = 5, altered = FALSE)
```

**Comment by mdm68** [comment]
That worked !! I wish I knew missing NCBI_build would cause the percentages to skew up. Thanks !!
