### ISSUE TITLE
coOncoplot Unable to Sort Genes By m1 or m2 Only

### ISSUE THREAD

**Issue by DarioS** [PoisonAlien/maftools#888]
It would be nice to be able to set a parameter that would allow sorting by m1 frequency or m2 frequency, rather than averaged. I want to show that the genes most frequently affected in one subtype are least affected in another subtype, so not the most averaged ones. Currently, it is clunky. I need to do `oncoplot`, write down the genes and then specify them like `genes = genesTSG` to `coOncoplot`.

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. I have added the argument `sortByM1` and `sortByM2` to `coOncoplot`.  Hope this helps.
