### ISSUE TITLE
Detecting caner driver genes

### ISSUE THREAD

**Issue by Jwang412** [PoisonAlien/maftools#89]
Hi,
I am new to analyze somatic mutation variants. So I followed the process in maftools manual. 
My data is breast cancer samples, and the clinical data contains three phenotypes ER, PR and HER-2.  
I want to detect the cancer driver genes. I followed the manual. The code was showed below:
##Detecting cancer driver genes based on positional clustering
`mf.sig = oncodrive(maf=mf, AACol="Proein_Change", minMut =5, pvalMethod='zscore')`

I got the error:
Estimating background scores from synonymous variants..
Error in eval(jsub, SDenv, parent.frame()) : object 'AAChange' not found

Could you tell me how to detect cancer driver genes?

Many thanks.

**Comment by PoisonAlien** [comment]
Hi,
Please accept my apologies for late reply. 
Did you figure out the issue ? Argument `AACol` takes the column name under which protein change information is stored. Use function `getFields()` to see available columns in the maf.

**Comment by pwwang** [comment]
@Jwang412 See if this helps: https://github.com/PoisonAlien/maftools/issues/16#issuecomment-401152757
