### ISSUE TITLE
Lolipop plot with custom data instead of count

### ISSUE THREAD

**Issue by haochenz96** [PoisonAlien/maftools#894]
**Describe the issue**
Currently the lolipop plot's y-axis can only plot the count of the number of times a certain mutation occurs in the data. Is it possible to make this y-axis value customizable (e.g. variant allele frequency)?

This is a follow-up on a previous issue: #746

Also including an example I found from another package:

<img width="768" alt="Screen Shot 2022-12-04 at 7 03 19 PM" src="https://user-images.githubusercontent.com/54121237/205540415-0e988d2a-d30a-470f-8115-865f4aea819a.png">
which was taken from this package (https://bioconductor.org/packages/release/bioc/vignettes/trackViewer/inst/doc/lollipopPlot.html#Change_the_height_of_a_lollipop_plot)

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. I have added an argument `data` to `lollipopPlot` which should do the job.
Input data should be a two-column data frame with position and the corresponding counts. Optionally you can add a thrid column `Variant_Classification` which will be used for color coding the dots.

Minimal example:

```r
my_data = data.frame(pos = sample.int(912, 15, replace = TRUE), count = sample.int(30, 15, replace = TRUE))
head(my_data)
  pos count
1 710    29
2 816    11
3 763    28
4 354    28
5 607    26
6 137    11
lollipopPlot(data = my_data, gene = "DNMT3A")
```

Hope this helps.
