### ISSUE TITLE
readGistic fails for Firebrowse GISTIC2 'MESO' cohort

### ISSUE THREAD

**Issue by selkamand** [PoisonAlien/maftools#899]
Thanks for an amazing package!

Just reporting that I've found a TCGA Gistic Dataset that causes maftools::readGistic to throw an error.

**The error**
```
Error in dcast.data.table(data = vc, formula = Tumor_Sample_Barcode ~  : 
  Can not cast an empty data.table
```

The source of the gistic files:

Firebrowse TCGA MESO gistic files

[gdac.broadinstitute.org_MESO-TP.CopyNumber_Gistic2.Level_4.2016012800.0.0.tar.gz](https://github.com/PoisonAlien/maftools/files/10478617/gdac.broadinstitute.org_MESO-TP.CopyNumber_Gistic2.Level_4.2016012800.0.0.tar.gz)

** The Code ** 

```r
library(maftools)

readGistic(
  gisticAllLesionsFile = "all_lesions.conf_99.txt",
  gisticAmpGenesFile = "amp_genes.conf_99.txt",
  gisticDelGenesFile = "del_genes.conf_99.txt",
  gisticScoresFile = "scores.gistic",
  cnLevel = "deep",
  isTCGA = TRUE
)
```

Reading works fine if cnLevel is `shallow` or `all`

I've attached an R project zipped up with the script, files and Rproj to aid reproducibility
[test_read_gistic.tar.gz](https://github.com/PoisonAlien/maftools/files/10478664/test_read_gistic.tar.gz)

**Session info**

``` r
sessionInfo()
#> R version 4.2.0 (2022-04-22)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur/Monterey 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.13   knitr_1.39        magrittr_2.0.3    R.cache_0.15.0   
#>  [5] rlang_1.0.6       fastmap_1.1.0     fansi_1.0.3       stringr_1.4.0    
#>  [9] styler_1.7.0      highr_0.9         tools_4.2.0       xfun_0.31        
#> [13] R.oo_1.25.0       utf8_1.2.2        cli_3.6.0         withr_2.5.0      
#> [17] htmltools_0.5.2   yaml_2.3.5        digest_0.6.29     tibble_3.1.8     
#> [21] lifecycle_1.0.3   purrr_1.0.1       R.utils_2.11.0    vctrs_0.5.1      
#> [25] fs_1.5.2          glue_1.6.2        evaluate_0.15     rmarkdown_2.14   
#> [29] reprex_2.0.1      stringi_1.7.8     compiler_4.2.0    pillar_1.8.1     
#> [33] R.methodsS3_1.8.2 pkgconfig_2.0.3
```

<sup>Created on 2023-01-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

** Notes **
Just wanted to log this, I'll take a deeper look later this week. Blind guess right now is that this is just a result of no deep CNAs

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply and thank you for reporting. Yes, indeed there were no deep cnv events. I have addressed the issue. It should now throw a proper error message.
