### ISSUE TITLE
mafSurvival: Add gene name to plot

### ISSUE THREAD

**Issue by tiagochst** [PoisonAlien/maftools#90]
This is just an small enhancement, it would be nice to add the gene name to the KM plot.
Like TP53 Mutant vs WT

![rplot](https://user-images.githubusercontent.com/145529/33129061-df0eb0ec-cf75-11e7-9525-c729d068c057.png)

**Comment by PoisonAlien** [comment]
Hi Tiago,

Apologies for late reply. Initially I thought of doing the same. But if the user provided more than two gene names, adding gene names to the plot would make it cluttery and hence I dropped the idea.
