### ISSUE TITLE
maftools gisticChromPlot

### ISSUE THREAD

**Issue by tanayb001** [PoisonAlien/maftools#901]
Hi I am new to this filed. I have generated output using GISTIC2 and also have maf file from few samples. Now I want to make chromosome copy number plot using gisticChromPlot of maftools. But i am not able to generate as I do not know how to generate input file for gisticChromPlot command. Can anyone please give me command to generate copy number plot?

Everywhere I'm getting TCGA command which is as follows:
all.lesions <- system.file("extdata", "all_lesions.conf_99.txt", package = "maftools")
amp.genes <- system.file("extdata", "amp_genes.conf_99.txt", package = "maftools")
del.genes <- system.file("extdata", "del_genes.conf_99.txt", package = "maftools")
scores.gistic <- system.file("extdata", "scores.gistic", package = "maftools")
laml.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gistic)
gisticChromPlot(laml.gistic)

But I'm not able to give my files as an input to make copy number plot on my samples. Please let me know how to give my file as an input to generate Copy number profile.

Thank you.

**Comment by ShixiangWang** [comment]
Could you show your file list of your GISTIC2 output?

**Comment by tanayb001** [comment]
Thease are the list of files generated by GISTIC2.

all_data_by_genes.txt           focal_data_by_genes.txt
all_lesions.conf_99.txt         freqarms_vs_ngenes.pdf
all_thresholded.by_genes.txt    gistic_inputs.mat
amp_genes.conf_99.txt           peak_regs.mat
amp_qplot.pdf                   perm_ads.mat
amp_qplot.png                   raw_copy_number.pdf
broad_data_by_genes.txt         raw_copy_number.png
broad_significance_results.txt  regions_track.conf_99.bed
broad_values_by_arm.txt         sample_cutoffs.txt
D.cap1.5.mat                    sample_seg_counts.txt
del_genes.conf_99.txt           scores.0.5.mat
del_qplot.pdf                   scores.gistic
del_qplot.png                   wide_peak_regs.mat
focal_dat.0.5.mat

Thank you.

**Comment by tanayb001** [comment]
I gave these connands and got this errors:

> all.lesions <- "all_lesions.conf_90.txt"
> amp.genes <- "amp_genes.conf_90.txt"
> del.genes <- "del_genes.conf_90.txt"
> scores.gis <- "scores.gistic"
> coad.gistic = readGistic(gisticAllLesionsFile = all.lesions, gisticAmpGenesFile = amp.genes, gisticDelGenesFile = del.genes, gisticScoresFile = scores.gis, isTCGA = FALSE)
-Processing Gistic files..
Error in data.table::fread(input = gisticAllLesionsFile, stringsAsFactors = FALSE,  : 
  File 'all_lesions.conf_90.txt' does not exist or is non-readable. getwd()=='/home/iit/Documents/gistic2_output'

**Comment by ShixiangWang** [comment]
It should be `all_lesions.conf_99.txt` instead of `all_lesions.conf_90.txt`.

**Comment by tanayb001** [comment]
Oh!! That was a really silly mistake. Thanks. It worked.
