### ISSUE TITLE
maftools is taking extra two samples as an input

### ISSUE THREAD

**Issue by tanayb001** [PoisonAlien/maftools#902]
Hi I'm using maftools to generate different plots. I have a merged maf file wilh 31 samples but in the summary maftools is showing 33 samples. I merged only two samples and gave input to maftools and then also it is showing 4 samples. Below is my all commands:

1. generated merged maf file using two samples:
cat *.maf > two_sample.maf

2. My commands in R :
>library(maftools)
> exp1 = read.maf(maf = "two_sample.maf")
-Reading
-Validating
--Non MAF specific values in Variant_Classification column:
  
  Variant_Classification
--Non MAF specific values in Variant_Type column:
  
  Variant_Type
-Silent variants: 19 
-Summarizing
-Processing clinical data
--Missing clinical data
--Annotation missing for below samples in MAF:
  
-Finished in 0.080s elapsed (0.135s cpu) 
Warning messages:
1: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
2: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion

> exp1
An object of class  MAF 
                  ID summary Mean Median
1:        NCBI_Build  GRCh38   NA     NA
2:            Center       .   NA     NA
3:           Samples       4   NA     NA
4:            nGenes       6   NA     NA
5: Missense_Mutation       3 0.75    0.5
6:  Nonstop_Mutation       2 0.50    0.0
7:       Splice_Site       2 0.50    0.5
8:             total       7 1.75    1.5

> getSampleSummary(exp1)
   Tumor_Sample_Barcode Missense_Mutation Nonstop_Mutation Splice_Site
1:          P02-TD                 1                2           1
2:          P01-TD                 2                0           1
3:                                      0                0           0
4: Tumor_Sample_Barcode                 0                0           0
   total
1:     4
2:     3
3:     0
4:     0

See, maftools is counting 4 samples. Please let me kno how to solve this.

Thank you.

**Comment by ShixiangWang** [comment]
Please check your `Tumor_Sample_Barcode` column in `two_sample.maf` file. It seems there are some issues with your input data.

Actually, you cannot merge two maf files just by `cat *.maf > two_sample.maf`, as the column header of the second file will be treated as a data row in merged maf and it will cause some problems for the reading.

**Comment by tanayb001** [comment]
I got that. I manually removed header and it is working fine. Thanks.
