### ISSUE TITLE
Error while generating oncoplot with clinical data

### ISSUE THREAD

**Issue by tanayb001** [PoisonAlien/maftools#907]
Hi,
I get this error while trying to make an oncoplot with clinical data using the following code:

>library(maftools)
> Ca = read.maf(maf = "merge.maf")
-Reading
-Validating
-Silent variants: 1412 
-Summarizing
-Processing clinical data
--Missing clinical data
-Finished in 0.244s elapsed (1.312s cpu) 
> clin = read.csv("2_clinical_data.txt", sep = "\t")
> prad = read.maf(maf = "merge.maf", clinicalData = clin, verbose = FALSE)
> getClinicalData(x = prad)
    Tumor_Sample_Barcode Age Gleason_Score     PSA
 1:          P01-TD  80             6   20.35
 2:          P02-TD  58             6   40.98
> fabcolors = RColorBrewer::brewer.pal(n = 4,name = 'Spectral')
> names(fabcolors) = c("6", "7", "8", "9")
> fabcolors = list(Gleason_score = fabcolors)
> oncoplot(maf = prad, top =10)
> oncoplot(maf = prad, top =10, clinicalFeatures = 'Gleason_score',
sortByAnnotation = TRUE, annotationColor = fabcolors, annotationDat = 'clin')
Error in split.default(anno, as.factor(as.character(anno[, 1]))) : 
  first argument must be a vector

Oncoplot is generating without clinical data. But I need to include clinical data. 
Please let me know how to solve it.

Thank you.

**Comment by ShixiangWang** [comment]
You can add clinical data within function `read.maf()`, there is an option for this.

**Comment by tanayb001** [comment]
I'm using below code to include clinical data:
prad = read.maf(maf = "merge.maf", clinicalData = clin, verbose = FALSE)

Isn't it correct?

**Comment by ShixiangWang** [comment]
Yeah. 

https://github.com/PoisonAlien/maftools/blob/e2ff232d71207cbef54001be69ffcf1f679820a5/R/read_maf_dt.R#L15

**Comment by tanayb001** [comment]
Now the below command is reading clinical file but plot is not generating.

Please correct my fault.

> newfile = read.maf(maf = "merge.maf", clinicalData = "2_clinical_data.txt")
-Reading
-Validating
-Silent variants: 1412 
-Summarizing
-Processing clinical data
-Finished in 0.232s elapsed (0.851s cpu) 
oncoplot(maf = newfile, top = 10, showTumorSampleBarcodes = TRUE, clinicalFeatures = 'Gleason_score', annotationColor = fabcolors)
Following columns are missing from annotation slot of MAF. Ignoring them..
[1] "Gleason_score"
Make sure at-least one of the values from provided clinicalFeatures are present in annotation slot of MAF. Here are available annotaions..
[1] "Tumor_Sample_Barcode" "Age"                  "Gleason_Score"        "PSA"                 
Error in parse_annotation_dat(annotationDat = maf, clinicalFeatures = clinicalFeatures) : 
  Zero annotaions to add! You can also provide custom annotations via annotationDat argument.

**Comment by ShixiangWang** [comment]
Send your zipped code and data files to w_shixiang@163.com, I will take a look.

**Comment by ShixiangWang** [comment]
You may want to remove the barcode.

Yeah, you can add multiple feature annotations.

**Comment by tanayb001** [comment]
Thank you so much. I just hope it also work for GISTIC files.
