### ISSUE TITLE
read.maf does not support unique Tumor_Sample_Barcode anymore

### ISSUE THREAD

**Issue by LMannarino** [PoisonAlien/maftools#91]
Hi,
due to experiment design I have a maf for each single sample in my experiment, thus the column "Tumor_Sample_Barcode" has a only one value. With the latest changes on maftools, now read.maf raises this error:

`Error in Tumor_Sample_Barcode %in% maf.tsbs`

although the column exists in the maf.

I have built a _fake_ maf by replacing some fields of "Tumor_Sample_Barcode" with another label and in this way read.maf works.

I was wondering if is it possible to allow only one sample per maf as it was before.

Thank you

**Comment by PoisonAlien** [comment]
Hi,
Sorry for late reply. Can you post your command ?

**Comment by LMannarino** [comment]
Sorry for my late reply.

Command:

`maf_ctrl <- read.maf(maf = 'CTRL.maf', isTCGA = FALSE)`

Thanks

**Comment by PoisonAlien** [comment]
Hi,
I have fixed the issue, it should be working now. Thank you for reporting. 
But may I ask why do want to process a single MAF file ? Most of the downstream analyses modules wont work with single sample and probably will result in an error.

**Comment by LMannarino** [comment]
Hi,
yes, I know it sounds strange, but for the moment I need only to summarize ('plotmafSummary') the mutational landscape for samples that are independent within eachother, and it doesn't make sense to compare and consider as a whole cohort. So, I have managed to use tables from 'plotmafSummary' with the information I need.
Of course, I'm waiting for further experiments to build a cohort and use maftools as a whole.

Thank you so much.

Laura

**Comment by PoisonAlien** [comment]
Got it. There is also a function called `mafSummary` - but I am not sure if it will be helpful for you, but you try it. For now, I am closing this issue. Thanks again.

**Comment by leiendeckerlu** [comment]
this very same error is in the most recent github version of maftools reoccuring with single sample mafs! 

Thank you!
