### ISSUE TITLE
can't load the clinical data with the maf file despite having Tumor_Sample_Barcode column

### ISSUE THREAD

**Issue by esraa-jamal** [PoisonAlien/maftools#912]
**Describe the issue**
I am trying to analyse WES data with their matched clinical data , the clinical data has (Tumor_Sample_Barcode) column which is matched with the maf file 
I read clinical data as CSV and tried to use 

(maf = filtered_TIER_maf, clinicalData = "TIER.cli.csv")

but I got an error 
<html>
<body>

Error in file.info(file) : invalid filename argument
--
 
could you please help me with this issue??

**Comment by PoisonAlien** [comment]
Hi,
I am not able to reproduce the error. Would it be possible to share a reproducible example?

**Comment by hamidghaedi** [comment]
I had the same problem and this is how I managed adding clinical data to a maf object:

```
clin <- clin[unique(maf@data$Tumor_Sample_Barcode),] # to re-order clin dataframe based on the sample order in the maf file
names(clin)[13] <- "Tumor_Sample_Barcode" # making sure that I have "Tumor_Sample_Barcode" in my dataframe
clinical.data <- data.table::as.data.table(clin) # converting dataframe to a data.table as required by maf tool
# Adding clinical data to maf file 
maf <- read.maf(maf, clinicalData = clinical.data)
```
