### ISSUE TITLE
SomaticInteractions without margin width for genenames

### ISSUE THREAD

**Issue by JadePrecious** [PoisonAlien/maftools#913]
**Describe the issue**
The marginwidth of gene names can not be set in SomaticInteractions. 
Can this parameter be added ?

**Command**
Interact <- somaticInteractions(maf = laml, top = 25, pvalue = c(0.05, 0.1)) 

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the delay. I have added two arguments `leftMar` and `topMar`  to `somaticInteractions`. I hope this helps. Please reinstall from GitHub for the changes.
