### ISSUE TITLE
Annotation problems with maftools

### ISSUE THREAD

**Issue by pradeep-sidd** [PoisonAlien/maftools#916]
I am new to R and this might be an easy problem for most of you. I am trying to create an oncoplot using TCGA data set. I am having issues creating the oncoplot with the annotations. I keep getting this error stated below. Unfortunately, this is a hard stop for me and I cannot proceed further. Any help would be appreciated.

```r
oncoplot(
  cholangio,
  top = 20,
  minMut = NULL,
  genes = NULL,
  altered = FALSE,
  drawRowBar = TRUE,
  drawColBar = TRUE,
  leftBarData = NULL,
  leftBarLims = NULL,
  rightBarData = NULL,
  rightBarLims = NULL,
  topBarData = NULL,
  logColBar = FALSE,
  includeColBarCN = TRUE,
  clinicalFeatures = AGE_GROUP,
  annotationColor = fabcolors,
  annotationDat = TRUE,
  pathways = NULL,
  selectedPathways = NULL,
  draw_titv = FALSE,
  showTumorSampleBarcodes = TRUE,
  barcode_mar = 4,
  barcodeSrt = 90,
  gene_mar = 5,
  anno_height = 1,
  legend_height = 4,
  sortByAnnotation = TRUE,
  groupAnnotationBySize = TRUE,
  annotationOrder = NULL,
  sortByMutation = FALSE,
  keepGeneOrder = FALSE,
  GeneOrderSort = TRUE,
  sampleOrder = NULL,
  additionalFeature = NULL,
  additionalFeaturePch = 20,
  additionalFeatureCol = "gray70",
  additionalFeatureCex = 0.9,
  genesToIgnore = NULL,
  removeNonMutated = TRUE,
  fill = TRUE,
  cohortSize = NULL,
  colors = TRUE,
  bgCol = "#CCCCCC",
  borderCol = "white",
  annoBorderCol = NA,
  numericAnnoCol = NULL,
  drawBox = FALSE,
  fontSize = 0.8,
  SampleNamefontSize = 1,
  titleFontSize = 1.5,
  legendFontSize = 1.2,
  annotationFontSize = 1.2,
  sepwd_genes = 0.5,
  sepwd_samples = 0.25,
  writeMatrix = FALSE,
  colbar_pathway = FALSE,
  showTitle = TRUE,
  titleText = NULL
)
```
**I get this error**

Error in split. Default(anno, as.factor(as.character(anno[, 1]))) : 
  first argument must be a vector

**Session info**
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.14.0

loaded via a namespace (and not attached):
 [1] compiler_4.2.2     Matrix_1.5-1       DNAcopy_1.72.3     tools_4.2.2       
 [5] RColorBrewer_1.1-3 survival_3.4-0     rstudioapi_0.14    splines_4.2.2     
 [9] grid_4.2.2         data.table_1.14.8  lattice_0.20-45

**Comment by PoisonAlien** [comment]
Hi,
Hi is AGE_GROUP a variable? `clinicalFeatures = AGE_GROUP`
Try to  put it in double quotes (`clinicalFeatures = "AGE_GROUP"`)

**Comment by pradeep-sidd** [comment]
Thank you so much for getting back to me Anand. I was able to get the code to work after changing the clinicalfeatures = ‘AGE_GROUP’ which is a column name.

Best

Pradeep

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
