### ISSUE TITLE
Oncoplot with multiple custom colors in clinical features 

### ISSUE THREAD

**Issue by FL512** [PoisonAlien/maftools#922]
Hi,
First of all, I really appreciate that you provide such an amazing tool for us.
I have been having a trouble with plotting a oncoplot with multiple clinical features with custom color setting.

(1) If I run the below script to plot an oncoplot with one clinical feature with a custom color setting, it worked well.
```
agecolors = RColorBrewer::brewer.pal(n = 6, name = 'YlOrRd')
names(agecolors)=c("30", "40", "50", "60", "70", "80")
agecolors = list(Age = agecolors)
print(agecolors)
oncoplot(maf = d1, clinicalFeatures = 'Age', sortByAnnotation = TRUE, annotationColor = agecolors, top=20)
```

(2) If I run the below script to plot an oncoplot with multiple clinical features without a custom color setting, it worked too.
```
oncoplot(maf=d1, clinicalFeatures=c('Sex', 'Age', "Smoking", "Stage"), sortByAnnotation=TRUE, top=20)
```

(3) However, if I wanted to run to plot an  oncoplot with multiple clinical features with a custom color setting, suddenly, it does not work properly.
```
oncoplot(maf=d1, clinicalFeatures=c('Sex', 'Age', "Smoking", "Stage"),
         annotationColor=c(agecolors, sexcolors, smokingcolors, stagecolors), sortByAnnotation=TRUE, top=20)
```

Eror message is as shown below.
```
Error in if (is.na(col)) { : argument is of length zero.
```

Could you please give me a comment/feedback when you have downtime, please?
The way to troubleshoot described in the below issue did not work for me.
https://github.com/PoisonAlien/maftools/issues/236

Sincerely,

**Session info**
```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932    LC_MONETARY=Japanese_Japan.932 LC_NUMERIC=C                  
[5] LC_TIME=Japanese_Japan.932    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.1.0     maftools_2.8.05

loaded via a namespace (and not attached):
 [1] lattice_0.20-45    fansi_1.0.4        utf8_1.2.3         R.methodsS3_1.8.2  grid_4.1.0         R6_2.5.1           lifecycle_1.0.3   
 [8] magrittr_2.0.3     pillar_1.8.1       rlang_1.1.0        cli_3.6.0          data.table_1.14.6  rstudioapi_0.14    R.oo_1.25.0       
[15] R.utils_2.12.2     Matrix_1.5-3       vctrs_0.5.2        generics_0.1.3     splines_4.1.0      RColorBrewer_1.1-3 tools_4.1.0       
[22] glue_1.6.2         survival_3.5-0     compiler_4.1.0     pkgconfig_2.0.3    tidyselect_1.2.0   tibble_3.2.0      
```

**Comment by PoisonAlien** [comment]
Hi,

Thank you and I am glad that you find the package useful.

You are almost there, its just that the colours need to be provided as a named list (not as a vector)

```r
oncoplot(maf=d1, clinicalFeatures=c('Sex', 'Age', "Smoking", "Stage"),
         annotationColor = 
list(Age = agecolors, Sex = sexcolors, Smoking = smokingcolors, Stage = stagecolors), sortByAnnotation=TRUE, top=20)
```

Let me know if this works.

**Comment by FL512** [comment]
Hi, thank you for the quick response!
No luck, because I have already tried.
Here is the error I just got a couple of minutes ago with your suggested code.
~~~
Error in if (is.na(col)) { : argument is of length zero
~~~
Does this make sense?
