### ISSUE TITLE
OncogenicPathways and plotOncogenicPathways

### ISSUE THREAD

**Issue by geejaytee** [PoisonAlien/maftools#923]
Once a list of pathways has been given for OncogenicPathways (enrichment analysis), is it possible to use the same set of pathways for plotOncogenicPathways?

Current documentation suggests that there is no way to use user-defined pathways in the latter function, and thus it is limited to the oncogenic signalling pathways used by default in OncogenicPathways.

**Comment by PoisonAlien** [comment]
Hi,

I have added the `pathdb` to `PlotOncogenicPathways` and it should do the job. If you have a custom database of pathways, provide it as a data.frame or a tsv file. Data should be of following format:

```
$cat testpw.tsv
Pathway	Gene
Cell_Cycle	CDKN1A
Cell_Cycle	CDKN1B
Cell_Cycle	CDKN2A
Cell_Cycle	CDKN2B
Cell_Cycle	CDKN2C
``` 

I hope this helps. Install from GitHub for changes.

usage:
```
PlotOncogenicPathways(maf = laml, pathways = "Cell_Cycle", pathdb = "testpw.tsv")
```

**Comment by geejaytee** [comment]
Thanks. Is there a way of restricting the OncogenicPathways plot please to the top (n) entriched pathways as found by the function itself? If we add a lot of pathways, then the plot is unreadable currently.

**Comment by geejaytee** [comment]
Never mind, can fix it by running the function, obtaining the top pathways and subsetting, like this:

````
all.paths = OncogenicPathways(maf=laml, pathways = pathdb);
dev.off();
all.paths = all.paths[ order(all.paths$fraction_affected, decreasing=T),]

png('Oncogenic_pathways.png');
OncogenicPathways(
  maf=laml,
  pathways = pathdb[pathdb$Pathway %in% all.paths$Pathway[1:10],],
  panelWidths=c(1.5, 3, 3)
)
dev.off()
````
for the top 10 mutated pathways, for example.

**Comment by geejaytee** [comment]
Now another issue has arisen. With the same code as above, the OncogenicPathways is now returning the following:

````
> OncogenicPathways(laml,pathways = pathdb)
                      Pathway   N n_affected_genes fraction_affected Mutated_samples Fraction_mutated_samples
1:     Chromatin modification 240               NA                NA              15                0.6818182
2:                DDR pathway 399               NA                NA              22                1.0000000
3: G1/S Cell cycle transition 185               NA                NA              19                0.8636364
4:           NOTCH signalling 218               NA                NA              16                0.7272727
5:             RAS signalling 128               NA                NA               0                0.0000000
6:             RNA processing 270               NA                NA              17                0.7727273
7:   ROBOSLIT/Axonal guidance 536               NA                NA              13                0.5909091
8:                    SWI/SNF  49               NA                NA              13                0.5909091
9:             WNT signalling 312               NA                NA              13                0.5909091
````
with NAs in the n_affected_genes and fraction_affected. The only thing that has changed from above is the pathdb file that I'm providing.

**Comment by geejaytee** [comment]
I've found the issue in the source - it's to do with the spaces/odd characters ("/" etc) in the pathway names which means the function get_pw_summary in oncomatrix.R (at line 724/725) doesn't merge properly. I've opened a pull request with a fix which works on my test example.
