### ISSUE TITLE
The project is not about cancer study

### ISSUE THREAD

**Issue by Niohuruzh** [PoisonAlien/maftools#926]
Hi,
  I focused on fungi mutation based on WGS data. I use `GATK` to generate the vcf files and `snpEff` to generate the annotation file. After that, I use snpEff2maf.pl to get the maf file. Finally, I want to use `maftools` to visualize the results.  However, it seems that `maftools` is designed for cancer study. So does `maftools` is also suitable for fungi study?

Looking forward to your reply!
Best wishes

**Comment by PoisonAlien** [comment]
Hi,

It depends on what you are trying to achieve. But in general - yes it works ideally with human data. 
If you are only interested in certain visualisations (such as onocplot) it will work just fine with other organisms as well.
