### ISSUE TITLE
Co-Oncoplot Top bar

### ISSUE THREAD

**Issue by albths** [PoisonAlien/maftools#928]
Hello,

Thank you for this great package! Very easy to use. 

I use the Cooncoplot function and wondered, whether it is possible to also include the top bar showing the mutation count for each sample and the side bars for gene specific mutation count, as in the main oncoplot function?

Thanks a lot!

**Comment by PoisonAlien** [comment]
Hi,

Unfortunately, it is not possible to do so at the moment.
