### ISSUE TITLE
Waterfall plot still exist ??

### ISSUE THREAD

**Issue by hafizmtalha** [PoisonAlien/maftools#929]
does the latest versions still supports waterfall function in maftools ?? I can't find it.

**Comment by PoisonAlien** [comment]
Hi,
maftools never had `waterfall` function. Maybe you meant [waterfall](https://www.bioconductor.org/packages/devel/bioc/vignettes/GenVisR/inst/doc/Intro.html#131_waterfall_(mutation_overview_graphic)) from GenVisR?

Equivalent function in maftools would be `oncoplot`
