### ISSUE TITLE
oncoplot: Annotation font size

### ISSUE THREAD

**Issue by tiagochst** [PoisonAlien/maftools#94]
Hello,

it is possible to change legend, title and gene names size font. Is it possible to change annotations font size?
Example (code: https://gist.github.com/tiagochst/15083a8595e3169a973d9612532ddd93): 
![selection_014](https://user-images.githubusercontent.com/145529/34160083-b31d9ec4-e4b2-11e7-8736-7053d684b479.png)

**Comment by PoisonAlien** [comment]
Hi,

You I have added two more arguments to oncoplot fucnction - `annotationFontSize` and `annotationTitleFontSize` which should help you to change font size and title size of annotations respectively. Please let me know if this works for you. 

Also you can control  legend, title and gene names font size with arguments `legendFontSize`, `titleFontSize` and `fontSize` arguments.
