### ISSUE TITLE
lollipopPlot can not show in_frame_del mutation

### ISSUE THREAD

**Issue by Suke-fudan** [PoisonAlien/maftools#940]
**Describe the issue**

> Chr	Start	End	Ref	Alt	Func.refGene	Gene.refGene	GeneDetail.refGene	ExonicFunc.refGene	AAChange.refGene	cytoBand
chr19	17753696	17753698	CTC	-	exonic	UNC13A	.	nonframeshift deletion	UNC13A:NM_001080421:exon19:c.2428_2430del:p.E810del	19p13.11
chr19	17774376	17774376	C	T	exonic	UNC13A	.	nonsynonymous SNV	UNC13A:NM_001080421:exon8:c.G524A:p.C175Y	19p13.11

Here is a tab delimited annovar file. I want to show the two mutions using lollipopPlot. 

I was confused because I tried many times and each time I could only draw the missense mutation but not the in_frame_del mutation(There is only the missense mutation in the plot). I checked, in the C_var.annovar.maf file, there are two mutations, the difference is that the "Variant_Type" of the in_frame_del mutation is listed as "NA".

**Command**

```r
C_var.annovar.maf = annovarToMaf(annovar = "2.hg19_multianno_1.txt", 
                                     Center = "NA", refBuild = "hg19", 
                                     table = "refGene", sep = "\t")
write.table(x=C_var.annovar.maf,file="C_var_annovar_maf",
            quote= F,sep="\t",row.names=F)
var_maf = read.maf("C_var_annovar_maf")
p <- lollipopPlot(maf = var_maf, gene = 'UNC13A', AACol = 'aaChange', refSeqID = 'NM_001080421',
                  proteinID = 'NP_001073890',showMutationRate = TRUE)
```

**Session info**
Run `sessionInfo()` and post the output below

```r
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

ggplot2_3.4.2
maftools_2.14.0
```

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue and sorry for the delay. 
I have updated the `annovarToMaf` and it should now better handle indels. I hope this helps.
