### ISSUE TITLE
How to combine multiple maf files without loss

### ISSUE THREAD

**Issue by jabbychase** [PoisonAlien/maftools#943]
Hi, I have 25 maf files which I want to combine so that I can run them through maftools. I don't want to lose any data, as is the case when using _merge_mafs_ as it deletes duplicates. I have looked into either using a _dplyr_ function (which could be far more tedious and tricky with the many columns on maf files) or using regular _merge_, but if there is better insight I would appreciate it. Ultimately I am trying to use the maftool functions _plotmafSummary_ and _oncoplot_.

My experience till now in R is very limited and mostly in relation to excel, so apologies if I'm overlooking something.

**Comment by PoisonAlien** [comment]
Hi,
I don't think it removes any duplicates. 
But you could do something as below if you don't want to use `merge_mafs`

```r
mafs = list.files(path = "/path/to/mafs/", pattern = "*.maf$", full.names = TRUE)
maf_dat = lapply(mafs, data.table::fread, sep = "\t", skip = "Hugo_Symbol")
names(maf_dat) = unlist(data.table::tstrsplit(basename(path = mafs), spli = "\\.", keep = 1))
maf = data.table::rbindlist(l = mafs, use.names = TRUE, fill = TRUE, idcol = "maf_file")
maf = maftools::read.maf(maf, removeDuplicatedVariants = FALSE)
```

I haven't tested the above code but I it should work.

**Comment by Coaxecva** [comment]
Hi @PoisonAlien,
I used the code above to merge the mafs, but got the error below:

`maf = data.table::rbindlist(l = mafs, use.names = TRUE, fill = TRUE, idcol = "maf_file")`
> Error in data.table::rbindlist(l = mafs, use.names = TRUE, fill = TRUE,  : 
>   Input is character but should be a plain list of items to be stacked

**Comment by PoisonAlien** [comment]
Hi,

The input `mafs` - it seems to be a list of files. `rbindlist` merges data tables. Please make sure `mafs` is a list of data.tables or data.frames.
