### ISSUE TITLE
Check `vc_nonSyn`` argumet in `read.maf` for details

### ISSUE THREAD

**Issue by binbinZhao2017** [PoisonAlien/maftools#947]
When I read multiple maf files using the following command
`maf_m <- lapply(paste("~/xxx/",list.files("~/xxx/"), sep = ""), read.maf, clinicalData=meta_data, verbose = FALSE)`
I got the following errors
```
Error in FUN(X[[i]], ...) : No non-synonymous mutations found
Check `vc_nonSyn`` argumet in `read.maf` for details
```
 I saw from other issues it is because of no non-synonymous mutations found in some of these files and can avoid this kind of problem by change **vc_nonSyn** parameter.

But I will use the merged maf to compare with TCGA dataset by the function tcgaCompare, so it would be better if do not change vc_nonSyn. 

Are there any other ways I can avoid these problems? Thanks.

**Comment by ShixiangWang** [comment]
May be you can set `read.maf()` in a chunk of `tryCatch()`, I mean bypassing the errored files.

```r
lapply(paste("~/xxx/",list.files("~/xxx/"), sep = ""), function(x) {
  tryCatch({
    read.maf(x, clinicalData=meta_data, verbose = FALSE)
  }, error = function(e) {
    NULL
  })
})
```

Actually, I more recommend that you merge the data firstly, then load it with `read.maf()`.

```r
maf_m <- data.table::rbindlist(lapply(paste("~/xxx/",list.files("~/xxx/"), sep = ""), data.table::fread))

maf <- maftools::read.maf(maf_m)
```

**Comment by ShixiangWang** [comment]
I found PA has already shown an example for this at https://github.com/PoisonAlien/maftools/issues/943#issuecomment-1573695668
