### ISSUE TITLE
trinucleotideMatrix function error in extracting 5' and 3' adjacent bases.

### ISSUE THREAD

**Issue by rk2802** [PoisonAlien/maftools#948]
**Describe the issue**
When using maftools trinucleotideMatrix function, I got an error in "Extracting 5' and 3' adjacent bases" 
Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
solving row 598: 'allow.nonnarrowing' is FALSE and the supplied start (81900005) is > refwidth + 1
Here I used hg19(GRCh37) as a reference genome and already checked for any other contig like chrUn in merge maf file. 
Any help in this regard is appreciated.
Thank you.

**Command**
> m.tnm = trinucleotideMatrix(maf = m, prefix = 'chr', add = TRUE, ref_genome = "BSgenome.Hsapiens.UCSC.hg19")
-Extracting 5' and 3' adjacent bases
Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 598: 'allow.nonnarrowing' is FALSE and the supplied start (81900005) is > refwidth + 1

**Comment by ShixiangWang** [comment]
have you tried GRCh38?

**Comment by rk2802** [comment]
Thank You for your response.

No. I have annotated with the GRCh37 reference sequence, that is why, for
the trinucleotide matrix, we are using GRCh37 (hg19).

**Comment by PoisonAlien** [comment]
Hi,
It seems one of your variant is located at a loci beyond the length of the chromosome. 
Can you check what chromosome it is? You could try as below..

```r
maf@data[Start_Position %in% 81900005]
```

**Comment by rk2802** [comment]
Yeah
Chromosome X

**Comment by PoisonAlien** [comment]
Would it be possible to share a reproducible example data?

**Comment by rk2802** [comment]
Sir, I am using a whole data set after running merge_maf function.

**Comment by PoisonAlien** [comment]
Hi,

There is something wrong with your variants.
The offending variant is:
```r
Chromosome    Start      End Reference_Allele Tumor_Seq_Allele2 Tumor_Sample_Barcode upstream downstream
 chr17 81900005 81900007                G                 A              CaBrI08 81899986   81900026
```

and chr17 length in hg19 is `81195210` which is smaller than the variant position `81900005`

```
fetchChromSizes hg19 | grep -w chr17
chr17   81195210
```

however, chr17 size is much bigger in hg38 and can accommodate your variant.
```
fetchChromSizes hg19 | grep -w chr17
chr17   83257441
```

As suggested by @ShixiangWang , try hg38 as ref genome. I would also carefully investigate how your maf files were generated.

**Comment by ShixiangWang** [comment]
Good to hear that.
