### ISSUE TITLE
confused aa.length in lollipopPlot()

### ISSUE THREAD

**Issue by X1angyang** [PoisonAlien/maftools#950]
**Describe the issue**
Hi, when i use lollipopPlot()  plot FLT3 domain, it shows there are 996 aa, actually，there are 993 aa in FLT3(NM_004119). I download the "protein_domains.RDs", it shows 993 aa, too. Why does this phenomenon occur?
![image](https://github.com/PoisonAlien/maftools/assets/51201520/382cbd98-287f-4b74-9511-3a0a47e45f3e)
![image](https://github.com/PoisonAlien/maftools/assets/51201520/aa5f7352-615a-420a-b18d-1403556d5d9e)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late response. I can't seem to reproduce your issue. On my system, your example shows 993 as the length. I believe, you are using an older version of the package. Could you please update it and try again?
I am closing the issue now, feel free to comment if you still see the same.

**Comment by X1angyang** [comment]
I updated the R package to the latest version, and now FLT3 is displaying correctly. Thank you.
