### ISSUE TITLE
bug:sortByGeneOrder() discard negative samples

### ISSUE THREAD

**Issue by X1angyang** [PoisonAlien/maftools#951]
**Describe the issue**
In the function oncoplot2(), there is a parameter called keepGeneOrder. When set to TRUE, it invokes the sortByGeneOrder() function to sort the data by genes. However, if there are samples in the data that do not have gene mutations (i.e., negative samples), the sortByGeneOrder() function will discard the information of these samples directly.

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
```

**Session info**
Run `sessionInfo()` and post the output below

```r
```

**Comment by ShixiangWang** [comment]
Do you mean `coOncoplot()`? You may want to set `removeNonMutated = FALSE`.

**Comment by X1angyang** [comment]
![image](https://github.com/PoisonAlien/maftools/assets/51201520/2bd103e4-ac25-4962-8b6d-4d3d29b7f529)
oncoplot() function.
Not work. I think it will work if there are no yellow box  code, because colnames in numMat has already remove negative samples.

**Comment by ShixiangWang** [comment]
@X1angyang Thank you for diving into the code. Currently, please modify the code on your own (or created a modified fork) or wait for @PoisonAlien to optimize/update the code.
