### ISSUE TITLE
Borderline 

### ISSUE THREAD

**Issue by rajkump** [PoisonAlien/maftools#958]
I am doing Oncoplot with options 
```
"annoBorderCol="black",borderCol="black",bgCol="white"".

```

**issue**
Borderline is not present for beginning of sample and also not for the last gene. Also borderline is not present for annotation bar last row. Please see the attached figure.

**R version**
R version 4.1.0 (2021-05-18)
maftools_2.8.0

![Picture1](https://github.com/PoisonAlien/maftools/assets/38671329/190c3f35-49b7-4c4b-b357-d838892fcd1d)

**Comment by rajkump** [comment]
Hi Anand,

Just wondering. Do you have any updates for me? Is the issue doable?

Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Hi Praveen,

Thanks for the issue. I have pushed changes which should address your issues. Please install from GitHub for changes.

For the third point, you can use `topBarLims` to set the limit and `topBarHline` to mark the ticks and add a line. If you would like to hide the line, set `topBarHlineCol = NA`

I hope this helps.
