### ISSUE TITLE
oncostrip doesn't work for my MAF

### ISSUE THREAD

**Issue by reiko-n** [PoisonAlien/maftools#96]
I greatly appreciate your suggestion in advance!

Although I could run oncostrip function using laml example data, it generate error when I apply the function to my own data.  I here used top=XX option, but even when I specify some genes, it returns the same error;
> oncostrip(maf = mafdata, top=3)
Error in numMat[geneOrder[geneOrder %in% rownames(numMat)], , drop = FALSE] : 
  subscript out of bounds

I read MAF files as;
> mafdata <- read.maf(maf = maffiles, clinicalData = epidata)
Summarizing..
                   ID summary    Mean Median
 1:        NCBI_Build      NA      NA     NA
 2:            Center      NA      NA     NA
 3:           Samples     515      NA     NA
 4:            nGenes   17350      NA     NA
 5:   Frame_Shift_Del    7747  15.043      1
 6:   Frame_Shift_Ins    2233   4.336      1
 7:      In_Frame_Del     582   1.130      0
 8:      In_Frame_Ins      30   0.058      0
 9: Missense_Mutation  122553 237.967    122
10: Nonsense_Mutation    8100  15.728      9
11:       Splice_Site    5778  11.219      5
12:             total  147023 285.482    138
Gene Summary..
       Hugo_Symbol Frame_Shift_Del Frame_Shift_Ins In_Frame_Del In_Frame_Ins Missense_Mutation
    1:         APC              71              42            0            0                42
    2:        TP53              21               7            1            2               204
    3:         TTN              13              10            1            0               420
    4:        KRAS               1               0            0            0               149
    5:       SYNE1               4               0            0            0               159
                                                                                    
17346:      ZNF627               0               0            0            0                 1
17347:      ZNF788               0               0            0            0                 1
17348:      ZNF879               0               0            0            0                 1
17349:       ZNRF1               0               0            0            0                 1
17350:      ZSCAN9               0               0            0            0                 0
       Nonsense_Mutation Splice_Site total MutatedSamples AlteredSamples
    1:               252          15   422            303            303
    2:                37          16   288            269            269
    3:                32          14   490            235            235
    4:                 0           0   150            148            148
    5:                13           7   183            130            130
                                                                  
17346:                 0           0     1              1              1
17347:                 0           0     1              1              1
17348:                 0           0     1              1              1
17349:                 0           0     1              1              1
17350:                 1           0     1              1              1
NOTE: Possible FLAGS among top ten genes:
[1] TTN   SYNE1 FLG   MUC16 MUC17 OBSCN
17805 Levels: A1BG A2M A2ML1 A3GALT2 A4GNT AAAS AACS AADACL3 AADACL4 AAK1 AAMP AARS AARS2 ... ZZZ3
Checking clinical data..
Done !

My original mafffiles look like this;
> head(mafffiles)
   Tumor_Sample_Barcode Hugo_Symbol Chromosome Start_position End_position Strand
1:                   18      SORCS1         10      108466322    108466322      +
2:                   18       ZNFX1         20       47881294     47881294      +
3:                   18       ZNF92          7       64863830     64863830      +
4:                   18     SIPA1L3         19       38573152     38573152      +
5:                   18    C1orf106          1      200880834    200880834      +
6:                   18       TM2D1          1       62190793     62190793      +
   Variant_Classification Variant_Type Reference_Allele Tumor_Seq_Allele1 Tumor_Seq_Allele2
1:      Missense_Mutation          SNP                G                 G                 A
2:      Missense_Mutation          SNP                G                 G                 A
3:      Missense_Mutation          SNP                G                 G                 A
4:      Missense_Mutation          SNP                G                 G                 A
5:      Missense_Mutation          SNP                C                 C                 T
6:      Missense_Mutation          SNP                C                 C                 G

> table(maffiles$Variant_Classification)

  Frame_Shift_Del   Frame_Shift_Ins      In_Frame_Del      In_Frame_Ins       Splice_Site 
             7747              2233               582                30              5778 
Missense_Mutation Nonsense_Mutation 
           122553              8100

I'd like to first solve a problem for oncostrip, I also get an error with lollipopPlot (and oncoplot crush my computer);
> lollipopPlot(maf = mafdata, gene = 'APC', showMutationRate = TRUE, domainLabelSize = 3, defaultYaxis = FALSE)
Error in if (pchange[pchange %in% colnames(mut)] > 0) { : 
  argument is of length zero

Thank you!

**Comment by PoisonAlien** [comment]
Hi,
My immediate guess would be because of how you have named your samples in your maf. It appears that they are integers ? Can you change your sample names to begin with a character ? 
i.e, 18 -> sample18 or something similar.

For lollipop plot you need a column containing protein change information and your maf file seems to lack that information. 

Let me know if this helps.

**Comment by reiko-n** [comment]
Thank you so much for your reply!  lollipopPlot is now working after I included Protein_Change column as suggested.
I also changed Tumor_Sample_Barcode but still oncosrtrip shows the same error;

>head(maffiles)
      Hugo_Symbol Chromosome Start_position End_position Reference_Allele
1:        CNTNAP1         17       40843932     40843932                C
2:           CHD4         12        6709138      6709138                G
3:          PUF60          8      144906533    144906533                C
4:           MYLK          3      123385149    123385149                G
5: CTD-2192J16.22         19       12759073     12759073                C
6:        PCDHGB4          5      140769000    140769000                G
   Tumor_Seq_Allele2 Variant_Classification Variant_Type Tumor_Sample_Barcode
1:                 T      Missense_Mutation          SNP   T18-Tumor-4C
2:                 A      Missense_Mutation          SNP   T18-Tumor-4C
3:                 G      Missense_Mutation          SNP   T18-Tumor-4C
4:                 A      Missense_Mutation          SNP   T18-Tumor-4C
5:                 T      Missense_Mutation          SNP   T18-Tumor-4C
6:                 A      Missense_Mutation          SNP   T18-Tumor-4C
   Protein_Change
1:        p.P818L
2:        p.S428L
3:         p.A21P
4:       p.R1250C
5:         p.G47R
6:        p.A517T

> oncostrip(maf = mafdata, top=3)
Error in numMat[geneOrder[geneOrder %in% rownames(numMat)], , drop = FALSE] : 
  subscript out of bounds

I appreciate your suggestion!

**Comment by PoisonAlien** [comment]
Hi,
That is weird. Do you think you can share your maf file ? You can email (anandmt3@gmail.com) me if you don't want to attach it here.

**Comment by lxilxi** [comment]
I had the same problem for my MAF, both oncoprint and oncostrip had the same error.

**Comment by lxilxi** [comment]
I had the same problem with my MAF when using oncostrip.  
Also for oncoplot, the top option doesn't work and it ends up plotting the whole gene list which made the plot hard to read.
Any insight would be appreciated.

**Comment by lxilxi** [comment]
Just to followup here:  
When using the example MAF bundled with the package, both oncoplot and oncostrip works.
Here are the commands used: 

> laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
oncoplot(maf = laml, top = 5)
oncostrip(maf = laml, genes = c('NPM1', 'RUNX1'))
