### ISSUE TITLE
CNV differences between the two cohorts

### ISSUE THREAD

**Issue by xiaoming123lk** [PoisonAlien/maftools#962]
Hello, thank you for the maftools R package. I am doing an SCNV analysis and I want to compare the CNV differences between the two cohorts at the genetic level to better explain DEG. I wonder if the output in GISTIC 2.0 can be implemented in maftools?

**Comment by ShixiangWang** [comment]
Check http://bioconductor.org/packages/release/bioc/vignettes/maftools/inst/doc/maftools.html#8_Processing_copy-number_data
