### ISSUE TITLE
Missing required field error

### ISSUE THREAD

**Issue by crystalclear58** [PoisonAlien/maftools#963]
**Describe the issue**
Hi Anand, I am not very familiar with R. I tried to use Maftools in order to generate an oncoplot and I am getting an error:  
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  : 
  missing required fields from MAF: Hugo_Symbol

**Command**
> laml.maf <- read.delim("E:/maftools data.tsv", header=FALSE)
>   View(laml.maf)
> laml.clin <- read.delim("D:/Clinical data for baseline relapse figure.tsv")
>   View(laml.clin)
> library(data.table)
data.table 1.14.8 using 2 threads (see ?getDTthreads).  Latest news: r-datatable.com
> library(maftools)
> laml = read.maf(maf = laml.maf, clinicalData = laml.clin)
-Validating
Error in validateMaf(maf = maf, isTCGA = isTCGA, rdup = removeDuplicatedVariants,  : 
  missing required fields from MAF: Hugo_Symbol

**Session info**
Run `sessionInfo()` and post the output below

R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.16.0   data.table_1.14.8

loaded via a namespace (and not attached):
[1] compiler_4.3.1     Matrix_1.5-4.1     DNAcopy_1.74.1    
[4] tools_4.3.1        RColorBrewer_1.1-3 survival_3.5-5    
[7] splines_4.3.1      grid_4.3.1         lattice_0.21-8

**Comment by ShixiangWang** [comment]
'Hugo_Symbol' is a typical column in MAF data, it contains gene names the mutations occurred at. I guess you haven't annotated your MAF? You can check your MAF file with EXCEL or a similar viewer.

**Comment by crystalclear58** [comment]
Thank you so much for replying on the weekend! The file is annotated correctly. I had to remove header=FALSE from this line-

laml.maf <- read.delim("E:/maftools data.tsv", header=FALSE)

This is a great package and I created a beautiful oncoplot!

**Comment by ShixiangWang** [comment]
Great
