### ISSUE TITLE
font type used in oncoplot

### ISSUE THREAD

**Issue by rajkump** [PoisonAlien/maftools#964]
**Question**
Could you please let me know the font type used in oncoplot genename and frequency %? I will be adding some text next to it. Just want to be consistent.

**Session info**
```
R version 4.1.0 (2021-05-18)
maftools_2.17.0
```

Thanks,
Praveen

**Comment by PoisonAlien** [comment]
Hi,

it uses base font family. I believe it's `Helvetica` - italicised for gene names.
