### ISSUE TITLE
Does Maftools support row annotations?

### ISSUE THREAD

**Issue by raulfalcao** [PoisonAlien/maftools#965]
Hi, I was wondering if maftools could display rows annotation?
Following an image as example
[The Journal of Pathology - 2015 - Martelotto - Genomic landscape of adenoid cystic carcinoma of the breast-6.pdf](https://github.com/PoisonAlien/maftools/files/12177714/The.Journal.of.Pathology.-.2015.-.Martelotto.-.Genomic.landscape.of.adenoid.cystic.carcinoma.of.the.breast-6.pdf)

**Comment by PoisonAlien** [comment]
Hi,
Current implementation does not support row annotations. I would be happy to add it as a feature sometimes.
