### ISSUE TITLE
Survival analysis can not be run

### ISSUE THREAD

**Issue by superjmiscool** [PoisonAlien/maftools#967]
```r
mafSurvival(maf = laml, genes = "TP53", time = 'OS.time', Status = 'OS', groupNames = c("Mutant", "WT"),
col = c("#ED0000", "#00468B"), isTCGA = T)
Looking for clinical data in annoatation slot of MAF..
Number of mutated samples for given genes: 
TP53 
 673 
Removed 968 samples with NA's
Median survival..
Empty data.table (0 rows and 3 cols): Group,medianTime,N
Error in survfit.formula(formula = survival::Surv(time = Time, event = Status) ~  : 
  data set has no non-missing observations
In addition: Warning message:
In max(event[who2]) : no non-missing arguments to max; returning -Inf
```

what's wrong with this?
Does anyone know about it?

**Comment by PoisonAlien** [comment]
Hi,
Could you please print show the columns for the OS and OS.time?

For example,
```r
> laml@clinical.data[,.(days_to_last_followup, Overall_Survival_Status)]
     days_to_last_followup Overall_Survival_Status
  1:                   365                       1
  2:                   792                       1
  3:                  2557                       0
  4:                   577                       1
  5:                   945                       1
 ---                                              
189:                  1581                       0
190:                   822                       1
191:                   577                       1
192:                  1885                       0
193:                  1887                       0
```

**Comment by superjmiscool** [comment]
> laml@clinical.data[,.(OS, OS.time)]
     OS OS.time
  1:  0       0
  2:  0    1523
  3:  1     121
  4:  0     607
  5:  0     426
 ---           
964:  1    1335
965:  1     261
966:  1     340
967:  0     513
968:  1       6

> Hi, Could you please show the columns for the OS and OS.time?
> 
> For example,
> 
> ```r
> > laml@clinical.data[,.(days_to_last_followup, Overall_Survival_Status)]
>      days_to_last_followup Overall_Survival_Status
>   1:                   365                       1
>   2:                   792                       1
>   3:                  2557                       0
>   4:                   577                       1
>   5:                   945                       1
>  ---                                              
> 189:                  1581                       0
> 190:                   822                       1
> 191:                   577                       1
> 192:                  1885                       0
> 193:                  1887                       0
> ```

It seems that no problem and it is no problem to do operation outside survival analysis.
thank you for your answer

**Comment by PoisonAlien** [comment]
One reason I can this is that your columns are non-numeric maybe. You could change it and try again,

```r
laml@clinical.data[,OS :=  as.numeric(OS)]
laml@clinical.data[,OS.time :=  as.numeric(OS.time)]
```

**Comment by superjmiscool** [comment]
I tried your code, but survival analysis still returned an error message.
> class(laml@clinical.data$OS)
[1] "numeric"
> class(laml@clinical.data$OS.time)
[1] "numeric"

I'll try some more. Thank you for your answer.

> One reason I can this is that your columns are non-numeric maybe. You could change it and try again,
> 
> ```r
> laml@clinical.data[,OS :=  as.numeric(OS)]
> laml@clinical.data[,OS.time :=  as.numeric(OS.time)]
> ```
