### ISSUE TITLE
number beside SNV Class in plotmafsummary

### ISSUE THREAD

**Issue by me-nobody** [PoisonAlien/maftools#971]
![maftools_num](https://github.com/PoisonAlien/maftools/assets/7254581/579b9d96-e7e4-477f-86ff-80bdb2e978b2)
Hi,
what is this number beside SNV class in the output of plotmafsummary?
BW
Anubrata

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the late reply. It's the number of SNVs for the corresponding SNV type.
