### ISSUE TITLE
Non standard Ti/Tv class: 1814TRUE

### ISSUE THREAD

**Issue by dalalsult** [PoisonAlien/maftools#973]
**Describe the issue**
Hi, I am very new to maftools. I've been encountering an issue when running plotmafsummary and titv functions. The issue has been raised before and seems to be due to incorrect annotations of INDELS to SNPS. However, I generated my data using VEP and not annovar, therefore I'm not sure if the previous solution discussed for this warning could be applied here.
Please let me know if you need any further details. Any assistance will be greatly appreciated.

**Command**
Please post your commands and the output (errors or any unexpected output)

```r
plotmafSummary(maf = maf_analysis, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = TRUE) 
Warning message:
In titv(maf = maf, useSyn = TRUE, plot = FALSE) :
  Non standard Ti/Tv class: 1814TRUE
maf.titv = titv(maf = maf_analysis, plot = FALSE, useSyn = TRUE)
Warning message:
In titv(maf = maf_analysis, plot = FALSE, useSyn = TRUE) :
  Non standard Ti/Tv class: 1814TRUE
```

**Session info**
Run `sessionInfo()` and post the output below

```r
R version 4.3.0 (2023-04-21)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Dublin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] maftools_2.16.0

loaded via a namespace (and not attached):
 [1] compiler_4.3.0     Matrix_1.6-1       DNAcopy_1.74.1     tools_4.3.0        RColorBrewer_1.1-3
 [6] survival_3.5-7     rstudioapi_0.15.0  splines_4.3.0      grid_4.3.0         data.table_1.14.8 
[11] lattice_0.21-8    
```

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue and sorry for the tardy response. 
Would it be possible to share a reproducible example?

**Comment by dalalsult** [comment]
Thanks for getting back to me. Yes, all data is already fully anonymised so I don't mind sharing. Could you give me an email address to send this?

**Comment by PoisonAlien** [comment]
Hi,
This is my mail: anandmt3@gmail.com
