### ISSUE TITLE
SomaticInteractions - pAjd method request

### ISSUE THREAD

**Issue by gaborbedics** [PoisonAlien/maftools#974]
Could you please provide the method for pAjd in SomaticInteractions function?
Many thanks in advance!

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue. Default method used for p adjust is FDR, but you can use `p.adjust` on the output with your favorite method.

```r
laml_si  = somaticInteractions(laml, returnAll = TRUE)
laml_si$pAdj_bh= p.adjust(laml_si$pValue, method = "BH")
```

I hope this helps.
