### ISSUE TITLE
lollipopPlot2 no plot, but lollipopPlot can plot for gene PALB2

### ISSUE THREAD

**Issue by geejaytee** [PoisonAlien/maftools#975]
Essentially, as above. Using lollipopPlot2 to do a comparison between two maf files for the gene PALB2, I receive the following error:
```r
> lollipopPlot2(
  m1 = maf1,
  m2 = maf2,
  gene = "PALB2",
  AACol1 = "aaChange",
  AACol2 = "aaChange",
  m1_label = 'all',
  m2_label = 'all',
  showDomainLabel =  TRUE,
  domainLabelSize = 0.4,
  labPosAngle = 90,
  labPosAngle = 0.4,
  pointSize = 0.8
)
Error in 0:max(prot$aa.length) : result would be too long a vector
```
but running the singular lollipopPlot() function:
```r
> lollipopPlot(
  maf = maf1,
  AACol = "aaChange",
  gene = "PALB2"
)
```
does generate a plot. Is there a problem with the function?

I'm running maftools v2.10.05 within a trusted research environment, so installing libraries is possible but very fiddly.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue. I am having hard time reproducing the issue. Is it possible to share a reproducible example?

```
maf1_palb2 = subsetMaf(maf = maf1, genes = "PALB2", fields = "aaChange")
maf2_palb2 = subsetMaf(maf = maf2, genes = "PALB2", fields = "aaChange")
```

**Comment by geejaytee** [comment]
I can't get the maf files out of the trusted research environment to give you. However, I've tried with TCGA data and I'm not finding an issue, so I'm confused (this is running v2.14.05) outside the RE.
