### ISSUE TITLE
Feature request: Extend subsetMaf to drop samples by barcode

### ISSUE THREAD

**Issue by FriederikeHanssen** [PoisonAlien/maftools#976]
Hi! 

I just encountered the case where I wanted to drop 2 out of a couple 100 samples for parts of the analysis. It would be very useful to have the inverse in subsetMaf (or a similar function), so to allow to drop samples by name.

And as always, thank you for the fantastic package 🙏

**Comment by PoisonAlien** [comment]
Hi,

Maybe `filterMaf()` would be of interest here..

```r
laml.maf <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
laml <- read.maf(maf = laml.maf)
#get rid of samples of interest
filterMaf(maf = laml, tsb = c("TCGA-AB-2830", "TCGA-AB-2804"))
#remove genes of intrest
filterMaf(maf = laml, genes =c("TTN", "AHNAK2"))
```

**Comment by FriederikeHanssen** [comment]
oh great, yes exactly what I was looking for! Thank you for the speedy help!
