### ISSUE TITLE
Can I get maftools package for R version 3.2

### ISSUE THREAD

**Issue by Huffyphenix** [PoisonAlien/maftools#98]
Hi,
Thank you for developing such a nice tool to summarize, analyze, annotate and visualize MAF files👍. It is very helpful for the work that I am doing now. Your development speed is so fast, and it performs well on R>=3.4. But for some reasons, my R can't be updated into a latest version, so I am looking for a version of maftools that can used on R version 3.2. Although I have downloaded the release V 0.99.30 package you released on github release part, but I found some useful arguments are not suitable for it, such as the front argument for oncoplot(). So, **I am here to ask if you can give me a old version of maftools that can be used on R version 3.2**, it will be very helpful for me.

Thank you very much, and I am looking forward to your reply.  :bowtie: 
Happy new year and best wishes.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for nice words and I am glad that you find the package useful. 

May I ask why are you still using version 3.2 of R ? Most of packages have already migrated to 3.4 and wont work on 3.2. Even if if I decrease maftools R requirement to 3.2, many dependency packages would fail/complain to install. 

Sorry, for now only way is to install 3.4

**Comment by Huffyphenix** [comment]
Hi,
Thank you for your replying. Your work is really helpful, I didn't exaggerate it.
As you asked me, I am still using R 3.2 cause there are many other people's works on the server using 3.2 of R, update of R will lead a lot of problems to them. So I wondered if I can get a maftools can be used on R 3.2.
I understand that for maftools V1.4.10 the only way to solve this problem is to update R to 3.4. What I mean is if there are still a old version maftools source code, like V0.99.30 I found on your github, which still using old version dependency packages, may help for me to solve my problem. For these dependency packages, I can use a old version of them too as I do now for V0.99.30.

Thank you.

**Comment by PoisonAlien** [comment]
Ah, I see !!

I have built a pkg binary to which should install with R >= 3.2, but I cannot promise it will work (package dependencies might complain). 

Install it from command line like this:

```r
R CMD INSTALL maftools_1.4.10.tar.gz
```
[maftools_1.4.10.tar.gz](https://github.com/PoisonAlien/maftools/files/1599715/maftools_1.4.10.tar.gz)

**Comment by Huffyphenix** [comment]
Thank you very much, that's very kind of you.
I have a success try for install maftools by installing old version dependency packages. 
Thanks again.

**Comment by PoisonAlien** [comment]
Glad to be of help. I'm closing this issue for now.
