### ISSUE TITLE
ICGC dataset error in plotmafSummary

### ISSUE THREAD

**Issue by sinumol** [PoisonAlien/maftools#980]
Hi all,
I tried to convert simple somatic muttaion file of ICGC databse to MAF using the below commands in maftools. 
> icgc =system.file("extdata", "ssm_orca_In.tsv.gz", package="maftools")
> maf <- icgcSimpleMutationToMAF(icgc = icgc, addHugoSymbol = TRUE)
Converting Ensemble Gene IDs into HGNC gene symbols.
Done! Original ensemble gene IDs are preserved under field name ens_id
--Removed 904661 duplicated variants
--Found  101696  variants with no Gene Symbols
--Annotating them as 'Unknown' for convenience
--Non MAF specific values in Variant_Classification column:
  NA
--Non MAF specific values in Variant_Type column:
  NA

It is converted but when i tried to plot mafsummary it is giving an error.
> plotmafSummary(maf)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘getSampleSummary’ for signature ‘"data.table"’

@PoisonAlien Please help me to resolve this issue

**Comment by PoisonAlien** [comment]
Hi,

```
icgc =system.file("extdata", "ssm_orca_In.tsv.gz", package="maftools")
```

Above command is only to access the example file bundled with the maftools package. You will have to use the function on your own file. 

```
icgc <- "ssm_orca_In.tsv.gz" #complete path to your file
maf <- icgcSimpleMutationToMAF(icgc = icgc, addHugoSymbol = TRUE)
```
