### ISSUE TITLE
Oncoplot - Cell hight and width

### ISSUE THREAD

**Issue by kunstner** [PoisonAlien/maftools#982]
Hi @PoisonAlien 

I have a request for a valuable feature. We usually prefer oncoplots with rectangular cells. Is it possible to add options like  cellwidth and cellheight to be able to decide on the shape of the cells (like in the pheatmap package)? Both options would take a numeric value (point size).

Many thanks,
 Axel

**Comment by PoisonAlien** [comment]
Hi Axel,

Thank you for the suggestion. Unfortunately, `oncoplots` are drawn with the `image` command in base R. Unfortunately, it does not allow to specify the sizes of the grid.

**Comment by kunstner** [comment]
Thanks for the quick reply. //axel
