### ISSUE TITLE
Question about gisticChromPlot

### ISSUE THREAD

**Issue by AnnaDvdH** [PoisonAlien/maftools#983]
Hello,

I have successfully ran GISTIC2 in canine data, and managed to get gisticChromPlot to generate a plot. However, the dog has 38 chromosomes, and the plot only shows the amplifications and deletions of the first 24 chromosomes (matching it to the human 23, X and Y chromosomes), meaning that I am missing data. So my question is: is there a way to make gisticChromPlot run with non-human data?

Thank you in advance and all the best.
![gistic_plot_cf4](https://github.com/PoisonAlien/maftools/assets/35726742/f8254e41-a19c-426e-bdf4-c3c24cbb8bfb)

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue. Unfortunately, the current implementation does not support non-human genomes. However, I don't see any problems with support for other organisms. It just needs the contig names and sizes. 
Would it be possible to share the GISTIC object to test?

**Comment by AnnaDvdH** [comment]
Hello,

Thank you very much for the quick response! Here is a dummy-file of the dog CNA data. Hope this will suffice.
[gistic_canfam4.zip](https://github.com/PoisonAlien/maftools/files/13239512/gistic_canfam4.zip)

Thank you again for all the help and all the best.
