### ISSUE TITLE
Plot both arm-level(broad) versus focal amplifications (and deletions)

### ISSUE THREAD

**Issue by Donatella93** [PoisonAlien/maftools#987]
Hi! I was wondering if there is a way to plot both broad versus focal events by using coGisticChromPlotV.R (now only focus events are shown), since in the GISTIC results the 2 informations are stored in separate files...

Thanks

**Comment by biosunsci** [comment]
Let me work on it, but this may take some time.

**Comment by biosunsci** [comment]
> Hi! I was wondering if there is a way to plot both broad versus focal events by using coGisticChromPlotV.R (now only focus events are shown), since in the GISTIC results the 2 informations are stored in separate files...
> 
> Thanks

did you mean a figure like this?
![image](https://github.com/PoisonAlien/maftools/assets/15091103/27ca8310-22fa-4781-92fe-21e6565ec656)

**Comment by Donatella93** [comment]
Exactly that figure I was referring to.
Thanks for the answer!

**Comment by wangzunq** [comment]
Any update on this? Really helpful on this type of plot.
