### ISSUE TITLE
clinicalEnrichment seems to ignore samples with no mutations

### ISSUE THREAD

**Issue by Marmach** [PoisonAlien/maftools#989]
I have a small cohort of patients (37) with limited number of genes analyzed (mutations + CNV). Only 27/37 patients have any alterations in this set of genes, so 10 patients have no records in MAF. However, they are included in clinical data. When I try to use `clinicalEnrichment`, it seems to ignore patients that don't have mutations in any of analyzed genes as if they were not part of the cohort.

![obraz](https://github.com/PoisonAlien/maftools/assets/32894259/fb68cd3a-cacf-4b23-8bcd-02b2341cf43d)

Is there a workaround other than adding somy dummy variants to the MAF?

maftools version: 2.17.0

**Comment by PoisonAlien** [comment]
Hi,
Sorry for the late reply. Unfortunately, the only workaround would be to add a dummy variant. Maybe you could add an intronic variant for these samples so that they are ignored from all the analysis but you still get to keep the whole cohort.
