### ISSUE TITLE
 subsetMaf() query argumet can't get Shiny reactive value from webpage input.

### ISSUE THREAD

**Issue by Huffyphenix** [PoisonAlien/maftools#99]
Hi,
I am doing some work to show a pic generated by maftools on web server, but it seems subsetMaf() "query" argument can't get a Shiny reactive value input from web server. Below is a simple test:
subsetMaf() works well on console on R like below:
# read data-------------------------------------------------------
library(magrittr)
mc3_pass <- readr::read_rds(file.path(config$database, "TCGA", "snv", "snv_mutation_mc3_public.pass.filtered_maf-4cancers.rds.gz")) # test data include clinical data, which include a column called "cancer_types"

# console test works well -------------------------------------------------
ct <- reactive({c("LUAD")}) # pre define a object stored a cancer type name like reactive value in shiny.
query = as.expression("cancer_types %in% isolate(ct())") # define a query for filter, isolate() used to get the value of reactive value on console.
maftools::subsetMaf(mc3_pass, query = query, mafObj = T) -> gene_list_maf  # subsetMaf filter

gene_list_maf %>%
  maftools::getClinicalData() # check the filter results
# works well on console, cancer_types filter successfully as you can see below.
Tumor_Sample_Barcode cancer_types
1: TCGA-05-4244-01A-01D-1105-08         LUAD
2: TCGA-05-4249-01A-01D-1105-08         LUAD
3: TCGA-05-4250-01A-01D-1105-08         LUAD
4: TCGA-05-4382-01A-01D-1931-08         LUAD
5: TCGA-05-4384-01A-01D-1753-08         LUAD
---                                          
  508: TCGA-NJ-A55O-01A-11D-A25L-08         LUAD
509: TCGA-NJ-A55R-01A-11D-A25L-08         LUAD
510: TCGA-NJ-A7XG-01A-12D-A397-08         LUAD
511: TCGA-O1-A52J-01A-11D-A25L-08         LUAD
512: TCGA-S2-AA1A-01A-12D-A397-08         LUAD

# shiny reactive value lead an error ----------------------------------------
# before run code below, please delete objects generated before.
mc3_pass <- readr::read_rds(file.path(config$database, "TCGA", "snv", "snv_mutation_mc3_public.pass.filtered_maf-4cancers.rds.gz")) # test data include clinical data, which include a column called "cancer_types"
library(shiny)
Lung_choice <- list(
  "Lung Adenocarcinoma(LUAD)" = "LUAD",
  "Lung Squamous Cell Carcinoma(LUSC)" = "LUSC"
)
ui <- fluidPage(
  checkboxGroupInput(inputId = "select",label = "Select cancers",
                     choices = Lung_choice),
  actionButton("go",label = "Go"),
  shiny::textOutput(outputId = "table")
)

server <- function(input, output, session) {
  ct <- reactive({
    input$select
  })
  observeEvent(input$go,{
    print(ct())
    print(class(ct()))
    ct_2 <- as.character(ct())
    print(ct_2)
    # query = as.expression("cancer_types %in% ct()") # Error in ct: could not find function "ct"
    # query = as.expression("cancer_types %in% ct_2") # Error in eval: object 'ct_2' not found
    query = as.expression("cancer_types %in% input$select") # Error in eval: object 'input' not found
    print(query)
    maftools::subsetMaf(mc3_pass, query = query, mafObj = T) -> gene_list_maf # subsetMaf filter
    print("maf done!")
    gene_list_maf %>%
      maftools::getClinicalData() %>%
      dplyr::select(cancer_types) %>%
      unique() %>% t() %>%
      as.vector()->.x# check the filter results
    print(".x done!")
    output$table <- renderText({
      return(.x)
    })
    print("out done!")
    print(.x)
  })
}
shinyApp(ui, server)

# output shows that object ct() and ct_2 is exactly store the value from webpage input---------------------------
[1] "LUAD"
[1] "character"
[1] "LUAD"
expression("cancer_types %in% input$select")
Warning: Error in eval: object 'input' not found
Stack trace (innermost first):
    75: eval
    74: eval
    73: [.data.table
    72: [
    71: maftools::subsetMaf
    70: observeEventHandler [#14]
     4: <Anonymous>
     3: do.call
     2: print.shiny.appobj
     1: <Promise>

I guess it is the problem of environment, but it is difficult for me to solve this problem, do you have any suggestion? Is there any way to solve this problem? 
Thank you very much, and I am looking forward for your reply.

**Comment by PoisonAlien** [comment]
Hi,
My apologies, I am not familiar with shiny development or the apps. I will have to spend time to look into it, which is bit hard for me to do now.

**Comment by Huffyphenix** [comment]
Ok, thanks for your help and patience.
