### ISSUE TITLE
resizing oncoplots

### ISSUE THREAD

**Issue by HiraDatascience** [PoisonAlien/maftools#990]
![issue](https://github.com/PoisonAlien/maftools/assets/62106499/c2f37399-7288-4a96-a333-d06d3d42423f)
![issue](https://github.com/PoisonAlien/maftools/assets/62106499/353b1c1b-5af7-40a3-8d25-6b9f84daf27a)

I am trying to create onco plots and pathway analysis in R studio. But plots comes out like this. i am only able to see the colors stripes better if i zoom it. if i save it as pdf from r studio its like this all blank.
how can i customize its size to make it publication quality. and how can i exclude samples with no mutations too to make it more compact and concentrated. 

session info:
```

R version 4.3.1 (2023-06-16 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 11 x64 (build 22621)  Matrix products: default   locale: [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    [3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                           [5] LC_TIME=English_United States.utf8      time zone: Europe/Stockholm tzcode source: internal  attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] dplyr_1.1.3     maftools_2.18.0  loaded via a namespace (and not attached):  [1] vctrs_0.6.4         cli_3.6.1           rlang_1.1.2         generics_0.1.3      data.table_1.14.8    [6] glue_1.6.2          hms_1.1.3           fansi_1.0.5         grid_4.3.1          tibble_3.2.1        [11] tzdb_0.4.0          lifecycle_1.0.3     BiocManager_1.30.22 DNAcopy_1.76.0      compiler_4.3.1      [16] RColorBrewer_1.1-3  pkgconfig_2.0.3     rstudioapi_0.15.0   R.oo_1.25.0         R.utils_2.12.2      [21] lattice_0.21-8      R6_2.5.1            readr_2.1.4         tidyselect_1.2.0    utf8_1.2.4          [26] pillar_1.9.0        splines_4.3.1       magrittr_2.0.3      R.methodsS3_1.8.2   Matrix_1.5-4.1      [31] withr_2.5.2         tools_4.3.1         survival_3.5-5
--
```
 
> | >
>

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the late reply. Your cohort is too big to visualize and hence the grids get too small.
You need to save the plot to a pdf with enough width and height to see the details.  Set `removeNonMutated = TRUE` to exclude..
