### ISSUE TITLE
Issue with importing GISTIC data into maftools

### ISSUE THREAD

**Issue by kbrar4013** [PoisonAlien/maftools#993]
Hi,

I ran GISTIC 2.0 on copy-number data for a set of approximately 100 samples. I have all the files from the GISTIC output and the tool itself seems to have run without issue; I can open all the resulting files and the formatting seems to be correct without issue. 

When importing the files into maftools in R, I get the following error output "cannot cast an empty data table":

<img width="829" alt="Screenshot 2023-12-06 at 3 18 49 PM" src="https://github.com/PoisonAlien/maftools/assets/23220359/ffa7727a-1553-4968-a563-9def7c5d9a77">

Any help would be appreciated, as I'm not sure what is causing this issue. Thanks.

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the issue. Would it be possible to share a reproducible example?
