### ISSUE TITLE
The issue of nonframeshift (block) substitution in annovarToMaf

### ISSUE THREAD

**Issue by ftian9** [PoisonAlien/maftools#994]
In annovarToMaf.R, "nonframeshift block substitution" and "nonframeshift substitution" will be parsed as "Inframe_INDEL":
https://github.com/PoisonAlien/maftools/blob/master/R/annovarToMaf.R#L107-L108

However, in some cases, it should be parsed as "Missense_Mutation".
For example (vcf format in hg19):
> chr17 37879601 . TT AA . . .

The VEP result:
![image](https://github.com/PoisonAlien/maftools/assets/134106614/c144af48-84de-4af0-b876-0ced90cc99f3)

**Comment by PoisonAlien** [comment]
Hi,

Could you please provide a reproducible example file?
