### ISSUE TITLE
an splice_region variant does not appear in the oncoplot

### ISSUE THREAD

**Issue by FerTalavera** [PoisonAlien/maftools#998]
Hi, I have a splice region variant (deletion) that does not appear in the oncoplot. I have tried with other variants of the same type, and the same occurs. I also already checked the MAF file, and the variants are there. Is this an issue with the package?

**Comment by PoisonAlien** [comment]
Hi,

It's hard to guess the problem. Could you please provide a reproducible example?

**Comment by FerTalavera** [comment]
Hi,

I've attached a maf that contains a splice region variant in Khsrp but it does not appear in the oncoplot as you can see in the image.

I'll appreciate your help.

Bw,

Fernanda Talavera
________________________________
De: Anand Mayakonda ***@***.***>
Enviado: jueves, 4 de enero de 2024 02:02 a. m.
Para: PoisonAlien/maftools ***@***.***>
Cc: MARIA FERNANDA TALAVERA CRUZ ***@***.***>; Author ***@***.***>
Asunto: Re: [PoisonAlien/maftools] an splice_region variant does not appear in the oncoplot (Issue #998)


Hi,

It's hard to guess the problem. Could you please provide a reproducible example?

**Comment by PoisonAlien** [comment]
Hi,

The attachment seems to be missing. Could you please try again?

**Comment by FerTalavera** [comment]
Sure, here I attached it again.
________________________________
De: Anand Mayakonda ***@***.***>
Enviado: viernes, 5 de enero de 2024 01:56 a. m.
Para: PoisonAlien/maftools ***@***.***>
Cc: MARIA FERNANDA TALAVERA CRUZ ***@***.***>; Author ***@***.***>
Asunto: Re: [PoisonAlien/maftools] an splice_region variant does not appear in the oncoplot (Issue #998)


Hi,

The attachment seems to be missing. Could you please try again?

**Comment by PoisonAlien** [comment]
Hi,
Unfortunately, I still can not see the attachment.

**Comment by FerTalavera** [comment]
Hi, are you seeing these messages in your email inbox or on GitHub?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by PoisonAlien** [comment]
Hi,

I checked both. There is no attachement. You can [email](anandmt3@gmail.com) if you would like.

**Comment by FerTalavera** [comment]
Hi,

Thanks, I just sent it to your email, I hope you can see it now.
________________________________
De: Anand Mayakonda ***@***.***>
Enviado: domingo, 7 de enero de 2024 10:41 a. m.
Para: PoisonAlien/maftools ***@***.***>
Cc: MARIA FERNANDA TALAVERA CRUZ ***@***.***>; Author ***@***.***>
Asunto: Re: [PoisonAlien/maftools] an splice_region variant does not appear in the oncoplot (Issue #998)


Hi,

I checked both. There is no attachement. You can ***@***.***> if you would like.

**Comment by PoisonAlien** [comment]
Thanks. I received the file. I will get back to you soon.

**Comment by FerTalavera** [comment]
Ok :) thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by PoisonAlien** [comment]
Hi,
Thanks for the file again. `Splice_Region` variants are considered silent since they are of [LOW functional impact](http://www.ensembl.org/info/genome/variation/prediction/predicted_data.html). If you would still like to include them, you can just define your variant classifications to be considered nonsynonymous while importing the MAF file.

´´´r
vc.nonSilent = c("Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site", "Translation_Start_Site",
                     "Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del",
                     "In_Frame_Ins", "Missense_Mutation", "Splice_Region")

m = maftools::read.maf(maf = "~/Downloads/all_mafs_merged.maf", vc_nonSyn = vc.nonSilent)
´´´

I hope this helps. 

P.S: Mouse genomes are not fully supported in maftools. Please be careful with some analyses.

**Comment by FerTalavera** [comment]
Oh, ok, I'll try that. Thank you so much for your help and the heads-up regarding mouse genome compatibility. :)
________________________________
De: Anand Mayakonda ***@***.***>
Enviado: domingo, 7 de enero de 2024 12:07 p. m.
Para: PoisonAlien/maftools ***@***.***>
Cc: MARIA FERNANDA TALAVERA CRUZ ***@***.***>; Author ***@***.***>
Asunto: Re: [PoisonAlien/maftools] an splice_region variant does not appear in the oncoplot (Issue #998)


Hi,
Thanks for the file again. Splice_Region variants are considered silent since they are of LOW functional impact<http://www.ensembl.org/info/genome/variation/prediction/predicted_data.html>. If you would still like to include them, you can just define your variant classifications to be considered nonsynonymous while importing the MAF file.

´´´r
vc.nonSilent = c("Frame_Shift_Del", "Frame_Shift_Ins", "Splice_Site", "Translation_Start_Site",
"Nonsense_Mutation", "Nonstop_Mutation", "In_Frame_Del",
"In_Frame_Ins", "Missense_Mutation", "Splice_Region")

m = maftools::read.maf(maf = "~/Downloads/all_mafs_merged.maf", vc_nonSyn = vc.nonSilent)
´´´

I hope this helps.

P.S: Mouse genomes are not fully supported in maftools. Please be careful with some analyses.
