### ISSUE TITLE
Cannot use function named "coGisticChromPlot"

### ISSUE THREAD

**Issue by XinpeiYi** [PoisonAlien/maftools#999]
Hi, I attempted to use the 'coGisticChromPlot' function in the 'maftools' package. Could you please guide me on how to use it? Thank you.

**Comment by PoisonAlien** [comment]
Hi,

You would need two gitsic objects to use the function. 

Import the GISTIC output with `readGistic` function and pass it to `coGisticChromPlot`

example:

```r
# path to GISTIC output
gistic_res_folder1 <- "/path/to/gistic1/
gistic_res_folder2 <- "/path/to/gistic2/

# Read in the results
g1 = readGistic(gisticDir = gistic_res_folder1)
g2 = readGistic(gisticDir = gistic_res_folder2)

# Compare
coGisticChromPlot(gistic1 = g1, gistic2 = g1, g1Name = "cohort1", g2Name = "cohort2", type = 'Amp')
```

I hope this helps.

**Comment by XinpeiYi** [comment]
Thanks for your reply. But I cannot install the newest version of maftools. Is it installed using the Github link?
